from pathlib import Path
import json,hashlib,os,stat
D=Path(__file__).resolve().parent;H=lambda b:hashlib.sha256(b).hexdigest()
def put(n,o):(D/n).write_text(json.dumps(o,sort_keys=True,indent=2)+'\n')
for name in ['COMPONENT01','FIVE01','COHORT01','ORIGINAL_REPLAY01','ADVERSARIAL01','AUTHENTICATION01']:assert (D/(name+'.stderr')).read_bytes()==b''
assert json.loads((D/'REPLAY_CONTROLS01.json').read_bytes())['checks']==105
assert len(json.loads((D/'FIVE_REFUSALS01.json').read_bytes()))==10 and len(json.loads((D/'COHORT_REPLAY01.json').read_bytes()))==6 and len(json.loads((D/'ADVERSARIAL01.json').read_bytes()))==41
profile_name='COMPLETED_REMOTE03_READ_ONLY_SELECTED_MODE_PROFILE01.json';profile=json.loads((D/profile_name).read_bytes());I=Path(profile['actual_receiver_root']);assert all(not os.path.lexists(I/n) for n in ['FLAT_INTENT01.json','FLAT_RECOVERY01.json','FLAT_FAILED01.json','flat-operational-delta01','flat-failed-remote02-01'])
report='''# Exact completed-receiver input-mode source successor04

Status: concrete source prepared for different-author review. Source17f4ee85d2408cdc1b678e107e82b6e19b674b4b941f1fa51f40f17bbedef282 is not installed or released. No actual Root restoration or new accepted authority is created.

## Explicit operational deviation

Completed remote03 was independently accepted for actual bytes while flat entry remained withheld under RM1. Its original selected root and three intermediate directories are0775; its three leaf bundle directories are0700, and all15 files are0600. Original receiver mkdir(parents=True) created those intermediate modes. They are preserved literally. No chmod, rename, new receiver identity, terminal-root replay, fake receipt or rewriting of permission history occurs.

This candidate allows that exact completed selected input tree to be read under its authenticated original modes. It does not call those directories private0700, exclude their writers, or widen the permission policy for arbitrary roots. Every new owned flat output directory/file remains strictly0700/0600. This is a named operational input-mode deviation, not a scientific-method change or resource-cap increase.

## Concrete implementation

Three literal metadata dependencies are added to the import-time pin table and to the final verified byte cohort: COMPLETED_REMOTE03_READ_ONLY_SELECTED_MODE_PROFILE01.json (d238a238...), COMPLETED_REMOTE_REVIEW_MACHINE01.json (26216031...) and COMPLETED_REMOTE_REVIEW_MANIFEST01.json (231ae543...). These are literal copies of actual Root profile and genuine different-author outcome review, not invented receipts. A future installed source requires all three beside restore01.py; Root alone performs installation and exact installed-entry review.

Before enabling input modes, VerifiedCohort.bind_completed_selected_profile hashes the literal profile; binds the exact absolute completed receiver and selected-root paths; validates owner1000 and the exact7 directory/15 file mapping; validates the full canonical typed manifest projection; rereads and hashes the actual remote receipt64c74556, selectiond2f64, and Root exit0f0eba; and compares the caller's parsed receipt/selection against the actual canonical bytes. The copied outcome machine/manifest hashes and machine membership are joined. Its original ACCEPTED_ACTUAL_REMOTE_BYTES_WITHHELD_FLAT_ENTRY_RM1 decision and false flat/numerical flags remain unchanged. The profile enables read-only component verification; it is not an entry grant.

Only paths inside that authenticated fixed selected tree obtain their exact listed original input modes. Every selected signature also enforces the observed owner and exact type/mode/member population. Every other root retains the original private0700 anchor rule. The original file-mode/extent/link checks, canonical paths, full metadata fingerprints, exact membership, all byte/SHA/Git OID joins, actual receipt/selection predicates, whole-tree bounds and fatal cleanup remain. Selected directory and file fingerprints stay in the same final cohort: complete enumerations and iterator cleanup precede the descriptor-free rejoin, and prerequisite/profile/review/exit bytes are included. The final prospective flat receipt names the bound input-mode profile hash and distinguishes original input modes from private output modes.

The complete nine-edit literal inverse reproduces source03 6d7688080efb716b7a79d1291b4f27e62e0315e5d7a8153b2890d1f9fab35214. AST comparison identifies only VerifiedCohort, authenticate_selected and run as changed definitions, plus the declared PINS assignment. All other functions and all three primitive dependencies/watch04 are byte/AST unchanged. Limits remain64MiB logical,96MiB allocated,4MiB per file,32768 members,depth32,10GiB floor, original five-second resource census and180-second/64-boundary flat execution envelope. Watch04 is a pinned independently accepted dependency; it is not re-reviewed by its author here.

## Actual read-only and synthetic evidence

COMPONENT01 uses the authentic current completed Root03 receipt and selected bytes. Exact original03 reproduces RM1 "cohort root private owner/mode". Candidate04 verifies all15 records/507946 bytes,21 prerequisite/selected byte proofs,28 full member pins and the exact7 original directory modes. A final cohort rejoin passes. Original selected full signatures, modes, bytes, receipt and selection remain unchanged. No public actual Root restoration, main or entry is invoked.

ADVERSARIAL01 retains41 new controls: wrong root, hash, receipt/selection context, altered profile, altered supporting review/exit bytes, observed UID/mode/type/device/extent/mtime drift, changed membership, unknown directories, deadline/member limits and genuine owned private-output regressions. Read substitutions and lstat metadata overlays are explicitly synthetic and never modify the actual completed input tree. Genuine owned output roots0775/0755/0777, wrong file mode, symlink, hardlink, extra member and wrong child-directory mode refuse even with the genuine profile bound.

All five inherited real stale-cleanup cases (earlier bytes, mode, foreign name, metadata and cross-scope) still refuse on both original03 and candidate04, yielding10 retained comparisons. Six additional cohort/currentness controls pass. The inherited105 opaque local controls pass, including actual64-body/two-metadata owned roundtrip, exact canonical archives, primitive framing/type refusals, nine real descriptor/fatal pairs, and retention of a complete first scope after a second partial-write fatal. This replay includes the original run(None,None) first-pin refusal; it does not reach intent, actual Root output or restoration execution. Its restoration components run only on owned local fixtures. Together the two actual-component observations,41 new controls,10 stale comparisons,6 cohort controls and105 inherited controls retain164 result rows.

AUTHENTICATION01 independently authenticates2399 declared original members:1726 prior-source members,608 different-author flat03 review members and65 actual remote-outcome review members. Prior source/review/failed harness evidence remains unchanged. Original RM1 stderr is copied literally. The original remote outcome review's recommended private-mode preparation is preserved as historical advice; this separately declared Root-authorized source correction instead binds the unchanged original read-only modes. No earlier receipt or conclusion is rewritten.

## Remaining authority and limits

Different-author full-source review, exact installed source/metadata closure, an exact one-use flat caller/entry review, actual restoration and independent recovered-byte acceptance remain mandatory. Original Root03 is terminal as a remote invocation; it is not replayed. The new action, if separately released, is the distinct flat phase. Old Root02 remains FAILED/spent with observed init exit null, separate reap0, Root exit1 and unknown changed path/field. No budget refund, new numerical identity, registration or ledger mutation occurs.

A mode profile authenticates an observed input graph; it does not prevent another same-owner/group writer. The checks are finite sampled currentness, not continuous atomicity, immutable storage, same-signature ABA protection, a kernel quota or a full-capacity claim. Actual final Root terminal/sidecar and composed recovery remain separately reviewed. Old385 Git/failed171 byte recovery, final Parent/caller/gate and runtime-package preservation, scientific methods/results and economic timing/returns/fees/funding/exposure are outside this source preparation. No network, numerical library, checkpoint decoder, Run/Owner or research claim was used.
'''
(D/'REPORT01.md').write_text(report)
put('INSTALLATION_REQUIREMENTS01.json',{'schema_version':1,'source_only_not_an_entry_release':True,'receiver_root':profile['actual_receiver_root'],'restore_helper':{'file':'restore01.py','sha256':H((D/'restore01.py').read_bytes())},'new_exact_metadata_dependencies':{n:{'bytes':(D/n).stat().st_size,'sha256':H((D/n).read_bytes())} for n in [profile_name,'COMPLETED_REMOTE_REVIEW_MACHINE01.json','COMPLETED_REMOTE_REVIEW_MANIFEST01.json']},'unchanged_dependencies':{n:H((D/n).read_bytes()) for n in ['watch01.py','utilities/recovery_pax01.py','utilities/owned_io.py','utilities/bounded_git01.py']},'actual_remote_receipt_sha256':profile['actual_remote_receipt_sha256'],'actual_root_exit_sha256':profile['actual_Root_exit_sha256'],'actual_selection_sha256':profile['selection_sha256'],'new_owned_flat_directory_mode':448,'new_owned_flat_file_mode':384,'actual_root_installation':None,'actual_entry_release':None})
put('MACHINE01.json',{'schema_version':1,'decision':'PREPARED_EXACT_COMPLETED_RECEIVER_READ_ONLY_MODE_PROFILE_SOURCE','source_sha256':H((D/'restore01.py').read_bytes()),'original_source_sha256':H((D/'ORIGINAL_restore01.py').read_bytes()),'profile_sha256':H((D/profile_name).read_bytes()),'actual_completed_remote_receipt_sha256':profile['actual_remote_receipt_sha256'],'actual_completed_remote_outcome_review_sha256':profile['actual_remote_outcome_review_sha256'],'actual_completed_root_exit_sha256':profile['actual_Root_exit_sha256'],'original_actual_selected_modes_preserved':True,'actual_component_original_RED_candidate_GREEN':True,'original_selected_directories':7,'original_selected_files':15,'original_selected_bytes':507946,'exact_literal_inverse_edits':len(json.loads((D/'SOURCE_INVERSE01.json').read_bytes())['edits']),'changed_definitions':['VerifiedCohort','authenticate_selected','run'],'original_three_primitives_and_watch_unchanged':True,'new_adversarial_controls':41,'inherited_stale_cleanup_comparisons':10,'inherited_cohort_controls':6,'inherited_local_primitive_controls':105,'actual_component_observations':2,'total_result_rows':164,'authenticated_historical_members':2399,'private_new_output_modes':[448,384],'independent_review':None,'actual_installation':None,'actual_flat_entry_release':None,'actual_flat_recovery':None,'numerical_authority':False,'report_sha256':H((D/'REPORT01.md').read_bytes()),'installation_requirements_sha256':H((D/'INSTALLATION_REQUIREMENTS01.json').read_bytes()),'qualification':'Explicit fixed completed-input mode deviation only; no generic public graph allowance, original mode mutation, writer exclusion or new authority.'})
rows=[]
def walk(p):
 for x in sorted(p.iterdir()):
  if x==D/'MANIFEST01.json':continue
  s=x.lstat();r={'path':str(x.relative_to(D)),'mode':stat.S_IMODE(s.st_mode)}
  if stat.S_ISDIR(s.st_mode):r['kind']='directory';rows.append(r);walk(x)
  elif stat.S_ISREG(s.st_mode):r.update(kind='file',bytes=s.st_size,sha256=H(x.read_bytes()),nlink=s.st_nlink);rows.append(r)
  elif stat.S_ISLNK(s.st_mode):r.update(kind='symlink',target=os.readlink(x));rows.append(r)
  else:raise AssertionError(x)
walk(D);put('MANIFEST01.json',{'schema_version':1,'root_mode':stat.S_IMODE(D.stat().st_mode),'members':rows,'retained_negative_symlink_and_hardlink_fixtures':True})
print(json.dumps({n:H((D/n).read_bytes()) for n in ['restore01.py','MACHINE01.json','REPORT01.md','MANIFEST01.json','INSTALLATION_REQUIREMENTS01.json']}));print(json.dumps({'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'bytes':sum(r.get('bytes',0) for r in rows)}))
