import hashlib,json,stat
from pathlib import Path
D=Path(__file__).resolve().parent;F=D.parent;T=F/'financial-wrapper-claimedrun-failed-remote01-2026-10-04';C=F/'financial-wrapper-claimedrun-failed-capture01-2026-10-04';H=F/'heartbeat-root-checkpoint10-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();enc=lambda v:(json.dumps(v,sort_keys=True,indent=2)+'\n').encode();a=json.loads((D/'READBACK01.json').read_bytes());b=json.loads((D/'READBACK02.json').read_bytes());count=a['checks']+b['checks']
e=D/'original-metadata';e.mkdir()
for p in [T/'FLAT_RECOVERY01.json',T/'FLAT_INTENT01.json',T/'REMOTE_RECOVERY01.json',T/'SELECTED_BODIES01.json',C/'CAPTURE01.json',H/'ROOT_FAILED_FLAT01_EXIT.json',H/'ROOT_FAILED_FLAT01_INTENT.json',H/'ROOT_FAILED_FLAT01.stdout',H/'ROOT_FAILED_FLAT01.stderr']:(e/p.name).write_bytes(p.read_bytes())
for role in ('capsule','parent','root'):(e/(role+'-flat-metadata.json')).write_bytes((T/('flat-'+role+'01')/'body-metadata.json').read_bytes())
m={'schema_version':1,'decision':'ACCEPTED_COMPLETE_ACTUAL_FAILED_OUTCOME_BYTE_RECOVERY','identity':'financial-wrapper-classification-eager-interrupt1-claimedrun-20261004-01','source':a['source'],'capture_sha256':a['capture_sha256'],'remote_receipt_sha256':a['remote_sha256'],'flat_receipt_sha256':a['flat_sha256'],'root_flat_actual_exit_sha256':a['root_actual_exit_sha256'],'remote_review_manifest_sha256':a['remote_review_manifest_sha256'],'checks':count,'original_typed_members':483,'original_regular_bodies':402,'actual_private_files_including_metadata':405,'current_source_Git_bodies':339,'registered_source_pins':338,'input_roles':8,'runtime_RECORD_metadata_pins':251,'checkpoint_state_sha256':a['checkpoint_sha256'],'checkpoint_state_bytes':a['checkpoint_bytes'],'checkpoint_decoded':False,'spent_claims':2,'highest_actual_allowance':19,'outcome':'FAILED_PlannedInterruption','original_parent_actual_exit':None,'separate_actual_engineering_outer_exit':1,'actual_byte_restore_exit':0,'paper_fit_credit':0,'whole_fit_capacity':False,'runtime_package_body_backup':False,'posix_tree_reproduction':False,'new_numerical_or_replay_release':False,'flat_original_OS_PID_history_recorded':False,'qualification':'Complete actual external-to-flat closure of exact captured non-Git Source339 FAILED capsule, complete Parent and six selected Root outcome files. Previously recovered original Git objects are a separate chain. This is byte preservation only.'}
(D/'MACHINE01.json').write_bytes(enc(m))
(D/'REPORT01.md').write_text('''# Complete actual FAILED outcome byte recovery

**Accepted the complete actual recovery of the exact captured failed outcome scope.** There are 3,364 independent checks. All402 original regular bodies and three canonical metadata files are present as405 private0600 single-link files with no extras. They preserve all483 original typed member names, modes and empty directories as metadata: capsule443/367 files, Parent34/29, and six named Root outcome files.

Every actual recovered body matches its original and snapshot hash/extent/bytes; sorted mapping and complete current original membership are exact. Each reconstructed canonical gzip/TAR archive is byte-identical to the actual fresh external Git blob, saved selected body and original capture. All eight selected external OIDs/modes were reread from the actual fetched bare Git store using bounded local no-replace Git, with no network. The unchanged accepted remote-review59c2 seal, all original evidence and its initial FETCH_HEAD harness failure remain intact. The402 flat body files and metadata inodes were checked again after validation.

All339 current Source0a2 Git tree/blob bodies are recovered. The actual claim's338 source pins, seven runtime API sources and eight input roles match recovered bytes. All251 runtime RECORD metadata pins are present; installed RECORD/package bodies are not thereby backed up or validated. The genuine claimedrun claimd390 and failed4b2 bind unchanged, preserving permanent FAILED PlannedInterruption after one update, no fit completion. Both genuine retained claims remain FAILED, spent2/highest actual19, no COMPLETE marker. Opaque checkpoint223ced42 is exactly493,424 bytes; only byte hashes were read, with no tensor/checkpoint deserialization or numerical imports.

The original Parent actual_parent_exit remains null. Its genuine child/outer1 and the separate observed Root outer1 are not rewritten. The new byte restore tool737925 returned0 and its actual receipt e53f91 is joined to Root exitb3ea38, original intent and raw streams. All seven recorded floors exceed10GiB within120 sampled seconds. Recorded original remote/native/control PIDs/groups and cgroup are currently absent. The ordinary flat caller did not record its original OS PID/start ticks: no complete PID history or synthetic absence proof is invented for it.

This closes the exact captured non-Git Source339 FAILED capsule, complete Parent and six selected Root outcomes. Original Git objects were excluded from this new capsule archive and remain covered by the separate preceding Source339 recovery. Root's broader heartbeat directory is not claimed recovered. Original helper flags—no POSIX instantiation, no installed runtime-body backup, no outside-store recovery, no independent research authority—remain unchanged. No new numerical phase, replay, paper fit credit, retirement, whole-fit capacity or native release follows from this byte-preservation acceptance.
''')
rows=[]
for p in [D]+sorted(D.rglob('*')):
 if p.name=='MANIFEST01.json':continue
 s=p.lstat();r={'path':'.'if p==D else p.relative_to(D).as_posix(),'mode':stat.S_IMODE(s.st_mode),'kind':'directory'if p.is_dir()else'file'}
 if r['kind']=='file':r.update(bytes=s.st_size,sha256=sha(p.read_bytes()))
 rows.append(r)
(D/'MANIFEST01.json').write_bytes(enc({'schema_version':1,'self_excluded':True,'members':rows}));print(json.dumps({'machine_sha256':sha((D/'MACHINE01.json').read_bytes()),'manifest_sha256':sha((D/'MANIFEST01.json').read_bytes()),'members':len(rows),'checks':count}))
