from pathlib import Path
import json,hashlib,subprocess,datetime,os
R=Path('/home/malecada/master_thesis/TradingAgents-audit-fixes');F=R/'research/onchain-paper-replication-2026-09-24/full_sources';A=F/'financial-wrapper-compatibility-operational-delta-remote-successor02-2026-10-04';V=F/'financial-wrapper-compatibility-operational-delta-remote-review02-2026-10-04';D=F/'financial-wrapper-compatibility-operational-delta-root-remote03-2026-10-04';h=lambda b:hashlib.sha256(b).hexdigest();HEAD='4d0dbef40c978788ec9ddd9a5e4f4c2d18c52714'
assert subprocess.check_output(['git','rev-parse','HEAD'],cwd=R,text=True).strip()==HEAD
assert h((V/'MACHINE01.json').read_bytes())=='bd33dac061d5a7dba3f7f9e1dd38f194770f66f6f37c487ba76d2e1eeefd5b02';assert h((V/'MANIFEST01.json').read_bytes())=='7b2a32464feaf8a95467dad2274d14b13154bd3f09fca447c72b952ff58e8714'
required=json.loads((A/'SOURCE_INVERSE01.json').read_bytes())['REQUIRED15'];assert len(required)==15;objects=[]
for name,pin in sorted(required.items()):
 body=(R/name).read_bytes();assert len(body)==pin['bytes'] and h(body)==pin['sha256'];raw=subprocess.check_output(['git','show',HEAD+':'+name],cwd=R);assert raw==body;objects.append(hashlib.sha1(b'blob '+str(len(body)).encode()+b'\0'+body).hexdigest())
assert len(set(objects))==15 and sum(p['bytes'] for p in required.values())==507946
assert not os.path.lexists(D);D.mkdir(mode=0o700);(D/'utilities').mkdir(mode=0o700)
for name in ('recover01.py','watch01.py','utilities/owned_io.py','utilities/bounded_git01.py','utilities/recovery_pax01.py'):(D/name).write_bytes((A/name).read_bytes())
sel={'remote_commit':HEAD,'rows':[dict(path=p,**pin) for p,pin in sorted(required.items())]};(D/'SELECTED_BODIES01.json').write_text(json.dumps(sel,sort_keys=True,indent=2)+'\n')
files={name:{'sha256':h((D/name).read_bytes()),'bytes':(D/name).stat().st_size} for name in ('recover01.py','watch01.py','utilities/owned_io.py','utilities/bounded_git01.py','utilities/recovery_pax01.py','SELECTED_BODIES01.json')}
draft={'schema_version':1,'time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'INSTALLED_SOURCE_DRAFT_NOT_EXTERNAL_ENTRY_RELEASED','owned_root':str(D),'source_main_commit':HEAD,'source_review':{'path':str(V/'MACHINE01.json'),'sha256':h((V/'MACHINE01.json').read_bytes())},'source_review_manifest_sha256':h((V/'MANIFEST01.json').read_bytes()),'helpers_and_selection':files,'required_count':15,'required_bytes':507946,'distinct_expected_git_blobs':15,'expected_operations':55,'fresh_namespaces':['fresh-operational-source-policy02.git','selected','flat-operational-delta01','flat-failed-remote02-01'],'prior_consumed_failure':{'root':str(F/'financial-wrapper-compatibility-operational-delta-root-remote02-2026-10-04'),'failed_sha256':'7491cc3c1940b68cab9b218e972a13c925f5ce1ff21d9f0a2f32ee416246268a','disposition':'PERMANENT_FAILED_NEVER_REPLAY'},'flat_helper_installed':False,'actual_recovery':None,'exact_installed_entry_review':None,'qualification':'One fresh remote transfer only may be separately released. Flat03 peer acceptance/installed review, actual remote acceptance, actual two-scope flat restoration/recovery and complete independent composition remain separate. No NUM/claim/paper fit or capacity authority.'}
(D/'ROOT_INSTALLATION_DRAFT01.json').write_text(json.dumps(draft,sort_keys=True,indent=2)+'\n');print(json.dumps({'selection':files['SELECTED_BODIES01.json']['sha256'],'draft':h((D/'ROOT_INSTALLATION_DRAFT01.json').read_bytes()),'root':str(D),'main':HEAD}))
