"""One fresh actual current byte-increment restoration; accepted R4 unchanged."""
from pathlib import Path
import sys,json,hashlib,shutil
ROOT=Path(__file__).resolve().parents[4];F=ROOT/'research/onchain-paper-replication-2026-09-24/full_sources';P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-continue100-serialized-storage-root-launch-20261005-01');REMOTE=F/'financial-wrapper-serialized-storage-current-remote01-2026-10-05';PREFIX='research/onchain-paper-replication-2026-09-24/full_sources/financial-wrapper-serialized-storage-current-capture01-2026-10-05';OUT=F/'financial-wrapper-serialized-storage-current-flat01-2026-10-05'
assert hashlib.sha256((P/'recovery04.py').read_bytes()).hexdigest()=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a';sys.path.insert(0,str(P));import recovery04 as R
archive=REMOTE/'selected'/PREFIX/'increment.tar.gz';manifest=REMOTE/'selected'/PREFIX/'archive-manifest.json';capture=REMOTE/'selected'/PREFIX/'CAPTURE01.json';receipt=json.loads(R.read(REMOTE,'REMOTE_RECOVERY01.json'));assert receipt['remote_commit']=='33219f465c3d8863f98a0d008dc423ab3b7fb791' and receipt['selected_count']==8 and receipt['selected_logical_bytes']==660098 and len(receipt['operations'])==34;assert all(r['actual_reaped_exit']==0 and r['cleanup_failures']==[] and r['actual_child_limits']=={'pid':r['pid'],'fsize':[4194304,4194304]} for r in receipt['operations']);refs={r['path']:r for r in receipt['selected_blobs']}
for p in (archive,manifest,capture):
 n=p.relative_to(REMOTE/'selected').as_posix();b=R.read(p.parent,p.name);assert len(b)==refs[n]['bytes'] and R.digest(b)==refs[n]['sha256']
assert R.digest(R.read(archive.parent,archive.name))=='61365ba16c8561b4ebbe17e1b8ac23e9b31261e9e87cda775019ff09ce625995';record=json.loads(R.read(capture.parent,capture.name));m=json.loads(R.read(manifest.parent,manifest.name));assert record['new_original_bodies']==93 and record['new_original_bytes']==1871149 and len(m['members'])==94 and record['CAP_regular']==856 and record['CAP_typed']==1088 and record['Git_logical_objects']==454 and record['Parent_regular']==11
assert not OUT.exists() and shutil.disk_usage(F).free>=10*1024**3;OUT.mkdir(mode=0o700);(OUT/'flat').mkdir(mode=0o700);result=R.restore(archive,record['archive'],m,OUT/'flat');assert result['regular_bodies']==94
R.put(OUT/'RECOVERY01.json',{'schema_version':1,'status':'ACTUAL_CURRENT_SERIALIZED_STORAGE_FLAT_BYTE_RECOVERY','receiver_receipt_sha256':R.digest(R.read(REMOTE,'REMOTE_RECOVERY01.json')),'capture_sha256':R.digest(R.read(capture.parent,capture.name)),'archive_sha256':record['archive']['sha256'],'manifest_sha256':R.digest(R.read(manifest.parent,manifest.name)),'primitive':result,'new_original_bodies':93,'new_original_bytes':1871149,'CAP_regular':856,'CAP_typed':1088,'Git_logical_objects':454,'Parent_regular':11,'accepted_unchanged_basis':record['basis'],'numerical_or_paper_fit_authority':False,'runtime_bodies_recovered':False,'POSIX_reconstruction':False,'immutable_writer_exclusion':False,'released_envelope_recovered':False});assert shutil.disk_usage(OUT).free>=10*1024**3;print(json.dumps({'status':'CURRENT_INCREMENT_BYTE_RECOVERED','regular_bodies':94,'recovery_sha256':R.digest(R.read(OUT,'RECOVERY01.json'))}))
