"""One fresh failed-receiver byte recovery, unchanged accepted R4 PAX primitive."""
from pathlib import Path
import sys,json,hashlib,shutil
ROOT=Path(__file__).resolve().parents[4];F=ROOT/'research/onchain-paper-replication-2026-09-24/full_sources';P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-continue100-resource-successor-root-launch-20261005-01');REMOTE=F/'financial-wrapper-serialized-storage-source-remote03-2026-10-05';PREFIX='research/onchain-paper-replication-2026-09-24/full_sources/financial-wrapper-serialized-storage-source-failed-capture01-2026-10-05';OUT=F/'financial-wrapper-serialized-storage-source-failed-flat01-2026-10-05'
assert hashlib.sha256((P/'recovery04.py').read_bytes()).hexdigest()=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a';sys.path.insert(0,str(P));import recovery04 as R
archive=REMOTE/'selected'/PREFIX/'failed-source-receiver.tar.gz';manifest=REMOTE/'selected'/PREFIX/'archive-manifest.json';capture=REMOTE/'selected'/PREFIX/'CAPTURE01.json';receipt=json.loads(R.read(REMOTE,'REMOTE_RECOVERY01.json'));assert receipt['remote_commit']=='e1da0fbb4aa9ff21da9545575adbc0f2505991c4' and receipt['selected_count']==62 and len(receipt['operations'])==193;assert all(r['actual_reaped_exit']==0 and r['cleanup_failures']==[] for r in receipt['operations']);refs={r['path']:r for r in receipt['selected_blobs']}
for p in (archive,manifest,capture):
 n=p.relative_to(REMOTE/'selected').as_posix();b=R.read(p.parent,p.name);assert len(b)==refs[n]['bytes'] and R.digest(b)==refs[n]['sha256']
assert R.digest(R.read(archive.parent,archive.name))=='da7d27f13dd9c2ff3cf091252249ba9f43dd3cad87059321c53a758609e0d0ae';record=json.loads(R.read(capture.parent,capture.name));m=json.loads(R.read(manifest.parent,manifest.name));assert record['original_regular']==93 and record['original_typed']==104 and len(m['members'])==104 and record['original_last_exit'] is None and record['actual_last_reaped_exit']==-9 and record['new_source_byte_recovery_complete'] is False
assert not OUT.exists() and shutil.disk_usage(F).free>=10*1024**3;OUT.mkdir(mode=0o700);(OUT/'flat').mkdir(mode=0o700);result=R.restore(archive,record['archive'],m,OUT/'flat');assert result['regular_bodies']==93
R.put(OUT/'RECOVERY01.json',{'schema_version':1,'status':'ACTUAL_FAILED_SOURCE_RECEIVER_FLAT_BYTE_RECOVERY','receiver_receipt_sha256':R.digest(R.read(REMOTE,'REMOTE_RECOVERY01.json')),'capture_sha256':R.digest(R.read(capture.parent,capture.name)),'archive_sha256':record['archive']['sha256'],'manifest_sha256':R.digest(R.read(manifest.parent,manifest.name)),'primitive':result,'original_regular':93,'original_typed':104,'original_attempt_remains_failed':True,'namespace_reuse_authority':False,'numerical_or_paper_fit_authority':False,'runtime_bodies_recovered':False,'POSIX_reconstruction':False});assert shutil.disk_usage(OUT).free>=10*1024**3;print(json.dumps({'status':'FAILED_SOURCE_BYTE_RECOVERED','regular_bodies':93,'recovery_sha256':R.digest(R.read(OUT,'RECOVERY01.json'))}))
