"""Publish actual reviewed byte recovery; final native authority is additive."""
from pathlib import Path
import json,sys
H=Path(__file__).resolve().parent;F=H.parent
sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'))
from verify_capture01 import R
v=json.loads(R.read(H,'CANONICAL_RECOVERY_READBACK01.json'));remote=json.loads(R.read(H,'REMOTE_OUTCOME_READBACK01.json'))
def ref(name):return {'path':str(H/name),'sha256':R.digest(R.read(H,name))}
report='''# Actual canonical current byte recovery

Accepted actual one-use remote and flat outcomes. All19 receiver operations succeeded and were reaped; all three remote selected bodies match their reviewed canonical selection and Git objects. The actual returned PAX archive and restored112 opaque bodies match every byte, including111 preserved originals and COMPOSITION01. The original111 source/caller/proof/dependency/Git-tail bodies and their literal mode metadata join actual originals. The complete three dependency snapshots include the preserved withheld builder and real witness, actual static Parent review and genuine source/cumulative proofs; future additions to the open review are outside those frozen snapshots.

Full current composition is823 CAP regular/1,049 typed, the exact11-file source-bound DRAFT Parent,359 source pins/360 tracked paths/29 roles and422 logical Git objects. Accepted original821 CAP body hashes and416-object actual recovery basis97faaa53 are explicitly reused; only the exact two corrected CAP bodies and six new Git object bodies are newly reconstructed and checked. All six Git object type/OIDs and the actual422-object closure join. No old821-body or251-runtime scan is repeated.

The source-bound draft0ea7cf3d and source d4c remain exact. Both metadata entries completed actual Root0 and child0 with cleanup[]. Original inner Parent exit fields remain null. The flat's two recorded PIDs and group are absent; universal process history remains unknown.17,924 checks read5,382,485 bytes in0.320 seconds. Sampled flat maxima remain within the unchanged controls; the final observed tree was2,677,285 logical bytes,2,985,984 allocated bytes and152 members.

This is complete current SOURCE-BOUND-DRAFT BYTE recovery composed with genuine accepted ancestry, not a new empirical outcome. Installed runtime bodies, POSIX reconstruction, continuous writer exclusion, universal process history, post-capture bound transport helper bodies and whole capacity are excluded. Final request/release are later additive authority and must validate against this recovered draft; no recursive archive of their future proof is required. Actual public8MiB preflight and numerical entry remain unavailable. The prior metadata preflight failures do not consume or reopen a numerical claim.
'''
with (H/'CANONICAL_RECOVERY_REPORT01.md').open('x') as f:f.write(report)
scope={k:v[k] for k in ('archive_regular','archive_typed','archive_logical_bytes','saved_original_bodies','current_CAP_regular','current_CAP_typed','Parent_source_bound_draft_files','source_bound_draft_sha256','tracked','source_pins','input_roles','current_Git_logical_objects','changed_CAP_bodies','new_Git_objects')}
machine={'schema_version':1,'decision':v['decision'],'reviewer':'/root/storage_watch_review','source':v['source'],'design_source':v['source'],'identity':v['identity'],'capsule_root':v['capsule_root'],'parent_root':v['parent_root'],'scope':scope,'readback':ref('CANONICAL_RECOVERY_READBACK01.json'),'report':ref('CANONICAL_RECOVERY_REPORT01.md'),'prior_current_recovery':v['prior_current_recovery'],'actual_remote_receipt':{'path':str(F/'financial-wrapper-continuation-canonical-remote01-2026-10-05/REMOTE_RECOVERY01.json'),'sha256':remote['remote_receipt_sha256']},'actual_flat_receipt':{'path':str(F/'financial-wrapper-continuation-canonical-flat01-2026-10-05/LANE_RECOVERY01.json'),'sha256':v['flat_receipt_sha256']},'actual_Root_exit_sha256':v['actual_Root_exit_sha256'],'original_parent_exit':None,'old821_CAP_hashes_and416Git_basis_reused':True,'final_public_preflight_passed':False,'numerical_authority':False,'sampled_currentness_only':True,'installed_runtime_bodies':False,'POSIX_reconstruction':False,'whole_capacity':False}
R.put(H/'CANONICAL_RECOVERY_MACHINE01.json',machine)
proof={'schema_version':1,'kind':'full_recovery','decision':'accepted-current-source-bound-draft-byte-recovery','source':v['source'],'design_source':v['source'],'identity':v['identity'],'capsule_root':v['capsule_root'],'parent_root':v['parent_root'],'scope':scope,'prior_current_recovery':v['prior_current_recovery'],'old821_CAP_hashes_and416Git_basis_reused':True,'review':ref('CANONICAL_RECOVERY_MACHINE01.json'),'future_final_authority':'additive request/release must join recovered source-bound draft through exact Parent validators','excludes':['installed-runtime-package-bodies','post-capture-bound-transport-helper-bodies','POSIX-reconstruction','writer-exclusion','whole-capacity','future-numerical-entry'],'numerical_authority':False}
R.put(H/'CANONICAL_FULL_RECOVERY_PROOF01.json',proof)
print(json.dumps({'proof':ref('CANONICAL_FULL_RECOVERY_PROOF01.json'),'machine':ref('CANONICAL_RECOVERY_MACHINE01.json'),'report':ref('CANONICAL_RECOVERY_REPORT01.md')}))
