"""Actual installed Parent + exact changed-source/accounting metadata review.
Runtime evidence is explicitly reused; no public admission/numerical invocation.
"""
from pathlib import Path
import copy,json,os,sys
H=Path(__file__).resolve().parent;F=H.parent;B=F/'financial-wrapper-continuation-current-admission-review01-2026-10-05';P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-continue100-canonical-plan-root-launch-20261005-01');CAP=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');SOURCE='d4c81c0961342bfe4c5771aabbef1d46a14cffb8'
sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'))
from verify_capture01 import Reader,R
rd=Reader();release=json.loads(rd.read(H/'STATIC_PARENT_INSTALL_RELEASE01.json','c54ac71495a061c900e4cae0fbac8337d02912b3725ae9f3ff75f6477580f30c'));files=release['allowed_files'];scan=R.scan(P)
installation_ref={'path':str(F/'heartbeat-root-checkpoint10-2026-10-04/CANONICAL_PARENT_STATIC_INSTALL01.json'),'sha256':'7785cd893f41f93096b648f3fe10f0bb9ee9980e47ef4b0812dc08b11c1f5389'};installation=json.loads(rd.read(Path(installation_ref['path']),installation_ref['sha256']));rd.need(installation['installed']==files and installation['target']==str(P) and installation['source']==SOURCE and not any(installation[k] for k in ('builder_invoked','attempt','claim','numerical_authority')),'actual Root installation receipt and withheld builder disposition')
rd.need(scan['root_mode']==0o700 and len(scan['members'])==10 and set(files)=={r['path'] for r in scan['members']},'actual exact ten-body private Parent namespace')
for row in scan['members']:
 item=files[row['path']];rd.need(row['kind']=='file' and row['mode']==0o600 and row['bytes']==item['bytes'] and row['sha256']==item['sha256'],'actual candidate mode/extent/hash');rd.read(P/row['path'],item['sha256'])
q=json.loads(rd.read(P/'REQUEST_DRAFT01.json',release['request_sha256']));rd.need(q['parent_root']==str(P) and q['source']==q['design_source']==SOURCE and q['status']=='DRAFT_NOT_RELEASED' and q['final_review'] is None and all(v is None for v in q['proofs'].values()),'honest actual null authority draft')
head=rd.read(CAP/'.git/HEAD').decode().strip();actual=rd.read(CAP/'.git'/head[5:]).decode().strip() if head.startswith('ref: ') else head;rd.need(actual==SOURCE,'actual current committed source')
gate=json.loads(rd.read(CAP/q['registration'],q['registration_sha256']));e=gate['experiments'][q['identity']];rd.need(e['source_files']==q['source_files'] and len(q['source_files'])==359 and {k:v['sha256'] for k,v in e['inputs'].items()}==q['input_hashes'] and len(q['input_hashes'])==29,'actual current359 source and29 role maps')
oldsource_raw=rd.read(B/'SOURCE_INPUT_RUNTIME_PROOF01.json','18e4dcd06596478b8d338bd2b0b53cd6adcaca3f565fd85211ec591c335bb0d3');oldbudget_raw=rd.read(B/'CUMULATIVE_PROOF01.json','d0ae47f74f9d17c05ef974d6cfff422dd12957b608cb07144774b77498cc6f1f');oldsource=json.loads(oldsource_raw);oldbudget=json.loads(oldbudget_raw)
rd.read(B/'READBACK01.json','eba0659842864be8d8bc8aeff09ac201551758b8972cd001758d2d515ae9ab9d');rd.read(B/'MANIFEST01.json','2287f0cc82972ac71b56d804202f1a21c6f7f32ebfe453f1578a127446f55ee3');rd.read(B/'REPORT01.md','0734274e7fcfcba772511e621c499f39811f2d53e8160777ee36e44edbb5db22')
rd.need(q['runtime_mapping']==json.loads(rd.read(CAP/e['inputs']['runtime_mapping']['path'],oldsource['runtime_mapping_sha256'])),'same actual runtime metadata mapping; old251 verification reused')
for item in oldbudget['claims']:
 root=CAP/'research_runs'/item['identity'];claim=json.loads(rd.read(root/'claim.json',item['claim_sha256']));terminal=json.loads(rd.read(root/(item['status']+'.json'),item['terminal_sha256']));rd.need(claim['experiment_id']==terminal['experiment_id']==item['identity'] and claim['experiment']['family']==oldbudget['family'] and terminal['status']==item['status'] and terminal['claim_sha256']==item['claim_sha256'],'actual four historical claim/terminal joins unchanged');rd.need(not os.path.lexists(root/('complete.json' if item['status']=='failed' else 'failed.json')),'opposite terminal absent')
rd.need(oldbudget['spent_claims']==4 and oldbudget['complete']==1 and oldbudget['failed']==3 and oldbudget['remaining']==16 and oldbudget['highest_claim_allowance']==20 and e['family']==oldbudget['family'],'unchanged accounting denominator')
for value in oldbudget['cumulative_budget_extension'].values():rd.read(CAP/value['path'],value['sha256'])
rd.need(not os.path.lexists(P/'attempt') and not os.path.lexists(CAP/'research_runs'/q['identity']),'no new actual numerical attempt')
rd.finish()
readback={'schema_version':1,'decision':'ACCEPTED_ACTUAL_CANONICAL_PARENT_SOURCE_INPUT_AND_REUSED_RUNTIME_METADATA','source':SOURCE,'identity':q['identity'],'parent_root':str(P),'caller_sha256':q['caller_sha256'],'request_sha256':release['request_sha256'],'helper_hashes':q['helper_hashes'],'registration':q['registration'],'registration_sha256':q['registration_sha256'],'source_pins':359,'tracked':360,'input_roles':29,'runtime_records_reused':251,'runtime_matrix_rerun':False,'old818_reread':False,'basis_source_proof':{'path':str(B/'SOURCE_INPUT_RUNTIME_PROOF01.json'),'sha256':R.digest(oldsource_raw)},'basis_cumulative_proof':{'path':str(B/'CUMULATIVE_PROOF01.json'),'sha256':R.digest(oldbudget_raw)},'actual_installed_manifest':scan,'actual_admission':False,'full_public_preflight_passed':False,'new_source_recovery':False,'numerical_authority':False,'checks':rd.checks,'read_bytes':rd.total}
readback['actual_Root_installation']=installation_ref
R.put(H/'INSTALLED_PARENT_READBACK01.json',readback)
report='''# Actual canonical Parent source and accounting phase

The actual installed ten-body Parent matches the exact independently released static candidate at its fixed fresh root, with directory0700/files0600. Caller5c0bab39 differs from the accepted original only in the frozen source binding and Parent path; the seven operational helpers remain byte-identical. The reuse contract changes only honest current source to d4c81c0; all accepted ancestry anchors and completed100 recovery remain unchanged. The actual DRAFT request preserves null source/accounting/recovery/final authority pending separately authored proofs. The optional builder4d081 remains WITHHELD and was not required for literal installation: its actual late-FD-close witness remains preserved.

Current source d4c is the exact two-file direct child of664e. Actual gate/prior bodies,359 source pins/360 tracked paths and29 input roles match. This source proof reuses the prior independently accepted251 RECORD/direct-METADATA/interpreter/lock evidence and its unchanged runtime mapping; it does not claim a new251 scan or installed runtime body recovery. Original818-body evidence is not reread. Runtime and historical scientific checks retain their original observation scope; sampled joins do not exclude later writes.

All four original claim and terminal body pins rejoin actual files: one COMPLETE and three FAILED, highest allowance20,16 remaining. Original extension/review bytes remain exact. There is no refund, transfer, new amendment, new claim or paper-fit credit. Both failed read-only preflights and the earlier Parent remain preserved. Actual new Parent attempt and fixed numerical claim namespaces are absent at readback.

This phase authenticates source/input/runtime metadata and cumulative accounting only. Current delta external recovery, final Parent release and complete public8MiB preflight remain unavailable. No numerical execution, Owner, ResearchRun, checkpoint deserialization, financial performance, whole capacity or POSIX reconstruction is claimed.
'''
with (H/'ADMISSION_PHASE_REPORT01.md').open('x') as f:f.write(report)
ref=lambda n:{'path':str(H/n),'sha256':R.digest(R.read(H,n))}
common={'source':SOURCE,'design_source':SOURCE,'reviewer':'/root/storage_watch_review','review':ref('INSTALLED_PARENT_READBACK01.json'),'report':ref('ADMISSION_PHASE_REPORT01.md')}
source=copy.deepcopy(oldsource);source.update(common);source.update(caller_sha256=q['caller_sha256'],registration_sha256=q['registration_sha256'],continuation_trusted_proof_contract={'path':str(P/'proof_reuse_contract01.json'),'sha256':q['helper_hashes']['proof_reuse_contract01.json']},runtime_scope='Reused accepted interpreter/lock/251 RECORD and installed METADATA evidence; same runtime mapping; no251 repeat or installed package body recovery',reused_basis=readback['basis_source_proof'])
budget=copy.deepcopy(oldbudget);budget.update(common);budget['reused_basis']=readback['basis_cumulative_proof']
R.put(H/'SOURCE_INPUT_RUNTIME_PROOF01.json',source);R.put(H/'CUMULATIVE_PROOF01.json',budget)
R.put(H/'ADMISSION_PHASE_MACHINE01.json',{'schema_version':1,'decision':readback['decision'],'reviewer':'/root/storage_watch_review','source':SOURCE,'identity':q['identity'],'readback':ref('INSTALLED_PARENT_READBACK01.json'),'report':ref('ADMISSION_PHASE_REPORT01.md'),'source_input_runtime':ref('SOURCE_INPUT_RUNTIME_PROOF01.json'),'cumulative':ref('CUMULATIVE_PROOF01.json'),'source_correction':ref('SOURCE_MACHINE01.json'),'static_parent_release':ref('STATIC_PARENT_INSTALL_RELEASE01.json'),'full_recovery':None,'final_review':None,'numerical_authority':False})
print(json.dumps({'machine':ref('ADMISSION_PHASE_MACHINE01.json'),'source_input_runtime':ref('SOURCE_INPUT_RUNTIME_PROOF01.json'),'cumulative':ref('CUMULATIVE_PROOF01.json'),'checks':rd.checks}))
