"""Genuine final metadata release; actual Parent validator functions only.
No Parent main, Admission, Owner, ResearchRun, model or preflight execution.
"""
from pathlib import Path
import sys,os,json,hashlib,re,ast,importlib.util
H=Path(__file__).resolve().parent;F=H.parent;P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-continue100-canonical-plan-root-launch-20261005-01');sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import Reader,R
rd=Reader();qr=rd.read(P/'REQUEST_FINAL_REVIEW_DRAFT01.json','410f544ceca7083937faf49449d291a569dc2246d012f1827bd54989a8517768');q=json.loads(qr);original_raw=rd.read(P/'REQUEST_SOURCE_BOUND_DRAFT01.json','0ea7cf3d34ccf9d67a1be6d836e130de275475bd6bb9d0284405cf141c6d18d6');original=json.loads(original_raw);fullref={'path':str(H/'CANONICAL_FULL_RECOVERY_PROOF01.json'),'sha256':'4bb7781345617bf5529e63b0c2d0a630aad726df87c3dc895ab4e02ca323aa79'};expected=json.loads(original_raw);expected['status']='RELEASED_ONE_USE_FINANCIAL_PARENT';expected['proofs']['full_recovery']=fullref;rd.need(q==expected and q['final_review'] is None,'exact only status plus genuine current recovery ref; additive review remains absent')
caller=rd.read(P/'parent01.py','5c0bab39643c61ffd36483ad466c203aa5df77a3a1749217a085d284d9051b66');rd.need(q['caller_sha256']==R.digest(caller),'exact genuine caller pin')
for name,h in q['helper_hashes'].items():rd.read(P/name,h)
proofs={k:rd.read(Path(v['path']),v['sha256']) for k,v in q['proofs'].items()};full=json.loads(proofs['full_recovery']);source=json.loads(proofs['independent_source_input_runtime']);budget=json.loads(proofs['cumulative'])
rd.need(R.digest(proofs['independent_source_input_runtime'])=='eaca3204a56979816cfd9b1eeb57b94f91d9b369c97bcd9706237a1273126591' and R.digest(proofs['cumulative'])=='46e039dcc4411c27697eba5cd85923b880956ad0d537ced11444c104e9591433','two accepted genuine proof bytes unchanged')
rd.need(full['decision']=='accepted-current-source-bound-draft-byte-recovery' and full['source']==full['design_source']==q['source']==q['design_source']=='d4c81c0961342bfe4c5771aabbef1d46a14cffb8' and full['identity']==q['identity'] and full['scope']['source_bound_draft_sha256']==R.digest(original_raw),'actual complete recovery and recovered draft lineage');review=json.loads(rd.read(Path(full['review']['path']),full['review']['sha256']));rd.need(review['decision']=='ACCEPTED_ACTUAL_CANONICAL_CURRENT_SOURCE_BOUND_DRAFT_BYTE_RECOVERY' and review['source']==q['source'] and review['identity']==q['identity'],'genuine actual recovery review')
rd.need(source['source']==source['design_source']==q['source'] and source['identity']==q['identity'] and source['caller_sha256']==q['caller_sha256'] and source['registration']==q['registration'] and source['registration_sha256']==q['registration_sha256'] and source['source_pins']==359 and source['input_roles']==29 and source['tracked']==360,'accepted actual source/input/runtime metadata');rd.need(source['continuation_trusted_proof_contract']=={'path':str(P/'proof_reuse_contract01.json'),'sha256':q['helper_hashes']['proof_reuse_contract01.json']},'actual current proof-reuse contract pinned')
rd.need(budget['source']==budget['design_source']==q['source'] and budget['identity']==q['identity'] and budget['spent_claims']==4 and budget['complete']==1 and budget['failed']==3 and budget['highest_claim_allowance']==20 and budget['effective_attempt_budget']==20 and budget['remaining']==16 and not any(budget[k] for k in ('new_amendment','refund','transfer','numerical_authority')),'exact no-refund/no-amendment accounting')
capture_basis=json.loads(rd.read(H/'DELTA_CAPTURE_READBACK01.json','741b8aa1b54c36853a59d44b842aa4c720f2e6f51c701564681a206db0dbad6e'));comp=json.loads(rd.read(F/'financial-wrapper-continuation-canonical-delta-root01-2026-10-05/snapshot/COMPOSITION01.json',capture_basis['composition_sha256']));rows={r['path']:r for r in comp['capsule']['members']};cap=Path(q['capsule_root']);gate_raw=rd.read(cap/q['registration'],q['registration_sha256']);gate=json.loads(gate_raw);definition=gate['experiments'][q['identity']];rd.need(definition['source_files']==q['source_files'] and len(q['source_files'])==359 and all(rows[n]['sha256']==h for n,h in q['source_files'].items()),'complete actual recovered current source map');rd.need(q['input_hashes']=={k:v['sha256'] for k,v in definition['inputs'].items()} and len(q['input_hashes'])==29,'all29 actual registered input roles');head=rd.read(cap/'.git/HEAD').decode().strip();commit=rd.read(cap/'.git'/head.removeprefix('ref: ')).decode().strip() if head.startswith('ref: ') else head;rd.need(commit==q['source'],'actual unchanged currentCAP HEAD')
rd.need(not os.path.lexists(P/'attempt') and not os.path.lexists(cap/'research_runs'/q['identity']),'genuine unused continuation identity')
# Import only actual stdlib byte-reader utility, never Parent/preclaim modules.
sys.path.insert(0,str(P));spec=importlib.util.spec_from_file_location('actual_parent_byte_utility',P/'recovery04.py');U=importlib.util.module_from_spec(spec);spec.loader.exec_module(U);ns={'Path':Path,'hashlib':hashlib,'json':json,'re':re,'R':U};tree=ast.parse(caller);names={'sha','require','reference','contract','validate_release'};nodes=[]
for n in tree.body:
 if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id in {'CAP','PARENT','IDENTITY','SOURCE_BINDING','PROOFS'} for t in n.targets):nodes.append(n)
 if isinstance(n,ast.FunctionDef) and n.name in names:nodes.append(n)
exec(compile(ast.Module(body=nodes,type_ignores=[]),'<genuine actual Parent release validators>','exec'),ns);core=ns['contract'](q);rd.need(core=='541647a8da01780a9ba5a4dc6c326fce38823e98f9e06bf54bcd58a8fde0cf08','actual exact Parent contract encoding')
# Two bounded refusal controls before granting actual concrete release.
controls=[]
for label,negative in [('genuine-null-final-review',q),('unreleased-source-bound-draft',original)]:
 try:ns['validate_release'](negative)
 except ValueError as error:controls.append({'case':label,'refused':True,'message':str(error)})
 else:raise AssertionError('missing expected unresolved authority refusal')
rd.finish();release={'schema_version':1,'decision':'accepted-exact-one-use-financial-parent','contract_sha256':core,'proof_sha256':{k:R.digest(v) for k,v in proofs.items()},'identity':q['identity'],'source':q['source'],'caller_sha256':q['caller_sha256']};R.put(H/'FINAL_PARENT_RELEASE01.json',release)
# This is the genuinely authored release, then actual untouched validator execution on its literal future reference.
bound=dict(q,final_review={'path':str(H/'FINAL_PARENT_RELEASE01.json'),'sha256':R.digest(R.encode(release))});rd.need(ns['validate_release'](bound)==release,'actual genuine complete release validates');rd.finish();result={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_FINANCIAL_PARENT_METADATA_RELEASE','request_draft_sha256':R.digest(qr),'recovered_source_bound_draft_sha256':R.digest(original_raw),'contract_sha256':core,'caller_sha256':q['caller_sha256'],'source':q['source'],'identity':q['identity'],'release_sha256':R.digest(R.encode(release)),'proof_sha256':release['proof_sha256'],'actual_unchanged_Parent_validator_pass':True,'controls':controls,'scientific_source_and_method_fields_unchanged':True,'actual_public_preclaim_executed_by_reviewer':False,'full8MiB_public_preclaim_still_required':True,'ResearchRun_or_Owner_created':False,'numerical_entry_executed':False,'source407_complete100_and_current_recovery_scopes_distinct':True,'future_final_authority_additive_to_recovered_draft':True,'checks':rd.checks,'read_bytes':rd.total};R.put(H/'FINAL_PARENT_RELEASE_READBACK01.json',result);print(json.dumps(result))
