"""Seal this consolidated review only after genuine Root public-preflight readback."""
from pathlib import Path
import sys,json
H=Path(__file__).resolve().parent
sys.path.insert(0,str(H.parent/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'))
from verify_capture01 import R

def ref(n):return {'path':str(H/n),'sha256':R.digest(R.read(H,n))}
p=json.loads(R.read(H,'PUBLIC_PREFLIGHT_READBACK01.json'))
r=json.loads(R.read(H,'FINAL_PARENT_RELEASE_READBACK01.json'))
c=json.loads(R.read(H,'CANONICAL_RECOVERY_MACHINE01.json'))
passed=p['public_preflight_passed']
report='''# Consolidated canonical-plan source, recovery and Parent review

The two exact canonical historical-plan metadata changes are accepted. The original public preflight refused the old alias; the unchanged extracted predicate accepts the corrected alias joined to the same genuine original636-byte plan. Prior descriptor and gate changes, dependent hashes and complete inverse are verified; continuation29 roles, prediction17 roles/null prior, two historical definitions, scientific code, training, seed, batch,100-epoch protocol and limits remain unchanged. Actual CAP d4c81c0961342bfe4c5771aabbef1d46a14cffb8 is the direct two-file successor of664e, with360 tracked paths and359 source pins.

Optional build01.py (4d08136c) remains WITHHELD. Its Reads.finish at lines30–32 rereads paths sequentially without a final descriptor-free whole-signature pass. A real later descriptor close changed an earlier already-reread file and mtime; finish succeeded with stale cached bytes. The actual witness is retained. Root did not invoke or repair that optional builder: the independently reviewed static ten-body Parent was directly installed and authenticated. Its two caller-header substitutions, reuse-contract source change and seven unchanged helpers preserve the accepted implementation. Genuine current source/input/runtime and cumulative proof bodies authenticate the installation; runtime251-record evidence is explicitly reused, not remeasured or claimed recovered.

The actual canonical delta, selected Git bodies,19-operation receiver and flat restoration are accepted. Every112 opaque archived/restored body and its original mapping were independently authenticated, including111 saved original bodies plus composition. The full current composition is823 CAP regular bodies/1049 typed entries,11 source-bound Parent files and422 logical Git objects. Accepted821 prior CAP hashes and416-object recovery are reused; exactly two changed bodies and six new Git objects are joined. Actual Root/child exits are zero, cleanup is empty and original inner Parent exit remains null. Recorded process absence has no universal-history implication. Original mode metadata is preserved; no POSIX reconstruction, installed-runtime body recovery, continuous writer exclusion or whole-capacity claim follows. Locally pinned transport utilities are not falsely included in the three-body recovered payload.

The final request is an exact additive transition from the genuinely recovered source-bound draft: released status and the current recovery-proof reference change, then the genuine final-review reference is added. Actual unchanged Parent.validate_release accepts the exact release; missing-review and draft-status controls refuse. Source, caller, all helper pins,359-source map,29 roles and three genuine proofs join. Accounting remains one COMPLETE/three FAILED, four spent claims, highest allowance20/effective20/16 remaining, without refund, transfer or amendment. No reviewer numerical invocation, Owner, ResearchRun, network operation or public preflight was performed.

'''
report+=('The actual Root full public preflight passed; its exact request, actual output and bounded reader total are retained in PUBLIC_PREFLIGHT_READBACK01. This is metadata admission, not a completed numerical outcome. Fresh resources and exact unused namespaces must still be checked by Root before its separately authorized one-use launch.\n\n' if passed else 'The actual Root public preflight did not pass. Its exact failure and raw evidence are retained in PUBLIC_PREFLIGHT_READBACK01; numerical entry remains WITHHELD. Accepted source/recovery and exact release-validator findings do not waive the unresolved public integration predicate.\n\n')
report+='Claims not tested: economic returns, timing leakage, exposure reuse, fees/funding, new numerical agreement, scientific capacity, universal process history, continuous writer exclusion, installed runtime body recovery and POSIX reconstruction. All original failed/withheld sources, raw witnesses and harness errors remain retained. The bounded source/admission snapshots remain byte-identical; later authority and outcome evidence is additive outside those snapshots.\n'
with (H/'REPORT01.md').open('x') as f:f.write(report)
m={'schema_version':1,'decision':'ACCEPTED_CANONICAL_SOURCE_RECOVERY_AND_EXACT_RELEASE_PUBLIC_PREFLIGHT_'+('PASSED' if passed else 'FAILED'),'reviewer':'/root/storage_watch_review','source':r['source'],'identity':r['identity'],'source_phase':ref('SOURCE_PHASE_MANIFEST01.json'),'admission_phase':ref('ADMISSION_PHASE_MANIFEST01.json'),'source_release':ref('SOURCE_CORRECTION_RELEASE01.json'),'static_parent_release':ref('STATIC_PARENT_INSTALL_RELEASE01.json'),'current_recovery_proof':ref('CANONICAL_FULL_RECOVERY_PROOF01.json'),'current_recovery_machine':ref('CANONICAL_RECOVERY_MACHINE01.json'),'final_parent_release':ref('FINAL_PARENT_RELEASE01.json'),'final_parent_readback':ref('FINAL_PARENT_RELEASE_READBACK01.json'),'public_preflight_readback':ref('PUBLIC_PREFLIGHT_READBACK01.json'),'public_preflight_passed':passed,'public_preflight_reader_bytes':p['reader_bytes'],'optional_builder_withheld':'4d08136c891107ee9a0f776632bd06ec51a94e850433d5299e5a2203012898fc','builder_invoked':False,'scope':c['scope'],'old821_CAP_hashes_and416Git_basis_reused':True,'runtime251_evidence_reused':True,'numerical_entry_executed_by_reviewer':False,'new_numerical_outcome_claimed':False,'whole_capacity':False,'continuous_writer_exclusion':False,'POSIX_reconstruction':False,'installed_runtime_body_recovery':False,'report':ref('REPORT01.md')}
R.put(H/'MACHINE01.json',m)
manifest=R.scan(H);manifest['self_excluded']='MANIFEST01.json';manifest['scope']='Complete consolidated canonical plan, static Parent, local capture, actual remote/flat recovery, exact final release and actual public-preflight review; earlier bounded phase seals preserved.'
R.put(H/'MANIFEST01.json',manifest)
print(json.dumps({'machine':ref('MACHINE01.json'),'report':ref('REPORT01.md'),'manifest':ref('MANIFEST01.json'),'members':len(manifest['members'])}))
