from pathlib import Path
import json,hashlib,ast,subprocess,copy,os
M=Path.cwd();F=M/'research/onchain-paper-replication-2026-09-24/full_sources';D=Path(__file__).parent;C=F/'heartbeat-root-checkpoint10-2026-10-04';B=F/'financial-wrapper-continuation-successor-review01-2026-10-05';CAP=M.parent/'onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source';P=M.parent/'onchain-financial-isolation/genuine-financial-wrapper-continue100-serialized-storage-root-launch-20261005-01';PREP=F/'financial-wrapper-serialized-storage-root-preparation01-2026-10-05';H=lambda b:hashlib.sha256(b).hexdigest()
def read(p):return json.loads(p.read_bytes())
def ref(p):return {'path':str(p),'sha256':H(p.read_bytes())}
def put(n,x):p=D/n;assert not p.exists();p.write_text(json.dumps(x,sort_keys=True,separators=(',',':'))+'\n');p.chmod(0o444);print(n,ref(p)['sha256'])
q=read(P/'REQUEST_SOURCE_BOUND_DRAFT01.json');ad=read(C/'SERIALIZED_READONLY_ADMISSION01.json');adexit=read(C/'SERIALIZED_READONLY_ADMISSION_ROOT_EXIT01.json');adopt=read(C/'SERIALIZED_SOURCE_GATE_ADOPTION01.json');source='6b07c0f841e7d38102814aabb335751fd71fb7f7';identity='financial-wrapper-classification-eager-continue100-serialized-storage-successor-20261005-01'
assert q['identity']==ad['identity']==identity and q['source']==q['design_source']==ad['source']==ad['design_source']==adopt['source']==source
assert adexit['actual_root_exit']==0 and adexit['source']==source and adexit['tool_chunk']=='92d91d';assert json.loads((C/'SERIALIZED_READONLY_ADMISSION01.stdout').read_text())==ad and (C/'SERIALIZED_READONLY_ADMISSION01.stderr').stat().st_size==0
assert ad['actual_admission_type']=="<class 'tradingagents.research.admission.Admission'>" and ad['decision']=='genuine-readonly-admission-passed-not-release' and ad['input_count']==36 and ad['source_count']==374 and ad['effective_attempt_budget']==20 and ad['numerical_imports']==[] and ad['lifecycle_claim_created'] is False and ad['monitor_owner'] is ad['scientific_owner'] is None
assert subprocess.run(['git','rev-parse','HEAD'],cwd=CAP,capture_output=True,check=True).stdout.decode().strip()==source
tracked=subprocess.run(['git','ls-tree','-r','--name-only','HEAD'],cwd=CAP,capture_output=True,check=True).stdout.decode().splitlines();assert len(tracked)==375 and set(tracked)==set(q['source_files'])|{q['registration']}
assert H((json.dumps(q['source_files'],sort_keys=True,indent=2)+'\n').encode())==adopt['source_map_sha256']=='2e289ef26bd4dfa378c2f3d9769475bbc0202fdc104f653310f12e5434f30584'
reg=read(CAP/q['registration']);exp=reg['experiments'][identity];assert H((CAP/q['registration']).read_bytes())==q['registration_sha256']==ad['registration_sha256']==adopt['registration_sha256']=='b61f834005dc622b166303962d387f77a8100c54ce3b7159e84ddd2926ce1774';assert exp['source_files']==q['source_files'] and {k:v['sha256'] for k,v in exp['inputs'].items()}==q['input_hashes']
unbound=copy.deepcopy(reg);unbound['experiments'][identity]['source_files']=None
for key in ['continuation_source_successor_review','continuation_source_successor_recovery']:unbound['experiments'][identity]['inputs'][key]['sha256']=None
assert unbound==read(PREP/'GATES_UNBOUND_DRAFT01.json')
oldgate=read(CAP/'fixture_inputs/financial_wrapper_continuation_successor01/gates.json');oldexp=oldgate['experiments']['financial-wrapper-classification-eager-continue100-resource-successor-20261005-01'];helper='tradingagents/research/onchain_replication/operational_source_compatibility.py';assert all(reg['experiments'][k]==v for k,v in oldgate['experiments'].items());assert {k for k,v in oldexp['source_files'].items() if q['source_files'].get(k)!=v}=={helper}
newnames=set(q['source_files'])-set(oldexp['source_files']);assert len(newnames)==8
for n in newnames|{helper}:assert H((CAP/n).read_bytes())==q['source_files'][n]
for role in ['continuation_source_successor','continuation_source_successor_review','continuation_source_successor_recovery','source_closure','successor_refusal','successor_previous_recovery','successor_original_refusal','wrapper_plan']:
 row=exp['inputs'][role];assert H((CAP/row['path']).read_bytes())==row['sha256']
assert H((P/'parent01.py').read_bytes())==q['caller_sha256']==adopt['caller_sha256']=='c1ac849e64ec3c49b2154867c645d0d6f00f993757289397b3098a518516519e'
parenttext=(P/'parent01.py').read_text();assignment=next(n for n in ast.parse(parenttext).body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id=='SOURCE_BINDING');binding=ast.literal_eval(assignment.value);assert binding['source']==source and binding['registration_sha256']==q['registration_sha256'] and binding['source_count']==374 and binding['tracked_count']==375
assert parenttext.replace('SOURCE_BINDING='+repr(binding),'SOURCE_BINDING=None')==(PREP/'parent-unbound01.py').read_text()
for name,pin in q['helper_hashes'].items():assert H((P/name).read_bytes())==pin
oldp=M.parent/'onchain-financial-isolation/genuine-financial-wrapper-continue100-resource-successor-root-launch-20261005-01';reuse=read(P/'proof_reuse_contract01.json');oldreuse=read(oldp/'proof_reuse_contract01.json');assert {k for k in reuse if reuse[k]!=oldreuse[k]}=={'consumer','current_source'} and reuse['consumer']==identity and reuse['current_source']==source
assert q['runtime_mapping']==read(oldp/'REQUEST_FINAL01.json')['runtime_mapping']
for p in [P/'attempt',CAP/'research_runs'/identity,CAP/'research_artifacts/financial_wrapper_engineering'/identity,CAP/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/identity]:assert not os.path.lexists(p)
previouscum=read(B/'CUMULATIVE_PROOF01.json');assert {p.name for p in (CAP/'research_runs').iterdir()}=={row['identity'] for row in previouscum['claims']}|{'.lock'};assert exp['cumulative_budget_extension']==previouscum['cumulative_budget_extension'] and reg['program_id']==previouscum['program_id'] and exp['family']==previouscum['family']
check={'schema_version':1,'decision':'accepted-actual-serialized-current-source-caller-and-readonly-admission','identity':identity,'source':source,'design_source':source,'tracked':375,'source_pins':374,'input_roles':36,'installed_paths':195,'changed_installed_paths':[helper],'unchanged_old_gate_definitions':5,'registration':q['registration'],'registration_sha256':q['registration_sha256'],'source_map_sha256':adopt['source_map_sha256'],'caller_sha256':q['caller_sha256'],'caller_exact_bound_unbound_inverse':True,'actual_adoption':ref(C/'SERIALIZED_SOURCE_GATE_ADOPTION01.json'),'actual_readonly_admission':ref(C/'SERIALIZED_READONLY_ADMISSION01.json'),'actual_readonly_root_exit':ref(C/'SERIALIZED_READONLY_ADMISSION_ROOT_EXIT01.json'),'failed_source_receiver_recovery':ref(D/'FAILED_FLAT_CHECK01.json'),'original_runtime_mapping_unchanged':True,'four_claim_namespace_unchanged':True,'fresh_namespaces_absent':True,'full_preclaim_success':False,'numerical_authority':False,'qualification':'Genuine Root read-only Admission authenticates current runtime/source/input files. Reviewer checks changed bytes/bindings and reuses accepted original195/runtime251/history roots; no historical body inventory rerun.'};put('CURRENT_GATE_CHECK01.json',check)
report=D/'ADMISSION_PHASE_REPORT01.md';report.write_text('Current source6b07,375 tracked/374 source pins/36 inputs/195 installed paths and bound Parentc1ac passed genuine read-only Admission. The original five definitions, runtime mapping, model/training/native job and cumulative20 allowance remain unchanged. Four spent claims (1 COMPLETE,3 FAILED),16 remaining and two permanent no-claim reservations remain exact. Source03 recovered all62 selected bodies; original failed receiver01 was independently restored93 bodies with unknown original exit preserved. Current CAP/Git/caller recovery and final preclaim/release remain pending; no numerical authority.\n');report.chmod(0o444)
cum=previouscum;cum.update(identity=identity,source=source,design_source=source,actual_readonly_admission=ref(C/'SERIALIZED_READONLY_ADMISSION01.json'),review=ref(D/'CURRENT_GATE_CHECK01.json'),report=ref(report),reused_basis=ref(B/'CUMULATIVE_PROOF01.json'))
cum['reserved_no_claim']=[cum['reserved_no_claim'],{'identity':'financial-wrapper-classification-eager-continue100-resource-successor-20261005-01','namespace_reuse_authorized':False,'spent_claim':False,'recovered_refusal':ref(F/'financial-wrapper-continuation-successor-outcome-review01-2026-10-05/FULL_TERMINAL_RECOVERY_PROOF01.json')}];put('CUMULATIVE_PROOF01.json',cum)
proof=read(B/'SOURCE_INPUT_RUNTIME_PROOF01.json');proof.update(identity=identity,source=source,design_source=source,caller_sha256=q['caller_sha256'],registration=q['registration'],registration_sha256=q['registration_sha256'],source_pins=374,tracked=375,input_roles=36,actual_readonly_admission=ref(C/'SERIALIZED_READONLY_ADMISSION01.json'),actual_readonly_admission_source=ref(C/'SERIALIZED_READONLY_ADMISSION01.py'),actual_readonly_admission_stdout=ref(C/'SERIALIZED_READONLY_ADMISSION01.stdout'),actual_readonly_admission_stderr=ref(C/'SERIALIZED_READONLY_ADMISSION01.stderr'),continuation_trusted_proof_contract=ref(P/'proof_reuse_contract01.json'),operational_source_policy_recovery=ref(D/'SOURCE_REMOTE_CHECK01.json'),review=ref(D/'CURRENT_GATE_CHECK01.json'),report=ref(report),reused_basis=ref(B/'SOURCE_INPUT_RUNTIME_PROOF01.json'));proof['actual_readonly_admission_root_exit']=ref(C/'SERIALIZED_READONLY_ADMISSION_ROOT_EXIT01.json');proof['source_increment_external_recovery']=True;proof['failed_receiver_complete_byte_recovery']=ref(D/'FAILED_FLAT_CHECK01.json');put('SOURCE_INPUT_RUNTIME_PROOF01.json',proof)
