from pathlib import Path
import hashlib,json,stat,tarfile
M=Path.cwd();F=M/'research/onchain-paper-replication-2026-09-24/full_sources';D=Path(__file__).parent;T=F/'financial-wrapper-serialized-storage-source-failed-flat01-2026-10-05';R=F/'financial-wrapper-serialized-storage-source-remote03-2026-10-05';prefix='research/onchain-paper-replication-2026-09-24/full_sources/financial-wrapper-serialized-storage-source-failed-capture01-2026-10-05';H=lambda b:hashlib.sha256(b).hexdigest()
def ref(p):b=p.read_bytes();return {'path':str(p),'sha256':H(b),'bytes':len(b)}
def read(p):return json.loads(p.read_bytes())
r=read(T/'RECOVERY01.json');root=read(T/'ACTUAL_ROOT_EXIT01.json');meta=read(T/'flat/body-metadata.json');manifest=read(R/'selected'/prefix/'archive-manifest.json');assert ref(T/'RECOVERY01.json')['sha256']=='929d62cc9243bd3dd2ce76050f2b052ba185484ae0335405c35bd363a27a013c' and root['actual_root_exit']==0 and root['tool_chunk']=='38f0b5';assert ref(T/'flat/body-metadata.json')['sha256']==r['primitive']['metadata_sha256'];assert meta['manifest']==manifest and len(manifest['members'])==104 and len(meta['flat_members'])==93
files={x['path']:x for x in manifest['members'] if x['kind']=='file'};assert set(meta['flat_members'])==set(files) and len(set(meta['flat_members'].values()))==93;assert set(p.name for p in (T/'flat').iterdir())==set(meta['flat_members'].values())|{'body-metadata.json'};assert stat.S_IMODE((T/'flat').stat().st_mode)==0o700;payload={}
for name,leaf in meta['flat_members'].items():
 p=T/'flat'/leaf;s=p.lstat();assert stat.S_ISREG(s.st_mode) and stat.S_IMODE(s.st_mode)==0o600 and s.st_nlink==1;b=p.read_bytes();assert H(b)==files[name]['sha256'] and len(b)==files[name]['bytes'];payload[name]=b
archive=R/'selected'/prefix/'failed-source-receiver.tar.gz';assert ref(archive)['sha256']==r['archive_sha256']=='da7d27f13dd9c2ff3cf091252249ba9f43dd3cad87059321c53a758609e0d0ae'
with tarfile.open(archive,'r:gz') as tar:
 members=tar.getmembers();assert len(members)==104
 for item in members:
  if item.isfile():assert tar.extractfile(item).read()==payload[item.name] and item.mode==files[item.name]['mode']
  else:assert item.isdir()
failed=json.loads(payload['FAILED01.json']);exit=json.loads(payload['ACTUAL_ROOT_EXIT01.json']);assert failed['status']=='failed-original-attempt' and failed['operations'][-1]['exit'] is None and failed['operations'][-1]['actual_reaped_exit']==-9 and exit['actual_root_exit']==1;assert len(failed['operations'])==30 and all(x['cleanup_failures']==[] for x in failed['operations']);assert r['receiver_receipt_sha256']==ref(R/'REMOTE_RECOVERY01.json')['sha256']
x={'schema_version':1,'decision':'accepted-actual-failed-source-receiver-complete-byte-recovery','actual_flat':ref(T/'RECOVERY01.json'),'actual_flat_root_exit':ref(T/'ACTUAL_ROOT_EXIT01.json'),'actual_remote':ref(R/'REMOTE_RECOVERY01.json'),'flat_metadata':ref(T/'flat/body-metadata.json'),'archive':ref(archive),'original_regular_bodies':93,'original_typed_members':104,'flat_bodies_independently_read_once':93,'original_failed_exit':None,'original_actual_reaped_exit':-9,'original_root_exit':1,'original_attempt_remains_failed':True,'all_30_original_cleanup_failure_lists_empty':True,'same_receiver_namespace_reuse_authorized':False,'POSIX_reconstruction':False,'numerical_authority':False,'qualification':'Complete actual failedreceiver01/bare/source receipt bytes recovered from genuine source03 archive and fresh flat output; original failed status and unknown exit remain unchanged. No old capsule/Git object body scan.'};p=D/'FAILED_FLAT_CHECK01.json';p.write_text(json.dumps(x,sort_keys=True,separators=(',',':'))+'\n');p.chmod(0o444);print(ref(p))
