import json,pathlib,hashlib,stat
ROOT=pathlib.Path.cwd();R=pathlib.Path(__file__).resolve().parent;F=R.parent;E=F/'real-data-pilot-full29-entry01-2026-10-09';T=F/'real-data-pilot-full29-transport-binding01-2026-10-09';O=F/'real-data-pilot-full28-entry01-2026-10-09';j=lambda p:json.loads(p.read_bytes());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
v=j(R/'CHECK02.json');assert v['decision']=='accepted';b=j(E/'BINDING_DRAFT03.json');g=j(E/'gate03.json');x=g['experiments'][v['identity']];old=j(O/'gate01.json')['experiments'][v['identity'][:-2]+'28'];prep=j(ROOT/b['preparation']['path']);pair=prep['builder03_result']['inputs']['pair_policy'];oldb=j(O/'BINDING01.json');oldpair=j(ROOT/oldb['preparation']['path'])['builder03_result']['inputs']['pair_policy'];installation=j(F/'pilot-full28-to-successor-root-integration01-2026-10-09/INSTALL01.json');current=pair['numerical_source']['files'];previous=oldpair['numerical_source']['files'];changed={p:sha for p,sha in current.items() if previous.get(p)!=sha};assert changed=={a['path']:a['after_sha256'] for a in installation['files']};assert len(changed)==17
assert j(T/'binder02/DEPENDENCIES01.json')==j(T/'BINDER_DEPENDENCY_CORRECTION01.json')['current_dependencies']
p=ROOT/b['transport']['path'];assert stat.S_IMODE(p.stat().st_mode)==0o600 and stat.S_IMODE(p.parent.stat().st_mode)==0o700
for role in ('model','training'):assert v['input_refs'][role]==oldb['input_refs'][role]
assert v['evidence'][str(E.relative_to(ROOT))+'/preflight29_01.py']==h(E/'preflight29_01.py')
# Summary allocation is seven stage batches, not seven copies of maximum-stage cap.
cap03=j(F/'mcm-batched-grouped-capacity03-2026-10-09/CAPACITY01.json')
# Retain source-qualified aggregate explicitly; exact arithmetic is101559*8192.
assert 101559*8192==831971328
for k in ('gate','public_preparation','public_manifest','preparation','transport_binding','budget_review'):assert v['evidence'][b[k]['path']]==b[k]['sha256']
ip=F/'pilot-full28-to-successor-root-integration01-2026-10-09/INSTALL01.json';v['evidence'][str(ip.relative_to(ROOT))]=h(ip)
for n in ('finish01.py','FINISH01.stderr','check01.py','check02.py','CHECK01.stderr','CHECK01.stdout','CHECK02.stderr','CHECK02.stdout','CHECK02.json'):
 p=R/n;v['evidence'][str(p.relative_to(ROOT))]=h(p)
review={'decision':'accepted','identity':v['identity'],'input_refs':v['input_refs'],'evidence':v['evidence'],'scope':'Exact corrected gate03/DRAFT03 source/input/caller binding. Conditional on actual final binding, committed genuine metadata admission, actual final declared public increment recovery independently accepted, and fresh resource/native/source eligibility before at most one unused29. No claim or launch granted.'}
(R/'BINDING_REVIEW01.json').write_text(json.dumps(review,indent=2,sort_keys=True)+'\n')
report={'decision':'accepted_changed_entry_only','identity':v['identity'],'binding_review_sha256':h(R/'BINDING_REVIEW01.json'),'source_count':455,'input_count':64,'evidence_count':len(v['evidence']),'numeric_source_count':196,'capacity_source_count':419,'source_anchor':pair['numerical_source']['commit'],'changed_numerical_sources':changed,'checks':v['checks']+['Exactly17 accepted installed changes, including3 new helpers; no other numerical source changes.','Actual binder dependency file equals dispatch-only corrected declaration; sole opaque29 mode0600/parent0700 checked without decoding.','Corrected preparation origin joins public_preparation; separate public manifest retains419 source/capacity join.','Per-stage summary144998400 unchanged; aggregate101559 batches*8192=831971328, not seven times the maximum-stage cap.'],'preserved_findings':['Original preflight preparation-origin reference mismatch corrected by Root; originals retained.','Original strict budget reference schema refusal corrected by Root in gate03/draft03; no budget amount change.','CHECK01 stopped on concurrently replaced preflight source while using oldgate01; original stderr retained.','Read-only discovery commands had gate list/dict and unmatched-parenthesis harness mistakes; no candidate execution or authority resulted.'],'wrapper_provenance':'Wrapper01 dependency refusal and wrapper02 post-bind footer failure remain FAILED. Actual BOUND02/readback/public11/opaque1 hashes authenticated separately; no replay or coerced success.','limitations':'Historical currentness/remote samples and prior_root_closure_review27 are provenance only. No empirical arrays/numerical imports/Owner/Run/network, current resource eligibility, full scientific completion, measured speedup or whole future capacity assertion. Source-only selection of adaptive/geometry/timing reuses accepted finite implementation evidence.'}
(R/'SOURCE_REVIEW01.json').write_text(json.dumps(report,indent=2,sort_keys=True)+'\n');print(json.dumps({'binding':h(R/'BINDING_REVIEW01.json'),'source':h(R/'SOURCE_REVIEW01.json'),'evidence':len(v['evidence'])}))
