import pathlib,json,hashlib
ROOT=pathlib.Path.cwd();R=pathlib.Path(__file__).resolve().parent;E=R.parent/'real-data-pilot-full29-entry01-2026-10-09';j=lambda p:json.loads(p.read_bytes());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
b=j(E/'BINDING02.json');d=j(E/'BINDING_DRAFT04.json');review=j(R/'BINDING_REVIEW02.json');ev=dict(review['evidence']);assert len(ev)==553 and review['decision']=='accepted';assert {k for k in b.keys()|d.keys() if b.get(k)!=d.get(k)}=={'binding_review'};assert d['binding_review'] is None
rp=R/'BINDING_REVIEW02.json';assert b['binding_review']=={'path':str(rp.relative_to(ROOT)),'sha256':h(rp),'bytes':rp.stat().st_size};assert h(rp)=='28bfc0b4f80f4d8a063f0f9008259b32c125a1ad78a1a14579ec98142e90beda'
for k,v in b.items():
 if isinstance(v,dict) and {'path','sha256'}<=v.keys() and k!='binding_review':assert ev[v['path']]==v['sha256']
for p in (E/'gate04.json',E/'preflight29_02.py',E/'root_io29_02.py'):assert ev[str(p.relative_to(ROOT))]==h(p)
x=j(E/'gate04.json')['experiments'][b['identity']];assert len(x['source_files'])==458 and len(x['inputs'])==64;assert all(ev[p]==sha for p,sha in x['source_files'].items());assert all(ev[v['path']]==v['sha256'] for v in x['inputs'].values());assert b['input_refs']==review['input_refs'];assert x['cumulative_budget_extension']['review']==b['budget_review']
for p in (E/'BINDING02.json',R/'BINDING_REVIEW02.json',R/'SOURCE_REVIEW02.json',R/'SCRATCH_REVIEW02.stdout',R/'SCRATCH_REVIEW02.stderr',R/'seal02.py'):ev[str(p.relative_to(ROOT))]=h(p)
out={'decision':'accepted','identity':b['identity'],'evidence':ev,'actual_final_binding_sha256':h(E/'BINDING02.json'),'reused_binding_review_sha256':h(rp),'scope':'Exact final full29 corrected scratch/caller binding seal.553 accepted references reused; actual BINDING02 differs DRAFT04 only binding_review.458 admitted source pins/64 inputs. Original release01 and failures preserved; no evidence self-reference.','conditions':['Actual final declared full29 public increment14 external return and independent exact typed-member/body verification.','Fresh original preflight committed admission, source/runtime/resource/process/namespace eligibility and authenticated committed release before at most one unused29 attempt.'],'qualification':'No completed increment14 recovery or current capacity eligibility asserted. Existing filesystem headroom refusal remains a fresh preflight matter. Earlier metadata admission predates scratch/caller successor and is not represented as current final admission. No numerical imports/inputs, Owner/Run/claim/network/launch, complete MCM/training, whole future capacity or speedup credit. Saved binder output readback remains distinct from failed outer wrapper. Sole current29 opaque dispatch is hash/stat evidence only.'}
(R/'RELEASE_REVIEW02.json').write_text(json.dumps(out,indent=2,sort_keys=True)+'\n');proof={'decision':'accepted_final_binding_delta_only','binding_sha256':h(E/'BINDING02.json'),'release_sha256':h(R/'RELEASE_REVIEW02.json'),'changed_binding_fields':['binding_review'],'inherited_evidence_count':553,'release_evidence_count':len(ev),'no_self_reference':str((R/'RELEASE_REVIEW02.json').relative_to(ROOT)) not in ev};(R/'SEAL02.json').write_text(json.dumps(proof,indent=2,sort_keys=True)+'\n');print(json.dumps(proof))
