from pathlib import Path
import ast,hashlib,json,os,stat
B=Path(__file__).resolve().parent;P=B.parent/'financial-outcome-chunked-preservation-preparation01-2026-10-04'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def put(name,obj):(B/name).write_text(json.dumps(obj,sort_keys=True,indent=2)+'\n')
c=json.loads((B/'CHECKS02.json').read_text());f=json.loads((B/'FRAMING_CHECKS04.json').read_text())
source=(P/'chunk_archive01.py').read_text();tree=ast.parse(source);rcalls=sorted({n.func.attr for n in ast.walk(tree) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and isinstance(n.func.value,ast.Name) and n.func.value.id=='R'});assert rcalls==['path_name','read','sig']
findings=[{'id':'CA1','priority':'P2','file':'chunk_archive01.py','line':187,'problem':'verify_flat authenticates a hash but omits the archive complete-index schema, fixed1GiB reservation and native_or_research_authority=False predicates. The exact routine accepts newly pinned opaque indexes with reserved_whole_bytes=TOTAL+1, wrong kind/version, or authority=True.','required_change':'Share a pure complete-index/member schema validator between archive and flat verification; enforce identical bounds/flags/root/mode/member/framing predicates independently of access to chunks. Retain whole-flat body hash proof.','qualification':'Each malformed test supplied its own newly computed opaque pin. No genuine Root index hash was bypassed, and no actual scientific/native authority was obtained.'},{'id':'CA2','priority':'P1','file':'chunk_archive01.py','line':86,'problem':'fresh checks/anchors the parent, then invokes path-based target.mkdir before rechecking. An owned parent renamed and substituted with a symlink redirects directory creation into a different owned root; the later anchor refusal occurs after the side effect.','required_change':'Acquire and bind the actual parent directory descriptor before mutation, create the one child relative to that descriptor with explicit ownership checks, and verify child/parent identity while retaining cleanup and failure evidence. Do not resolve a mutable path again for the creation action.','qualification':'Exact source operations were scheduled explicitly on owned opaque directories; no monkeypatch and no claimed observation of a timed uninstrumented full fresh() race.'}]
put('REVIEW01.json',{'schema_version':1,'verdict':'WITHHELD_CA1_CA2','candidate_manifest_sha256':sha(P/'MANIFEST01.json'),'candidate_source_sha256':sha(P/'chunk_archive01.py'),'findings':findings,'actual_witnesses':c['witnesses'],'checks':{'source_pipeline_and_owned_io':c['checks'],'framing_and_actual_failure':f['checks']},'actual_opaque_pipeline':{'capture':c['actual_capture'],'fresh_flat_receipt':c['actual_flat_receipt'],'source_archive_names_removed_before_flat_verification':True,'raw_chunk_extents':[1048576,256],'member_pages':2,'mapping_pages':2,'complete_logical_modes_directories_and_git_byte_metadata':True,'Git_validity_or_ancestry_verified':False},'actual_failure':f['actual_failure'],'verified_scope':['152-member108-file candidate manifest/mode/hash plus declared hardlink/symlink witnesses','all three primitive helper files match authenticated unchanged originals; source calls R.path_name/read/sig only; no Git invocation','whole byte capture/restore/independent flat verification on two exact owned roots, including empty file/dir, hidden paths and opaque Git-like bytes','exact full sorted file/directory/mode/hash membership, two pages and consecutive chunk extents/reconstruction','corrupt/missing/unexpected archive bodies, changed flat body and failure-marker refusal','newly pinned malformed chunk missing/duplicate/swapped/extents/overlap/member-order/missing-parent/unknown-root envelopes refuse archive validation','real concurrent owned-source addition after capture intent causes ValueError and preserves actual partial artifacts/failure receipt','fixed4MiB output gate refuses before file creation; bounds constants unchanged; actual helper first-fatal/all-callback semantics'], 'harness_history':['check01 assumed type rather than actual kind manifest field; preserved error, check02 corrects this and authenticates declared nlink','check_framing03 had a parser syntax typo and executed no controls; preserved, check_framing04 corrects it'],'not_tested':['Live financial outputs, checkpoints or Run/Owner/claims; numerical modules/arrays/test labels','Actual100epoch/128MiB or near1GiB workload resource capacity; cumulative native accounting and outer launcher','External transport, remote recovery, actual Git objects/ancestry or POSIX reconstructed tree','All concurrent races/allocator faults/failed-close success guarantees; source-operation CA2 schedule is explicitly bounded'],'authority':{'installed_source':None,'FINAL_REVIEW':None,'native_execution':None,'financial_credit':0}})
(B/'REVIEW01.md').write_text(f'''# Independent chunked-preservation source review

Verdict: WITHHELD for CA1 and CA2. The actual small opaque capture → restore → independent flat-verification pipeline succeeds, but the following source corrections are required before Root can adopt it.

**CA1, P2 — chunk_archive01.py:187:** verify_flat omits the complete index schema and fixed-cap predicates enforced by validate_archive. The actual routine accepts a test index with reserved_whole_bytes=1GiB+1, wrong kind/version or native_or_research_authority=True. Each counterexample supplies a new opaque index hash; this does not bypass a genuine external Root pin or grant authority. A shared pure index/member validator should enforce identical flags, types, reservation limits, roots and complete framing rules in both paths.

**CA2, P1 — chunk_archive01.py:86:** fresh anchors the parent, then performs target.mkdir by pathname before rechecking the anchor. Exact source operations on owned directories demonstrate a rename/symlink substitution creating the child inside another owned root; the check refuses only afterward. Bind the actual parent fd and create the direct child relative to that descriptor, retaining child/parent verification and all cleanup. This is explicit source-operation scheduling without monkeypatching, not a claimed timed uninstrumented race observation.

{c['checks']} source/pipeline/IO controls and {f['checks']} framing/failure controls authenticate the complete candidate and unchanged primitives, reconstruct every opaque file/directory/mode, exercise two member pages and two mapping pages, and verify a 1MiB+256B body split into exact ordered chunks. Independent flat verification succeeds after the original source and archive names have been removed. The opaque Git-like bytes retain no Git object/ancestry authority.

Corrupt, missing, duplicate, reordered, overlapping, wrong-extent and unexpected bodies or descriptors refuse at their checked boundaries. A real owned-source addition after capture intent produces an actual ValueError and capture-failure receipt; all partial artifacts and original source bytes remain. An extra failure marker prevents a previously complete flat tree from validating. The4MiB output limit refuses before creating an oversized file. Source plus archive plus flat conservative reservation and10GiB floor remain in the code; only the small owned workload was exercised, not future100epoch or near-capacity feasibility.

One initial harness assumed the wrong typed-manifest field name, and one supplemental harness had a syntax typo before execution. Their exact source/errors are retained; corrected check02 and check_framing04 provide the reported results. No source/helper constants were patched. The new module invokes only unchanged R.path_name/read/sig primitives and original owned cleanup; no Git function, child/native process, network, numerical module, array, test label, genuine Run/Owner or claim was invoked.

Root still owns exact live outcome scope, attempt denominator, current cumulative storage/resource accounting, final caller/source pins, external preservation and genuine recovery. No larger file/watch/cap, retry, budget transfer, paper credit, scientific representation or POSIX restoration authority follows from these byte controls.
''')
entries=[]
for p in sorted(B.rglob('*')):
 rel=p.relative_to(B).as_posix()
 if rel=='MANIFEST01.json':continue
 s=p.lstat();e={'path':rel,'mode':stat.S_IMODE(s.st_mode),'nlink':s.st_nlink}
 if stat.S_ISDIR(s.st_mode):e['type']='directory'
 elif stat.S_ISREG(s.st_mode):e.update(type='file',bytes=s.st_size,sha256=sha(p))
 elif stat.S_ISLNK(s.st_mode):e.update(type='symlink',target=os.readlink(p))
 else:raise ValueError('unsupported type')
 entries.append(e)
put('MANIFEST01.json',{'schema_version':1,'scope':'complete typed independent review and actual owned opaque pipeline/failure witnesses; exact self excluded','entries':entries,'members':len(entries),'regular_files':sum(e['type']=='file' for e in entries),'regular_bytes':sum(e.get('bytes',0) for e in entries)})
print(json.dumps({'report':sha(B/'REVIEW01.md'),'machine':sha(B/'REVIEW01.json'),'manifest':sha(B/'MANIFEST01.json'),'members':len(entries),'files':sum(e['type']=='file' for e in entries),'bytes':sum(e.get('bytes',0) for e in entries),'checks':[c['checks'],f['checks']]},indent=2))
