from pathlib import Path
import ast,difflib,hashlib,json,os,stat
H=Path(__file__).resolve().parent;sha=lambda b:hashlib.sha256(b).hexdigest()
def save(n,x):(H/n).write_text(json.dumps(x,sort_keys=True,indent=2)+'\n')
old=(H/'DRAFT01_copy_layout01.py').read_text();new=(H/'copy_layout01.py').read_text();patch=[]
for tag,i,j,k,l in difflib.SequenceMatcher(None,old,new,autojunk=False).get_opcodes():
 if tag!='equal':patch.append({'old_start':i,'old_end':j,'new_start':k,'new_end':l,'old':old[i:j],'new':new[k:l]})
x=new
for p in reversed(patch):assert x[p['new_start']:p['new_end']]==p['new'];x=x[:p['new_start']]+p['old']+x[p['new_end']:]
assert x==old and ast.dump(ast.parse(x))==ast.dump(ast.parse(old))
save('SOURCE_INVERSE01.json',{'draft_sha256':sha(old.encode()),'source_sha256':sha(new.encode()),'segments':patch,'complete_literal_inverse':True,'complete_AST_inverse':True,'declaration':'Original new-code draft and successful tiny controls retained; final candidate adds full root/member cleanup-bracket signature joins and final original-mode joins. Neither draft nor successor fixed Root entry ran.','unchanged_primitives':{'preclaim01.py':'557b7bcb38b48e3bf1e9e5b5b1eae25ab4908b8567820e17700dc08774b48d16','owned_io.py':'09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb'}})
report='''SOURCE PREPARATION ONLY. copy_layout01.py implements the finite one-use ordinary Root evidence-layout copy; its fixed output financial-wrapper-compatibility-coalesced-evidence-root03-2026-10-04 remains absent. No public run/entry, network, numerical import, source/admission/claim mutation or new accepted proof was executed or emitted.

The fixed INPUTS01 digest binds57 unique sorted destinations: all51 original provenance entries (38 genuine receipt bodies +13 original source evidence bodies), two additional literal original proofs, and four literal original review02 context bodies. Total copied regular bytes1,384,187. The original policy MACHINE/REPORT/MANIFEST destinations are concrete-policy/{original filename}, retaining the exact original modes. REVIEW_PROOF01 joins the same original typed policy manifest. The38 receipt candidates refer to those SAME three canonical paths. Other copies keep the prior copied modes, while original paths/modes and retained-copy paths/modes are separately preserved in ORIGIN_MAP01. No body is reencoded. Original c5cf proof is a literal ORIGINAL_RECOVERY_PROOF01 copy, not a newly issued authority. Original51 origins/old review02 remain unchanged.

All admitted bodies are exact regular files with pinned byte extent/hash/mode and nlink1; source control FIFOs/links/hardlink witnesses are never opened by discovery. Their original descriptions remain preserved in the copied immutable source/review metadata. Public run requires exact INPUTS SHA, denominator51/38/13/57 and fixed absent canonical output. Parent directories are opened using descriptor-relative O_NOFOLLOW; output reservation uses mkdir700 once. Every file uses exclusive O_NOFOLLOW creation, full bounded os.write, fsync, explicit exact mode and readback. No output is removed on failure and no namespace is reusable. Actual Root must retain stdout/stderr/tool exit and any partial namespace; the in-file draft is not terminal authority.

The exact557b preclaim02 bytebody and09d1 owned_io bytebody are embedded and separately copied unchanged. Full literal and AST identity are checked; no unchecked bootstrap filesystem import is added. The Reader retains the unchanged4MiB file/8MiB aggregate/120s limits. Output is sampled at fresh-empty creation, after each copied body, before output-descriptor cleanup and after full Reader.finish. Complete namespace equality and original identity/modes bracket cleanup; every read fingerprint and output member/root signature is rejoined after the last measurement cleanup. Whole output checks retain64MiB logical/96MiB allocated/256members/5s census and10GiB free floor plus1MiB conservative prewrite headroom. These are finite observed bounds, not a kernel quota, writer exclusion, atomicity or ABA immunity.

The actual owned control suite passes217 assertions with25 real descriptor failure pairs, exact byte/mode copy and one-use refusal, bad hash/order/duplicate/traversal/mode/extent, retained-body tampering, actual hardlinks/symlinks, late byte/mode/extra-member changes and floor refusal. Descriptor cleanup attempts all owned closes with first-fatal precedence and retained secondary objects. Original successful draft controls and all partial/negative test namespaces are retained. Full local opaque metadata-copy control processes all57 exact fixed bodies under a separate owned directory, not the fixed Root output. It charges7,981,684 actual Reader bytes including finish, beneath8,388,608, produces59 files including draft/origin map, and validates the three policy-proof members against the unchanged original manifest using the real metadata _sealed/Reader components. That copied scope is local engineering evidence only, not actual Root preservation or a new recovery proof. Fixed source-only input authentication alone charges5,009,584 bytes. Controls do not create genuine authority handles.

DRAFT_LAYOUT01 contains only candidate paths/hashes, original proof copy and NULL new accepted machine/report/manifest/final Parent. A different author must inspect Root's eventual actual copy and write a genuine accepted review/machine/typed seal, preserving all original facts/receipts. New accepted fields are deliberately not synthesized here. The final Parent's complete8MiB preclaim remains unmeasured: this copier's7,981,684B read cost is a different operation. The earlier handoff's271,114B coalescence saving remains exact for unchanged receipt bytes; actual final review-size deltas and full Parent/contract/release/three proofs must be charged without cap increase, body reencoding or evidence omission.
'''
(H/'REPORT01.md').write_text(report)
full=json.loads((H/'FULL_CONTROLS03.json').read_bytes());machine={'schema_version':1,'status':'SOURCE_ONLY_DRAFT_LAYOUT_COPIER_READY_FOR_INDEPENDENT_REVIEW','source_sha256':sha(new.encode()),'inputs_sha256':sha((H/'INPUTS01.json').read_bytes()),'fixed_root':json.loads((H/'INPUTS01.json').read_bytes())['output_root'],'source_output_root_absent':not Path(json.loads((H/'INPUTS01.json').read_bytes())['output_root']).exists(),'complete_copy_bodies':57,'original_provenance_entries':51,'receipt_bodies':38,'source_evidence_bodies':13,'logical_original_bytes':1384187,'final_checks':217,'real_descriptor_error_pairs':25,'local_complete_metadata_control':{'fixed_root_entry':False,'actual_bytes_read_including_finish':full['actual_bytes_read_including_full_finish'],'draft_bytes':full['draft_bytes'],'origin_map_bytes':full['origin_map_bytes']},'new_accepted_machine':None,'new_recovery_proof':None,'numerical_authority':False,'network_or_lifecycle':False,'final_parent_preclaim_fit':None,'report_sha256':sha((H/'REPORT01.md').read_bytes())};save('MACHINE01.json',machine)
rows=[];pending=[H]
while pending:
 p=pending.pop()
 with os.scandir(p) as it:
  for e in it:
   n=Path(e.path).relative_to(H).as_posix()
   if n=='MANIFEST01.json':continue
   s=e.stat(follow_symlinks=False);r={'path':n,'mode':stat.S_IMODE(s.st_mode)}
   if stat.S_ISDIR(s.st_mode):r['kind']='directory';pending.append(Path(e.path))
   elif stat.S_ISLNK(s.st_mode):r.update(kind='symlink',target=os.readlink(e.path))
   elif stat.S_ISREG(s.st_mode):assert s.st_size<=4194304;r.update(kind='file',bytes=s.st_size,sha256=sha(Path(e.path).read_bytes()),nlink=s.st_nlink)
   else:raise AssertionError('unexpected special')
   rows.append(r)
rows.sort(key=lambda x:x['path']);save('MANIFEST01.json',{'schema_version':1,'manifest_self_excluded':True,'members':rows,'typed_members':len(rows),'regular_files':sum(x['kind']=='file' for x in rows),'logical_bytes':sum(x.get('bytes',0) for x in rows),'literal_links':sum(x['kind']=='symlink' for x in rows),'negative_hardlink_groups_retained':True})
print(json.dumps({n:sha((H/n).read_bytes()) for n in ['copy_layout01.py','INPUTS01.json','MACHINE01.json','MANIFEST01.json','REPORT01.md']}))
