import hashlib,json,stat,datetime
from pathlib import Path
H=Path(__file__).resolve().parent;sha=lambda b:hashlib.sha256(b).hexdigest()
def put(n,v):(H/n).write_text(json.dumps(v,sort_keys=True,indent=2,allow_nan=False)+'\n')
x=json.loads((H/'READBACK01.json').read_text());q=json.loads((H/'source/REQUEST_DRAFT01.json').read_text());ad=json.loads((H/'ACTUAL_ADMISSION01.json').read_text());assert ad['ready'] is True and ad['source_files']==q['source_files'] and len(ad['inputs'])==8 and ad['registration_sha256']==q['registration_sha256'];C=Path(q['capsule_root'])
(H/'genuine-source').mkdir()
for name in ('job.py','resources.py','financial_wrapper_fixture.py','training.py'):
 p='tradingagents/research/onchain_replication/'+name;b=(C/p).read_bytes();assert len(b)<=4194304 and sha(b)==q['source_files'][p];(H/'genuine-source'/name).write_bytes(b)
put('MACHINE01.json',{'schema_version':1,'decision':'accepted-source-draft-only','reviewer':'combined_worker_review independent of Root author','timestamp_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'parent_sha256':q['caller_sha256'],'request_sha256':sha((H/'source/REQUEST_DRAFT01.json').read_bytes()),'original_parent_sha256':sha((H/'ORIGINAL_PARENT01.py').read_bytes()),'source_inverse_sha256':sha((H/'source/SOURCE_INVERSE01.json').read_bytes()),'actual_source':q['source'],'actual_design_source':q['design_source'],'actual_gate_sha256':q['registration_sha256'],'identity':q['identity'],'phase':'complete100','parent':None,'literal_and_AST_inverse':True,'unchanged_helpers':6,'unchanged_source_bodies':339,'source_pins_excluding_only_gate':338,'inputs':8,'implementation_closure':194,'actual_admission_sha256':sha((H/'ACTUAL_ADMISSION01.json').read_bytes()),'actual_admission_ready':True,'read_only_admission_rerun_by_reviewer':False,'actual_spent_claims':2,'highest_actual_allowance':19,'checks':x['checks'],'check_count_qualification':'repeated bounded source/body authentication assertions included; not independent empirical trials','negative_controls':len(x['refusal_controls']),'complete_previous_review_trees_members':50,'complete_Main_preparation_bodies':9,'failures_retained':[{'script':'check02.py','raw_stderr':'CHECK02.err','cause':'reviewer membership comparison omitted the genuine explicit root dot entry; source bodies/modes had passed; separate check03 fixes enumeration and succeeds'}],'full_recovery':None,'final_review':None,'actual_native_release':None,'actual_parent_attempt':None,'genuine_handles_constructed':False,'numerical_or_project_imports':False,'actual_Source_or_registry_mutation':False,'paper_fit_credit':0,'full100_capacity_verified':False,'actual_context':'original actual admission process history remains NULL; no invented PID/start/group/census'})
report='''# Complete100 Parent source review

**Accepted SOURCE_DRAFT only. No final release.** The installed Parent7f28cee6 and request7f506c00 select the original unused `financial-wrapper-classification-eager-complete100-20261003-01` identity, independent experiment parent null, complete100 phase and actual current=design9dc5c79f. Full recovery and final review are genuinely missing/null. The unmodified request refuses immediately; no preflight, admission, attempt namespace, child or native unit was created by this review.

Seven declared substitutions reconstruct actual predecessor5d5cbdae byte-for-byte and AST-for-AST. Only validate_release and preflight change as functions; the Parent root/identity constants also change explicitly. The six helpers, genuine job._command(args,'launch'),1840-second outer supervisor, original1800-second native guard, limits, pre-dispatch admission ordering, no-numerical-import checks, first-fatal cleanup, descendant/PID-start/cgroup shutdown and terminal semantics are unchanged. The newly added planned-failure pins preserve actual d390/4b2 history alongside old4c54/3515; neither is reopened or coerced complete. Actual current claim count is2/highest19.

All339 current Git entries were joined to current regular bodies and executable classes, and all338 request pins exclude only the actual gate. Gate752c34df,194 implementation closure, eight input roles,251 declared runtime RECORDs and the genuine ready read-only admission6a3b48 rejoin. Original100 epochs/batch16/lookback28/model configuration/training and both null prerequisite roles are retained. Admission6a3 has genuine module origins matching these pins, no Binding/Owner/Run.start/native call, and its original process-history fields remain null. This reviewer did not rerun admission or import the project runtime. Installed scientific package execution and full100 feasibility were not tested.

Twelve finite controls through extracted actual Parent validator functions refuse: unchanged draft; status-only edit with missing final review; genuine receipt put in a wrong role while full recovery remains null; old source/design/identity/phase/Parent or wrong gate; incomplete338/8 maps; and actual budget receipt improperly substituted for both missing proof roles. No synthetic receipt or authority was created. The actual bounded stream reader also verifies a tiny opaque body and refuses an undersized limit. No resource query or launch path was executed. Existing race/currentness and FD/cleanup semantics are inherited unchanged, not asserted universally re-proved by these small controls.

The complete nine-body immutable Main preparation joins manifestbed95bcd and the external installed originals. Root readback6787cd77 is authentic; both applicable25-member review trees authenticate completely, including their explicit root directory mode. One reviewer harness initially omitted that dot root from its comparison and failed; CHECK02.err and check02.py are retained. Independent successor check03 passes without rewriting the failure. Main preparation and prior review completeness are metadata facts, not evidence of a new external recovery.

The exact seven-field final review must still bind this caller, source, identity and complete request contract plus the three genuine proof bodies. Source/caller/full witness external and fresh recovery must be completed and independently accepted, followed by fresh native eligibility before Root's separately released fixed attempt. A past admission receipt or an old failed caller is insufficient. No budget extension above19, refund, identity substitution, native launch, numerical equivalence, full-population storage/RAM claim or paper credit follows. All1420 paper fits remain pending. Economic returns, cashflows, fees/funding and empirical performance were not part of this engineering review.
'''
(H/'REPORT01.md').write_text(report)
rows=[]
for p in sorted(H.rglob('*')):
 s=p.lstat();r={'path':str(p.relative_to(H)),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):r['kind']='directory'
 elif stat.S_ISREG(s.st_mode):
  b=p.read_bytes();assert len(b)<=4194304;r.update(kind='file',bytes=len(b),sha256=sha(b))
 else:raise AssertionError('unexpected local type')
 rows.append(r)
put('MANIFEST01.json',{'schema_version':1,'self_excluded':'MANIFEST01.json','scope':'complete independent Parent source-draft review including raw failed harness','members':rows,'counts':{'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'logical_bytes':sum(r.get('bytes',0) for r in rows)}})
for r in rows:
 p=H/r['path'];assert stat.S_IMODE(p.lstat().st_mode)==r['mode']
 if r['kind']=='file':assert len(p.read_bytes())==r['bytes'] and sha(p.read_bytes())==r['sha256']
print(json.dumps({'manifest_sha256':sha((H/'MANIFEST01.json').read_bytes()),'machine_sha256':sha((H/'MACHINE01.json').read_bytes()),'report_sha256':sha((H/'REPORT01.md').read_bytes()),'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'bytes':sum(r.get('bytes',0) for r in rows)}))
