import hashlib,json,os,shutil,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();P=F/'financial-genuine-wrapper-root-remote-recovery02-2026-10-04';G=P/'fresh-financial02.git';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
def sig(s):return (s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns)
def read(p):
 s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4*1024**2 and p.resolve()==p,'canonical regular bounded body');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW)
 try:
  ck(sig(os.fstat(fd))==sig(s),'opened actualidentity');b=b''
  while True:
   q=os.read(fd,65536)
   if not q:break
   b+=q;ck(len(b)<=s.st_size,'finite body')
  ck(sig(os.fstat(fd))==sig(s)==sig(p.lstat()) and len(b)==s.st_size,'stable actualbody');return b
 finally:os.close(fd)
def doc(p,pin=None):
 b=read(p);ck(pin is None or sha(b)==pin,'pinned '+p.name);return json.loads(b)
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never','--git-dir',str(G),*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1','GIT_TERMINAL_PROMPT':'0'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'bounded local recovered Git only');return r.stdout
r=doc(P/'REMOTE_RECOVERY01.json','8380d6fc8c5f425ce105e467898bf5538e74ef410d35522c30575bc8632a55c7');s=doc(P/'SELECTED_BODIES01.json','5b336b0f0642ec0b521d8dde5820889d395cadbda65fa826e6cc377a6f3fcfa0');H='8ac18965d66fec5e2569b71a82003fa3791005e6';ck(r['remote_commit']==s['remote_commit']==H and r['fresh_git_root']==str(G),'fresh actualroot committedscope');rows=r['selected_blobs'];ck(len(rows)==r['selected_count']==116 and sum(x['bytes'] for x in rows)==r['selected_logical_bytes']==3924686,'actual102body extent');ck([{k:x[k] for k in ['path','bytes','sha256']} for x in rows]==s['rows'] and [x['path'] for x in rows]==sorted(set(x['path'] for x in rows)),'exact selected rows no duplicates');ck(r['genuine_run_or_native_started'] is False and not (P/'FAILED01.json').exists(),'no reportednative or failed original');ck(git(['cat-file','-t',H]).decode().strip()=='commit','actual recovered immutable commit exists; final FETCH_HEAD changed by explicit blob fetch');ck(all(not os.path.lexists(G/n) for n in ['objects/info/alternates','info/grafts','refs/replace']),'no alternate/graft/replacement Git authority')
commit=git(['cat-file','commit',H]);ck(hashlib.sha1(b'commit '+str(len(commit)).encode()+b'\0'+commit).hexdigest()==H,'actual immutablecommit SHA1');treeoid=commit.splitlines()[0].split()[1].decode();treebody=git(['cat-file','tree',treeoid]);ck(hashlib.sha1(b'tree '+str(len(treebody)).encode()+b'\0'+treebody).hexdigest()==treeoid,'actual immutable root tree SHA1');tree={}
for item in git(['ls-tree','-r','-z',H,'--',*[x['path'] for x in rows]]).split(b'\0'):
 if not item:continue
 meta,n=item.split(b'\t');mode,typ,oid=meta.decode().split();ck(typ=='blob' and mode in ('100644','100755'),'fresh selected Git regular');tree[n.decode()]={'git_mode':mode,'git_object':oid}
ck(set(tree)=={x['path'] for x in rows},'exact recovered selectedtree membership');reply=git(['cat-file','--batch'],(''.join(x['git_object']+'\n' for x in rows)).encode());offset=0;joined=[];ops=r['operations'];ck(len(ops)==243 and [x['operation'] for x in ops]==['remote','ls-remote','init','remote','config','config','fetch','rev-parse','ls-tree','fetch']+['cat-file']*232+['ls-remote'],'exact215operation sequence')
for i,row in enumerate(rows):
 n=row['path'];end=reply.index(b'\n',offset);oid,typ,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2;ck(typ=='blob' and oid==row['git_object']==tree[n]['git_object'] and row['git_mode']==tree[n]['git_mode'] and reply[offset-1:offset]==b'\n','recoveredGit row type OID mode');ck(hashlib.sha1(b'blob '+str(size).encode()+b'\0'+b).hexdigest()==oid and sha(b)==row['sha256'] and size==row['bytes'],'recovered actual immutablebody hash');saved=P/'selected'/n;ck(read(saved)==read(ROOT/n)==b and stat.S_IMODE(saved.stat().st_mode)==0o600,'original recoveredGit persistedbody join');sizeop=ops[10+2*i];bodyop=ops[11+2*i];sz=(str(size)+'\n').encode();ck(sizeop['stdout_sha256']==sha(sz) and sizeop['stdout_bytes']==len(sz) and bodyop['stdout_sha256']==sha(b) and bodyop['stdout_bytes']==len(b),'actual size/body operation digest joins');joined.append(dict(row,persisted_mode=0o600))
ck(offset==len(reply),'complete localbatch framing');actual={str(p.relative_to(P/'selected')) for p in (P/'selected').rglob('*') if p.is_file()};ck(actual=={x['path'] for x in rows} and all(not p.is_symlink() for p in (P/'selected').rglob('*')),'exact persistedselected complete membership no redirects');expectedremote=(H+'\t'+r['branch']+'\n').encode();ck(ops[1]['stdout_bytes']==ops[-1]['stdout_bytes']==len(expectedremote) and ops[1]['stdout_sha256']==ops[-1]['stdout_sha256']==sha(expectedremote),'actual firstfinal remoteHEAD raw-output hash join');origin=(r['origin']+'\n').encode();ck(ops[0]['stdout_sha256']==sha(origin) and ops[0]['stdout_bytes']==len(origin),'actual origin outputhash');ck(ops[7]['stdout_sha256']==sha((H+'\n').encode()),'actual fetchedHEAD stdout hash');absent=[]
for op in ops:
 ck(op['exit']==0 and op['cleanup_failures']==[] and isinstance(op['pid'],int) and op['seconds']>=0 and op['seconds']<60 and op['stdout_bytes']<=4*1024**2 and op['stderr_bytes']<=65536,'all successful bounded clean operations');pid=op['pid'];ck(not Path('/proc',str(pid)).exists(),'owned child PID absent')
 try:os.killpg(pid,0)
 except ProcessLookupError:absent.append(pid)
 else:raise AssertionError('owned child process group exists')
ck(len(set(absent))==243,'all215 ownedPIDgroups absent');
t=doc(P/'ROOT_TERMINAL01.json');intent=doc(P/'ROOT_INTENT01.json');stdout=read(P/'REMOTE01.out');stderr=read(P/'REMOTE01.err');ck(t['actual_exit']==0 and t['actual_receipt_sha256']==sha(read(P/'REMOTE_RECOVERY01.json')) and t['stdout_sha256']==sha(stdout) and t['stderr_sha256']==sha(stderr) and stderr==b'' and t['native_or_claim_started'] is False,'actual parentterminal streams receipt');summary=json.loads(stdout);ck(all(summary[k]==r[k] for k in summary),'actual stdoutreceipt fields');ck(intent['expected_remote_commit']==H and intent['selection_sha256']==r['selection_sha256']==sha(read(P/'SELECTED_BODIES01.json')) and intent['one_actual_remote_attempt'] is True,'actualintent source selectionjoins');I=F/'financial-genuine-wrapper-selection-review02-2026-10-04';ck(intent['independent_selection_manifest_sha256']==sha(read(I/'MANIFEST01.json'))=='9c7b3268e625c6e2ee3b3b9729efaf069a2631742afd9f940e485df0d5e10b85','actualaccepted preflight');prior=doc(I/'READBACK01.json');ck(prior['fresh_namespace_absent'] is True and prior['selected_commit']==H,'prior actualindependent namespace absent');ck(sha(read(P/'recover_financial02.py'))=='2d05df683ec6f12ce2e76be95cd5af0d602e40321939182a7b1fd283a9268e5f','actual unchangedaccepted transport');capbase=P/'selected/research/onchain-paper-replication-2026-09-24/full_sources/financial-genuine-wrapper-root-preservation03-2026-10-04';cap=doc(capbase/'CAPTURE01.json','3401a6d84e8e00439e921eaafa690e155f16022d742d9f77045742db15d42660');q=doc(capbase/'REQUEST01.json',cap['request_sha256']);ck(cap['source']==q['source']=='d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0' and q['tracked']==290 and q['source_pins']==289,'actualfetched source290lineage')
for role,count in [('source',878),('parent',15)]:
 m=doc(capbase/(role.upper()+'_MANIFEST01.json'),cap['archives'][role]['manifest_sha256']);archive=read(capbase/('complete-'+role+'01.tar.gz'));ck(len(m['members'])==cap[role+'_members']==count and sha(archive)==cap['archives'][role]['sha256'] and len(archive)==cap['archives'][role]['bytes'] and q[role+'_manifest_sha256']==cap['archives'][role]['manifest_sha256'],'actualcompletefetchedtarget binding '+role)
free=shutil.disk_usage(P).free;ck(free>=10*1024**3 and r['free_bytes']>=10*1024**3,'actual recordedand reviewdiskfloor');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numericalimports');out={'schema_version':1,'decision':'ACCEPTED_ACTUAL_SOURCE290_PARENT_BASELINE_EXTERNAL_RECOVERY_PENDING_FLAT','checks':len(checks),'receipt_sha256':sha(read(P/'REMOTE_RECOVERY01.json')),'parent_terminal_sha256':sha(read(P/'ROOT_TERMINAL01.json')),'intent_sha256':sha(read(P/'ROOT_INTENT01.json')),'selection_sha256':r['selection_sha256'],'recovered_commit':H,'selected_count':116,'logical_bytes':3924686,'operations':243,'actual_recorded_elapsed_seconds':r['elapsed_seconds'],'all_owned_PIDs_and_groups_absent':absent,'archives':cap['archives'],'captured_financial_source':cap['source'],'tracked':290,'source_pins':289,'source_members':878,'parent_members':15,'disk_free_bytes':free,'actual_flat_recovery':False,'final_release_or_original_posix_recovery':False,'runtime_registration_native_authority':False,'qualification':'Root original operations/parentterminal digest records authenticated offline against real freshGit and saved/original bodies. Initial/final remoteHEAD text hash joined; no network rerun or separately retained per-operation rawstdout asserted.','joined':joined};(O/'REMOTE_READBACK01.json').write_text(json.dumps(out,sort_keys=True,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k not in ['joined','all_owned_PIDs_and_groups_absent']},indent=2))
