import ast,hashlib,importlib.util,json,os,stat,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-root-launch-20261004-01');S=P.parent/'genuine-financial-wrapper-native-20261003-01/source';C=F/'financial-genuine-wrapper-root-preservation05-2026-10-04';B=F/'financial-genuine-wrapper-root-final-binding02-2026-10-04';V=F/'financial-genuine-wrapper-final-release-review01-2026-10-04';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
ck(sha((U/'recovery04.py').read_bytes())=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','R4 exact');sys.path.insert(0,str(U));sp=importlib.util.spec_from_file_location('union_review_R',U/'recovery04.py');R=importlib.util.module_from_spec(sp);sp.loader.exec_module(R)
def read(p):return R.read(p.parent,p.name)
def doc(p):return json.loads(read(p))
sm=doc(C/'SOURCE_MANIFEST01.json');pm=doc(C/'PARENT_MANIFEST01.json');vm=doc(C/'REVIEW_MANIFEST01.json');ck(R.scan(S)==sm and R.scan(P)==pm and R.scan(V)==vm,'complete stable three actual scopes');ck((len(sm['members']),len(pm['members']),len(vm['members']))==(878,23,10),'actual 878/23/10');old=doc(F/'financial-genuine-wrapper-root-release-binding01-2026-10-04/PARENT_MANIFEST02.json');rows={r['path']:r for r in pm['members']};ck(all(rows[r['path']]==r for r in old['members']),'all original19 unchanged');ck(set(rows)-{r['path'] for r in old['members']}=={'REQUEST_FINAL03.json','proofs/FINAL_RELEASE_REVIEW01.json','proofs/FINAL_RELEASE_REPORT01.md','proofs/FINAL_RELEASE_MANIFEST01.json'},'only four finalappendages')
q=doc(P/'REQUEST_FINAL03.json');ck(sha(read(P/'REQUEST_FINAL03.json'))=='dc80a4dff93fbf3261bdf151076c1420630ed38926ab7094d60eb1902bde25bc' and read(P/'REQUEST_FINAL03.json')==read(B/'REQUEST_FINAL03.json'),'actual final request');before=doc(P/'REQUEST_CANDIDATE02.json');ck({k for k in q if q[k]!=before[k]}=={'final_review'},'only actual final review reference changes');ck(sha(R.encode({k:v for k,v in q.items() if k!='final_review'}))=='6884fa8027cf49b519f5c635828244d4685ce0f989691593e816792e2586704a','contract unchanged')
for n,orig in [('FINAL_RELEASE_REVIEW01.json','RELEASE_REVIEW01.json'),('FINAL_RELEASE_REPORT01.md','REVIEW01.md'),('FINAL_RELEASE_MANIFEST01.json','MANIFEST01.json')]:ck(read(P/'proofs'/n)==read(V/orig),'actual final proof copy '+n)
ck(q['final_review']=={'path':str(P/'proofs/FINAL_RELEASE_REVIEW01.json'),'sha256':sha(read(V/'RELEASE_REVIEW01.json'))},'exact genuine review reference');m=doc(V/'MANIFEST01.json');ck(len(m['entries'])==9 and {p.name for p in V.iterdir()}=={r['path'] for r in m['entries']}|{'MANIFEST01.json'},'manifest self-exclusion explains10')
for r in m['entries']:
 p=V/r['path'];ck(stat.S_IMODE(p.lstat().st_mode)==r['mode'] and len(read(p))==r['bytes'] and sha(read(p))==r['sha256'],'all9original reviewed bodies unchanged')
validation=doc(B/'VALIDATION01.json');ck(validation['actual_exit']==0 and validation['launch_requested'] is False and validation['native_preflight_performed'] is False and '--launch' not in validation['actual_argv'] and not Path('/proc',str(validation['actual_pid'])).exists(),'Root original defaultvalidation record closed');ck(read(B/'VALIDATE01.out')==read(B/'VALIDATE01.err')==b'','actual empty validation streams');ck(not (P/'attempt').exists() and all(not (S/n).exists() for n in ['research_runs','research_artifacts','fixture_outer']),'no launch reservation outputs')
oldC=F/'financial-genuine-wrapper-root-preservation04-2026-10-04';source=read(C/'capture05.py');oldsource=read(oldC/'capture04.py');ck(sha(source)=='1f96344ff0e7bacf6aa0ab24d314f05f3e5abbc67aa53c2130d260e355f6d2fc' and sha(oldsource)=='a90da3397a1a2055689c98ef667f8f477da300424548306f2de5205ee4bd6820','exact current and preserved failed source')
inverse=source.replace(b'financial-genuine-wrapper-final-union-capture-review02-2026-10-04',b'financial-genuine-wrapper-final-union-capture-review01-2026-10-04').replace(b"len(review_manifest['members'])==10",b"len(review_manifest['members'])==9").replace(b'exact final23/10 scope',b'exact final23/9 scope');ck(inverse==oldsource and ast.dump(ast.parse(inverse))==ast.dump(ast.parse(oldsource)),'entire byte and AST inverse exactly route/count/errorlabel')
for name in ['SOURCE_MANIFEST01.json','PARENT_MANIFEST01.json','REVIEW_MANIFEST01.json']:ck(read(C/name)==read(oldC/name),'all3 prepared manifests unchanged')
for d in (C,oldC):ck(all(not (d/n).exists() for n in ['REQUEST01.json','INTENT01.json','CAPTURE01.json','complete-source01.tar.gz','complete-parent01.tar.gz','complete-review01.tar.gz']),'fresh successor/no old rerun')
tree=ast.parse(source);main=next(n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='main');condition=next(n for n in ast.walk(main) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and n.func.attr=='require' and len(n.args)==2 and isinstance(n.args[1],ast.Constant) and n.args[1].value=='exact final23/10 scope');compiled=compile(ast.fix_missing_locations(ast.Module(body=[ast.Expr(value=condition)],type_ignores=[])),str(C/'capture05.py'),'exec');exec(compiled,{'R':R,'parent_manifest':pm,'review_manifest':vm});ck(True,'GREEN exact actual23/10 assertion')
refusals=[]
for field,value in [('review_manifest',dict(vm,members=vm['members'][:-1])),('parent_manifest',dict(pm,members=pm['members'][:-1]))]:
 ns={'R':R,'parent_manifest':pm,'review_manifest':vm};ns[field]=value
 try:exec(compiled,ns)
 except ValueError as e:refusals.append({'changed':field,'error':str(e)})
 else:raise AssertionError('wrong cardinality accepted')
ck(len(refusals)==2,'GREEN refuses incomplete9review/22parent')
text=source.decode();ck(text.index("R.same(SOURCE,source_manifest)")<text.index("R.put(HERE/'REQUEST01.json'") and text.index("a.review_manifest_sha256,'exact independent")<text.index("R.put(HERE/'REQUEST01.json'"),'allscopes and exact independent review pinned beforewrites');ck("for label,root,m in [('source',SOURCE,source_manifest),('parent',PARENT,parent_manifest),('review',FINAL_REVIEW,review_manifest)]" in text and text.count('R.same(SOURCE,source_manifest);R.same(PARENT,parent_manifest);R.same(FINAL_REVIEW,review_manifest)')==2,'exact three targets and complete before-after comparisons');ck("R.require(not os.path.lexists(HERE/'INTENT01.json')" in text and "R.pack(root,m,HERE/('complete-'+label+'01.tar.gz'))" in text,'fresh intent and exclusive actual archives');ck("'continuous_floor_watch_claim':False" in text and "free>=R.FLOOR" in text and "floor();archives[label]=R.pack" in text and "floor()\n floor();R.same" in text,'observed floor beforeafter pack no continuous claim');ck("'final_release_recovered':False" in text and "'native_authority':False" in text and "'claim_started':False" in text,'capture only flags honest')
pins=next(n.value for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='PINS' for t in n.targets));pins=ast.literal_eval(pins)
for name,pin in pins.items():ck(sha(read(U/name))==pin,'unchanged exactprimitive '+name)
ck(R.FILE==4*1024**2 and R.BASE==128*1024**2 and R.INFLATED==192*1024**2 and R.PAX==8192 and R.FLOOR==10*1024**3,'unchanged concrete bounds');ck(all(not C.is_relative_to(root) and not root.is_relative_to(C) for root in [S,P,V]),'outputs disjoint from allthreeinputroots')
for m in (sm,pm,vm):R.validate(m);ck(sum(r.get('bytes',0) for r in m['members'])<=R.BASE and all(r.get('bytes',0)<=R.FILE for r in m['members']),'actual declared scope withinbounds')
# Genuine helper first-fatal control with ordinary cleanup and no filesystem writes.
fatal=KeyboardInterrupt('review sentinel');seen=[]
def ordinary():seen.append('ordinary');raise OSError('review ordinary cleanup')
def tail():seen.append('tail')
try:
 try:raise fatal
 finally:R._cleanup((ordinary,tail))
except BaseException as e:ck(e is fatal and seen==['ordinary','tail'],'real firstfatal identity/all cleanup callbacks')
else:raise AssertionError('fatal hidden')
ck(R.scan(S)==sm and R.scan(P)==pm and R.scan(V)==vm,'final allthree actual scopes stable');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas','tradingagents'} for n in sys.modules),'no numerical/lifecycle imports')
result={'schema_version':1,'decision':'ACCEPTED_EXACT_FINAL_COMPOSITION_AND_THREE_TARGET_CAPTURE_SOURCE_ONLY','checks':len(checks),'source_sha256':sha(source),'original_withheld_sha256':sha(oldsource),'source_members':878,'parent_members':23,'review_members':10,'source':'d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0','final_request_sha256':sha(read(P/'REQUEST_FINAL03.json')),'contract_sha256':'6884fa8027cf49b519f5c635828244d4685ce0f989691593e816792e2586704a','exact_inverse':['independent review route','review count9to10','diagnostic23/9to23/10'],'refusals':refusals,'actual_capture_executed':False,'native_preflight_performed':False,'final_union_recovered':False,'capacity_verified':False,'native_authority':False};(O/'READBACK01.json').write_bytes(R.encode(result));print(json.dumps(result,indent=2))
