from pathlib import Path
import json,hashlib
D=Path(__file__).resolve().parent;F=D.parent;M=F.parents[2];S=M/'research/onchain-paper-replication-2026-09-24/storage/real-pilot-fourth-graph-preservation-20261006-01'
sha=lambda b:hashlib.sha256(b).hexdigest();read=lambda p:json.loads(p.read_bytes())
c=read(D/'OUTCOME_CHECK01.json');e=c['evidence'];t=read(S/'ROOT_TERMINAL01.json');b=read(D/'ACTUAL_TERMINAL_BINDING01.json');f=read(S/'guard01/final.json');env=read(S/'envelope01.json');run=read(S/'ROOT_RUNNING01.json')
assert sha((S/'ROOT_TERMINAL01.json').read_bytes())==b['root_terminal_sha256']
assert run['actual_remote_head']==run['source_commit']==t['source_commit']==b['source'] and run['actual_push_exit_code']==run['actual_remote_readback_exit_code']==0
for path,pin in env['source_files'].items():
 p=M/path;assert p.stat().st_size<4*1024**2 and sha(p.read_bytes())==pin;e[path]=pin
for r in [env['environment'],*env['evidence']]:
 p=M/r['path'];assert p.stat().st_size<4*1024**2 and sha(p.read_bytes())==r['sha256'];e[r['path']]=r['sha256']
rdir=F/'real-data-pilot-fourth-graph-post-recovery-retirement-preparation01-2026-10-06';inv=read(rdir/'INVERSE01.json');before=(M/inv['baseline']).read_bytes();after=(rdir/'retire01.py').read_bytes();assert sha(before)==inv['before_sha256'] and sha(after)==inv['after_sha256'];x=after.decode()
for edit in reversed(inv['literal_edits']):x=x.replace(edit['after'],edit['before'])
assert x.encode()==before
execution={'session':5005,'initial_tool_chunk':'4c3708','completion_tool_chunk':'1592cc','exit_code':0,'recovered_six_passes':1,'original_six_passes':0,'metadata_only_source_joins':12,'retirement_source_exact_inverse':True,'observed_preparation_missing_legacy_name':'ROOT_PREPARATION01.json absent; actual ROOT_BINDING01.json used, no checker/hash failure'}
(D/'ACTUAL_CHECK_EXECUTION01.json').write_text(json.dumps(execution,indent=2)+'\n')
for n in ('ACTUAL_CHECK_EXECUTION01.json','ACTUAL_TERMINAL_BINDING01.json','OUTCOME_CHECK01.json','RECOVERED_PAYLOAD_HASH01.json','INVERSE01.json','check_outcome01.py'):
 p=D/n;e[str(p.relative_to(M))]=sha(p.read_bytes())
review={'schema_version':1,'decision':'accepted','identity':b['identity'],'full_scope_byte_recovery':True,'count':36,'bytes':c['bytes'],'directories':8,'successful_get_receipts':73,'retirement_executed':False,'retirement_release':False,'retirement_only_paths':c['retirement_only_paths'],'retirement_payload_bytes':c['retirement_payload_bytes'],'evidence':e,'actual_root_tool':{'session':50000,'chunk':'af517e','exit_code':0},'actual_native':{'phase':f['phase'],'child_exit_code':f['child_exit_code'],'cleanup_verified':f['cleanup_verified'],'elapsed_seconds':f['elapsed_seconds'],'original_cleanup_stop_returncode':f['cleanup_stop_returncode'],'last_unit_kernel_peak_bytes':f['optional_memory_telemetry']['unit']['kernel_peak_bytes'],'sampled_memory_current_peak_bytes':f['peak_sampled_memory_current_bytes'],'high_events':f['memory_events']['high'],'max_events':f['memory_events']['max'],'oom_events':f['memory_events']['oom'],'unit_swap_current_bytes':f['optional_memory_telemetry']['unit']['swap_current_bytes'],'minimum_sampled_volume_free_bytes':min(f['minimum_sampled_disk_free_bytes'].values())},'cleanup':{'selected_recorded_pids_absent':76,'cgroup_absent':True,'unit_inactive_dead_mainpid_zero':True,'complete_lifetime_pid_history':'unknown'},'qualification':['Full actual BYTE recovery and original path/name/mode descriptors; not POSIX reconstruction or restored runtime execution. Directories joined through original selection, no invented complete.directories key.','One independent recovered-six streamed SHA pass (3720674424 bytes), original-six prior proof reused with current stats; 30 small controls compared exactly. All 73 get receipts and original native/outer/Root joins accepted.','Kernel memory peak includes charged cache and differs from sampled memory; ancestor memory is not job-only, whole-volume sampled free space includes unrelated activity. Original cleanup stop return code5 remains.','Historical full-get success is verified, not perpetual current remote availability. No numerical/scientific capacity, paper claim or financial-return conclusion. Concrete retirement release remains separate and requires actual bound caller.']}
(D/'REVIEW01.json').write_text(json.dumps(review,indent=2,sort_keys=True)+'\n')
(D/'REPORT01.md').write_text('Accepted actual May23 backup: 36 files / 3,720,766,030 bytes and 8 selection-directory descriptors, with 73 successful body/restore/completion get receipts. One independent recovered-six SHA pass covered 3,720,674,424 bytes in 7.05 seconds; original six bodies were not reread. Exact original name/mode restoration metadata and all current original/recovered stat joins passed.\n\nRoot50000/af517e exit0 is distinct from original outer/child0. Native elapsed1853.106634626s; original cleanup stop5 retained; 76 selected recorded PIDs absent, unit inactive/dead/MainPID0 and cgroup absent. Lifetime PID completeness remains unknown. Kernel cache-inclusive peak203,489,280B differs from sampled202,502,144B; high20,849/maxOOM0/swap0, minimum sampled whole-volume free11,978,375,168B. Ancestor and unrelated volume activity are not workload-only measurements.\n\nTwelve source pins and original remote-readback/source receipts joined. The concrete ledger source differs from its accepted predecessor only by declared fixed identity/date/ledger extent/flag edits. BYTE recovery with path/name/mode descriptors does not claim POSIX reconstruction, current remote permanence, scientific capacity or retirement execution. The two prospective ledger retirement paths total6,437,658,624B; release awaits Root\'s bound caller request.\n')
members={str(p.relative_to(D)):{'sha256':sha(p.read_bytes()),'bytes':p.stat().st_size} for p in sorted(D.iterdir()) if p.is_file() and p.name!='MANIFEST01.json'}
(D/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'status':'SEALED_ACTUAL_BYTE_OUTCOME_REVIEW','members':members},indent=2,sort_keys=True)+'\n')
print(json.dumps({n:sha((D/n).read_bytes()) for n in ['REVIEW01.json','RECOVERED_PAYLOAD_HASH01.json','MANIFEST01.json']}))
