from pathlib import Path
import hashlib,json,stat
D=Path(__file__).resolve().parent;F=D.parent;S=F/'heartbeat-root-checkpoint10-2026-10-04/root_compatibility_gate_preview01.py';h=lambda b:hashlib.sha256(b).hexdigest();actual=json.loads((D/'ACTUAL_SOURCE_METADATA01.json').read_bytes());w=json.loads((D/'WITNESSES01.json').read_bytes())
def put(n,o):(D/n).write_text(json.dumps(o,sort_keys=True,indent=2)+'\n')
assert h(S.read_bytes())=='845e744580b45228e9bcb19925dd9d4ed851ea6912e246287b6e447c6c620de6'
findings=[{'id':'GP1','priority':'P2','file':str(S),'line':54,'additional_lines':[59,66,68,69,70,75,79,80,81],'title':'Prepared science and experiment fields have no independent byte binding','issue':'Draft and prepared input bodies are not pinned to their frozen preparation. Body hashes are accepted from the same unpinned draft. Exact extracted predicates accept coherent epochs100to99, seed11to12, eager-to-selected execution changes, a removed cumulative_budget_extension, and a foreign experiment family. Source/input counts and historical12 preservation remain satisfied.','impact':'The preview can emit a internally consistent but scientifically or accounting-incompatible prospective gate while reporting the intended fixed identity/20 allowance. Later admission may reject it; this is not a demonstrated numerical-admission bypass.','required_fix':'Before using them, authenticate the exact current frozen draft, preparation binding, and all13 prepared body path/size/hash pins independently of their own references. Rejoin required family, model/training/recipe/job/plan/runtime/closure/review roles, charter/runtime hashes and cumulative extension/review paths to that pinned draft.'},{'id':'GP2','priority':'P2','file':str(S),'line':89,'additional_lines':[51,52,57,78],'title':'Current failed-history maximum is emitted without a current history predicate','issue':'actual_highest19 is a literal output field. Source reads no claim.json or failed.json and only checks absence of the fresh identity; git status explicitly ignores untracked files. The actual three FAILED identities are true at review time but their exact claim/failed hashes and disposition are not rejoined by the preview.','impact':'A later change to the lifecycle namespace can leave the preview reporting the old spent count/highest allowance with no refusal, contrary to the stated exact preview contract. No actual lifecycle file was modified to demonstrate this static omission.','required_fix':'Bind the exact three claim and failed-body identities/hashes/families/effective allowances, reject complete/active/extra identities, and derive spent3/highest19 under unchanged base18/prior0 before output. Preserve all historical records and prospective20 substance.'}]
put('FINDINGS01.json',{'schema_version':1,'decision':'WITHHELD_GATE_PREVIEW_PREPARATION_AND_HISTORY_BINDING','source_sha256':h(S.read_bytes()),'findings':findings})
report='''# Gate preview source review01

WITHHELD_GATE_PREVIEW_PREPARATION_AND_HISTORY_BINDING for exact source845e744580b45228e9bcb19925dd9d4ed851ea6912e246287b6e447c6c620de6. No public preview or proof-validation block was run, no accepted authority body was constructed, and no gate/admission/source/claim was written. Findings concern preparation validity, not an observed numerical admission bypass.

GP1 (P2), root_compatibility_gate_preview01.py:54–81: the draft and13 prepared input bytes lack independent frozen pins. The checks compare bodies to hashes from the same draft. Eleven executions of the exact extracted AST statements at lines66–83 comprise one unchanged metadata control, five coherent mutation witnesses and five genuine inverse refusals. Training epochs100→99, recipe seed11→12, eager→selected execution, removal of cumulative_budget_extension, and a foreign family all pass. The per-file/role/source cardinalities still pass, and the12 old experiment definitions remain identical. An opaque non-proof byte marker was used only to satisfy the skipped post-authority component interface; neither the proof parser nor public preview was executed, and no assembled gate or marker was written as an authority artifact. Pin the exact draft, preparation binding and all13 fixed body paths/sizes/hashes before parsing/use; rejoin experiment family and extension/review references. Downstream genuine fixed-method validators may still reject such a gate, so no successful relaxation is claimed.

GP2 (P2), line89: actual_highest19 is printed literally without any current claim/failed-body read or exact namespace check. Lines51–52 only verify source HEAD/tracked cleanliness, and line57 checks the one future namespace. The true actual three FAILED/spent identities and maximum19 were independently read and hashed in this review, but the preview does not enforce those predicates before output. Add exact current historical claim/failure hashes, family/effective allowance joins and complete/active/extra-identity refusals. Derive the output from those observations under base18/prior0. No original lifecycle record was changed for this finding.

Positive source/metadata evidence: actual CAP HEAD7b056 is clean for tracked files;340 distinct tracked paths and all195 operational target bodies authenticate. The original gate752c has12 definitions, base18/prior0. Current preparation has13 bodies/10 roles; all10 role/body pins presently agree. Fixed complete100 identity, parentNone, reference cell and absent current new-gate/run namespaces are correct. Original model20f451/trainingd527 and recipe/plan/job/runtime bytes are currently the intended originals. The exact b5ac/07100/461d budget bytes are enforced by the assembly segment; this does not substitute for linking the experiment's own extension descriptor.

Independently derived arithmetic is correct:340 existing paths plus15 distinct new paths =355 prospective tracked paths; excluding only the new gate gives354 source pins. Original gate bytes remain among existing source pins, and all12 old experiment definitions compare equal after in-memory assembly. No concrete gate artifact is emitted by this review.

The preview canonical encoder exactly matches the actual d0d770 helper and the preclaim canonical function for ordinary opaque input and both complete maps. Canonical historical hash ebb1727c and target hash2e281f7c match. This check concerns the encoder only; it does not accept the separately withheld preclaim Reader. The seven-field recovery proof schema and role name structurally agree with the helper. The source requires machine/proof/report hashes and manifest members plus receipt references inside the same manifest root. Genuine accepted composed recovery remains a separate prerequisite; a decision string alone is not evidence. Actual future recovery arguments, their independent authorship, full body composition and the eventual gate/Admission were not dynamically exercised here.

The first reviewer harness attempt rejected an overly broad AST safety assertion because source_files.update is an ordinary allowed in-memory call. Its exact check01.py and CHECK01 stderr are retained. check02 narrows that extraction assertion to allow only update expressions; the actual author statements and source bytes remain unchanged. No author source defect was hidden by that harness correction.

No numerical/financial computation, arrays or checkpoint deserialization, network access, actual restoration, Owner/Run construction, registration/budget adoption, Root/liveCAP/STATE edit or genuine proof fabrication occurred. Timing leakage, returns/cashflows, exposure, fees/funding and scientific performance are outside this source-only review. Full final Parent/recovery/preclaim/native release remains unavailable from this review. A new separately frozen source must resolve GP1/GP2 and receive its own exact review; source01 is preserved.
'''
(D/'REPORT01.md').write_text(report)
put('MACHINE01.json',{'schema_version':1,'decision':'WITHHELD_GATE_PREVIEW_PREPARATION_AND_HISTORY_BINDING','source':str(S),'source_sha256':h(S.read_bytes()),'findings':findings,'metadata_checks':len(actual['controls']),'extracted_component_cases':len(w['cases']),'coherent_mismatches_accepted':5,'genuine_inverse_refusals':5,'current_tracked':340,'target_implementation':195,'new_files':15,'prospective_tracked':355,'source_pins':354,'original_experiments':12,'actual_failed':3,'actual_highest':19,'prospective20_adopted':False,'canonical_map_encoding_agrees':True,'actual_preview_invoked':False,'accepted_authority_body_fabricated':False,'numerical_authority':False,'readback_sha256':h((D/'ACTUAL_SOURCE_METADATA01.json').read_bytes()),'witness_sha256':h((D/'WITNESSES01.json').read_bytes()),'report_sha256':h((D/'REPORT01.md').read_bytes())})
rows=[]
for p in sorted(D.rglob('*')):
 if p==D/'MANIFEST01.json':continue
 s=p.lstat();x={'path':p.relative_to(D).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):x['kind']='directory'
 else:assert stat.S_ISREG(s.st_mode) and s.st_nlink==1;x.update(kind='file',bytes=s.st_size,sha256=h(p.read_bytes()))
 rows.append(x)
put('MANIFEST01.json',{'schema_version':1,'manifest_self_excluded':True,'members':rows})
print(json.dumps({n:h((D/n).read_bytes()) for n in ['MACHINE01.json','MANIFEST01.json','REPORT01.md','WITNESSES01.json']},sort_keys=True))
