import ast,gzip,hashlib,io,json,os,stat,sys,tarfile
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=F/'financial-genuine-wrapper-root-claimedrun-source339-capture01-2026-10-04';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';sys.path.insert(0,str(U));import recovery04 as a
sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
def read(p):return a.read(p.parent,p.name)
for name,pin in [('recovery04.py','b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a'),('owned_io.py','09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb'),('bounded_git01.py','db4a65a450bf9930abac04ab794539ebd952b07826d7314b4aea4e989dd9240f')]:ck(sha(read(U/name))==pin,'accepted primitive body')
t=ast.parse(read(F/'held-consumer-final-released-scope-capture-review01-2026-10-03/check01.py'));exec(compile(ast.Module(body=[n for n in t.body if isinstance(n,ast.FunctionDef) and n.name in ('decode','recode')],type_ignores=[]),'<independent bounded framing>','exec'))
c=json.loads(read(P/'CAPTURE01.json'));m=json.loads(read(P/'source-manifest.json'));S=Path(c['source_root']);raw=read(P/'source.tar.gz');ck(sha(raw)=='b5b6aad2f515447dc6566cfb716a20ef90031313d48f1ac903ab756735431e24' and sha(read(P/'source-manifest.json'))=='fdf77348b81a4d6df8b420b98530f5485900a0461636e1c201506106b036dfd8','actual archive/manifest supplied pins');ck(c['archive']=={'bytes':len(raw),'sha256':sha(raw),'manifest_sha256':sha(read(P/'source-manifest.json'))},'actual receipt archive join');ck(a.scan(S)==m==json.loads(read(O/'current-source02.manifest.json')),'full fresh current/census/capture scopes identical');bodies,framing=decode(raw,m)
for r in m['members']:
 p=S/r['path'];s=p.lstat();ck(stat.S_IMODE(s.st_mode)==r['mode'],'literal original mode')
 if r['kind']=='file':ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and read(p)==bodies[r['path']],'every original opaque file exactly archived')
 else:ck(stat.S_ISDIR(s.st_mode),'original directory type')
ck(recode(m,bodies)==raw,'full canonical compressed byte inverse');ck(a.scan(S)==m,'full stable current tree after all reads');ck(len(m['members'])==1029 and sum(r['kind']=='file' for r in m['members'])==747,'complete actual denominator');prior=json.loads(read(O/'CENSUS01.json'));ck(prior['known_scopes'][0]['projected_archive_sha256']==sha(raw),'independent precapture in-memory projection exact');ck(c['current_equals_design']==prior['source'] and c['tracked']==339 and c['registered_pins']==338 and c['input_roles']==8,'current source/census joins');ck(c['original_spent_claims']==1 and c['new_claim_started'] is False and c['parent_or_final_review_captured'] is False,'honest copied history and absent finalParent scope');ck(c['disk_free_after_bytes']>=a.FLOOR,'actual receipt observed postpack floor');ck(not any(n.split('.')[0] in {'torch','numpy','scipy'} for n in sys.modules),'no numerical import')
x={'schema_version':1,'decision':'ACCEPTED_ACTUAL_COMPLETE_SOURCE339_LOCAL_BYTE_CAPTURE_ONLY','source':c['current_equals_design'],'capture_sha256':sha(read(P/'CAPTURE01.json')),'caller_sha256':sha(read(P/'CAPTURE01.py')),'archive':c['archive'],'members':1029,'regular_bodies':747,'logical_bytes':sum(r.get('bytes',0) for r in m['members']),'tracked':339,'registered_pins':338,'implementation':194,'package':149,'genuine_spent_identity_count':1,'highest_actual_claim_budget':18,'checks':len(checks),'framing':framing,'reported_tool_execution':{'session':81263,'start':'60814b','completion':'4b9adb','exit':0,'source':'Root message; not an independently saved OS process receipt'},'original_pid_startticks_process_group_history':'unavailable; tool session is not OS PID','capture_caller_qualification':'Generic scan/pack; initial and postpack disk observations only; ordinary git check_output has no explicit timeout. No continuous disk watch or general process-history guarantee. Full actual byte result independently verified.','external_recovery':False,'final_parent_or_final_review_capture':False,'runtime_body_recovery':False,'POSIX_reinstantiation':False,'numerical_or_capacity_release':False};(O/'ACTUAL_SOURCE_CAPTURE_READBACK02.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');print(json.dumps(x,sort_keys=True))
