import hashlib,json,stat
from pathlib import Path
O=Path(__file__).resolve().parent;c=json.loads((O/'CENSUS01.json').read_text());a=json.loads((O/'ACTUAL_SOURCE_CAPTURE_READBACK02.json').read_text())
report=['# Independent current scope census and actual Source339 capture review','', 'The actual complete Source339 local byte capture is accepted narrowly. All 1,029 typed members, 747 regular bodies, literal modes, full Git bytes and copied genuine failed history match the fresh current tree. The whole bounded raw gzip/TAR stream was independently framed and recompressed byte-for-byte. This is not external recovery, a final Parent closure, runtime-body recovery, admission, capacity or numerical release.','',f"Census checks: {c['checks']}; actual archive checks: {a['checks']}. Current=design {a['source']}; 339 tracked, 338 source pins, 194 implementation /149 package bodies. One copied genuine spent identity remains one global claim; its highest actual budget is 18.",'','| Known scope | Typed | Files | Links | Logical bytes | Projected canonical archive |','|---|---:|---:|---:|---:|---:|']
for r in c['known_scopes']:report.append(f"| {r['name']} | {r['members_excluding_root']} | {r['regular']} | {r['lexical_links']} | {r['logical_bytes']} | {r['projected_canonical_archive_bytes']} |")
report+=['','The 16 known roots total 20,054,603 logical bytes; their individually projected canonical opaque archives total 9,043,445 bytes and each fits 4 MiB. These projections are feasibility measurements, not saved archives or external backups. Thirteen literal-link witnesses must be preserved as archive metadata without following or instantiating targets. All 364 frozen original manifest member joins were checked.','', 'A provisional 58-path /127-operation packaging estimate includes six legacy Source325 supplemental bodies and three records per known tree. This is not a closed final selection: the newly frozen Parent preparation, its independent review, actual installed Parent/proofs/final request, Root composition/validation, applicable original verifier witnesses, this review and later exact recovery evidence must be added. Preserve the full original witnesses, not copied manifest references alone. Existing helper bounds are 506 paths, 64 MiB selected aggregate, 4 MiB each and 1,024 finite operations.','', 'The failed Source01 partial clone archive and its entire Root preparation are included; its 32-mode failure remains immutable. Successful Source02 history copy and the separate assembly typo failure/success and source generation are included. No original failed identity, source or attempt is reused or erased. Prior Source649 postfailure remote61ce/flatd4a closure remains historical and cannot substitute for new Source339.','', 'The actual Source339 capture caller checks free disk before work and after packing, but does not provide continuous monitoring; its ordinary Git check has no explicit timeout. The completed bytes are independently verified. Original OS PID/tick/group evidence is unavailable, and the tool session is never treated as PID. Root reported session81263/start60814b/completion4b9adb exit0; no saved terminal body existed when reviewed.','', 'No source mutation, numerical import, admission, claim, capture replay, network or recovery was performed. The newly available Parent candidate is a separate next review; no final Parent or launch acceptance is inferred here.']
(O/'REPORT01.md').write_text('\n'.join(report)+'\n');members=[]
for p in sorted(O.rglob('*')):
 s=p.lstat();r={'path':p.relative_to(O).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISREG(s.st_mode):b=p.read_bytes();r.update(kind='file',bytes=len(b),sha256=hashlib.sha256(b).hexdigest())
 elif stat.S_ISDIR(s.st_mode):r['kind']='directory'
 else:raise AssertionError(p)
 members.append(r)
(O/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'members':members},sort_keys=True,indent=2)+'\n')
for n in ['CENSUS01.json','ACTUAL_SOURCE_CAPTURE_READBACK02.json','REPORT01.md','MANIFEST01.json']:print(n,hashlib.sha256((O/n).read_bytes()).hexdigest())
