from pathlib import Path
import difflib,json,hashlib
D=Path(__file__).resolve().parent;F=D.parent;P=Path('tradingagents/research/onchain_replication');T=D/'candidate'/P
bases={n:F/'real-data-pilot-full-size-policy01-2026-10-05/candidate'/P/n for n in ('job.py','resources.py')}
bases['real_pilot_import_caller.py']=F/'real-data-pilot-throughput-measurement01-2026-10-05/candidate'/P/'real_pilot_import_caller.py'
edits={}
def build(name,changes):
 s=bases[name].read_text();old=s;records=[]
 for a,b in changes:
  assert s.count(a)==1,(name,a,s.count(a));s=s.replace(a,b);records.append({'old':a,'new':b})
 (T/name).write_text(s);(D/(name+'.patch')).write_text(''.join(difflib.unified_diff(old.splitlines(True),s.splitlines(True),fromfile='baseline/'+name,tofile='candidate/'+name)))
 inverse=s
 for r in reversed(records):assert inverse.count(r['new'])==1;inverse=inverse.replace(r['new'],r['old'])
 assert inverse==old
 edits[name]={'baseline':str(bases[name]),'baseline_sha256':hashlib.sha256(old.encode()).hexdigest(),'candidate_sha256':hashlib.sha256(s.encode()).hexdigest(),'replacements':records}
build('resources.py',[
 ('def _native_owned_env(cwd):','def _native_owned_env(cwd,storage_budget=None):'),
 ("    return {'PYTHONPATH':str(root),", "    result={'PYTHONPATH':str(root),"),
 ("'NUMEXPR_NUM_THREADS':'2'}\n\n\ndef _native_seconds", "'NUMEXPR_NUM_THREADS':'2'}\n    if storage_budget is not None and storage_budget.get('schema_version')==2:\n        from tradingagents.research.onchain_replication.real_pilot_storage import validate,environment\n        validate(storage_budget,root);return environment(root,result)\n    return result\n\n\ndef _native_seconds"),
 ('def _native_ready(policy,ready,properties,wall_seconds,cwd):','def _native_ready(policy,ready,properties,wall_seconds,cwd,storage_budget=None):'),
 ("ready.get('native_environment')!=_native_owned_env(cwd)","ready.get('native_environment')!=_native_owned_env(cwd,storage_budget)"),
 ("            ready['native_environment']={key:os.environ.get(key) for key in _native_owned_env(Path.cwd())}\n            if ready['native_environment']!=_native_owned_env(Path.cwd()):", "            budget=json.loads((receipt/'live.json').read_text()).get('storage_budget')\n            ready['native_environment']={key:os.environ.get(key) for key in _native_owned_env(Path.cwd(),budget)}\n            if ready['native_environment']!=_native_owned_env(Path.cwd(),budget):"),
 ("        if type(storage_budget) is not dict or set(storage_budget)!={'root','limits'}:\n            raise ValueError('storage budget schema differs')\n        storage_watch=StorageWatch(storage_budget['root'],storage_budget['limits'])", "        if type(storage_budget) is dict and storage_budget.get('schema_version')==2:\n            from tradingagents.research.onchain_replication.real_pilot_storage import WritableUnion,EXPERIMENT\n            if native_unit_limits is None or not isinstance(owner_identity,dict) or owner_identity.get('experiment')!=EXPERIMENT:raise ValueError('union requires fixed real-pilot native owner')\n            storage_watch=WritableUnion(storage_budget,Path(cwd))\n        else:\n            if type(storage_budget) is not dict or set(storage_budget)!={'root','limits'}:\n                raise ValueError('storage budget schema differs')\n            storage_watch=StorageWatch(storage_budget['root'],storage_budget['limits'])"),
 ("        state['storage_budget']={'root':str(storage_watch.root),'limits':dict(storage_watch.limits)}\n        state['storage_root_identity']=list(storage_watch.identity)", "        if hasattr(storage_watch,'budget'):\n            state['storage_budget']=storage_watch.budget\n            state['storage_watched_root_identities']=storage_watch.identities\n        else:\n            state['storage_budget']={'root':str(storage_watch.root),'limits':dict(storage_watch.limits)}\n            state['storage_root_identity']=list(storage_watch.identity)"),
 ("for key,value in _native_owned_env(cwd).items()", "for key,value in _native_owned_env(cwd,storage_budget).items()"),
 ("_native_ready(native_unit_limits,ready,state['native_unit_properties'],wall_seconds,cwd)","_native_ready(native_unit_limits,ready,state['native_unit_properties'],wall_seconds,cwd,storage_budget)"),
 ("if {key:os.environ.get(key) for key in _native_owned_env(Path.cwd())}!=_native_owned_env(Path.cwd()):raise RuntimeError('native worker environment differs')", "if {key:os.environ.get(key) for key in _native_owned_env(Path.cwd(),live.get('storage_budget'))}!=_native_owned_env(Path.cwd(),live.get('storage_budget')):raise RuntimeError('native worker environment differs')")])
build('job.py',[
 ('def resource_policy(value, root):','def resource_policy(value, root, *, pilot_context=None):'),
 ("        if type(budget) is not dict or set(budget)!={'root','limits'} or type(budget['root']) is not str:\n            raise ValueError('registered storage budget schema differs')\n        watch=StorageWatch(budget['root'],budget['limits'])\n        if not watch.root.is_relative_to(Path(root).resolve()):\n            raise ValueError('registered storage root is outside the admitted workspace')", "        if type(budget) is dict and budget.get('schema_version')==2:\n            if pilot_context is None:raise ValueError('writable union requires explicit real-pilot selection')\n            from ..admission import Admission\n            from .real_pilot_import_caller import selected,_read,validate_plan\n            ad,execution=pilot_context\n            if not isinstance(ad,Admission) or ad.root!=Path(root) or not selected(execution) or execution['kind']!='compact_resource' or execution['resources']!=value:raise ValueError('original real-pilot admission context required')\n            selected_plan=next(iter(execution['payload']['representation_jobs'].values()))\n            plan=validate_plan(_read(ad,selected_plan['real_pilot_input']))\n            if plan['schema_version']!=2 or plan['resource_policy']!=value:raise ValueError('authenticated schema2 policy required')\n            from .real_pilot_storage import validate,EXPERIMENT\n            if ad.experiment_id!=EXPERIMENT:raise ValueError('fixed real-pilot identity required')\n            validate(budget,Path(root))\n        else:\n            if type(budget) is not dict or set(budget)!={'root','limits'} or type(budget['root']) is not str:\n                raise ValueError('registered storage budget schema differs')\n            watch=StorageWatch(budget['root'],budget['limits'])\n            if not watch.root.is_relative_to(Path(root).resolve()):\n                raise ValueError('registered storage root is outside the admitted workspace')"),
 ("    resource_policy(job['resources'], admitted.root)", "    resource_policy(job['resources'], admitted.root,pilot_context=(admitted,job))"),
 ("            monitor = subprocess.Popen(_command(args, 'monitor')+['--owner-pid', str(os.getpid()), '--nonce', nonce], cwd=args.root)", "            budget=job['resources'].get('storage_budget')\n            extra={}\n            if type(budget) is dict and budget.get('schema_version')==2:\n                from .real_pilot_storage import prepare_environment\n                env=resources._native_owned_env(Path(args.root),budget);prepare_environment(Path(args.root),budget,env)\n                extra['env']={**os.environ,**env}\n            monitor = subprocess.Popen(_command(args, 'monitor')+['--owner-pid', str(os.getpid()), '--nonce', nonce], cwd=args.root,**extra)"),
 ("for key in resources._native_owned_env(Path(args.root))", "for key in resources._native_owned_env(Path(args.root),job['resources'].get('storage_budget'))"),
 ("value['native_environment']!=resources._native_owned_env(Path(args.root))", "value['native_environment']!=resources._native_owned_env(Path(args.root),job['resources'].get('storage_budget'))"),
 ])
build('real_pilot_import_caller.py',[
 ("    require('physical_policy' not in p and 'storage_budget' in p, 'whole workspace storage guard required')", "    require('physical_policy' not in p and 'storage_budget' in p, 'whole workspace storage guard required')\n    require('schema_version' not in p['storage_budget'],'tiny route cannot select writable union')"),
 ("    require(type(budget) is dict and set(budget)=={'root','limits'} and type(budget['root']) is str\n            and Path(budget['root']).is_absolute(), 'explicit whole-root budget required')", "    if type(budget) is dict and budget.get('schema_version')==2:\n        require(set(budget)=={'schema_version','kind','authority_root','roots','limits'} and budget['kind']=='real-pilot-writable-union','explicit writable union fields required')\n    else:\n        require(type(budget) is dict and set(budget)=={'root','limits'} and type(budget['root']) is str\n                and Path(budget['root']).is_absolute(), 'explicit whole-root budget required')"),
 ("    resource_policy(resources,ad.root)", "    resource_policy(resources,ad.root,pilot_context=(ad,job))"),
 ("    require(Path(job['resources']['storage_budget']['root']) == ad.root and (ad.root/'.git').is_dir(), 'complete isolated workspace watch required')", "    budget=job['resources']['storage_budget']\n    if budget.get('schema_version')==2:\n        from .real_pilot_storage import validate,EXPERIMENT\n        require(p['schema_version']==2 and ad.experiment_id==EXPERIMENT,'union requires fixed schema2 real pilot')\n        validate(budget,ad.root)\n        require((ad.root/'.git').is_dir(),'original source authority root required')\n    else:\n        require(Path(budget['root']) == ad.root and (ad.root/'.git').is_dir(), 'complete isolated workspace watch required')"),
 ("    watch = StorageWatch(run.admission.root,job['resources']['storage_budget']['limits']); watch.check()", "    budget=job['resources']['storage_budget']\n    if budget.get('schema_version')==2:\n        from .real_pilot_storage import WritableUnion\n        watch=WritableUnion(budget,run.admission.root)\n        from .resources import assert_guarded_worker\n        limits=job['resources']\n        live=assert_guarded_worker(run.admission.root/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/run.admission.experiment_id/'guard',__import__('sys').orig_argv,required_paths=[run.admission.root],wall_seconds=limits['wall_seconds'],memory_max_bytes=limits['memory_max_bytes'],memory_high_bytes=limits['memory_high_bytes'],disk_floor_bytes=limits['disk_floor_bytes'])\n        require(live.get('storage_budget')==budget,'worker/monitor writable scopes differ')\n    else:watch=StorageWatch(run.admission.root,budget['limits'])\n    watch.check()")])
bases['matching_owner.py']=D.parents[3]/P/'matching_owner.py'
build('matching_owner.py',[("    policy_resources=job.resource_policy(execution['resources'],ad.root)","    policy_resources=job.resource_policy(execution['resources'],ad.root,pilot_context=(ad,execution) if _resource else None)")])
(D/'SOURCE_DELTA01.json').write_text(json.dumps(edits,indent=2)+'\n')
