from pathlib import Path
import hashlib,json,os,stat,subprocess
D=Path(__file__).resolve().parent;F=D.parent;S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');I='financial-wrapper-classification-eager-complete100-20261003-01';B=S/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/I;P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-complete100-root-launch-20261004-01');H=F/'heartbeat-root-checkpoint10-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();read=lambda p:json.loads(p.read_bytes());checks=[];pins={}
def ok(v,n):assert v,n;checks.append(n)
def observe(p):
 s=p.lstat();ok(stat.S_ISREG(s.st_mode)and s.st_size<=4*1024**2,'bounded original file '+str(p));b=p.read_bytes();pins[str(p)]={'bytes':len(b),'mode':stat.S_IMODE(s.st_mode),'sha256':sha(b)};return b
claimpath=S/'research_runs'/I/'claim.json';claim=json.loads(observe(claimpath));failed=json.loads(observe(claimpath.parent/'failed.json'));ok(sha(claimpath.read_bytes())==failed['claim_sha256']=='2e3bbbbf786f784eadb18bc3cdfea68905610ae773bbbd748ea1b2666b9e61f1','genuine claim/failed hash');ok(failed['status']=='failed'and failed['output_sha256']=={}and not(claimpath.parent/'complete.json').exists(),'permanentFAILED no registered output')
q=read(Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-complete100-final-contract-20261004-01/REQUEST_RELEASED01.json'));ok(claim['source']==claim['design_source']==q['source']=='9dc5c79f738920b52947b4e63fed0397f1b5b207','actual same scientific source/design');ok(claim['effective_attempt_budget']==19 and claim['family']['attempt_budget']==18 and claim['family']['prior_attempts']==0,'genuine budget19/base18/prior0')
for name,h in q['source_files'].items():ok(sha((S/name).read_bytes())==h,'unchanged source '+name)
head=subprocess.run(['git','--no-replace-objects','-C',str(S),'rev-parse','HEAD'],capture_output=True,timeout=10);ok(head.returncode==0 and head.stdout.decode().strip()==q['source'],'actual sourceGit HEAD unchanged')
claims=[]
for p in sorted((S/'research_runs').glob('*/claim.json')):
 c=read(p);f=read(p.parent/'failed.json');ok(f['claim_sha256']==sha(p.read_bytes())and f['status']=='failed'and not(p.parent/'complete.json').exists(),'genuine spentfailed '+p.parent.name);claims.append({'identity':p.parent.name,'claim_sha256':sha(p.read_bytes()),'budget':c['effective_attempt_budget']})
ok(len(claims)==3 and max(x['budget']for x in claims)==19,'actual spent3/highest19')
fitroots=list((S/'research_artifacts/onchain_fit_cells').glob('*/'+I));ok(len(fitroots)==1,'one actual fit root');fit=fitroots[0];schedule=read(fit/'schedule.json');epochs=sorted(fit.glob('epoch-*.json'));ok([read(p)['epoch']for p in epochs]==list(range(29)),'durable29epoch logs0..28');ok(schedule['n_examples']==schedule['training']['batch_size']==16 and schedule['training']['epochs']==100,'one batch per epoch of100 fixed schedule')
cp=list((fit/'checkpoints').glob('*/manifest.json'));ok(len(cp)==29,'29 complete opaque checkpoint manifests');checkpoint_rows=[]
for p in cp:
 m=read(p);ok(m['provenance']['source_commit']==q['source']and m['provenance']['cell_id']=='financial-wrapper-classification-eager-reference-20261003-01','checkpoint genuine provenance');ok(set(m['members'])=={'state.pt'},'exact opaque checkpoint body member');r=m['members']['state.pt'];b=observe(p.parent/'state.pt');ok(len(b)==r['size']and sha(b)==r['sha256'],'actual opaque checkpoint hash/extent');checkpoint_rows.append({'manifest':str(p),'manifest_sha256':sha(p.read_bytes()),'state_sha256':sha(b),'bytes':len(b)})
ff=read(fit/'failed.json');ok(Path(ff['last_checkpoint'])in cp and not(fit/'complete.json').exists(),'lastcheckpoint exists no completed fit')
wrapper=S/'research_artifacts/financial_wrapper_engineering'/I;wf=read(wrapper/'failure.json');ok(wf['success']is False and wf['retry']is False and wf['type']=='SystemExit','actual wrapper permanent failure');post=read(B/'postmortem-cells.json');ok(len(post)==1 and post[0]['status']=='unavailable','reference cell explicitly unavailable');ok(read(B/'unsealed-journals.json')==[],'no durable cell journals')
for n in ['summary.json','wrapper-summary.json','cell-ledger.json','artifact-index.json','complete.json']:ok(not(wrapper/n).exists(),'wrapper output absent '+n)
for tree in (claimpath.parent,B,fit,wrapper,P/'attempt'):
 for p in sorted(tree.rglob('*')):
  if p.is_file():observe(p)
terminal=read(P/'attempt/parent-terminal.json');guard=read(B/'guard/final.json');child=read(B/'guard/child_exit.json');cleanup=read(P/'attempt/owned-tree-cleanup.json');owner=read(B/'owner.json');launch=read(B/'launch.json');rootexit=read(H/'ROOT_COMPLETE100_NATIVE01_EXIT.json');spawn=read(H/'ROOT_COMPLETE100_NATIVE01_SPAWN.json')
ok(terminal['actual_parent_exit']is None and terminal['actual_child_exit']==1 and rootexit['actual_root_observed_parent_exit']==1,'original nullParent separate actualRoot1/child1')
ok(guard['child_exit_code']is None and child['exit_code']==125 and child['reason']=='signal','original guardnull separate actualworkload125signal');ok(guard['phase']=='failed'and guard['retry']is False and guard['elapsed_time_kill']is False,'failedguard no timeout/retry')
ok(all(owner[k]==v for k,v in launch.items())and guard['owner_identity']==owner,'original actual Owner/launch/guard joins');ok(cleanup['remaining_original_identities']==[]and cleanup['subreaper_used']is True,'original owned descendants drained')
ok(sha((P/'attempt/owned-tree-cleanup.json').read_bytes())==terminal['cleanup']['subreaper_cleanup_sha256'],'original cleanup byte binding')
for stream in ('stdout','stderr'):ok(sha(observe(H/('ROOT_COMPLETE100_NATIVE01.'+stream)))==rootexit[stream+'_sha256'],'Root actual stream hash '+stream)
err=(H/'ROOT_COMPLETE100_NATIVE01.stderr').read_text();ok("os.stat(entry.name,dir_fd=fd,follow_symlinks=False)"in err and '.pending-bfcc60df908b42b880ddb3c8a52deb9a'in err,'actual original scan failure')
for n in ('ROOT_COMPLETE100_NATIVE01_EXIT.json','ROOT_COMPLETE100_NATIVE01_INTENT.json','ROOT_COMPLETE100_NATIVE01_SPAWN.json','COMPLETE100_NATIVE_OBSERVATION01.json'):observe(H/n)
for key in ('oom','oom_kill','oom_group_kill'):ok(guard['initial_memory_events'][key]==guard['memory_events'][key]==child['terminal_memory_snapshot']['memory_events'][key]==0,'recorded cgroup OOM counter0 '+key)
pids={spawn['actual_root_spawned_parent_pid'],child['workload_pid'],guard['monitor_pid'],owner['supervisor_pid']}|{x['pid']for x in cleanup['owned_pid_start_records']}|{int(x)for x in guard['cpu_thread_readback']}|{x['pid']for x in terminal['cleanup']['actual_control_operations'].values()}
for pid in sorted(pids):ok(not Path('/proc',str(pid)).exists(),'current actual recorded PID absent '+str(pid))
for group in {x['pgrp']for x in cleanup['owned_pid_start_records']}:
 try:os.killpg(group,0)
 except ProcessLookupError:checks.append('current recorded group absent '+str(group))
 else:raise AssertionError('groupalive')
ok(terminal['cleanup']['cgroup_absent']and not Path(guard['cgroup']).exists(),'actual current cgroup absent');ok(terminal['cleanup']['joined_unit_stopped']and all(x['exit_code']==0 for x in terminal['cleanup']['actual_control_operations'].values()),'original stop/before/after0');ok(terminal['cleanup']['native_pid_census_is_complete_history']is False,'complete native PIDhistory explicitly unavailable')
result={'checks':len(checks),'checks_detail':checks,'claims':claims,'durable_epoch_records':29,'epoch_range':[0,28],'optimizer_updates_evidenced_at_least':29,'further_unjournaled_updates':'unknown','checkpoint_manifests':checkpoint_rows,'checkpoint_deserialized':False,'reference_completed':False,'postmortem':post,'actual_parent_exit_original':None,'Root_observed_parent_exit':1,'guard_child_exit_original':None,'actual_child_exit_record':125,'guard_peak_sampled_memory_current_bytes':guard['peak_sampled_memory_current_bytes'],'terminal_memory_current_bytes':child['terminal_memory_snapshot']['memory_current_bytes'],'OOM_qualification':'No OOM or OOM-kill event in original unit initial/final/terminal counters; not complete host history or capacity proof.','recorded_pids_now_absent':sorted(pids),'native_PID_complete_history':False,'claim_started_at':claim['started_at'],'claim_ended_at':failed['ended_at'],'Root_elapsed_seconds':rootexit['elapsed_seconds'],'retry_or_new_identity_authority':False}
(D/'READBACK01.json').write_text(json.dumps(result,indent=2,sort_keys=True)+'\n');(D/'ORIGINAL_PINS01.json').write_text(json.dumps(pins,indent=2,sort_keys=True)+'\n');print(json.dumps({'checks':len(checks),'epochs':29,'checkpoints':29,'pids':len(pids)}))
