import ast,difflib,gzip,hashlib,importlib.util,io,json,os,shutil,stat,subprocess,sys,tarfile
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=F/'financial-genuine-wrapper-root-preservation06-2026-10-04';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';T=F/'financial-genuine-wrapper-root-remote-recovery02-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
ck(sha((U/'recovery04.py').read_bytes())=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','actual accepteddecoder');sys.path.insert(0,str(U));sp=importlib.util.spec_from_file_location('actual_capture_review',U/'recovery04.py');a=importlib.util.module_from_spec(sp);sp.loader.exec_module(a)
def read(p):return a.read(p.parent,p.name)
def doc(p,pin=None):
 b=read(p);ck(pin is None or sha(b)==pin,'pin '+p.name);v=json.loads(b);ck(a.encode(v)==b,'canonical '+p.name);return v
q=doc(P/'REQUEST01.json','fb1f603733d24a5ca7e0eff41242651620b7561de17afc07668e1db102dbeca9');cap=doc(P/'CAPTURE01.json','645387e5bede68f778ad4a94c5e3b30c4e9f64bd10aa4cfb1108508939a8b899');terminal=doc(P/'ACTUAL_TERMINAL01.json');intent=doc(P/'INTENT01.json');H='d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0';ck(q['source']==cap['source']==intent['source']==H and cap['request_sha256']==intent['request_sha256']==sha(read(P/'REQUEST01.json')),'actual failedcapture chain');ck(terminal['actual_exit']==0 and terminal['capture_sha256']==sha(read(P/'CAPTURE01.json')) and terminal['actual_exec_session']==82798 and terminal['actual_start_tool']=='ee5a61' and terminal['actual_completion_tool']=='758478','actual captureterminaltools');ck(terminal['actual_stdout_sha256']==sha(read(P/'ACTUAL_CAPTURE01.out')) and terminal['actual_stderr_sha256']==sha(read(P/'ACTUAL_CAPTURE01.err')) and read(P/'ACTUAL_CAPTURE01.err')==b'' and json.loads(read(P/'ACTUAL_CAPTURE01.out'))==cap,'actualcapture stdout andemptyerr');ck(not Path('/proc',str(intent['pid'])).exists() and intent['one_use'] is True,'original capturePID closed');ck(len(cap['disk_floor_observations'])==9 and all(x['free_bytes']>=a.FLOOR for x in cap['disk_floor_observations']) and cap['continuous_floor_watch_claim'] is False,'nine actualobservedfloors');V=F/'financial-genuine-wrapper-first-attempt-capture-review01-2026-10-04';ck(sha(read(V/'MANIFEST01.json'))==q['independent_review_manifest_sha256']=='a0636b112e9a1cd26a66b21ad5cada81effd0db540ef19abd465cf00f675bbe9','actual source review pin');vm=doc(V/'MANIFEST01.json')
for x in vm['entries']:ck(sha(read(V/x['path']))==x['sha256'] and stat.S_IMODE((V/x['path']).stat().st_mode)==x['mode'],'allsource review originals')
ck(sha(read(P/'capture06.py'))=='4f849700c45c5d4b35009988d91e0aeaed72084c2fce39ab3404aeabd8069a06','actualaccepted capturecaller')
for n,h in q['primitive_sha256'].items():ck(sha(read(U/n))==h,'exact genericprimitive')
prior=F/'held-consumer-final-released-scope-capture-review01-2026-10-03/check01.py';defs=[n for n in ast.parse(read(prior)).body if isinstance(n,ast.FunctionDef) and n.name in ('decode','recode')];exec(compile(ast.Module(body=defs,type_ignores=[]),str(prior),'exec'));results={};bodies={};manifests={}
for role,count in [('source',878),('parent',30),('outer',8)]:
 root=Path(q['roots'][role]);m=doc(P/(role.upper()+'_MANIFEST01.json'),q['manifests'][role]);ck(a.scan(root)==m and len(m['members'])==count==cap['members'][role],'full actualmanifestbefore '+role);raw=read(P/('complete-'+role+'01.tar.gz'));info=cap['archives'][role];ck(sha(raw)==info['sha256'] and len(raw)==info['bytes']<=a.FILE and info['manifest_sha256']==q['manifests'][role],'complete compressedpin '+role);decoded,framing=decode(raw,m);ck(recode(m,decoded)==raw,'fullindependent canonical recompression '+role);files={x['path']:x for x in m['members'] if x['kind']=='file'}
 for n,row in files.items():ck(read(root/n)==decoded[n] and stat.S_IMODE((root/n).stat().st_mode)==row['mode'],'alloriginal opaque bodymode '+role)
 ck(a.scan(root)==m and stat.S_IMODE(root.stat().st_mode)==m['root_mode'],'full actualstable rootmode '+role);bodies[role]=decoded;manifests[role]=m;results[role]={'archive':info,'members':count,'regular_bodies':len(files),'logical_bytes':sum(r['bytes'] for r in files.values()),'root_mode':m['root_mode'],'framing':framing}
sb=bodies['source'];pb=bodies['parent'];ob=bodies['outer'];S=Path(q['roots']['source']);final=json.loads(pb['REQUEST_FINAL03.json']);gate=json.loads(sb[final['registration']]);exp=gate['experiments'][final['identity']];ck(sha(pb['REQUEST_FINAL03.json'])=='dc80a4dff93fbf3261bdf151076c1420630ed38926ab7094d60eb1902bde25bc' and final['source']==H and len(exp['source_files'])==289 and final['source_files']==exp['source_files'],'exact original finalrequest/source289')
for n,h in exp['source_files'].items():ck(sha(sb[n])==h,'all289original sourcepins')
for e in gate['experiments'].values():
 for ref in e['inputs'].values():ck(sha(sb[ref['path']])==ref['sha256'],'all80original inputjoins')
installed=doc(F/'financial-genuine-wrapper-installed-gate-admission-review01-2026-10-04/READBACK01.json');rows={x['path']:x for x in installed['joined']}
def git(args):
 z=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never','-C',str(S),*args],stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1'});ck(z.returncode==0 and len(z.stdout)<=8*1024**2 and len(z.stderr)<=65536,'bounded readonlyGit');return z.stdout
tree={}
for entry in git(['ls-tree','-r','-z',H]).split(b'\0'):
 if not entry:continue
 left,n=entry.split(b'\t');mode,kind,oid=left.decode().split();ck(kind=='blob','actualsourceGitregular');tree[n.decode()]=(mode,oid)
ck(set(tree)==set(rows)==set(exp['source_files'])|{final['registration']} and len(tree)==290 and installed['implementation']==194 and sum(n.startswith('tradingagents/') for n in rows)==149,'entire290/194149scope')
for n,row in rows.items():
 raw=sb[n];ck(sha(raw)==row['sha256'] and len(raw)==row['bytes'] and hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==row['git_oid']==tree[n][1] and tree[n][0]==row['git_mode'],'all290sourcebody immutableOIDmode')
oldparent=doc(F/'financial-genuine-wrapper-root-preservation05-2026-10-04/PARENT_MANIFEST01.json');current={x['path']:x for x in manifests['parent']['members']};ck(all(current[x['path']]==x for x in oldparent['members']) and set(current)-{x['path'] for x in oldparent['members']}=={'attempt','attempt/intent.json','attempt/owned-tree-cleanup.json','attempt/parent-terminal.json','attempt/spawn.json','attempt/stderr','attempt/stdout'},'all original23 unchanged +actual7members');original=json.loads(pb['attempt/parent-terminal.json']);actual=json.loads(ob['ACTUAL_TERMINAL01.json']);ck(original['actual_parent_exit'] is None and original['actual_child_exit']==1 and actual['actual_parent_exit']==1 and actual['original_parent_terminal_sha256']==sha(pb['attempt/parent-terminal.json']),'originalNULL andseparateactual1 preserved');ck(original['cleanup']['source_bound_no_dispatch'] is True and b'Unavailable: runtime installed RECORD unavailable' in pb['attempt/stderr'],'original runtimefailure/no-dispatch retained');ck(json.loads(ob['ROOT_INTENT01.json'])['native_properties_verified_by_original_guard_before_worker_release'] is True and 'not an observational proof' in json.loads(ob['INTENT_QUALIFICATION01.json'])['original_intent_native_properties_verified_field'],'original TRUE qualifier retained');closure=doc(F/'financial-genuine-wrapper-first-attempt-closure-review01-2026-10-04/READBACK01.json');ck(sha(pb['attempt/parent-terminal.json'])==closure['parent_terminal_sha256'] and sha(ob['ACTUAL_TERMINAL01.json'])==closure['root_terminal_sha256'] and sha(pb['attempt/stderr'])==closure['original_traceback_sha256'],'exact independentlyclosed originaloutcomes');ck(cap['failed_identity_permanently_reserved'] is True and cap['original_parent_terminal_exit'] is None and cap['actual_outer_exit']==1 and cap['numerical_claims']==cap['numerical_components_completed']==0 and cap['native_started'] is False,'honest failedreservation/zeroactualclaims scope');ck(all(not (S/n).exists() for n in ['research_runs','research_artifacts','fixture_outer']) and all(not Path('/proc',str(pid)).exists() for pid in closure['observed_absent_original_pids']),'stillzero claims originalPIDsabsent');ck(all(a.scan(Path(q['roots'][role]))==manifests[role] for role in manifests) and git(['rev-parse','HEAD']).decode().strip()==H and git(['status','--porcelain','--untracked-files=all'])==b'','allclosedoriginalscope stable');support=[]
for p in sorted(P.iterdir()):
 b=read(p);support.append({'path':p.name,'type':'file','mode':stat.S_IMODE(p.stat().st_mode),'bytes':len(b),'sha256':sha(b)})
ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numericalimports');out={'schema_version':1,'decision':'ACCEPTED_ACTUAL_LOCAL_COMPLETE_FAILED_SCOPE_CAPTURE_ONLY','checks':len(checks),'source':H,'identity':q['identity'],'capture_sha256':sha(read(P/'CAPTURE01.json')),'request_sha256':sha(read(P/'REQUEST01.json')),'actual_capture_terminal_sha256':sha(read(P/'ACTUAL_TERMINAL01.json')),'archives':results,'tracked':290,'source_pins':289,'implementation':194,'package':149,'original_parent_terminal_exit':None,'actual_outer_exit':1,'numerical_claims':0,'failed_identity_permanently_reserved':True,'further_numerical_release_halted':True,'native_noncreation_qualification':'source-order inference; no actual native property readback','actual_external_or_flat_failedscope_recovery':False,'runtime_native_scientific_authority':False,'capture_support':support};(O/'READBACK01.json').write_bytes(a.encode(out));print(json.dumps({k:v for k,v in out.items() if k!='capture_support'},indent=2))
