import ast,difflib,hashlib,json,stat,datetime
from pathlib import Path
H=Path(__file__).resolve().parent;B=H.parent;sha=lambda b:hashlib.sha256(b).hexdigest()
def put(n,v):(H/n).write_text(json.dumps(v,sort_keys=True,indent=2,allow_nan=False)+'\n')
old=(B/'financial-wrapper-complete100-baseline-remote01-2026-10-04/restore02.py').read_bytes();assert sha(old)=='8b010b28e37978c6ea24eb0e4aaad68d715f4031a102d7396f4627fd501d06e1';(H/'ORIGINAL_FLAT02.py').write_bytes(old);new=(H/'restore02.py').read_bytes();ot=ast.parse(old);nt=ast.parse(new);entry=lambda t:ast.dump(next(n for n in t.body if isinstance(n,ast.FunctionDef) and n.name=='entry'),include_attributes=False);assert entry(ot)==entry(nt)
# Whole orchestration replacement explicitly recorded, not mislabeled as a narrow code delta.
put('FLAT_FULL_INVERSE01.json',{'original_sha256':sha(old),'successor_sha256':sha(new),'scope':'new two-scope orchestration replaces baseline six-scope/Git main; unchanged failure-handler AST and exact pinned primitives except separately declared PAX framer','original_source':old.decode(),'successor_source':new.decode(),'unchanged_entry_AST_sha256':sha(entry(nt).encode())});(H/'FLAT_DELTA01.patch').write_text(''.join(difflib.unified_diff(old.decode().splitlines(keepends=True),new.decode().splitlines(keepends=True),fromfile='baseline-restore02.py',tofile='final-supplement-restore02.py')))
checks=json.loads((H/'CHECKS05.json').read_text());capture=json.loads((H/'ACTUAL_CAPTURE01.json').read_text());required=json.loads((H/'REQUIRED_BODIES01.json').read_text());domain=json.loads((H/'PAX_DOMAIN06.json').read_text())
put('MACHINE01.json',{'schema_version':1,'status':'SOURCE_PREPARATION_REQUIRES_DIFFERENT_AUTHOR_REVIEW','author':'combined_worker_review','timestamp_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'remote_source_sha256':sha((H/'recover01.py').read_bytes()),'flat_source_sha256':sha(new),'original_flat_withheld_sha256':sha((H/'restore01.py').read_bytes()),'explicit_PAX_helper_sha256':'a054d5922899b53579f4220ff3b427dc050dff075cb5470b43ff55e621b97eb2','actual_capture_sha256':sha((H/'ACTUAL_CAPTURE01.json').read_bytes()),'source':capture['source'],'identity':capture['identity'],'request_sha256':capture['request_sha256'],'contract_sha256':capture['contract_sha256'],'release_sha256':capture['release_sha256'],'baseline_full_recovery_sha256':capture['baseline_full_recovery_sha256'],'selected_bodies':len(required),'selected_bytes':sum(r['bytes'] for r in required.values()),'remote_Git_operations':11+2*len(required),'scopes':['contract','support'],'actual_scope_typed_members':sum(r['members'] for r in capture['scopes'].values()),'actual_scope_regular_bodies':sum(r['files'] for r in capture['scopes'].values()),'actual_scope_logical_bytes':sum(r['logical_bytes'] for r in capture['scopes'].values()),'checks':checks['checks'],'count_qualification':'includes actual opaque member/body authentication checks, not empirical trials','tiny_fatal_pairs':len(checks['fatal_pairs']),'actual_archive_canonical_recompression_scopes':2,'actual_remote_commit':None,'actual_remote_receipt':None,'actual_complete_flat_recovery':None,'independent_source_review':None,'numerical_release':None,'actual_helper_main_or_entry_executed':False,'underlying_Parent_R4_unchanged':True,'original_capture_archives_unchanged':True,'preserved_failure':{'script':'check03.py','raw':'CHECK03.err','cause':'actual final support archive reproduces original b40 PAX raw-prefix slash refusal before output restore; original restore01 remains withheld for this domain'},'no_Git_reconstruction_in_final_helper':True,'no_numerical_import_or_handle_or_claim_or_network':True,'no_POSIX_runtime_or_wholecapacity_authority':True})
report='''# Final supplement tooling — source preparation

The concrete remote helper recover01.py binds the seven actual Root-captured bodies totaling1,063,336 bytes and25 Git operations. It differs from accepted baseline b03a2c29 by exactly four literal replacements: REQUIRED map, fresh bare namespace, status and byte-scope qualification. SOURCE_INVERSE01 preserves the complete original and verifies literal/AST inversion. The inherited≤506paths/64MiB logical/4MiB body/10GiB floor/60s per-operation/600s total/1024call controls and process/write first-fatal cleanup are unchanged. Only exact seven-body selection is proposed; generic supplemental scope is not granted.

The new flat caller is restore02.py. It authenticates the actual selected remote receipt/hash/count/Git OIDs and exact fixed capture86b787a7, then restores exactly contract/support to fresh existing-private0700 outputs. It verifies complete manifest/body/mode metadata, canonical archives and final retained flat namespaces, including a second pass over first-scope bodies after the second restore. Before/after operations retain observed disk/time boundaries. All failure outputs remain; the inherited entry handler preserves first fatal and attempts a separate failure journal. The180s check is at boundaries, not an independent preemptive timer. No Git reconstruction occurs: genuine Source339/all385 object recovery belongs to the separately accepted baseline.

**Explicit PAX dependency correction:** the first bound restore01 using original b40 failed the actual support archive at the raw-name slash predicate. CHECK03.err and original candidate/template remain unchanged. No recovery entrypoint or Root flat restore was invoked. The separate restore02 binds exact previously reviewed recovery_pax01/a054d592 by name/hash, copied without editing. Only that utility's framed_members differs from b40; whole function replacement returns every original byte. Its narrow predicate validates the complete effective PAX path while retaining mandatory full canonical reencoding. owned_io and bounded_git are exact unchanged originals, and the real Parent's recovery04.py is untouched. PAX_BINDING_INVERSE01 records this explicit new dependency and copied original author/reviewer manifest/report references. Prior acceptance was witness-domain only; this final-supplement use requires its own different-author review.

Checks authenticate all290 actual typed members/245 original files/5,262,175 logical bytes through the new framer and exact full recompression of both immutable actual archives, without restoring them. An owned canonical PAX file whose truncated raw100-byte header ends at a slash reproduces old RED and new private-flat GREEN; truncation still refuses. Additional opaque two-scope controls cover exact body/mode/emptydir recovery, missing pins, five fixed selection mutations, replay refusal, extra scopes, second-scope interruption with first scope retained, late first-scope corruption, and nine ordinary/fatal publication pairs. The complete raw failed original control is preserved. Numerical packages, values, labels, Owner/Run/Admission, network and real claims were not used.

Actual request34d1a856, immutable contract6da30ea8, releasef7e5b3d3 and baseline proof49e0ad65 are fixed by the capture. These are byte provenance, not a launch grant from this helper. Actual committed remote selection/receipt and complete fresh final restoration remain null/unperformed here. Root must copy both final helper sources and the exact utilities directory, preserve their source review, commit/push/read back the seven-body selection, perform bounded external and fresh flat recovery once, and obtain independent actual final-recovery/release acceptance. Use restore02, never the retained original restore01. No whole-fit capacity, installed runtime preservation, POSIX topology or scientific/financial result follows.

FLAT_FULL_INVERSE01 and FLAT_DELTA01 explicitly retain the complete six-scope/Git baseline-to-new-two-scope orchestration delta; this is not mislabeled as just the two PAX import edits. The original failure handler AST remains exact. All original templates, bodies, failures and tiny controls are included in the final typed manifest. No file outside the assigned tooling directory was written.
'''
(H/'REPORT01.md').write_text(report)
rows=[]
for p in sorted(H.rglob('*')):
 s=p.lstat();r={'path':str(p.relative_to(H)),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):r['kind']='directory'
 elif stat.S_ISREG(s.st_mode):b=p.read_bytes();assert len(b)<=4194304;r.update(kind='file',bytes=len(b),sha256=sha(b))
 else:raise AssertionError('unexpected fixture type')
 rows.append(r)
put('MANIFEST01.json',{'schema_version':1,'self_excluded':'MANIFEST01.json','scope':'complete source preparation including original PAX-failing candidate and all raw controls','members':rows,'counts':{'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'logical_bytes':sum(r.get('bytes',0) for r in rows)}})
for r in rows:
 p=H/r['path'];assert stat.S_IMODE(p.lstat().st_mode)==r['mode']
 if r['kind']=='file':assert sha(p.read_bytes())==r['sha256'] and p.stat().st_size==r['bytes']
print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'remote':sha((H/'recover01.py').read_bytes()),'flat':sha(new),'machine':sha((H/'MACHINE01.json').read_bytes()),'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'bytes':sum(r.get('bytes',0) for r in rows)}))
