# Composed checker cleanup successor02

OBSERVATION_REQUIRES_INDEPENDENT_REVIEW. Successor02 corrects only owned cleanup and refusal-diagnostic handling in the withheld14145 checker. No accepted recovery proof, authority body, registration, claim or release is created. All complete byte/Git/source/policy composition predicates and bounds remain unchanged. Original checker01, Root measurement, gate-preview01 refusal and reviewer CR1/CR2/CR3 evidence remain immutable.

Exactly five literal substitutions reverse byte-for-byte and AST-for-AST to original14145: add stdlib types; add the pinned owned-IO delegation/retention wrapper; delegate Reader.read's one owned FD close; explicitly close the owned scandir iterator under the same rules; protect the public refusal diagnostic. The entire run(), flat_scope(), git_graph(), hashes, maps, all589/585/194/195/191/150/340/385+9 denominators, and Reader initialization/tick/anchor/json/final-global-currentness remain exact original AST. INPUTS01 is exactly f992329f.4MiB individual read/256MiB cumulative unique byte/32768 member+anchor/180second read-only bounds are unchanged; no numerical/runtime/preclaim limit is amended.

The copied owned_io.py is the literal09d1fbcc dependency. The identical bytes are embedded in the successor and SHA256-checked before compilation into a private stdlib module. This avoids adding a new mutable filesystem dependency bootstrap or import-path race; no dependency function is edited. The actual _cleanup semantics select the first actual fatal exception over ordinary body/close uncertainty, never retry an uncertain descriptor integer, and run each owned close action once. A narrow wrapper additionally retains primary and secondary actual objects using the BaseException dictionary descriptor. Optional evidence attachment cannot displace the selected exception. The pinned dependency's existing cause-attachment behavior remains unchanged.

CR1: ordinary ValueError followed by real FD-close MemoryError or SystemExit now escapes as the first actual fatal close object; original ordinary error remains reachable. CR2: original KeyboardInterrupt or MemoryError followed by iterator-close SystemExit or ValueError now preserves the earlier fatal identity, while closing the actual iterator once and retaining secondary evidence. No failed read enters the cache; no failed scan is published as an accepted tree. CR3: hostile str(), JSON encoding or print failures are processed as owned diagnostic actions. Earlier original fatal identity survives; an actual later fatal outranks an ordinary primary; all ordinary unresolved cleanup remains a stop through CleanupFailure. A bare raise preserves the original traceback when the selected primary survives.

118 new control rows passed: six exact original RED→corrected GREEN witnesses;25 actual-FD and25 actual-scandir primary/secondary matrices;60 exact-public-handler str/json/print matrices; nested real two-FD first-fatal/object-reachability checks; hostile exception attribute/cause hooks. Every owned FD closes once, no integer is retried, and every owned iterator closes once. All37 original opaque controls replayed with only the target filename and renamed retained-secondary attribute expectation changed; the replay inverse is retained. These are155 engineering rows, not scientific experiments, financial samples or actual authority outcomes.

The complete unchanged read-only actual composition passed again:1,727distinct files/84,824,406 bytes,589 current typed/585 protected/194 historical/195 target/191 equal/150 package/340 tracked paths, and385 original plus9 new logical Git objects forming the exact394 reachable set. The actual64 new opaque flat bodies/66physical files/83typed descendants, canonical archives, exact original modes and failed43 scope, genuine narrow outcomea0c192/1f3e, actual flat e702/sidecar72c910/Root d395, and original threeFAILED/spent/highest19 join. Checkpoint state is hashed only. The output decision remains COMPLETE_COMPOSED_BYTES_OBSERVED_REQUIRES_INDEPENDENT_REVIEW and recovery_proof remains null. The genuine different-author actual composition review and proof are still required.

Both original source and independent-withheld-review complete typed seals were reauthenticated, including every regular body and explicit metadata-only handling of FIFO/symlink adversarial fixtures. No blind FIFO read occurred. Original schema-error source versions/raw failures remain in the authenticated original preparation; original independent CR1/CR2/CR3 witnesses and stderr are copied literally into prior-review01. This correction's build, new matrix, inherited replay, prior authentication and actual readback had empty stderr; no unsuccessful local correction attempt was discarded.

Limits remain explicit: finite sampled currentness, not atomicity, writer exclusion, same-signature ABA protection, kernel aggregate quota, POSIX reconstruction, installed dependency-body recovery or whole fit capacity. Source policy/financial method, science AST, tolerances, old/new checkpoint provenance, spent identities and budgets are not changed. No network, public restoration, numerical package/array import, Owner/Run/Admission, proof, liveCAP/Root/gate/STATE edit or claim occurred. Final caller/gate/contract recovery and preclaim8MiB union eligibility remain separate. Invoke verify02.py only as the pinned-runtime read-only composition checker; output is observations only. Historical build/freeze scripts must not be replayed over this frozen directory.
