# Complete failed100 outcome recovery

COMPLETE_FAILED_SCOPE_BYTE_UNION_ACCEPTED. Every fresh flat file was independently authenticated:522 opaque original regular bodies plus10 metadata files, all private0600/single-link with exact complete membership. Corrected capsule:588 original typed members,475 unique files,113 directories/23,015,911 logical bytes. Each file belongs to exactly one of eight shards; repeated directory metadata is declared and identical. Parent28 typed/24 files and support26 typed/23 files are complete for their exact originals. Every body/name/type/mode joins current originals, capture snapshots, fetched Git blobs and fresh flat files.

All ten gzip/PAX TAR archives were reconstructed from actual fresh flat mappings and original-mode metadata, reproducing exact canonical compressed bytes. All35 selected actual external blobs rejoin fresh Git path/type/mode/OID/extent/hash and current original bodies. Nine original erroneous zero-capsule capture01 bodies remain preserved forensic evidence; actual capsule completeness derives from corrected capture02/e9e78f. Independent remote03 acceptance and all109 child FSIZE/reaped0 records rejoin; recorded PIDs/groups are currently absent.

Current Source/design9dc5 has339 tracked files. All tracked blob bodies,338 registered source pins,eight registered input roles,194 implementation paths/149 package paths and251 opaque RECORD metadata rows rejoin recovered bytes. Original385-object baseline Git recovery is separately accepted and not reconstructed here. Installed dependency package bodies and unrelated empirical stores are outside this scope.

Three original claims remain FAILED/spent/highest19. The fixed complete100 identity has29 journal ordinals0–28 and29 opaque checkpoint state/manifest pairs; state bodies were hashed only. Original Parent actual_parent_exit=NULL remains separate from Root actual_root_observed_parent_exit=1. No completed100 reference, successful fit, gradient agreement, paper-fit credit or capacity result is inferred. Full Parent/controller/Root evidence and prior active-observation corrections are preserved. Two reviewer inspection mistakes—terminal filename and Root exit-field name—are retained separately and corrected against actual fields, without altering originals or rerunning recovery.

The ordinary flat helper exited0 once; original PID904177/group are now absent. All recorded floor samples exceed10GiB. Root samples show owned-tree growth from35,676,686 logical/36,118,528 allocated bytes to59,764,030 logical/61,550,592 allocated bytes/724members before the final documentary exit file. These are historical sampled observations, not a continuous quota or an assertion that later added documentary files have identical counts. Fixed64/96MiB forensic bounds remain distinct from native scientific limits.

Original archival-only flags remain literal. Flat0600 bodies with original-mode tables are not a reconstructed POSIX source/Git tree. No network, helper entry, tensor/checkpoint deserialization, numerical module import, new claim, gate/budget change or adoption occurred. Acceptance closes only the actual failed-outcome byte union. Prospective compatibility correction, accounting, registration, caller/full preservation and native release remain separate.
