from pathlib import Path
import json,hashlib,stat
H=Path(__file__).resolve().parent;sha=lambda b:hashlib.sha256(b).hexdigest();checks=json.loads((H/'CHECKS01.json').read_text())
(H/'REPORT01.md').write_text('''# Independent historical cohort evidence review

Accepted as partial historical public-source evidence only. The complete frozen investigation is authenticated, including every raw retrieved body, receipt, ordered membership artifact and retained failed retrieval. No external request was repeated. The Git blob SHA-1 framing, tree mode and size joins reproduce for the fund list, Alameda list, README and MIT license. GitHub API metadata establishes the reported repository/file history; unsigned API commit metadata is not an author acquisition attestation or independent cryptographic signature.

Independent duplicate-key decoding verifies exactly65 distinct valid lowercase addresses. Canonical address order and address-label JSON bytes match. There are25 numbered Alameda labels (1–27 excluding18 and21), plus two deposit labels, not25 total Alameda-prefixed addresses. The March26 list has64 entries; the June16 version adds only Amber Group, without relabeling existing entries. October1 is the later repository snapshot date. The README scrape date and file commit date remain different observations. These establish a candidate historical list, not label creation dates or paper vintage.

The retained original paper §5.4 states65 entities and25 Alameda associations without providing the actual membership, acquisition date or exact fund graph inclusion rule. No collector or Coquidé/Cazabet/Tovanich citation appears in its retained text. The separate2024 paper describes65 accounts/27 Alameda and token transfers through March2023, including counterparties; those decisions cannot be transferred to the original paper. Its2025 extension reports90 addresses as of December2024. Its collector citation occurs in additional address-label enrichment: it does not authenticate this65-address file as that study's initial cohort, still less as Çelik–Sefer's cohort. The author's report is accepted only with that precise limitation.

The actual MIT notice is preserved, including attribution and notice-retention condition. This review verifies the text and repository blob; it does not extend rights to underlying third-party labels or authorize collection.

Task11 explicitly requires cohort/list-vintage evidence and forbids manufacturing65 addresses from65 entities; contemporary substitution is a distinct exploratory variant. REPLICATION_SPEC U12 requires actual list/date/inclusion, and its evidence hierarchy says proximity or a citation is not provenance. This historical candidate improves recoverability but does not resolve U12 or F19. A prospective independent reconstruction may be proposed only as an explicitly separate, pre-outcome registered assumption/variant; it cannot discharge exact-paper scope or replace blocked Tables5–6 silently. Root must resolve classification and register any choice; this review grants no admission and changes no blocked_cohort state.

Before exact replication admission, require an experiment-linked author list/acquisition record; exact entity-to-address and deposit-label treatment; cohort vintage and historical availability policy; transaction classes, success/token/native rules and edge direction/weight; induced versus external-neighbor inclusion and expansion; exact fund dates, folds and denominators, including missing/empty weeks. A reconstruction additionally requires frozen source/data/assumption joins, retrospective-selection disclosure, causal availability and independent gate review before outcomes. No author/provider contact was made.

The initial reviewer harness assumed the manifest excluded its root directory and used kind/bytes fields. The original manifest actually includes '.' and type/size; the mismatch and traceback are retained. check02 uses the original schema and passes. No author file, coverage, registration, source gate, numerical input or runtime was changed.
''')
m={'schema_version':1,'decision':'ACCEPTED_PARTIAL_HISTORICAL_EVIDENCE_ONLY','checks':checks['count'],'candidate_count':65,'numbered_alameda':25,'all_alameda_labels':27,'cohort_status':'blocked_cohort','author_reuse_authenticated':False,'U12_resolved':False,'paper_scope_discharged':False,'prospective_registration_authorized':False,'external_refetch':False,'report_sha256':sha((H/'REPORT01.md').read_bytes()),'checks_sha256':sha((H/'CHECKS01.json').read_bytes())};(H/'MACHINE01.json').write_text(json.dumps(m,indent=2,sort_keys=True)+'\n')
rows=[]
for p in sorted(H.rglob('*')):
 if p==H/'MANIFEST01.json':continue
 s=p.lstat();assert stat.S_ISREG(s.st_mode);b=p.read_bytes();rows.append({'path':str(p.relative_to(H)),'kind':'file','mode':oct(stat.S_IMODE(s.st_mode)),'bytes':len(b),'sha256':sha(b)})
(H/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'members':rows},indent=2,sort_keys=True)+'\n');print(json.dumps({'checks':checks['count'],'members':len(rows),'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'report':sha((H/'REPORT01.md').read_bytes())}))
