from pathlib import Path
import json,hashlib,os,subprocess
R=Path.cwd();D=Path(__file__).resolve().parent;F=D.parent.parent;P=F/'real-data-pilot-full24-preparation-increment01-2026-10-09/outcome13';h=lambda b:hashlib.sha256(b).hexdigest();secondreads=0
cache={}
def read(p):
 global secondreads
 if p not in cache:cache[p]=p.read_bytes();secondreads+=len(cache[p])
 return cache[p]
load=lambda p:json.loads(read(p))
r=load(P/'FRESH_GIT_RECOVERY13.json');c=load(R/r['capture']['path']);s=load(R/c['selection']['path']);review=load(D.parent/'TOOLS_REVIEW01.json');env={**os.environ,'GIT_NO_LAZY_FETCH':'1','GIT_TERMINAL_PROMPT':'0'}
names=[x['path'] for x in s['rows'] if not x['path'].startswith(('research_artifacts/','research_runs/'))];tree=subprocess.check_output(['git','ls-tree','-r',r['source'],'--',*names],env=env);secondreads+=len(tree);entries={}
for line in tree.decode().splitlines():head,name=line.split('\t');mode,kind,oid=head.split();entries[name]=(mode,kind,oid)
selected={x['path']:x for x in s['rows']};ignored=[];tracked=0;needed={}
for name in names:
 if name not in entries:
  assert name.endswith(('.log','.so'));ignored.append(name);continue
 mode,kind,oid=entries[name];assert kind=='blob';body=subprocess.check_output(['git','cat-file','blob',oid],env=env);secondreads+=len(body);assert h(body)==selected[name]['sha256'] and len(body)==selected[name]['bytes'];tracked+=1
 if name.endswith(('INSTALL01.json','OUTCOME_REVIEW01.json','ROOT_TERMINAL01.json','INTEGRATION_REVIEW01.json','RETURNED_GROUP_REVIEW01.json')):needed[name]=json.loads(body)
install=next(v for n,v in needed.items() if n.endswith('pilot-full28-to-successor-root-integration01-2026-10-09/INSTALL01.json'));assert len(install['files'])==17
for row in install['files']:assert selected[row['path']]['sha256']==row['after_sha256']
o=next(v for n,v in needed.items() if n.endswith('full28-outcome-review01-2026-10-09/OUTCOME_REVIEW01.json'));assert o['scientific_disposition']['confirmed_post_sink_cells']==61440 and o['scientific_disposition']['whole_cell_credit']==0 and o['scientific_disposition']['training'] is None
group=next(n for n in selected if n.endswith('full28-group-fresh-return01-2026-10-09/original-group-return01.tar'));assert selected[group]['bytes']==3532800 and selected[group]['sha256']=='4526a050543542cb47de4bcc393d36f904ef3ad0fa07f01ee5b3b4a8c60b81a8'
assert any(n.endswith('full28-entry01-2026-10-09/ROOT_TERMINAL01.json') for n in needed)
# Recover first-stage read accounting from its exact cache roster; no body rereads.
paths={D.parent/'TOOLS_REVIEW01.json',P/'FRESH_GIT_RECOVERY13.json',R/r['capture']['path'],R/c['selection']['path'],R/r['returned_archive']['path'],R/c['archive']['path'],P/'GIT_OPERATIONS13.json',R/s['baseline_actual_recovery']['path'],(R/s['baseline_actual_recovery']['path']).parent/'SELECTION12.json'};paths.update(P/n for n in review['helpers']);paths.update(P/(op['operation']+'.'+k) for op in r['operations'] for k in ('stdout','stderr'));paths.update(R/n for n in s['exact_unchanged_prior_rows_reused']+s['exact_already_recovered_duplicate_exclusions']);paths.update(q for scope in s['actual_scope_states'] for q in (R/scope['path']).rglob('*') if q.is_file())
firstdisk=sum(p.stat().st_size for p in paths);firstgit_upper=r['returned_archive']['bytes']+65536;total=firstdisk+firstgit_upper+secondreads;assert total<=64*1024**2
out={'decision':'accepted','scope':'Actual returned full28 outcome13 public selected increment only','source':r['source'],'archive_sha256':r['returned_archive']['sha256'],'archive_bytes':10444800,'regular_bodies':738,'regular_bytes':8907878,'directories':177,'git_operations_all_zero':13,'offline_no_lazy_fetch':True,'no_alternates':True,'deterministic_archive_reencoding_equal':True,'seven_original_scope_inventories_joined':True,'seventeen_installed_sources_joined':True,'fresh_original_group_archive_included':True,'prior_rows_reused':len(s['exact_unchanged_prior_rows_reused']),'duplicate_exclusions':s['exact_already_recovered_duplicate_exclusions'],'tracked_public_blob_bodies_sha256_joined':tracked,'ignored_public_bodies_archive_bound_only':ignored,'verification_provenance':{'first_stage':'check01.py passed all archive/member/reencoding/raw13ops/barecommit/blob/oldrows/exclusions/seven-scope checks before overstrict individual Git-membership assertion failed on ignored CHECK01.log. Raw failure preserved.','remaining_only':'finish02.py verifies individual tracked bodies and final scope joins; absent individual .log/.so objects are authenticated by complete returned archive committed blob, not misrepresented as standalone tracked files. No archive matrix repeated.'},'read_accounting':{'first_stage_unique_file_bytes_reconstructed_from_exact_executed_cache_roster':firstdisk,'first_stage_git_output_upper_bound':firstgit_upper,'second_stage_actual_file_and_git_bytes':secondreads,'combined_verifier_read_upper_bound':total,'limit':64*1024**2,'in_memory_member_bytes':8907878,'in_memory_reencoding_bytes':10444800,'qualification':'In-memory member parsing and reencoding do not reread storage. First-stage cache roster reconstructed after its preserved final assertion failure;64KiB conservatively covers its small Git outputs in addition to actual blob.'},'evidence':{str(p.relative_to(R)):h(read(p)) for p in [P/'FRESH_GIT_RECOVERY13.json',R/r['capture']['path'],R/c['selection']['path'],D.parent/'TOOLS_REVIEW01.json',D/'check01.py',D/'CHECK01.stderr',D/'finish02.py']},'qualifications':['No network, numerical imports, archive extraction, Owner/Run or Git mutation. Binary files hashed opaquely.','Selected public increment only, not whole Git/runtime/raw graph-store or POSIX/deletion proof.','Failed28 remains65536 journal-recorded/61440confirmed post_sink,zero wholeMCM/trainingnull. Separate original group semantic acceptance retained.','Later metadata not selected is not included by implication. Root terminal remains qualified author transcription.']}
p=D/'RECOVERY_REVIEW01.json';p.write_text(json.dumps(out,indent=2)+'\n');print(h(p.read_bytes()),total)
