from pathlib import Path
import json,hashlib,os,stat
H=Path(__file__).resolve().parent;B=H.parent;r=json.loads((H/'READ_INVENTORY01.json').read_bytes());sha=lambda b:hashlib.sha256(b).hexdigest()
def save(n,x):(H/n).write_text(json.dumps(x,sort_keys=True,indent=2)+'\n')
requirements=[
{'component':'Parent fixed context','original_source':'parent01.py:10-14,validate_release:24-36','required_delta':['new canonical absent external Parent namespace and fixed compatible100 identity','actual post-adoption source=design commit, actual gate e1846c9f,355 tracked/354 source pins/11 inputs','all12 original definitions retained plus new reference definition; unchanged base18/prior0 and actual prospective20 extension+review','three genuine FAILED claims retained,spent3/highest historical19; complete100 reference parent=None; exact fixed new cell','current accepted wrapper5f478bc3 and complete195 implementation/150 package map; no original f4ea pin reused'],'missing_actual_values':['new Parent path','new source commit','new caller hash']},
{'component':'Original protocols and resources','original_source':'Parent.preflight/launch/child_cleanup;PROTOCOL_PINS01.json','required_delta':['preserve actual job755c/resources e1d305 unchanged; original genuine job._admitted then job._command','keep native3GiB high=max,swap0,twoCPU,1800s and1840s outer,4MiBFSIZE,wholeCAP1GiB/Parent80MiB allocated64MiB logical,10GiB disk floor,6GiB startup','retain PID/start tick/subreaper supervisor and all native ownership/cleanup joins; no old namespace reuse','use actual source workflow_storage91e21c52 via current source; forensic watch04/bdeaca is distinct preservation utility, not a scientific watcher replacement'],'missing_actual_values':['fresh runtime/read-only admission','fresh resource eligibility','final descendant/cgroup release']},
{'component':'Accepted preclaim integration','original_source':'preclaim01.py:276-343','required_delta':['copy exact557b7bcb preclaim01.py to fresh external Parent, pin in q.helper_hashes; preserve original six helpers and protocol pins','call validate_preclaim on the actual Admission from job._admitted, exact admitted job/plan and ten genuine release_refs','place call before attempt/intents/spawn; do not construct substitute Admission or execute ResearchRun.start in Parent','retain original package-prefix/re-audit/runtime251/executable/lock verification; no numerical imports','the external preflight-to-child interval is not atomic; preserve original child admission/native ownership checks, no claim of immediate in-process Run.start adjacency'],'missing_actual_values':['actual genuine Admission','final contract/review and three proofs']},
{'component':'Circularity-free exact release','original_source':'Parent.contract;preclaim._parent_release:191-211','required_delta':['freeze caller/preclaim/helper bytes before q; do not embed final contract hash in caller body','independent metadata proof binds exact eight review/recovery refs only, excluding final_parent_contract and final_parent_review','fill q with actual source/maps/runtime/caller/helper/three proof refs; hash canonical q excluding final_review','different author final review binds contract hash/proof hashes/identity/source/caller; then q.final_review points to it','supply actual request path and raw SHA via CLI; construct final contract/review refs from actual request and q.final_review, preserving exact public ten-key schema','separate final caller/request/review witness recovery follows immutable contract; a baseline proof cannot falsely claim to have recovered its own not-yet-written contract'],'missing_actual_values':['metadata proof','full final recovery','actual final contract and release']},
{'component':'Evidence/cache layout','original_source':'preclaim.Reader.read/finish,_sealed,_proof_bundle','required_delta':['new reviewed layout may put all four original policy-review bodies under concrete-policy/ with literal original modes and filenames','both review refs and three corresponding recovery_receipts use exact same canonical paths; no hardlink/symlink or hash-only cache shortcut','preserve38 literal original receipt bodies and13 source evidence origins; retain original review02 immutable and exact recovery proofc5cf','new machine/report/manifest must be genuinely authored/reviewed and seal all refs; every reference stays descendant of its actual manifest parent','recompute budget using actual unique canonical paths; include twice every body, including new machine/report/manifest and final Parent contract/caller/proofs'],'missing_actual_values':['actual new layout machine/report/manifest lengths','full final byte count']}
]
save('INTEGRATION_REQUIREMENTS01.json',{'schema_version':1,'status':'READ_ONLY_HANDOFF_NOT_RELEASED','requirements':requirements,'all_numerical_claims_and_native_authority':None,'source_gate_parent_mutation_by_investigator':False})
report='''The current final-caller evidence layout cannot pass the unchanged accepted preclaim02 8MiB reader. Exact known reads cost8,252,864B before the new Parent caller, contract, final review or any of the three Parent proofs. The contract's354 source hashes and251-record runtime map alone require at least114,744B in compact JSON, charged twice; the strict minimum total is8,482,352B, exceeding8,388,608B by93,744B. This is a lower bound, not a synthetic successful preclaim.

The earlier4,124,892B figure covers only195 implementation bodies read twice. The11 actual preview inputs total186,109B and the genuine prospective gate is640,969B; with final rereads these add1,654,156B. Source/input/gate subtotal is5,779,048B. The actual composed proof/machine/report+38 receipt subset costs2,029,710B; its14,831B typed manifest adds29,662B. Fixed concrete-policy proof/machine/report/manifest and seven unchanged/frozen Parent helper bodies including preclaim complete the known8,252,864B. SOURCE_READBACK01 and READ_INVENTORY01 retain every real path, hash and extent. No scientific dependency or lifecycle entry was imported.

All nine repeated-content groups were inspected. Exactly three current groups can share a canonical path without changing public predicates: concrete-policy MACHINE01.json(2,676B),REPORT01.md(5,361B),MANIFEST01.json(127,520B), already duplicated as literal composed-recovery receipts. A NEW independently sealed recovery evidence layout can place those three and the unchanged REVIEW_PROOF01.json under concrete-policy/ with the original filenames and literal modes. Point both the four review refs and the relevant recovery_receipts at those same paths. This saves271,114B over first reads plus finish rereads using the EXISTING path-keyed cache. It changes neither bytes nor reader semantics. Preserve all38 receipt bodies, all13 source-evidence origins and exact c5cf seven-field recovery proof; old review02 remains immutable. The nested policy manifest still validates its original top-level relative names. The new outer manifest must also seal these members. Original origin and mode history remains explicit.

The resulting current-body subtotal would be7,981,750B, leaving406,858 charged bytes or203,429 unique bytes for the entire future caller, full contract, final review and three proofs. Actual new recovery machine/report/manifest size differences must also be charged at twice their signed byte delta; these values remain unknown. Subtracting only the contract's minimal114,744B leaves88,685 unique bytes for everything else. This is possible headroom, not demonstrated final fit. Original old caller20,992B, old request131,041B and old admission receipt59,263B are size observations only; their old identities/source/effective19 cannot be reused. The latter59,263B is not asserted to be the required shape of the not-yet-authored genuine metadata proof.

No second eligible current fixed-body coalescence exists. Other identical bodies cross actual CAP registered-input paths, fixed195-source paths or mandatory external Parent paths. Each path must be separately authenticated; a digest match, hardlink, symlink, or reset reader cannot erase its read charge. If actual new proof bodies later coincide semantically and byte-for-byte with an already required reference, their SAME canonical path can be counted once, but no such qualifying future proof currently exists. In particular, existing composed recovery cannot fill full final source/registration/Parent recovery. If the final measured bundle exceeds the residual, stop for a separately reviewed byte-preserving dependency layout; no cap raise, receipt removal, body reencoding or guessed allowance is justified.

The smallest integration path is an external Parent successor, preserving six original helpers and genuine job/resource protocols while adding exact accepted preclaim557b7bcb as a seventh helper. Change only fixed context predicates to actual new source=design, gatee1846c9f,355tracked354pins11roles, expected cumulative20 and three FAILED histories; require the independent unused compatible100 identity/cell and parent=None. Actual adopted wrapper5f478bc3/current source watchdog91e21c52 are distinct from old f4ea and forensic watch04/bdeaca. The latter is preservation tooling, not a permitted scientific source replacement. Original scientific model20f451/trainingd527/100epochs/seed11/batch16/28lookback remain fixed.

Call the unchanged public validate_preclaim with the genuine job._admitted Admission, actual registered job/plan, and ten exact external references before any attempt/intent/spawn. Retain all current-source Git joins, executable/lock/251RECORD checks, package-origin re-audit, native environment, ownership, full-capacity watch, subreaper and cleanup. External preflight is not an atomic in-process adjacency guarantee to the child's later Run.start; original child admission and source/native checks remain indispensable. Reader caches canonical paths, charges all physical first reads and full final rereads, then performs a finite whole-reader signature join; no writer exclusion/ABA immunity follows. Original admission/Git/runtime operations occur outside this helper's8MiB counter and remain separately bounded by the real caller.

Circularity is resolved by freezing caller/helper bytes first, binding only the eight actual review/recovery refs in the genuine independent-source/input/runtime proof, and constructing the Parent contract from actual source/maps/runtime/helper pins and three actual proof refs. The final release hashes canonical contract with final_review omitted. The actual request then points to that release. The caller must receive request path/SHA externally and derive the two final refs from the exact request plus q.final_review, rather than embedding its own final request hash. A separately frozen final supplement must recover the completed request/release/caller evidence after their creation; no baseline proof may assert self-recovery. No draft field is release authority.

EXTERNAL_REFS_CURRENT01 contains only eight genuine known refs and two NULL future refs. INTEGRATION_REQUIREMENTS01 enumerates required actual values and concrete source locations. This handoff creates no Parent, proof, admission, registration, claim or numerical release. The old complete100 remains FAILED; all three spent identities/highest19 and17 remaining original phase obligations are preserved. The original preview's prospective20 and355tracked are not promoted here to observed adoption. Root and its distinct reviewer own adoption/current-source authentication, complete actual caller recovery and final dispatch eligibility.
'''
(H/'REPORT01.md').write_text(report)
machine={'schema_version':1,'decision':'READ_ONLY_FINAL_CALLER_HANDOFF_CURRENT_LAYOUT_OVER_8MIB','preclaim_sha256':'557b7bcb38b48e3bf1e9e5b5b1eae25ab4908b8567820e17700dc08774b48d16','preview_gate_sha256':'e1846c9fbd5d1964c867c9c7027e3e9a6009520c07841ed720c035374dbeb806','identity':'financial-wrapper-classification-eager-complete100-compatibility-20261004-01','cell':'financial-wrapper-classification-eager-reference-compatibility-20261004-01','parent':None,'known_budget':r['budget'],'coalesced_all_unknown_unique_ceiling_before_size_deltas':203429,'additional_fixed_coalescence_available':False,'actual_future_source':None,'actual_final_parent':None,'actual_final_release':None,'final_whole_preclaim_budget_proven':False,'numeric_authority':False,'admission_or_Run_or_Owner_constructed':False,'network_or_restore':False,'report_sha256':sha((H/'REPORT01.md').read_bytes())}
save('MACHINE01.json',machine)
rows=[]
for p in sorted(H.rglob('*')):
 if p.name=='MANIFEST01.json':continue
 s=p.lstat();r={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):r['kind']='directory'
 else:assert stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4194304;r.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()))
 rows.append(r)
save('MANIFEST01.json',{'schema_version':1,'manifest_self_excluded':True,'members':rows,'typed_members':len(rows),'regular_files':sum(x['kind']=='file' for x in rows),'logical_bytes':sum(x.get('bytes',0) for x in rows)})
print(json.dumps({n:sha((H/n).read_bytes()) for n in ['MANIFEST01.json','MACHINE01.json','REPORT01.md','READ_INVENTORY01.json','DUPLICATE_PATHS01.json']}))
