from pathlib import Path
P=Path(__file__).resolve().parent/'candidate'
def edit(name, changes):
 p=P/name;s=p.read_text()
 for a,b in changes:
  assert s.count(a)==1,(name,a[:100],s.count(a));s=s.replace(a,b)
 p.write_text(s)
edit('archive_transport.py',[
 ('from tradingagents.research.lifecycle import _immutable','from tradingagents.research.lifecycle import _immutable, _encode'),
 ('bytes_per_second, lease_callback):','bytes_per_second, lease_callback, receipt_sink=None):'),
 ("        _immutable(receipt, {'status': 'failed' if failure is not None else 'complete',","        record = {'status': 'failed' if failure is not None else 'complete',"),
 ("'stderr_tail': tail.decode('utf-8', errors='replace')})","'stderr_tail': tail.decode('utf-8', errors='replace')}\n        if receipt_sink is None:_immutable(receipt, record)\n        else:receipt_sink(receipt, _encode(record), failure is None)"),
 ('rate_kbit=32768, max_seconds=30):','rate_kbit=32768, max_seconds=30, receipt_sink=None):'),
 ('        self.counter = 0','        self.counter = 0\n        if receipt_sink is not None:\n            if not callable(receipt_sink):raise ValueError("actual receipt sink required")\n            self._receipt_sink=receipt_sink'),
 ('            lease_callback=self.live)\n\n    def mkdir','            lease_callback=self.live, **({"receipt_sink":self._receipt_sink} if hasattr(self,"_receipt_sink") else {}))\n\n    def mkdir'),
 ('            bytes_per_second=self.rate_bytes, lease_callback=self.live)\n        os.link','            bytes_per_second=self.rate_bytes, lease_callback=self.live,\n            **({"receipt_sink":self._receipt_sink} if hasattr(self,"_receipt_sink") else {}))\n        os.link'),
])
edit('archive_dispatch.py',[
 ("    typed=type(value) is dict and value.get('schema_version')==2", "    typed=type(value) is dict and value.get('schema_version')==2\n    history=type(value) is dict and 'control_history' in value\n    if history:\n        from .archive_control_history import validate\n        require(typed,'control history only explicit typed resource route');validate(value['control_history'])\n        fields=fields|{'control_history'}"),
 ("    require(config['max_diagnostic_bytes']>=config['max_payload_bytes']+META*config['max_commands'],'insufficient cumulative diagnostic allowance')\n    require(config['max_control_bytes']>=META*(8+4*config['max_commands']),'insufficient durable reservation/failure headroom')", "    if 'control_history' in config:\n        from .archive_control_history import capacity as control_capacity\n        bounds=control_capacity(config['control_history'],config['max_commands'])\n        require(config['max_diagnostic_bytes']>=bounds['diagnostic_bytes'] and config['max_control_bytes']>=bounds['control_bytes'],'insufficient bounded retained controls/failure headroom')\n    else:\n        require(config['max_diagnostic_bytes']>=config['max_payload_bytes']+META*config['max_commands'],'insufficient cumulative diagnostic allowance')\n        require(config['max_control_bytes']>=META*(8+4*config['max_commands']),'insufficient durable reservation/failure headroom')"),
 ("        self._expected={};self._bytes=0;self._spent=", "        self._history_policy=self._limits.get('control_history');self._history=None;self._control_journal=None;self._diagnostic_journal=None\n        self._publication_count=0;self._root_control_bytes=0;self._diagnostic_receipts=0\n        if self._history_policy is not None:\n            from .archive_control_history import Interval,Journal\n            self._history=Interval(self._history_policy)\n            self._control_journal=Journal(self.root/'controls',record_bytes=self._history_policy['success_control_bytes'],total_bytes=self._limits['max_control_bytes']-8*META,records=4*self._limits['max_commands'],shard_bytes=self._history_policy['shard_bytes'])\n        self._expected={};self._bytes=0;self._spent="),
 ("                lease_callback=self._callback,rate_kbit=self._limits['rate_kbit'],max_seconds=self._limits['max_seconds'])", "                lease_callback=self._callback,rate_kbit=self._limits['rate_kbit'],max_seconds=self._limits['max_seconds'],\n                **({'receipt_sink':self._receive_control} if self._history is not None else {}))"),
 ("            self._diag_inode=self._signature(self._transport.diagnostics);self._counter=0", "            self._diag_inode=self._signature(self._transport.diagnostics);self._counter=0\n            if self._history is not None:\n                self._diagnostic_journal=Journal(self.root/'diagnostic-controls',record_bytes=self._history_policy['success_diagnostic_bytes'],total_bytes=self._limits['max_diagnostic_bytes']-META-low.archive.MAX_BYTES,records=self._limits['max_commands'],shard_bytes=self._history_policy['shard_bytes'])"),
 ("        raw=canonical_bytes(value)\n        require(len(raw)<=META", "        raw=canonical_bytes(value)\n        if self._history is not None and (name.startswith(('command-','result-','reservation-','operation-','typed-')) and 'failed' not in name):\n            self._control_journal.append(name,raw);self._bytes+=len(raw);self._publication_count+=1;return\n        if self._history is not None:\n            require(self._root_control_bytes+len(raw)<=8*META,'failure/control headroom exhausted')\n            self._root_control_bytes+=len(raw)\n        require(len(raw)<=META"),
 ("        self._expected[name]=raw;self._bytes+=len(raw)","        self._expected[name]=raw;self._bytes+=len(raw);self._publication_count+=1"),
 ("    def _outer(self):", "    def _receive_control(self,path,raw,success):\n        require(self._history is not None and self._in_call and path.parent==self.root/'diagnostics' and self._diagnostic_receipts<self._spent['commands'],'receipt outside actual selected command')\n        self._diagnostic_receipts+=1\n        if success and len(raw)<=self._history_policy['success_diagnostic_bytes']:\n            self._diagnostic_journal.append(path.name,raw)\n        else:\n            require(len(raw)<=META,'failed original diagnostic exceeds finite headroom')\n            root,fd=low.archive.io._open(path.parent)\n            try:low.archive.io._write(fd,path.name,raw);low.archive.io._root(root,fd)\n            finally:_close_owned(lambda:os.close(fd))\n            if success:raise ValueError('original successful diagnostic exceeds selected compact cap; bytes retained, stop')\n\n    def _outer(self,*,sampled=False):"),
 ("and set(vars(self._transport))=={'identity','host','ssh','scp','rate_bytes','max_seconds','live','budget','diagnostics','counter','_dispatch_context'}", "and set(vars(self._transport))=={'identity','host','ssh','scp','rate_bytes','max_seconds','live','budget','diagnostics','counter','_dispatch_context'}|({'_receipt_sink'} if self._history is not None else set())"),
 ("        root,fd=low.archive.io._open(self.root)\n        try:\n            low.archive._inventory(fd,set(self._expected)|{'diagnostics'})", "        if self._history is not None:\n            require(self._transport._receipt_sink==self._receive_control,'selected receipt sink replaced')\n            self._history.check(self._full_history,force=not sampled)\n            return\n        self._full_history()\n\n    def _full_history(self):\n        root,fd=low.archive.io._open(self.root)\n        try:\n            low.archive._inventory(fd,set(self._expected)|{'diagnostics'}|({'controls','diagnostic-controls'} if self._history is not None else set()))"),
 ("        snapshot=self._diagnostics()\n        require(all(snapshot.get(k)==v", "        if self._history is not None:\n            self._control_journal.audit();self._diagnostic_journal.audit()\n        snapshot=self._diagnostics()\n        require(all(snapshot.get(k)==v"),
 ("        self._outer();cap=self._cap", "        self._outer(sampled=True);cap=self._cap"),
 ("        self._outer()\n\n    def view", "        self._outer(sampled=True)\n\n    def view"),
 ("'reservation-%08d.json'%len(self._expected)", "'reservation-%08d.json'%(self._publication_count if self._history is not None else len(self._expected))"),
 ("            diagnostic_snapshot=self._diagnostics()", "            if self._history is not None:\n                require(self._diagnostic_receipts==self._spent['commands'],'actual original command receipt absent')\n                # Successful command outputs are exactly zero bytes. Preserve\n                # their original name/stat/empty hash before removing only that\n                # empty staging file; get bodies remain caller-owned.\n                for empty in (self.root/'diagnostics').iterdir():\n                    if empty.name.startswith('command-') and empty.name.endswith('.bin'):\n                        st=empty.lstat();require(stat.S_ISREG(st.st_mode) and st.st_nlink==1 and st.st_size==0,'successful command output not empty')\n                        self._control_journal.append('empty-'+empty.name,canonical_bytes({'name':empty.name,'stat':list(low.archive.io._signature(st)),'sha256':digest(b''),'bytes':0}))\n                        require(low.archive.io._signature(empty.lstat())==low.archive.io._signature(st),'empty command staging changed')\n                        empty.unlink()\n                low.sync_directory(self.root/'diagnostics')\n            diagnostic_snapshot=self._diagnostics()"),
 ("        c._live();c._claims.add(key)", "        c._outer();c._live();c._claims.add(key)"),
])
edit('archive_owner_operations.py',[
 ("        self._identity = owners.cache_key(self._configuration())", "        self._identity = owners.cache_key(self._configuration())\n        self._history=None\n        from .archive_dispatch import View\n        transport=selection._transport\n        if type(transport) is View and transport._context._history is not None:\n            from .archive_control_history import Interval\n            self._history=Interval(transport._context._history_policy)\n            self._history_context=transport._context\n            self._evidence()"),
 ("    def _evidence(self):\n        if hasattr", "    def _evidence(self,*,sampled=False):\n        if self._history is not None:\n            require(self.selection._transport._context is self._history_context,'selected history context changed')\n            self._history.check(self._full_evidence,force=not sampled)\n            return\n        self._full_evidence()\n\n    def _full_evidence(self):\n        if hasattr"),
 ("        self._evidence()\n        require(not self._closed", "        self._evidence(sampled=not full)\n        if self._history is not None and self._active is not None:\n            operation=self._active\n            root,fd=io._open(operation.root)\n            try:\n                require(io._signature(os.fstat(fd))[:2]==self._pins[operation.root.name],'active archive operation directory changed')\n                require(io._read(fd,'intent.json',io.META_LIMIT)==io._json(thaw(operation.record)),'active archive operation intent changed')\n                for name,raw in (operation._terminal or {}).items():require(io._read(fd,name,io.META_LIMIT)==raw,'active archive terminal changed')\n                io._root(root,fd)\n            finally:_close_descriptor(fd)\n        require(not self._closed"),
 ("            self._live(operation)\n            self._write(operation.root,'complete.json',raw)", "            self._live(operation)\n            if self._history is not None:self._evidence()\n            self._write(operation.root,'complete.json',raw)"),
 ("        if self._closed:return\n        self._closed = True", "        if self._closed:return\n        if self._history is not None:self._evidence()\n        self._closed = True"),
])
