import hashlib,json,os,stat,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;D=F/'financial-genuine-wrapper-root-claimedrun-final-capture01-2026-10-04';V=F/'financial-genuine-wrapper-claimedrun-actual-final-capture-failure-review01-2026-10-04';sys.path.insert(0,str(F/'held-consumer-final-recovery-preparation04-2026-10-03'));import recovery04 as R
sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
def read(p):return R.read(p.parent,p.name)
ck(sha(read(V/'MANIFEST01.json'))=='9b29dc2e1e5cc71e17c6539876a1dcc0379dfdfc2bf60046cef7c84b4512d50b' and sha(read(V/'READBACK01.json'))=='1533e3d4888a0ba245750f55f376efac55efbc6e22935ea82a9d8b0be2399466','original failedreview frozen unchanged');prior=json.loads(read(V/'READBACK01.json'));raw=read(D/'ACTUAL_TOOL_TERMINAL02.json');ck(sha(raw)=='ef8e9f17782b1b7a01a3852c069bb3c8d2b8bb51c29b1fa0a6e8a632a9d6465b','actual additive terminal');t=json.loads(raw);ck((t['actual_tool_session'],t['start_tool_chunk'],t['completion_tool_chunk'],t['actual_tool_exit'])==(62650,'dcf485','133355',1),'actual original tool failure');ck(t['actual_parent_pid'] is t['actual_start_ticks'] is t['original_process_group_history'] is None,'original unavailable OS history unchanged null');ck(t['partial_archive_sha256']==sha(read(D/'union.tar.gz'))==prior['partial_archive_sha256'] and t['partial_archive_bytes']==len(read(D/'union.tar.gz'))==4190463,'sameoriginal incompletearchive');ck(t['prepack_union_manifest_sha256']==sha(read(D/'union-manifest.json'))==prior['prepack_manifest_sha256'],'sameoriginal prepackmanifest');ck(t['raw_stderr_sha256']==sha(read(D/'ACTUAL_CAPTURE01.err'))==prior['original_stderr_sha256'] and t['raw_stdout_sha256']==sha(read(D/'ACTUAL_CAPTURE01.out'))==prior['original_stdout_sha256'],'actual terminal/rawerrorstreamjoins');ck(not os.path.lexists(D/'UNION_AUTHENTICATION01.json') and t['successful_union_authentication_absent'] is True,'no successfulauthentication')
manifest_raw=read(D/'FAILED_SCOPE_MANIFEST03.json');ck(sha(manifest_raw)=='fdda7c05fa6b46d3054ffb56841ab816d00b51ff6aac93f40d9bae0092d45ceb','exact failurepreservationmanifest');m=json.loads(manifest_raw);ck(R.encode(m)==manifest_raw,'canonical actualmanifestencoding');actual=R.scan(D);members=[r for r in actual['members'] if r['path']!='FAILED_SCOPE_MANIFEST03.json'];ck(m==dict(actual,members=members) and len(members)==1484,'complete actual1484 excluding only ownappendedseal');ck('FAILED_SCOPE_MANIFEST03.json' not in {r['path'] for r in m['members']},'honest manifest selfexclusion')
for r in m['members']:
 p=D/r['path'];s=p.lstat();ck(stat.S_IMODE(s.st_mode)==r['mode'],'everyliteralfailedscope mode')
 if r['kind']=='file':b=read(p);ck(len(b)==r['bytes'] and sha(b)==r['sha256'],'everyfailedscope originalbody')
 else:ck(stat.S_ISDIR(s.st_mode),'originalfailedscope dir')
mp=json.loads(read(D/'union-bytes01/ORIGINAL_TREES01.json'));regular=links=0
for tr in mp['scope_trees']:
 root=Path(tr['original_root']);ck({'.'}|{p.relative_to(root).as_posix() for p in root.rglob('*')}=={r['path'] for r in tr['members']},'complete currentoriginal20membership')
 for r in tr['members']:
  p=root/r['path'];s=p.lstat();ck(stat.S_IMODE(s.st_mode)==r['mode'],'currentoriginalmode')
  if r['kind']=='file':b=read(p);ck(sha(b)==r['sha256'] and len(b)==r['bytes'] and b==read(D/'union-bytes01'/r['union_path']),'currentoriginal/copiedbody');regular+=1
  elif r['kind']=='lexical-symlink':ck(stat.S_ISLNK(s.st_mode) and os.readlink(p)==r['target'],'currentoriginal linkmetadata');links+=1
  else:ck(stat.S_ISDIR(s.st_mode),'currentoriginaldirectory')
ck(regular==1185 and links==50 and len(mp['scope_trees'])==20,'actual wholeoriginaldenominators');ck(R.scan(D)==actual,'failedRootcomplete stableafterread');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','tradingagents'} for n in sys.modules),'no numerical researchimport');x={'schema_version':1,'decision':'VERIFIED_ADDITIVE_ACTUAL_FAILURE_TERMINAL_AND_COMPLETE_FAILED_ROOT_SCOPE','original_failure_review_manifest_sha256':'9b29dc2e1e5cc71e17c6539876a1dcc0379dfdfc2bf60046cef7c84b4512d50b','actual_terminal_sha256':sha(raw),'actual_tool_exit':1,'failed_scope_manifest_sha256':sha(manifest_raw),'sealed_members_excluding_own_manifest':1484,'current_members_including_own_manifest':len(actual['members']),'checks':len(checks),'partial_archive_sha256':t['partial_archive_sha256'],'partial_archive_bytes':4190463,'original_error_stream_sha256':t['raw_stderr_sha256'],'original_OS_history':None,'original_current20_scopes_stable':True,'original_failed_disposition_unchanged':True,'complete_archive_or_final_union_accepted':False,'capture_replayed':False,'numerical_authority':False};(O/'READBACK01.json').write_bytes(R.encode(x));(O/'ACTUAL_TERMINAL_ORIGINAL01.json').write_bytes(raw);print(json.dumps({'checks':len(checks),'decision':x['decision']}))
