import hashlib,json,os,stat
from pathlib import Path
H=Path(__file__).resolve().parent
sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def put(n,o):
 with (H/n).open('x') as f:f.write(json.dumps(o,sort_keys=True,indent=2)+'\n')
future={'schema_version':1,'actual_future_pins':{'Root_witness_capture_index':None,'Root_witness_capture_authentication':None,'Root_witness_virtual_manifest':None,'Root_witness_shard_manifests_and_archives':None,'Root_witness_terminal_intent_raw_outputs':None,'independent_actual_witness_capture_review':None,'actual_Root_selection':None,'actual_Main_commit_remote_join':None,'actual_final_remote_recovery':None},'required_roles':['genuine actual sharded-plus-direct witness index/auth/virtual manifest and EVERY indexed shard archive/manifest','exact original direct READBACK01.json c47fcb6875375ecb8ea5c60926bae307955007751cdf52bec2473c44964e17e3,2532973B,0600 already in current core','actual witness capture intent/terminal/rawoutputs/adoption/source/helper pins','complete independent actual witness capture review','complete exporter02 source and independent review typed memberships including all raw controls and lexical witnesses, through direct bytes or reviewed exact full mapping','complete current census/reuse evidence if Root adopts its mapping','actual final source/helper/review/request/release metadata generated after this observation'],'count_bytes_rule':'Append only actual observed immutable bodies. Recompute deduplicated PATH count<=506, actual selected byte sum<=67108864, every body<=4194304, Gitcalls<=1024 and actual free floor10GiB. Current residuals exclude this census and all future receipts.','authority':'No current future hash, approval, remote OID or archive identity is inferred.'}
put('REQUIRED_FUTURE_ROLES01.json',future)
report='''Read-only final-preservation candidate census, not a Root selection, transport release or recovery. The snapshot at08:40:50UTC is recorded as exact sorted Main-relative regular paths with sizes, hashes, modes and roles. Complete typed original trees retain directories and literal symlinks separately. All2,734 observed regular candidate paths were within the existing4MiB limit; maximum is original failed partial4,190,463B. No Main/Source/Parent/gate/Git/ledger changes, network, claims, admission or numerical execution occurred.

Mandatory current core is117paths/22,672,976B. It includes unchanged transport0b397 plus its six REQUIRED Source325 supplemental objects; complete five-body currentSource339 captureb5b6/fdf7; all five original actual-admission-review files24e6451d including authentic059232d0; original actual admission receipts; genuine old Source339 remote9e6d/flatf9b3 and independent468d proof chain; all22 actual final shard archives/manifests plus actual index/auth/virtualmanifest/source/terminal metadata; exact eight failed old support/partial bodies; and original direct2,532,973B c47f readback. Source325 is supplemental historical evidence and cannot replace current Source339. The old failure stays FAILED, including old OS-historyNULL and cap/gzip cleanup errors.

Complete exporterpreparation02 has270 sealed members plus its manifest,123regulars/24,416,735B/20literal links. The final exporter independent review is407 sealed members plus its manifest,193regulars/17,470,329B/30literal links. Its d0bd935a seal was explicitly verified after the initial unknown-status observation; no source body changed in the later census. All original raw controls, initial harness failures and final metadata remain included in their typed inventories. The reviewer seal interpretation initially failed because the census harness needlessly renamed lexical-symlink to symlink; the failed harness/stderr is retained, and check02 compares the genuine spelling directly.1,047 metadata checks passed.

Selecting all current core plus complete exporterpreparation yields240paths/47,089,711B and leaves266paths/20,019,153B. Adding the complete independent exporterreview yields433paths/64,560,040B and leaves only73paths/2,548,824B BEFORE future witness archives/actual review and this census. This is current pressure, not a claim that future capture will fit. Directly selecting all five raw witness trees as well would be2,734paths/123,998,097B and fails both count and selected-logical limits. The five complete source trees have2,302regular bodies/61,971,030B; their future actual capture is unknown here. Never silently drop raw witnesses to meet the ceiling.

A concrete alternative records every316 exporterpreparation/review original regular path, mode, length and hash in EXPLICIT_REUSE_CANDIDATES01. Exact byte donors are an already required core body, an independently accepted current final canonical shard member, a genuinely already externally and flat recovered Source339 archive member, or one newly selected representative for the same exact bytes. No mode/path is inferred from the donor: each original retains its own mode/path in the full typed mapping. All50 exporter lexical-link witnesses remain literal metadata. This currently needs117core+105new unique byte representatives,222candidate paths/34,292,007B, leaving284paths/32,816,857B. Those residuals also exclude all future actual capture/review/census support. This mapping is NOT adopted or already recovered; Root needs a separately reviewed complete mapping, actual byte readback and fresh recovery joins before using it. A mere hash collision-free lookup is not authority, and donors cannot be replaced by summaries.

Archival reuse is explicit. The current1476member/1186file final virtual union is backed by eleven genuine canonical archives and20original-tree mapping, so raw union/shard-tree copies need not be separately selected. Old failed union bytes are exactly equal under the preserved old-prefix mapping; all eight non-union failure bodies remain required, especially incomplete rawfc7d which is never a successful gzip. Source339's747bodies already have genuine full archive/external/flat/review support; neither its flat physical copies nor old remote selected copies need to be duplicated. The five prospective witness source trees may be represented only after the actual sharded-plus-direct index/auth and independent acceptance exist: all2,302 original paths must be accounted, with c47f direct as declared. Future hashes/counts stay null rather than treating preparation as capture.

REQUIRED_FUTURE_ROLES01 lists pending actual witness index/auth/virtual manifest/every shard pair, direct original, terminal/intent/raw outputs, source/helper/reviews, final actual selection/commit/readback/recovery and all post-census receipts. Exact same-path rows are deduplicated for totals; content-only alternatives require the explicit extra mapping. Root alone may freeze the final sorted selection after all actual pins exist and recompute506paths/64MiBselected/4MiBbody/1024Git calls/10GiBfloor. This census does not infer compression savings, native capacity, runtime package recovery, empirical-store reconstruction or any financial result. Every prior source/failure/timing history stays immutable.
'''
with (H/'REPORT01.md').open('x') as f:f.write(report)
put('VERDICT01.json',{'schema_version':1,'decision':'COMPLETE_READ_ONLY_CURRENT_CENSUS_WITH_EXPLICIT_FUTURE_GAPS','checks':1047,'summary_sha256':sha(H/'SUMMARY02.json'),'core_rows_sha256':sha(H/'CURRENT_CORE_ROWS01.json'),'typed_trees_sha256':sha(H/'COMPLETE_TYPED_TREES01.json'),'reuse_mapping_sha256':sha(H/'EXPLICIT_REUSE_CANDIDATES01.json'),'reuse_rows_sha256':sha(H/'REUSE_ROW_CANDIDATE01.json'),'actual_selection':None,'actual_future_capture':None,'actual_new_remote':None,'adopted_deduplication':False,'numerical_authority':False})
rows=[]
for p in sorted(H.iterdir()):
 s=p.lstat();assert stat.S_ISREG(s.st_mode);body=p.read_bytes();assert len(body)<=4194304;rows.append({'path':p.name,'kind':'file','mode':stat.S_IMODE(s.st_mode),'bytes':len(body),'sha256':hashlib.sha256(body).hexdigest()})
put('MANIFEST01.json',{'schema_version':1,'scope':'complete read-only candidate census evidence excluding this manifest','members':rows,'member_count':len(rows)})
for n in ('MANIFEST01.json','VERDICT01.json','SUMMARY02.json','EXPLICIT_REUSE_CANDIDATES01.json','REUSE_ROW_CANDIDATE01.json'):print(n,sha(H/n))
print('current_files',len(rows)+1,'current_bytes',sum(r['bytes'] for r in rows)+(H/'MANIFEST01.json').stat().st_size)
