from pathlib import Path
p=Path(__file__).parent/'overlay/tradingagents/research/onchain_replication/treatment_admission.py'
s=p.read_text()
s=s.replace("'job_input', 'plan_input', 'disposition_input'):","'job_input', 'plan_input'):")
s=s.replace("        if r['status'] == 'complete':\n", "        if r['status'] == 'complete':\n            role(r['disposition_input'])\n",1)
s=s.replace("        else:\n            require(all(r[k]", "        else:\n            if r['disposition_input'] is not None: role(r['disposition_input'])\n            require(all(r[k]",1)
s=s.replace("        raw = run.read_input(name)\n        require(len(raw) <= LIMIT, 'metadata grew past bound')", "        import os, stat\n        fd = os.open(path, os.O_RDONLY | os.O_NOFOLLOW)\n        with os.fdopen(fd, 'rb') as stream:\n            require(stat.S_ISREG(os.fstat(stream.fileno()).st_mode), 'regular metadata required')\n            raw = stream.read(LIMIT + 1)\n        require(len(raw) <= LIMIT and sha(raw) == item['sha256'], 'metadata extent/hash differs')")
s=s.replace("    value, body, _ = _reader(run, input_name)", "    from .provenance import file_hash\n    source_path = Path(__file__)\n    require(run.admission.experiment['source_files'].get(str(source_path.relative_to(run.admission.root))) == file_hash(source_path), 'treatment verifier source is not admitted')\n    value, body, _ = _reader(run, input_name)")
s=s.replace("        saved, _, spath = _reader(run, reference['disposition_input'])\n        require(saved == row and spath == run.admission.root/PREFIX/'treatments'/claim['experiment_id']/(row['id']+'.json'), 'actual per-cell disposition differs')", "        actual_row_path = run.admission.root/PREFIX/'treatments'/claim['experiment_id']/(row['id']+'.json')\n        if reference['disposition_input'] is None:\n            require(row['status'] == 'unavailable' and terminal['status'] == 'failed' and not actual_row_path.exists(), 'only failed absent cell may use postmortem absence')\n        else:\n            saved, _, spath = _reader(run, reference['disposition_input'])\n            require(saved == row and spath == actual_row_path, 'actual per-cell disposition differs')")
s=s.replace("        parent_ref = plan['parents'][week]\n", "        parent_ref = plan['parents'][week]\n        for key, name in parent_ref.items():\n            if key != 'components': original(name)\n")
s=s.replace("        parent_receipts(pc, pt, pl, sha(pcraw), sha(pmraw), week, asset)", "        parent_row = parent_receipts(pc, pt, pl, sha(pcraw), sha(pmraw), week, asset)")
s=s.replace("        require(coverage['members'] == pcoverage['members']", "        require(parent_row['coverage_sha256'] == sha(pcovraw), 'parent ledger coverage differs')\n        require(coverage['members'] == pcoverage['members']")
s=s.replace("    admitted = admit_treatment(run, reference['treatment_input'], asset=cell['asset'], variant=cell['variant'], weeks=reference['treatment_weeks'])", "    require('treatment_population_plan_input' in reference, 'full population calendar/denominator input required')\n    population_plan, _, _ = _reader(run, reference['treatment_population_plan_input'])\n    require(population_plan.get('treatment_input') == reference['treatment_input'], 'population and fit treatment contracts differ')\n    calendar, _, _ = _reader(run, population_plan['calendar_input'])\n    from .population_assembly import required_weeks\n    from .contracts import Fold\n    fold = Fold(**population_plan['fold'])\n    require(fold.id == cell['fold'] and fold.member_hash == examples.fold_hash, 'actual fold treatment binding differs')\n    weeks = required_weeks(fold, calendar['lookback_days'])\n    require(list(weeks) == reference['treatment_weeks'] == population_plan['expected_weeks'], 'full fit treatment week denominator differs')\n    admitted = admit_treatment(run, reference['treatment_input'], asset=cell['asset'], variant=cell['variant'], weeks=weeks)")
p.write_text(s)
