"""Freeze source-only handoff; writes exclusive owned evidence only."""
import hashlib,json,stat,datetime
from pathlib import Path
H=Path(__file__).resolve().parent;D=H/'generated03';sha=lambda b:hashlib.sha256(b).hexdigest()
def put(n,v):(H/n).write_text(json.dumps(v,indent=2,sort_keys=True,allow_nan=False)+'\n')
source=json.loads((D/'SOURCE339_READBACK.json').read_text());caller=json.loads((D/'CALLER.DRAFT.json').read_text());delta=json.loads((D/'INPUT_DELTA.json').read_text());check=json.loads((D/'CHECKS01.json').read_text());extra=json.loads((H/'CHECKS04.json').read_text());charter=json.loads((D/'ORIGINAL_CHARTER02.json').read_text());runtime=json.loads((D/'draft-inputs/runtime_mapping.json').read_text())
requirements=[
 {'order':1,'predicate':'actual complete external and fresh failed-outcome recovery independently accepted','actual_proof':None,'scope':'both original raw failed identity scopes remain immutable; new planned failure has own complete recovery'},
 {'order':2,'predicate':'Root chooses explicitly reviewed same-absolute-root gate-only topology; no active run and no old source/body/history loss','actual_decision':None,'alternative':'separate root requires independently reviewed exact relocation of all absolute artifact/diagnostic paths; this draft does not authorize it'},
 {'order':3,'predicate':'Root adopts exact draft gate only, commits actual new source=current design, authenticates all339 tracked/338 excluding selfgate and194 scientific closure/149 package; all old objects/claims preserved','actual_source':None,'actual_design_source':None,'draft_gate_sha256':sha((D/'GATE.DRAFT.json').read_bytes())},
 {'order':4,'predicate':'independent exact new source/input/runtime/budget review, actual original job._admitted read-only receipt; 251 runtime RECORDs, genuine source origins; original exploratory dataset/windows remain exposed','actual_proof':None},
 {'order':5,'predicate':'new exact external Parent/request fixed to this unused reference and new source; genuine job._command / ResearchRun.start and existing claimed-run authorize, original native limits/whole watches; no old caller or spent identity reuse','actual_parent':None,'actual_request':None,'actual_release':None},
 {'order':6,'predicate':'complete actual new Source and full caller/witness external plus fresh flat recovery, source/context/body proofs joined to exact request','actual_proof':None},
 {'order':7,'predicate':'fresh dispatch-time memory/disk/CPU/namespace and no-active-run/native-cgroup measurements under unchanged limits, independent exact native eligibility','actual_observation':None},
 {'order':8,'predicate':'Root alone releases at most one original100 reference attempt; all actual outcomes retained; unexpected failure halts numerical releases pending diagnosis; no budget increase/refund/retry implicit','actual_launch':None},
 {'order':9,'predicate':'only actual COMPLETE reference claim/fit100 completion/checkpoint100-0/replay/outputs plus complete preservation can support later continuation; opaque planned parent checkpoint still needs genuine loader cursor/log/model/optimizer/RNG checks inside guarded continuation','actual_reference_complete':None}
]
put('RELEASE_REQUIREMENTS01.json',{'status':'DRAFT_NOT_RELEASED','requirements':requirements,'unfulfilled_nulls_are_refusals':True})
put('CONTINUATION_REQUIREMENTS01.json',{
 'status':'LATER_DEPENDENT_NOT_ADMITTED','original_identity':'financial-wrapper-classification-eager-continue100-20261003-01',
 'required_parent':'financial-wrapper-classification-eager-interrupt1-claimedrun-20261004-01','required_reference':caller['experiment'],
 'same_cell':'financial-wrapper-classification-eager-continued-20261003-01','source_functions':{'financial_wrapper_fixture.py':{'_parent':272,'_interrupt_case':303,'_one_epoch_state':309,'_interrupt_parent':317,'_reference_state':346,'execute':365}},
 'parent_descriptor_exact_fields':['parent','claim_input','terminal_input','checkpoint_input','completion_input','provenance','parent_job_input','parent_plan_input','fit_claim_input','failed_fit_input','diagnostic_input','schedule_input'],
 'reference_descriptor_exact_fields':['checkpoint_input','provenance','completion_input','claim_input','terminal_input'],
 'parent_actual_claim_sha256':'d390980c956aab64d5521698cbb6123ccf01ece94a95277b97755f019adf692b','parent_failed_sha256':'4b2d7b0d162e80fe2074997baed35f2d6e6c86e5f660872fc2b8e97bb9622558',
 'parent_checkpoint_manifest_sha256':'b2f7d33b2f2280f5d9b0a9731ea320c64d18768bda772926421ddb0af2e12c70','parent_checkpoint_state_sha256':'223ced42edec29ec0afd4ea5265b2e0a557a98787e57be47e841e8491511a281','parent_checkpoint_state_bytes':493424,
 'parent_checkpoint_decoded':False,'reference_claim':None,'reference_terminal':None,'reference_fit_completion':None,'reference_checkpoint':None,
 'all_checkpoint_members':'each original member must be registered individually at genuine path/hash/size; descriptors are role references not synthetic receipts',
 'scientific_equality':'parent provenance equality excludes source_commit only; reference excludes source_commit and cell_id only; current194 scientific bodies must be preserved',
 'runtime_checks':'actual parent checkpoint load epoch1/batch0 plus exact single epoch0 log before fit reservation; reference load100/0; original99 remaining updates then exact final model/Adam/RNG/log comparison',
 'absolute_paths':'failed-fit last_checkpoint and diagnostic checkpoint remain original absolute paths; silent companion-root relocation refused',
 'not_required_for_reference':'reference is independent full100, plan prior_input/reference_input null and experiment parent null',
 'tensor_currentness_and_numerical_equivalence_unproved':True})
put('MACHINE01.json',{'schema_version':1,'status':'SOURCE_ONLY_HANDOFF_DRAFT_NOT_RELEASED','author':'combined_worker_review','observed_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'current_source':source['source'],'current_gate_sha256':'3a20293832fa7ecc5e2821fb27dc940d1a997ab7f2ad373bc28f73e893e8781a','next_identity':caller['experiment'],'next_cell':caller['cell_id'],'future_source':None,'future_design_source':None,'future_admission':None,'future_parent':None,'future_release':None,'actual_current_claims':2,'actual_highest_allowance':19,'base_attempt_budget':18,'prior_attempts':0,'remaining':17,'new_extension':False,'phases_total':18,'original_denominator':charter['denominator'],'replay_copies_required':16,'distinct_original_cells':10,'source339_pins338':True,'implementation194_package149':True,'onchain_subpackage_body_count':141,'runtime_record_declarations':251,'model_config_sha256':'20f451c08143dd81491b5c9fa0a90243ee6a9363df1fbbfcbd9c45b32f9b054d','training_sha256':'d5276b75491e130bd03d43de28120f72dd792e42af4446382a6c127d387b8ec0','unchanged_plan_sha256':delta['unchanged_plan_sha256'],'draft_gate_sha256':sha((D/'GATE.DRAFT.json').read_bytes()),'changes':delta,'successful_check_counts':{'build03':check['checks'],'check04':extra['checks']},'count_qualification':'assertion/check events including repeated bounded source reads; not independent trials','preserved_failures':[{'script':'build01.py','error':'AssertionError: package count used onchain prefix141 instead of all tradingagents149','partial_outputs':'root ORIGINAL_CHARTER02 and draft-inputs retained'}, {'script':'build02.py','error':'NameError: Unavailable omitted from isolated AST validator namespace','partial_outputs':'generated02 retained'}, {'tool':'a822a7','error':'earlier read-only exploratory dict/list mistake AttributeError str has no attribute get','durable_raw_file':None,'qualification':'tool history only; not claimed to be a retained local raw traceback'}],'no_actual_admission_or_claim_or_native':True,'no_numeric_import_or_checkpoint_decode':True,'scientific_compact_Owner_Binding':None,'genuine_ResearchRun_and_native_monitor_Owner_required':True,'paper_fits_completed':0,'paper_fits_pending':1420,'no_capacity_or_numerical_equivalence_claim':True})
report='''# Next original complete100 reference handoff — source only

The first unused declared identity is `financial-wrapper-classification-eager-complete100-20261003-01`, original slot2, on the distinct `financial-wrapper-classification-eager-reference-20261003-01` cell. The unchanged plan dc567350… selects classification/eager/complete100, has no prior/reference input and no experiment parent. It must execute the original 100-epoch fit; the one-update failed checkpoint cannot substitute for this reference.

`generated03/GATE.DRAFT.json` is the concrete minimal **conditional same-absolute-root** successor: only that reference entry changes. It binds the already-present corrected execution_job4712/source_closure94a3 bodies, all338 current source pins excluding the self gate, and the existing adopted dfed extension/3268 independent review. All11 other gate entries, original041a charter, six other role bodies, exposed exploratory window, scientific configuration, outputs and runtime hashes are identical. No new implementation or input body is required for this exact topology. Complete literal JSON inversion restores the original gate bytes. Root must commit a genuine new current=design OID; old0a2 cannot authenticate modified gate bytes. A separate capsule requires a different reviewed relocation preparation, particularly the immutable absolute diagnostic/checkpoint paths.

The current reference entry is not ready: it retains289 pins, the e13 wrapper closure, old capsule disk paths and no extension. Original `budget_extensions.effective_budget` refuses it because an adopted extension must be carried forward. With the exact existing reviewed extension and both actual raw failed claims, the same original function returns19. Base18/prior0 stays unchanged;2 spent leaves17 slots for17 pending original phases. The extension's original consumed_before1 snapshot stays unchanged: it records its original adoption, while the actual latest19 adopter remains permanently FAILED. No further amendment, refund, transfer or reopened identity follows.

The complete18-slot charter and DAG are retained in `PHASES18.json`, with original historical null fields preserved and the actual slot1 fulfillment recorded separately. Original14COMPLETE/4plannedFAILED,8 complete100 fits,12 fit calls,800 training updates plus4 agreement updates,16 replay copies,10 cells,16 examples x28=448 distinct tiny graphs remain required. The extra earlier unexpected failure is separately spent. All1420 paper financial fits remain pending; the synthetic recipe is not an empirical dictionary or full population.

Actual Source0a2 readback authenticates339 Git/body records and338 gated hashes,194 implementation bodies including149 tradingagents package bodies (141 in the onchain subpackage). The historical reference closure differs only at the already adopted f4ea wrapper;193 other bodies remain exact. Model20f451 is the CONFIG hash; original trainingd527, seed11, full batch16, lookback28, architecture, gradients, Adam,100 epochs and exact/F32 tolerances are unchanged. All251 runtime RECORD declarations are retained; this task did not re-import or revalidate installed scientific packages.

Original source joins are copied literally and indexed by function/line/AST hash in `SOURCE_API_JOINS.json`. `financial_wrapper_fixture.admitted` verifies actual roles/roots/closure/runtime before scientific execution; `authorize` uses the genuine active ResearchRun and original admission/source/input checks, avoiding the previously failed second fresh admit. `execute` lines365–452 invokes original `training.fit_cell`, demands100 logs and actual replay before output publication. Genuine ResearchRun/native monitor Owner remain required. The synthetic route does not manufacture compact scientific Owner or Binding. `job._admitted`/`admission.admit` were not invoked.

Later continuation is separate. `_parent`/`_interrupt_parent` must join the genuine new plannedFAILED d390/4b2d claim and all original job/plan/fit/schedule/diagnostic/checkpoint inputs. The opaque checkpoint223ced42… (493424 bytes) and manifestb2f7 are authenticated by the pinned actual outcome review, not decoded here. `_one_epoch_state` still requires real loaded1/0 and exact epoch0 log. `_reference_state` must join actual COMPLETE reference claim/terminal, original fit completion100, every checkpoint member, and loaded100/0. Only then can original continuation perform99 updates and compare model/optimizer/RNG/logs exactly. No COMPLETE reference exists at this handoff.

`CALLER.DRAFT.json` deliberately contains null interpreter/source/current design/new external Parent/request/proofs/release/recovery fields. Its module argv is an incomplete job command template, not an external Parent invocation or launcher. `RELEASE_REQUIREMENTS01.json` lists exact outstanding predicates in dependency order. Root must finish the failed outcome's actual external/fresh recovery; adopt and independently review the new gate/source; obtain genuine read-only admission; bind a fresh case-specific Parent and request; preserve/recover the complete new source/caller/review scopes; remeasure unchanged native eligibility at dispatch; and release at most one new fixed attempt. Old5d5/request529c remain fixed to the spent interruption and cannot be rebound by this draft. No resource limit changed:3GiB memory, swap0/twoCPU/4MiB file,1800 native/1840 outer,6GiB startup,10GiB floor and1GiB whole writable storage watch remain. One-update resource observations do not establish100-epoch feasibility.

Verification: build03 recorded2033 bounded source/metadata checks; check04 recorded45 checks including full literal gate inverse, all18 denominators and five real original budget mutation refusals. These counts include repeated source-authentication events, not independent experiments. Both failed builder traces and partial outputs are retained: build01 used the wrong package prefix count; build02 omitted the original Unavailable class from its AST namespace. Separate build03 succeeds without rewriting either failure. An earlier exploratory read-only dict/list typo exists only in tool history and is identified as such. No checkpoint values, labels, scientific arrays, genuine handles, numerical run, real admission, Git mutation or network action was used.

This is an author preparation handoff requiring different-author review, not an accepted gate, release or empirical conclusion. Numerical continuation equivalence, full100 runtime/storage capacity, financial return/cashflow/fees/funding, empirical availability and paper performance were not tested.
'''
(H/'REPORT01.md').write_text(report)
# Typed complete local manifest, excluding only the manifest itself. No follow.
rows=[]
for p in sorted(H.rglob('*')):
 r={'path':str(p.relative_to(H)),'mode':stat.S_IMODE(p.lstat().st_mode)};s=p.lstat()
 if stat.S_ISDIR(s.st_mode):r['kind']='directory'
 elif stat.S_ISREG(s.st_mode):
  b=p.read_bytes();assert len(b)<=4194304;r.update(kind='file',bytes=len(b),sha256=sha(b))
 else:raise ValueError('unexpected local evidence type')
 rows.append(r)
put('MANIFEST01.json',{'schema_version':1,'scope':'complete owned source-only reference handoff including failed harnesses/partial outputs','self_excluded':'MANIFEST01.json','members':rows,'counts':{'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'logical_bytes':sum(r.get('bytes',0) for r in rows)}})
print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'report':sha((H/'REPORT01.md').read_bytes()),'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'logical_bytes':sum(r.get('bytes',0) for r in rows)}))
