from pathlib import Path
import hashlib,json,os,stat
H=Path(__file__).resolve().parent;B=H.parent;P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-complete100-compatibility-root-launch-20261004-01');A=B/'financial-wrapper-compatibility-root-admission01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest()
def save(n,x):(H/n).write_text(json.dumps(x,sort_keys=True,indent=2)+'\n')
(H/'evidence').mkdir(mode=0o700);origin=[]
for p in [P/n for n in ['parent01.py','REQUEST_DRAFT01.json','SOURCE_INVERSE01.json','preclaim01.py','supervisor01.py','descendants01.py','owned_io.py','bounded_git01.py','recovery04.py','PROTOCOL_PINS01.json']]+[A/'ACTUAL_ADMISSION01.json',A/'stdout',A/'stderr']:
 s=p.lstat();assert stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4194304;b=p.read_bytes();q=H/'evidence'/p.name;q.write_bytes(b);q.chmod(0o600);origin.append({'original_path':str(p),'copy_path':str(q),'original_mode':stat.S_IMODE(s.st_mode),'copy_mode':0o600,'bytes':len(b),'sha256':sha(b)})
ad=json.loads((A/'ACTUAL_ADMISSION01.json').read_bytes());stdout=json.loads((A/'stdout').read_bytes());assert sha((A/'ACTUAL_ADMISSION01.json').read_bytes())=='dcbef49b6fd6c89b3c0eb022113ff51dd987edb84d1b5ce7ddc8cb4b30bfbb65';assert sha((A/'stdout').read_bytes())==ad['stdout_sha256'] and (A/'stderr').read_bytes()==b'' and ad['actual_child_exit']==0 and not Path('/proc',str(ad['child_pid'])).exists();assert stdout['ready'] is True and stdout['run_started'] is False and stdout['empirical_inputs_opened'] is False
save('PROVENANCE01.json',{'copies':origin,'actual_readonly_admission_terminal_sha256':sha((A/'ACTUAL_ADMISSION01.json').read_bytes()),'actual_admission_ready_observed':True,'actual_original_child_currently_absent':True,'original_admission_not_rerun':True})
report='''ACCEPTED_SOURCE_DRAFT_ONLY for exact Parent424f13b6 and actual draft e7579251. This is a different-author source/request/inverse review; no final release, full preflight success or numerical capacity is established.

All22 declared literal replacements reverse exactly to original7f28cee6, including full AST equality. Six original helpers are byte-identical; the seventh is exact accepted preclaim557b7bcb. Core stream_hash, memory, contract, reference and child_cleanup ASTs are unchanged. Source/current=design32d57eac is independently read from actual local Git; all355 tracked blobs,354 source pins, each current body SHA/Git object/executable class,11 input hashes and13 definitions are joined. All12 older experiment definitions remain byte-equivalent JSON. Actual job755c/resources e1d3 protocols, model20f451/trainingd527,251 RECORD mapping and unchanged native/environment/ownership supervision remain bound. Runtime metadata authentication is source-reviewed here; the interpreter and251 runtime RECORD bodies were not rehashed by this review.

Actual fixed reference identity financial-wrapper-classification-eager-complete100-compatibility-20261004-01 uses the new reference-compatibility cell, parent=None and no prior/reference descriptor. The three original failed claim/terminal pairs remain genuine and unchanged, highest actual claim allowance19 and spent3. The newly registered prospective20 extension is distinguished from highest historical19; no refund, transfer, failed identity replay or paper credit follows. All1,420 paper fits remain pending.

The public preflight calls original job._admitted, validates source/runtime/package origins and genuine job._command, then derives exactly eight review/recovery refs from the actual independently hashed metadata proof. The final two refs come from the externally supplied exact REQUEST_FINAL01 path/SHA and q.final_review. Public preclaim independently rejoins the whole request/admission/proofs/helpers and actual source. The final contract digest excludes only final_review, preventing a final-review self-hash cycle. Caller source does not embed the eventual request hash. AST inspection confirms preflight has no direct directory creation, spawn, Owner or Run.start; attempt/intents and genuine supervision stay in launch after preflight returns. External preflight is a finite sample before the separately guarded child, not atomic adjacency to the child's Run.start.

The real draft has DRAFT_NOT_RELEASED and NULL full_recovery, independent_source_input_runtime and final_review. Actual validate_release and preflight refuse immediately with no draft release. Changing only the status label cannot bypass NULL fields. Missing-field controls, exact source/context comparisons and16 real descriptor error pairs pass in2,163 assertions. Each tested stream descriptor was actually closed and the first fatal escaped according to the unchanged owned_io contract. No general allocation-failure or secondary-evidence-completeness claim is inferred. Original reviewer check01 mistakenly accessed recovery04.IO (the primitive is imported as owned_io); its raw AttributeError/error-pair traceback and script remain preserved. Corrected check02 uses the actual owned_io class and passed. The original draft, all sources and histories were never edited.

Root's genuine read-only CLI admission terminal dcbef49b/stdout8982989e is authenticated as actual exit0, ready=true, run_started=false, empirical_inputs_opened=false; child1079341 is now absent. This review neither reran admission nor constructed substitute authority. The CLI observation is not the complete new Parent preflight. Actual Parent --launch and public main were not invoked. No project or numerical package was imported by the reviewer, no checkpoint decoded, no network/native action or new claim created. Only local read-only Git metadata and reviewer-owned opaque file controls ran.

Current draft117,551B plus caller22,909B uses140,460 unique bytes. Against the handoff's coalesced203,429 unique-byte remainder, arithmetic residual is62,969B for future proofs/release/contract growth and new evidence-layout size deltas. This is not a fit guarantee: changing NULL values, adding the actual three proofs, metadata refs and final review will add bytes; finish rereads all unique paths. The genuine new coalesced layout and its independently accepted machine/report/manifest remain pending. Final full source/registration/Parent recovery, exact independent source/input/runtime proof, final seven-field release and fresh complete8MiB preclaim measurement remain required. None of those missing values is invented here.
'''
(H/'REPORT01.md').write_text(report)
save('MACHINE01.json',{'schema_version':1,'decision':'ACCEPTED_SOURCE_DRAFT_ONLY','source_sha256':'424f13b653d970efc4994e76e27f4ff5e8cf732133daab6a956cb1a034299ea0','request_draft_sha256':'e7579251741a865a2955917a3a9dc346ed6710ffc08388f1907c727e95d0a721','original_parent_sha256':'7f28cee688b661584e57466838ecdb79f0e17aa52be7d6f2c04f374326de9fb3','actual_source':'32d57eac5ea14435cd9d4aeb3e3b04d98bf16c41','registration_sha256':'e1846c9fbd5d1964c867c9c7027e3e9a6009520c07841ed720c035374dbeb806','tracked':355,'source_pins':354,'roles':11,'helpers':7,'literal_inverse_edits':22,'independent_assertions':2163,'real_descriptor_error_pairs':16,'actual_read_only_admission_ready':True,'reviewer_admission_calls':0,'whole_preclaim_tested':False,'native_launch':False,'numerical_authority':False,'final_release':None,'new_full_recovery':None,'source_runtime_proof':None,'actual_full_budget_fit':None,'budget_unique_arithmetic_residual_before_unknowns':62969,'raw_harness_failure_preserved':True,'report_sha256':sha((H/'REPORT01.md').read_bytes())})
rows=[]
for p in sorted(H.rglob('*')):
 if p.name=='MANIFEST01.json':continue
 s=p.lstat();r={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):r['kind']='directory'
 else:assert stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4194304;r.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()))
 rows.append(r)
save('MANIFEST01.json',{'schema_version':1,'manifest_self_excluded':True,'members':rows,'typed_members':len(rows),'regular_files':sum(r['kind']=='file' for r in rows),'logical_bytes':sum(r.get('bytes',0) for r in rows)})
print(json.dumps({n:sha((H/n).read_bytes()) for n in ['MANIFEST01.json','MACHINE01.json','REPORT01.md','READBACK02.json']}))
