# Independent exact first financial caller contract review

Accepted for the exact source contract only. `RELEASE_REVIEW01.json` is the genuine independent seven-field body required by the installed `validate_release`; it is not a native outcome or immediate execution release. Complete final-union capture, actual external recovery, fresh flat recovery, independent union acceptance and fresh preflight remain mandatory before launch. No source contract defect was found within this bounded scope.

The actual candidate is `ed9513a0727211c69953d57bbd5ecd465e9b07df73b2944b3c9e58eb31931ca2`, contract `6884fa8027cf49b519f5c635828244d4685ce0f989691593e816792e2586704a` excluding only final_review. Caller `3546fadac261bf1853b0139466c296c351e568b3842658d2984ac0aa5bdb8843` and its six helper bodies equal the independently accepted Parent03 originals. All original 15 Parent members retain exact types, modes and bodies; exactly four genuine appendages give 19 current members. The original draft remains unchanged. The candidate changes only status and the full_recovery proof from that draft; final_review remains null and the exact extracted validator refuses with `unresolved release field final_review`. The request's RELEASED status string alone is insufficient authority.

`check02.py` passed 2,869 checks. Complete current source878 and Parent19 manifests were matched before and after review. All 290 tracked paths, modes, opaque bytes, Git object identifiers and blob framing match immutable d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0 and the accepted installed-admission record; the working tree remains clean. This comprises 194 unchanged implementation files, including 149 package files, and 96 auxiliary files. The selected registration has 289 source pins excluding the gate itself. Its eight inputs and runtime map match actual files. Interpreter and all 251 distribution RECORD/version/path pins were read and checked, including legitimate read-only hardlinks. Basic historical expectation fields match current metadata; current Torch/CUDA API equality remains unobserved.

The three proof references match actual bodies. The full-recovery machine/report/manifest are exact copies of a3e020e2/8c7f67a6/e01c840f from the independent actual recovery review. That genuine chain covers the complete source878 and original Parent15, including actual remote116 bodies and two-target flat647 files. It does not cover the four new appendages, this review, or the eventual final request. The caller checks proof bytes and the exact independent review schema; it does not parse or independently enforce final-union closure. Root must therefore retain the separate mandatory union gate. Neither a local manifest nor this source verdict can substitute for it.

The cumulative proof remains explicitly prospective accounting, not a claim that it originally adopted a gate. Its distinct synthetic family base18/prior0 is joined to the subsequent genuine installed gate/admission proof. Ten initial entries, eight withheld dependents and the exact fixed 18-slot topological order remain unchanged. The first identity is financial-wrapper-classification-eager-interrupt1-20261003-01. No research_runs, research_artifacts, fixture_outer or Parent attempt namespace exists at review. No budget refund, paper65, transfer from exhausted historical families, or reset of same-mechanism history is admitted. This review does not reclassify historical FAILED/UNAVAILABLE outcomes or repeat the prior history investigation.

The source command uses the pinned interpreter with -B and the actual job module, root, registration, identity and committed source. It dispatches the genuine launch/monitor/worker path with owned native environment directories under the source root and two-thread environment settings. Registered limits are 3 GiB memory high/max, zero swap in the guard call, 3 GiB reserve, 6 GiB startup availability, 10 GiB disk floor, 1 GiB whole-root storage budgets, 4 MiB file limit and 1800-second native wall limit. The wrapper's cooperative deadline is 1700 seconds; the outer supervisor samples an 1840-second active bound with separate cleanup/control work. These are source policies, not proof that a fit will finish or that a strict total wall bound holds.

The actual function is `job.worker`, which enters genuine ResearchRun.start before full inventory comparison with Torch enabled, then invokes the financial fixture. The fixture repeats actual inventory verification before tensors and requires CPU execution. A mismatch consumes a genuine FAILED attempt and permits no retry. For this first interrupt1 case, the genuine one-epoch checkpoint callback raises PlannedInterruption; no completion or success is manufactured. Later independent outcome review must authenticate the original claim, all outputs, checkpoint cursor, failed-fit/lifecycle/native/outer terminals and cleanup. Planned FAILED must remain FAILED and spent. Unexpected failure stops subsequent numerical release; continuation and prediction require authentic recovered predecessor evidence and separately admitted dependent registrations.

The first-fatal and cleanup seams remain the exact accepted Parent03 bodies. Callback publication retains the process handle before the fallible census; directory close and all cleanup callbacks use the accepted reducer. Actual parent exit remains null inside its own terminal and must be supplied by the external actual terminal, not coerced. Cleanup/outcome semantics remain unaccepted until independently observed. The no-live inference requires the original pre-dispatch protocol, ordinary descendant drainage, absent original identities and all five absent native records. Native PID sampling is not a complete historical census. Prior asynchronous interruption/allocation windows, actual OS cleanup uncertainty and whole-fit capacity qualifications remain; this review does not claim universal closure of those paths.

The original check01 StopIteration is retained: the review harness looked for `_worker`, while the actual source names it `worker`. check02 corrects that source lookup and uses the actual `disk_floor_bytes` key; no reviewed source changed. An earlier shell read requested resources.py at the wrong package level and returned no file; the correct onchain_replication/resources.py was subsequently read. This was a read-only navigation error. No numerical package, lifecycle module, native command, preflight, ResearchRun, Owner, Binding or launcher was executed. No source/Parent/registration/Git/network mutation occurred. Only the new review directory was written.
