import copy,hashlib,json,os,stat,subprocess
from pathlib import Path
R=Path.cwd();F=R/'research/onchain-paper-replication-2026-09-24/full_sources';H=F/'real-data-pilot-retry13-review01-2026-10-06';D=F/'real-data-pilot-final13-2026-10-06'
def ld(p):return json.loads(p.read_bytes())
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def ref(p):return {'path':str(p.relative_to(R)),'sha256':sha(p)}
draft=ld(D/'BINDING_DRAFT02.json');final=ld(D/'BINDING01.json');review=ld(H/'BINDING_REVIEW02.json');expected=copy.deepcopy(draft);expected['status']='FINAL_BOUND_REQUIRES_COMMITTED_RELEASE';expected['binding_review']=ref(H/'BINDING_REVIEW02.json');assert final==expected and review['decision']=='accepted' and sha(D/'BINDING01.json')=='b7f347ab573788e88ae313d0bc46aa3ef48a8f48ba944e1c1888e0e812ca9062'
evidence=review['evidence'].copy()
for p in [D/'BINDING01.json',H/'BINDING_REVIEW02.json',D/'ACTUAL_READONLY_ADMISSION02.json']:evidence[str(p.relative_to(R))]=sha(p)
opaque=final['transport'];private=[p for p in evidence if p.startswith('research_artifacts/real_pilot_runtime/')];assert private==[opaque['path']] and evidence[opaque['path']]==opaque['sha256']
# Authenticate only the new final seams here; all other public refs were authenticated in the accepted binding review.
for p in [D/'root_io02.py',D/'preflight02.py',D/'gate02.json',D/'BINDING01.json',H/'BINDING_REVIEW02.json',D/'ACTUAL_READONLY_ADMISSION02.json']:assert evidence[str(p.relative_to(R))]==sha(p)
p=R/opaque['path'];st=p.lstat();assert stat.S_ISREG(st.st_mode) and stat.S_IMODE(st.st_mode)==0o600 and st.st_nlink==1 and st.st_size==928 and st.st_uid==os.getuid()
a=ld(D/'ACTUAL_READONLY_ADMISSION02.json');assert a['ready'] and a['effective_attempt_budget']==84 and a['source_pins']==269 and a['compact_input_pins']==59 and not a['research_run_start_called'] and not a['scientific_owner_created']
assert subprocess.check_output(['git','show',a['source']+':'+str((D/'gate02.json').relative_to(R))])==(D/'gate02.json').read_bytes()
assert not (R/'research_runs'/final['identity']).exists() and not (D/'launch-attempt01.json').exists() and not os.path.lexists(R/'research_artifacts/archive-dispatch-ethpilot-20261006-13')
o=ld(F/'real-data-pilot-retry12-review01-2026-10-06/EXACT_LAUNCH_RELEASE01.json')
o.update(identity=final['identity'],reviewer='pilot09_review independent fresh13 conditional release reviewer',binding_sha256=sha(D/'BINDING01.json'),binding_review_sha256=sha(H/'BINDING_REVIEW02.json'),actual_readonly_admission=a,actual_readonly_admission_reference=ref(D/'ACTUAL_READONLY_ADMISSION02.json'),evidence=evidence,
 cardinality={'changed_package_pins':1,'gate_input_roles':59,'gate_source_pins':269,'package_pins':179,'released_unique_references':len(evidence),'sole_opaque_private_exceptions':1,'unchanged_package_pins':178},
 accounting='84=53 genuine closed spent claims (17 correlated prior plus36 actual current;33COMPLETE20FAILED)+28 unchanged pending+two permanent preclaim03reserve74 and08reserve79+one fresh fixed13. Genuine12 claim83 permanently FAILED. No fabricated preclaim, refund, transfer, reopening, cap ladder or financial-fit allowance.',
 scope='Final binding differs solely by authentic review reference and final status from accepted draft. Genuine committed readonly84/269/59 and exact gate bytes at3b03eaaf joined without synthetic fields. Accepted binding810 refs reused; no admission or unchanged matrix repeated. Both unchanged numerical helper source paths are explicitly registered and the fresh caller validates the exact Target source closure and actual hashes before downstream scientific work.',
 source_provenance_scope='Current exact imported kernel8d810af1 and scalar helper30a957ad accepted narrowly in SOURCE_REVIEW01 under current Target/Owner wrapper; complete n*32 coverage and scoped callback joins inspected. Original bridge whole-fixture WITHHELD disposition remains, and historical pair-workload acceptance remains isolated purpose/scalar scope. No helper-body mutation, sampling, clustering, tolerance or architecture change.',
 timing_qualification='Actual11 passed all seven Target constructors and then failed before MCM computation on missing helper source registration; this does not prove full MCM or training capacity. Earlier timing boundaries and30s mandatory refusal remain unchanged.',
 private_transport_scope='SOLE selected13-r2 protected dispatch reference is metadata/stat/public-digest bound and authenticated internally by genuine committed admission. Reviewer did not read private body. Historical opaque inputs excluded from evidence-map body entries.')
o['conditionality']=o['conditionality'].replace('fixed12','fixed13');o['not_tested'][2]='No fresh host eligibility, full pair workspace, complete seven-graph/MCM/training capacity, throughput or ETA.'
o['scope']='Final binding differs solely by authentic review reference and final status from accepted draft02. Genuine committed readonly84/269/59 and exact gate02 bytes at3b03eaaf joined. Accepted810 references reused; no admission or unchanged matrix repeated. Selected root_io02/preflight02/gate02/pure preparation02/binder02 and sole13-r2 dispatch agree; original01 namespace evidence remains preserved unselected.'
o['diagnostic_scope']='Unchanged notes-only freshness diagnostic and clock sampling/poisoning. Explicit registered maximum stale age alone changes30000→60000ms; independent synthetic exactly60s acceptance,60.001s refusal and callback failure poisoning verified. No empirical latency prediction.'
o['timing_scope']='Exact canonical-byte batching and genuine existing lease checks remain unchanged. User explicitly authorized60second maximum stale age. No callbacks inside graph hashes or after final identity hash. Existing single-graph timing does not prove whole MCM/training capacity.'
o['timing_qualification']='Actual12 permanently failed at genuine age30.05162506600027s (pre-callback24.771937047000392 + callback5.279688018999877). Permitting60s expands detection-age tolerance and is not a speedup. Actual13 native capacity and whole-pilot completion remain unproven.'
o['policy_change']='ONLY max_stale_ms30000→60000; live100ms/fingerprint1000ms/full10000ms and65536 calls remain. Full validation, poison/refusal semantics and physical limits unchanged. Detection is sampled without atomic writer exclusion.'
o['required_entry']={'root_io':ref(D/'root_io02.py'),'preflight':ref(D/'preflight02.py'),'gate':ref(D/'gate02.json')}
o['source_provenance_scope']='Only package mutation from12 is strict storage identity12→13 (178 other package bodies unchanged). Registered60s input is separate. Current imported kernel8d810af1/scalar helper30a957ad remain accepted narrowly under current Target/Owner wrapper; original bridge whole-fixture WITHHELD disposition preserved; no helper/scientific body mutation.'
p=H/'EXACT_LAUNCH_RELEASE02.json';p.write_text(json.dumps(o,indent=2,sort_keys=True)+'\n');print(json.dumps({'sha256':sha(p),'references':len(evidence)}))
