from pathlib import Path
import ast,hashlib,json,os,stat
D=Path(__file__).resolve().parent;F=D.parent;S=F/'heartbeat-root-checkpoint10-2026-10-04/root_compatibility_gate_adopt01.py';P=F/'financial-wrapper-compatibility-gate-preview02-2026-10-04';B=F/'financial-wrapper-compatibility-operational-delta-capture02-2026-10-04/snapshot/COMPOSITION_BASIS01.json';CAP='/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source';h=lambda b:hashlib.sha256(b).hexdigest()
def put(n,o):(D/n).write_text(json.dumps(o,sort_keys=True,indent=2,allow_nan=False)+'\n')
source=S.read_bytes();assert h(source)=='f8aad6a7eab5f484036ae27d8c25ba1620be651c437644fcd8aca218686982c8';preview=json.loads((P/'PREVIEW01.json').read_bytes());a=json.loads((D/'PREVIEW_READBACK01.json').read_bytes());c=json.loads((D/'ADOPTER_CONTROLS01.json').read_bytes());assert (D/'PREVIEW_CHECK02.err').read_bytes()==b'' and (D/'ADOPTER_CONTROLS02.err').read_bytes()==b''
report='''# Exact Root gate metadata adoption review01

ACCEPTED_EXACT_ROOT_GATE_METADATA_ADOPTION_ONLY for root_compatibility_gate_adopt01.py SHA f8aad6a7eab5f484036ae27d8c25ba1620be651c437644fcd8aca218686982c8 and actual preview b725fa4f. Root may invoke this exact source once with this genuine review root to add the exact15 pinned files in fixture_inputs/financial_wrapper_compatibility01 under the same CAP Source7b056. This is a bounded metadata installation grant. It grants no Git commit, genuine Admission/Owner/Run, claim, numerical execution, final caller/native release, budget spend/refund/transfer or mutation of existing bodies.

The actual preview was freshly authenticated, not inferred from the author's report. All13 original prepared bodies are byte-identical to their frozen preparation; policy-recovery.json is exactly the genuine different-author c5cf38d2 proof; gates.json is exact e1846c9f. The actual recovery machine aae1d255/report4ddb9c23/typedseal4c1bafac authenticate the complete SOURCE_POLICY BYTE recovery and the proof. All73 review members authenticate, and all51 literal-copy origins (38 receipt copies plus13 source-evidence copies) rejoin their originals and original/copy modes. This acceptance does not convert those narrow byte claims into POSIX, installed-runtime, capacity or numerical proof.

The new gate preserves every top-level original field and all12 historical experiment definitions exactly. Old gate752c itself remains a source-pinned original body and is never rewritten. The new complete100 compatibility identity has parentNone, exact fixed reference cell,11 genuine role bodies, original eager complete100 plan and unchanged model20f451/trainingd527/100epochs/batch16/recipe seed11/batch16/lookback28. Every remaining experiment field—including family, charter, cumulative extension/review paths, runtime hashes, outputs and exploratory status—equals the now independently pinned draft. All195 implementation bodies remain exact target-map hashes, so the scientific method and hardcoded tolerances are unchanged. No scientific function is run.

Actual Source7b056 has340 distinct clean tracked paths. The15 new paths are disjoint from all existing paths, yielding355 prospective tracked paths; excluding only the new gate gives the exact354 source-pinned population. All11 input bodies also have matching source pins. Current whole589 non-Git capsule members were independently enumerated and compared for type/mode/body hashes, including all585 protected members. All394 original reachable logical Git objects were re-read locally with bounded, network-disabled Git commands and matched the frozen object type/length/hash index. The adopter itself invokes no Git or lifecycle API and writes no .git/history/existing source path. Git ancestry and commit/adoption verification remain a separate Root step after the installation result.

All three genuine historical claims and FAILED markers authenticate byte-for-byte, with no COMPLETE marker or extra identity. Their maximum actual allowance remains19 under original base18/prior0;3 attempts are spent. The genuine07100 extension/461d allocation/b5ac review remain prospective20 eligibility for17 pending original phase contracts; nothing spends20 at metadata installation or changes paper accounting. New gate and new run namespaces are currently absent. The adopter repeats these exact history hashes and namespace checks before mutation.

The candidate's Reader/ownedIO/manifest prefix is exactly the independently accepted cleanup successor02 prefix plus one blank separator; source and AST checks authenticate it. Its added put() opens O_EXCL/O_NOFOLLOW with explicit0600, loops bounded byte writes, fsyncs, and closes once through the same primary/first-fatal semantics.25 real owned write/close pairs cover ordinary/fatal body and close failures, preserved partial bytes, actual FD closure and object retention. Exclusive existing/symlink refusal,4MiB-before-open refusal and zero-write stop controls pass. Exact preview predicate inverses refuse altered identity/source/root/role/count/history/allowance and outside destinations. Exact terminal predicates on owned opaque populations accept unchanged old bytes plus the allowed addition and refuse old/new body or mode changes, inode replacement, extra membership, old-gate change, HEAD change and wrong new-directory mode. Public main() and read_release() were not invoked against fabricated authorization.

The one-use OUT reservation and durable INTENT precede any CAP addition. Only the new directory0700 and15 files0600 are written inside CAP; any failed or partial attempt remains present and the fresh-namespace checks prevent its automatic replay. After all output FDs close, whole605 membership must equal old589 plus15files plus the one new directory. Every old regular file retains its full signature/hash/mode/owner; old directories retain identity/owner/mode; new bodies and private modes are rejoined. Source HEAD and old-gate bytes remain exact. Final Reader namespace/signature joins and10GiB floor precede the immutable not-committed terminal. These are finite sampled checks, not writer exclusion or continuous atomicity; final Root outcome review is still required.

Metadata naming clarification: the INTENT field budget_spent_before=19 denotes the highest existing allowance, not the number of spent attempts. The separate actual_failed_before=3 and reviewed machine fields provide the correct spent denominator. The installed terminal explicitly remains NOT_COMMITTED/NOT_ADMITTED/NOT_NUMERICALLY_RELEASED. This naming issue does not change any source, gate allowance, or claim; later accounting must continue to distinguish3 spent attempts from highest19/prospective20.

Two reviewer harness failures are retained. preview_check01 expected38 total provenance rows; actual CLOSURE has51 rows comprising38 receipt and13 source-evidence origins. preview_check02 authenticates all51. adopter_controls01 initially demanded literal equality including the joining separator; the real candidate differs by exactly one blank line after the accepted prefix. adopter_controls02 verifies that exact difference and complete prefix AST equality. No candidate or original artifact was edited to make controls pass.

No financial experiment, numerical package/array or checkpoint decoding, live source/gate adoption, network, public Root entry, fabricated accepted recovery body, claim or ledger mutation occurred in this review. Actual metadata adoption, a genuine descendant Git commit, post-adoption proof, final writableCAP/gate/caller/contract recovery, exact complete8MiB preclaim eligibility, genuine Admission and final numerical release remain Root-owned later steps. Any source/preview/pin/scope change invalidates this exact one-use release and requires fresh review.
'''
(D/'REPORT01.md').write_text(report)
put('MACHINE01.json',{'schema_version':1,'decision':'ACCEPTED_EXACT_ROOT_GATE_METADATA_ADOPTION_ONLY','root_adopter_sha256':h(source),'preview_sha256':h((P/'PREVIEW01.json').read_bytes()),'composition_basis_sha256':h(B.read_bytes()),'allowed_new_file_pins':preview['new_file_pins'],'root':CAP,'source_before':'7b056a574e3e7b3c7ba209a39ee6a615e649d60c','numerical_authority':False,'claim_authority':False,'existing_body_mutation_allowed':False,'git_commit_authority':False,'maximum_metadata_adoptions':1,'outcome_review_required':True,'old_gate_sha256':preview['old_gate_sha256'],'new_gate_sha256':preview['new_gate_sha256'],'genuine_recovery_proof_sha256':'c5cf38d2a54682e9b36c0d4462cc07a611fb047cc422803b23d590552511b7a5','genuine_recovery_machine_sha256':'aae1d255e54bf8fb52a82c7c7dff6495df16e1c82b71d448828e28f841db116f','genuine_recovery_manifest_sha256':'4c1bafac000b164f4534e0308169214c9fd7f3f72cab2f4389a1647e6ada3cde','old_typed_preserved':589,'protected_typed_preserved':585,'old_git_objects_preserved':394,'expected_new_files':15,'expected_new_directory':1,'prospective_typed':605,'existing_tracked':340,'prospective_tracked':355,'source_pins':354,'input_roles':11,'original_definitions':12,'actual_failed_spent':3,'actual_highest':19,'base_attempt_budget':18,'prior_attempts':0,'prospective_extension':20,'extension_spent_by_adoption':False,'public_main_invoked_by_review':False,'preview_metadata_checks':a['checks'],'source_control_cases':len(c['rows']),'preview_readback_sha256':h((D/'PREVIEW_READBACK01.json').read_bytes()),'source_controls_sha256':h((D/'ADOPTER_CONTROLS01.json').read_bytes()),'report_sha256':h((D/'REPORT01.md').read_bytes()),'nonblocking_metadata_note':'budget_spent_before19 is highest allowance; true spent attempts3, unchanged.'})
rows=[]
for base,ds,fs in os.walk(D,followlinks=False):
 for name in ds+fs:
  p=Path(base)/name
  if p==D/'MANIFEST01.json':continue
  st=p.lstat();x={'path':p.relative_to(D).as_posix(),'mode':stat.S_IMODE(st.st_mode)}
  if stat.S_ISDIR(st.st_mode):x['kind']='directory'
  elif stat.S_ISLNK(st.st_mode):x.update(kind='symlink',target=os.readlink(p))
  else:assert stat.S_ISREG(st.st_mode) and st.st_nlink==1;x.update(kind='file',bytes=st.st_size,sha256=h(p.read_bytes()))
  rows.append(x)
put('MANIFEST01.json',{'schema_version':1,'manifest_self_excluded':True,'qualification':'Complete reviewer source/metadata/control seal, including explicit owned symlink negative and opaque HEAD fixtures; not a POSIX archival reconstruction.','members':sorted(rows,key=lambda x:x['path'])})
print(json.dumps({n:h((D/n).read_bytes()) for n in ['MACHINE01.json','MANIFEST01.json','REPORT01.md','PREVIEW_READBACK01.json','ADOPTER_CONTROLS01.json']},sort_keys=True))
