"""Genuine final metadata release; actual Parent validator functions only.
No Parent main, Admission, Owner, ResearchRun, model or preflight execution.
"""
from pathlib import Path
import sys,os,json,hashlib,re,ast,importlib.util
H=Path(__file__).resolve().parent;F=H.parent;P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-continue100-compatibility-root-launch-20261005-01');sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import Reader,R
rd=Reader();qr=rd.read(P/'REQUEST_FINAL_REVIEW_DRAFT01.json','a794aa04070a43a0d738cff1ec9a0fe91ff0d18c095a7f93ff2576ede7ac71ba');q=json.loads(qr);original_raw=rd.read(P/'REQUEST_SOURCE_BOUND_DRAFT01.json','eb5aaac1fa444f792c87c914094f7cd2b8f024295a4daf33f82e11ec1d1417db');original=json.loads(original_raw);fullref={'path':str(H/'CURRENT_FULL_RECOVERY_PROOF01.json'),'sha256':'97faaa53f2bcc1cdfd08756480e89632ae6ca6fc4a3f966ace53de3a59cdf19d'};expected=json.loads(original_raw);expected['status']='RELEASED_ONE_USE_FINANCIAL_PARENT';expected['proofs']['full_recovery']=fullref;rd.need(q==expected and q['final_review'] is None,'exact only status plus genuine current recovery ref; additive review remains absent')
caller=rd.read(P/'parent01.py','b50d1e727979a989f3da1e18a5b204cc3d29169ad425806e8550aa88af5ed0be');rd.need(q['caller_sha256']==R.digest(caller),'exact genuine caller pin')
for name,h in q['helper_hashes'].items():rd.read(P/name,h)
proofs={k:rd.read(Path(v['path']),v['sha256']) for k,v in q['proofs'].items()};full=json.loads(proofs['full_recovery']);source=json.loads(proofs['independent_source_input_runtime']);budget=json.loads(proofs['cumulative'])
rd.need(R.digest(proofs['independent_source_input_runtime'])=='18e4dcd06596478b8d338bd2b0b53cd6adcaca3f565fd85211ec591c335bb0d3' and R.digest(proofs['cumulative'])=='d0ae47f74f9d17c05ef974d6cfff422dd12957b608cb07144774b77498cc6f1f','two accepted genuine proof bytes unchanged')
rd.need(full['decision']=='accepted-current-source-bound-draft-byte-recovery' and full['source']==full['design_source']==q['source']==q['design_source']=='664e2ca5fa11d6640ab79f64c5aa222aeb3a9128' and full['identity']==q['identity'] and full['scope']['source_bound_draft_sha256']==R.digest(original_raw),'actual complete recovery and recovered draft lineage');review=json.loads(rd.read(Path(full['review']['path']),full['review']['sha256']));rd.need(review['decision']=='ACCEPTED_ACTUAL_CURRENT_SOURCE_BOUND_DRAFT_BYTE_RECOVERY' and review['source']==q['source'] and review['identity']==q['identity'],'genuine actual recovery review')
rd.need(source['source']==source['design_source']==q['source'] and source['identity']==q['identity'] and source['caller_sha256']==q['caller_sha256'] and source['registration']==q['registration'] and source['registration_sha256']==q['registration_sha256'] and source['source_pins']==359 and source['input_roles']==29 and source['tracked']==360,'accepted actual source/input/runtime metadata');rd.need(source['continuation_trusted_proof_contract']=={'path':str(P/'proof_reuse_contract01.json'),'sha256':q['helper_hashes']['proof_reuse_contract01.json']},'actual current proof-reuse contract pinned')
rd.need(budget['source']==budget['design_source']==q['source'] and budget['identity']==q['identity'] and budget['spent_claims']==4 and budget['complete']==1 and budget['failed']==3 and budget['highest_claim_allowance']==20 and budget['effective_attempt_budget']==20 and budget['remaining']==16 and not any(budget[k] for k in ('new_amendment','refund','transfer','numerical_authority')),'exact no-refund/no-amendment accounting')
comp=json.loads(rd.read(F/'financial-wrapper-continuation-current-preservation-preparation01-2026-10-05/CURRENT_COMPOSITION02.json','65ee768ba3a6569b125920bbc61f01d64487a90a5ced608df31b505cd008f370'));rows={r['path']:r for r in comp['capsule']['members']};cap=Path(q['capsule_root']);gate_raw=rd.read(cap/q['registration'],q['registration_sha256']);gate=json.loads(gate_raw);definition=gate['experiments'][q['identity']];rd.need(definition['source_files']==q['source_files'] and len(q['source_files'])==359 and all(rows[n]['sha256']==h for n,h in q['source_files'].items()),'complete actual recovered current source map');rd.need(q['input_hashes']=={k:v['sha256'] for k,v in definition['inputs'].items()} and len(q['input_hashes'])==29,'all29 actual registered input roles');head=rd.read(cap/'.git/HEAD').decode().strip();commit=rd.read(cap/'.git'/head.removeprefix('ref: ')).decode().strip() if head.startswith('ref: ') else head;rd.need(commit==q['source'],'actual unchanged currentCAP HEAD')
rd.need(not os.path.lexists(P/'attempt') and not os.path.lexists(cap/'research_runs'/q['identity']),'genuine unused continuation identity')
# Import only actual stdlib byte-reader utility, never Parent/preclaim modules.
sys.path.insert(0,str(P));spec=importlib.util.spec_from_file_location('actual_parent_byte_utility',P/'recovery04.py');U=importlib.util.module_from_spec(spec);spec.loader.exec_module(U);ns={'Path':Path,'hashlib':hashlib,'json':json,'re':re,'R':U};tree=ast.parse(caller);names={'sha','require','reference','contract','validate_release'};nodes=[]
for n in tree.body:
 if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id in {'CAP','PARENT','IDENTITY','SOURCE_BINDING','PROOFS'} for t in n.targets):nodes.append(n)
 if isinstance(n,ast.FunctionDef) and n.name in names:nodes.append(n)
exec(compile(ast.Module(body=nodes,type_ignores=[]),'<genuine actual Parent release validators>','exec'),ns);core=ns['contract'](q);rd.need(core=='705610759ceec477137e8f0275388689f2dbee8d3d1953002010ba16efc1bba6','actual exact Parent contract encoding')
# Two bounded refusal controls before granting actual concrete release.
controls=[]
for label,negative in [('genuine-null-final-review',q),('unreleased-source-bound-draft',original)]:
 try:ns['validate_release'](negative)
 except ValueError as error:controls.append({'case':label,'refused':True,'message':str(error)})
 else:raise AssertionError('missing expected unresolved authority refusal')
rd.finish();release={'schema_version':1,'decision':'accepted-exact-one-use-financial-parent','contract_sha256':core,'proof_sha256':{k:R.digest(v) for k,v in proofs.items()},'identity':q['identity'],'source':q['source'],'caller_sha256':q['caller_sha256']};R.put(H/'FINAL_PARENT_RELEASE01.json',release)
# This is the genuinely authored release, then actual untouched validator execution on its literal future reference.
bound=dict(q,final_review={'path':str(H/'FINAL_PARENT_RELEASE01.json'),'sha256':R.digest(R.encode(release))});rd.need(ns['validate_release'](bound)==release,'actual genuine complete release validates');rd.finish();result={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_FINANCIAL_PARENT_METADATA_RELEASE','request_draft_sha256':R.digest(qr),'recovered_source_bound_draft_sha256':R.digest(original_raw),'contract_sha256':core,'caller_sha256':q['caller_sha256'],'source':q['source'],'identity':q['identity'],'release_sha256':R.digest(R.encode(release)),'proof_sha256':release['proof_sha256'],'actual_unchanged_Parent_validator_pass':True,'controls':controls,'scientific_source_and_method_fields_unchanged':True,'actual_public_preclaim_executed_by_reviewer':False,'full8MiB_public_preclaim_still_required':True,'ResearchRun_or_Owner_created':False,'numerical_entry_executed':False,'source407_complete100_and_current_recovery_scopes_distinct':True,'future_final_authority_additive_to_recovered_draft':True,'checks':rd.checks,'read_bytes':rd.total};R.put(H/'FINAL_PARENT_RELEASE_READBACK01.json',result);print(json.dumps(result))
