from pathlib import Path
import sys,json
H=Path(__file__).resolve().parent;F=H.parent;sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import R
read=lambda n:R.read(H,n);ref=lambda p:{'path':str(p),'sha256':R.digest(R.read(p.parent,p.name))};v=json.loads(read('CURRENT_RECOVERY_READBACK01.json'));assert v['decision']=='ACCEPTED_ACTUAL_CURRENT_SOURCE_BOUND_DRAFT_BYTE_RECOVERY'
report='''# Actual current source-bound draft byte recovery

Accepted the actual single receiver and flat restoration:159 archive regular bodies/175 typed members/3,411,804 logical bytes, including all27 incremental payload files842,160 bytes and the exact finite review/proof closure. Every actual flat body was checked against the actual remotely returned archive and its genuine preserved original. Canonical archive framing, complete name/type/mode/body mapping, original mode/link metadata, exact selected Git objects, receipt/contract/release joins, fixed resource observations and cleanup were checked. The negative symlink remains literal metadata only. The source-phase snapshot is exact and unchanged; later review files are outside it.

The actual current CAP composition is823 regular/1,049 typed members,360 tracked paths/359 source pins/29 roles/source664e2ca5. All five new CAP bodies and11 source-bound draft Parent files, two genuine proofs and nine original Git object bodies are returned and joined. Accepted old818 body hashes are reused from the genuine complete100 recovery32acf316 plus its original capture, with a fresh whole current metadata/membership/mode/extent/final-signature observation. Old818 bytes were not reread or retransferred. Accepted source407 basis02900ae1 plus nine exact object hashes yields current416. This is the explicit complete byte-availability composition, not a claim that the small incremental archive alone contains all historical bodies.

Receiver19 actual Git operations and separate actual Root/child exits0 are accepted; its21 recorded PIDs/20 groups were absent. Flat actual Root tool87b99f and child exited0; its two recorded PIDs and one owned group were absent. Original inner actual_parent_exit remains null; no tools session was invented for the flat tool call. All cleanup failures are empty. The direct independent composition check read9,268,043 bytes in20,173 checks. No additional Root cross-join, restoration or numerical experiment was run.

The recovered Parent is the11-file source-bound DRAFTeb5aaac1 with callerb50d1e72 and exact helper/proof contract. Full-recovery and final-review fields are null in that archived draft. A future final request and release are additive authority bodies: actual unchanged Parent/preclaim validators must join them to this recovered draft/source and all three genuine proof hashes before launch. The recovery receipt is not recursively archived into itself. Final numerical release and the actual full8MiB public preclaim remain pending.

Original helper9161fc remains withheld for a real descriptor allocation leak; exact successor53f4a5fc and retained RED/GREEN evidence passed. Two reviewer harness errors remain preserved: the initial cleanup expectation overlooked IO09d1's sys.exception handling, and first entry-generation comparison overlooked dict insertion order after JSON parsing. Corrected controls passed without source changes. Transport report wording claiming Main-relative outer evidence paths was corrected by actual receiver-relative binding; inner request paths remain Main-relative. Stage59cc0f remote HEAD was held fixed through the two genuine receiver checks, avoiding a source-push mismatch.

No numerical authority, claim, budget amendment/refund, installed runtime-package body recovery, POSIX reconstruction, unrelated-store recovery, continuous writer exclusion or whole-capacity conclusion follows. New ordinary transport sources are locally pinned and retained; their external recovery is not asserted. All original failed/withheld bodies, original Parent nulls and accounting1COMPLETE3FAILED/highest20 remain preserved.
'''
with (H/'CURRENT_RECOVERY_REPORT01.md').open('x') as f:f.write(report)
remote=F/'financial-wrapper-continuation-current-remote01-2026-10-05';flat=F/'financial-wrapper-continuation-current-flat01-2026-10-05'
m={'schema_version':1,'decision':v['decision'],'reviewer':'/root/storage_watch_review','source':v['source'],'design_source':v['source'],'identity':v['identity'],'capsule_root':v['capsule_root'],'parent_root':v['parent_root'],'scope':{k:v[k] for k in ('current_CAP_regular','current_CAP_typed','Parent_source_bound_draft_files','source_bound_draft_sha256','tracked','source_pins','input_roles','current_Git_logical_objects','new_payload_files','new_payload_bytes','archive_regular','archive_typed')},'readback':ref(H/'CURRENT_RECOVERY_READBACK01.json'),'report':ref(H/'CURRENT_RECOVERY_REPORT01.md'),'actual_remote_receipt':ref(remote/'REMOTE_RECOVERY01.json'),'actual_remote_Root_exit':ref(remote/'ACTUAL_ROOT_EXIT01.json'),'actual_flat_receipt':ref(flat/'LANE_RECOVERY01.json'),'actual_flat_Root_exit':ref(flat/'ACTUAL_ROOT_EXIT01.json'),'original_parent_exit':None,'old818_hash_reuse_not_reread':True,'complete100_basis_sha256':v['complete100_basis_sha256'],'Git407_basis_sha256':v['Git407_basis_sha256'],'sampled_currentness_only':True,'final_authority_is_additive_and_unreleased':True,'final_public_preclaim_passed':False,'numerical_authority':False,'new_transport_source_external_recovery':False,'installed_runtime_bodies':False,'POSIX_reconstruction':False,'whole_capacity':False}
R.put(H/'CURRENT_RECOVERY_MACHINE01.json',m)
proof={'schema_version':1,'kind':'full_recovery','decision':'accepted-current-source-bound-draft-byte-recovery','source':v['source'],'design_source':v['source'],'identity':v['identity'],'capsule_root':v['capsule_root'],'parent_root':v['parent_root'],'scope':m['scope'],'complete100_basis':{'path':str(F/'financial-wrapper-compatibility-complete100-recovery-outcome-review03-2026-10-05/COMPLETE100_OUTCOME_RECOVERY_PROOF01.json'),'sha256':v['complete100_basis_sha256']},'Git407_basis':{'path':str(F/'financial-wrapper-compatibility-baseline-recovery-review02-2026-10-05/BASELINE_FULL_RECOVERY_PROOF01.json'),'sha256':v['Git407_basis_sha256']},'review':ref(H/'CURRENT_RECOVERY_MACHINE01.json'),'old818_hashes_reused_not_reread':True,'future_final_authority':'additive request/release must join recovered source-bound draft through exact Parent validators','numerical_authority':False,'excludes':['installed-runtime-package-bodies','new-transport-source-external-recovery','POSIX-reconstruction','writer-exclusion','whole-capacity','future-numerical-entry']};R.put(H/'CURRENT_FULL_RECOVERY_PROOF01.json',proof)
print(json.dumps({'proof':ref(H/'CURRENT_FULL_RECOVERY_PROOF01.json'),'machine':ref(H/'CURRENT_RECOVERY_MACHINE01.json'),'report':ref(H/'CURRENT_RECOVERY_REPORT01.md')}))
