from pathlib import Path
import sys,os,json,stat,ast,hashlib,importlib.util
H=Path(__file__).resolve().parent;F=H.parent;T=F/'financial-wrapper-continuation-current-transport-preparation01-2026-10-05';sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import Reader,R
sys.path[:0]=[str(T),str(T/'utilities')];spec=importlib.util.spec_from_file_location('current_transport',T/'outcome01.py');O=importlib.util.module_from_spec(spec);spec.loader.exec_module(O);rd=Reader();root=O.lane_root(0,'flat');remote=O.lane_root(0,'remote');cr=rd.read(root/'FLAT_CONTRACT01.json','ecbe50c500fe41d8fe12d5f3f4b30b19b2502431e0a58e3aa0513c19a012088b');c=json.loads(cr);qr=rd.read(root/'REQUEST_FLAT01.json','34aaff025c8a047ba3ff5d60d91a5f9498acc1b38046590b5440b5318a5be056');q=json.loads(qr);draft=json.loads(rd.read(root/'REQUEST_FLAT_SOURCE_BOUND01.json','55e6bad5aee3cac294b5d6e60b2fd795c3f22cee4767818f8e44e4dca993ce1b'));inner=rd.read(H/'INNER_FLAT_RELEASE01.json','01e124cca451287f6553638ea773432f17f7bd3ba38b6b01defdde3649ba2ca1');rd.need(q==dict(draft,release={'name':c['flat_release']['path'],'sha256':R.digest(inner)}) and rd.read(root/c['flat_release']['path'],c['flat_release']['sha256'])==inner,'only genuine literal release ref added');rd.need(O.request_core_sha256(q)=='653928c13c5d35eaa924f662d1d5039e82e40be239c86a3613f27d9fe8867418','same actual reviewed core')
capture=rd.read(T/'CAPTURE01.json',O.CAPTURE);g=O.generate(dict(q,required=O.expected_required(O.context(capture))),capture);caller=rd.read(root/'caller01.py','64b35553da199c840335e133939b136119049d7cd793d2c76346f8ca2f14cf2d');rd.need(caller==g['callers']['flat'].encode(),'entire unchanged generated actual caller');ns={'Path':Path,'os':os,'stat':stat,'hashlib':hashlib,'D':root,'RECEIVER':remote,'FILE':R.FILE,'IOPIN':'09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb','pins':{}};names={'sig','raw','read','rejoin','local','evidence','contract'};nodes=[n for n in ast.parse(caller).body if isinstance(n,ast.FunctionDef) and n.name in names];rd.need(len(nodes)==len(names),'actual extracted validator');exec(compile(ast.Module(body=nodes,type_ignores=[]),'<actual flat caller validators>','exec'),ns);rd.need(ns['contract'](c)=='FLAT','actual source-bound flat contract')
expected={'selection':'SELECTED_BODIES01.json','remote_receipt':'REMOTE_RECOVERY01.json','remote_root_exit':'ACTUAL_ROOT_EXIT01.json','selected_mode_profile':'ACTUAL_SELECTED_MODE_PROFILE01.json'}
for key in ('selection','request','remote_receipt','remote_root_exit','selected_mode_profile','flat_release'):
 ref=c[key]
 if key in expected:rd.need(ref['path']==expected[key],'exact receiver-relative evidence basename')
 p=(ns['evidence'] if key in expected else ns['local'])(ref['path']);rd.need(ns['read'](p,ref['sha256'])==rd.read(p,ref['sha256']),'actual evidence resolution and bytes')
rd.need(c['request']=={'path':'REQUEST_FLAT01.json','sha256':R.digest(qr)} and c['main_commit']==q['commit']=='cc0f324dc39a54f9a7868628ca788c2a840f028b','exact final request and commit');previous=json.loads(rd.read(remote/'REMOTE_CONTRACT01.json'));rd.need(c['helpers']==previous['helpers'] and len(c['helpers'])==20,'entire exact unchanged helper closure')
for name,h in c['helpers'].items():rd.need(rd.read(root/name,h)==rd.read(remote/name,h),'same actual helper bodies')
rd.need(rd.read(root/'recover01.py')==g['receiver'].encode() and rd.read(root/'receipt_current01.py')==g['receipt'].encode(),'actual generated receiver/receipt pair');fresh={'BUNDLE_FLAT_INTENT01.json','BUNDLE_FLAT_RECOVERY01.json','BUNDLE_FLAT_FAILED01.json','flat-current-increment','LANE_RECOVERY01.json'};rd.need(set(c['fresh_names'])==fresh and len(c['fresh_names'])==5,'entire exact fixed fresh scope');prefix='ROOT_CONTINUATION_CURRENT_FLAT02'
for n in fresh|{prefix+x for x in ('_INTENT.json','_SPAWN.json','.stdout','.stderr','_EXIT.json')}:rd.need(not os.path.lexists(root/n),'unused one-use entry/output')
for p in Path('/proc').iterdir():
 if p.name.isdigit() and int(p.name)!=os.getpid():
  try:args=ns['raw'](p/'cmdline').split(b'\0')
  except (FileNotFoundError,ProcessLookupError,PermissionError):continue
  rd.need(not any(str(root/n).encode() in args for n in ('caller01.py','restore_bundle01.py','recover01.py')),'no selected flat process already active')
rd.need(root.resolve()==root and stat.S_IMODE(root.stat().st_mode)==0o700,'actual private owned flat root');sample=O.W.census(root);ns['rejoin']();rd.finish();release={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_CONTINUATION_CURRENT_FLAT','contract_sha256':R.digest(cr),'caller_sha256':R.digest(caller),'numerical_authority':False};R.put(H/'OUTER_FLAT_RELEASE01.json',release);result={'schema_version':1,'decision':release['decision'],'owned_root':str(root),'contract_sha256':R.digest(cr),'caller_sha256':R.digest(caller),'request_sha256':R.digest(qr),'request_core_sha256':O.request_core_sha256(q),'inner_release_sha256':R.digest(inner),'release_sha256':R.digest(R.encode(release)),'all20_helper_pins_unchanged':True,'actual_receiver_evidence_paths':expected,'sampled_census':sample,'checks':rd.checks,'read_bytes':rd.total,'flat_outcome_accepted':False,'numerical_authority':False};R.put(H/'FLAT_ENTRY_READBACK01.json',result);print(json.dumps(result))
