from pathlib import Path
import sys,json,importlib.util,os
H=Path(__file__).resolve().parent;F=H.parent;T=F/'financial-wrapper-continuation-current-transport-preparation01-2026-10-05';sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import Reader,R,MAIN
sys.path[:0]=[str(T),str(T/'utilities')];spec=importlib.util.spec_from_file_location('current_transport',T/'outcome01.py');O=importlib.util.module_from_spec(spec);spec.loader.exec_module(O);rd=Reader();root=O.lane_root(0,'flat');remote=O.lane_root(0,'remote');raw=rd.read(root/'REQUEST_FLAT_SOURCE_BOUND01.json');q=json.loads(raw);prior=json.loads(rd.read(remote/'REQUEST_DRAFT01.json'));rd.need({k:v for k,v in q.items() if k not in ('remote','profile')}=={k:v for k,v in prior.items() if k not in ('remote','profile')},'only real remote/profile fields added');core=O.request_core_sha256(q);rd.need(core=='653928c13c5d35eaa924f662d1d5039e82e40be239c86a3613f27d9fe8867418' and q['release'] is None,'actual exact unsigned flat core')
for role in ('remote','profile'):
 ref=q[role];b=rd.read(MAIN/ref['path'],ref['sha256']);rd.need(len(b)==ref['bytes'],'actual exact inner Main-relative ref')
profile=json.loads(rd.read(MAIN/q['profile']['path'],'89bb2236c6a4493ca484c5d221db44c962511925596d954b7196803e14a54dcc'));observed=json.loads(rd.read(H/'SELECTED_MODE_PROFILE01.json'));rd.need(profile=={k:observed[k] for k in ('actual_selected_root','full_manifest')},'Root profile exactly equals independently sampled actual tree');rd.tree(remote/'selected',profile['full_manifest']);basis=json.loads(rd.read(H/'REMOTE_OUTCOME_READBACK01.json'));rd.need(q['remote']['sha256']==basis['remote_receipt_sha256'],'genuine independently accepted receiver')
for n in O.HELPERS+('CAPTURE01.json','archive-manifest.json','increment.tar.gz'):rd.need(rd.read(root/n)==rd.read(T/n),'exact unchanged installed flat source')
rd.need(rd.read(root/'receipt_current01.py')==rd.read(remote/'receipt_current01.py'),'actual exact receipt status checker');rd.need(not any(os.path.lexists(root/n) for n in ('LANE_RECOVERY01.json','flat-current-increment','BUNDLE_FLAT_FAILED01.json')),'fresh actual flat scope');O.W.census(root);rd.finish();release={'schema_version':1,'decision':'ACCEPTED_EXACT_CONTINUATION_CURRENT_FLAT','lane':0,'request_core_sha256':core,'source_sha256':'9e28b4ec5e3ef3e7e280378a82dd93484837c5f6820fc1e3d1c2824f3a9aff42','numerical_authority':False};R.put(H/'INNER_FLAT_RELEASE01.json',release);result={'request_sha256':R.digest(raw),'request_core_sha256':core,'release_sha256':R.digest(R.encode(release)),'Root_profile_equals_independent_observation':True,'checks':rd.checks,'read_bytes':rd.total,'outer_entry_released':False};R.put(H/'FLAT_CORE_READBACK01.json',result);print(json.dumps(result))
