"""Actual installed source/caller/selection predicates; no main, child or network."""
from pathlib import Path
import os,sys,json,stat,ast,hashlib,importlib.util
H=Path(__file__).resolve().parent;F=H.parent;T=F/'financial-wrapper-continuation-current-transport-preparation01-2026-10-05';sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import Reader,R,MAIN
sys.path[:0]=[str(T),str(T/'utilities')];spec=importlib.util.spec_from_file_location('current_transport',T/'outcome01.py');O=importlib.util.module_from_spec(spec);spec.loader.exec_module(O);from bounded_git01 import git
rd=Reader();root=O.lane_root(0,'remote');cr=rd.read(root/'REMOTE_CONTRACT01.json');c=json.loads(cr);qraw=rd.read(root/'REQUEST_DRAFT01.json');q=json.loads(qraw);capture=rd.read(T/'CAPTURE01.json',O.CAPTURE);generated=O.generate(q,capture);caller=rd.read(root/'caller01.py','2e1b40b909c77c23007ffa06d1fa8194fd35fdc05fe443d197641bb4da689387');receiver=rd.read(root/'recover01.py');rd.need(caller==generated['callers']['remote'].encode() and receiver==generated['receiver'].encode(),'entire fixed installed caller/receiver bodies');rd.need(rd.read(root/'receipt_current01.py')==generated['receipt'].encode(),'actual installed generated receipt')
selection_raw=rd.read(root/'SELECTED_BODIES01.json',c['selection']['sha256']);rd.need(selection_raw==generated['selection_body'],'verbatim actual canonical selection');selection=json.loads(selection_raw);rd.need(c['main_commit']==q['commit']==selection['remote_commit']=='cc0f324dc39a54f9a7868628ca788c2a840f028b','fixed actual Root-reported/readback commit')
# Actual caller pre-entry validator functions only; its public entry never executes.
ns={'Path':Path,'os':os,'stat':stat,'hashlib':hashlib,'D':root,'FILE':R.FILE,'IOPIN':'09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb','pins':{}};names={'sig','raw','read','rejoin','local','contract'};nodes=[n for n in ast.parse(caller).body if isinstance(n,ast.FunctionDef) and n.name in names];rd.need(len(nodes)==len(names),'actual extracted validators');exec(compile(ast.Module(body=nodes,type_ignores=[]),'<actual fixed remote caller validators>','exec'),ns);rd.need(ns['contract'](c)=='REMOTE','actual exact caller contract')
expected_helpers=set(O.HELPERS)|{'CAPTURE01.json','archive-manifest.json','increment.tar.gz','recover01.py','receipt_current01.py'};rd.need(set(c['helpers'])==expected_helpers and len(c['helpers'])==20,'entire exact helper closure')
for n,h in c['helpers'].items():
 raw=rd.read(root/n,h);rd.need(ns['read'](root/n,h)==raw,'actual caller helper read and retained signature')
 if n not in ('recover01.py','receipt_current01.py'):rd.need(raw==rd.read(T/n,h),'installed local exact frozen source')
rd.need(c['selection']=={'path':'SELECTED_BODIES01.json','sha256':R.digest(selection_raw)} and c['request'] is c['remote_receipt'] is c['remote_root_exit'] is c['selected_mode_profile'] is c['flat_release'] is None,'actual remote only/no future receipt fabricated');ns['read'](root/'SELECTED_BODIES01.json',R.digest(selection_raw));rd.need(q['remote'] is q['profile'] is q['release'] is None,'request future fields remain null')
# Execute actual frozen-selection validator, not main/any Git operation.
module=ast.parse(receiver);fn=next(n for n in module.body if isinstance(n,ast.FunctionDef) and n.name=='validate_fixed_selection');required=next(n for n in module.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='REQUIRED' for t in n.targets));count=next(n for n in module.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='FINAL_POPULATION_COUNT' for t in n.targets));v={'require':R.require,'REQUIRED':ast.literal_eval(required.value),'FINAL_POPULATION_COUNT':ast.literal_eval(count.value),'Path':Path};exec(compile(ast.Module(body=[fn],type_ignores=[]),'<actual frozen selection validator>','exec'),v);v['validate_fixed_selection'](selection)
rd.need(len(selection['rows'])==3 and sum(x['bytes'] for x in selection['rows'])==759580,'only exact3 selected bodies');objects=[]
for row in selection['rows']:
 raw=rd.read(MAIN/row['path'],row['sha256']);rd.need(len(raw)==row['bytes'],'actual selected path/body');line=git(MAIN,['ls-tree',c['main_commit'],'--',row['path']]).decode().strip();mode,kind,oidpath=line.split(' ',2);oid,name=oidpath.split('\t',1);rd.need(mode=='100644' and kind=='blob' and name==row['path'],'actual committed selected path/mode');stored=git(MAIN,['cat-file','blob',oid]);rd.need(stored==raw and hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==oid,'actual committed Git/body/OID join');objects.append(oid)
rd.need(10+len(set(objects))+2*len(objects)==19,'exact operations denominator')
fresh={'fresh-continuation-current01.git','selected','REMOTE_RECOVERY01.json','FAILED01.json'};rd.need(set(c['fresh_names'])==fresh and len(c['fresh_names'])==4,'entire exact fresh namespace');prefix='ROOT_CONTINUATION_CURRENT_REMOTE02'
for name in fresh|{prefix+x for x in ('_INTENT.json','_SPAWN.json','.stdout','.stderr','_EXIT.json')}:rd.need(not os.path.lexists(root/name),'unused one-use root');
for p in Path('/proc').iterdir():
 if p.name.isdigit() and int(p.name)!=os.getpid():
  try:args=ns['raw'](p/'cmdline').split(b'\0')
  except (FileNotFoundError,ProcessLookupError,PermissionError):continue
  rd.need(not any(str(root/n).encode() in args for n in ('caller01.py','recover01.py','restore_bundle01.py')),'no selected actual process')
rd.need(stat.S_IMODE(root.stat().st_mode)==0o700 and root.resolve()==root,'actual private receiver root');census=O.W.census(root);ns['rejoin']();rd.finish()
release={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_CONTINUATION_CURRENT_REMOTE','contract_sha256':R.digest(cr),'caller_sha256':R.digest(caller),'numerical_authority':False};R.put(H/'REMOTE_ENTRY_RELEASE01.json',release)
result={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_CONTINUATION_CURRENT_REMOTE','owned_root':str(root),'commit':c['main_commit'],'actual_network_readback':'Root observed; unchanged receiver independently checks initial and final remote HEAD','caller_sha256':R.digest(caller),'receiver_sha256':R.digest(receiver),'contract_sha256':R.digest(cr),'selection_sha256':R.digest(selection_raw),'selected_files':3,'selected_bytes':759580,'actual_committed_blob_oids':objects,'expected_operations':19,'release_sha256':R.digest(R.encode(release)),'sampled_census':census,'transport_source_external_recovery_claimed':False,'fresh':True,'numerical_authority':False,'checks':rd.checks,'read_bytes':rd.total};R.put(H/'REMOTE_ENTRY_READBACK01.json',result);print(json.dumps(result))
