"""Actual current receiver bytes/cleanup and original selected-mode observation."""
from pathlib import Path
import os,sys,json,stat,ast,hashlib,importlib.util
H=Path(__file__).resolve().parent;F=H.parent;T=F/'financial-wrapper-continuation-current-transport-preparation01-2026-10-05';sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import Reader,R
sys.path[:0]=[str(T),str(T/'utilities')];spec=importlib.util.spec_from_file_location('current_transport',T/'outcome01.py');O=importlib.util.module_from_spec(spec);spec.loader.exec_module(O)
rd=Reader();entry=json.loads(rd.read(H/'REMOTE_ENTRY_READBACK01.json'));root=O.lane_root(0,'remote');selected=root/'selected';prefix='ROOT_CONTINUATION_CURRENT_REMOTE02';sr=rd.read(root/'SELECTED_BODIES01.json',entry['selection_sha256']);selection=json.loads(sr);cr=rd.read(root/'REMOTE_CONTRACT01.json',entry['contract_sha256']);contract=json.loads(cr);q=json.loads(rd.read(root/'REQUEST_DRAFT01.json'));capture=O.context(rd.read(T/'CAPTURE01.json',O.CAPTURE));required=O.selected_required(q,0,capture)
rd.read(root/'receipt_current01.py',contract['helpers']['receipt_current01.py']);spec=importlib.util.spec_from_file_location('actual_current_receipt',root/'receipt_current01.py');M=importlib.util.module_from_spec(spec);spec.loader.exec_module(M)
rr=rd.read(root/'REMOTE_RECOVERY01.json','ffa9ca9ed28e7af85c532a1f7573e24e88efb0eae7dbd9382863e0d952428a51');remote=json.loads(rr);records=M.validate_remote(remote,selection,R.digest(sr),required);rd.need(len(remote['operations'])==remote['expected_operations']==19 and len(records)==3,'all real19 Git operations and exact3body denominator')
ar=rd.read(root/'ACTUAL_ROOT_EXIT01.json','4a738f2158f211a2550afad71e7da5b2076f32f60c72c6ff23a3cc845b347193');actual=json.loads(ar);rd.need(actual['actual_root_exit']==0 and actual['session']==61404 and actual['initial_chunk']=='8ad287' and actual['final_chunk']=='08bb68','separate actual Root tool receipt')
er=rd.read(root/(prefix+'_EXIT.json'));e=json.loads(er);rd.need(e['child_exit']==0 and e['actual_parent_exit'] is None and e['parent_failure_type'] is None and e['cleanup_failures']==[] and e['parent_fsize_readback']==[R.FILE,R.FILE] and e['elapsed_seconds']<630 and e['numerical_authority'] is False,'original inner ParentNULL, actual child0/cleanup/limits');rd.need(rd.read(root/(prefix+'.stderr'))==b'' and not os.path.lexists(root/'FAILED01.json'),'no failure/stderr');rd.read(root/(prefix+'.stdout'));intent=json.loads(rd.read(root/(prefix+'_INTENT.json')));spawn=json.loads(rd.read(root/(prefix+'_SPAWN.json')));rd.need(intent['contract_sha256']==entry['contract_sha256'] and intent['entry_release_sha256']==entry['release_sha256'] and intent['argv']==spawn['argv'] and intent['claim_started'] is False,'actual released caller/source/argv')
for sample in e['observations']:rd.need(0<=sample['logical_bytes']<=64*1024**2 and 0<=sample['allocated_bytes']<=96*1024**2 and 1<=sample['members']<=32768 and 0<=sample['seconds']<5 and 1<=sample['complete_attempts']<=3,'actual bounded namespace observations')
m=R.scan(selected);rd.tree(selected,m);files={x['path']:x for x in m['members'] if x['kind']=='file'};rd.need(set(files)==set(required),'actual selected complete membership')
for row in records:
 body=rd.read(selected/row['path'],row['sha256']);rd.need(len(body)==row['bytes'] and files[row['path']]['bytes']==len(body) and files[row['path']]['sha256']==row['sha256'] and hashlib.sha1(b'blob '+str(len(body)).encode()+b'\0'+body).hexdigest()==row['git_object'],'actual remote body/extent/OID');rd.need(body==rd.read(O.ROOT/row['path'],row['sha256']),'literal remote to committed source bytejoin')
for row in m['members']:rd.need((selected/row['path']).lstat().st_uid==os.geteuid(),'actual selected owner UID')
pids={spawn['pid'],intent['parent_pid']}|{x['pid'] for x in remote['operations']};groups={spawn['pid']}|{x['pid'] for x in remote['operations']}
for pid in pids:rd.need(not os.path.lexists(Path('/proc')/str(pid)),'recorded receiver PID absent')
caller=rd.read(root/'caller01.py',entry['caller_sha256']);node=next(n for n in ast.parse(caller).body if isinstance(n,ast.FunctionDef) and n.name=='raw');ns={'os':os,'FILE':R.FILE};exec(compile(ast.Module(body=[node],type_ignores=[]),'<accepted proc reader>','exec'),ns)
for p in Path('/proc').iterdir():
 if p.name.isdigit():
  try:b=ns['raw'](p/'stat');rd.total+=len(b);rd.tick()
  except (FileNotFoundError,ProcessLookupError,PermissionError):continue
  rd.need(int(b.decode().rsplit(')',1)[1].split()[2]) not in groups,'recorded owned receiver group absent')
O.W.check();rd.finish();profile={'schema_version':1,'actual_selected_root':str(selected),'expected_owner_uid':os.geteuid(),'full_manifest':m,'remote_receipt_sha256':R.digest(rr),'selection_sha256':R.digest(sr),'actual_root_exit_sha256':R.digest(ar),'original_inner_parent_exit':None,'scope':'Exact actual preserved original input modes; no chmod, private-mode or writer-exclusion assertion','numerical_authority':False};R.put(H/'SELECTED_MODE_PROFILE01.json',profile)
result={'schema_version':1,'decision':'ACCEPTED_ACTUAL_CONTINUATION_CURRENT_REMOTE_BYTES_ONLY','remote_root':str(root),'remote_receipt_sha256':R.digest(rr),'selection_sha256':R.digest(sr),'actual_root_exit_sha256':R.digest(ar),'inner_exit_sha256':R.digest(er),'actual_root_exit':0,'child_exit':0,'original_parent_exit':None,'cleanup_failures':[],'recorded_PIDs_absent':sorted(pids),'recorded_groups_absent':sorted(groups),'universal_process_history':None,'selected_files':3,'selected_bytes':759580,'actual_operations':19,'profile_sha256':R.digest(R.encode(profile)),'checks':rd.checks,'read_bytes':rd.total,'flat_outcome_accepted':False,'numerical_authority':False};R.put(H/'REMOTE_OUTCOME_READBACK01.json',result);print(json.dumps(result))
