"""Actual flat incremental bytes + accepted historical composition. Never restores."""
from pathlib import Path
import sys,os,json,stat,ast,hashlib,importlib.util,time
H=Path(__file__).resolve().parent;F=H.parent;T=F/'financial-wrapper-continuation-current-transport-preparation01-2026-10-05';sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import Reader,R
sys.path[:0]=[str(T),str(T/'utilities')];spec=importlib.util.spec_from_file_location('current_transport',T/'outcome01.py');O=importlib.util.module_from_spec(spec);spec.loader.exec_module(O)
def main():
 rd=Reader();root=O.lane_root(0,'flat');remote=O.lane_root(0,'remote');selected=remote/'selected';prefix='ROOT_CONTINUATION_CURRENT_FLAT02';entry=json.loads(rd.read(H/'FLAT_ENTRY_READBACK01.json'));rr=rd.read(root/'LANE_RECOVERY01.json');receipt=json.loads(rr);er=rd.read(root/(prefix+'_EXIT.json'));outer=json.loads(er);ar=rd.read(root/'ACTUAL_ROOT_EXIT01.json');actual=json.loads(ar)
 rd.need(actual['actual_root_exit']==0,'actual separate Root tool exit0');rd.need(outer['child_exit']==0 and outer['actual_parent_exit'] is None and outer['parent_failure_type'] is None and outer['cleanup_failures']==[] and outer['parent_fsize_readback']==[R.FILE,R.FILE] and outer['numerical_authority'] is False and outer['elapsed_seconds']<210,'actual child/cleanup/limits with original ParentNULL')
 qr=rd.read(root/'REQUEST_FLAT01.json',entry['request_sha256']);q=json.loads(qr);contract=json.loads(rd.read(root/'FLAT_CONTRACT01.json',entry['contract_sha256']));rd.need(O.request_core_sha256(q)==entry['request_core_sha256'],'exact reviewed core')
 for name,pin in contract['helpers'].items():rd.read(root/name,pin)
 rd.need(receipt=={'schema_version':1,'lane':0,'capture_sha256':O.CAPTURE,'request_sha256':R.digest(qr),'scope':'current-increment','scopes':receipt['scopes'],'numerical_authority':False,'requires_actual_composition_review':True} and set(receipt['scopes'])=={'current-increment'},'actual complete exact increment receipt')
 intent=json.loads(rd.read(root/(prefix+'_INTENT.json')));spawn=json.loads(rd.read(root/(prefix+'_SPAWN.json')));rd.need(intent['contract_sha256']==entry['contract_sha256'] and intent['entry_release_sha256']==entry['release_sha256'] and intent['argv']==spawn['argv'] and intent['claim_started'] is False,'actual exact one-use entry joins');rd.need(rd.read(root/(prefix+'.stderr'))==b'' and not os.path.lexists(root/'BUNDLE_FLAT_FAILED01.json'),'no failed/stderr outcome');rd.read(root/(prefix+'.stdout'))
 for s in outer['observations']:rd.need(0<=s['logical_bytes']<=64*1024**2 and 0<=s['allocated_bytes']<=96*1024**2 and 1<=s['members']<=32768 and 0<=s['seconds']<5 and 1<=s['complete_attempts']<=3,'all actual fixed-cap samples')
 profile=json.loads(rd.read(remote/'ACTUAL_SELECTED_MODE_PROFILE01.json','89bb2236c6a4493ca484c5d221db44c962511925596d954b7196803e14a54dcc'));rd.tree(selected,profile['full_manifest']);prefixpath=str(Path(O.CAPTURE_PATH).parent)+'/'
 capture_raw=rd.read(selected/O.CAPTURE_PATH,O.CAPTURE);c=O.context(capture_raw);mr=rd.read(selected/(prefixpath+c['manifest']),c['archive_pin']['manifest_sha256']);m=json.loads(mr);R.validate(m);archive=rd.read(selected/(prefixpath+c['archive']),c['archive_pin']['sha256']);rd.need(len(archive)==c['archive_pin']['bytes'],'actual remotely recovered archive bound');scope=receipt['scopes']['current-increment'];flat=root/'flat-current-increment';metaraw=rd.read(flat/scope['metadata_file'],scope['metadata_sha256']);meta=json.loads(metaraw);rd.need(meta['manifest']==m and meta['archive']==c['archive_pin'] and meta['schema_version']==1,'actual output carries entire original archive metadata');mapping=meta['flat_members'];expected={r['path']:r for r in m['members'] if r['kind']=='file'}
 rd.need(len(m['members'])==175 and len(expected)==159 and sum(r['bytes'] for r in expected.values())==3411804 and set(mapping)==set(expected) and len(mapping)==len(set(mapping.values())),'all original159/175 exact mapping');rd.need(scope['members']==175 and scope['regular_bodies']==159 and scope['archive_sha256']==c['archive_pin']['sha256'] and scope['manifest_sha256']==R.digest(mr) and scope['instantiated_posix_tree'] is False and scope['runtime_package_bodies_recovered'] is False,'honest actual restoration scope')
 fm={'schema_version':1,'root_mode':448,'members':[{'path':mapping[n],'kind':'file','mode':384,'bytes':r['bytes'],'sha256':r['sha256']} for n,r in expected.items()]+[{'path':scope['metadata_file'],'kind':'file','mode':384,'bytes':len(metaraw),'sha256':R.digest(metaraw)}]};fm['members'].sort(key=lambda r:r['path']);rd.tree(flat,fm);bodies={n:rd.read(flat/mapping[n],r['sha256']) for n,r in expected.items()}
 for n,b in bodies.items():rd.need(len(b)==expected[n]['bytes'],'all actual flat file extents')
 # Independent framing over the actual received archive against the actual flat bytes.
 it=R.framed_members(archive);seen=set();primary=None;typed={r['path']:r for r in m['members']}
 try:
  for n,t,b in it:
   rd.need(n in typed and n not in seen,'exact returned archive membership');seen.add(n);r=typed[n];rd.need(t.mode==r['mode'] and t.uid==t.gid==0 and t.mtime==0 and t.uname==t.gname=='','canonical actual archive metadata');rd.need((t.isfile() and b==bodies[n]) if r['kind']=='file' else (t.isdir() and t.size==0),'every actual archive/flat body equal')
 except BaseException as e:primary=e
 R._cleanup((it.close,),primary=primary)
 if primary is not None:raise primary
 rd.need(seen==set(typed),'complete returned archive denominator');table=json.loads(bodies['ORIGIN_TABLE01.json']);rd.need(R.digest(bodies['ORIGIN_TABLE01.json'])==c['origin_table_sha256'],'authentic original mode/link metadata');dep=json.loads(rd.read(H/'TRANSPORT_DEPENDENCIES01.json','dd10413fce4f83fbe2f86ca36367633771092e2152ab89654b381b19312fb1bb'));rd.need(set(table['scopes'])=={Path(x['path']).name for x in dep['closed_scopes']}|{H.name},'entire exact source/review snapshot scopes')
 links=[]
 for scope_name,orig in table['scopes'].items():
  origin=Path(orig['root']);sealname='SOURCE_PHASE_MANIFEST01.json' if origin==H else 'MANIFEST01.json';sealraw=bodies[scope_name+'/'+sealname];seal=json.loads(sealraw);rd.need([r for r in orig['members'] if r['path']!=sealname]==seal['members'],'genuine recovered scope seals/complete typed mapping')
  for r in orig['members']:
   p=origin/r['path'];s=p.lstat();rd.need(stat.S_IMODE(s.st_mode)==r['mode'],'actual original source mode retained')
   if r['kind']=='file':rd.need(bodies[scope_name+'/'+r['path']]==rd.read(p,r['sha256']),'all recovered source/evidence bodies equal genuine originals')
   elif r['kind']=='symlink':rd.need(stat.S_ISLNK(s.st_mode) and os.readlink(p)==r['target'],'literal uninstantiated link metadata');links.append(str(p))
   else:rd.need(stat.S_ISDIR(s.st_mode),'original directory metadata')
 for ref in table['basis']:rd.need(bodies[ref['snapshot_path']]==rd.read(Path(ref['path']),ref['sha256']),'actual returned accepted basis metadata')
 pp='financial-wrapper-continuation-current-preservation-preparation01-2026-10-05/';comp=json.loads(bodies[pp+'CURRENT_COMPOSITION02.json']);sel=json.loads(bodies[pp+'SELECTED_BODIES02.json']);rd.need(R.digest(bodies[pp+'CURRENT_COMPOSITION02.json'])=='65ee768ba3a6569b125920bbc61f01d64487a90a5ced608df31b505cd008f370' and R.digest(bodies[pp+'SELECTED_BODIES02.json'])=='afa2f09dc897f15d63433982fe3afb43119fd95cfeb3d1e289836281fecfc20a','actual complete composition/selector returned')
 cap=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');parent=Path(comp['source_bound_request']['path']).parent;rd.tree(cap,comp['capsule'],('.git',));rd.tree(parent,comp['parent']);objects={r['oid']:r for r in comp['git']['new_objects']};new={}
 for r in sel['bodies']:
  body=bodies[pp+r['path']];rd.need(len(body)==r['bytes'] and R.digest(body)==r['sha256'],'all27 actual newly recovered payloads');new[(r['original_root'],r['original_path'])]=body
  if r['role']=='git':
   obj=objects[r['original_path']];rd.need(len(body)==obj['bytes'] and R.digest(body)==obj['sha256'] and hashlib.sha1(obj['kind'].encode()+b' '+str(len(body)).encode()+b'\0'+body).hexdigest()==obj['oid'],'all nine returned logical Git objects genuine')
  else:
   p=Path(r['original_root'])/r['original_path'];rd.need(body==rd.read(p,r['sha256']) and stat.S_IMODE(p.lstat().st_mode)==r['original_mode'],'all new actual CAP/Parent/proof bytes and modes')
 old_capture=json.loads(next(bodies[r['snapshot_path']] for r in table['basis'] if r['sha256']=='ef82889318080bf2fec673d6c558c4afe3d95260c1a4d783c9b5eb16d8979442'));oldrows={r['path']:r for r in old_capture['originals']['capsule']['manifest']['members']};current={r['path']:r for r in comp['capsule']['members']};rd.need(all(current[n]==r for n,r in oldrows.items()) and len(current)==1049 and sum(r['kind']=='file' for r in current.values())==823,'old accepted818 plus new5 complete typed1049 mapping');rd.need(set(current)-set(oldrows)==set(comp['new_capsule_files'])|{'fixture_inputs/financial_wrapper_continuation01'},'exact no-omission current CAP decomposition');rd.need(len(comp['git']['old407'])==407 and set(comp['git']['old407'])|set(objects)==set(comp['git']['current416']) and len(comp['git']['current416'])==416,'old407 plus new9 complete Git set')
 head=rd.read(cap/'.git/HEAD').decode().strip();commit=rd.read(cap/'.git'/head.removeprefix('ref: ')).decode().strip() if head.startswith('ref: ') else head;rd.need(commit==comp['source']==O.SOURCE,'current actual CAP source unchanged');draft=json.loads(new[str(parent),'REQUEST_SOURCE_BOUND_DRAFT01.json']);rd.need(draft['status']=='DRAFT_NOT_RELEASED' and draft['final_review'] is None and draft['proofs']['full_recovery'] is None,'recovered actual source-bound draft and honest future authority');rd.need(not os.path.lexists(parent/'attempt') and not os.path.lexists(cap/'research_runs'/draft['identity']),'no new numerical attempt/claim')
 pids={intent['parent_pid'],spawn['pid']};groups={spawn['pid']}
 for pid in pids:rd.need(not os.path.lexists(Path('/proc')/str(pid)),'recorded flat process absent')
 caller=rd.read(root/'caller01.py',entry['caller_sha256']);node=next(n for n in ast.parse(caller).body if isinstance(n,ast.FunctionDef) and n.name=='raw');ns={'os':os,'FILE':R.FILE};exec(compile(ast.Module(body=[node],type_ignores=[]),'<accepted proc reader>','exec'),ns)
 for p in Path('/proc').iterdir():
  if p.name.isdigit():
   try:b=ns['raw'](p/'stat');rd.total+=len(b);rd.tick()
   except (FileNotFoundError,ProcessLookupError,PermissionError):continue
   rd.need(int(b.decode().rsplit(')',1)[1].split()[2]) not in groups,'recorded owned flat group absent')
 sample=O.W.census(root);rd.finish();result={'schema_version':1,'decision':'ACCEPTED_ACTUAL_CURRENT_SOURCE_BOUND_DRAFT_BYTE_RECOVERY','source':commit,'design_source':commit,'identity':draft['identity'],'capsule_root':str(cap),'parent_root':str(parent),'capture_sha256':O.CAPTURE,'archive_sha256':c['archive_pin']['sha256'],'flat_receipt_sha256':R.digest(rr),'actual_Root_exit_sha256':R.digest(ar),'original_outer_exit_sha256':R.digest(er),'actual_Root_exit':0,'actual_child_exit':0,'original_parent_exit':None,'cleanup_failures':[],'recorded_flat_PIDs_absent':sorted(pids),'recorded_flat_groups_absent':sorted(groups),'universal_process_history':None,'archive_regular':159,'archive_typed':175,'archive_logical_bytes':3411804,'new_payload_files':27,'new_payload_bytes':842160,'current_CAP_regular':823,'current_CAP_typed':1049,'Parent_source_bound_draft_files':11,'source_bound_draft_sha256':comp['source_bound_request']['sha256'],'tracked':360,'source_pins':359,'input_roles':29,'current_Git_logical_objects':416,'old_Git407_reused':True,'old818_body_hashes_reused_not_reread':True,'complete100_basis_sha256':'32acf31622837219bd947d64f135dce90120169fe87b4400094d7cb329b76958','Git407_basis_sha256':'02900ae11c7053a5f691ef2838fa7427b5befd86778331c19b97143e1c6c2e48','proof_regular':2,'literal_links_metadata_only':links,'new_transport_source_external_recovery':False,'future_final_request_and_release':'additive authority; must join recovered draft through actual unchanged validators before launch','sampled_currentness_only':True,'POSIX_reconstruction':False,'installed_runtime_body_recovery':False,'whole_capacity':False,'numerical_authority':False,'checks':rd.checks,'read_bytes':rd.total,'elapsed_seconds':time.monotonic()-rd.start,'final_sample':sample};R.put(H/'CURRENT_RECOVERY_READBACK01.json',result);print(json.dumps(result))
if __name__=='__main__':main()
