import ast,hashlib,json,os,shutil,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();P=F/'financial-genuine-wrapper-root-recordfix-failed-remote01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
def sig(s):return (s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns)
def read(p):
 s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4*1024**2 and p.resolve()==p,'regular canonical bounded input');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW)
 try:
  ck(sig(os.fstat(fd))==sig(s),'actual opened identity');out=[];total=0
  while True:
   b=os.read(fd,65536)
   if not b:break
   total+=len(b);ck(total<=s.st_size,'bounded extent');out.append(b)
  ck(sig(os.fstat(fd))==sig(s)==sig(p.lstat()) and total==s.st_size,'stable body identity');return b''.join(out)
 finally:os.close(fd)
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never',*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1','GIT_TERMINAL_PROMPT':'0'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'bounded local Git only');return r.stdout
raw=read(P/'SELECTED_BODIES01.json');ck(sha(raw)=='59bd4601e99418d669f84d4b9f65320bf7e0907a51cbd4a561e9a2495227781f','exact selection pin');raw_selection=raw;v=json.loads(raw);ck((json.dumps(v,sort_keys=True,indent=2)+'\n').encode()==raw,'canonical selection');H='d6859b5cabccde4e4c5af2320cb96b397dfbedd4';ck(v['remote_commit']==H,'explicit committed selection');rows=v['rows'];names=[r['path'] for r in rows];ck(names==sorted(set(names)) and len(rows)==270 and sum(r['bytes'] for r in rows)==17965145,'exact unique270 extent17965145');ck(11+2*len(rows)==551 and len(rows)<=506 and 551<=1024 and sum(r['bytes'] for r in rows)<=64*1024**2,'effective row and operation budgets');ck(git(['rev-parse','HEAD']).decode().strip()==H,'actual MainHEAD selectedcommit')
committed={}
for ent in git(['ls-tree','-r','-z',H,'--',*names]).split(b'\0'):
 if not ent:continue
 meta,path=ent.split(b'\t');mode,typ,oid=meta.decode().split();committed[path.decode()]={'git_mode':mode,'kind':typ,'git_object':oid}
ck(set(committed)==set(names),'exact committed selected tree');reply=b''.join(git(['cat-file','--batch'],(''.join(committed[n]['git_object']+'\n' for n in names[i:i+40])).encode()) for i in range(0,len(names),40));offset=0;joined=[]
for row in rows:
 n=row['path'];p=ROOT/n;meta=committed[n];ck(n.startswith('research/') and Path(n).as_posix()==n and '..' not in Path(n).parts and not any(x in ('.env','keys','apis') for x in Path(n).parts),'safe exact path');ck(type(row['bytes']) is int and 0<=row['bytes']<=4*1024**2 and meta['kind']=='blob' and meta['git_mode'] in ('100644','100755'),'regular selected mode extent');end=reply.index(b'\n',offset);oid,typ,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2
 ck(oid==meta['git_object'] and typ=='blob' and reply[offset-1:offset]==b'\n' and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+b).hexdigest()==oid,'actual Git blob body OID');ck(read(p)==b and sha(b)==row['sha256'] and len(b)==row['bytes'],'complete selected byte joins');mode=stat.S_IMODE(p.lstat().st_mode);ck(meta['git_mode']==('100755' if mode&0o111 else '100644'),'actual executable-mode Git join');joined.append(dict(row,git_mode=meta['git_mode'],git_object=oid,original_filesystem_mode=mode))
ck(offset==len(reply),'complete no trailingGitframe');selected=set(names)


SEL=P;selected_rows=joined;selected_commit=H;P=F/'financial-genuine-wrapper-root-recordfix-failed-scope-capture01-2026-10-04'
import gzip,io,tarfile,importlib.util
RP=F/'held-consumer-final-recovery-preparation04-2026-10-03';sys.path.insert(0,str(RP));sp=importlib.util.spec_from_file_location('failed_archive_r4',RP/'recovery04.py');a=importlib.util.module_from_spec(sp);sp.loader.exec_module(a)
for n,pin in {'recovery04.py':'b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','owned_io.py':'09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb','bounded_git01.py':'db4a65a450bf9930abac04ab794539ebd952b07826d7314b4aea4e989dd9240f'}.items():ck(sha(read(RP/n))==pin,'unchanged accepted primitive')
prior=F/'held-consumer-final-released-scope-capture-review01-2026-10-03/check01.py';defs=[n for n in ast.parse(read(prior)).body if isinstance(n,ast.FunctionDef) and n.name in ['decode','recode']];exec(compile(ast.Module(body=defs,type_ignores=[]),str(prior),'exec'))
capraw=read(P/'CAPTURE01.json');ck(sha(capraw)=='37c3f6b064b005398535c8b49636ef4e9190dd508d29200034c81823b699786c','actual complete failed capture');cap=json.loads(capraw);allman={};allbody={};arch=[]
for role in ['source','parent','outer']:
 mr=read(P/(role+'-manifest.json'));m=json.loads(mr);root=Path(cap['source_roots'][role]);raw=read(P/(role+'.tar.gz'));pin=cap['archives'][role];ck(sha(mr)==pin['manifest_sha256'] and sha(raw)==pin['sha256'] and len(raw)==pin['bytes'],'actual archive manifest pins '+role);ck(a.scan(root)==m,'fresh exact closed current tree '+role);bodies,frame=decode(raw,m);ck(recode(m,bodies)==raw,'whole canonical compressed reconstruction '+role)
 for r in m['members']:
  if r['kind']=='file':ck(bodies[r['path']]==a.read(root,r['path']),'every complete opaque current original body '+role)
 ck(len(m['members'])==cap['typed_members'][role] and sum(r['kind']=='file' for r in m['members'])==cap['regular_members'][role] and sum(r.get('bytes',0) for r in m['members'])==cap['logical_bytes'][role],'actual complete extent denominators '+role);allman[role]=m;allbody[role]=bodies;arch.append({'role':role,**pin,'members':len(m['members']),'regular':cap['regular_members'][role],'framing':frame})
S=Path(cap['source_roots']['source']);Par=Path(cap['source_roots']['parent']);Ext=Path(cap['source_roots']['outer']);identity=cap['identity'];H='649fb8a11089524aaef7843dffeeb90a3a55ca17';sb=allbody['source'];pb=allbody['parent'];eb=allbody['outer'];old=json.loads(read(F/'financial-genuine-wrapper-root-recordfix-capture01-2026-10-04/source-manifest.json'));new={r['path']:r for r in allman['source']['members']}
for r in old['members']:ck(new[r['path']]==r,'every original frozen986 Source member unchanged')
ck(len(new)==1011 and len(old['members'])==986,'exact Source25 typed appendages');source_delta=[r['path'] for r in allman['source']['members'] if r['path'] not in {x['path'] for x in old['members']}]
ck(git(['-C',str(S),'rev-parse','HEAD']).decode().strip()==H,'actual frozen SourceHEAD');tree=git(['-C',str(S),'ls-tree','-r','-z',H]);entries=[]
for item in tree.split(b'\0'):
 if item:meta,n=item.split(b'\t');mode,kind,oid=meta.decode().split();entries.append((n.decode(),mode,kind,oid))
ck(len(entries)==325,'complete325 tracked Source');reply=b''.join(git(['-C',str(S),'cat-file','--batch'],(''.join(r[3]+'\n' for r in entries[i:i+40])).encode()) for i in range(0,len(entries),40));offset=0
for name,mode,kind,oid in entries:
 end=reply.index(b'\n',offset);actualoid,actualkind,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2;ck(kind==actualkind=='blob' and actualoid==oid and b==sb[name] and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+b).hexdigest()==oid and mode==('100755' if new[name]['mode']&0o111 else '100644'),'every committed Source body mode/OID/current archive join')
ck(offset==len(reply),'complete boundedGit framing');claimpath='research_runs/'+identity+'/claim.json';failedpath='research_runs/'+identity+'/failed.json';ck(sha(sb[claimpath])==cap['claim_sha256']=='4c543d71fad5255be61087eaa3619d9e88cbbdc12fa1398bd7fa7fe6fb75c128' and sha(sb[failedpath])==cap['failed_sha256']=='35158c0ecebfe4dc75203ba87d5372f2f85643c0b5f828a99e17aa28fe79c450','actual genuine claim and permanentFAILED exact bodies');claim=json.loads(sb[claimpath]);failed=json.loads(sb[failedpath]);ck(claim['source']==claim['design_source']==H and claim['effective_attempt_budget']==18 and failed['claim_sha256']==sha(sb[claimpath]) and failed['status']=='failed' and failed['output_sha256']=={} and failed['reason']=='ValueError: repeat run prohibited; use a separately justified registration','actual failed accounting no outputs');ck(len([n for n in sb if n.startswith('research_runs/') and n.endswith('/claim.json')])==1,'actual one spent genuine claim')
for n,pin in claim['experiment']['source_files'].items():ck(sha(sb[n])==pin,'all actual claim source pins')
ck(len(claim['experiment']['source_files'])==324 and len(claim['inputs'])==8,'exact324sources eight actualroles')
for role,row in claim['inputs'].items():ck(sha(sb[row['path']])==row['sha256'],'genuine current input opaque pin '+role)
closure=json.loads(sb['fixture_inputs/financial_wrapper_recordfix01/source_closure.json']);ck(len(closure['installed'])==194 and sum(n.startswith('tradingagents/') for n in closure['installed'])==149,'actual194implementation149package closure')
for n,pin in closure['installed'].items():ck(sha(sb[n])==pin,'all194 method bodies unchanged')
base='research_artifacts/onchain-paper-replication-2026-09-24/runs/'+identity+'/';j=lambda n:json.loads(sb[base+n]);guard=j('guard/final.json');owner=j('owner.json');observer=j('observer.json');outer=json.loads(eb['ACTUAL_TERMINAL01.json']);pt=json.loads(pb['attempt/parent-terminal.json']);cleanup=json.loads(pb['attempt/owned-tree-cleanup.json']);captureterminal=json.loads(read(P/'ACTUAL_TERMINAL01.json'));captureintent=json.loads(read(P/'ACTUAL_INTENT01.json'))
ck(guard['child_exit_code']==1 and guard['cleanup_verified'] is True and guard['cleanup_stop_returncode']==0 and guard['peak_sampled_memory_current_bytes']==325218304,'original failed guard cleanup and sampled memory');ck(outer['actual_exit']==1 and outer['actual_session']==58508 and outer['actual_start_tool']=='b185ed' and outer['actual_completion_tool']=='ea4290' and outer['actual_guard']['memory_peak_bytes'] is None,'actual Root native exit and preserved null alias');ck(pt['actual_parent_exit'] is None and pt['actual_child_exit']==1 and pt['cleanup']['original_parent_exit']==1 and pt['outcome_semantics_accepted'] is False,'original Parent self-null preserved with additive child/root1');ck(b'325218304' in eb['MEMORY_FIELD_QUALIFICATION02.json'],'actual sampled memory qualification retained');ck(observer['financial_completion'] is False and observer['status']=='failed' and observer['terminal_sha256']==sha(sb[failedpath]) and observer['owner_sha256']==sha(sb[base+'owner.json']),'genuine observer/owner/failed chain')
for n,pin in observer['evidence_sha256'].items():ck(sha(sb[base+n])==pin,'original observer evidence exactbody')
ck(j('unsealed-journals.json')==[] and all(c['status']=='unavailable' for c in j('postmortem-cells.json')),'original unavailable dependent cells and empty journals');ck(b'repeat run prohibited' in sb[base+'guard/child.log'],'original actual worker fatal trace retained')
absent_outputs=['wrapper-native-cpu-readback.json','wrapper-summary.json','artifact-index.json','cell-ledger.json','fit-checkpoint']
# Complete captured namespace proves all registered output leaves absent; no checkpoint file exists anywhere in attempted output namespace.
for name in claim['experiment']['outputs']:ck(not any(n.startswith('research_runs/'+identity+'/outputs/') and n.endswith('/'+name) for n in sb),'registered output absent '+name)
ck(not any(n.startswith(base) and any(w in n.lower() for w in ['checkpoint','wrapper-summary','wrapper-native','fit-summary','fit-evidence']) for n in sb),'no wrapper native/fit/checkpoint bodies')
ck(cleanup['remaining_original_identities']==[] and pt['cleanup']['cgroup_absent'] and pt['cleanup']['joined_unit_stopped'],'original Parent drainage evidence');pids={outer['actual_parent_pid'],owner['supervisor_pid'],owner['monitor_pid'],guard['monitor_pid'],j('guard/child_exit.json')['workload_pid'],j('guard/cpu_ready.json')['pid'],captureintent['pid']};pids.update(int(n) for n in guard['cpu_thread_readback']);pids.update(r['pid'] for r in cleanup['owned_pid_start_records']);groups={r['pgrp'] for r in cleanup['owned_pid_start_records']}
for op,row in pt['cleanup']['actual_control_operations'].items():ck(row['exit_code']==0 and pb['attempt/'+op+'/stdout']==row['stdout'].encode() and pb['attempt/'+op+'/stderr']==row['stderr'].encode(),'actual controller operation and rawstreams '+op);pids.add(row['pid'])
for pid in sorted(pids):ck(not Path('/proc',str(pid)).exists(),'recorded original PID or TID currently absent')
for group in sorted(groups):
 try:os.killpg(group,0)
 except ProcessLookupError:pass
 else:raise AssertionError('recorded group remains')
ck(not Path(guard['cgroup']).exists(),'actual exact cgroup absent');ck(captureterminal['actual_exit']==0 and captureterminal['actual_session']==75520 and captureterminal['actual_start_tool']=='119d83' and captureterminal['actual_completion_tool']=='e28242' and captureterminal['capture_sha256']==sha(capraw),'actual original capture tool exit receipt');ck(captureterminal['actual_parent_pid']==captureintent['pid']==334390 and captureterminal['actual_parent_start_ticks']==captureintent['start_ticks']=='14967492','actual recorded capture parent identity');ck(len(cap['observed_free_bytes'])==6 and min(cap['observed_free_bytes'])>=10*1024**3,'all six actual recorded diskfloor samples')
for role,manifest in allman.items():ck(a.scan(Path(cap['source_roots'][role]))==manifest,'final stable current full tree '+role)
ck(sha(read(P/'capture01.py'))==json.loads(read(P/'CAPTURE_SOURCE01.json'))['script_sha256'],'actual capture source provenance');ck(sum(cap['typed_members'].values())==1049 and sum(cap['regular_members'].values())==763,'full1049typed763body scope');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numerical imports')
selected_by={r['path']:r for r in selected_rows};ck(len({r['git_object'] for r in selected_rows})==226,'exact226 immutable selected objects');covered=dict(selected_by)
for role,bodymap in allbody.items():
 root=Path(cap['source_roots'][role])
 for name,b in bodymap.items():
  actualpath=root/name
  if actualpath.is_relative_to(ROOT):covered[actualpath.relative_to(ROOT).as_posix()]={'sha256':sha(b),'bytes':len(b)}
complete_dirs=['financial-genuine-wrapper-recordfix-first-failure-review01-2026-10-04','financial-genuine-wrapper-recordfix-first-failure-capture-review01-2026-10-04','financial-genuine-wrapper-claimed-run-correction-preparation01-2026-10-04','financial-genuine-wrapper-claimed-run-correction-review01-2026-10-04','financial-genuine-wrapper-recordfix-final-union-actual-recovery-review01-2026-10-04']
closure=[];missing=[]
for dirname in complete_dirs:
 d=F/dirname
 for p in d.rglob('*'):
  st=p.lstat()
  if stat.S_ISREG(st.st_mode):ck(p.relative_to(ROOT).as_posix() in selected_by,'full declared selected directory member '+str(p.relative_to(d)))
  elif stat.S_ISLNK(st.st_mode):raise AssertionError('unexpected link in directly selected review')
  else:ck(stat.S_ISDIR(st.st_mode),'declared directory only')
 for p in sorted(d.glob('MANIFEST*.json')):
  doc=json.loads(read(p))
  for row in doc.get('members',doc.get('entries',[])):
   target=p.parent/row['path'];mode=row.get('mode');kind=row.get('kind',row.get('type'));st=target.lstat();ck(mode==stat.S_IMODE(st.st_mode),'every frozen review original mode')
   if kind=='file':
    relative=target.relative_to(ROOT).as_posix();actual=covered.get(relative)
    if actual is None:missing.append({'manifest':str(p),'member':row['path']});continue
    ck(stat.S_ISREG(st.st_mode) and actual['sha256']==row['sha256']==sha(read(target)) and actual['bytes']==row.get('bytes',row.get('size')),'every relevant selected review witness body exact');closure.append(relative)
   elif kind in ('directory','dir'):ck(stat.S_ISDIR(st.st_mode),'review typed directory')
   else:raise AssertionError('unexpected declared witness kind '+str(kind))
(O/'FLAT_MANIFEST_CLOSURE03.json').write_text(json.dumps({'missing':missing,'joined_count':len(closure)},sort_keys=True,indent=2)+'\n');ck(not missing,'complete relevant original review-body closure')
ck(sha(read(SEL/'recover01.py'))=='0b397ccd0a014f60a414ce79d67dfd53c58a0fb61ca616a6576cc43da4bbf0aa','unchanged accepted bounded firstfatal transport helper')
ck(not os.path.lexists(SEL/'FAILED01.json'),'no failed actual transport record')
legacy=F/'financial-genuine-wrapper-root-recordfix-capture01-2026-10-04'
for n in ['ACTUAL_TERMINAL02.json','request.json','source-authentication.json','source-manifest.json','source.tar.gz','terminal.json']:ck((legacy/n).relative_to(ROOT).as_posix() in selected_by,'six required legacy supplement present')
ck(git(['rev-parse','HEAD']).decode().strip()==selected_commit,'Main immutable selected commit after checks');free=shutil.disk_usage(SEL).free;ck(free>=10*1024**3,'actual observed current disk floor')
rr=read(SEL/'REMOTE_RECOVERY01.json');ck(sha(rr)=='61ce415a7b951e0922350c2c16e95b5b6d51ce4abefc4c45404e75f82ab117b2','actual original remote receipt');receipt=json.loads(rr);rt=read(SEL/'ACTUAL_TERMINAL01.json');terminal=json.loads(rt);intent=json.loads(read(SEL/'INTENT01.json'));qualraw=read(SEL/'FAILED_SCOPE_QUALIFICATION02.json');qualification=json.loads(qualraw);ops=receipt['operations'];repo=Path(receipt['fresh_git_root']);ck(repo==SEL/'fresh-recordfix-source325-01.git','actual exact fresh failed remote repository');ck(receipt['remote_commit']==selected_commit and receipt['selection_sha256']==sha(raw_selection) and receipt['selected_count']==270 and receipt['selected_logical_bytes']==17965145,'actual selected complete failedscope receipt joins');ck(receipt['status']=='fresh-actual-remote-recordfix-source325-recovered' and receipt['genuine_run_or_native_started'] is False,'inherited original archival-only labels preserved')
ck(terminal['actual_exit']==0 and terminal['actual_tool_session']==71644 and terminal['actual_start_tool']=='71c947' and terminal['actual_completion_tool']=='2ceb83' and terminal['actual_remote_receipt_sha256']==sha(rr),'actual Root original tool completion');ck(intent['accepted_selection_manifest']==sha(read(O/'MANIFEST01.json'))=='9b38c943cf983dc7383ded3ae125a85412a027bfc3039729fb00dbbe9aae7988' and intent['selection_sha256']==sha(raw_selection),'actual original intent independent selection pin');ck(intent['actual_root_pid']==terminal['actual_root_pid']==348990 and intent['actual_start_ticks']==terminal['actual_start_ticks']==15080261,'actual original parent recorded ticks');stdout=read(SEL/'ACTUAL_REMOTE01.out');ck(json.loads(stdout)=={k:receipt[k] for k in json.loads(stdout)} and read(SEL/'ACTUAL_REMOTE01.err')==b'','actual original stdout/empty stderr joins')
ck(qualification['original_receipt_sha256']==sha(rr) and qualification['selection_sha256']==sha(raw_selection) and qualification['selected_commit']==selected_commit and qualification['actual_failed_capture_sha256']==sha(capraw) and qualification['actual_claim_sha256']==cap['claim_sha256'] and qualification['actual_failed_sha256']==cap['failed_sha256'],'separate authentic actual failed-scope qualification body pins');ck(qualification['original_status_and_qualification_unchanged'] is True and qualification['new_three_role_flat_recovery'] is False,'original limited qualification retained')
ck([r['operation'] for r in ops]==['remote','ls-remote','init','remote','config','config','fetch','rev-parse','ls-tree','fetch']+['cat-file']*540+['ls-remote'],'all551 finite actual operation ordering');absent=set()
for pid in [intent['actual_root_pid'],intent['actual_pgid']]+[r['pid'] for r in ops]:
 ck(not Path('/proc',str(pid)).exists(),'actual original recorded process absent')
 try:os.killpg(pid,0)
 except ProcessLookupError:pass
 else:raise AssertionError('actual original recorded group remains')
 absent.add(pid)
for r in ops:ck(r['exit']==0 and r['cleanup_failures']==[] and 0<=r['stdout_bytes']<=4*1024**2 and 0<=r['stderr_bytes']<=65536,'actual operation closed within streambounds')
line=(selected_commit+'\t'+receipt['branch']+'\n').encode();ck(all(r['stdout_sha256']==sha(line) and r['stdout_bytes']==len(line) for r in (ops[1],ops[-1])),'actual original first/final remote head output joins');selected_names=[r['path'] for r in selected_rows];ft=git(['--git-dir='+str(repo),'ls-tree','-r','-z',selected_commit,'--',*selected_names]);ck(ft==git(['ls-tree','-r','-z',selected_commit,'--',*selected_names]) and sha(ft)==ops[8]['stdout_sha256'] and len(ft)==ops[8]['stdout_bytes'],'actual recovered immutable selected tree and original raw operation output');ck(git(['--git-dir='+str(repo),'cat-file','commit',selected_commit])==git(['cat-file','commit',selected_commit]),'actual fetched immutable commit body')
ck(receipt['selected_blobs']==[{k:r[k] for k in ('path','bytes','sha256','git_mode','git_object')} for r in selected_rows],'all270 exact original/fetched receipt rows');reply=b''.join(git(['--git-dir='+str(repo),'cat-file','--batch'],(''.join(r['git_object']+'\n' for r in selected_rows[i:i+40])).encode()) for i in range(0,len(selected_rows),40));offset=0;actualnames=set()
for p in (SEL/'selected').rglob('*'):
 st=p.lstat()
 if stat.S_ISREG(st.st_mode):actualnames.add(p.relative_to(SEL/'selected').as_posix())
 else:ck(stat.S_ISDIR(st.st_mode),'no saved link or foreignkind')
ck(actualnames==set(selected_names),'actual full saved namespace exactly270bodies')
for i,row in enumerate(selected_rows):
 end=reply.index(b'\n',offset);oid,kind,size=reply[offset:end].decode().split();size=int(size);body=reply[end+1:end+1+size];offset=end+size+2;p=SEL/'selected'/row['path'];ck(oid==row['git_object'] and kind=='blob' and size==row['bytes'] and sha(body)==row['sha256'] and body==read(p)==read(ROOT/row['path']),'every actual fetched saved original body');ck(stat.S_IMODE(p.lstat().st_mode)==0o600,'actual saved0600 body');sizeop,bodyop=ops[10+2*i:12+2*i];sr=(str(size)+'\n').encode();ck(sizeop['stdout_sha256']==sha(sr) and sizeop['stdout_bytes']==len(sr) and bodyop['stdout_sha256']==sha(body) and bodyop['stdout_bytes']==len(body),'actual original size and body output digests')
ck(offset==len(reply),'complete fetchedGit batch consumed');ck(receipt['free_bytes']>=10*1024**3 and terminal['actual_operations']==551 and terminal['actual_child_cleanup_failures']==0,'actual closed terminal operation floor qualification');ck(sha(read(O/'MANIFEST01.json'))=='9b38c943cf983dc7383ded3ae125a85412a027bfc3039729fb00dbbe9aae7988','original selection manifest immutable')
FP=F/'financial-genuine-wrapper-root-recordfix-failed-flat01-2026-10-04';D=F/'financial-genuine-wrapper-recordfix-failed-scope-flat-20261004-01';frraw=read(D/'RECOVERY01.json');ck(sha(frraw)=='d4a081d08a49cedc0c7c734e636aa4c0927ed9682c50bcece10c17798373476b','actual original three-role flat receipt');fr=json.loads(frraw);ck(fr['status']=='COMPLETE_ACTUAL_FAILED_SCOPE_FLAT_BYTES' and fr['capture_sha256']==sha(capraw) and fr['remote_receipt_sha256']==sha(rr),'actual full failed capture/remote/flat chain')
ck({p.name for p in D.iterdir()}=={'request.json','INTENT01.json','RECOVERY01.json','flat-source','flat-parent','flat-outer'},'complete output namespace without extras');ck(stat.S_IMODE(D.lstat().st_mode)==0o700,'actual private output root');inodes=set();role_maps={};metadata_pins={};recovered={};private_count=0
for role in ('source','parent','outer'):
 dest=D/('flat-'+role);result=fr['actual'][role];mr=read(dest/result['metadata_file']);meta=json.loads(mr);ck(sha(mr)==result['metadata_sha256'] and meta['manifest']==allman[role] and meta['archive']==cap['archives'][role],'each full actual role mode/name metadata chain');ck(stat.S_IMODE(dest.lstat().st_mode)==0o700,'each actual private role directory');mapping=meta['flat_members'];names={r['path'] for r in allman[role]['members'] if r['kind']=='file'};ck(set(mapping)==names and len(set(mapping.values()))==len(names)==result['regular_bodies'],'each role exact one-to-one complete regular mapping');ck({p.name for p in dest.iterdir()}==set(mapping.values())|{result['metadata_file']},'each exact role privatefile namespace');bodies={}
 for name,leaf in list(mapping.items())+[('__role_metadata__',result['metadata_file'])]:
  p=dest/leaf;s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and stat.S_IMODE(s.st_mode)==0o600 and (s.st_dev,s.st_ino) not in inodes,'every distinct singlelink0600 private body');inodes.add((s.st_dev,s.st_ino));private_count+=1;body=read(p)
  if name!='__role_metadata__':ck(body==allbody[role][name],'every actual recovered body equals complete original archive/current body');bodies[name]=body
 ck(recode(allman[role],bodies)==read(P/(role+'.tar.gz')),'every full archive reconstructed from actual recovered bodies '+role);ck(all(result[k] is False for k in ['instantiated_posix_tree','outside_stores_recovered','recovered_tree_git_join','research_authority','runtime_package_bodies_recovered']),'original limited R4 fields retained '+role);role_maps[role]=mapping;metadata_pins[role]=sha(mr);recovered[role]=bodies
ck(private_count==len(inodes)==766 and sum(len(v) for v in recovered.values())==763,'full766distinctprivatefiles all763ordinarybodies')
# Validate original installed helper semantics against actual recovered metadata, without executing run/restore.
AP=F/'financial-genuine-wrapper-recordfix-failed-scope-recovery-preparation01-2026-10-04'
for name in ['restore01.py','recovery04.py','owned_io.py','bounded_git01.py','CAPTURE_PINS01.json']:ck(read(FP/name)==read(AP/name),'actual unchanged installed helper '+name)
sys.path.insert(0,str(FP));sp=importlib.util.spec_from_file_location('actual_failed_outcome_joins',FP/'restore01.py');adapter=importlib.util.module_from_spec(sp);sp.loader.exec_module(adapter);ck(adapter.outcome_joins(D,fr['actual'],allman,cap)==fr['outcome_metadata'],'actual full recovered permanent-failure semantic joins')
proposal=json.loads(read(FP/'REQUEST_PROPOSAL02.json'));fqraw=read(FP/'REQUEST_FINAL03.json');fq=json.loads(fqraw);ck(sha(fqraw)=='186d77e253cbc3ec865a728a384767b2cda95c538e1bf6215d001c8a5ede896b' and read(D/'request.json')==fqraw,'actual exact final request matches output');ck({k:v for k,v in fq.items() if k!='release'}=={k:v for k,v in proposal.items() if k!='release'} and proposal['release'] is None,'only genuine original release reference bound');ck(adapter.contract(fq)=='50d7900b531cd181d9b06504691d7da962d3fcc0646ee028f51713f747add8c9','actual exact original release-excluded contract');release=adapter.ref(fq['release']);ck(sha(release)=='698ff85d825e605a17fef4e33231c5bc1449cb341a28ed41134a3e4b923eba23' and json.loads(release)['helper_sha256']==sha(read(FP/'restore01.py')),'genuine six-field release body unchanged');ck(sha(adapter.ref(fq['review']))=='a5bb9cb9d3e2f5ba134c831c070db53d854d39632f7e00aec90b5b9bb4f4f2ba','actual source review reference authentic')
ft_raw=read(FP/'ACTUAL_TERMINAL03.json');ft=json.loads(ft_raw);fi=json.loads(read(FP/'ACTUAL_INTENT03.json'));oi=json.loads(read(D/'INTENT01.json'));ck(ft['actual_exit']==0 and ft['actual_session']==34175 and ft['actual_start_tool']=='2539c6' and ft['actual_completion_tool']=='876888' and ft['actual_recovery_sha256']==sha(frraw),'actual original flat tool exit');ck(fi['actual_root_pid']==ft['actual_root_pid']==oi['pid']==360813 and fi['actual_start_ticks']==ft['actual_start_ticks']==15167022,'actual original observed flat parent ticks');ck(fi['final_request_sha256']==ft['final_request_sha256']==sha(fqraw) and fi['accepted_release_sha256']==sha(release) and fi['actual_remote_receipt_sha256']==sha(rr),'actual original flat intent chain')
flat_absent=[]
for pid in (fi['actual_root_pid'],fi['actual_pgid']):
 ck(not Path('/proc',str(pid)).exists(),'actual original flat parentPID absence')
 try:os.killpg(pid,0)
 except ProcessLookupError:pass
 else:raise AssertionError('actual flat original group remains')
 flat_absent.append(pid)
fstdout=read(FP/'ACTUAL_FLAT03.out');ck(json.loads(fstdout)==fr['actual'] and read(FP/'ACTUAL_FLAT03.err')==b'','actual original flat stdout and empty stderr');ck(ft['actual_private_flat_files']==766 and ft['actual_flat_regular_bodies']==763 and ft['actual_original_role_metadata_files']==3 and ft['actual_original_typed_members']==1049,'actual terminal denominations independently matched');ck(len(fr['observed_free_bytes'])==9 and fr['observed_free_bytes']==ft['actual_observed_free_bytes'] and min(fr['observed_free_bytes'])>=10*1024**3,'allnine actual floor observations');ck(fr['research_authority'] is False and fr['same_identity_retry'] is False and fr['runtime_or_empirical_recovery'] is False and fr['posix_instantiation'] is False,'original false archival authority flags unchanged')
ck(sha(recovered['source'][claimpath])==cap['claim_sha256'] and sha(recovered['source'][failedpath])==cap['failed_sha256'],'actual recovered genuine permanent claimFAILED bytes');ck(recovered['parent']['attempt/parent-terminal.json']==pb['attempt/parent-terminal.json'] and recovered['outer']['ACTUAL_TERMINAL01.json']==eb['ACTUAL_TERMINAL01.json'] and recovered['outer']['MEMORY_FIELD_QUALIFICATION02.json']==eb['MEMORY_FIELD_QUALIFICATION02.json'],'actual recovered null/Root1/memory qualifier original bytes');ck(fr['outcome_metadata']['genuine_failed_spent_claims']==1 and fr['outcome_metadata']['budget']==18 and fr['outcome_metadata']['planned_checkpoint_present'] is False,'actual recovered accounting no refund/19budget/fit')
for role,m in allman.items():ck(a.scan(Path(cap['source_roots'][role]))==m,'all current originals still fully stable '+role)
ck(sha(read(O/'MANIFEST02.json'))=='5debe30399f70546180e10854cb3291cd8b87271a654378abbe08c249949e52f','original remote manifest unchanged');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numerical imports')
x={'schema_version':1,'decision':'COMPLETE_FAILED_SCOPE_BYTE_UNION_ACCEPTED','checks':len(checks),'capture_sha256':sha(capraw),'remote_receipt_sha256':sha(rr),'flat_receipt_sha256':sha(frraw),'flat_request_sha256':sha(fqraw),'flat_terminal_sha256':sha(ft_raw),'flat_stdout_sha256':sha(fstdout),'flat_stderr_sha256':sha(read(FP/'ACTUAL_FLAT03.err')),'role_metadata_sha256':metadata_pins,'roles':{r:{'typed':len(allman[r]['members']),'regular':len(recovered[r])} for r in recovered},'full_typed_members':1049,'regular_bodies':763,'distinct_private_files_including_metadata':766,'source_commit':H,'tracked':325,'claimed_source_pins':324,'implementation':194,'package':149,'input_roles':8,'original_source986_unchanged':True,'failed_source_appendages':25,'genuine_failed_spent_claims':1,'numerical_ceiling':18,'claim_sha256':cap['claim_sha256'],'failed_sha256':cap['failed_sha256'],'original_parent_self_exit':None,'actual_root_native_exit':1,'peak_sampled_memory_current_bytes':325218304,'root_peak_alias':None,'kernel_peak_or_capacity':False,'original_flat_pid_and_group_currently_absent':flat_absent,'remote_recorded_processes_rechecked':551,'same_identity_replay_authority':False,'installed_runtime_or_paper_empirical_recovery':False,'posix_instantiation':False,'numerical_release':False,'qualification':'Complete original failed Source/Parent/Root archival union, not a model/fit checkpoint or capacity claim. Original receipts and null fields remain unchanged; recorded process absence is current evidence, not complete historical ancestry.'};(O/'FLAT_READBACK03.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');print(json.dumps(x,sort_keys=True))
