from pathlib import Path
import json,hashlib,os,stat,shutil
P=Path(__file__).absolute().parent;A=P.parent/'financial-wrapper-compatibility-operational-delta-flat-successor03-2026-10-04'
def sha(b):return hashlib.sha256(b).hexdigest()
def put(n,v):(P/n).write_text(json.dumps(v,sort_keys=True,indent=2)+'\n')
a=json.loads((P/'READBACK01.json').read_bytes());b=json.loads((P/'READBACK02.json').read_bytes());prior=json.loads((P/'PRIOR_REVIEW_AUTHENTICATION01.json').read_bytes())
for name in ('SEAL01.out','SEAL01.err'):shutil.copyfile(A/name,P/('AUTHOR_'+name))
put('MACHINE01.json',{'schema_version':1,'decision':'ACCEPTED_NARROW_SOURCE_ONLY_VERIFIED_COHORT_CORRECTION','source_sha256':sha((P/'restore01.py').read_bytes()),'author_manifest_sha256':sha((A/'MANIFEST01.json').read_bytes()),'author_typed_members':len(json.loads((A/'MANIFEST01.json').read_bytes())['members']),'prior_withheld_review_manifest_sha256':prior['manifest_sha256'],'prior_review_members_authenticated':prior['members_authenticated'],'independent_checks':a['checks']+b['checks'],'source_inverse_complete':True,'changed_original_functions':['authenticate_selected','load_capture','load_failed_capture','run','verify_flat'],'added_class':'VerifiedCohort','five_independent_real_red_refusal_pairs':True,'actual_local_canonical_archives':2,'actual_local_body_count':64,'actual_local_metadata_count':2,'partial_second_fatal_first_output_retained':True,'watch04_independent_review_manifest':'7a94ef046588cb9a10a978d63865302e0b12a25e60db98190aea9927ecc59f47','actual_remote_entry':False,'actual_successful_public_run':False,'actual_release':None,'actual_recovery':None,'native_or_numerical':False,'scope_qualification':b['sidecar_scope_qualification'],'limits_unchanged':{'file':4194304,'whole_logical':67108864,'whole_allocated':100663296,'floor':10737418240,'run_seconds':180,'run_samples':64,'members':32768,'depth':32},'no_atomic_ABA_or_writer_exclusion_claim':True})
(P/'REPORT01.md').write_text('''# Independent successor03 flat source review

ACCEPTED_NARROW_SOURCE_ONLY for6d7688080efb716b7a79d1291b4f27e62e0315e5d7a8153b2890d1f9fab35214. All author726 typed members and the complete375-member prior independently withheld review were authenticated without changing any originals. Source02 and every earlier witness remain WITHHELD historical evidence. The literal/AST inverse reproduces exact4832 source02: five original functions change, one VerifiedCohort class is added, and every other function remains AST-identical. Fixed15selected bodies507946B, both capture contexts, original mode mapping and all resource/data/method constants are unchanged. R4a054/IO09d1/Gitdb4a remain exact; watch04bdeaca has this agent's separate independent source review7a94ef04.

Five independent real owned oldRED/newREFUSAL pairs reproduce earlier-byte corruption, private-mode change, foreign member addition, metadata corruption and mutation of an earlier scope during the last real read close in the second scope. Every close occurred on a real descriptor; no read-return bytes or successful external receipt were fabricated. New03 refuses all five while old02 returned normally. Both genuine frozen canonical archives restore locally with all64 opaque bodies and two metadata files. Original failedRoot43 including root projects exactly to42 descendants31files; operational scope41/33 remains intact. R4 full canonical framing and recompression run unchanged.

Independent controls additionally refuse prerequisite bytes/modes, receiver private mode, selected ancestor mode, extra member and mutation during real iterator close. A mutation after the original final boundary callback is refused. The shared cohort covers the earlier scope when verifying the later scope. Actual third-write MemoryError during the second restoration survives a later actual-close SystemExit, all descriptors close, partial second output stays retained and the completed first output remains byte/mode-identical. No fresh full public run/main/entry or accepted remote receipt was constructed or executed.

VerifiedCohort brackets each actual body read with full signatures before and after original read/cleanup. All tree enumeration/iterator cleanup finishes before the final signature pass. Expected selected/flat namespaces retain full directory signatures and private modes; the receiver root alone retains canonical owner/device/inode/mode rather than directory times because its own intent/output/receipt publications are deliberate. This does not relax selected or flat ancestor/member fingerprints. Both output populations, their metadata and actual remote/selection/prerequisite byte proofs share the terminal rejoin. No hashing is replaced by a resource-only census.

Precise scope qualification: the final cohort check executes after the sidecar's last boundary, but FLAT_POSTWRITE_OBSERVATION01 itself is not read into the byte cohort. The author's phrase “receipt/sidecar reads” overstates that one auxiliary body. The actual remote receipt, selection, selected capture/archive/metadata prerequisites, restored bodies and metadata, and FLAT_RECOVERY01 JSON are covered. The sidecar and actual Root tool terminal require their separate genuine outcome authentication. This review does not claim sidecar byte currentness or actual Root success.

All limits remain4MiB per body,64MiB logical/96MiB allocated whole owned tree,10GiB floor,180seconds/64run observations,32768members/depth32. Cohort checks are finite sampled signature/membership checks tied to actual read bytes, not continuous atomicity, writer exclusion or same-signature ABA immunity. Nothing here proves a kernel quota, full-population numerical capacity, runtime package restoration, scientific reproduction, policy admission or financial performance. Root alone must install the exact reviewed helper closure, authenticate genuine selected external receipt/commit, execute one fresh recovery namespace and obtain complete actual outcome review. No Main/CAP/Parent/gate/claim mutation, network, scientific import or numerical execution occurred.
''')
rows=[]
def walk(p,rel=''):
 for q in sorted(p.iterdir(),key=lambda q:q.name):
  n=q.name if not rel else rel+'/'+q.name
  if n=='MANIFEST01.json':continue
  s=q.lstat();r={'path':n,'mode':stat.S_IMODE(s.st_mode)}
  if stat.S_ISLNK(s.st_mode):r.update(kind='symlink',target=os.readlink(q));rows.append(r)
  elif stat.S_ISDIR(s.st_mode):r.update(kind='directory');rows.append(r);walk(q,n)
  else:r.update(kind='file',bytes=s.st_size,sha256=sha(q.read_bytes()));rows.append(r)
walk(P);rows.sort(key=lambda r:r['path']);put('MANIFEST01.json',{'schema_version':1,'scope':'complete independent review and all raw controls; excludes only self seal','members':rows,'typed_members':len(rows),'regular_files':sum(r['kind']=='file' for r in rows),'regular_bytes':sum(r.get('bytes',0) for r in rows)})
print(json.dumps({n:sha((P/n).read_bytes()) for n in ['MANIFEST01.json','MACHINE01.json','REPORT01.md','READBACK01.json','READBACK02.json']}));print('checks',a['checks']+b['checks'],'members',len(rows))
