from pathlib import Path
import json,hashlib,collections
ROOT=Path.cwd();R=Path(__file__).resolve().parent;F=R.parent;E=F/'real-data-pilot-full27-entry01-2026-10-09';O=F/'real-data-pilot-full26-entry01-2026-10-09';j=lambda p:json.loads(p.read_bytes());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();ev={}
def load(p):ev[str(p.relative_to(ROOT))]=h(p);return j(p)
a=load(E/'CUMULATIVE_ALLOCATION_PROPOSED98_01.json');e=load(E/'EXTENSION_PROPOSED98_01.json');oa=load(O/'CUMULATIVE_ALLOCATION_PROPOSED97_01.json');oe=load(O/'EXTENSION_PROPOSED97_02.json');pr=load(F/'mcm-batched-full26-allocation-review01-2026-10-09/EXTENSION97_REVIEW02.json');assert pr['decision']=='accepted' and pr['extension_sha256']==h(O/'EXTENSION_PROPOSED97_02.json')
assert e['allocation']=={'path':str((E/'CUMULATIVE_ALLOCATION_PROPOSED98_01.json').relative_to(ROOT)),'sha256':h(E/'CUMULATIVE_ALLOCATION_PROPOSED98_01.json')}
assert e['claims']==a['closed_claims'] and e['claims'][:-1]==oe['claims']==oa['closed_claims'] and len(e['claims'])==49 and len({r['experiment'] for r in e['claims']})==49
n=e['claims'][-1];assert n['experiment']=='eth-paper-real-data-end-to-end-resource-20261009-26' and n['terminal_status']=='failed'
c=load(ROOT/'research_runs'/n['experiment']/'claim.json');f=load(ROOT/'research_runs'/n['experiment']/'failed.json');assert ev[str(Path('research_runs')/n['experiment']/'claim.json')]==n['claim_sha256'] and ev[str(Path('research_runs')/n['experiment']/'failed.json')]==n['terminal_sha256'];assert f['claim_sha256']==n['claim_sha256'] and f['status']=='failed' and f['experiment_id']==n['experiment'] and c['effective_attempt_budget']==97
assert {k for k in a if a[k]!=oa[k]}=={'closed_claims','consumed_before','equation','identities','prior_adopted_cumulative_ceiling','prior_reviewed_reserved_ceiling','proposed_cumulative_ceiling','qualification','question'}
assert a['base_family']==e['base_family']==oe['base_family']==c['family'] and a['base_family']['attempt_budget']==51 and a['base_family']['prior_attempts']==17
assert e['consumed_before']==a['consumed_before']==49+17==66 and e['cumulative_ceiling']==a['proposed_cumulative_ceiling']==98
assert sum(a['unchanged_pending_allocation'].values())==28 and len(a['preserved_reserved_preclaim_allowances'])==3 and sum(a['new_fixed_allocation'].values())==1 and 66+28+3+1==98
assert a['refunds']==a['category_transfers']==a['historical_claims_reopened']==a['new_financial_fits']==0 and a['maximum_unique_financial_fits_unchanged']==1420
assert a['prior_adopted_cumulative_ceiling']==a['prior_reviewed_reserved_ceiling']==97
name='eth-paper-real-data-end-to-end-resource-20261009-27';assert a['identities']==[name] and e['initial_experiment']==name and not (ROOT/'research_runs'/name).exists() and not (ROOT/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/name).exists()
outcome=load(F/'real-data-pilot-full26-outcome-review01-2026-10-09/OUTCOME_REVIEW01.json');closure=load(F/'real-data-pilot-full26-outcome-review01-2026-10-09/ROOT_REVIEW01.json');assert outcome['accounting']['closed_total']==66 and outcome['accounting']['complete_total']==33 and outcome['accounting']['failed_total']==33 and outcome['claim_sha256']==n['claim_sha256'] and outcome['failed_sha256']==n['terminal_sha256'];assert closure['decision']=='accepted_qualified_root_closure'
poll=load(F/'pilot-batched-authority-poll-review01-2026-10-09/SOURCE_REVIEW01.json');eager=load(F/'pilot-preparation-eager-sweep-removal-review01-2026-10-09/SOURCE_REVIEW01.json');assert poll['decision']==eager['decision']=='accepted_source_only'
installed={}
for module,pin in poll['selected'].items():
 p=ROOT/'tradingagents/research/onchain_replication'/module;assert h(p)==pin['candidate_sha256'];installed[str(p.relative_to(ROOT))]=h(p)
p=ROOT/'tradingagents/research/onchain_replication/real_pilot_import_caller.py';assert h(p)==eager['candidate_sha256'];installed[str(p.relative_to(ROOT))]=h(p);ev.update(installed)
review={'schema_version':1,'decision':'accepted','extension_sha256':h(E/'EXTENSION_PROPOSED98_01.json'),'reviewer':'Independent full27 allocation reviewer; immutable accepted97 prefix plus actual failed26 delta','scope':'Same-family cumulative allowance only:49 actual closed receipts plus17 preserved historical=66 permanently spent,33COMPLETE33FAILED;28 unchanged pending+3 closed preclaim reserves+ONE unused27=98. Exact98 allocation reference joined. Base51/prior17 and1420 financial ceiling preserved; no refund, transfer, reopening, fresh-sample assertion or cap change. Six installed source bodies join accepted polling/eager source reviews but no entry/release/capacity/execution permission follows.'};p=R/'EXTENSION98_REVIEW01.json';p.write_text(json.dumps(review,indent=2)+'\n')
s={'decision':'accepted_allocation_delta_only','extension_review_sha256':h(p),'evidence':ev,'installed_source_pins':installed,'checks':['Accepted97 immutable claim prefix unchanged; only raw full26 failed claim/terminal added.','Exact current98 extension allocation pointer/hash checked, not inherited prior allocation.','All pending/reserved/category financial fields unchanged;66+28+3+1=98; unique unused27.','Original full26 partial numeric summary supplies no MCM completion; qualified Root terminal transcription remains non-raw export.'],'qualification':'No historical re-execution or duplicate claim census. No scientific input reads, numerical imports, Run/Owner, real transport, source mutation or launch. Subsequent exact registration/source/input/recovery/current eligibility review remains required.'};(R/'SOURCE_REVIEW01.json').write_text(json.dumps(s,indent=2)+'\n');print(json.dumps({'extension_review_sha256':h(p),'source_review_sha256':h(R/'SOURCE_REVIEW01.json')}))
