# Actual local source and Parent capture04 review

Accepted only as an actual local BYTE capture with original-mode metadata. No material mismatch was found in the reviewed capture. This is not an external recovery proof, a final caller release, or numerical authority.

Independent reconstruction passed 17,710 assertions, plus 851 supplementary assertions. The checker read 1,632 distinct bounded regular files totaling 81,151,556 bytes (the review uses a declared 256 MiB aggregate read ceiling; this is not the 8 MiB preclaim measurement). It reconstructed all 15 prior canonical archives from their genuine recovered flat bodies, then joined the complete current 605-member/491-file capsule to the old 589-member basis plus exactly 15 new input files and one directory. All original bodies and literal modes were retained. The complete current tracked tree has 355 files; only the self gate is excluded from its 354 source pins. All 11 role inputs and the full historical/target 194/195 path maps join, with 191 historical paths byte-identical. Model20f451, training configurationd5276b, and recipef8b1ec remain exact.

All 407 typed logical Git objects were independently reconstructed and SHA-1 framed from the 385 original recovered objects, nine previously recovered delta objects, and 13 captured new objects. Recursive commit/tree/blob traversal, canonical slash-sensitive tree ordering, all parents, exact reachable membership, and every current tracked body/executable class passed. Current HEAD is32d57eac5ea14435cd9d4aeb3e3b04d98bf16c41 with direct parent7b056a. The new13 and15inputs remain local-only; old394 availability does not confer recovery on the new commit.

The actual snapshot has 55 typed entries/47 regular files/2,119,573 logical bytes. Full USTAR headers, order, modes, padding, terminal blocks, compression, body hashes and byte-for-byte canonical reencoding reproduce archive d90353cb (553,764 bytes). Every snapshot file and directory has its declared private mode. All31 original origin rows independently join actual bytes, modes and paths:15inputs,10Parent files, and six closed-review MACHINE/MANIFEST/REPORT bodies. These six are precisely the declared review summary/seal scope, not a claim that the archive contains each original review's entire witness tree.

All10 actual Parent files match: caller424f13b6, draft requeste7579251, inverse and seven helpers. The helper set includes the exact preclaim557b7bcb; scientific job/resources remain original pinned bodies. The draft is still DRAFT_NOT_RELEASED, with genuine full_recovery, independent_source_input_runtime and final_review NULL. All12 old registration definitions are unchanged; the new reference is independent parent=None. All three original FAILED claims remain byte-identical, with highest claimed allowance19. No claim was created by this review.

The exact three-edit literal and AST inverse reconstructs source03 from source04; all functions/classes other than the declared put/main changes are identical. Real owned extracted put controls reproduced original intermediate0775 directories under umask002 and corrected0700 chains; an existing0755 parent refused before body creation. This is not a general validation of arbitrary concurrent writers or the public capture entry.

Failed capture03 remains FAILED with no CAPTURE receipt. Its snapshot and canonical archive bytes are identical to04, but its reviews, source-inputs, and source-inputs/fixture_inputs directories remain0775 where its manifest declared0700. No chmod or relabel occurred. Its failure07838977 and source368d77 are retained; the corrected successor does not retroactively validate its physical-mode claim.

The separate ACTUAL_ROOT_EXIT01 body115c0a7e reports Root tool5b7011 exit0 and0.463010116 seconds for combined generation/capture. That is a separately recorded observed tool result, not a program timing measure. Its original process PID is explicitly unrecorded NULL; process or group history cannot be reconstructed from it and was not invented. The program CAPTURE5a44a5 remains a distinct body.

No actual capture/restore, remote action, admission, lifecycle, model execution, checkpoint decoding, or numerical experiment was performed. The review does not test or assert POSIX restoration, installed runtime package bodies, unrelated stores, atomic writer exclusion, whole-fit resource capacity, full final caller/proof completeness, or numerical release. Future external selection must retain the exact new capture plus original failed03 disposition and mode history, and carry the genuinely recovered original394/589 basis. Final request/release and future proofs remain separate unresolved prerequisites. No new release or recovery proof is issued here.
