# Actual complete100 baseline recovery acceptance

Decision: ACCEPTED_ACTUAL_COMPLETE_BASELINE_BYTES_AND_ORIGINAL_GIT. The actual external selection and six fresh flat restorations recover the complete declared current Source9dc5/caller baseline. This substantive machine/report pair may be referenced as the genuine baseline full_recovery proof in the new Parent contract. It does not release native execution or assert recovery of later final request/release files.

All863regular original bodies,949typed original members and six additional flat metadata files authenticate. Each flat namespace is exact, private0700/0600, with one-to-one mapping and no omitted or duplicate body. Every archive frame, original type/path/mode, bounded body hash and footer agrees; independent deterministic gzip/PAX reconstruction from the actual flat bodies equals all six original archives byte-for-byte. All17selected current/external archive and metadata bodies retain their authenticated Git OIDs. The accepted actual remote reviewbbf4 and genuine one-use flat releasedd6dec authenticate completely; receipt36cc and exact executed restore028b010 match.

The NEW fresh-original-source339-01.git contains all385original logical Git objects with their actual types, lengths, body hashes and Git OIDs. Independent offline cat-file reads verified each object against its restored opaque body. HEAD is9dc5c79f738920b52947b4e63fed0397f1b5b207; strict fsck succeeds; its complete reachable object population equals the exact385index. All339current tree blobs join to the restored capsule and actual current source with valid Git mode classes. The full current non-Git capsule and nine-file Parent also match their whole baseline membership, literal modes and bytes, not merely selected source subsets.

The restored338registered source pins,194implementation/149package closure,8input roles,251runtime RECORD declarations, gate752c, Parent7f28 and draft7f506c join correctly. The actual admission6a3 body is present in recovered support. Both original failed claims4c543/d390 and failed markers35158/4b2d remain byte-exact, with genuine declared effective budgets18and19. Exactly2claims are spent; highest actual allowance19 remains. The planned checkpoint is preserved as opaque bytes, never deserialized. No scientific fit completion or refund is inferred.

The seven original Root receipts retain their actual0664 metadata through the explicit sidecar, while captured support copies and flat bodies are0600. Original metadata and private recovery metadata remain distinct; no POSIX tree or original Git-store layout restoration is claimed. The385objects establish logical Git reconstruction. Runtime RECORD declarations do not constitute installed runtime-body preservation or current Torch API observation.

Root's actual intent, stdout, empty stderr and outer-exit0 receipt authenticate the one actual restore. The original controller receipt records392successful offline Git operations and785floor observations above10GiB and within180seconds. Its `offline_git_PID_history_recorded:false` remains unchanged: no original PID, start ticks or complete drainage history was manufactured. The reviewer performed only bounded offline Git reads with lazy fetch and protocols disabled, canonical byte comparisons and metadata checks. No native/admission/claim/network call, numerical imports, tensor decoding, deletion or mutation of original outputs occurred.

Validation:4676scope/object/frame checks plus1106current-tree/context checks passed. Original local mode-equality, original restore01BR1 and previous review broad-output harness failures remain preserved in their original scopes; this acceptance applies to actual restore02. The original draft final_review/full_recovery nulls were not edited. Final immutable request, independent exact release, complete final-caller supplement preservation/recovery, fresh dispatch-time resource eligibility and one-use native authorization remain separate and unavailable here. Full100epoch capacity and all1420paper financial fits remain unproved/pending.
