The actual Root coalesced copy is independently accepted as a byte-preserving relocation of the genuine original source-policy recovery evidence. Exact candidate MACHINE01.json, REPORT01.md and MANIFEST01.json are prepared under candidates/ for Root-only exclusive installation at /home/malecada/master_thesis/TradingAgents-audit-fixes/research/onchain-paper-replication-2026-09-24/full_sources/financial-wrapper-compatibility-coalesced-evidence-root03-2026-10-04. Their combined byte extent is28,047; full final8MiB preclaim eligibility remains unmeasured by this review.

The readback passed4984 assertions across193 distinct regular paths. All57 intended bodies join their actual retained copies and original paths, extents, hashes and modes. The complete51-entry original provenance denominator remains38 receipts+13 source-evidence bodies, with six additional original proof/context bodies. All63 actual output members (59 regular files+4directories) matched the copier's retained signatures exactly, and the root identity/mode remained unchanged. Sampled output logical bytes1,441,608 and allocated bytes1,589,248 satisfy the fixed bounds; free space remained above10GiB. Every original body was rehashed after validation.

The actual source/input/release joins are copierfcadbfc, input5c4c9e and source releasecfe4f31b. Actual child1100653 was reaped with exit0; the separate actual tool receipt3a21e1f0 records chunk7fe463/root exit0. Original inner Root_exit remains null, as does actual_tool_root_exit in the child receipt. No inferred PID/time or substituted terminal was written. The current child PID and process group were independently absent. File-size inheritance is recorded as inheritance, without claiming a separate child limit readback. Actual copier Reader charge7,978,780B is distinct from this review's reads and the final Parent preclaim.

The complete original accepted composed review02 seal4c1bafac, machineaae1d255, report4ddb9c23 and c5cf38d2 proof were independently body-authenticated. Acceptance remains source7b056/589typed/585protected/340tracked/394Git385+9. This task did not repeat the earlier full83MB reconstruction; it authenticates the genuine accepted reconstruction evidence, all copied originals and the relocation joins. The new32d57eac commit/407objects/fifteen new inputs and finalParent/caller/proofs require separate fresh recovery. Three FAILED attempts and highest claimed allowance19 remain; prospective20 is not consumed.

The fixed concrete-policy four bodies retain their original bytes/names/modes; genuine preclaim557b Reader/_sealed accepts the inner proof/machine/report against its unchanged manifest. The three policy machine/report/manifest paths are exactly the same canonical paths used by the38receipt list. Candidate outer manifest lists every actual copied body and directory, origin map and draft, plus the two candidate review bodies; only the outer manifest itself is excluded. It has66 typed rows including root,61 regular members excluding itself; installation makes62 regular files. The c5 proof remains the existing literal ORIGINAL_RECOVERY_PROOF01.json. No new seven-field proof was fabricated or reencoded.

The candidate recovery machine uses the required original decision, policy/helper/map/proof pins, report hash and all38 real-root receipt references, with an explicit original7b-only scope and no native/claim authority. Candidate bytes are independently joined to their prospective manifest rows, while actual copied rows are checked against real bodies. Genuine _proof_bundle on all eleven registered inputs and real c5 proof currently refuses the absent Root MACHINE01.json, as required. No placeholder or fake accepted body was supplied. Candidate installation and a subsequent real-path proof-bundle check remain mandatory.

Root installation must follow INSTALL_CANDIDATES01.json: verify all63 retained fingerprints and hashes and all three destination names absent; install only the three exact bodies exclusively at0600, publish outer manifest last, fsync files/root, retain partial outcomes on failure without overwrite/retry, and verify every installed member. Root alone performs these mutations. No old draft NULL, proof, body or mode is changed.

The first verifier retained a one-character transcription error in the supplied Root tool-exit SHA; CHECK01.stderr/source remain. The successor uses the actual previously observed3a21e1f0 full pin and passes. A transient empty setup file outside the owned directory was immediately removed; REVIEW_OPERATIONS_NOTE01 records the mistake. No live Root/CAP/evidence file changed during review. All claimed results use the corrected retained readback.

There is no claim of atomic writer exclusion, POSIX reconstruction, dependency-body recovery, full scientific capacity, finalpreclaim success, empirical timing/returns/exposure/fees/funding or predictive performance. Exact byte recovery evidence is the only accepted scientific-provenance scope here; numerical execution remains unreleased.
