from pathlib import Path
import hashlib,json,stat
B=Path(__file__).resolve().parent;P=B.parent/'paper-treatment-fit-admission-preparation02-2026-10-04';R=B.parent/'paper-treatment-fit-admission-review01-2026-10-04';REL='overlay/tradingagents/research/onchain_replication/treatment_admission.py'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def put(name,x):(B/name).write_text(json.dumps(x,sort_keys=True,indent=2)+'\n')
c=json.loads((B/'CHECKS02.json').read_text())
put('REVIEW02.json',{'schema_version':1,'verdict':'WITHHELD_EXACT_ABSENCE_DA4','candidate_manifest_sha256':sha(P/'MANIFEST02.json'),'candidate_source_sha256':sha(P/REL),'prior_review_manifest_sha256':sha(R/'MANIFEST01.json'),'source_inverse_sha256':sha(P/'CORRECTION_INVERSE01.json'),'verified_corrections':{'DA1':'actual original id/status/reason fallback accepted unchanged as unavailable only with explicit absent flag, FAILED terminal, exact registered ordered cells; retained rows remain strict; complete/unknown/malformed cases refuse','DA2':'actual descriptors acquired at open are closed when fdopen fails; ownership transfers after successful wrapping; fstat/read failures close acquired stream','DA3':'earliest fatal object survives later ordinary/fatal errors; otherwise first ordinary survives; all callbacks attempted and actual secondary error identities attached best effort; attachment failure cannot replace original'},'remaining_findings':[{'id':'DA4','priority':'P2','file':REL,'line':234,'witness':c['witnesses'][0],'required_change':'Refuse any lexically present durable pathname using os.path.lexists or equivalent lstat semantics; retain absence only when no directory entry exists. Keep FAILED/unavailable/id/date/ordered-denominator checks unchanged.','scope':'Presence proof only; the demonstrated route still returns unavailable and does not create positive financial or completed-graph authority.'}],'checks':c['checks'],'checked_scope':['47-member/42-file complete typed manifest bytes/modes','full five-edit byte and AST inverse to old treatment_admission; all other inherited candidate bodies unchanged','unmodified genuine verify_claim/job._terminal source/input/parent/component/config/coverage/timing joins and fit/population caller bodies','actual fallback AST and absent/retained refusal controls','216 first-fatal primary/two-cleanup combinations','126 owned-IO stage/error combinations, including faultless reads and fdopen/read/close failures','real tiny descriptors proved closed after each owned-IO control; no actual lifecycle objects'], 'harness_history':'check01 stopped before source testing because predecessor manifest schema was assumed (members/string mode versus actual entries/integer mode); error and source preserved, check02 uses actual schema','limits':['Producer pins remain None; genuine treatment admission refuses. Fund policy remains unadmitted.','No ResearchRun/Owner/claim, numerical array/test-label/financial execution, native process or network/Git operations','No arbitrary allocation-exhaustion, concurrent pathname race or failing-close success guarantee; injected close faults happen after actual owned descriptor closes','No adoption, installed source, capacity, cumulative allowance, recovery or paper-credit conclusion'],'authority':{'installed_source':None,'claim':None,'native_execution':None,'financial_credit':0}})
(B/'REVIEW02.md').write_text('''# Independent downstream02 correction review

Verdict: WITHHELD for one remaining exact-absence predicate, DA4. The original DA1–DA3 corrections pass the bounded independent controls.

**DA4, P2 — treatment_admission.py:234:** `not actual_row_path.exists()` accepts a present dangling symlink as an absent durable row. A fresh owned control established `lexists=True`, `is_symlink=True`, `exists=False`; the actual extracted consumer predicate accepted it. The branch still represents unavailable data, so this is not evidence of positive completion or financial authority. It fails the claimed exact pathname-absence prerequisite. Use lexical presence (`os.path.lexists` or equivalent lstat semantics), rejecting files, directories and both live and dangling symlinks while retaining the existing FAILED/unavailable/registered-cell checks.

DA1 now accepts the actual observer's id/status/reason fallback unchanged, without fabricated asset/week fields. Complete or active terminals, extra fields, wrong identity and retained-row impersonation refuse. The caller derives the flag from disposition_input=None and retains the later path predicate; only that predicate remains defective.

DA2 closes actual acquired descriptors when fdopen raises and transfers ownership only after successful wrapping. DA3 preserves the earliest fatal object through later close errors, otherwise retaining the earliest ordinary error. All cleanup callbacks are attempted and secondary actual exception identities remain available in the cause group; attachment failure cannot replace the selected error.

The 1,273 independent controls include complete 47-member/42-file manifest authentication, all inherited body comparisons, full byte/AST inverse, untouched source/provenance/per-week/component/coverage/causal/common-mask checks, 216 callback combinations and 126 actual owned-IO stage/error cases. Real tiny descriptors were checked closed after each case. These counts are engineering checks, not empirical outcomes. check01 stopped at an incorrect predecessor-manifest schema assumption; its source/error are retained and check02 corrects the harness to the actual entries/integer-mode schema.

Producer pins remain None, fund historical membership/vintage/known_at policy remains refused, and no genuine ResearchRun/Owner/claim, native workload, numerical module, array or test label was used. Actual committed ancestry, graph numerical semantics, financial source composition, capacity, cumulative accounting, full recovery and release remain separately withheld. Arbitrary allocation exhaustion and concurrent path races were not proved; injected close failures occurred after the owned descriptor actually closed.
''')
entries=[]
for p in sorted(B.rglob('*')):
 rel=p.relative_to(B).as_posix()
 if rel=='MANIFEST01.json':continue
 s=p.lstat();kind='directory' if stat.S_ISDIR(s.st_mode) else 'file';assert kind=='directory' or stat.S_ISREG(s.st_mode)
 e={'path':rel,'type':kind,'mode':stat.S_IMODE(s.st_mode)}
 if kind=='file':e.update(bytes=s.st_size,sha256=sha(p))
 entries.append(e)
put('MANIFEST01.json',{'schema_version':1,'scope':'complete typed independent downstream02 source review; exact self excluded','entries':entries,'members':len(entries),'regular_files':sum(e['type']=='file' for e in entries)})
print(json.dumps({'checks':c['checks'],'report':sha(B/'REVIEW02.md'),'machine':sha(B/'REVIEW02.json'),'manifest':sha(B/'MANIFEST01.json'),'members':len(entries)},indent=2))
