# Independent actual baseline and native documentary-predicate review

Decision: **accepted actual immutable unreleased baseline recovery and exact native source contract as documentary release predicates. Final complete-union/request acceptance and fresh launch eligibility remain required; these records alone do not authorize an invocation.** No concrete schema contradiction or new source defect was identified in the bounded review.

This additive review preserves the earlier source-only report `804928472b3dece1f8d2b664e6fb14cbfc3c6f5971d462458dc93295b58ffe7f` and every original null/unreleased template. The earlier unresolved recovered-Git prerequisite is now discharged within the selected scope by the independent actual outcome review `e9e5205c05be226379abeb49c844bacb218332f537c667c21cdf5b77203d203b`, manifest `0b97569c9c3f4a6457bdd07cf704190e56afbabc41783196d6fdc683c9f0a048`. Later final-body recovery remains undisclosed as complete because it has not occurred.

## Exact actual baseline receipt

The reviewed Root body is `held-consumer-final-native-proof-root-preparation01-2026-10-03/ACTUAL_EXTERNAL_FINAL_BASELINE_RECOVERY01.json`, SHA256 `dc18f7ae66cf3ad67733e6f14b1941245a6e08ca365f3eac2bf35af8009f5962`.

Independent `check01.py` authenticates all ten referenced bodies by canonical path, full bytes, length and SHA256, then the complete 12-member recovered-Git review evidence manifest including modes and single-link regular types. Actual proof, terminal, verdict, source, flat-recovery and original request/capture hashes agree. The accepted recovered-Git outcome covers 246 current committed files, 205 source/registration joins, 33 opaque registered inputs, 26 selected C6 paths, 638 historical commit:path joins and 354 installed object bodies. Its 5,282 independent checks and four exact FAILED histories with effective budgets 2,3,4,5 are authenticated as that review's actual evidence, not represented as a second rerun by this reviewer. The successful proof terminal retains exit 0 and 90.29580722100218 seconds. No ObjectStore/proof, Git query, archive restoration or network operation was repeated for this additive review.

The baseline joins the already independently authenticated remote-origin receipt `e4c0d191f87816717e3239c627421d5096e79466f4234a85ed6d4cdaf610ea9d`, flat recovery `48c24f5b7c015cb902db19afbb2b171edefadb88a3bb10ef86d8815067c8bf34`, and genuine selected recovered-Git proof `b4544ebb75a5411b99d07fccd5c34ed72e5c40f9f53a6e6558dfaf9bb3523c5c`. Source origin is actual external Main commit `d9ebc6cb0be3b3b5f7247ff486e44455136b21ef`. Complete archival membership remains 925 capsule members (663 regular bodies) and 12 external-parent members (10 regular bodies); flat representation is exactly 676 files including its metadata and receipt.

The receipt correctly separates archival original modes from instantiated POSIX modes and retains `full_c6_tree_or_ancestry=false`, installed runtime-body and outside-store recovery false, genuine run/native false, later proof/release/request-body recovery false and complete-final-union acceptance false. The recovered-Git proof itself correctly retains `external_origin_proved=false`; the separate accepted real remote chain supplies that origin, rather than changing the Git utility's scope. The C6 selected-path proof does not establish its full recursive tree or ancestry.

## Exact caller and contract

The original capsule remains `d443208795f59292c156c5b81b687594efacea4d`. The actual external parent caller remains `7a197e2f57db3fff44fce453356d187f62dce5f119125e6814831eb6008f38dc`, success parser `95affaa3867b0f50dedc706121b47304126c6def39715133414ef149b9eae153`, and source contract `17e513bb0fa4ae667c822d80118578ae487138a3c6ad1cdd1123b7d68c435110`. All 205 current registered source/registration bodies were rehashed against the already reviewed proposal. The original installed request and envelope remain unreleased; both fresh case namespaces and the parent attempt namespace remained absent.

The source contract is limited to one fixed fresh `original-import-held-success-20261003-01` invocation after the remaining conditions. The generic envelope retains the dependent publication-failure case, but the caller only selects success. The finite resources remain 3 GiB native high=max/zero swap, 1,800-second native unit, 1,840-second outer active wait, 2,000-second parent active wait with separate cleanup, 6 GiB startup availability/3 GiB host reserve/two CPUs/4 MiB per-file limit/sampled 1 GiB whole-capsule watch/10 GiB disk floor. There is no new current unit readback, guarantee of completion, hard whole-invocation deadline or aggregate kernel quota.

The same-program accounting retains four FAILED attempts and the independently accepted cumulative-six proposal for the two fixed fresh cases, base two/prior zero, highest currently adopted five. No adoption or claim has occurred here. No paper allowance 65, exhausted cold-family transfer, refund, old-identity retry, source/mathematical/tolerance change or financial fit follows.

## Honest finite sequence and machine records

The actual Parent03 `prepared` predicates (`launch_success01.py:229` onward) require exact native review fields and an authenticated baseline recovery decision; they do not require the documentary records to hash or prove their own future external recovery. The contract digest excludes exactly the three later proof-reference fields, so the following sequence is finite:

1. Preserve the now accepted complete immutable baseline, genuine selected recovered-Git result and their independent reviews.
2. Issue the genuine independent documentary decisions in this directory for the unchanged caller/parser/source contract and exact actual baseline body.
3. Root installs copies of these decisions and the actual receipt, then renders exact final release/request references without altering the bound contract. Every added/changed member is enumerated against the immutable baseline; original unreleased templates stay preserved.
4. Root externally preserves and freshly recovers every final added/changed proof, review, release, request and invocation body. A separate independent complete-union and exact actual-request review, retained outside the immutable parent, verifies the full baseline-plus-delta before any `--launch`. Such a review can honestly inspect already recovered bodies without claiming that its own later statement was in the prior archive.
5. Root checks fresh original source/runtime/namespace/process/memory/disk eligibility and permits at most the single fixed success invocation through the genuine guarded source. Native source must authenticate actual kernel/readiness controls before worker release. Independent actual outcome, complete retention/recovery and a separately reviewed dependent invocation remain required afterward.

The two JSON records emitted by this reviewer are genuine decisions:

- `NATIVE_PARENT_RELEASE_REVIEW01.json` uses the source-required exact seven fields and decision `accepted-native-parent-release`. It approves this precise documentary native contract; its parser schema does not have a place for an added scope field, so this report supplies the explicit necessary-but-not-sufficient execution condition. It is not a current claim, native control receipt or complete-union decision.
- `EXTERNAL_BASELINE_RECOVERY_REVIEW01.json` uses decision `accepted-external-final-baseline-recovery`, binds actual receipt `dc18f7ae…`, and explicitly states the immutable-unreleased-baseline-only scope and mandatory final-body recovery/union/request review. “Final baseline” is the selected source schema's name, not an assertion that future final documents have already been recovered.

`check01.py` extracted only the actual two documentary assertion statements from the pinned parent, confirmed that these genuine decisions satisfy them, and confirmed refusal of a changed caller hash and changed actual-recovery hash. It did not call `prepared`, `main`, `launch`, Admission, ResearchRun, Owner, native guard or a capsule worker. No synthetic review was represented as actual authority. Root must not interpret satisfaction of these two assertions as the entire independent launch decision.

## Untested and excluded claims

No numerical/scientific module, array or score was imported/decoded; no financial experiment, output ledger, native process, source/Git mutation or network action occurred. Native/current-unit effectiveness, full MCM/GAT/LSTM or financial capacity, full-size storage/offload, timing leakage, fees/funding, exposure/cashflow conventions and numerical agreement with the paper remain untested here. The small LOCAL6 success has not occurred. Both held receipts, stage closure and full 160-comparison success remain prospective; the dependent case's 64 completed comparisons versus 96 computed unpublished cells must remain distinct if it is later admitted.

All previous failures, source-only limitations and remaining tasks remain. Runtime installation, empirical stores, complete C6 ancestry and a reconstructed original POSIX tree are excluded. The actual baseline, actual Git proof, review bodies and caller are unmodified. Only this new reviewer directory was written; its exact checks, readback, decisions and report are frozen below the review manifest.
