# Independent LOCAL6 native contract review — source and metadata only

Disposition: **accepted as the exact source/native-contract preparation for one fresh success identity; final execution approval is not issued by this record.** No new material implementation defect was identified within the reviewed source and metadata scope. The three documentary proof fields remain null in the proposal, and the installed request and envelope remain unreleased. No `accepted-native-parent-release` machine record is issued here.

The prospective contract digest is `17e513bb0fa4ae667c822d80118578ae487138a3c6ad1cdd1123b7d68c435110`, computed by removing only `release_review_sha256`, `external_capsule_recovery_sha256` and `external_recovery_review_sha256`. The proposal body is `2d80c20b409f55ecd3e61141d8a962b43ba2d105326248f40fb6bfffea906b8c`. This binds both registered case contracts, while the reviewed caller permits only `original-import-held-success-20261003-01`.

The original parent is `/home/malecada/master_thesis/onchain-fixture-isolation/held-score-consumer-root-launch-20261003-01`. Its caller is `7a197e2f57db3fff44fce453356d187f62dce5f119125e6814831eb6008f38dc`; its success supplement is `95affaa3867b0f50dedc706121b47304126c6def39715133414ef149b9eae153`. The unchanged original capsule is `/home/malecada/master_thesis/onchain-fixture-isolation/held-score-consumer-native-20261003-07/source`, actual Git HEAD `d443208795f59292c156c5b81b687594efacea4d`.

## Independent checks

`check02.py` executed only standard-library metadata checks and source-extracted command construction. The authentic, pinned parser's bounded reader and offline Git batch source checker independently rejoined 204 registered source pins plus the registration, all 33 opaque input bodies for each case, the six exact outputs, current registration/experiment/family equality, and genuine current Git bodies. No source-package numerical import, array deserialization, Admission, Owner creation, native guard or claim was executed. The actual runtime checker verified the current interpreter/origins/lock and 251 named distribution RECORD/version entries. This is installed runtime metadata authentication, not backup or hash authentication of every installed binary.

The two input policies retain score chunks of 64 cells and the selected held-read policy with two targets and a 768-byte maximum. Source/input/model identity and ordered 32-motif denominator are unchanged. The caller and parser hashes were rechecked against the original installed files. The installed envelope differs from the prospective contract only in status and remaining work; the three proof references are still null. The fresh claim, outer and native-artifact paths for both cases and the parent attempt path were absent at this observation.

The exact source `_command` at `job.py:147` was extracted and exercised with metadata arguments. Launch, monitor and worker vectors use the current pinned interpreter, `-B -m tradingagents.research.onchain_replication.job`, the original capsule, exact registration, one selected identity and source commit. The physical-anchor argument is absent for this selected route; the compact resource policy has no physical-policy override. Static AST checks also verify `assert_guarded_worker` and `_resource_limit_receipt` precede `ResearchRun.start`, and genuine preflight precedes resource Binding, imported-stage attachment and MCM production. These checks establish callable source ordering, not actual native enforcement or genuine capabilities.

The first reviewer harness failed because its package-count assertion counted only the `onchain_replication` directory (140 files), rather than the full selected `tradingagents/` package closure (148). `check01.py` and `CHECK01.log` are retained unchanged. `check02.py` changes only that prefix and its output name; the corrected run passed. No author source or registration changed.

## Genuine authority and resource route

References below are relative to the original capsule unless stated otherwise; exact body hashes are retained in `READBACK02.json`.

- `fixture_tools/outer_controller01.py:47` checks the released envelope, original source/Git/root/runtime/registration and selected unused identity. Its `run` route at line 134 authenticates the runtime and selected `owned_io` origin before starting the genuine job launcher. No returned dictionary substitutes for a ResearchRun or Owner.
- `tradingagents/research/onchain_replication/job.py:201`, `:255` and `:318` preserve launch → monitor → guarded worker. At lines 329–342 the worker verifies the actual native guard, owner identity and complete registered resource policy, records real file-limit/native receipt data, then calls `ResearchRun.start`. Failure and interruption retain the original identity; the source explicitly disallows relaunch.
- `resource_binding.py:22`, `matching_owner.py:160`, and `resource_fixture.py:254` retain real resource Binding and compact Owner checks. `resource_fixture.py:116` joins the exact job/plan/selected held key, six registered outputs, original 32 motifs/512 samples, original source ancestry, both graph inventories and both finite reservations before the Owner birth. The executed branch remains the registered resource engineering fixture; it is not a financial fit.
- `resources.py:466` establishes the native unit, and lines 489–529 authenticate LimitFSIZE, RuntimeMaxSec, child affinity/readiness, cgroup limits and the host reserve before publishing release. The selected contract remains memory high=max=3 GiB, swap zero, two CPUs, unit wall 1,800 seconds, startup availability 6 GiB, host reserve 3 GiB, per-file hard/soft 4 MiB and 10 GiB disk floor. The capsule storage watch is sampled 1 GiB allocated/logical with 32,768 entries/depth 32/five-second traversal bound; it is not a kernel aggregate quota. The outer active wait is 1,840 seconds; parent active monitoring is 2,000 seconds with separate cleanup. These are not an asserted hard whole-invocation deadline or a guarantee that the numerical workload will finish.
- The original accepted Parent03 cleanup, fsynced exclusive reservations, anchored log FDs, first-actual-fatal reducer, independent TERM/wait/KILL/reap actions, genuine post-tail globals, final source and log rejoins remain unchanged. Its `prepared` function (`launch_success01.py:201`) demands actual hash-bound review/recovery bodies. Documentary approval is a necessary release condition, not a replacement for native control readback.

## Denominators and retained accounting

The authentic same-program amendment is `b1d56965524c870c3233e828cc94f28402c4d9b0cffe82f4d87bf090cbe3ce1c`, allocation `7f882018f3d34bbd98a4ac1c1498e25fc3f4d577309832c87a98455e229c7120`, and independent accounting review `e317a6e59b79036376dc055c8aa42db6366bf230b151b1cd66404576752e58f7`. The amendment retains four exact FAILED claims and terminals, consumed-before four, cumulative ceiling six, base family budget two/prior zero, and only the two fixed fresh held identities. Highest allowance in an existing claim remains five; the sixth allowance has not been adopted by this review. Both fresh experiments have parent null. No historical identity is reopened, no failure refunded, and no paper/cold-family allowance transferred.

For success, two targets contain 2×32 and 3×32 MCM cells: 64+96=160 prospective independent scalar comparisons; the retained held f64 payloads are 512 and 768 bytes, sealed as one and two 64-cell batches. The original dictionary and spent sample history are imported, never regenerated. Actual `compact_mcm` source performs the selected held-byte consumption after complete streaming while the genuine stage is held, closes the stage, then reaches publication. On the dependent publication-failure case, both held readbacks and closed stages therefore precede the deliberate second publication refusal. Only the first 64 scalar comparisons are completed; the second 96 computed held cells must not be reported as completed scalar comparisons. First Produced completion and second failed/no-complete/no-publication remain distinct.

The generic envelope includes that dependent case because the genuine outer schema requires it. This review does not release its launch. It remains unavailable until genuine success COMPLETE, independent outcome acceptance, external outcome recovery and a separately reviewed exact dependent invocation. Missing or partial results must stay failed/unavailable.

## Exact remaining release requirements

1. Independently accepted actual recovered-Git outcome must join the complete archival baseline to genuine recovered current Git, 246 tracked bodies, 205 current source/registration checks, both 33-input cases, 26 selected original C6 paths and 638 historical source lookups/four FAILED claims. Root reports proof `b4544ebb75a5411b99d07fccd5c34ed72e5c40f9f53a6e6558dfaf9bb3523c5c`; its separate independent outcome verdict was pending when this source record was written. Reporting that execution is not this review accepting it.
2. The real baseline receipt and independent recovery decision must bind actual remote-origin `e4c0d191…`, complete flat recovery `48c24f5b…`, recovered-Git proof and the accepted review bodies. The baseline is unreleased. Later exact release/request/proof bodies and their changed/added members require separate byte-exact final preservation/recovery and union review; the older archive cannot be described as containing them. A self-referential hash/approval cycle must not be manufactured.
3. The final exact request, release, command and genuine review/proof body references must be checked against this unchanged contract, caller and parser before a machine native-release decision is issued. The final independent recovery union and fresh original namespace/process/memory/disk eligibility remain release conditions. Original unit controls must be observed by the real native source before worker release; no current unit exists as evidence here.

This preparation grants no neural/full-MCM capacity, transport or byte-retirement authority, financial fit, statistical agreement with the paper, timing-leakage clearance or positive trading evidence. Return/cashflow, fees/funding, exposure reuse and market-timing results were not measured because this is a tiny engineering route. All 13 tasks/C01–C18, broader assets/history, full eligible graph/batch population and gradients, financial wrapper/capacity, 27 refusal variants/16 classes and remaining Task8 obligations persist. The separate paper ledger remains 36 closed/highest 64; all 1,420 financial fits remain pending. Full tail and non-tail storage/recovery requirements remain; neither 4 MiB file caps nor tiny 160-cell comparisons establish that capacity.
