# Residual HUP3 one-use parent successor

Uninstalled source03. Source01/02 and their exact withheld reviews remain unchanged. Source02 corrected post-tail globals, controller independent escalation, authenticated cleanup-type reduction and receipt FD anchoring, but review1b26d2b0/c014fbb6 reproduces redirected stdout/stderr and absent reservation-parent fsync. RED03 replays that exact reviewer against unchanged source02 in a separately retained tree. Source03 does not run an old launcher or genuine job.

Acquired directory_identity now fsyncs its held original directory and its held parent before return, then rejoins mode/device/inode/uid/gid/path. The parent first calls it on attempt (fsync of PARENT's attempt entry), then on the fresh fixed identity (fsync of attempt's identity entry), before controller release. An error before completed fsync is a permanent observed reservation failure and grants no launch authorization; no replay or cleanup deletion follows. This does not claim an atomic mkdir-returned inode or immunity from storage hardware failures. Root alone owns the acquired writable scope.

Both logs are created through mandatory current directory/parent anchors and held nofollow FDs with O_CREAT|O_EXCL. The actual newly created original file FD, canonical path and inode are rejoined, file and directory fsync occur, and directory FDs close independently before handing the file FD to the genuine controller. Failed acquisitions independently close all acquired handles under the original first-fatal reducer. Replacement parents and same-mode inode substitutions refuse. File FD-to-current-path joins and actual FD file bounds are sampled during the controller and individually rechecked after reap, before every FD close. Final stable file signatures and actual log-fd-joins.json retain those joins. A changed namespace cannot redirect already acquired FD writes to a foreign file, and causes failure rather than a passed wrapper. No directory chmod occurs.

The exact two-case release/source/Git/input/runtime/199-148-204 counts, native3GiB/swap0/3GiBreserve/6GiBstart/2CPU/1800native1840outer/4MiBfile/1GiBcapswatch/10GiBfloor, external16MiBlogical32MiBallocated limits, fixed fresh success identity, original numerical/model protocol/32motifs512spent and genuine Run/Binding/Owner remain unchanged. Only directory_identity and launch plus new open_log/log_join differ from frozen02; full AST inverse elsewhere is recorded. Documentary templates remain unreleased, never approvals. Actual caller tree and full prepared/finish/native/recovery are absent.

GREEN03 seven new controls pass: exact launch log-loop redirection refusal, actual reservation-directory/parent four fsyncs, actual atomic logFD/write/final joins, foreign-file replacement not receiving FD writes, all3 log acquisition FD closes under first fatal, both reservation FD closes under first fatal and invalid/default source refusal. PRIOR_CORRECTION03 eight prior and LEGACY_CHECK03 nine original controls also pass. Actual returned process statuses for all three executions were0. Tiny utility processes and qualified source/metadata fixtures carry no research capability. Independent exact source review, actual final caller/envelope/review composition, complete actual external archival recovery and separately qualified genuine recovered Git proof, independent execution decisions and fresh OS/native eligibility remain required. No original run, native job, claim, numerical fit, network or financial execution occurred.
