Synthetic imported-original held MCM engineering case: second_target_publication_failure.

Program original-dictionary-import-engineering-2026-10-02; identity original-import-held-publication-failure-20261003-01; parent None; development/exploratory. The full original dictionary of32motifs and512spent samples is imported without resampling or clustering. Two authenticated synthetic targets have2 and3nodes and64 and96MCM cells. Normal success requires160 scalar-reference comparisons, both held f64 readbacks512+768bytes, both original MCM publications and all six registered outputs. Matching, dictionary and numerical tolerances remain unchanged. This local resource fixture does not complete the scientific full representation or paper-scope evaluation.

Cumulative engineering ceiling6 preserves four actual FAILED claims; at most one fresh claim per fixed identity. No refund, sample reset, transfer, cap ladder, paper budget65, test tuning or closed job replay is allowed. The dependent publication-failure identity may execute only after COMPLETE normal success, independent outcome review and actual complete external recovery. Otherwise it remains unavailable. Its expected publication failure stays FAILED; only the first64 scalar-reference comparisons can be counted complete. Second-target publication and scalar checks stay unavailable; any actual preceding MCM/held receipts are retained and evaluated separately.

The exact native envelope is3GiB high=max, zero swap,3GiB host reserve,6GiB startup reserve, two CPU affinity/threads, 1800seconds native/1840seconds outer,4MiB native hard/soft writable-file cap,1GiB whole-tree watch and10GiB disk floor. Interpreter authentication streams at most64KiB per read with a separate64MiB read ceiling; this changes no writable cap. Actual source199/package148 plus five admission metadata pins, all33inputs and six outputs must be committed and independently released. Guard/native readback, whole writable baseline, current resources, one-use parent and complete externally recovered inputs/sources are prerequisites. These rendered bytes are unregistered; no source/runtime metadata result confers execution authority.

All13tasks/C01-C18, both assets/history/comparisons, all32Task8 requirements and all1420financial fits remain in scope. Full55.44GB MCM, real eligible populations, joint gradients, typed tails plus batch/output streaming and capacity remain unproved. The27mutation variants/16classes are separate. No payment/contact/trading/deployment or deletion is authorized by this case.
