# Cold-proof engineering materialization charter

This is a prospective source-only charter template. It is not a registration or launch permission. The coordinator must install and commit the exact charter, input registration, source/runtime closure and independently reviewed release before numerical imports or reservation.

Program `compact-cold-engineering-20261003`, mechanism/family `compact-cold-genuine-authority`, maximum two attempts, prior attempts zero. This attempt is `compact-cold-inputs-20261003-01`, parent null, single cell `cold-input-materialization`, single registered output `proof-materialize.json`. Separate ResearchRun and exclusive outer/supervisor namespace receipts form the engineering history; no paper-family charge, transfer, refund or budget65 is created.

The question is whether the frozen synthetic input recipe can be materialized under genuine native worker authority with complete provenance and finite limits. The exact recipe, configs, model and training documents are frozen by their canonical source pins. Materialization generates19 four-node/four-edge weekly synthetic graphs, prices with the prescribed missing date, real calendar/example/scaler membership, all43 comparison input records and byte hashes. No dictionary is sampled or fitted in this phase. The original closed512-sample dictionary and historical jobs are not reopened. Synthetic labels/dates do not imply real market observations or fresh financial confirmation; lifecycle windows use existing availability and exploratory reuse.

Expected source-derived training count56, batches16/16/8 and graph count19 are prospective checks, not observed outcomes. Actual materialization must record all included/excluded dates, required graph hashes and actual denominators. Failure, missing inputs, disagreement, incomplete outputs or native/whole-tree boundary breach leaves the attempt failed/unavailable. No fabricated completed population can replace an unsuccessful materialization.

Proposed selected native policy:3GiB high=max, zero swap,3GiB host reserve,6GiB startup availability, two pinned CPU identities,1800-second native wall,4MiB file hard/soft cap,10GiB free-space floor. Whole capsule sampled watch:1GiB logical and allocated bytes,32768 entries,depth32,scan5seconds. Proof payload maximum256MiB and4MiB per file is additional. These are finite proposed constraints, not capacity evidence or a hard aggregate disk quota; root must verify actual native controls and complete descendants/cleanup.

An exclusive reservation consumes its fixed identity even if ResearchRun birth fails. A lifecycle claim consumes one family attempt regardless of success/failure. An outer-only failed reservation cannot be silently reused or refunded: it remains in the separate reservation history and the nominally unused lifecycle slot is blocked under this charter until a separately reviewed amendment. Withdrawing an untouched identity creates no trial and no refund; withdrawal cannot erase existing claim/raw evidence. A failed materialization blocks comparison. Partial files, failed/unavailable records and raw native/outer receipts remain immutable and require independent external recovery checks.

Acceptance requires a genuine completed ResearchRun, positive native/worker provenance, exact output membership and all43 input/body joins, no active owned processes/cgroup, and authenticated supervisor exit. Acceptance permits preparing the second registration only; it does not admit comparison or establish numerical equality, model capacity, financial fitting, original-import/refusal completion or paper agreement.
