from pathlib import Path
import json,hashlib,stat,os
D=Path(__file__).resolve().parent;F=D.parent;O=F/'financial-wrapper-compatibility-coalesced-evidence-root03-2026-10-04';L=F/'financial-wrapper-compatibility-coalesced-evidence-root-launch04-2026-10-04';C=D/'candidates';C.mkdir(mode=0o700);q=json.loads((D/'READBACK01.json').read_text());base=q['original_baseline_machine'];h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();encoded=lambda x:(json.dumps(x,sort_keys=True,separators=(',',':'),allow_nan=False)+'\n').encode()
report='''Independent review accepts the actual coalesced evidence copy and preserves the original accepted operational source-policy BYTE recovery scope: source7b056a574e3e7b3c7ba209a39ee6a615e649d60c,589 typed members/585 protected,340 tracked/195 implementation/150 package paths,394 Git objects comprising385 original+9. The unchanged literal c5cf38d2 proof remains ORIGINAL_RECOVERY_PROOF01.json. No new seven-field proof was issued.

All57 copied bodies and original modes join the full51 original provenance entries:38 receipts+13 source-evidence bodies, plus two original proof bodies and four original review context bodies. ORIGIN_MAP01 retains every original and retained-copy path/hash/mode. All38 receipts descend this manifest root. The three policy machine/report/manifest paths are shared with the fixed policy-review refs; its original proof and typed inner seal remain exact. Every existing copied body and the two new review bodies are included in the outer seal; only the seal itself is excluded.

Actual copier04 fcadbfc/input5c4c ran once:57 bodies,38 receipts,7,978,780 Reader bytes. Actual child1100653 was reaped0; separate tool7fe463 exited0. Their original receipts and stdout hashes are pinned in this machine; the inner Root_exit and draft missing-authority fields remain null. All63 existing member signatures matched stdout at independent readback, PID/group were absent, and sampled logical/allocated/floor limits passed. Source release cfe4f31b and original composed review aae1d255/4c1bafac are preserved.

This review authenticates the byte-preserving relocation of the genuine previously accepted recovery evidence, not a new recovery event for source32d57eac/407 Git objects, its fifteen gate/input files, or the final Parent/caller/proofs. Those require fresh recovery. Three old FAILED attempts and highest claimed allowance19 remain; prospective20 is unspent. No installed dependency-body recovery, POSIX reconstruction, atomic writer exclusion, full capacity, final8MiB preclaim success, numerical/claim authority or economic result is asserted. Root must install these exact review bytes at the declared paths and obtain final integration verification before use.
''';(C/'REPORT01.md').write_bytes(report.encode());(C/'REPORT01.md').chmod(0o600)
m={k:base[k] for k in ('schema_version','decision','policy_sha256','checker_sha256','historical_map_sha256','target_map_sha256','recovery_proof_sha256','source_commit','current_typed','protected_typed','tracked','historical_paths','target_paths','package_paths','unchanged_paths','complete_reachable_git_objects','old_git_objects','new_git_objects','highest_actual_allowance','global_spent')};m.update({'reviewer':'storage_watch_review; independent of copier author and Root execution','report_sha256':h(C/'REPORT01.md'),'recovery_receipts':q['actual_receipt_refs'],'scope':'Actual literal coalescence of original accepted7b source-policy BYTE recovery evidence only','original_review_machine_sha256':'aae1d255e54bf8fb52a82c7c7dff6495df16e1c82b71d448828e28f841db116f','original_review_manifest_sha256':'4c1bafac000b164f4534e0308169214c9fd7f3f72cab2f4389a1647e6ada3cde','original_review_report_sha256':base['report_sha256'],'origin_map':{'path':str(O/'ORIGIN_MAP01.json'),'sha256':h(O/'ORIGIN_MAP01.json')},'copied_bodies':57,'original_provenance_entries':51,'receipt_bodies':38,'source_evidence_bodies':13,'actual_copier_source_sha256':'fcadbfcde1bf9d9d61887af27de2dff610b5d7cce188a4cb77da1c99d6989fda','actual_inputs_sha256':'5c4c9ebbc976d057a1896f106c18fc00c8c0a179e2beaf047bc5ed329ea40f04','actual_copy_reader_bytes':7978780,'actual_launch_evidence':{n:{'path':str(L/n),'sha256':h(L/n)} for n in ('INTENT01.json','SPAWN01.json','ACTUAL_CHILD_EXIT01.json','ACTUAL_ROOT_TOOL_EXIT01.json','stdout01.log','stderr01.log')},'actual_root_exit':0,'actual_child_exit':0,'original_inner_root_exit':None,'original_draft_authority_nulls_preserved':True,'same_path_policy_receipts':True,'new_source32d_recovery':False,'final_parent_recovery':False,'runtime_package_bodies':False,'posix_tree':False,'atomic_writer_exclusion':False,'full_preclaim_success_or_8MiB_fit_proven':False,'claim_authority':False,'numerical_authority':False})
(C/'MACHINE01.json').write_bytes(encoded(m));(C/'MACHINE01.json').chmod(0o600)
rows=[{'path':'.','kind':'directory','mode':stat.S_IMODE(O.lstat().st_mode)}]
for n in sorted(q['whole_signatures']):
 p=O/n;s=p.lstat();expected=[s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns];assert expected==q['whole_signatures'][n];row={'path':n,'kind':'directory' if stat.S_ISDIR(s.st_mode) else 'file','mode':stat.S_IMODE(s.st_mode)}
 if row['kind']=='file':row.update(bytes=s.st_size,sha256=h(p))
 rows.append(row)
for n in ('MACHINE01.json','REPORT01.md'):assert not (O/n).exists();rows.append({'path':n,'kind':'file','mode':0o600,'bytes':(C/n).stat().st_size,'sha256':h(C/n)})
manifest={'schema_version':1,'scope':'Exact actual coalesced root plus reviewed machine/report; manifest itself excluded','members':sorted(rows,key=lambda x:x['path'])};(C/'MANIFEST01.json').write_bytes(encoded(manifest));(C/'MANIFEST01.json').chmod(0o600)
# Independent prospective seal/body joins. Candidate files are not treated as already installed.
maprows={x['path']:x for x in rows};assert len(maprows)==len(rows)==66
for ref in m['recovery_receipts']:
 rel=Path(ref['path']).relative_to(O).as_posix();assert maprows[rel]['sha256']==ref['sha256'] and maprows[rel]['kind']=='file'
assert maprows['ORIGINAL_RECOVERY_PROOF01.json']['sha256']==m['recovery_proof_sha256'];assert maprows['REPORT01.md']['sha256']==m['report_sha256'];assert maprows['MACHINE01.json']['sha256']==h(C/'MACHINE01.json')
for row in rows:
 if row['kind']=='file':p=C/row['path'] if row['path'] in ('MACHINE01.json','REPORT01.md') else O/row['path'];assert h(p)==row['sha256'] and p.stat().st_size==row['bytes'] and stat.S_IMODE(p.stat().st_mode)==row['mode']
plan={'schema_version':1,'status':'EXACT_CANDIDATES_NOT_INSTALLED','destination_root':str(O),'preserve_existing_members':63,'candidate_files':{n:{'source':str(C/n),'destination':str(O/n),'sha256':h(C/n),'bytes':(C/n).stat().st_size,'mode':0o600} for n in ('MACHINE01.json','REPORT01.md','MANIFEST01.json')},'write_protocol':['Require all three destination names absent, current root identity/mode unchanged and all63 existing member fingerprints/body pins equal READBACK01.','Read and hash these exact candidate bytebodies. Create each destination exclusively O_CREAT|O_EXCL|O_NOFOLLOW at0600; write complete bytes, fsync file, close once with first-fatal precedence; publish manifest last, then fsync root directory.','Retain any partial output and actual launch/install exit on failure; never overwrite/retry a created name. Do not modify existing copied bodies, original proofs, modes, draft NULLs or receipts.','Independently rehash all actual members against the installed outer seal and run unchanged preclaim _sealed/proof-bundle components on actual paths; final Parent admission remains separate.'],'post_install_typed_members_excluding_manifest_including_root':66,'post_install_regular_files_including_manifest':62,'whole_preclaim8MiB_fit':None,'claim_authority':False,'numerical_authority':False}
(D/'INSTALL_CANDIDATES01.json').write_bytes(encoded(plan));print(json.dumps({n:{'sha256':h(C/n),'bytes':(C/n).stat().st_size} for n in ('MACHINE01.json','REPORT01.md','MANIFEST01.json')},indent=2));print(sum((C/n).stat().st_size for n in ('MACHINE01.json','REPORT01.md','MANIFEST01.json')))
