import hashlib,json,os,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();D=F/'financial-genuine-wrapper-root-claimedrun-source339-remote02-2026-10-04';OLD=F/'financial-genuine-wrapper-claimedrun-source339-selection-review01-2026-10-04';sys.path.insert(0,str(F/'held-consumer-final-recovery-preparation04-2026-10-03'));import recovery04 as R
sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
def read(p):return R.read(p.parent,p.name)
def git(args):
 p=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never',*args],stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_NO_LAZY_FETCH':'1','GIT_OPTIONAL_LOCKS':'0','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_TERMINAL_PROMPT':'0'});ck(p.returncode==0 and len(p.stdout)<=8*1024**2 and len(p.stderr)<=65536,'bounded localGit');return p.stdout
ck(sha(read(OLD/'MANIFEST01.json'))=='60ded6f79c98e0e5878208f8196c2c45c3a66fadfc1d05e21526720a9e3813b3','immutable withheld prior review');oldread=json.loads(read(OLD/'READBACK01.json'));oldjoins=json.loads(read(OLD/'COMMITTED_BODY_JOINS01.json'));oldrows={r['path']:r for r in oldjoins};raw=read(D/'SELECTED_BODIES01.json');ck(sha(raw)=='38bc70a9c3cc684588e9cb8792587be08ff65a4cefc27e4d31057fb630650cce','exact successor selection');q=json.loads(raw);rows=q['rows'];names=[r['path'] for r in rows];new={r['path']:r for r in rows};H=q['remote_commit'];ck(H=='6514f20fc208e0d2f7ada31bc285b4e0b5c33ff8' and names==sorted(set(names)) and len(rows)==195 and sum(r['bytes'] for r in rows)==18500231,'exact unique195/bytes/commit');ck(set(oldrows)<=set(new) and len(set(new)-set(oldrows))==19,'exact prior176 plus19')
for n,r in oldrows.items():ck(new[n]=={k:r[k] for k in ('path','bytes','sha256')},'all176 rows unchanged')
tree={}
for item in git(['ls-tree','-r','-z',H,'--',*names]).split(b'\0'):
 if item:meta,n=item.split(b'\t',1);tree[n.decode()]=tuple(meta.decode().split())
ck(set(tree)==set(names),'actual full committed selection membership');joins=[]
for r in rows:
 p=ROOT/r['path'];s=p.lstat();b=read(p);mode,kind,oid=tree[r['path']];ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and len(b)==r['bytes']<=4*1024**2 and sha(b)==r['sha256'],'every selected current bounded body');ck(kind=='blob' and mode in ('100644','100755') and hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()==oid,'every committed blob/OID')
 if r['path'] in oldrows:ck(oid==oldrows[r['path']]['git_object'] and mode==oldrows[r['path']]['git_mode'] and stat.S_IMODE(s.st_mode)==oldrows[r['path']]['literal_mode'],'unchanged176 actual object and literal mode joins')
 else:ck(git(['cat-file','blob',oid])==b,'new19 actual immutable committed bodies')
 joins.append(dict(r,git_mode=mode,git_object=oid,literal_mode=stat.S_IMODE(s.st_mode)))
# Resolve original blocker via full own manifest closure; never substitute a copied reference.
P=F/'financial-genuine-wrapper-claimedrun-actual-admission-review01-2026-10-04';m=json.loads(read(P/'MANIFEST01.json'));ck(sha(read(P/'MANIFEST01.json'))=='24e6451d2a9c5ec516b99ca95bb477567e5f9ef5d13adef3bb41c0633b93e5c7','genuine missing manifest now selected');required={r['path'] for r in m['members']}|{'MANIFEST01.json'};ck(required=={p.name for p in P.iterdir()} and len(required)==5,'complete actual independent review originalfive')
for n in required:ck((P/n).relative_to(ROOT).as_posix() in new,'all missing originalfive selected')
for r in m['members']:
 p=P/r['path'];b=read(p);ck(len(b)==r['bytes'] and sha(b)==r['sha256'] and stat.S_IMODE(p.lstat().st_mode)==r['mode'],'actual independent review exact body/mode')
proof=json.loads(read(P/'INDEPENDENT_SOURCE_INPUT_RUNTIME01.json'));ck(sha(read(P/'INDEPENDENT_SOURCE_INPUT_RUNTIME01.json'))=='059232d0f7fc8922cee526a1bd30fef2ecb51ee17103284bcaac18c77e77641c','genuine0592 proof selected');ck(proof['source']==proof['design_source']=='0a2e7639b42b9423b90743feadcda4078aa21816' and proof['tracked_source_count']==339 and proof['source_file_count']==338 and len(proof['inputs'])==8,'proof current339338/eightroles');ck(proof['actual_metadata_admission']['global_spent_claims']==1 and proof['actual_metadata_admission']['highest_actual_claim_budget']==18 and proof['actual_metadata_admission']['effective_attempt_budget']==19,'exact actual metadata19/spent1/highestclaim18');ck(proof['actual_fresh_claim'] is None and proof['actual_complete_external_flat_recovery'] is None and proof['actual_new_Parent_release'] is None,'no release or freshclaim from metadata proof')
# Every selected own review manifest closes in this selection; census inventory manifests remain descriptive snapshots.
for r in rows:
 p=ROOT/r['path']
 if p.name.startswith('MANIFEST') and p.suffix=='.json':
  for v in json.loads(read(p)).get('members',[]):
   if v['kind']=='file':ck((p.parent/v['path']).relative_to(ROOT).as_posix() in new,'every selected own manifest regular member included')
# Previously bounded-parsed/recompressed archives are unchanged complete bodies and committed OIDs; reuse exact immutable proof.
for r in oldread['verified_archives']:ck(new[r['path']]['sha256']==r['sha256'],'whole earlier canonical archive identity unchanged')
C=F/'financial-genuine-wrapper-root-claimedrun-source339-capture01-2026-10-04';S=Path(proof['capsule_root']);R.same(S,json.loads(read(C/'source-manifest.json')));ck(git(['-C',str(S),'rev-parse','HEAD']).decode().strip()==proof['source'],'actual sourcecurrent stable')
for n,pin in proof['source_files'].items():ck(sha(read(S/n))==pin,'current actual338 proof bodyjoins')
ck(sha(read(D/'recover01.py'))=='0b397ccd0a014f60a414ce79d67dfd53c58a0fb61ca616a6576cc43da4bbf0aa','unchanged accepted transport');ck(not any(os.path.lexists(D/n) for n in ['fresh-recordfix-source325-01.git','selected','REMOTE_RECOVERY01.json','FAILED01.json','ACTUAL_INTENT01.json']),'fresh successor transport namespace absent');ck(not any(os.path.lexists(D.parent/'financial-genuine-wrapper-root-claimedrun-source339-remote01-2026-10-04'/n) for n in ['fresh-recordfix-source325-01.git','selected','REMOTE_RECOVERY01.json']),'withheld original not executed');ck(len(rows)<=506 and 11+2*len(rows)==401<=1024 and sum(r['bytes'] for r in rows)<=64*1024**2,'finite401 operation bounds');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','tradingagents'} for n in sys.modules),'no numerical research imports')
x={'schema_version':1,'decision':'ACCEPTED_EXACT_SOURCE339_SELECTION02_ONLY','selection_sha256':sha(raw),'commit':H,'selected_count':195,'selected_logical_bytes':18500231,'unique_Git_objects':len({r['git_object'] for r in joins}),'expected_Git_operations':401,'checks':len(checks),'unchanged_prior_rows':176,'new_rows':sorted(set(new)-set(oldrows)),'resolved_missing_proof_sha256':'059232d0f7fc8922cee526a1bd30fef2ecb51ee17103284bcaac18c77e77641c','resolved_complete_original_manifest_sha256':'24e6451d2a9c5ec516b99ca95bb477567e5f9ef5d13adef3bb41c0633b93e5c7','reused_whole_archive_verification':{'readback_sha256':sha(read(OLD/'READBACK01.json')),'manifest_sha256':sha(read(OLD/'MANIFEST01.json')),'checks':oldread['checks'],'reason':'Complete archive hashes, sizes and committed OIDs unchanged; prior bounded framing/full canonical proofs retained.'},'original_selection01_remains_withheld':True,'external_recovery':False,'Source339_actual_flat':False,'final_caller_release':False,'runtime_body_or_empirical_recovery':False,'numerical_authority':False};(O/'READBACK01.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');(O/'COMMITTED_BODY_JOINS01.json').write_text(json.dumps(joins,sort_keys=True,indent=2)+'\n');print(json.dumps({'checks':len(checks),'decision':x['decision'],'unique_oids':x['unique_Git_objects']}))
