import copy,hashlib,importlib.util,json,os,stat,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;PARENT=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-root-launch-20261004-01');A=F/'financial-genuine-wrapper-claimedrun-parent-preparation01-2026-10-04';V=F/'financial-genuine-wrapper-claimedrun-parent-review01-2026-10-04';REC=F/'financial-genuine-wrapper-claimedrun-source339-actual-flat-review01-2026-10-04';SOURCEPROOF=F/'financial-genuine-wrapper-claimedrun-actual-admission-review01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
sys.path.insert(0,str(PARENT));spec=importlib.util.spec_from_file_location('actual_parent_definitions_only',PARENT/'parent01.py');P=importlib.util.module_from_spec(spec);spec.loader.exec_module(P)
def read(p):return P.R.read(p.parent,p.name)
raw=read(PARENT/'REQUEST_PROPOSAL02.json');ck(sha(raw)=='ec75df7b63dbdf5d4e2982a95e6bda29b423dd95cc82dd02485681ca1b7f819a','exact actual Root proposal');q=json.loads(raw);before=P.R.scan(PARENT);S=Path(q['capsule_root']);sm=json.loads(read(F/'financial-genuine-wrapper-root-claimedrun-source339-capture01-2026-10-04/source-manifest.json'));P.R.same(S,sm);ck(q['final_review'] is None and q['status']=='RELEASED_ONE_USE_FINANCIAL_PARENT','actual unreleased finalreviewnull');ck(sha(read(V/'MANIFEST01.json'))=='034d5977ba0327a425fb4d99ebf7deda3fec78ab55ff1fd7a971c2cf9ec34f71','original independent caller review');ck(read(PARENT/'parent01.py')==read(A/'parent01.py') and sha(read(PARENT/'parent01.py'))==q['caller_sha256']=='5d5cbdae455c62c3e66b53208b0f79e6e5bbc7ce05d3ded77126da5e0692deda','exact actual accepted installed caller')
for n,pin in q['helper_hashes'].items():ck(sha(read(PARENT/n))==pin and read(PARENT/n)==read(A/n),'all six unchanged helpers')
proof_pins={};proofdocs={};originals={'full_recovery':REC/'READBACK01.json','independent_source_input_runtime':SOURCEPROOF/'INDEPENDENT_SOURCE_INPUT_RUNTIME01.json','cumulative':S/'fixture_inputs/financial_wrapper_claimedrun01/extension-review19.json'}
for role,ref in q['proofs'].items():
 p=Path(ref['path']);b=P.reference(ref);ck(p.is_relative_to(PARENT/'proofs') and stat.S_IMODE(p.lstat().st_mode)==0o600 and b==read(originals[role]),'genuine proof original/copy/private join '+role);proof_pins[role]=sha(b);proofdocs[role]=json.loads(b);(O/(role.upper()+'_ORIGINAL01.json')).write_bytes(b)
ck(proof_pins=={'full_recovery':'468dac2c06e570a89a30771c3f7e1b8e064e6f27e610acf01edcccf91c9a2825','independent_source_input_runtime':'059232d0f7fc8922cee526a1bd30fef2ecb51ee17103284bcaac18c77e77641c','cumulative':'3268b76971e4e721222707d16d25dfe84e94104779931e647fb4d7a2bf01202e'},'exact three genuine authoritybody pins');ck(sha(read(REC/'MANIFEST01.json'))=='0a4c5540c2b616a49ccc0d2e5b21255c04abc96199cd24d03c963d54ede164fd','complete actual Source recovery evidence seal');ck(proofdocs['full_recovery']['decision']=='COMPLETE_ACTUAL_SOURCE339_BYTE_UNION_ACCEPTED' and proofdocs['full_recovery']['source']==q['source'],'actual Sourcefullrecovery role')
sourceproof=proofdocs['independent_source_input_runtime'];ck(sourceproof['source']==sourceproof['design_source']==q['source']==q['design_source']=='0a2e7639b42b9423b90743feadcda4078aa21816','actual current/design Source339');ck(sourceproof['source_files']==q['source_files'] and sourceproof['input_hashes']==q['input_hashes'] and sourceproof['runtime_mapping']==q['runtime_mapping'],'complete source/input/runtime independent proof joins');ck(sourceproof['actual_metadata_admission']['effective_attempt_budget']==19 and sourceproof['actual_metadata_admission']['global_spent_claims']==1 and sourceproof['actual_metadata_admission']['highest_actual_claim_budget']==18,'metadata19 actualspent1/highestactual18 distinction')
regraw=read(S/q['registration']);ck(sha(regraw)==q['registration_sha256']=='3a20293832fa7ecc5e2821fb27dc940d1a997ab7f2ad373bc28f73e893e8781a','actual committed registration current');reg=json.loads(regraw);exp=reg['experiments'][q['identity']];ck(exp['source_files']==q['source_files'] and len(q['source_files'])==338 and len(reg['experiments'])==12,'exact selected source338+olddefinitions');ck(reg['families'][exp['family']]['attempt_budget']==18 and reg['families'][exp['family']]['prior_attempts']==0,'no basebudget rewrite/refund')
for n,pin in q['source_files'].items():ck(sha(read(S/n))==pin,'every actual338 selectedsource')
for role,ref in exp['inputs'].items():ck(sha(read(S/ref['path']))==ref['sha256']==q['input_hashes'][role],'every actualeight input')
rt=q['runtime_mapping'];ck(rt==json.loads(read(S/exp['inputs']['runtime_mapping']['path'])) and len(rt['distribution_records'])==251 and rt['executable']==sys.executable and rt['prefix']==sys.prefix and rt['python']=='3.13.13','actual runtime basic metadata')
ck(P.stream_hash(Path(sys.executable).resolve(),64*1024**2)==rt['executable_sha256'] and sha(read(S/'uv.lock'))==rt['lock_sha256'],'actual interpreter/lock hashes');seen=set()
for row in rt['distribution_records']:
 p=Path(row['record']);ck(row['name'] not in seen and p.is_relative_to(Path(sys.prefix)/'lib/python3.13/site-packages') and p.name=='RECORD' and p.parent.name.endswith('.dist-info'),'exact251 runtime RECORD metadata path');seen.add(row['name']);ck(P.stream_hash(p,P.R.FILE)==row['record_sha256'],'every actual251 RECORD pin')
j=json.loads(read(S/exp['inputs']['execution_job']['path']));plan=json.loads(read(S/exp['inputs']['wrapper_plan']['path']));resources=j['resources'];ck(plan['experiment']==plan['namespace']==q['identity'] and plan['phase']==q['expected_phase']=='interrupt1' and plan['task']=='classification' and plan['execution']=='eager','fixed actual initialcell/phase');ck(resources['memory_high_bytes']==resources['memory_max_bytes']==3*1024**3 and resources['reserve_bytes']==3*1024**3 and resources['start_reserve_bytes']==6*1024**3 and resources['wall_seconds']==1800 and resources['native_unit_limits']['file_size_bytes']==4*1024**2,'exact native resourcepolicy metadata');ck(resources['disk_paths']==[str(S)] and resources['storage_budget']['root']==str(S) and resources['disk_floor_bytes']==10*1024**3,'whole currentSource watches')
old='financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01';ck(sha(read(S/'research_runs'/old/'claim.json'))=='4c543d71fad5255be61087eaa3619d9e88cbbdc12fa1398bd7fa7fe6fb75c128' and sha(read(S/'research_runs'/old/'failed.json'))=='35158c0ecebfe4dc75203ba87d5372f2f85643c0b5f828a99e17aa28fe79c450','originalspentfailure unchanged');ck({p.name for p in (S/'research_runs').iterdir()}=={old,'.lock'} and not (S/'research_runs'/old/'complete.json').exists(),'exactactual onefailedclaim/no complete');ck(not os.path.lexists(PARENT/'attempt') and not os.path.lexists(S/'research_artifacts') and not os.path.lexists(S/'research_runs'/q['identity']),'all future attempt/native/claim namespaces absent')
def refuse(fn,label):
 try:fn()
 except (ValueError,TypeError,KeyError,FileNotFoundError) as e:checks.append(label);return {'case':label,'type':type(e).__name__,'message':str(e)}
 raise AssertionError('unexpectedacceptance '+label)
refusals=[refuse(lambda:P.validate_release(q),'actual null finalreview refuses')]
for k in q:
 bad=copy.deepcopy(q);del bad[k];refusals.append(refuse(lambda:P.validate_release(bad),'missing exact field '+k))
# Genuine independent release is authored only after exact real evidence checks; no fake admission/OS outcome.
release={'schema_version':1,'decision':'accepted-exact-one-use-financial-parent','contract_sha256':P.contract(q),'proof_sha256':proof_pins,'identity':q['identity'],'source':q['source'],'caller_sha256':q['caller_sha256']};release_raw=P.R.encode(release);fd=os.open(O/'RELEASE01.json',os.O_WRONLY|os.O_CREAT|os.O_EXCL|os.O_NOFOLLOW,0o600)
try:
 offset=0
 while offset<len(release_raw):offset+=os.write(fd,release_raw[offset:])
 os.fsync(fd)
finally:os.close(fd)
valid=copy.deepcopy(q);valid['final_review']={'path':str(O/'RELEASE01.json'),'sha256':sha(release_raw)};ck(P.validate_release(valid)==release,'actual genuine exactsevenfield release purevalidation')
for k,value in [('identity',old),('source','649fb8a11089524aaef7843dffeeb90a3a55ca17'),('expected_phase','resume'),('caller_sha256','0'*64)]:
 bad=copy.deepcopy(valid);bad[k]=value;refusals.append(refuse(lambda:P.validate_release(bad),'oldspent/altered exactcontract '+k+' refuses'))
bad=copy.deepcopy(valid);bad['proofs']['cumulative']['sha256']='0'*64;refusals.append(refuse(lambda:P.validate_release(bad),'cumulative proof change/refund substitution refuses'));bad=copy.deepcopy(valid);bad['attempt_budget_refund']=1;refusals.append(refuse(lambda:P.validate_release(bad),'unregistered refund field refuses'));bad=copy.deepcopy(valid);bad['proofs']['full_recovery']=None;refusals.append(refuse(lambda:P.validate_release(bad),'missing actualfullrecovery refuses'))
ck(P.R.scan(PARENT)==before and read(PARENT/'REQUEST_PROPOSAL02.json')==raw,'actualParent/proposal unchanged');P.R.same(S,sm);ck(not any(n.split('.')[0] in {'numpy','torch','scipy','tradingagents'} for n in sys.modules),'no numerical/research imports');(O/'REQUEST_PROPOSAL_COPY01.json').write_bytes(raw);(O/'ACTUAL_PARENT_MANIFEST01.json').write_bytes(P.R.encode(before));x={'schema_version':1,'decision':'ACCEPTED_EXACT_CLAIMEDRUN_PARENT_CONTRACT_ONLY','proposal_sha256':sha(raw),'contract_sha256':release['contract_sha256'],'release_sha256':sha(release_raw),'caller_sha256':q['caller_sha256'],'source':q['source'],'identity':q['identity'],'proof_sha256':proof_pins,'checks':len(checks),'refusals':refusals,'actual_metadata_budget':19,'actual_global_spent_claims':1,'highest_actual_claim_budget':18,'base_budget':18,'prior_attempts':0,'full_Source339_byte_recovery':True,'full_final_Parent_caller_review_external_recovery':False,'fresh_genuine_admission_called':False,'actual_preflight_called':False,'actual_launch_or_ResearchRun_started':False,'actual_Root_or_Parent_mutated':False,'current_runtime_numerical_API_observed':False,'capacity_or_empirical_authority':False};(O/'READBACK01.json').write_bytes(P.R.encode(x));print(json.dumps({'checks':len(checks),'release':sha(release_raw),'contract':release['contract_sha256']}))
