import copy,hashlib,json,os,shutil,stat,subprocess,sys,time
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=F/'held-consumer-post-outcome-root-capture01-2026-10-03';U=F/'held-consumer-post-outcome-archive-preparation01-2026-10-03';sys.path.insert(0,str(U));import post_outcome01 as W
R=W.R;checks=[];pins=[]
def ck(v,m):
 assert v,m
 checks.append(m)
def read(p,pin=None):
 b=R.read(p.parent,p.name);ck(pin is None or R.digest(b)==pin,'pin '+str(p));pins.append({'path':str(p),'bytes':len(b),'sha256':R.digest(b)});return b
def doc(p,pin=None):return json.loads(read(p,pin))
q=doc(P/'REQUEST_PROPOSAL01.json');ck(R.digest(read(U/'post_outcome01.py'))=='eca351c9bf2d12fe4ae903c9358e2d7acb9c01833bc3a826b59635130ce752ce','source accepted');ck(R.digest(read(U/'recovery04.py'))==W.HELPER_SHA256,'primitive accepted');ck(R.digest(R.encode(q['baseline']))==W.BASELINE_SHA256,'original final950exact');cap=Path(q['baseline']['capsule_root']);parent=Path(q['baseline']['external_root']);ident=W.IDENTITY;run=cap/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/ident;attempt=parent/'attempt'/ident
term=doc(Path(q['evidence']['terminal']['path']),'c88202808f54920409bf36d3d398982d54b3f5ce9ac30dc135bf96b0104b71af');cleanup=doc(Path(q['evidence']['cleanup']['path']),'215b5dab9d43d0b303350fb3e6a0b54f2dc19c7052c679a5e3cb390992ea72ad');guard=doc(run/'guard/final.json',term['actual_guard_final_sha256']);failed=doc(cap/'research_runs'/ident/'failed.json',term['actual_failed_run_sha256']);claim=doc(cap/'research_runs'/ident/'claim.json',failed['claim_sha256']);outer=doc(cap/'fixture_outer'/ident/'terminal.json');parentterminal=doc(attempt/'terminal.json',term['actual_parent_terminal_sha256']);controller=doc(attempt/'controller-exit.json',term['actual_controller_exit_sha256']);intent=doc(attempt/'intent.json');owner=doc(run/'owner.json');child=doc(run/'guard/child_exit.json');observer=doc(run/'observer.json');outercleanup=doc(cap/'fixture_outer'/ident/'cleanup.json');stop=doc(attempt/'native-stop.json',cleanup['separate_original_parent_cleanup_sha256'])
ck(failed['status']==outer['status']==parentterminal['status']==observer['status']=='failed','original genuine failure chain');ck(claim['experiment_id']==failed['experiment_id']==parentterminal['identity']==ident and claim['source']==claim['design_source']==R.SOURCE and claim['registration_sha256']==q['baseline']['registration_sha256'],'actual claim source joins');ck(claim['effective_attempt_budget']==6 and len(claim['inputs'])==33,'actual allowance6 and33inputs');ck(guard['child_exit_code'] is None and guard['cleanup_verified'] is False and child['exit_code']==125 and outercleanup['pid_absence_verified'] is False and outercleanup['unresolved_pid_absence'] is True,'original null/false retained');ck(guard['wall_seconds']==1800 and guard['elapsed_seconds']>1800 and guard['cleanup_unit_properties']['Result']=='timeout' and controller['actual_exit_code']==1 and parentterminal['actual_controller_exit']==1,'actual1800timeout/controllerfailure');ck(parentterminal['semantic_proof'] is None and parentterminal['scientific_publication'] is False and outer['proof'] is None and observer['financial_completion'] is False,'no semantic/financial proof');ck(guard['owner_identity']==owner and cleanup['actual_cgroup']==guard['cgroup']==stop['cgroup'] and cleanup['actual_unit']==guard['unit'],'actual native identity')
for name,pin in failed['output_sha256'].items():read(cap/'research_runs'/ident/'outputs'/name,pin)
ledger=doc(cap/'research_runs'/ident/'outputs/cell-ledger.json');ck([(x['id'],x['status']) for x in ledger]==[('import-target-01','failed'),('import-target-02','unavailable')],'actual stage ledger')
for name,pin in observer['evidence_sha256'].items():read(run/name,pin)
pids={str(intent['parent_pid']),str(controller['pid']),str(owner['supervisor_pid']),str(owner['monitor_pid']),*guard['cpu_thread_readback'].keys()};ck(len(pids)==10 and pids==set(cleanup['actual_pid_absence']) and all(cleanup['actual_pid_absence'].values()),'actual all10 PID origin union');ck(str(child['workload_pid']) in pids,'actual workload covered');ck(all(not Path('/proc',n).exists() for n in pids),'current all10absent');ck(not Path(guard['cgroup']).exists(),'current cgroup absent')
proc=subprocess.run(['systemctl','--user','show',guard['unit'],'--property=ActiveState','--property=SubState','--property=Result','--property=ControlGroup','--property=ExecMainStatus'],stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10);ck(proc.returncode==0 and len(proc.stdout)<65536 and not proc.stderr,'actual readonly unit query');props=dict(line.split('=',1) for line in proc.stdout.decode().splitlines());ck(props==cleanup['unit_properties'] and props['ControlGroup']=='' and props['ActiveState']=='failed','fresh actual unit agrees');(O/'UNIT02.stdout').write_bytes(proc.stdout);(O/'UNIT02.stderr').write_bytes(proc.stderr)
# Both complete current inventories are byte-only; no binary/array parsing.
scopes={};initial={}
for role,root in [('capsule',cap),('external',parent)]:
 manifest=q['current_manifests'][role];ck(R.digest(R.encode(manifest))==q['current_manifest_sha256'][role],'current manifest pin '+role);ck(doc(P/(role+'-current-manifest01.json'))==manifest,'actual supplied manifest '+role);ck(R.scan(root)==manifest,'complete actual scope before '+role);delta=W.subset(q['baseline'][role+'_manifest'],manifest);initial[role]=manifest;scopes[role]={'members':len(manifest['members']),'regular':sum(r['kind']=='file' for r in manifest['members']),'logical_bytes':sum(r.get('bytes',0) for r in manifest['members']),'allocated_bytes':root.lstat().st_blocks*512+sum((root/r['path']).lstat().st_blocks*512 for r in manifest['members']),'subset':delta}
ck(scopes['capsule']['members']==1012 and scopes['external']['members']==35,'actual1012plus35');sourcejoin=R.authenticate_source(cap,q['baseline']);ck(sourcejoin=={'source':R.SOURCE,'committed_source_registration_bodies':205,'registered_inputs':33,'tracked_files':246,'nonGit_files':288},'actual current205/33/sourceGit joins')
# Actual historical claims, not counting a synthetic receipt ledger.
extension=doc(cap/'cumulative-extension04-proposal.json');history=[]
for r in extension['claims']:
 c=doc(cap/'research_runs'/r['experiment']/'claim.json',r['claim_sha256']);t=doc(cap/'research_runs'/r['experiment']/'failed.json',r['terminal_sha256']);ck(t['claim_sha256']==r['claim_sha256'] and t['status']=='failed' and c['experiment_id']==r['experiment'],'retained actual failed priorclaim');history.append(r)
ck(len(history)==4 and extension['cumulative_ceiling']==6,'four prior pluscurrent five actual failures');dependent='original-import-held-publication-failure-20261003-01';ck(not (cap/'research_runs'/dependent).exists() and not (parent/'attempt'/dependent).exists(),'dependent unclaimed/unattempted');ck(not (cap/'research_runs'/ident/'complete.json').exists(),'no complete currentterminal')
# Identify actual stage artifacts without decoding numerical records.
new={r['path']:r for r in q['current_manifests']['capsule']['members'] if r['path'] not in {x['path'] for x in q['baseline']['capsule_manifest']['members']}};stagefiles=[n for n,r in new.items() if r['kind']=='file' and n.startswith('research_artifacts/onchain_representations/')];ck(any(n.endswith('dictionary-import/import-complete.json') for n in stagefiles),'actual dictionary import marker');ck(any(n.endswith('/matching/events-000000000000.bin') for n in stagefiles) and any(n.endswith('/tails/tail-000000000000/records.bin') for n in stagefiles),'retained opaque partial matching/tail bodies');ck(not any('/checkpoints/' in n or '/stream/batches/' in n and not n.endswith('/start.json') for n in stagefiles),'no actual checkpoint or scorebatch bodies')
support={}
for name,ref in q['support_bodies'].items():support[name]=read(Path(ref['path']),ref['sha256'])
launchdir=Path(q['evidence']['terminal']['path']).parent;ck({Path(ref['path']).name for ref in q['support_bodies'].values()}=={p.name for p in launchdir.iterdir()} and len(support)==10,'complete outside launcher directory membership');ck(sum(map(len,support.values()))==50826,'all10outsidebytes');ck(R.digest(support['cleanup_units02_stdout'])==cleanup['actual_unit_stdout_sha256'] and R.digest(support['cleanup_units02_stderr'])==cleanup['actual_unit_stderr_sha256'],'original unit output joins')
# Additional current writer observation: same-user FD links only, no commandlines,
# credentials, process environments or unrelated file contents are read.
roots=[cap,parent,launchdir];writers=[];uncertain=[];processes=0;fds=0;deadline=time.monotonic()+20
for procpath in Path('/proc').iterdir():
 if not procpath.name.isdecimal() or int(procpath.name)==os.getpid():continue
 ck(time.monotonic()<deadline,'bounded writer census')
 try:
  if procpath.stat().st_uid!=os.geteuid():continue
  processes+=1
  for f in (procpath/'fd').iterdir():
   fds+=1;ck(fds<=32768 and time.monotonic()<deadline,'bounded descriptor census')
   try:
    target=os.readlink(f);clean=target.removesuffix(' (deleted)');path=Path(clean)
    if not path.is_absolute() or not any(path.is_relative_to(r) for r in roots):continue
    fields=dict(x.split(':',1) for x in (procpath/'fdinfo'/f.name).read_text().splitlines() if ':' in x);flags=int(fields['flags'].strip(),8)
    if flags&os.O_ACCMODE in (os.O_WRONLY,os.O_RDWR):writers.append({'pid':int(procpath.name),'fd':f.name,'target':target,'flags':flags})
   except FileNotFoundError:pass
   except PermissionError:uncertain.append({'pid':int(procpath.name),'fd':f.name})
 except FileNotFoundError:pass
 except PermissionError:uncertain.append({'pid':int(procpath.name),'fd':None})
(O/'WRITER_WITNESS02.json').write_bytes(R.encode({'writers':writers,'uncertain':uncertain,'processes':processes,'descriptors':fds}));ck(not writers and not uncertain,'no observed remaining sameuser writableFD/uncertain');ck(all(not Path('/proc',n).exists() for n in pids) and not Path(guard['cgroup']).exists(),'final all10/cgroup absence')
for role,root in [('capsule',cap),('external',parent)]:ck(R.scan(root)==initial[role],'whole current mode/body/membership stable after '+role)
for name,ref in q['support_bodies'].items():ck(read(Path(ref['path']),ref['sha256'])==support[name],'outside support stable '+name)
free=shutil.disk_usage(Path(q['output_root']).parent).free;ck(free>=R.FLOOR,'actual10GiBfloor');ck(not os.path.lexists(q['output_root']),'new output identity unreserved');ck(sum(x['logical_bytes'] for x in scopes.values())+sum(map(len,support.values()))+len(read(Path(q['evidence']['terminal']['path'])))+len(read(Path(q['evidence']['cleanup']['path'])))+16384<R.BASE,'logical scope plus conservative review allowance128MiB');ck(sum(x['allocated_bytes'] for x in scopes.values())+sum(Path(ref['path']).lstat().st_blocks*512 for ref in q['support_bodies'].values())+32768<R.BASE,'allocated scope plus evidence allowance128MiB')
review={'schema_version':1,'decision':'accepted-closed-tree-byte-preservation','identity':ident,'source':R.SOURCE,'baseline_sha256':W.BASELINE_SHA256,'current_manifest_sha256':q['current_manifest_sha256'],'terminal_sha256':q['evidence']['terminal']['sha256'],'cleanup_sha256':q['evidence']['cleanup']['sha256'],'processes_absent':True,'cgroup_absent':True,'writer_quiescence_verified':True,'support_sha256':{n:ref['sha256'] for n,ref in q['support_bodies'].items()},'outcome':'FAILED'}
(O/'CLOSED_TREE_REVIEW01.json').write_bytes(R.encode(review));final=copy.deepcopy(q);final['evidence']['closed_tree_review']={'path':str(O/'CLOSED_TREE_REVIEW01.json'),'sha256':R.digest(R.encode(review))};W.request(final);W.evidence(final,{n:W.load_ref(ref) for n,ref in final['evidence'].items()});(O/'REQUEST_REVIEWED01.json').write_bytes(R.encode(final));ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numerical imports');result={'decision':'ACCEPTED_GENUINE_CLOSED_FAILED_SCOPE_FOR_BYTE_CAPTURE_ONLY','checks':len(checks),'scopes':scopes,'sourcejoin':sourcejoin,'all10_pids':sorted(pids),'unit_properties':props,'writer_observation':{'sameuser_processes':processes,'descriptors':fds,'writable_matches':writers,'uncertain':uncertain,'qualification':'bounded contemporaneous observation plus all10/cgroup absence and full stable inventories; no future writer guarantee'},'five_actual_failed_claims':5,'actual_highest_adopted':claim['effective_attempt_budget'],'dependent_case':'UNAVAILABLE_NO_CLAIM','stagefiles':stagefiles,'free_bytes':free,'machine_review_sha256':R.digest(R.encode(review)),'reviewed_request_sha256':R.digest(R.encode(final)),'capture_performed':False,'native_or_scientific_authority':False};(O/'READBACK01.json').write_bytes(R.encode(result));(O/'PINS01.json').write_bytes(R.encode(pins));print(json.dumps({k:v for k,v in result.items() if k!='stagefiles'},indent=2))
