import pathlib,json,hashlib,runpy,ast,types
D=pathlib.Path(__file__).parent;P=D.parent/'neural-cold-feature-handoff-held-consumer-fixture-successor-preparation01-2026-10-03';G=runpy.run_path(str(P/'generate_inputs01.py'));H=lambda b:hashlib.sha256(b).hexdigest();R=pathlib.Path('/synthetic-review-only')
source={'source_count':199,'package_count':148,'execution_admitted':False,'source':'1'*40,'anchor':'2'*40,'root':str(R),'source_files':{'uv.lock':'a'*64},'package_files':{'synthetic.py':'a'*64}}
def ref(p):return {'path':p,'sha256':'a'*64,'bytes':1}
def role(name,doc):return {'reference':ref(name+'.json'),'document':doc}
original={'inputs':[{'name':'original_node_ids' if i==0 else 'original_'+str(i),'reference':ref('old/'+str(i)+'.json'),'original_path':'original/'+str(i)} for i in range(11)],'original_source':'3'*40,'original_claim':'saved-original'}
def targets(first='graph0'):
 return [{'graph_hash':h*64,'nodes':n,'input_name':name,'manifest':ref(name+'/manifest.json'),'components':{k:ref(name+'/'+k+'.npy') for k in ('node_ids','node_features','edge_index','edge_features')}} for h,n,name in [('a',2,first),('b',3,'graph1')]]
roles={'original_import_index':role('original',original),'target_catalog':role('targets',{'schema_version':1,'kind':'registered-imported-held-targets-v1','targets':targets('original')})}
result=G['held_input_plan'](roles,source);assert len(result['input_rows'])==20 and result['input_rows']['original_node_ids']['path']=='original/node_ids.npy' and result['input_rows']['original_node_ids']['dataset']=='synthetic'
print('HFS1: original11+target10 silently becomes20; original_node_ids overwritten by generated target component role')
case={'schema_version':1,'kind':'root-selected-imported-held-resource-v1','program_id':'synthetic-program','experiment_id':'future-review-only','job_input':'job','plan_input':'plan','representation':'rep','producer':'prod','held_policy_input':'ABSENT_HELD_POLICY','readback_outputs':{'a'*64:'a.json','b'*64:'b.json'},'additional_inputs':{n:{'reference':ref(n+'.json'),'dataset':'synthetic'} for n in ('job','plan','pair','control','env')}}
native={'memory_max_bytes':3*1024**3,'memory_high_bytes':3*1024**3,'reserve_bytes':3*1024**3,'start_reserve_bytes':6*1024**3,'disk_floor_bytes':10*1024**3,'wall_seconds':1800,'native_unit_limits':{'file_size_bytes':4194304},'disk_paths':[str(R)],'storage_budget':{'root':str(R)}}
roles.update(target_catalog=role('targets',{'schema_version':1,'kind':'registered-imported-held-targets-v1','targets':targets()}),case_contract=role('case',case),native_policy=role('native',native),software_environment=role('software',{}))
selected={'plan_input':'plan','producer':'prod','descriptor':{'dictionary_origin':'imported-original-v1','required_graphs':['a'*64,'b'*64]},'held_score_consumer_input':'ABSENT_HELD_POLICY','pair_checkpoint_input':'pair','original_dictionary_input':'control'}
docs={v['reference']['path']:v['document'] for v in roles.values()};docs.update({'job.json':{'schema_version':1,'kind':'compact_resource','resources':native,'environment_input':'env','payload':{'representation_jobs':{'rep':selected}}},'plan.json':{'schema_version':2,'producers':{'prod':{'descriptor':selected['descriptor'],'held_score_consumer_input':'ABSENT_HELD_POLICY'}}},'pair.json':{'numerical_source':{'commit':source['anchor'],'files':source['package_files']}},'control.json':{'kind':'original-dictionary-import-v1','sample_count':512,'motif_count':32,'original_source':'3'*40,'original_claim':'saved-original'}})
reads=[]
def document(root,row):reads.append(row['path']);return json.dumps(docs[row['path']]).encode()
builder=types.SimpleNamespace(__file__=str(R/'fixture_tools/capsule_builder01.py'),held_source_plan=lambda *a:source,held_document=document)
generator=types.SimpleNamespace(__file__=str(R/'fixture_tools/generate_inputs01.py'),HELD_ROLES=G['HELD_ROLES'],held_input_plan=G['held_input_plan'])
t=ast.parse((P/'build_release_draft01.py').read_text());f=next(x for x in t.body if isinstance(x,ast.FunctionDef) and x.name=='held_metadata_draft');f.body=[x for x in f.body if not isinstance(x,ast.ImportFrom)];ns={'builder':builder,'generator':generator,'Path':pathlib.Path,'require':G['require'],'json':json,'__file__':str(R/'proof_tools/build_release_draft01.py')};exec(compile(ast.Module(body=[f],type_ignores=[]),'actual-held-draft-with-synthetic-source-and-byte-reader','exec'),ns)
out=ns['held_metadata_draft'](R,source['source'],source['anchor'],[],{k:v['reference'] for k,v in roles.items()});assert out['route_readback']['kind']=='authenticated-metadata-only-imported-route' and case['held_policy_input'] not in out['input_plan']['input_rows'] and 'ABSENT_HELD_POLICY' not in reads
print('HFS2: actual held_metadata_draft returns authenticated-metadata-only-imported-route while selected held policy input is absent and never read/joined to rendered policy')
print(json.dumps({'counterexamples':2,'qualification':'Actual generator and AST-extracted draft; synthetic source/metadata reader stand-ins, no original arrays/authority/claims/execution. Both results remain draft-not-released; defect is accepted incomplete/misbound metadata, not claimed admission.'},indent=2))
