from pathlib import Path
import ast,hashlib,json,os,stat,sys
D=Path(__file__).resolve().parent
h=lambda b:hashlib.sha256(b).hexdigest()
def put(n,o):(D/n).write_text(json.dumps(o,sort_keys=True,indent=2,allow_nan=False)+'\n')
q=json.loads((D/'READBACK02.json').read_bytes());c=json.loads((D/'CONTROLS01.json').read_bytes());cfg=json.loads((D/'INPUTS01.json').read_bytes());source=(D/'verify01.py').read_bytes();ast.parse(source);assert sys.version_info[:3]==(3,13,13)
refs={x['path']:x for x in q['recovery_receipts']};rows=[]
for p,x in refs.items():
 b=Path(p).read_bytes();assert h(b)==x['sha256'];rows.append({**x,'bytes':len(b)})
put('RECOVERY_RECEIPT_CANDIDATES01.json',{'schema_version':1,'status':'EXACT_ACTUAL_REFERENCE_INVENTORY_NOT_PROOF','references':rows,'distinct_referenced_bytes':sum(x['bytes'] for x in rows),'largest_reference_bytes':max(x['bytes'] for x in rows),'scope':'Actual source-policy recovery evidence references only; final preclaim and Parent input union must be measured independently under unchanged 8MiB total and4MiB single-file limits. A receipt subset is not itself full recovery.'})
put('PROOF_INTERFACE01.json',{'schema_version':1,'status':'REQUIREMENTS_ONLY_NO_ACTUAL_PROOF_ISSUED','required_proof_field_names':['schema_version','kind','decision','policy_sha256','checker_sha256','historical_map_sha256','target_map_sha256'],'required_role':'operational_source_compatibility_recovery','required_policy_sha256':q['policy_sha256'],'required_checker_sha256':q['checker_sha256'],'required_historical_map_sha256':q['historical_map_sha256'],'required_target_map_sha256':q['target_map_sha256'],'required_actual_machine_decision':'ACCEPTED_ACTUAL_OPERATIONAL_SOURCE_POLICY_BYTE_RECOVERY','required_actual_machine_fields':['schema_version','decision','policy_sha256','checker_sha256','historical_map_sha256','target_map_sha256','recovery_proof_sha256','report_sha256','recovery_receipts'],'required_recovery_receipt_descriptor_fields':['path','sha256'],'independent_review_requirements':['Different-author substantive review of this checker and actual composed bytes, not acceptance based on a decision string.','Every cited original receipt or literal copy must be hash-authenticated and a regular member of the final typed reviewer manifest; copies must join original path/hash.','Authenticate source pins, complete589 composition, original385Git plus exact9 new logical objects, genuine narrow predecessor decisions and actual flat/Root outcomes.','Retain original source/checkpoint provenance, three FAILED/spent identities/highest19, original775 selected directories and historical NULLs.','Root separately measures final complete preclaim metadata union, registers actual proofs, and supplies later complete finalCAP/gate/caller/contract supplement.'],'actual_recovery_proof':None,'actual_operational_recovery_machine':None,'actual_registration':None,'actual_numerical_release':None})
report=f'''# Composed source-policy recovery checker preparation

PREPARED_CHECKER_ACTUAL_COMPOSITION_OBSERVED_NO_PROOF. The frozen stdlib verifier independently joined actual bytes after the single Root flat05 invocation and its genuine narrow outcome review a0c19210/1f3e7209. It creates no files when invoked, executes no restoration or Git process, imports no scientific package, and emits no accepted proof. Root must obtain a different-author substantive review before composing or installing the actual operational recovery proof. Final Parent/caller/registration recovery remains separate.

The current source7b056 has589 exact typed non-Git members. All585 protected members retain original names/types/modes/bytes from the accepted failed588 capsule; four changed source bodies join the actual new flat delta. The complete historical194 and target195 maps match the concrete ae8f policy and af61 closure,191 original implementation bodies remain equal, and150 target package bodies are present. Historical parent claim/FAILED/checkpoint manifest and opaque state223c rejoin the complete old provenance without checkpoint deserialization. All three original claims remain FAILED/spent/highest19. No100epoch completion, reference credit, budget amendment, new identity or scientific authority is inferred.

Actual recovered385 logical Git bodies plus nine recovered new objects have valid type/length/SHA256/GitOID joins. An independent stdlib commit/tree traversal establishes the exact394 reachable-object denominator and340 tracked path/body/mode-class joins to the current source. This is logical object composition, not a reconstructed POSIX Git store or a new fsck result. The original385 recovery acceptance remains independently pinned.

The two new flat populations contain64 original bodies and two physical metadata files,83 declared typed descendants. Canonical gzip/PAX regeneration reproduces both original archives. All old failed-scope archives and three old Git-object shard archives are likewise reconstructed from actual flat bytes. Exact old588 capsule membership, original failedRoot43 metadata,31 failedRoot bodies, original failure7491/observedinitNULL/separatereaped0/outer1, and all22 delta-origin paths/modes remain literal. The selected7 directories retain actual0700/0775 modes and15files retain0600; no writer-exclusion or private0700 claim is made for the completed selected hierarchy. Fresh flat output remains0700/0600.

The installed source17f4/profiled238/dependencies, exact caller025a, entry18d36, actual remote64c745/selectiond2f64/55 operations, actual flate702/sidecar72c910/Rootd395 zero exits, raw streams and narrow actual-outcome machine/report/seal all join. The original flat receipt actual_root_exit=NULL remains distinct from later Root0. Parent FSIZE readback is4MiB; default child inheritance has no separate child readback claim. Recorded flat PID/group is absent. Current receiver sampled allocation/membership/floor and historical bounded samples satisfy unchanged64MiB logical/96MiB allocated/4MiB file/32768 members/10GiB floor; this is no continuous quota or full scientific capacity result.

Final readback visited{q['files_read']} distinct files/{q['bytes_read']:,} bytes. Checker limits are4MiB per read,256MiB cumulative unique input bytes,32768 tracked members/anchors and180seconds; these are read-only verification bounds and do not amend any source/runtime/preclaim cap. All read descriptors and scandir iterators close before the final whole-reader path/type/owner/mode/signature and complete namespace rejoins. The guarantee is sampled currentness, excluding same-signature ABA/atomicity/kernel quotas.

Thirty-seven owned opaque controls passed, including real FD closure, first fatal and secondary close object preservation, late-close mutation of an earlier body, stale cached content, foreign namespace, symlink/FIFO/hardlink refusal, byte/deadline limits, original versus private modes, canonical archive tails and missing/extra reachable Git objects. These primitive engineering controls do not issue an Admission, Run, Root authority or actual recovery outcome.

The prospective receipt inventory has{len(rows)} distinct original paths/{sum(x['bytes'] for x in rows):,} bytes, largest{max(x['bytes'] for x in rows):,}. This is only a measured reference subset. The separately reported4,124,892 bytes for two actual source-path traversals plus this subset are not the final complete8MiB preclaim union; remaining policy/roles/proofs/finalParent/external joins still require Root's exact measurement. Each reference is an original file; a final reviewer must seal originals or authenticated literal copies. No field omission or cap increase is authorized.

Preserved errors: original caller04 preparation remains separate from permanently withheld caller04; the real missing-flat refusal predates Root's successful invocation. Actual-composition attempt01 retained a KeyError from expecting caller04's child-FSIZE field; source was corrected to caller05's actual parent-readback field and explicit unobserved child inheritance. Attempt04 retained a KeyError from expecting checkpoint member `bytes`; genuine manifest uses `size`. Both failed source versions and all raw stdout/stderr remain. No source/input/outcome was replaced to satisfy a check.

Not tested or claimed: financial timing/return/exposure/fees/funding performance, arrays or state decoding, installed dependency/runtime bodies, unrelated stores, POSIX source reconstruction, complete runtime capacity, finalCAP/gate/caller supplement, final preclaim eligibility, policy/proof registration, financial admission or a new numerical launch. No network or actual helper entry was invoked.

Invocation: use the pinned repository `.venv/bin/python -B` with this directory's `verify01.py`; default is the complete read-only composition check. `--prerequisites-only` emits a narrower observation, never recovery. All required actual outcomes and peer evidence are now pinned in INPUTS01; absent or changed files refuse. Historical prepare/refine/freeze scripts are retained audit artifacts and must not be re-executed over this frozen directory.
'''
(D/'REPORT01.md').write_text(report)
put('MACHINE01.json',{'schema_version':1,'decision':'PREPARED_CHECKER_ACTUAL_COMPOSITION_OBSERVED_NO_PROOF','source_sha256':h(source),'inputs_sha256':h((D/'INPUTS01.json').read_bytes()),'readback_sha256':h((D/'READBACK02.json').read_bytes()),'report_sha256':h((D/'REPORT01.md').read_bytes()),'controls_sha256':h((D/'CONTROLS01.json').read_bytes()),'opaque_controls':len(c['rows']),'policy_sha256':q['policy_sha256'],'checker_sha256':q['checker_sha256'],'historical_map_sha256':q['historical_map_sha256'],'target_map_sha256':q['target_map_sha256'],'closure_sha256':q['closure_sha256'],'source_commit':q['source'],'current_typed':589,'protected_typed':585,'old_git_objects':385,'new_git_objects':9,'reachable_objects':394,'tracked':340,'implementation_paths':195,'package_paths':150,'original_failed_claims':3,'highest_actual_allowance':19,'actual_two_scope_outcome_review_sha256':'a0c19210a486194de02dc43631c64e40e9c6ae9e688b423496de230d801d7685','receipt_reference_count':len(rows),'receipt_reference_bytes':sum(x['bytes'] for x in rows),'actual_recovery_proof':None,'actual_complete_recovery_review':None,'numerical_authority':False,'registration_mutated':False,'actual_restoration_invoked':False,'checkpoint_deserialized':False,'network':False})
# Complete typed evidence seal: negative fixtures retain FIFO/symlink/hardlink/sparse metadata rather than being opened blindly.
manifest=[]
for root,ds,fs in os.walk(D,followlinks=False):
 for name in ds+fs:
  p=Path(root)/name
  if p.name=='MANIFEST01.json' and p.parent==D:continue
  st=p.lstat();x={'path':p.relative_to(D).as_posix(),'mode':stat.S_IMODE(st.st_mode),'nlink':st.st_nlink}
  if stat.S_ISDIR(st.st_mode):x['kind']='directory'
  elif stat.S_ISLNK(st.st_mode):x.update(kind='symlink',target=os.readlink(p))
  elif stat.S_ISFIFO(st.st_mode):x['kind']='fifo'
  elif stat.S_ISREG(st.st_mode):
   digest=hashlib.sha256()
   with p.open('rb') as f:
    for chunk in iter(lambda:f.read(65536),b''):digest.update(chunk)
   x.update(kind='file',bytes=st.st_size,sha256=digest.hexdigest())
  else:raise ValueError('unexpected fixture type')
  manifest.append(x)
put('MANIFEST01.json',{'schema_version':1,'manifest_self_excluded':True,'qualification':'Complete preparation seal, including explicit adversarial FIFO/symlink/hardlink/sparse fixtures; not an archival restore manifest.','members':sorted(manifest,key=lambda x:x['path'])})
print(json.dumps({n:h((D/n).read_bytes()) for n in ['verify01.py','INPUTS01.json','READBACK02.json','MACHINE01.json','REPORT01.md','MANIFEST01.json']},sort_keys=True))
