from pathlib import Path
import hashlib,json,os,stat
H=Path(__file__).resolve().parent;P=H.parent/'financial-wrapper-compatibility-root-policy01-2026-10-04';S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');sha=lambda b:hashlib.sha256(b).hexdigest();canon=lambda o:json.dumps(o,sort_keys=True,separators=(',',':'),allow_nan=False).encode()
def save(n,v):(H/n).write_text(json.dumps(v,sort_keys=True,indent=2)+'\n')
assert not (H/'MANIFEST01.json').exists();pins=json.loads((H/'ROOT_PINS01.json').read_bytes());readback=[]
for n,pin in pins.items():assert sha((P/n).read_bytes())==pin;readback.append({'path':str(P/n),'sha256':pin,'passed':True})
policy=json.loads((H/'POLICY01.json').read_bytes());proof=json.loads((H/'REVIEW_PROOF01.json').read_bytes());proofpin=sha((H/'REVIEW_PROOF01.json').read_bytes())
for rel,pin in policy['target']['installed'].items():assert sha((S/rel).read_bytes())==pin;readback.append({'path':str(S/rel),'sha256':pin,'passed':True})
for n in ('CHECK02.err','PROOF01.err'):assert (H/n).read_bytes()==b''
assert json.loads((H/'CHECKS01.json').read_bytes())['checks']==1644 and len(json.loads((H/'PROOF_CHECKS01.json').read_bytes())['rows'])==9
report='''# Independent concrete operational-policy review

ACCEPTED_EXACT_CONCRETE_POLICY_ONLY. POLICY01.json ae8fbdc9d13e75fc453b70b5ee633c89fb4577e9b68a35b4147cf1bbd58c6887 is consistent with the accepted operational-source bridge and the authentic historical parent. REVIEW_PROOF01.json is the genuinely different-author seven-field review document for this exact policy/helper/full-map tuple. It is a review artifact only. No recovery proof was created, and no policy, proof, gate, allowance or numerical release was installed by this review.

The actual installed helper d0d770b45def89e8e00e81fa1bbb35416034eaace5ecab0f15193fd43b7a32d8 independently validated the concrete policy using its pure validate_contract predicate. The complete candidate-review and actual-source-adoption review manifests were authenticated member by member. Source7b056a574e3e7b3c7ba209a39ee6a615e649d60c was observed as the direct child of9dc5 in the same genuine root. Every one of194 historical bodies was read from the authentic0a2 Git commit; every one of195 target bodies matched both current working bytes and its7b056 committed blob. Exactly191 original bodies remain equal. The maps contain193 and194 distinct hashes respectively; the complete path maps, not only hash sets, are bound.

The six concrete historical aliases independently rejoined actual same-root claim d390980c, FAILED terminal4b2d7b0d, checkpoint manifestb2f7d33b, original source closure, job and plan. Every alias retains its exact original path, extent and SHA256. The actual checkpoint provenance equals the complete historical policy provenance byte-for-value, with source0a2e7639b42b9423b90743feadcda4078aa21816 and all193 original source hashes. Its sole493424-byte state member hashes to223ced42edec29ec0afd4ea5265b2e0a557a98787e57be47e841e8491511a281; state bytes were only hashed and were not decoded or copied. The claim remains FAILED without a COMPLETE terminal.

The concrete consumers are exactly the fixed classification/eager complete100, continue100 and predict compatibility identities dated20261004-01. Each identity's lifecycle, native-job, wrapper and fit namespaces was absent in the genuine CAP and Main at observation. This is a bounded current namespace check, not a claim about all possible external roots. The new reference cell is absent. Continuation and prediction intentionally retain financial-wrapper-classification-eager-continued-20261003-01, whose fit directory contains only the original failed one-update parent. That shared historical cell is not described as unused, and no old experiment identity is reopened. The future replacement reference remains unavailable until genuinely COMPLETE and independently admitted/recovered.

Original model20f451/trainingd527/recipe bytes remain authentic. Scientific/tolerance AST outside the declared metadata wrappers is identical between original0a2 and target; training fit/predict, generic checkpoint/cache/financial-execution/evaluation bodies retain their exact semantics. Frozen100epochs, batch16, seed11, lookback28, F32 atol1e-6/rtol1e-5 and exact controls are unchanged. Source inspection confirms strict genuine source/design checks, source-pinned policy/proofs, full target-body checks, directional historical provenance comparison and prediction same-policy/full-map/cell guards. No-role legacy behavior still grants no operational bridge authority; final registration must bind this identical explicit policy to all three named consumers.

There were1644 passing independent source, historical-byte, policy, namespace and refusal checks, followed by9 exact seven-field proof-predicate controls. The authentic helper predicate refused wrong historical claims/source/maps, incomplete deltas/proofs, unresolved/historical consumer identities and laundering/direction/cell changes. The actual source-extracted proof predicates accepted only the correctly bound review document and refused each null field and substitution of the recovery role. The original check01.py missing closing bracket produced a SyntaxError before executing any check; its source and raw stderr are retained. check02.py contains the correction and passed. This was a reviewer harness defect, not a policy failure.

The seven proof fields bind policy ae8fbdc9, historical canonical map ebb1727c, target canonical map2e281f7c and helperd0d770. Their exact full hashes are in REVIEW_PROOF01.json and MACHINE01.json. An accepted label does not prove recovery; the independently sealed report/checks explain this review's authorship and scope. The Root binding's source_adoption_review_pending flag is a retained pre-review documentary snapshot; separately authenticated actual-source-adoption reviewe0a39ef/3a5ebab supplies the later source-only decision. No change to that Root snapshot was made.

Genuine Run/Admission/Owner construction, registration or claim creation, runtime preclaim integration, state decoding, numerical continuation/agreement, fees/funding/return claims and external transport/recovery were not performed. Final registered role deduplication, exact committed policy/proof/source/gate/caller, same-family budget adoption, complete external preservation/recovery and native release remain Root prerequisites. This acceptance creates no budget refund, new paper authority, successful reference or numerical-launch authorization.
'''
(H/'REPORT01.md').write_text(report)
save('READBACK01.json',{'checks':len(readback),'rows':readback})
machine={'schema_version':1,'decision':'ACCEPTED_EXACT_CONCRETE_POLICY_ONLY','reviewer':'Independent research-reviewer /root/storage_watch_review; policy author /root','policy_sha256':pins['POLICY01.json'],'checker_sha256':proof['checker_sha256'],'historical_map_sha256':proof['historical_map_sha256'],'target_map_sha256':proof['target_map_sha256'],'closure_sha256':pins['SOURCE_CLOSURE01.json'],'review_proof_sha256':proofpin,'actual_adopted_source_observed':'7b056a574e3e7b3c7ba209a39ee6a615e649d60c','historical_source':'0a2e7639b42b9423b90743feadcda4078aa21816','actual_source_adoption_review_manifest':'e0a39ef23d7b3624249e769b7f0bc2bec6a6c20028a48a393780e5f6ca19a915','candidate_review_manifest':'6d61d65f528a1db42fead75f70062acff1599aa571af1d1f09746302c3538e5e','checks':{'source_metadata_policy':1644,'proof_predicate':9,'final_current_readback':len(readback)},'consumers':policy['consumers'],'historical_paths':194,'target_paths':195,'original_equal_bodies':191,'historical_state_hashed_only':True,'checkpoint_deserialized':False,'genuine_runtime_objects_constructed':False,'numerical_packages_imported':False,'policy_installed_by_review':False,'review_proof_installed_by_review':False,'actual_recovery_proof':None,'actual_gate_adoption':None,'actual_budget_adoption':None,'actual_native_release':None,'scope':'Exact policy/source-map consistency and independently authored review proof; no recovery, admission, runtime/numerical result or budget authority.','retained_reviewer_error':'check01.py SyntaxError missing closing bracket before any execution; corrected check02 passed','report_sha256':sha((H/'REPORT01.md').read_bytes())}
save('MACHINE01.json',machine)
rows=[];excluded={'MANIFEST01.json','FREEZE01.out','FREEZE01.err'}
for root,dirs,files in os.walk(H,followlinks=False):
 for name in dirs+files:
  p=Path(root)/name;rel=str(p.relative_to(H))
  if rel in excluded:continue
  st=p.lstat();r={'path':rel,'mode':stat.S_IMODE(st.st_mode),'links':st.st_nlink}
  if stat.S_ISREG(st.st_mode):assert st.st_size<=4194304;r.update(kind='file',bytes=st.st_size,sha256=sha(p.read_bytes()))
  elif stat.S_ISDIR(st.st_mode):r.update(kind='directory')
  elif stat.S_ISLNK(st.st_mode):r.update(kind='symlink',target=os.readlink(p))
  else:raise AssertionError(rel)
  rows.append(r)
rows.sort(key=lambda r:r['path']);save('MANIFEST01.json',{'schema_version':1,'decision':machine['decision'],'scope':'Complete independent concrete-policy review tree','exclusions':sorted(excluded),'members':rows,'typed_members':len(rows),'regular_files':sum(r['kind']=='file' for r in rows),'regular_bytes':sum(r.get('bytes',0) for r in rows)})
print(json.dumps({'manifest_sha256':sha((H/'MANIFEST01.json').read_bytes()),'machine_sha256':sha((H/'MACHINE01.json').read_bytes()),'report_sha256':sha((H/'REPORT01.md').read_bytes()),'review_proof_sha256':proofpin,'members':len(rows),'regular_bytes':sum(r.get('bytes',0) for r in rows)}))
