from pathlib import Path
import json,hashlib,stat
H=Path(__file__).resolve().parent;B=H.parent;C=B/'heartbeat-root-checkpoint10-2026-10-04';V=B/'financial-wrapper-compatibility-gate-preview-source-review01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();r=json.loads((H/'READBACK01.json').read_bytes())
for root,n,prefix in [(C,n,'source') for n in ['root_compatibility_gate_preview01.py','root_compatibility_gate_preview02.py','ROOT_GATE_PREVIEW02_SOURCE_INVERSE01.json','ROOT_GATE_PREVIEW02_SOURCE_DIFF01.patch']]+[(V,n,'prior-review') for n in ['MACHINE01.json','MANIFEST01.json','REPORT01.md','WITNESSES01.json','FINDINGS01.json']]:
 p=H/'evidence'/prefix/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes((root/n).read_bytes())
report='''# Gate preview02 source-only review

**Accepted narrow GP1/GP2 source correction. No public preview or adoption/entry release.** Exact source8edbfb20 and12-segment inverse reconstruct original845e7445 byte-for-byte and AST-identically. Original GP1/GP2 review and its witnesses remain unchanged.

GP1: draftedd6e8 and binding1a7685 now have fixed source literals, and the entire thirteen-name prepared directory has exact fixed hashes. The script checks these before output and repeats each body pin on the assembly read. Independent extracted genuine predicates accept byte-identical owned copies and refuse coherent epochs100→99, seed11→12, eager→selected, dropped cumulative extension and foreign-family drift. The original exact post-authority assembly still accepts those same five corruptions in a paired control. No proof parser or public preview was invoked: its skipped component uses an in-memory explicitly opaque non-proof marker, and no assembled gate or marker authority body is written.

GP2: complete research_runs namespace is bound to three original identities plus.lock; all six actual claim/failed bodies are pinned. Program/family/base18/prior0/identity/failed→claim SHA and absent COMPLETE checks pass on genuine historical metadata. Maximum effective allowance is derived as19 from the actual bodies, with spent3. Owned corrupted-copy controls refuse budget refund, identity/program changes, missing failure, contradictory COMPLETE presence and an extra empty identity directory. These are deliberately corrupted copies of authentic old metadata, not new genuine claims. Binding-level refund and independent body-only drift also refuse.

Positive actual source/metadata joins: current CAP7b056 tracked-clean,340 existing tracked paths, old gate752c with12 preserved definitions, all195 target source bodies. Thirteen prepared files plus a future genuine recovery role file plus new gate give15 new files,355 prospective tracked paths and354 source pins excluding only the new gate. Original complete100 parentNone/reference cell/phase/eager route and eleven prospective roles remain. Original model20f451/trainingd527/100epochs/batch16 and synthetic recipe seed11/batch16/lookback28 remain exact. Three spent claims plus17 pending original phases require prospective20; existing19 yields16 remaining allowances. Nothing adopts20 or refunds/aliases an old claim.

This source review executes only extracted pure encoding, preparation-pin/history predicates and original in-memory assembly controls. It never creates accepted proof fields, invokes public preview, writes a gate, imports numerical dependencies or executes Admission/Owner/Run. Actual new fixture and prospective identity namespaces remain absent. Genuine composed-recovery acceptance is currently withheld for checker cleanup defects, so preview02 is not executable merely because this correction is source-accepted. The future proof/machine/report/manifest/descendant receipt checks were inspected, not bypassed or dynamically satisfied with invented authority.

No guarantee of concurrent writer exclusion, continuous source currentness, successful public output publication, actual gate/API admission, empirical timing/returns/fees/funding, runtime preservation or numerical capacity follows. Root must provide genuinely accepted recovery, invoke only the separately authorized preparation, preserve partial outcomes, then obtain exact generated-gate/source/admission/final caller review. All original financial failures and1420 pending paper fits remain unchanged.
'''
(H/'REPORT01.md').write_text(report)
m={'schema_version':1,'decision':'ACCEPTED_SOURCE_ONLY_GATE_PREVIEW02_GP1_GP2_CORRECTION','source_sha256':sha((C/'root_compatibility_gate_preview02.py').read_bytes()),'original_source_sha256':sha((C/'root_compatibility_gate_preview01.py').read_bytes()),'literal_inverse_segments':12,'assertions':r['assertions'],'cases':len(r['cases']),'actual_highest':19,'actual_spent_failed':3,'base_attempt_budget':18,'prior_attempts':0,'remaining_original_phases':17,'existing_remaining_allowances':16,'prospective_allowance':20,'allowance_adopted':False,'source_pins_prospective':354,'tracked_prospective':355,'prepared_bodies':13,'new_files_prospective':15,'reference_roles_prospective':11,'original_gate_definitions_preserved':12,'public_preview_invoked':False,'actual_recovery_proof':None,'actual_gate_adopted':False,'numerical_authority':False,'readback_sha256':sha((H/'READBACK01.json').read_bytes()),'report_sha256':sha((H/'REPORT01.md').read_bytes()),'qualification':'Bounded source/metadata acceptance only; genuine composed recovery is still withheld and no proof/public preview/adoption/research release is authorized.'}
(H/'MACHINE01.json').write_text(json.dumps(m,indent=2,sort_keys=True)+'\n');rows=[]
for p in sorted(H.rglob('*')):
 if p==H/'MANIFEST01.json':continue
 s=p.lstat();z={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):z['kind']='directory'
 elif stat.S_ISREG(s.st_mode):z.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()))
 else:raise AssertionError(p)
 rows.append(z)
(H/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'members':rows,'exclusion':'self only; all genuine original-byte copies and explicitly corrupt negative controls retained'},indent=2,sort_keys=True)+'\n');print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'readback':m['readback_sha256'],'report':m['report_sha256'],'members':len(rows),'bytes':sum(z.get('bytes',0) for z in rows),'assertions':r['assertions'],'cases':len(r['cases'])}))
