import ast,hashlib,json,os,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-native-20261003-01/source');A=F/'financial-genuine-wrapper-root-initial-input-adoption01-2026-10-04';G=F/'financial-genuine-wrapper-registration-preparation01-2026-10-04/generated03';P=F/'financial-genuine-wrapper-root-gate-preparation01-2026-10-04';H='1a8c612d5d66858c725f9196e80b2140b9e6fc81';BASE='868bfa6404a2c34d6e5b6e0932a2baf4b38eb370';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
def sig(s):return (s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns)
def read(p):
 s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4*1024**2 and p.resolve()==p,'canonical bounded input');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW)
 try:
  ck(sig(os.fstat(fd))==sig(s),'opened actualinode');parts=[];count=0
  while True:
   b=os.read(fd,65536)
   if not b:break
   count+=len(b);ck(count<=s.st_size,'bounded extent');parts.append(b)
  ck(sig(os.fstat(fd))==sig(s)==sig(p.lstat()) and count==s.st_size,'unchanged actualbody');return b''.join(parts)
 finally:os.close(fd)
def doc(p,pin=None):
 b=read(p);ck(pin is None or sha(b)==pin,'pin '+p.name);return json.loads(b)
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never','-C',str(S),*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'bounded offline Git');return r.stdout
ad=doc(A/'ADOPTION01.json');current=doc(A/'CURRENT_SOURCE_MAP01.json');prior=doc(F/'financial-genuine-wrapper-installed-expectation-review01-2026-10-04/READBACK01.json','654c84e1c98110d54bf4b5c91ec1ed2bb2f594b0bb800bdca3e8fe18148b92a6');old={r['path']:r for r in prior['joined']};rows={r['path']:r for r in current['files']};new={r['path']:r for r in ad['exact26']};prep=doc(G/'PREPARATION01.json');ck(git(['rev-parse','HEAD']).decode().strip()==H==ad['actual_current_source']==current['source'] and git(['rev-parse',H+'^']).decode().strip()==BASE==ad['prior_source'],'actual source direct868parent');ck(len(rows)==269 and len(old)==243 and len(new)==26 and set(rows)==set(old)|set(new) and not(set(old)&set(new)),'exact269 union');ck(set(new)==set(prep['proposed_body_pins']),'exactaccepted26 paths');tree={}
for e in git(['ls-tree','-r','-z',H]).split(b'\0'):
 if not e:continue
 m,n=e.split(b'\t');mode,typ,oid=m.decode().split();ck(typ=='blob' and mode in ('100644','100755'),'regular committedsource');tree[n.decode()]={'git_mode':mode,'git_oid':oid}
ck(set(tree)==set(rows),'exact current269tree');actual=set()
for root,ds,fs in os.walk(S,followlinks=False):
 if Path(root)==S:ds.remove('.git')
 for n in ds:ck(stat.S_ISDIR((Path(root)/n).lstat().st_mode),'canonical directory')
 actual.update(str((Path(root)/n).relative_to(S)) for n in fs)
ck(actual==set(rows),'full live269 files only');reply=git(['cat-file','--batch'],(''.join(tree[n]['git_oid']+'\n' for n in sorted(rows))).encode());offset=0;joined=[]
for n,row in sorted(rows.items()):
 end=reply.index(b'\n',offset);oid,typ,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2;mode=stat.S_IMODE((S/n).lstat().st_mode);ck(typ=='blob' and oid==tree[n]['git_oid']==row['git_oid'] and reply[offset-1:offset]==b'\n' and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+b).hexdigest()==oid,'current269 actualGitOID');ck(read(S/n)==b and sha(b)==row['sha256'] and size==row['bytes'] and row['git_mode']==tree[n]['git_mode']==('100755' if mode&0o111 else '100644'),'current269body/hash/mode')
 if n in old:ck(old[n]['git_object']==oid and old[n]['sha256']==sha(b) and old[n]['mode']==mode and old[n]['git_mode']==row['git_mode'],'all243 historicalbody/mode/OID unchanged')
 else:ck(read(G/'bodies'/n)==b and new[n]['sha256']==prep['proposed_body_pins'][n]==sha(b) and new[n]['bytes']==len(b) and stat.S_IMODE((G/'bodies'/n).stat().st_mode)==mode,'26exactaccepted generatedbody modes')
 joined.append(dict(row,mode=mode))
ck(offset==len(reply),'complete bodybatch');ck(sum(n.startswith('tradingagents/') for n in rows)==149 and prior['implementation']==194 and ad['auxiliary']==75,'19414975 actualscope')
# Complete actual prerequisite reviews; no historical counters substitute for source admission.
for dirname,pin in [('financial-genuine-wrapper-registration-review01-2026-10-04','eb25ea7c3042d5f323c1b96b9c8c5b909ab81044c5891d5d68aa02e964cf8b9c'),('financial-genuine-wrapper-cumulative-admission-review01-2026-10-04','bb187bc15451b41dc9286d0ea26dff094ac67e6bfbd53fd34191457ea290ae45')]:
 d=F/dirname;m=doc(d/'MANIFEST01.json',pin);ck({p.name for p in d.iterdir()}=={r['path'] for r in m['members']}|{'MANIFEST01.json'},'complete prerequisite review')
 for row in m['members']:
  p=d/row['path'];b=read(p);ck(row['kind']=='file' and sha(b)==row['sha256'] and len(b)==row['bytes'] and stat.S_IMODE(p.stat().st_mode)==row['mode'],'prerequisite typedbody')
gate=doc(P/'GATE_PROPOSAL01.json','6818dfdc48879fde8bf149bd1dae252885c6460a209e31af5a17a66012247691');proposal=doc(P/'PROPOSAL01.json');support=proposal['support_adoption'];ck(len(support)==20 and not(set(support)&set(rows)),'20future support paths disjoint actual269');source_map={n:r['sha256'] for n,r in rows.items()}
for n,row in support.items():
 b=read(Path(row['actual_prepared_path']));ck(len(b)==row['bytes'] and sha(b)==row['sha256'] and not (S/n).exists(),'exactprepared uninstalled supportbody');source_map[n]=sha(b)
ck(len(source_map)==proposal['prospective_source_files']==289,'prospective289 notactual269');draft=doc(G/'INITIAL_REGISTRATION_DRAFT01.json');phases=doc(G/'PHASES01.json');charter=doc(F/'financial-genuine-wrapper-root-charter-preparation01-2026-10-04/CHARTER02.json','041ab6260eeb81805202ba31c4ba1710b3109bbd0b24131e83a5c4f05984cbb1');ck(gate['program_id']==draft['program_id']==charter['program_id']=='financial-wrapper-engineering-2026-10-03' and gate['schema_version']==1,'program schema');family=gate['families']['synthetic-financial-wrapper'];ck(set(gate['families'])=={'synthetic-financial-wrapper'} and family['mechanism_id']==charter['mechanism_id']=='synthetic-full-financial-wrapper-v1' and family['attempt_budget']==charter['base_attempt_budget']==18 and family['prior_attempts']==charter['prior_same_mechanism_attempts']==0,'exact prospective distinct18prior0');ck('no refund or family rename reset' in family['history_reference'] and '88' in family['history_reference'],'related accounting disclosed');ck(gate['datasets']['synthetic']['identity']==draft['datasets']['synthetic']['identity'] and gate['datasets']['synthetic']['exposures']==draft['datasets']['synthetic']['exposures'] and 'exploratory' in gate['datasets']['synthetic']['history_reference'],'conservatively exposed synthetic administrative history');runtime={p.name:sha(read(p)) for p in (S/'tradingagents/research').glob('*.py')};ck(set(gate['experiments'])==set(draft['experiments']) and len(gate['experiments'])==10,'exact10initial only');slots={r['proposed_plan']['experiment']:r for r in phases['slots']};ck(len(slots)==18 and set(gate['experiments'])<set(slots),'8dependent remainwithheld');descriptors=[]
for exp,e in gate['experiments'].items():
 original=draft['experiments'][exp];ck(e['source_files']==source_map and e['runtime_hashes']==runtime,'all289prospective source/runtimepins');ck(e['charter']=={'path':'fixture_inputs/financial_wrapper_registration01/CHARTER02.json','sha256':'041ab6260eeb81805202ba31c4ba1710b3109bbd0b24131e83a5c4f05984cbb1'},'exactprospectivecharter');ck({k:v for k,v in e.items() if k not in ['source_files','charter','question']}=={k:v for k,v in original.items() if k not in ['source_files','charter','question']},'fullotherexperiment inverse');ck(e['parent'] is None and e['stage']=='development' and e['reuse']=='exploratory' and len(e['inputs'])==8,'initialparent/reuse8inputs');ck(all(w=={'availability':'existing','dataset':'synthetic','start':'2026-10-03T00:00:00Z','end':'2026-10-03T00:00:01Z'} for w in e['windows']),'administrative originalwindow');plan=None
 for role,ref in e['inputs'].items():
  ck(set(ref)=={'path','sha256','dataset'} and ref['dataset']=='synthetic' and ref['path'] in new and sha(read(S/ref['path']))==ref['sha256']==source_map[ref['path']],'80actual initial descriptor joins');descriptors.append({'experiment':exp,'role':role,**ref})
  if role=='wrapper_plan':plan=doc(S/ref['path'])
 ck(plan==slots[exp]['proposed_plan'] and plan['experiment']==exp and plan['namespace']==exp and e['cells']==[plan['cell_id']] and plan['phase'] in ['interrupt1','complete100','agreement'],'actual exactplan identity cell phase')
ck(len(descriptors)==80,'all80body joins');ck(all(not any(x in n.lower() for x in ['gate_proposal','initial_registration','gates.json']) for n in source_map),'no gate selfhash requirement');ck(all(not(S/n).exists() for n in ['research_runs','research_artifacts','fixture_inputs/financial_wrapper_registration01']),'no genuineclaim/output/adopted supportgate namespace')
fixture=ast.parse(read(S/'tradingagents/research/onchain_replication/financial_wrapper_fixture.py'));fn=next(n for n in fixture.body if isinstance(n,ast.FunctionDef) and n.name=='synthetic');ck(any(isinstance(n,ast.For) and ast.unparse(n.iter)=='range(16 * 28)' for n in ast.walk(fn)) and 'graphs.append({' in ast.unparse(fn),'actual448graph dictionaries source');ck(charter['denominator']['distinct_graphs_total']==448 and charter['denominator']['synthetic_examples']==16 and charter['denominator']['distinct_graphs_per_example']==28,'exact charter448denominator');job=ast.parse(read(S/'tradingagents/research/onchain_replication/job.py'));starts=[n for n in ast.walk(job) if isinstance(n,ast.Call) and ast.unparse(n.func)=='ResearchRun.start'];ck(len(starts)==1 and {x.arg for x in starts[0].keywords}=={'root','registration','experiment','source'},'actualworker sameSourceDesign defaults nofabricatedbinding');admissions=read(S/'tradingagents/research/admission.py').decode();ck('design_source = design_source or source' in admissions,'actualadmissiondefault source');ck(git(['rev-parse','HEAD']).decode().strip()==H and git(['status','--porcelain','--untracked-files=all'])==b'','finalunchanged clean269');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numericalimports');out={'schema_version':1,'decision':'ACCEPTED_INSTALLED269_AND_PROSPECTIVE289_GATE_SUPPORT_ADOPTION_ONLY','checks':len(checks),'actual_current_source':H,'prior_source':BASE,'actual_tracked':269,'unchanged_historical':243,'new_input_bodies':26,'implementation':194,'package':149,'auxiliary':75,'prospective_source_pins':289,'future_support_bodies':20,'eventual_gate_excluded_from_own_source_pins':True,'gate_sha256':sha(read(P/'GATE_PROPOSAL01.json')),'proposal_sha256':sha(read(P/'PROPOSAL01.json')),'initial_experiments':10,'withheld_dependents':8,'actual_descriptor_joins':80,'actual_admit_start_or_grant_called':False,'current269_full_recovery':False,'launch_or_capacity_or_runtime_authority':False,'joined':joined,'descriptors':descriptors};(O/'READBACK01.json').write_text(json.dumps(out,sort_keys=True,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k not in ['joined','descriptors']},indent=2))
