import ast,gzip,hashlib,io,json,os,stat,subprocess,sys,tarfile
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();D=F/'financial-genuine-wrapper-root-claimedrun-source339-remote02-2026-10-04';V=F/'financial-genuine-wrapper-claimedrun-source339-selection-review02-2026-10-04';sys.path.insert(0,str(F/'held-consumer-final-recovery-preparation04-2026-10-03'));import recovery04 as a
sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
def read(p):return a.read(p.parent,p.name)
def git(args,cwd):
 p=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never',*args],cwd=cwd,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_NO_LAZY_FETCH':'1','GIT_OPTIONAL_LOCKS':'0','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_TERMINAL_PROMPT':'0'});ck(p.returncode==0 and len(p.stdout)<=8*1024**2 and len(p.stderr)<=65536,'bounded readonly genuine fetchedGit no network');return p.stdout
receipt=read(D/'REMOTE_RECOVERY01.json');ck(sha(receipt)=='9e6d7dd7e0260aa955f6aeff72abbf6fbaf7c85bd5b308d1c527c6b69ce472b2','exact original actual remote receipt');r=json.loads(receipt);q=json.loads(read(D/'SELECTED_BODIES01.json'));ck(sha(read(D/'SELECTED_BODIES01.json'))==r['selection_sha256']=='38bc70a9c3cc684588e9cb8792587be08ff65a4cefc27e4d31057fb630650cce','selection receipt');ck(sha(read(V/'MANIFEST01.json'))=='5aae8f741c063068a10f9c6384f5523604424d9c94785e1193995a9009774661','accepted original selection review');prior={v['path']:v for v in json.loads(read(V/'COMMITTED_BODY_JOINS01.json'))};term=json.loads(read(D/'ACTUAL_TOOL_TERMINAL02.json'));intent=json.loads(read(D/'INTENT01.json'));ck(sha(read(D/'INTENT01.json'))==term['intent_sha256']=='0e3bdcf105858eab930b2ba8109602f53c200c7fb681a30b5ba6fcbd374e9ee5eb','actual intentpin');ck(term['remote_receipt_sha256']==sha(receipt) and (term['session_id'],term['start_tool_chunk'],term['completion_tool_chunk'],term['actual_exit'])==(70954,'8d9766','24df16',0),'original actual tool outcome');ck(intent['accepted_selection_manifest']=='5aae8f741c063068a10f9c6384f5523604424d9c94785e1193995a9009774661','actual accepted selection intent')
for k,v in [('actual_root_pid',451048),('actual_start_ticks',15906391),('actual_pgid',451045),('actual_sid',451045)]:ck(intent[k]==term[k]==v,'actual original process identity '+k)
for label in ['stdout','stderr']:
 b=read(D/('ACTUAL_REMOTE01.'+('out' if label=='stdout' else 'err')));ck(sha(b)==term['actual_'+label+'_sha256'],'actual raw '+label)
 if label=='stderr':ck(b==b'','actual empty stderr')
 else:
  printed=json.loads(b);ck(printed=={k:r[k] for k in ('status','remote_commit','selected_count','selected_logical_bytes','elapsed_seconds')},'actual stdout exact receipt result')
H=r['remote_commit'];repo=Path(r['fresh_git_root']);ck(H==q['remote_commit']=='6514f20fc208e0d2f7ada31bc285b4e0b5c33ff8' and repo==D/'fresh-recordfix-source325-01.git' and repo.resolve()==repo,'actual fresh root/commit');ck(git(['cat-file','-t',H],repo)==b'commit\n','actual immutable fetched commit present');names=[v['path'] for v in q['rows']];rawtree=git(['ls-tree','-r','-z',H,'--',*names],repo);tree={}
for item in rawtree.split(b'\0'):
 if item:meta,n=item.split(b'\t',1);tree[n.decode()]=tuple(meta.decode().split())
ck(set(tree)==set(names) and names==sorted(set(names)),'actual fetched complete sorted scope');ck(len(r['selected_blobs'])==len(names)==195 and r['selected_count']==195 and r['selected_logical_bytes']==sum(v['bytes'] for v in q['rows'])==18500231,'actual195/fullbytes');selected={};joins=[]
for original,actual in zip(q['rows'],r['selected_blobs']):
 n=original['path'];mode,kind,oid=tree[n];ck(actual==dict(original,git_mode=mode,git_object=oid),'receipt exact original row/object');ck(kind=='blob' and mode==prior[n]['git_mode'] and oid==prior[n]['git_object'],'immutable original/fetched Git object');b=read(D/'selected'/n);s=(D/'selected'/n).lstat();ck(stat.S_IMODE(s.st_mode)==0o600 and s.st_nlink==1 and sha(b)==original['sha256'] and len(b)==original['bytes'],'saved actual0600 singlelink body');ck(read(ROOT/n)==b==git(['cat-file','blob',oid],repo),'all original/fetched/saved bodytriples');selected[n]=b;joins.append(actual)
ck({p.relative_to(D/'selected').as_posix() for p in (D/'selected').rglob('*') if p.is_file()}==set(names),'no extra or missing selected files')
ops=r['operations'];expected=['remote','ls-remote','init','remote','config','config','fetch','rev-parse','ls-tree','fetch']+['cat-file']*390+['ls-remote'];ck(len(ops)==401 and [op['operation'] for op in ops]==expected,'all401 original operation sequence');pids=[]
for op in ops:ck(op['exit']==0 and op['cleanup_failures']==[] and 0<=op['stdout_bytes']<=4*1024**2 and 0<=op['stderr_bytes']<=65536 and op['seconds']<60,'all original operation exits bounds cleanup');pids.append(op['pid'])
head=(H+'\t'+r['branch']+'\n').encode()
for idx in [1,400]:ck(ops[idx]['stdout_sha256']==sha(head) and ops[idx]['stdout_bytes']==len(head),'original actual initial/final remoteHEAD output hashes')
ck(ops[7]['stdout_sha256']==sha((H+'\n').encode()) and ops[8]['stdout_sha256']==sha(rawtree),'actual fetchedcommit/tree output hashes')
for i,row in enumerate(q['rows']):
 b=selected[row['path']];size=(str(len(b))+'\n').encode();ck(ops[10+2*i]['stdout_sha256']==sha(size) and ops[10+2*i]['stdout_bytes']==len(size) and ops[11+2*i]['stdout_sha256']==sha(b) and ops[11+2*i]['stdout_bytes']==len(b),'all390 actual size/body operations bound to saved bytes')
ck(len(set(pids))==401,'distinct actual Git child PIDs')
for pid in pids+[451048]:ck(type(pid)is int and not Path('/proc'/str(pid)).exists(),'recorded original PID currentlyabsent')
for pg in pids+[451045]:
 try:os.killpg(pg,0)
 except ProcessLookupError:checks.append('recorded original group currentlyabsent')
 else:raise AssertionError('original group remains '+str(pg))
# Full selected remote archives: raw bounded parsing/reencoding from actual recovered bytes.
t=ast.parse(read(F/'held-consumer-final-released-scope-capture-review01-2026-10-03/check01.py'));exec(compile(ast.Module(body=[n for n in t.body if isinstance(n,ast.FunctionDef) and n.name in ('decode','recode')],type_ignores=[]),'<independent raw framing>','exec'));archives={};archive_results=[]
for n,b in selected.items():
 if not n.endswith('.tar.gz'):continue
 mp=n[:-7]+'-manifest.json';m=json.loads(selected[mp]);bs,frames=decode(b,m);ck(recode(m,bs)==b,'entire actual recovered canonical archive inverse');archives[n]=(m,bs);archive_results.append({'path':n,'sha256':sha(b),'members':len(m['members']),'regular':sum(v['kind']=='file' for v in m['members']),'framing':frames})
C=F/'financial-genuine-wrapper-root-claimedrun-source339-capture01-2026-10-04';m,bs=archives[(C/'source.tar.gz').relative_to(ROOT).as_posix()];S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');ck(a.scan(S)==m and len(m['members'])==1029,'entire Source339 current stillcaptured');ck(git(['rev-parse','HEAD'],S).decode().strip()=='0a2e7639b42b9423b90743feadcda4078aa21816','actual Sourcecurrent');old='research_runs/financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01/';ck(sha(bs[old+'claim.json'])=='4c543d71fad5255be61087eaa3619d9e88cbbdc12fa1398bd7fa7fe6fb75c128' and sha(bs[old+'failed.json'])=='35158c0ecebfe4dc75203ba87d5372f2f85643c0b5f828a99e17aa28fe79c450','genuine copied spent1 actualfailure archived');ck(not os.path.lexists(S/'research_runs/financial-wrapper-classification-eager-interrupt1-claimedrun-20261004-01'),'no newclaim')
P=F/'financial-genuine-wrapper-claimedrun-actual-admission-review01-2026-10-04';proof=selected[(P/'INDEPENDENT_SOURCE_INPUT_RUNTIME01.json').relative_to(ROOT).as_posix()];seal=selected[(P/'MANIFEST01.json').relative_to(ROOT).as_posix()];ck(sha(proof)=='059232d0f7fc8922cee526a1bd30fef2ecb51ee17103284bcaac18c77e77641c' and sha(seal)=='24e6451d2a9c5ec516b99ca95bb477567e5f9ef5d13adef3bb41c0633b93e5c7','actual remote previouslymissing proof complete');ck(r['free_bytes']>=10*1024**3 and intent['free_before']>=10*1024**3,'actual observed disk floors');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','tradingagents'} for n in sys.modules),'no research/numerical import')
x={'schema_version':1,'decision':'ACCEPTED_ACTUAL_SOURCE339_SELECTED_REMOTE_RECOVERY','remote_receipt_sha256':sha(receipt),'selection_sha256':r['selection_sha256'],'accepted_selection_manifest_sha256':'5aae8f741c063068a10f9c6384f5523604424d9c94785e1193995a9009774661','remote_commit':H,'selected_count':195,'selected_logical_bytes':18500231,'actual_Git_operations':401,'checks':len(checks),'complete_actual_archives':archive_results,'actual_terminal_sha256':sha(read(D/'ACTUAL_TOOL_TERMINAL02.json')),'actual_intent_sha256':sha(read(D/'INTENT01.json')),'actual_parent_exit':0,'original_root_pid':451048,'original_start_ticks':15906391,'original_group_session':451045,'all_recorded_root_and_Git_pids_and_groups_currently_absent':True,'per_operation_raw_streams':'Not independently retained as separate files; recorded hashes joined to immutable output bodies/tree/initial-final HEAD where reconstructable. Raw Root streams retained.','inherited_receipt_status':r['status'],'inherited_receipt_qualification':r['qualification'],'actual_scope_qualification':'195 exact selected source/support bodies include complete Source3391029/747/Git/history, actual admission review, old failed ordinary preparations and full opaque handoff/recovery witness archives. Original inheritedSource325 wording is retained, not treated as actual new scope evidence.','Source339_flat_recovery':False,'final_Parent_caller_release_or_recovery':False,'installed_runtime_or_empirical_stores_recovered':False,'POSIX_reinstantiation':False,'native_capacity_or_numerical_authority':False};(O/'READBACK01.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');(O/'ACTUAL_SAVED_BLOB_JOINS01.json').write_text(json.dumps(joins,sort_keys=True,indent=2)+'\n');print(json.dumps({'checks':len(checks),'decision':x['decision']}))
