"""Candidate metadata assembly only; not installation/admission/runtime execution."""
from pathlib import Path
import ast,difflib,hashlib,json,sys
D=Path(__file__).resolve().parent;F=D.parent;ROOT=D.parents[3]
base=F/'original-import-native-refusal-candidate05-2026-10-03';inv=json.loads((base/'source_inventory05.json').read_text())
def ref(p):
 b=p.read_bytes();return {'path':str(p.relative_to(ROOT)),'bytes':len(b),'sha256':hashlib.sha256(b).hexdigest()}
def write(n,v):(D/n).write_text(json.dumps(v,indent=2)+'\n')
install={'tradingagents/research/onchain_replication/resource_refusal.py':'resource_refusal.py'}|{'fixture_tools/'+n:n for n in ('refusal_outer01.py','refusal_preclaim01.py','refusal_native01.py','refusal_oracle_evidence01.py','templates01.py')}
rows={r['target']:r for r in inv['source_inventory']};changes=[]
for target,name in install.items():
 if target in rows:
  old=ROOT/rows[target]['origin'];(D/(name+'.patch')).write_text(''.join(difflib.unified_diff(old.read_text().splitlines(True),(D/name).read_text().splitlines(True),fromfile=rows[target]['origin'],tofile=str((D/name).relative_to(ROOT)))))
 v=ref(D/name);r={'target':target,'origin':v['path'],'bytes':v['bytes'],'sha256':v['sha256'],'git_commit':None,'git_path':None};rows[target]=r;changes.append(r)
for r in rows.values():
 p=ROOT/r['origin'];v=ref(p);assert v['bytes']==r['bytes'] and v['sha256']==r['sha256']
package=[k for k in rows if k.startswith('tradingagents/')];assert len(package)==144
inv.update(source_inventory=sorted(rows.values(),key=lambda r:r['target']),source_count=len(rows),source_logical_bytes=sum(r['bytes'] for r in rows.values()),base_inventory=ref(base/'source_inventory05.json'),status='source-only-worker-candidate-unreviewed-not-admitted',final_overlay_git_commit=None)
write('source_inventory01.json',inv);write('install-delta01.json',{'base_inventory':ref(base/'source_inventory05.json'),'targets':changes,'package_count':144,'status':inv['status']})
# Bounded audit of every new source's direct package/tool dependencies plus
# the fixed dynamic imports in the genuine oracle hook. No package import.
audit=[]
for target,name in install.items():
 tree=ast.parse((D/name).read_text());edges=[]
 for node in ast.walk(tree):
  candidates=[]
  if isinstance(node,ast.ImportFrom):
   if node.level:
    prefix='tradingagents/research/onchain_replication/'
    candidates=[prefix+(node.module or alias.name).replace('.','/')+'.py' for alias in node.names]
   elif node.module and node.module.startswith('tradingagents.research.onchain_replication'):
    tail=node.module.removeprefix('tradingagents.research.onchain_replication').strip('.')
    candidates=['tradingagents/research/onchain_replication/'+(tail or alias.name).replace('.','/')+'.py' for alias in node.names]
   elif node.module and node.module.split('.')[0] not in sys.stdlib_module_names:
    candidates=['fixture_tools/'+node.module.replace('.','/')+'.py']
  elif isinstance(node,ast.Import):
   candidates=['fixture_tools/'+alias.name+'.py' for alias in node.names if alias.name.split('.')[0] not in sys.stdlib_module_names]
  for dependency in candidates:
   assert dependency in rows,(target,dependency);edges.append(dependency)
 if name=='resource_refusal.py':
  for n in ('raw_receipts01','original_semantics','refusal_pair_identity','resource_policy05','guarded_formula_oracle05'):
   t='fixture_tools/'+n+'.py';assert t in rows;edges.append(t)
 audit.append({'source':target,'sha256':rows[target]['sha256'],'selected_dependencies':sorted(set(edges))})
write('source-hook-audit01.json',{'qualification':'Direct static and explicit fixed-dynamic new-hook closure. Complete selected inventory retained; no numerical imports, runtime import proof or native execution.','sources':audit})
# Qualified exact renderer exercise using original read-only metadata and tiny
# stdlib-generated bytes; no graph arrays imported or body files emitted.
sys.path.insert(0,str(D));import test_adapter01
path=base/'test_inputs05.py';import importlib.util
spec=importlib.util.spec_from_file_location('qualified_input_render',path);mod=importlib.util.module_from_spec(spec);spec.loader.exec_module(mod);basic,_,_,_=mod.render()
sources={k:r['sha256'] for k,r in rows.items()};primary,_=mod.generator.registration(rendered={'success':basic,'second_target_publication_failure':basic},source_files=sources,runtime_hashes={'qualified_only':'a'*64})
import templates01
identity_path=ROOT/rows['tradingagents/research/onchain_replication/imported_mcm_identity.py']['origin']
value=templates01.prepare(basic,primary,source_files=sources,runtime_hashes={'qualified_only':'a'*64},imported_identity_source=identity_path.read_bytes(),runtime={'qualified_only':True},native_environment={'qualified_only':True},capsule='/qualified-unregistered-synthetic',source_commit='a'*40)
write('PROTOCOL01.json',value['protocol']);write('qualified-release-draft01.json',value['release']);write('qualified-registration-draft01.json',value['registration'])
write('generated-input-index01.json',{'qualification':'Sentinel a*40 source anchor and non-runtime environment; unregistered test-only templates. No actual capsule installation or input body population.','cases':{n:{'identity':v['identity'],'inputs':v['inputs'],'generated_body_hashes':{k:hashlib.sha256(b).hexdigest() for k,b in v['files'].items()}} for n,v in value['rendered'].items()}})
assert not any(n.split('.')[0] in ('numpy','scipy','torch','tradingagents') for n in sys.modules)
print(len(rows),'source bodies;',len(package),'package;',inv['source_logical_bytes'],'bytes. Direct/fixed-dynamic hooks accounted.27 draft cases; no guard/job/claim/registration adoption.')
