# Financial wrapper prospective cumulative accounting review

**Decision: the narrowly defined synthetic financial-wrapper program may legitimately have its own prospective family and finite 18-attempt allocation. Registration, actual allowance adoption and execution remain WITHHELD.** This is a substantive accounting interpretation of draft `060e13c4534747393591e30f60ba38fe105a9b8782260a0b75575cf3b7775564`; it is not an accepted-extension token, registry mutation, claim reservation or native release.

Independent metadata reconstruction passed 1,577 assertions across 11 explicitly bounded genuine ledger roots, including 88 recorded claim copies. No existing claim with the proposed program/mechanism or any of its 18 proposed identities was found there. The scope is enumerated in `HISTORY_READBACK01.json`; this does not establish universal or future namespace freshness. Exact claim/terminal/body hashes, current source-interface hashes and each ledger root are retained. One reader initially refused the genuine historical seven-day claim's two-link file; the original failed script and correction are preserved. Only that exact claim and its terminal received a two-link read exception. Their hashes match the original historical manifest; no exclusive-ownership claim follows.

The distinction rests on the actual question and implementation, not the new names. The wrapper tests original `fit_cell` 100-epoch execution, a genuine one-update interrupted FAILED parent, 99-update continuation, separate uninterrupted reference, and saved completed-model prediction on 448 distinct synthetic graphs per 16×28 batch. Its selected candidate requires graph checkpointing false (`financial_execution.py:87,109`). It is neither the old checkpoint-false/true two/28-graph proof, cold feature detachment/lifetime/joint-gradient acceptance, empirical dictionary import nor paper/full-graph capacity. Source reuse, original model20f451, seed11 and engineering knowledge remain related exposure and must be disclosed. A future claim of the old failed mechanism under this new name would invalidate the distinct-family interpretation and require cumulative same-mechanism review.

Actual history is preserved as follows:

| Account | Independently joined actual history | Accounting consequence |
|---|---|---|
| Paper | Original 17 identities and all historical metadata pins, plus 19 current program claims = 36 unique closed; 27 COMPLETE, 9 FAILED; maximum adopted current ceiling 64 | No paper65, refund, spare-quota transfer or financial-fit credit. |
| Original import | Five genuine FAILED claims, effective allowances 2,3,4,5,6 | Held-success identity remains permanently spent; dependent publication-failure is absent/unclaimed and UNAVAILABLE. Its unused conditional slot is not transferable. |
| Cold authority | Materialization COMPLETE, comparison FAILED, base2/prior0 | Two attempts exhaust the family. Materialization does not complete scientific cold comparison. |
| Tiny checkpoint | Original separately reserved outer identity FAILED; three exact original arm terminals passed; scalar totals retain 3,823 comparisons | No rerun, ResearchRun refund, paper claim or financial fit; passed components do not change outer failure. |

`docs/research/README.md:79–103` and actual installed `admission.py:188,319–346` require all starts, including failure, to count; renamed mechanism aliases cannot reset a real family. The admission helper scans only its root's `research_runs`, so an empty isolated financial root alone is insufficient history. The cross-root readback is therefore essential. Related but substantively different historical mechanisms stay explicitly linked history; they are not falsely inserted as same-family ResearchRun parents. Actual admission rejects cross-family parent ancestry.

For this finite question, the permissible prospective base is program `financial-wrapper-engineering-2026-10-03`, family `synthetic-financial-wrapper`, mechanism `synthetic-full-financial-wrapper-v1`, **attempt_budget18, prior_attempts0**, conditional on fresh history/identity checks and exact committed charter/registry/history. No base has been adopted. A version-1 cumulative extension is not needed for an unclaimed distinct family and must not be fabricated using unrelated claims: the actual extension implementation requires a nonempty same-mechanism closed-claim snapshot. If prior same-mechanism work is discovered, or the substantive objective widens into a failed existing mechanism, this proposed base0 interpretation must be revisited before adoption.

The complete proposed denominator reconstructs exactly: two agreement phases, four interruptions, four uninterrupted fits, four continuations and four predictions, over 18 identities and ten cells. Intended terminal outcomes are conditionally 14 COMPLETE and four planned FAILED, not observations. There are 12 fit_cell calls; four reference fits perform 400 updates, four interrupts perform four updates, and four continuations perform 396 updates, totaling 800. Two agreement phases add four one-step updates. Eight genuine completed100 fit records, four prediction phases and 16 replay copies are conditional coverage targets, with **zero paper fit credit**. Replay copies are not additional fits. All phases share deterministic model/recipe development, so they are not 18 independent financial trials or fresh confirmation samples.

Every continuation's primary ResearchRun parent must be its actual FAILED interrupt1, with identical task/backend/cell and authentic checkpoint1/0/one log/PlannedInterruption diagnostic. The separate COMPLETE uninterrupted100 reference is a fully pinned prerequisite, not an invented second parent. Prediction follows the chosen genuine COMPLETE continuation parent. A missing or wrong parent makes a descendant unavailable; any unexpected claimed failure remains spent. No automatic retries, replacement identities, cap ladder or resource/seed/config/tolerance changes can be fitted inside the allocation silently.

Concrete remaining admission blockers are machine-enumerated as FA1–FA8 in `CUMULATIVE_REQUIREMENTS01.json`:

- Draft `CHARTER_DRAFT01.json:3,10,927` leaves allowance/review/release fields null. Freeze the actual charter, full family/history object, exact dataset/exposure windows, phase names/cells/namespaces, selection and stop rules, and registration with committed source/design pins. The draft's `COMPLETE:14` at line34 must remain explicitly projected in any registration/ledger presentation.
- The same draft's source390 at line943 is historical. Current observed source is `868bfa6404a2c34d6e5b6e0932a2baf4b38eb370`, 243 tracked/149 package, with unchanged wrapper02 `e13d7170…`; later registration/gate additions require their own exact final source/design/current joins. Source44's earlier complete archive is not recovery of this later state.
- Phase launch order and stop behavior must be explicit. Agreement-first was proposed in earlier investigation but is not a hard dependency in the frozen draft or source. Root must freeze whichever exact safe order is selected before outcomes, rather than invent an implicit prerequisite after a result.
- All genuine runtime expectation/worker equality, role/source/input closure, final full recovery, actual caller/Binding/Owner/ResearchRun/native seals, fresh namespace checks and bounded 100-epoch checkpoint/storage feasibility remain outstanding. Parent outcomes require independent review and full recovery before dependency use. Historical expected runtime values do not establish current API observations.

Root can now construct the exact registration and finite allocation under these constraints, with later independent source/registration review; this decision does not authorize launching it. No arrays, numerical libraries, runtime API, experiment, financial returns, cashflows, timing leakage, fees/funding or resource-capacity measurement was executed or validated. The 1,420 paper fits remain pending. No higher-effort numerical rerun is warranted to settle this accounting interpretation.
