from pathlib import Path
import hashlib,json,stat
B=Path(__file__).resolve().parent;P=B.parent/'paper-treatment-fit-admission-preparation01-2026-10-04'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def put(name,x):(B/name).write_text(json.dumps(x,sort_keys=True,indent=2)+'\n')
c=json.loads((B/'CHECKS02.json').read_text());findings=[{'id':'DA1','priority':'P2','file':'overlay/tradingagents/research/onchain_replication/treatment_admission.py','line':97,'problem':'Genuine observer missing-row shape has only id/status/reason; unconditional asset/week check refuses failed unavailable fallback before disposition_input=None branch.','required_change':'Accept only the exact genuine absent-row fallback under failed terminal and exact registered cell/date mapping, preserving unavailable status; retain strict asset/week checks for actual durable rows. Do not fabricate durable evidence.','witness':'CHECKS02.json DA1; actual corrected producer02 job fallback AST extracted.'},{'id':'DA2','priority':'P2','file':'overlay/tradingagents/research/onchain_replication/treatment_admission.py','line':138,'problem':'fdopen can raise after os.open acquired a descriptor, leaving no owner to close it.','required_change':'Transfer fd ownership explicitly; always close a still-owned fd if fdopen fails. Preserve first fatal if close also fails.','witness':'CHECKS02.json DA2; actual stdlib fd acquired by extracted source, fdopen MemoryError injected, fstat confirms open, reviewer explicitly closes it.'},{'id':'DA3','priority':'P1','file':'overlay/tradingagents/research/onchain_replication/treatment_admission.py','line':138,'problem':'with-exit close exception replaces an original fatal read. KeyboardInterrupt became ordinary OSError in the exact extracted seam.','required_change':'Use explicit first-fatal cleanup semantics preserving original fatal object and all close attempts/errors; include ordered fatal/fatal and ordinary/fatal controls.','witness':'CHECKS02.json DA3; actual acquired stream closed, read KeyboardInterrupt and close OSError injected; ordinary close error propagates.'}]
put('REVIEW01.json',{'schema_version':1,'verdict':'WITHHELD_SOURCE_INTEGRATION','candidate_manifest_sha256':sha(P/'MANIFEST01.json'),'candidate_source_sha256':sha(P/'overlay/tradingagents/research/onchain_replication/treatment_admission.py'),'findings':findings,'checks':c['checks'],'checked_scope':['complete candidate typed manifest/modes/hash membership','declared actual original source origins','three full byte/AST inverses','new stdlib admission source and fit/population call sites','exact real producer02 observer fallback row shape','tiny real owned descriptor acquisition/closure under injected failures','source-only unavailable/terminal/cell/date refusal and causal-week controls'],'harness_history':[{'path':'CHECK01.err','cause':'Review harness expected ValueError/KeyError/TypeError only; malformed output_sha256=None raises AttributeError. Preserved, broadened ordinary-refusal expectation in check02.'}],'accepted_narrow_properties':['Producer source pins remain None and refuse actual admission','New direct-fit and batch call sites invoke mandatory treatment checks before fit dispatch','Per-week config map preserves complete-week denominator; original legacy None branch unchanged','Original method/filter/calendar/array implementation bytes unchanged by exact inverses/origin authentication','Completed fund consumption remains explicitly unadmitted; no fabricated historical cohort or financial authority'],'not_tested':['Actual verify_claim/job._terminal/genuine ResearchRun/native chain or registered admission','Numerical arrays, representations, daily price/test labels or PnL/accounting','Actual fit or resource capacity and full cumulative financial source composition','Network/archive recovery or external backing','Arbitrary allocation exhaustion/filesystem race guarantees; injected IO controls cover named seams only'],'authority':{'installed_source':None,'registration':None,'gate':None,'native_execution':None,'financial_credit':0,'paper_fits':0}})
(B/'REVIEW01.md').write_text('''# Treatment fit admission — independent source review

Verdict: WITHHELD. Three concrete source blockers remain before Root can compose or adopt the candidate.

- **DA1, P2 — treatment_admission.py:97:** the genuine observer's missing-cell postmortem row has only `id/status/reason`. The unconditional `asset/week` check rejects it before the intended `disposition_input=None` branch. Derive the expected identity/date from the registered exact cell and plan only for the authenticated failed-and-absent fallback; do not fabricate a durable row or relax checks for retained rows.
- **DA2, P2 — treatment_admission.py:138:** an exception from `os.fdopen` leaves the descriptor just acquired by `os.open` unclosed. The exact extracted source acquired a real owned tiny-file descriptor; injected `MemoryError` left it open, confirmed by `fstat`, and the reviewer closed it. Explicit ownership transfer and failure cleanup are required.
- **DA3, P1 — treatment_admission.py:138:** context-manager cleanup can replace fatal cancellation with an ordinary error. The exact extracted seam propagated close `OSError` instead of original read `KeyboardInterrupt`. Preserve the first fatal object through independent close attempts; retain secondary errors without replacing it.

The independent 148 controls include exact complete manifest membership/modes/hashes, actual declared source-origin joins, complete byte/AST inverses of all three existing-module edits, original fallback reconstruction, terminal/cell/date refusal controls and the named owned-descriptor witnesses. These are not 148 empirical cases. One harness failure incorrectly excluded AttributeError from ordinary malformed-input refusals; CHECK01.err and check01.py remain preserved and check02 corrects only that harness assumption.

The new module uses stdlib imports, producer source pins remain deliberately None, and genuine runtime treatment admission remains refused. Direct-fit and batch call sites add mandatory receipt checks before fitting. Per-week transformed config identities and the legacy no-treatment branch are separated explicitly. Original filter/calendar/model code is unchanged. Complete fund consumption still refuses until historical entity/address/vintage and known_at policy admission exist.

No genuine Run/Owner/claim was fabricated or started. No numerical modules, graph arrays, test labels, PnL book, native workload, registration, budget, Git mutation or network operation were exercised. Genuine committed ancestry and numerical/component correctness remain unperformed. The isolated financial source requires its own exact composition and reviewed source/recovery/capacity; this Main overlay is not that source. Paper 1,420-fit, cumulative budget and historical failures are unchanged.
''')
entries=[]
for p in sorted(B.rglob('*')):
 rel=p.relative_to(B).as_posix()
 if rel=='MANIFEST01.json':continue
 s=p.lstat();kind='directory' if stat.S_ISDIR(s.st_mode) else 'file';assert kind=='directory' or stat.S_ISREG(s.st_mode)
 e={'path':rel,'type':kind,'mode':stat.S_IMODE(s.st_mode)}
 if kind=='file':e.update(bytes=s.st_size,sha256=sha(p))
 entries.append(e)
put('MANIFEST01.json',{'schema_version':1,'scope':'complete typed independent source review; exact root manifest self-excluded','entries':entries,'members':len(entries),'regular_files':sum(e['type']=='file' for e in entries)})
print(json.dumps({'verdict':'WITHHELD','checks':c['checks'],'report':sha(B/'REVIEW01.md'),'machine':sha(B/'REVIEW01.json'),'manifest':sha(B/'MANIFEST01.json'),'members':len(entries)},indent=2))
