import ast,hashlib,json,os,stat
from pathlib import Path
H=Path(__file__).resolve().parent;sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest()
def save(n,v):(H/n).write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
s=json.loads((H/'SOURCE_READBACK01.json').read_text());base=json.loads((H/'MACHINE_BASE01.json').read_text());roles=json.loads((H/'ROLE_MAP01.json').read_text());templates=json.loads((H/'INPUT_BODY_TEMPLATES01.json').read_text());line=s['source_functions']
steps=[]
def add(key,phases,predicate,pointer,status='Root must implement and independently review the preclaim metadata/body equivalent; worker validation alone is too late'):
 steps.append({'id':key,'phases':phases,'refuse_unless':predicate,'actual_source_pointer':pointer,'source_location':line[pointer],'preclaim_status':status})
allph=['complete100','continue100','predict']
add('P01_exact_current_gate',allph,'Actual committed current=design source, exact same program/family/cumulative history and genuinely reviewed finite allowance; all12 old registrations retained; fixed new identity absent from every claimed/attempt namespace. Existing gate12 is source-stale and is not a new release.','job.py:_admitted','Current original admission supports source/gate/identity checks once Root registers; not executed here')
add('P02_entire_registered_input_inventory',allph,'Every input role has canonical contained regular path, explicit lowercase64 SHA256 and <=4MiB extent; read/hash every registered input before start, including extras, policy/proofs and descriptor-referenced roles. Missing/null/redirect/changed bytes refuse.','lifecycle.py:start','MATERIAL ORDER: original start writes claim before _check_inputs; job._admitted does not check every late dependency')
add('P03_job_plan_science',allph,'Exact original job limits and whole same physical capsule roots; fixed plan identity/cell/phase/task classification/backend eager; original model20f451, trainingd527100epochs/batch16, recipef8b1 and outputs3 unchanged.','financial_wrapper_fixture.py:admitted','Original pre-import fixture checks base science/job/plan; exact three templates pass extracted pure schemas')
add('P04_runtime_environment',allph,'Exact actual interpreter/environment and251 RECORD metadata mapping, genuine guarded execution package/source origins; no package replacement. Missing actual runtime/native evidence refuses release.','financial_wrapper_fixture.py:runtime_check','Existing metadata runtime check applies; this investigation only authenticated saved JSON bytes')
add('P05_target195_and_current_provenance',allph,'Full exact195 path map/helper wrapper training watcher pins,191 unchanged originals; current closure has new195 map while historical closure94a33256 remains194. Actual source_files cover195 plus all prospective input/proof/gate roles, excluding only the containing gate self hash. Final counts freshly derived.','operational_source_compatibility.py:_context')
add('P06_same_prospective_policy',allph,'One identical policy frozen before reference binds all three exact supplied IDs/cells, full old/current maps and fixed historical claim/FAILED/checkpoint/protocol. No containing-future-commit self hash; actual Root release separately binds final commit.','operational_source_compatibility.py:_context')
add('P07_genuine_proofs',allph,'Both committed source-pinned compatibility review/recovery role bodies exist and match exact policy/helper/map hashes; independently authenticate underlying authorship and actual full recovery. Accepted labels are not proof.','operational_source_compatibility.py:_context')
add('P08_fresh_reference_cell',['complete100'],'Parent None, prior/reference inputs None, supplied new reference cell and namespace absent. All target195 bodies/policy already final for future continuation/predict.','training.py:_reserve')
add('P09_actual_old_history',['continue100'],'Genuine verify_claim/closed FAILED history0a2/d390/4b2 and original Git source/design/registration; unchanged all claim/terminal paths/bytes; no COMPLETE terminal. Parent is original claimedrun interruption, never old failed complete100.','operational_source_compatibility.py:_parent_predicate')
add('P10_exact_old_selected_job_plan',['continue100'],'Original job4712 selects original wrapper_plan15fd, registered at old claim paths; old194 closure94a; exact cell/task/backend matches child. All11 historical alias bodies, including state.pt, explicitly registered in the new consumer; availability alone is not registration.','financial_wrapper_fixture.py:_interrupt_parent')
add('P11_checkpoint_original_bytes',['continue100'],'Old checkpoint b2f7 at literal original failed fit path, member state.pt493424/223ced42, all manifest members independently registered with exact extent/hash; old complete provenance0a2/source193 unchanged, no relabeling or relocation.','operational_source_compatibility.py:_parent_predicate')
add('P12_failed_fit_schedule',['continue100'],'Exactly one prior fit directory equal historical interruption; exact fresh fit claim, PlannedInterruption terminal, diagnostic absolute checkpoint/hash and original schedule16examples/seed11/training100; no completed fit exists.','financial_wrapper_fixture.py:_interrupt_parent')
add('P13_prior_descriptor',['continue100'],'Exact12-field descriptor, aliases joined to policy historical aliases; parent_input completion_input remains None for FAILED parent. Every role reference exists and hash matches actual original.','financial_wrapper_fixture.py:_parent')
add('P14_reference_complete',['continue100'],'Fixed NEW reference actual COMPLETE claim and lifecycle terminal, matching outputs/cell denominator/full result receipts, no FAILED; actual fit completion100 and original checkpoint/member bytes at fixed new reference cell. Descriptor exact5fields, actual full provenance and every real member populated after completion/recovery.','financial_wrapper_fixture.py:_reference_state')
add('P15_reference_science_policy',['continue100'],'Reference/current strict provenance equal except existing source_commit/cell exceptions; same195 implementation, same policy hash and fixed reference consumer. Genuine completed reference externally/freshly recovered and independently accepted before dependent release.','operational_source_compatibility.py:require_reference_policy')
add('P16_prediction_complete_parent',['predict'],'Fixed new continuation genuine COMPLETE lifecycle/fit100, exact6-field prior descriptor, every member registered; policy input SHA, complete closure SHA, fixed continuation identity/cell and entire target195 map equal current. No old failed or unrelated completed parent.','operational_source_compatibility.py:validate_prediction_parent')
add('P17_prediction_strict_provenance',['predict'],'Original strict provenance equality except source_commit; literal completed parent fit/checkpoint/completion paths and hashes. No loader or policy fallback and zero optimizer updates.','evaluation.py:recover_completed_model')
add('P18_source_and_dependency_rejoin',allph,'After all reads and genuine verifier checks, rejoin exact full sources/inputs/role hashes and prove no active writer/run; review final caller/Parent request/proofs/source/recovery and fresh resources immediately before ONE released dispatch.','job.py:_admitted')
add('P19_tensor_cursor_boundary',['continue100'],'Original loader must establish genuine cursor1/0, one epoch log, model/Adam/RNG contract before fit reservation; reference loader must establish100/0. Opaque metadata hashing cannot establish these tensor facts.','financial_wrapper_fixture.py:_one_epoch_state','Not claimed preclaim-verifiable here; unchanged genuine native loader checks after Run.start remain mandatory. Missing input detection can precede start, arbitrary future tensor/runtime failure cannot be ruled out.')
save('PRECLAIM_REFUSAL_MAP01.json',{'status':'EXACT_REQUIRED_PREDICATES_NOT_EXECUTED_ADMISSION','current_api_gap':True,'steps':steps,'source_only':True,'no_general_guarantee_against_future_runtime_failure':True})
delta=[]
for phase in ('complete100','continue100','predict'):
 old=next(x for x in s['original18_phases'] if x['task']=='classification' and x['backend']=='eager' and x['phase']==phase)
 delta.append({'logical_phase':old['logical_key_not_identity'],'original_slot_index':old['slot_index'],'original_identity':old['proposed_identity'],'future_fixed_identity':base['fixed_future_ids'][phase],'original_cell':old['proposed_cell'],'future_cell':base['fixed_future_cells'][phase],'original_dependencies':old['proposed_dependencies'],'new_declared_parent':base['genuine_parent_topology'][phase],'additional_actual_reference_dependency':base['fixed_future_ids']['complete100'] if phase=='continue100' else None,'original_scheduled_epochs_unchanged':100,'optimizer_updates_if_phase_completes':old['optimizer_updates_if_successful'],'original_phase_preserved_not_added':True,'paper_fit_credit':0})
save('ORIGINAL_PHASE_DELTA01.json',{'original_phase_count':18,'affected_original_slots':[x['original_slot_index'] for x in delta],'changes':delta,'unchanged_other_phase_records':15,'old_gate12_preserved':True,'future15entries_only_ifall3registered':True,'no_budget_extension_adopted':True})
save('INSPECTION_FAILURE01.json',{'tool_chunk':'f08c77','error':'TypeError: string indices must be integers, not str','expression':"[(e['id'],e.get('parent'),e.get('cells')) for e in g['experiments']]",'cause':'Read-only ad hoc printer treated genuine experiments dict as list; subsequent bounded investigation uses .items().','raw_files_changed':False,'no_runtime_or_registration_attempt':True})
(H/'REPORT01.md').write_text('''# Exact three-consumer input investigation

Current source is7b056a574e3e7b3c7ba209a39ee6a615e649d60c with the exact compatible02 helper/wrapper, unchanged training and reviewed watcher. All195 bodies were read and hashed;191 original paths remain byte-identical. The original12-entry gate is unchanged and stale for these new implementation hashes. No new registration, policy or proof was generated here.

INPUT_BODY_TEMPLATES01 supplies the original job structure and exact schema-valid plans for Root's three supplied identities. The reference uses the new reference cell with parent/prior/reference None. Continuation and prediction retain the original continued cell. Continuation's parent is permanently FAILED interrupt1 claimedrun; its separate reference is the new future COMPLETE100 identity. Prediction's parent is the future COMPLETE continuation. Namespace strings equal the fixed new identities and remain absent.

The authentic original18 contract identifies these logical phases at slots2,3,4. The new identities replace the operational definitions for those same required phases; no phase is removed or added. The old failed reference remains terminal. All12 old gate entries remain intact; adding all three prospective consumers produces15 definitions, not a new allowance. Three failures remain spent/highest19:16 existing allowances versus17 original requirements still needs separate reviewed cumulative20 before execution. No amendment occurs in this investigation.

ROLE_MAP01 records exact actual canonical paths, SHA256 and sizes for11 historical aliases: d390 claim,4b2 FAILED terminal, original4712 job,15fd selected plan,94a194-body closure, b2f7 checkpoint manifest,223ced42 state.pt493424B, fresh fit claim, planned failed-fit terminal, diagnostic and schedule. The original job/plan aliases must retain the claim's actual paths; no copied relative alias can silently change ancestry. The original interrupted checkpoint has one actual opaque member and full0a2 provenance. Its bytes were hashed, never decoded. A historical completion_input is explicitly None because no completed fit exists.

Minimum phase role counts are11 for reference,29 for continuation and17 for prediction. These counts include the original8 roles plus policy and two genuine proof roles. The29/17 denominators assume one member in each future completed checkpoint; actual future manifests must determine complete member sets and recalculated counts. Missing future checkpoint/provenance/path/hash fields stay NULL. These aliases are available-byte specifications, not already registered new inputs.

The original job bytes may be reused because the physical capsule and resource roots stay the same and plan_input remains wrapper_plan; role resolution can select the new plan path. New current source_closure must describe195 bodies, while the historical closure remains untouched. Model/training/recipe/environment/runtime metadata stay byte-identical; runtime compatibility still requires the genuine live readbacks. Reference, continuation and prediction must share the same195 closure bytes and policy before the first new reference. Later source/gate/input-only commits are distinguishable actual commits; they may preserve the implementation map, but no current/design or Git equality is fabricated.

MATERIAL PRECLAIM GAP: job._admitted115 and fixture.admitted46 check base job/plan/science/source/runtime. They do not invoke compatible02 _context, historical prior/reference verification or prediction parent-policy matching before start. lifecycle.start125 publishes claim before _check_inputs128. Therefore missing or malformed late dependencies can spend a claim unless Root executes a separately reviewed metadata/body preclaim checker. PRECLAIM_REFUSAL_MAP01 enumerates19 exact predicates with actual hashed source/line pointers and which native-only facts remain unproved. It is a concrete refusal specification, not an executed admission or a substitute ready=True receipt.

Root must prehash every registered input and descriptor-reference role, authenticate genuine historical/COMPLETE receipts and all original Git/source/claim joins, check the fixed policy/map/proof relations and final whole-source/caller/recovery/resource release, then rejoin bytes before dispatch. Worker held-lock checks remain mandatory. Original tensor cursor/model/Adam/RNG checks still occur through unchanged loaders in the genuine native guard; this metadata work cannot prove those values or guarantee an arbitrary future run cannot fail. No numerical package, array, label, checkpoint decode, Run, Owner, claim, network or live edit occurred.693 finite source/metadata/schema checks passed. The earlier dict/list printer error is retained explicitly.
''')
base.update({'source_readback_sha256':sha(H/'SOURCE_READBACK01.json'),'role_map_sha256':sha(H/'ROLE_MAP01.json'),'templates_sha256':sha(H/'INPUT_BODY_TEMPLATES01.json'),'preclaim_map_sha256':sha(H/'PRECLAIM_REFUSAL_MAP01.json'),'phase_delta_sha256':sha(H/'ORIGINAL_PHASE_DELTA01.json'),'report_sha256':sha(H/'REPORT01.md'),'preclaim_admission_gap':True,'preclaim_predicates':len(steps),'actual_policy_generated':False,'actual_registration_generated':False,'actual_proofs_generated':False,'actual_admission_performed':False});save('MACHINE01.json',base)
rows=[]
for root,dirs,files in os.walk(H,followlinks=False):
 for n in dirs+files:
  p=Path(root)/n;st=p.lstat();row={'path':str(p.relative_to(H)),'mode':stat.S_IMODE(st.st_mode)}
  if stat.S_ISDIR(st.st_mode):row['kind']='directory'
  elif stat.S_ISREG(st.st_mode):assert st.st_size<=4194304;row.update(kind='file',bytes=st.st_size,sha256=sha(p))
  else:raise ValueError('unexpected type')
  rows.append(row)
rows.sort(key=lambda x:x['path']);save('MANIFEST01.json',{'schema_version':1,'scope':'complete investigation except self manifest','members':rows,'typed_members':len(rows),'regular_files':sum(x['kind']=='file' for x in rows),'regular_bytes':sum(x.get('bytes',0) for x in rows)})
print(json.dumps({'manifest':sha(H/'MANIFEST01.json'),'machine':sha(H/'MACHINE01.json'),'report':sha(H/'REPORT01.md'),'role_map':sha(H/'ROLE_MAP01.json'),'preclaim_map':sha(H/'PRECLAIM_REFUSAL_MAP01.json'),'typed':len(rows)}))
