from pathlib import Path
import hashlib,json,stat
H=Path(__file__).resolve().parent;r=json.loads((H/'READBACK01.json').read_bytes());sha=lambda b:hashlib.sha256(b).hexdigest()
report='''# Actual two-scope flat05 outcome review

**Accepted actual narrow two-scope BYTE recovery.** Root's one completed flat operation is authenticated; no helper entry, restore, network, numerical import or research admission was rerun by the reviewer. This acceptance does not compose or reconstruct the old385 plus new9 Git-object basis.

Exact installed source17f4, immutable draft770f509c, genuine entry release18d36caf/manifestf745feaf, caller025a28c6, actual remote64c74556/selectiond2f64/Rootexit0f0eba and pinned input-mode profiled238 join. Actual intent/spawn bind parent1026972 and child1026975. Root terminald3952457 records child0/outer0, no cleanup failures and no primary failure; stdout4cbe5cc2 and empty stderr match actual hashes. Recorded parent FSIZE is4MiB soft/hard; child inheritance remains explicitly unobserved independently. Root terminal elapsed is0.743983630s; Root-supplied original tool-event attribution e38e0a/exit0 is distinct from these file-authenticated receipts.

The actual recoverye702f568 preserves all33 operational source-policy bodies plus31 failed-root bodies, in66 private files including their two metadata bodies. Metadata1a8b747d and8e243a07 exactly bind complete41typed and42descendant manifests respectively. Failed original root row is retained separately, giving43 original failed-root typed members. Every recovered body was independently read/hash/size/type/private-mode checked and joined to the original snapshot. Exact flat names have no missing, duplicate, foreign or partial members. All original directory modes, file modes, empty directories and source paths remain in metadata; physical flat files are0600/root0700, without a claim of POSIX tree reconstruction.

Both canonical archives are fully framed/footer-validated, and independently reconstructed using standard gzip/PAX TAR from the actual recovered flat bodies and original metadata. Compressed output matches immutable archivea60e1914 and06c8a9cd byte-for-byte. All83 typed descendants and64 original body hashes participate; no subset is relabeled a complete tree. The complete original failed init observed exitNULL, separate reap0, Rootexit1 and raw7491 remain unchanged after recovery.

Auxiliary sidecar72c91036 is authenticated independently of the helper's byte cohort: its exact hash, recovery binding and post-receipt observation qualify its own exclusion from that observation. Root actual terminal is authenticated separately. Original recovery.actual_root_exit staysNULL; numerical_release/whole_fit_capacity remainNULL and all POSIX/runtime/research authority flags remainfalse. Selected input mode history stays four0775/three0700 and all fifteen0600 bodies, with genuine remote review262160/231ae preserved.

The13 receipt observations,1 sidecar observation,1 final stdout observation and5 outer observations all satisfy fixed4MiB file/64MiB logical/96MiB allocated/10GiB floor/finite time and member bounds. Root's last observation excludes its subsequently written terminal body, as expected; no continuous quota or instantaneous whole-lifetime bound is inferred. Current whole-root census and floor recheck pass. Every recorded flat parent/child and prior remote Git/parent/receiver PID and matching process-group ID is absent at review. Unrecorded historical descendants/start ticks are not fabricated.

FLAT_FAILED and all withheld04 outer namespaces remain absent. Original remote03 is still permanently completed; caller04 remains withheld, prior remote02 permanentlyfailed, and no closed numerical phase is reopened. This acceptance supplies only actual byte-recovery evidence for the declared two scopes. Separate composed385+9 source/Git proof, genuine policy/input/registration/caller dependencies, runtime package-body preservation, numerical capacity and any future scientific/native release remain unproved here. No memory peak, wire measure, writer exclusion, financial result or paper credit is claimed.
'''
(H/'REPORT01.md').write_text(report)
m={'schema_version':1,'decision':'ACCEPTED_ACTUAL_TWO_SCOPE_BYTE_RECOVERY','reviewer':'combined_worker_review','owned_root':str(H.parent/'financial-wrapper-compatibility-operational-delta-root-remote03-2026-10-04'),'flat_receipt_sha256':r['flat_receipt_sha256'],'sidecar_sha256':r['sidecar_sha256'],'root_exit_sha256':r['root_exit_sha256'],'release_sha256':r['release_sha256'],'caller_sha256':'025a28c6a2c3d9ec296c895de086c003e23a25ecdd68b0743b8dec6f21cef9be','source_sha256':'17f4ee85d2408cdc1b678e107e82b6e19b674b4b941f1fa51f40f17bbedef282','remote_receipt_sha256':'64c74556c7060fc7d118b5b07354bb737e5c157446ffef8c27fe77ea6cef4d47','selection_sha256':'d2f64f4a7175ab13de9f40bcb7c700dc615197c61e65c39456233a21617bb23b','source_commit':'7b056a574e3e7b3c7ba209a39ee6a615e649d60c','policy_sha256':'ae8fbdc9d13e75fc453b70b5ee633c89fb4577e9b68a35b4147cf1bbd58c6887','original_regular_bodies':64,'physical_regular_files':66,'typed_descendants':83,'failed_original_members_including_root':43,'all_canonical_archives_match':True,'actual_child_exit':0,'actual_outer_exit':0,'original_receipt_actual_root_exit':None,'cleanup_failures':[],'observed_all_recorded_pids_groups_absent':True,'readback_sha256':sha((H/'READBACK01.json').read_bytes()),'report_sha256':sha((H/'REPORT01.md').read_bytes()),'assertions':r['assertions'],'composed_git385_plus9_proof':None,'runtime_package_bodies':False,'posix_tree':False,'numerical_authority':False,'further_entry_release':False,'qualification':'Actual narrow ordinary two-scope BYTE recovery only; separate complete source composition/authority/recovery and numerical release remain required.'}
(H/'MACHINE01.json').write_text(json.dumps(m,indent=2,sort_keys=True)+'\n');rows=[]
for p in sorted(H.rglob('*')):
 if p==H/'MANIFEST01.json':continue
 s=p.lstat();z={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):z['kind']='directory'
 elif stat.S_ISREG(s.st_mode):z.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()))
 else:raise AssertionError(p)
 rows.append(z)
(H/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'members':rows,'exclusion':'self only; all source/raw controls and exact exported actual metadata bodies retained'},indent=2,sort_keys=True)+'\n');print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'readback':m['readback_sha256'],'report':m['report_sha256'],'members':len(rows)}))
