"""Read-only original source/Git/opaque bodies; no actual recovery proof or decode."""
import hashlib,json,stat,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=F/'held-consumer-flat-git-root-specification01-2026-10-03';helper=F/'held-consumer-flat-git-recovery-preparation01-2026-10-03';sys.path.insert(0,str(helper));import archive03 as a
from bounded_git01 import git
H=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(ok,label):
 assert ok,label
 checks.append(label)
raw=(P/'EXPECTED01.json').read_bytes();ck(H(raw)=='d4c2ad952d50a4f3c813ca188a9ebded94c6f1c356b8c645c3b684a048244227','exact Root worksheet');e=json.loads(raw);ck(a.encode(e)==raw,'canonical worksheet');template=json.loads((helper/'EXPECTED_ORIGINAL_TEMPLATE01.json').read_bytes());ck({k:v for k,v in e.items() if k!='current'}=={k:v for k,v in template.items() if k!='current'},'only current differs from original template');ck(len(e['current'])==246,'current246')
qraw=(F/'held-consumer-final-baseline-root-capture01-2026-10-03/REQUEST01.json').read_bytes();ck(H(qraw)=='3d5481584c69034d696276431465064d01788e0fd651bdc8fe7df203bc52bf71','actual accepted capture request');q=json.loads(qraw);a.request(q);ck(H(a.encode(q['capsule_manifest']))=='0ed39e3bb1f374f5eb3df1ff2053e0533804cc18df152dc8179b26598d94169e','accepted capsule manifest');manifest={r['path']:r for r in q['capsule_manifest']['members']};cap=Path(q['capsule_root']);source=e['source'];ck(source==q['source']==a.SOURCE,'exact source join')
head=git(cap,['rev-parse','HEAD'],cap=128).decode().strip();ck(head==source,'actual unchanged initialHEAD');tree=git(cap,['ls-tree','-r','-z',source]);ck(tree.endswith(b'\0'),'actual tree framing');actual={}
for item in tree.split(b'\0')[:-1]:
 left,name=item.split(b'\t',1);mode,kind,oid=left.decode().split();name=name.decode();a.path_name(name);ck(kind=='blob' and mode in ('100644','100755'),'actual tracked regular '+name);ck(name not in actual,'unique actual tree '+name);actual[name]=(mode,oid)
ck(len(actual)==246 and set(actual)=={r['path'] for r in e['current']},'entire actual246 roster');joined=[]
for offset in range(0,246,128):
 group=e['current'][offset:offset+128];request=''.join(source+':'+r['path']+'\n' for r in group).encode();raw=git(cap,['cat-file','--batch'],request);pos=0
 for r in group:
  name=r['path'];ck(set(r)=={'path','git_mode','object','bytes','sha256'},'exact fields '+name);end=raw.index(b'\n',pos);header=raw[pos:end].split();ck(len(header)==3 and header[1]==b'blob','blob header '+name);n=int(header[2]);start=end+1;body=raw[start:start+n];ck(n==r['bytes']<=a.FILE and raw[start+n:start+n+1]==b'\n','opaque extent '+name);oid=hashlib.sha1(b'blob '+str(n).encode()+b'\0'+body).hexdigest();ck(oid==header[0].decode()==r['object'] and (r['git_mode'],oid)==actual[name] and H(body)==r['sha256'],'actual tree/OID/hash '+name)
  mr=manifest[name];ck(mr['kind']=='file' and mr['bytes']==n and mr['sha256']==r['sha256'] and r['git_mode']==('100755' if mr['mode']&0o100 else '100644'),'captured manifest exact '+name);live=a.read(cap,name);s=(cap/name).lstat();ck(live==body and stat.S_IMODE(s.st_mode)==mr['mode'],'original live body/mode '+name);joined.append(name);pos=start+n+1
 ck(pos==len(raw),'complete bounded batch response')
head_after=git(cap,['rev-parse','HEAD'],cap=128).decode().strip();ck(head_after==head,'actual unchanged finalHEAD');ck((P/'EXPECTED01.json').read_bytes()==(P/'EXPECTED01.json').read_bytes() and H((P/'EXPECTED01.json').read_bytes())=='d4c2ad952d50a4f3c813ca188a9ebded94c6f1c356b8c645c3b684a048244227','worksheet final hash')
reg=json.loads(a.read(cap,q['registration']));ex=reg['experiments']['original-import-held-success-20261003-01'];refs=dict(ex['source_files']);refs[q['registration']]=q['registration_sha256'];lookup={r['path']:r for r in e['current']};ck(len(refs)==205 and all(lookup[n]['sha256']==h for n,h in refs.items()),'all205 source registration rows');ck(len(ex['inputs'])==33,'33 input roles');ck(e['historical']['claims']==json.loads((F/'held-consumer-historical-admission-closure-investigation01-2026-10-03/COPY_PLAN01.json').read_bytes())['claims'],'original four claims preserved');ck(len(e['historical']['lookups'])==638 and len(e['selected_c6']['rows'])==26,'638/26 preserved')
result={'status':'WORKSHEET_ACCEPTED_READ_ONLY_ORIGINAL_JOINS_SPEC_PENDING','expected_sha256':H((P/'EXPECTED01.json').read_bytes()),'request_sha256':H(qraw),'capsule_manifest_sha256':q['capsule_manifest_sha256'],'source_before':head,'source_after':head_after,'current_rows':len(joined),'source_registration_rows':205,'input_roles':33,'historical_rows':638,'selected_c6_rows':26,'original_failed_claims':4,'check_count':len(checks),'opaque_bytes':sum(r['bytes'] for r in e['current']),'recovered_git_proof_executed':False,'origin_or_native_authority':False};(O/'WORKSHEET_READBACK01.json').write_text(json.dumps(result,sort_keys=True,indent=2)+'\n');print(json.dumps(result,indent=2))
