import ast,gzip,hashlib,io,json,os,stat,sys,tarfile
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=F/'financial-genuine-wrapper-root-claimedrun-witness-capture01-2026-10-04';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';sys.path.insert(0,str(U));import recovery04 as a
sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
def read(p):return a.read(p.parent,p.name)
for n,pin in [('recovery04.py','b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a'),('owned_io.py','09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb'),('bounded_git01.py','db4a65a450bf9930abac04ab794539ebd952b07826d7314b4aea4e989dd9240f')]:ck(sha(read(U/n))==pin,'exact unchanged primitive')
ck(sha(read(P/'capture01.py'))=='e4ee138df24ab2ce90c105fceb294ceb0749b2a541f7541b73afea723032d7cb','actual installed accepted helper');t=ast.parse(read(F/'held-consumer-final-released-scope-capture-review01-2026-10-03/check01.py'));exec(compile(ast.Module(body=[n for n in t.body if isinstance(n,ast.FunctionDef) and n.name in ('decode','recode')],type_ignores=[]),'<independent framing>','exec'))
auth=json.loads(read(P/'UNION_AUTHENTICATION01.json'));m=json.loads(read(P/'union-manifest.json'));raw=read(P/'union.tar.gz');ck(sha(raw)=='31560b60726b07f2ce060c9a814f5e7cab114cd88c75c85061642712651b7ff4' and len(raw)==1001788,'actual archive hash/extent');ck(sha(read(P/'union-manifest.json'))=='1c40420ce467c8c84e0120903983ce2877c9f64020cf9a30e35d1cf339c01ee3','actual manifest');ck(auth['archive']=={'bytes':len(raw),'sha256':sha(raw),'manifest_sha256':sha(read(P/'union-manifest.json'))},'actual auth chain');ck(a.scan(P/'union-bytes01')==m,'full live union before');bodies,framing=decode(raw,m);ck(recode(m,bodies)==raw,'complete canonical compressed raw inverse')
for r in m['members']:
 p=P/'union-bytes01'/r['path'];ck(stat.S_IMODE(p.lstat().st_mode)==r['mode'],'actual union literal mode')
 if r['kind']=='file':ck(read(p)==bodies[r['path']],'all actual union saved bodies')
ck(a.scan(P/'union-bytes01')==m,'full live union after');mapping=json.loads(bodies['ORIGINAL_TREES01.json']);ck(sha(bodies['ORIGINAL_TREES01.json'])==auth['union_mapping_sha256'],'actual mapping pin');ck(mapping['source_full_recovery_readback_sha256'] is None and mapping['source_commit']=='0a2e7639b42b9423b90743feadcda4078aa21816' and mapping['links_followed_or_extracted'] is False,'no false recovery or link authority')
ns={'__name__':'source_definitions','__file__':str(P/'capture01.py')};exec(compile(read(P/'capture01.py'),'<helper definitions only>','exec'),ns);ck({t['scope']:Path(t['original_root']) for t in mapping['scope_trees']}==ns['SCOPES'],'exact four actual root scopes');regular=0;links=[];typed=0;total=0;wanted={'ORIGINAL_TREES01.json'}
for tree in mapping['scope_trees']:
 root=Path(tree['original_root']);ck(root.resolve()==root,'canonical actual original');observed=[]
 def walk(p,n):
  st=p.lstat();r={'path':n,'mode':stat.S_IMODE(st.st_mode)}
  if stat.S_ISDIR(st.st_mode):r['kind']='directory';observed.append(r);[walk(c,c.name if n=='.' else n+'/'+c.name) for c in sorted(p.iterdir(),key=lambda p:p.name)]
  elif stat.S_ISLNK(st.st_mode):r.update(kind='lexical-symlink',target=os.readlink(p));observed.append(r)
  else:b=read(p);ck(stat.S_ISREG(st.st_mode) and st.st_nlink==1,'actual regular original');r.update(kind='file',bytes=len(b),sha256=sha(b),union_path=tree['scope']+'/'+n);observed.append(r)
 walk(root,'.');observed.sort(key=lambda r:r['path']);ck(observed==tree['members'],'all original typed members/bodies/modes/targets current complete')
 for r in observed:
  typed+=1
  if r['kind']=='file':regular+=1;total+=r['bytes'];wanted.add(r['union_path']);ck(bodies[r['union_path']]==read(root/r['path']),'exact current-original to archive bytes')
  elif r['kind']=='lexical-symlink':links.append({'scope':tree['scope'],**r});ck(tree['scope']+'/'+r['path'] not in bodies,'literal target not instantiated')
ck(set(n for n,r in ((r['path'],r) for r in m['members']) if r['kind']=='file')==wanted,'no extra or missing ordinary union files');ck((typed,regular,len(links))==(234,186,13) and auth['ordinary_members']==len(m['members'])==222,'complete typed denominator');ck(total==mapping['original_regular_logical_bytes']==4296757,'full original byte count')
cap=ns['SOURCE_CAPTURE'];ck(sha(read(cap/'source.tar.gz'))==mapping['source_archive_sha256']=='b5b6aad2f515447dc6566cfb716a20ef90031313d48f1ac903ab756735431e24','actual Source339 completearchive chain');ck(sha(read(cap/'source-manifest.json'))==mapping['source_manifest_sha256']=='fdf77348b81a4d6df8b420b98530f5485900a0461636e1c201506106b036dfd8','actual Source339 manifest chain');a.same(ns['SOURCE'],json.loads(read(cap/'source-manifest.json')))
for n,pin in [('MANIFEST01.json','24e6451d2a9c5ec516b99ca95bb477567e5f9ef5d13adef3bb41c0633b93e5c7'),('INDEPENDENT_SOURCE_INPUT_RUNTIME01.json','059232d0f7fc8922cee526a1bd30fef2ecb51ee17103284bcaac18c77e77641c')]:ck(sha(read(ns['SOURCE_REVIEW']/n))==pin,'actual metadata proof chain')
out=read(P/'ACTUAL_CAPTURE01.out');err=read(P/'ACTUAL_CAPTURE01.err');printed=json.loads(out);ck(err==b'' and printed=={'status':auth['status'],'archive':auth['archive'],'original_trees':4,'original_regular_members':186,'original_lexical_links':13},'actual raw stdout/empty stderr exact auth joins');ck(auth['free_bytes']>=10*1024**3 and auth['genuine_native_or_numerical_started'] is False,'actual receipt floor/nonnumerical scope')
x={'schema_version':1,'decision':'ACCEPTED_ACTUAL_COMPLETE_FOUR_HANDOFF_WITNESS_LOCAL_BYTE_CAPTURE','archive':auth['archive'],'authentication_sha256':sha(read(P/'UNION_AUTHENTICATION01.json')),'mapping_sha256':auth['union_mapping_sha256'],'source_sha256':sha(read(P/'capture01.py')),'checks':len(checks),'ordinary_members':222,'ordinary_files':187,'original_trees':4,'original_typed_members':234,'original_regular_members':186,'original_literal_links':links,'original_regular_bytes':total,'raw_framing':framing,'stdout_sha256':sha(out),'stderr_sha256':sha(err),'reported_original_tool':{'session':98488,'start':'eecc9d','completion':'86f75b','exit':0,'provenance':'Root report; separate persisted terminal pending at review start'},'original_os_pid_ticks_group':'unobserved/unavailable; not inferred from session','source339_current_unchanged':True,'source339_full_recovery':None,'external_recovery':False,'Parent_or_final_caller_recovery':False,'numerical_release':False};(O/'READBACK01.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');print(json.dumps({'checks':len(checks),'decision':x['decision']}))
