from pathlib import Path
import hashlib,json,stat
D=Path(__file__).resolve().parent;F=D.parent;B=F/'financial-wrapper-complete100-final-supplement-capture01-2026-10-04';h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();r=json.loads((D/'READBACK01.json').read_bytes());c=json.loads((D/'CURRENT03.json').read_bytes());p=json.loads((D/'PAX_FINDING01.json').read_bytes())
report='''# Final complete100 supplement: actual local preservation review

The complete local contract and support snapshots and their canonical archives are accepted as byte-preservation evidence. This is not external recovery, flat restoration, or numerical release.

The contract retains all three original files (394,056 bytes); support retains all nine original closed review trees and the cumulative review plus its original-path mapping (287 typed members, 242 files, 4,868,119 bytes). Exact original root modes, nested directory/file modes, paths, sizes and body hashes agree. Every archive effective member agrees with the complete manifest and snapshot. Independent deterministic gzip/PAX reencoding reproduces both archives byte for byte. The seven required external bodies total 1,063,336 bytes and imply 25 bounded Git operations.

The final request 34d1a856, independent release f7e5b3d3 and contract 6da30ea8 agree with the actual proof bodies. The existing baseline full-recovery proof 49e0ad65 remains unchanged. The supplement is a separate future Root dispatch predicate, not a recursive replacement for q.proofs.full_recovery. The actual nine-file Parent is unchanged against the accepted baseline. A separate full current non-Git capsule census rejoins all 443 members/367 bodies with that baseline, including both failed claims, source/gate metadata and unchanged cumulative accounting (two spent claims, highest allowance 19). No claim or admission was invoked.

A real compatibility failure is retained: CHECK01.err records original b40 R4 framed_members refusing the support archive with “noncanonical raw member slash/type”. PAX_FINDING01 identifies one canonical regular header whose truncated raw name ends with a slash; its effective authenticated PAX path ends with the ordinary filename opaque. The original archive is canonical and unchanged, not corrupt. CHECK02 uses an independent stdlib effective-path parse and exact canonical reencoding, not a silently substituted recovery implementation. The older b40 recovery caller is NOT accepted for this support archive. A separately reviewed exact caller binding to the accepted narrow PAX-aware recovery module is required before actual restoration; the installed scientific Parent helper must remain unchanged.

Checks comprise 1,703 local snapshot/archive/original/proof checks and the additional current-capsule checks recorded in CURRENT03.json. CHECK01 is an authentic failed compatibility test, not a passing check. CHECK02 and CURRENT03 have empty stderr. PAX parsing inspection did not restore files or decode checkpoints. All source histories, raw failures and original terminal nulls remain preserved.

Remaining requirements: actual bounded external transfer and independent review of its committed-body joins, an independently accepted PAX-compatible restore caller and exact flat release, fresh complete flat recovery and independent outcome review, then Root's separate native eligibility and one-use dispatch checks. No OS readiness, runtime-body recovery, POSIX recreation, full numerical capacity, scientific completion or fit credit follows from this local acceptance.
''';(D/'REPORT01.md').write_text(report)
m={'schema_version':1,'decision':'ACCEPTED_LOCAL_CANONICAL_FINAL_SUPPLEMENT_PRESERVATION_WITH_B40_RESTORE_INCOMPATIBILITY','capture_sha256':h(B/'CAPTURE01.json'),'readback_sha256':h(D/'READBACK01.json'),'current_capsule_sha256':h(D/'CURRENT03.json'),'pax_finding_sha256':h(D/'PAX_FINDING01.json'),'report_sha256':h(D/'REPORT01.md'),'checks':r['checks']+c['checks'],'contract':r['contract'],'support':r['support'],'baseline_full_recovery_unchanged':r['full_recovery_bound'],'local_complete_byte_preservation':True,'original_b40_restore_compatible':False,'actual_external_recovery':None,'actual_flat_recovery':None,'numerical_release':None,'claim_or_admission_invoked':False,'failed_harnesses':['check01.py / CHECK01.err: authentic original b40 framing refusal'],'qualification':'Exact canonical archive acceptance only; separately reviewed PAX-aware restoration required. No scientific or capacity authority.'};(D/'MACHINE01.json').write_text(json.dumps(m,indent=2,sort_keys=True)+'\n')
rows=[]
for x in sorted(D.rglob('*')):
 if x==D/'MANIFEST01.json':continue
 s=x.lstat();row={'path':x.relative_to(D).as_posix(),'mode':stat.S_IMODE(s.st_mode),'kind':'directory' if stat.S_ISDIR(s.st_mode) else 'file'}
 if row['kind']=='file':row.update(bytes=s.st_size,sha256=h(x))
 rows.append(row)
(D/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'root_mode':stat.S_IMODE(D.stat().st_mode),'members':rows},indent=2,sort_keys=True)+'\n');print(json.dumps({'machine':h(D/'MACHINE01.json'),'manifest':h(D/'MANIFEST01.json'),'report':h(D/'REPORT01.md'),'checks':m['checks'],'members':len(rows),'capture':m['capture_sha256']}))
