import json,hashlib,stat
from pathlib import Path
D=Path(__file__).resolve().parent;F=D.parent;H=F/'heartbeat-root-checkpoint10-2026-10-04';a=json.loads((D/'ACTUAL_ADMISSION01.json').read_bytes());p=json.loads((D/'PRECHECK01.json').read_bytes());q=json.loads((D/'POSTCHECK01.json').read_bytes());sha=lambda b:hashlib.sha256(b).hexdigest();enc=lambda v:(json.dumps(v,sort_keys=True,indent=2)+'\n').encode();S=Path(a['root']);E=D/'source-evidence';E.mkdir()
for n in ('REFERENCE_GATE_ADOPTION01.json','REFERENCE_GATE_ADOPTION01_INTENT.json'):(E/n).write_bytes((H/n).read_bytes())
for n in ('job.py','financial_wrapper_fixture.py'):(E/n).write_bytes((S/'tradingagents/research/onchain_replication'/n).read_bytes())
(E/'gates.json').write_bytes((S/a['registration']).read_bytes())
terminal={'schema_version':1,'actual_tool_chunk':'bbeb16','actual_exec_return_exit_code':0,'actual_stdout_sha256':sha((D/'ADMIT01.out').read_bytes()),'actual_stderr_sha256':sha((D/'ADMIT01.err').read_bytes()),'actual_readback_sha256':sha((D/'ACTUAL_ADMISSION01.json').read_bytes()),'actual_api_calls':1,'actual_OS_PID':None,'PID_start_ticks':None,'qualification':'Actual ordinary metadata-only subprocess returned exit0. No recorded OS process history is invented; no native numerical job was launched.'};(D/'ACTUAL_CALL_TERMINAL01.json').write_bytes(enc(terminal))
m={'schema_version':1,'decision':'ACCEPTED_ACTUAL_GATE_ONLY_SOURCE_AND_GENUINE_READONLY_COMPLETE100_ADMISSION','identity':a['experiment_id'],'source':a['source'],'design_source':a['design_source'],'root':a['root'],'registration':a['registration'],'registration_sha256':a['registration_sha256'],'ready':a['ready'],'actual_job_admitted_calls':1,'actual_admission_readback_sha256':sha((D/'ACTUAL_ADMISSION01.json').read_bytes()),'actual_call_terminal_sha256':sha((D/'ACTUAL_CALL_TERMINAL01.json').read_bytes()),'prerequisite_failed_recovery_review_manifest_sha256':'3990bed86ee8aa873c7ed28c6170a9e67c478cc64f338eef61f3f8af3a6a51b9','conditional_handoff_review_manifest_sha256':'a8cedd365c750f58ec8e3e2afa492abf2ac2e5a072b9f8f72509c0a39accfc1d','tracked_source_files':339,'unchanged_source_pins':338,'implementation_files':194,'package_files':149,'input_roles':8,'runtime_RECORD_metadata_hashes_verified':251,'interpreter_read_bound_bytes':67108864,'base_attempt_budget':a['family']['attempt_budget'],'prior_attempts':a['family']['prior_attempts'],'effective_attempt_budget':a['effective_attempt_budget'],'actual_spent_claims':2,'highest_actual_prior_allowance':19,'remaining_existing_allowance':17,'whole_source_before_after_equal':True,'new_claim_or_output_reserved':False,'new_numerical_imports':False,'ResearchRun_start_called':False,'Owner_constructed':False,'new_parent':None,'new_source_and_caller_external_recovery':None,'new_release':None,'native_capacity':None,'checks':p['checks']+q['checks'],'paper_fit_credit':0,'qualification':'Genuine readonly admission only. Actual Torch/CUDA inventory, native resource release, Parent/caller and complete current source/caller recovery remain separate.'};(D/'MACHINE01.json').write_bytes(enc(m))
(D/'REPORT01.md').write_text('''# Complete100 gate adoption and genuine readonly admission

**Accepted the actual same-root gate-only adoption and one genuine metadata-only admission.** Source and design are9dc5c79f738920b52947b4e63fed0397f1b5b207, direct child of original0a2. The only committed change is fixture_inputs/financial_wrapper_claimedrun01/gates.json, whose752c34df bytes equal the independently reviewed draft. All339 tracked objects remain, with338 source pins byte/mode-identical,194 implementation files and149 package files unchanged. The original full failed history and every non-Git member other than the authorized gate are preserved.

All prerequisites were checked before the call, including complete failed-outcome recovery3990bed8, conditional handoffa8cedd36, actual Root adoption9a6824f1 and intent a7ef584b, all eight inputs, original model20f451 and trainingd527, source closure, charter, existing cumulative19 review and two spent terminal claims. The interpreter was read within the explicit64MiB metadata bound. All251 installed RECORD byte hashes match the frozen runtime mapping. This does not rehash every dependency body or observe current Torch/CUDA execution.

The exact isolated source's job._admitted was invoked once from the actual capsule working directory with the unused original financial-wrapper-classification-eager-complete100-20261003-01 identity and new source9dc5. It returned a genuine ready Admission with equal source/design, bindings null,338 pins,8 roles and effective ceiling19. The plan is eager classification complete100 with no prior checkpoint or reference input. Base18/prior0, two spent claims, highest actual19 and remaining17 are unchanged; no allowance was minted or refunded.

The call used the pinned interpreter and actual source modules. An import guard refused any unexpected NumPy/Torch/SciPy import; none occurred. No ResearchRun.start, Owner, namespace reservation, tensor/checkpoint decoding, native launch or numerical update was performed. Real CLI-argument fields were passed to the original API; no Admission/Run/Binding object was fabricated. The actual tool chunkbbeb16 returned0 with empty stderr. Original OS PID/start ticks were not observed and remain null in the ordinary call receipt.

There are2,827 source, prerequisite and post-call checks, plus the original actual admission predicates. A full before/after non-Git member/name/mode/body comparison is equal. Both original claims remain FAILED and the new claim/output namespaces remain absent. The runtime limits are unchanged:3GiB native high=max,3GiB reserve/6GiB startup,10GiB disk floor,1800seconds,4MiB files and1GiB logical/allocated whole-storage envelope. These are policy checks, not actual capacity observations or eligibility.

The original Parent and claimd390 were not reused as new authority. A new exact caller/Parent contract, whole current source and caller preservation/recovery, fresh capacity preflight and genuine final release remain pending. No paper fit credit or new numerical permission follows from this readonly admission proof.
''')
rows=[]
for f in [D]+sorted(D.rglob('*')):
 if f.name=='MANIFEST01.json':continue
 s=f.lstat();r={'path':'.'if f==D else f.relative_to(D).as_posix(),'mode':stat.S_IMODE(s.st_mode),'kind':'directory'if f.is_dir()else'file'}
 if r['kind']=='file':r.update(bytes=s.st_size,sha256=sha(f.read_bytes()))
 rows.append(r)
(D/'MANIFEST01.json').write_bytes(enc({'schema_version':1,'self_excluded':True,'members':rows}));print(json.dumps({'machine_sha256':sha((D/'MACHINE01.json').read_bytes()),'manifest_sha256':sha((D/'MANIFEST01.json').read_bytes()),'actual_admission_sha256':sha((D/'ACTUAL_ADMISSION01.json').read_bytes()),'members':len(rows),'checks':m['checks']}))
