from pathlib import Path
import json,hashlib,statistics,math
ROOT=Path.cwd();R=Path(__file__).resolve().parent;C=R.parent/'matching-pair-route-profile01-2026-10-09';j=lambda p:json.loads(p.read_bytes());h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();m=j(C/'MANIFEST01.json');d=j(C/'RESULT02.json');ev={}
for n,v in m['files'].items():assert h(C/n)==v['sha256'] and (C/n).stat().st_size==v['bytes'];ev[str((C/n).relative_to(ROOT))]=v['sha256']
for p,v in d['source_refs'].items():assert h(ROOT/p)==v;ev[p]=v
assert d['affinity']==[2] and d['authority_poll'] is None and d['checkpoint_calls']==0 and d['all_result_bits_equal'] is True
cfg=j(ROOT/'research/onchain-paper-replication-2026-09-24/config/matching-stable.json');stage=j(ROOT/'research/onchain-paper-replication-2026-09-24/full_sources/real-data-pilot-capacity-selection03-2026-10-08/compact_policy.json')['stage_policy'];cfg['max_pair_entries']=stage['pair']['max_pair_entries_override'];assert cfg==d['config'];assert d['policy']=={k:v for k,v in stage['pair'].items() if k!='max_pair_entries_override'} and d['schedule']==stage['schedule'];assert d['schedule']['operations_per_call']==1000000 and d['schedule']['calls_per_checkpoint']==10000
assert len(d['raw_route'])==len(d['raw_staged'])==len(d['raw_components'])==12
for shape in ((4,5),(8,7)):
 rr=[r for r in d['raw_route'] if tuple(r['shape'])==shape];ss=[r for r in d['raw_staged'] if tuple(r['shape'])==shape];cc=[r for r in d['raw_components'] if tuple(r['shape'])==shape];assert [r['rep'] for r in rr]==list(range(6));summary=d['summary'][str(shape)]
 for k,v in summary['route_medians'].items():assert statistics.median(r[k] for r in rr)==v
 assert statistics.median(t for r in rr for t in r['memo_hits'])==summary['memo_hit_median'] and sum(len(r['memo_hits']) for r in rr)==24
 for k,v in summary['staged_medians'].items():assert statistics.median(sum(r[k]) if k=='advance' else r[k] for r in ss)==v
 for k,v in summary['independent_component_medians'].items():assert statistics.median(r[k] for r in cc)==v
for k,v in m['cumulative_measured_route_seconds'].items():assert sum(sum(r[k]) if k=='memo_hits' else r[k] for r in d['raw_route'])==v
assert 'ValueError: pair policy schema' in (C/'RUN01.log').read_text()
name='eth-paper-real-data-end-to-end-resource-20261009-26';outcome=j(R.parent/'real-data-pilot-full26-outcome-review01-2026-10-09/OUTCOME_REVIEW01.json');summary=outcome['scientific_disposition']['numeric_batch_summary'];assert summary['elapsed_seconds']/4096==m['actual26_mixed_call_mean_seconds_for_context'];assert summary['computed']==4000 and summary['reused']==96
for p in (C/'MANIFEST01.json',R.parent/'real-data-pilot-full26-outcome-review01-2026-10-09/OUTCOME_REVIEW01.json'):ev[str(p.relative_to(ROOT))]=h(p)
r={'status':'PASS_READ_ONLY_ARITHMETIC_SOURCE_JOINS','evidence':ev,'actual26_mixed_mean_seconds':summary['elapsed_seconds']/4096,'summary':d['summary'],'source_count':len(d['source_refs']),'timer_scopes':['Direct timer includes purpose hash construction and PairExecutor call; executor construction outside.','Memo miss/hit includes purpose hash construction,validation/key/call; constructor,begin,end measured separately;close untimed.','Staged sequence times original numerical functions separately; cleanup timed; not nested attribution of original direct/memo calls.','Bare state construction excluded; private advance only timed; completion asserted but bare result bits not compared.'],'limitations':['Real26 summary elapsed excludes/integrates different source-era wrapper scopes; not population pair distribution or a matched experiment.','No genuine authority polling measured:authority_pollNone throughout.','Bit equality is the retained script assertion outcome, not a stored per-result score corpus.','CPU2 self-observation is retained; launcher resource/timeout enforcement requires separate evidence, absent from supplied scripts/logs/manifest.']};(R/'CHECK01.json').write_text(json.dumps(r,indent=2)+'\n');print(json.dumps({'source_count':len(d['source_refs']),'means_checked':True,'medians_checked':True,'repetitions':12,'hits':48}))
