import ast,hashlib,json,os,shutil,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();P=F/'financial-genuine-wrapper-root-recordfix-failed-scope-capture01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
def sig(s):return (s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns)
def read(p):
 s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4*1024**2 and p.resolve()==p,'regular canonical bounded input');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW)
 try:
  ck(sig(os.fstat(fd))==sig(s),'actual opened identity');out=[];total=0
  while True:
   b=os.read(fd,65536)
   if not b:break
   total+=len(b);ck(total<=s.st_size,'bounded extent');out.append(b)
  ck(sig(os.fstat(fd))==sig(s)==sig(p.lstat()) and total==s.st_size,'stable body identity');return b''.join(out)
 finally:os.close(fd)
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never',*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1','GIT_TERMINAL_PROMPT':'0'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'bounded local Git only');return r.stdout
import importlib.util
D=F/'financial-genuine-wrapper-root-claimedrun-capsule-history-preparation02-2026-10-04';FD=F/'financial-genuine-wrapper-root-claimedrun-capsule-history-preparation01-2026-10-04';S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-recordfix-native-20261004-01/source');N=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');H='649fb8a11089524aaef7843dffeeb90a3a55ca17';ID='financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01';V=F/'financial-genuine-wrapper-claimedrun-history-copy-admission-review01-2026-10-04';RP=F/'held-consumer-final-recovery-preparation04-2026-10-03';sys.path.insert(0,str(RP));sp=importlib.util.spec_from_file_location('actual_history_r4',RP/'recovery04.py');a=importlib.util.module_from_spec(sp);sp.loader.exec_module(a)
readbackraw=read(D/'READBACK01.json');relraw=read(D/'RELOCATION01.json');ck(sha(readbackraw)=='fb3d38ba6338f8640d45fb9b8ed76e7c50bc834272d0c75e2e3b720aa0e6f34b' and sha(relraw)=='d3612b77042edef19f3945eeb64d930623bc066f37b049478c0cbde4c678f0d3','actual original preparation readback/relocation pins');rb=json.loads(readbackraw);rel=json.loads(relraw);terminalraw=read(D/'ACTUAL_TERMINAL01.json');t=json.loads(terminalraw);intent=json.loads(read(D/'INTENT01.json'));ck(t['actual_exit']==0 and t['actual_session']==60580 and t['actual_start_tool']=='5d8114' and t['actual_completion_tool']=='288742' and t['actual_destination_readback_sha256']==sha(readbackraw) and t['actual_relocation_sha256']==sha(relraw),'actual original source preparation tool receipt');ck(t['actual_root_pid']==intent['pid']==377661 and not Path('/proc/377661').exists() and t['qualified_original_pid_start_ticks_or_group_history'] is None,'actual recorded PID now absent; start/group unavailable unchanged')
ck(sha(read(D/'PREPARATION01.py'))=='e85ceefb44c12f0fe886021f84133e8bbaa13257c844a849fcdcbd04e9e1e199','exact reviewed successor source actually retained');ck(sha(read(O/'MANIFEST01.json'))=='1447595f89e568867d6f3dcaa21061080ef47f43660b8d2e1334f332a989c3e8','original source review immutable')
baseline=json.loads(read(F/'financial-genuine-wrapper-root-recordfix-failed-scope-capture01-2026-10-04/source-manifest.json'));a.same(S,baseline);destination=a.scan(N);ck(N.resolve()==N and stat.S_IMODE(N.parent.lstat().st_mode)==0o700 and (N/'.git').is_dir() and not (N/'.git').is_symlink() and not os.path.lexists(N/'.git/objects/info/alternates') and not os.path.lexists(N/'.git/shallow'),'actual private standalone canonical destination Git');gs=json.loads(read(V/'GIT_ANCESTRY_SPEC01.json'));ck(git(['-C',str(N),'rev-parse','HEAD']).decode().strip()==H and git(['-C',str(S),'rev-parse','HEAD']).decode().strip()==H,'actual unchanged source HEADs');ck(git(['-C',str(N),'rev-list','--parents',H]).decode().splitlines()==gs['ancestry_lines'] and len(gs['ancestry_lines'])==6,'actual copied full six-commit ancestry');objects=gs['objects'];reply=b''.join(git(['-C',str(N),'cat-file','--batch'],(''.join(r['oid']+'\n' for r in objects[i:i+40])).encode()) for i in range(0,len(objects),40));offset=0
for r in objects:
 end=reply.index(b'\n',offset);oid,kind,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2;ck(oid==r['oid'] and kind==r['type'] and size==r['bytes'] and sha(b)==r['content_sha256'] and hashlib.sha1(kind.encode()+b' '+str(size).encode()+b'\0'+b).hexdigest()==oid,'actual each363 destination object extent/hash/OID')
ck(offset==len(reply) and len(objects)==363,'complete object recovery graph');tree=git(['-C',str(N),'ls-tree','-r','-z',H]);ck(tree==git(['-C',str(S),'ls-tree','-r','-z',H]),'actual identical tracked tree');tracked=[];modecounts={}
for item in tree.split(b'\0'):
 if not item:continue
 meta,n=item.split(b'\t');mode,kind,oid=meta.decode().split();name=n.decode();raw=read(N/name);s=(S/name).lstat();d=(N/name).lstat();ck(kind=='blob' and raw==read(S/name) and hashlib.sha1(b'blob '+str(len(raw)).encode()+b'\0'+raw).hexdigest()==oid and stat.S_IMODE(s.st_mode)==stat.S_IMODE(d.st_mode) and (s.st_dev,s.st_ino)!=(d.st_dev,d.st_ino),'all325 actual bodies literal modes independent inodes');tracked.append({'path':name,'git_mode':mode,'git_object':oid,'sha256':sha(raw)});modecounts[oct(stat.S_IMODE(d.st_mode))]=modecounts.get(oct(stat.S_IMODE(d.st_mode)),0)+1
ck(tracked==rb['all_tracked_original_bodies_modes'] and len(tracked)==325 and modecounts=={'0o644':32,'0o664':293},'actual325 original receipt and literal mode census');ck(all(p.lstat().st_nlink==1 for p in (N/'.git/objects').rglob('*') if p.is_file()),'actual object-store files not hardlinked')
spec=json.loads(read(V/'CLAIM_COPY_SPEC01.json'));ledger=N/'research_runs';copied=[]
for row in spec['members']:
 target=N/row['destination_relative_path'];src=Path(row['origin']);s=src.lstat();d=target.lstat();ck(stat.S_IMODE(s.st_mode)==stat.S_IMODE(d.st_mode)==row['mode'] and target.resolve()==target and (s.st_dev,s.st_ino)!=(d.st_dev,d.st_ino),'each actual copiedhistory literal mode and fresh inode')
 if row['kind']=='file':ck(read(target)==read(src) and sha(read(target))==row['sha256'] and d.st_size==row['bytes'],'each genuine copiedclaim/FAILED exactbody');copied.append(row['path'])
 else:ck(stat.S_ISDIR(d.st_mode),'actual copied history directory')
ck({p.relative_to(ledger/ID).as_posix() for p in (ledger/ID).rglob('*')}=={'claim.json','failed.json','outputs'} and list((ledger/ID/'outputs').iterdir())==[],'full four-node claim and emptyoutputs');ck({p.name for p in ledger.iterdir()}=={ID,'.lock'} and read(ledger/'.lock')==read(S/'research_runs/.lock')==b'' and stat.S_IMODE((ledger/'.lock').lstat().st_mode)==stat.S_IMODE((S/'research_runs/.lock').lstat().st_mode),'single ledger identity plus actual empty hidden lock');ck(not os.path.lexists(N/'research_artifacts'),'old runtime Owner/job not copied as active authority')
# Independent genuine structural verification, no admission or start.
verifypath=N/'tradingagents/research/verify.py';ck(sha(read(verifypath))=='3a45746a388307d1b375c885bb2fd7a22c2a60f139df714d2bbe98906d57d7eb','genuine pinned actual destination verifier');sp=importlib.util.spec_from_file_location('independent_actual_destination_verify',verifypath);v=importlib.util.module_from_spec(sp);sp.loader.exec_module(v);claim=v.verify_claim(ledger/ID);result=v.verify_run(ledger/ID);ck(claim==json.loads(read(S/'research_runs'/ID/'claim.json')) and result==rb['genuine_actual_destination_verify_run'] and result['status']=='failed' and result['output_count']==0,'genuine actual verify_claim and verify_run retained failed outcome');ck(claim['effective_attempt_budget']==18 and claim['source']==H,'historical ceiling18/source unchanged');ck(rel['literal_historical_absolute_paths_unchanged'] is True and rel['historical_owner_or_job_runtime_authority_transferred'] is False and rel['scientific_checkpoint_present_or_relocated'] is False,'relocation qualification authentic')
ck(all(rel[k] is None for k in ['new_corrected_source_or_gate','actual_cumulative19_admission','actual_new_identity_registration','actual_new_caller_or_native_release']),'no invented future authority');ck(len(rb['git_calls'])==367 and all(c['exit']==0 for c in rb['git_calls']),'original367 successful ordinary Git calls')
# Permanent failed Source01 remains exactly captured, never promoted to successful copy.
import gzip,io,tarfile
prior=F/'held-consumer-final-released-scope-capture-review01-2026-10-03/check01.py';defs=[n for n in ast.parse(read(prior)).body if isinstance(n,ast.FunctionDef) and n.name in ['decode','recode']];exec(compile(ast.Module(body=defs,type_ignores=[]),str(prior),'exec'));fm=json.loads(read(FD/'partial-source-manifest.json'));fa=read(FD/'partial-source.tar.gz');fc=json.loads(read(FD/'PARTIAL_SOURCE_CAPTURE01.json'));failure=json.loads(read(FD/'FAILED01.json'));partial=Path(fc['root']);ck(sha(fa)==fc['archive']['sha256']=='2babd9a97bb9974072e32496184185eefb12460fdb278e059d0ba9ffd865a684' and sha(read(FD/'partial-source-manifest.json'))==fc['manifest_sha256']=='b1c063fd6a303ab9fde4de0fd96851c80bdf119f9e0db31b6c5f53ae9b00bcad','permanent partial archive real pins');a.same(partial,fm);bodies,framing=decode(fa,fm);ck(recode(fm,bodies)==fa,'permanent partial complete canonical recompression')
for row in fm['members']:
 if row['kind']=='file':ck(bodies[row['path']]==a.read(partial,row['path']),'every permanent failed partial body preserved')
ck(len(fm['members'])==985 and sum(r['kind']=='file' for r in fm['members'])==712 and not os.path.lexists(partial/'research_runs'),'partial985/712 nohistory or extra numeric claim');ck(sha(read(FD/'FAILED01.json'))==fc['failure_sha256'] and failure['actual_exit']==1 and len(failure['mode_differences'])==32,'original32mode failure genuine unchanged');ck({json.loads(read(r/'research_runs'/ID/'claim.json'))['experiment_id'] for r in [S,N]}=={ID},'global same unique historicalidentity deduplicates exactcopies')
a.same(S,baseline);a.same(N,destination);a.same(partial,fm);ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numerical imports');(O/'DESTINATION_MANIFEST02.json').write_bytes(a.encode(destination))
x={'schema_version':1,'decision':'ACCEPTED_ACTUAL_SOURCE02_AND_CLOSED_HISTORY_PREPARATION_ONLY','checks':len(checks),'root_readback_sha256':sha(readbackraw),'root_relocation_sha256':sha(relraw),'root_terminal_sha256':sha(terminalraw),'actual_source_root':str(N),'current_source':H,'tracked':325,'literal_mode_counts':modecounts,'actual_git_objects':363,'ancestry_commits':6,'complete_destination_members':len(destination['members']),'complete_destination_regular':sum(r['kind']=='file' for r in destination['members']),'destination_manifest_sha256':sha((O/'DESTINATION_MANIFEST02.json').read_bytes()),'actual_copied_history_nodes':4,'actual_copied_history_files':2,'actual_copied_history_bytes':54951,'actual_empty_outputs_and_hidden_lock':True,'independent_genuine_verifier_calls':['verify_claim','verify_run'],'genuine_verifier_result':result,'global_unique_spent_claims':1,'highest_actual_budget':18,'old_preparation01_permanent_failed_members':985,'old_preparation01_regular':712,'old_original_source1011_unchanged':True,'original_pid_currently_absent':377661,'original_start_ticks_or_group_history':None,'new_correction_gate_admission_claim_or_native_authority':False,'full_destination_external_recovery':False};(O/'ACTUAL_READBACK02.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');print(json.dumps(x,sort_keys=True))
