import ast,hashlib,json,os,shutil,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();P=F/'financial-genuine-wrapper-root-recordfix-failed-scope-capture01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
def sig(s):return (s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns)
def read(p):
 s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4*1024**2 and p.resolve()==p,'regular canonical bounded input');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW)
 try:
  ck(sig(os.fstat(fd))==sig(s),'actual opened identity');out=[];total=0
  while True:
   b=os.read(fd,65536)
   if not b:break
   total+=len(b);ck(total<=s.st_size,'bounded extent');out.append(b)
  ck(sig(os.fstat(fd))==sig(s)==sig(p.lstat()) and total==s.st_size,'stable body identity');return b''.join(out)
 finally:os.close(fd)
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never',*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1','GIT_TERMINAL_PROMPT':'0'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'bounded local Git only');return r.stdout
import importlib.util
oldpath=Path('/tmp/financial_claimedrun_capsule_history01_20261004.py');newpath=Path('/tmp/financial_claimedrun_capsule_history02_20261004.py');oldraw=read(oldpath);newraw=read(newpath);oldtext=oldraw.decode();newtext=newraw.decode();expected=oldtext.replace('financial-genuine-wrapper-root-claimedrun-capsule-history-preparation01-2026-10-04','financial-genuine-wrapper-root-claimedrun-capsule-history-preparation02-2026-10-04').replace('genuine-financial-wrapper-claimedrun-native-20261004-01','genuine-financial-wrapper-claimedrun-native-20261004-02').replace(" assert stat.S_IMODE((OLD/name).lstat().st_mode)==stat.S_IMODE((NEW/name).lstat().st_mode)"," os.chmod(NEW/name,stat.S_IMODE((OLD/name).lstat().st_mode))\n assert stat.S_IMODE((OLD/name).lstat().st_mode)==stat.S_IMODE((NEW/name).lstat().st_mode)");ck(expected==newtext,'full exact path+one-mode-line byte inverse');ck(ast.dump(ast.parse(expected))==ast.dump(ast.parse(newtext)),'complete AST inverse')
S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-recordfix-native-20261004-01/source');N=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02');ND=F/'financial-genuine-wrapper-root-claimedrun-capsule-history-preparation02-2026-10-04';H='649fb8a11089524aaef7843dffeeb90a3a55ca17';ID='financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01';V=F/'financial-genuine-wrapper-claimedrun-history-copy-admission-review01-2026-10-04';A=F/'financial-genuine-wrapper-recordfix-failed-scope-actual-recovery-review01-2026-10-04'
ck(not os.path.lexists(N) and not os.path.lexists(ND) and N.parent.resolve()==N.parent and ND.parent.resolve()==ND.parent,'actual fixed successor namespaces absent canonical parents');ck(sha(read(A/'MANIFEST03.json'))=='09113794673e1e4ff3016bf545482a9c2d40a23a3945dd2e55590944aeb24f40','actual complete failed union accepted');specraw=read(V/'CLAIM_COPY_SPEC01.json');gsraw=read(V/'GIT_ANCESTRY_SPEC01.json');ck(sha(specraw)=='2857d64fd1b90bd3787c566051d6e52e093912ef9afb441e1433fb6b62b06545' and sha(gsraw)=='45883032094fb2f2033056755403c08cc12783835bdfa3f2ea78194bbfb6ebee','exact accepted closedhistory specifications');spec=json.loads(specraw);gs=json.loads(gsraw)
RP=F/'held-consumer-final-recovery-preparation04-2026-10-03';sys.path.insert(0,str(RP));sp=importlib.util.spec_from_file_location('history_source_r4',RP/'recovery04.py');R=importlib.util.module_from_spec(sp);sp.loader.exec_module(R);baseline=json.loads(read(F/'financial-genuine-wrapper-root-recordfix-failed-scope-capture01-2026-10-04/source-manifest.json'));R.same(S,baseline);ck(len(baseline['members'])==1011,'actual complete failed original tree still unchanged')
ck(git(['-C',str(S),'rev-parse','HEAD']).decode().strip()==H,'actual original Source649');ck(git(['-C',str(S),'rev-list','--parents',H]).decode().splitlines()==gs['ancestry_lines'] and len(gs['ancestry_lines'])==6,'actual full six-commit ancestry');objects=gs['objects'];ck(len(objects)==363 and len({r['oid'] for r in objects})==363,'exact363 unique Git objects');reply=b''.join(git(['-C',str(S),'cat-file','--batch'],(''.join(r['oid']+'\n' for r in objects[i:i+40])).encode()) for i in range(0,len(objects),40));offset=0
for r in objects:
 end=reply.index(b'\n',offset);oid,kind,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2;ck(oid==r['oid'] and kind==r['type'] and size==r['bytes'] and sha(b)==r['content_sha256'] and hashlib.sha1(kind.encode()+b' '+str(size).encode()+b'\0'+b).hexdigest()==oid,'all363 genuine original object content/OID/extent')
ck(offset==len(reply),'complete actual object framing');tree=git(['-C',str(S),'ls-tree','-r','-z',H]);tracked=[];modecounts={}
for ent in tree.split(b'\0'):
 if not ent:continue
 meta,n=ent.split(b'\t');mode,kind,oid=meta.decode().split();name=n.decode();b=read(S/name);s=(S/name).lstat();ck(kind=='blob' and mode in ('100644','100755') and hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()==oid,'alltracked Source body Gitmode/OID');modecounts[oct(stat.S_IMODE(s.st_mode))]=modecounts.get(oct(stat.S_IMODE(s.st_mode)),0)+1;tracked.append(name)
ck(len(tracked)==325,'actual325tracked mode map');claimroot=S/'research_runs'/ID;ck({p.relative_to(claimroot).as_posix() for p in claimroot.rglob('*')}=={'claim.json','failed.json','outputs'} and list((claimroot/'outputs').iterdir())==[],'complete genuine four-node closed claim with empty outputs');ck({p.name for p in (S/'research_runs').iterdir()}=={ID,'.lock'} and R.read(S/'research_runs','.lock')==b'','actual singleclaim and hidden emptylock')
for row in spec['members']:
 p=Path(row['origin']);s=p.lstat();ck(p.resolve()==p and stat.S_IMODE(s.st_mode)==row['mode'],'each current authentic history mode/path');ck(row['destination_relative_path']==('research_runs/'+ID+('' if row['path']=='.' else '/'+row['path'])),'exact rooted destination path')
 if row['kind']=='file':ck(sha(read(p))==row['sha256'] and s.st_size==row['bytes'],'each genuine claim/FAILED exact bytecopy specification')
 else:ck(stat.S_ISDIR(s.st_mode),'actual directory type')
claim=json.loads(read(claimroot/'claim.json'));failed=json.loads(read(claimroot/'failed.json'));ck(claim['effective_attempt_budget']==18 and failed['status']=='failed' and failed['claim_sha256']==sha(read(claimroot/'claim.json')),'actual one-spent ceiling18 history');verifyraw=read(S/'tradingagents/research/verify.py');ck(sha(verifyraw)=='3a45746a388307d1b375c885bb2fd7a22c2a60f139df714d2bbe98906d57d7eb','exact read-only verifier source');verifyast=ast.parse(verifyraw);imports={n.names[0].name for n in ast.walk(verifyast) if isinstance(n,ast.Import)};ck(not imports&{'numpy','torch','scipy','pandas'},'verifier no scientific imports');ck(all(n in verifyraw.decode() for n in ['def verify_claim','def verify_run','_verify_sources']),'actual verifier source entrypoints and object verification')
# Inspect concrete source ordering; never execute clone/chmod/history copy/verifier/admission.
start=newtext.index("for item in tree.split");end=newtext.index('assert len(tracked)==325');segment=newtext[start:end];ck(segment.index("assert kind=='blob'")<segment.index('os.chmod(NEW/name')<segment.index('assert stat.S_IMODE') and 'os.chmod(OLD' not in newtext,'literal mode mutation only successor after authenticated byte/OID match');ck("['clone','--no-hardlinks',str(OLD),str(NEW)]" in newtext and "assert (NEW/'.git').is_dir()" in newtext and 'objects/info/alternates' in newtext,'standalone local clone nohardlinks/noalternates checks');ck(newtext.count('R.same(OLD,baseline)')==2 and "with R.new_file(ledger/'.lock')" in newtext and "module_spec.loader.exec_module(v)" in newtext,'original whole-tree prepost and exact pinned metadata-only verifier route');ck('ResearchRun' not in newtext and '._admitted' not in newtext and 'v.verify_claim(ledger/ID)' in newtext and 'v.verify_run(ledger/ID)' in newtext,'no admission/start callable in successor')
FD=F/'financial-genuine-wrapper-root-claimedrun-capsule-history-preparation01-2026-10-04';failure=json.loads(read(FD/'FAILED01.json'));partial=Path(failure['partial_source_root']);ck(failure['actual_exit']==1 and not failure['history_copied'] and not failure['new_numeric_identity_registered_reserved_claimed_or_dispatched'] and sha(oldraw)==failure['actual_script_sha256'],'actual failed ordinary preparation retained');diffs=[]
for name in tracked:
 p=partial/name;ck(read(p)==read(S/name),'actual failed Source01 clonedbody retained');a=stat.S_IMODE((S/name).lstat().st_mode);b=stat.S_IMODE(p.lstat().st_mode)
 if a!=b:diffs.append({'path':name,'original_mode':a,'new_checkout_mode':b,'body_unchanged':True})
ck(diffs==failure['mode_differences'] and len(diffs)==32 and not os.path.lexists(partial/'research_runs'),'actual32literal mode failures before historycopy reproduced read-only');R.same(S,baseline);ck(not os.path.lexists(N) and not os.path.lexists(ND),'no actual successor preparation performed');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numerical import')
x={'schema_version':1,'decision':'ACCEPTED_EXACT_CAPSULE_HISTORY_SUCCESSOR02_SOURCE_ONLY','checks':len(checks),'successor_script_sha256':sha(newraw),'original_failed_script_sha256':sha(oldraw),'exact_inverse':'two fresh namespace literals plus one successor tracked-file chmod after authenticated body/OID match','source':H,'actual_original_tracked':325,'actual_original_git_objects':363,'actual_original_ancestry_commits':6,'actual_original_mode_counts':modecounts,'actual_original_whole_members':1011,'actual_history_nodes':4,'actual_history_regular_files':2,'actual_history_bytes':54951,'actual_empty_outputs_and_sibling_lock':True,'actual_old_preparation_mode_failures':32,'global_unique_spent_claims':1,'highest_actual_budget':18,'actual_successor_clone_copy_or_verifier_execution':False,'new_registration_admission_claim_or_native_release':False,'qualifications':['Source02 must be independently checked after actual execution.','This preserves historical claim bytes and ancestry; it transfers no old Owner/job/checkpoint execution authority.','Root ordinary subprocess runner has a60-second per-command timeout and post-collection output-size assertions; no aggregate or streaming cap guarantee is claimed.','Literal mode restoration applies to authenticated successor regular tracked files only, not original Source.']};(O/'READBACK01.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');print(json.dumps(x,sort_keys=True))
