"""Independent source binder review; no real/fake released Parent or outcome."""
import ast,hashlib,importlib.util,json,os,stat,sys
from pathlib import Path
D=Path(__file__).resolve().parent;S=D/'source';P=D.parent/'financial-genuine-wrapper-recordfix-outcome-verifier-preparation01-2026-10-04';checks=[];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def ok(n,v):
 if not v:raise AssertionError(n)
 checks.append(n)
def refuse(n,f):
 try:f()
 except (ValueError,TypeError,KeyError,OSError):ok(n,True);return
 raise AssertionError('accepted '+n)
ok('binder exactsource',sha(S/'bind01.py')=='a7e2d76530ddeb91168ca831706895268aa61e5afb68160071391c5dbf527790');ok('candidate exact manifest',sha(P/'MANIFEST01.json')=='d8b68c05c84b14332d5e1d031ebc4b7d38379bbf784ee9b1269eab63aa4505aa');m=json.loads((P/'MANIFEST01.json').read_text());ok('whole author tree membership',{p.relative_to(P).as_posix() for p in P.rglob('*') if p!=P/'MANIFEST01.json'}=={r['path'] for r in m['members']})
for r in m['members']:
 p=P/r['path'];q=S/r['path'];s=p.lstat();valid=stat.S_IMODE(s.st_mode)==r['mode']==stat.S_IMODE(q.lstat().st_mode)
 if r['kind']=='file':valid=valid and stat.S_ISREG(s.st_mode) and s.st_size==r['bytes'] and sha(p)==sha(q)==r['sha256']
 else:valid=valid and p.is_dir() and q.is_dir()
 ok('member '+r['path'],valid)
sys.path.insert(0,str(S));spec=importlib.util.spec_from_file_location('independent_binder',S/'bind01.py');B=importlib.util.module_from_spec(spec);spec.loader.exec_module(B);parent=B.prepared();ok('actual accepted parent validator module',Path(parent.__file__).resolve()==S/'accepted_parent01.py')
for local,origin in [('original-verifier03.py','financial-genuine-wrapper-first-outcome-verifier-preparation03-2026-10-04/verifier01.py'),('accepted_parent01.py','financial-genuine-wrapper-recordfix-parent-preparation01-2026-10-04/parent01.py'),('verifier-review/MANIFEST03.json','financial-genuine-wrapper-first-outcome-verifier-review03-2026-10-04/MANIFEST03.json'),('verifier-review/REVIEW03.json','financial-genuine-wrapper-first-outcome-verifier-review03-2026-10-04/REVIEW03.json'),('parent-review/MANIFEST01.json','financial-genuine-wrapper-recordfix-parent-review01-2026-10-04/MANIFEST01.json'),('parent-review/REVIEW01.json','financial-genuine-wrapper-recordfix-parent-review01-2026-10-04/REVIEW01.json')]:ok('actual original metadata/body '+local,(S/local).read_bytes()==(D.parent/origin).read_bytes())
for name in ('recovery04.py','owned_io.py','bounded_git01.py','descendants01.py','supervisor01.py','PROTOCOL_PINS01.json'):ok('actual exact helper '+name,(S/name).read_bytes()==(D.parent/'financial-genuine-wrapper-recordfix-parent-preparation01-2026-10-04'/name).read_bytes())
ad=json.loads((S/'SOURCE_ADOPTION01.json').read_text());gate=Path(B.CAP)/ad['registration'];ok('actual fixed gate4474 hash',sha(gate)==ad['registration_sha256']=='4474df26460aab41281bfdcc311129b613a90d76963e853858841200d9faa69a');experiment=json.loads(gate.read_text())['experiments'][B.IDENTITY];ok('actual gate324 map agrees with adoption',experiment['source_files']==ad['source_files'] and len(experiment['source_files'])==324);ok('actual eight role map agrees with adoption',len(experiment['inputs'])==8 and {v['path']:v['sha256'] for v in experiment['inputs'].values()}==ad['role_hashes']);ok('fixed context Source649',ad['source']==ad['design_source']==B.SOURCE and ad['root']==B.CAP and ad['fresh_identity']==B.IDENTITY)
original=(S/'original-verifier03.py').read_bytes();oldtree=ast.parse(original);oldfn={n.name:ast.dump(n) for n in oldtree.body if isinstance(n,(ast.FunctionDef,ast.ClassDef))}
# Pure source transformations are kept in memory only, never emitted or labeled authoritative.
for i in range(100):
 name='REQUEST_FINAL'+str(i).zfill(2)+'.json';pin=hashlib.sha256(('opaque unbound source projection '+str(i)).encode()).hexdigest();code,edits=B.rewrite(original,pin,name);back=code.decode()
 for edit in reversed(edits):ok('unique projected inverse '+str(i)+'/'+str(len(edit['new'])),back.count(edit['new'])==1);back=back.replace(edit['new'],edit['old'])
 ok('entire byteAST inverse '+name,back.encode()==original and ast.dump(ast.parse(back))==ast.dump(oldtree));ok('exact expected edit count '+name,len(edits)==(2 if i==3 else 3));newfn={n.name:ast.dump(n) for n in ast.parse(code).body if isinstance(n,(ast.FunctionDef,ast.ClassDef))};ok('all nonverify definitions untouched '+name,{k:v for k,v in newfn.items() if k!='verify'}=={k:v for k,v in oldfn.items() if k!='verify'})
for pin in (None,False,0,'','x'*64,'A'*64,'a'*63,'a'*65,B.OLD_QHASH):refuse('invalid or spent pin '+repr(pin),lambda pin=pin:B.rewrite(original,pin,'REQUEST_FINAL01.json'))
for name in ('../REQUEST_FINAL01.json','/REQUEST_FINAL01.json','REQUEST_FINAL1.json','REQUEST_FINAL100.json','REQUEST_FINAL01.json/child','REQUEST_FINAL01.json\n','request_final01.json','REQUEST_FINALaa.json',None,1):refuse('invalid basename '+repr(name),lambda name=name:B.rewrite(original,'b'*64,name))
refuse('changed original refuses',lambda:B.rewrite(original+b'\n','b'*64,'REQUEST_FINAL01.json'))
oldq=json.loads((D.parent/'financial-genuine-wrapper-first-outcome-verifier-preparation03-2026-10-04/REQUEST_FINAL03.json').read_text());refuse('real old request fixed context refusal',lambda:B.fixed(oldq));refuse('real old request parent validator refusal',lambda:parent.validate_release(oldq));refuse('stale original pin before IO',lambda:B.authenticate(Path(B.PARENT)/'REQUEST_FINAL01.json',B.OLD_QHASH));refuse('outside fixed parent before IO',lambda:B.authenticate(S/'REQUEST_FINAL01.json','b'*64))
missing=Path(B.PARENT)/'MISSING_INDEPENDENT_BINDER_REVIEW.json';ok('chosen missing path absent',not os.path.lexists(missing));refuse('missing real final request',lambda:B.authenticate(missing,'b'*64))
template=json.loads((S/'REQUEST_TEMPLATE01.json').read_text());ok('all actual future fields null',template=={'actual_parent_request':None,'actual_parent_request_sha256':None,'generated_verifier':None,'status':'DRAFT_NOT_RELEASED'});ok('no generated output before or after controls',not os.path.lexists(S/'generated-recordfix01') and not os.path.lexists(P/'generated-recordfix01'))
text=(S/'bind01.py').read_text();functions={n.name:n for n in ast.parse(text).body if isinstance(n,ast.FunctionDef)};auth=ast.get_source_segment(text,functions['authenticate']);gen=ast.get_source_segment(text,functions['generate']);emit=ast.get_source_segment(text,functions['emit'])
ok('authentication before rewrite',gen.index('authenticate(path,pin)')<gen.index('rewrite('));ok('genuine release validator before accepted result',auth.index('P.validate_release(q)')<auth.index('return raw,q'));ok('installed actual caller and six helpers before result',auth.index('actual installed accepted Parent body')<auth.index('return raw,q') and auth.index('actual six helper denominator')<auth.index('return raw,q'));ok('proof containment and bodypins',"p.is_relative_to(Path(PARENT)) and p.resolve()==p" in auth and "h(ref['sha256'])" in auth)
ok('authentication before mkdir',emit.index('generate(path,pin)')<emit.index('out.mkdir'));ok('exclusive output identity',"not os.path.lexists(out)" in emit);ok('bounded owned emission and cleanup',"with R.new_file(out/name) as fd" in emit and 'len(raw)<=R.FILE' in emit and 'os.fsync(fd)' in emit);ok('no catch replacing binder failure',not any(isinstance(n,ast.ExceptHandler) for n in ast.walk(functions['emit'])))
# Exercise only the exact nested utility writer over tiny opaque bytes, never a verifier.
writer=next(n for n in functions['emit'].body if isinstance(n,ast.FunctionDef) and n.name=='write');owned=D/'owned01';owned.mkdir(mode=0o700);namespace={'out':owned,'R':B.R,'os':os};exec(compile(ast.Module(body=[writer],type_ignores=[]),'<exact nested utility writer>','exec'),namespace);before=set(os.listdir('/proc/self/fd'));namespace['write']('opaque.txt',b'independent utility body\n');after=set(os.listdir('/proc/self/fd'));ok('actual utility write owned bytes',B.R.read(owned,'opaque.txt')==b'independent utility body\n');ok('private utility mode',stat.S_IMODE((owned/'opaque.txt').stat().st_mode)==0o600);ok('observed FD numbers unchanged',before==after);refuse('utility refuses overwrite',lambda:namespace['write']('opaque.txt',b'changed'));ok('previous utility bytes retained',B.R.read(owned,'opaque.txt')==b'independent utility body\n')
ok('no numerical imports',not any(n in sys.modules for n in ('numpy','torch','pandas','scipy')))
result={'verdict':'ACCEPTED_SOURCE_ONLY_BINDER_FINAL_BINDING_PENDING','count':len(checks),'checks':checks,'actual_parent_authentication_success':False,'emitted_final_verifiers':0,'actual_outcomes_inspected':0,'actual_admission_calls':0,'network_operations':0,'native_executions':0,'authority':None,'qualification':'100 in-memory source rewrite projections are not requests or released bindings; no final request/proofs synthesized.'};(D/'CHECKS01.json').write_text(json.dumps(result,sort_keys=True,indent=2)+'\n');print(json.dumps({'verdict':result['verdict'],'count':len(checks)}))
