# Genuine scientific cold-handoff comparison charter

Unregistered until the actual materialization has been authenticated through the independently reviewed outer03 historical-source verifier installed before materialization. No precomputed hashes, accepted labels, fabricated capability or self-declared receipt authorizes this attempt.

Fixed program/family/budget match CHARTER_MATERIALIZE02.md: two total engineering attempts, prior zero. Identity `compact-cold-comparison-20261003-01`, parent `compact-cold-inputs-20261003-01`, cell `cold-genuine-comparison`. Exact outputs: `binding.json`, `journal.json`, `cold-handoff.json`, `proof-compare.json`. The new registration must retain the original parent experiment, family/mechanism/history and dataset unchanged, adding only the comparison experiment. Its44 input entries are the actual43 materialized records (future_execution_job renamed execution_job) plus the original environment. No guessed array hashes or new numerical source bodies may be inserted after materialization.

Execute the genuine scientific chain Binding→Owner→Training→sampler→samples→dictionary→all required MCMs→graph artifacts→denominator/Closure→Published→terminal. Use fresh synthetic32 samples and dictionary32 only for this engineering experiment. Preserve the original matching beta schedule/50 iterations, graph/model widths, seed11, full28-step lookback, actual batch factory and streamed-gat-mulsum-v1 block65536. The original512-sample historical job remains closed. No resource-only terminal, forged Produced object or private callback may substitute for scientific completion.

Finite matching denominators: dictionary at most992 ordered off-diagonal pairs; each required four-node graph MCM128 pairs/32 columns;19 source graphs bound required graph count and thus maximum2432 MCM pairs. Actual calendar membership/required graph count is authenticated from materialization and must not be reduced. This is not a23-resource-cell or27-refusal-suite claim.

Two tasks (regression and classification), three batches (gap16, ordinary16, final8) and two trajectories (resident and detached) produce12 prescribed batch/task/trajectory steps. Each compares actual graph-object sharing, fixed inputs, forward/loss, MCM/price gradients, every parameter gradient, clipped update/Adam state, weights and RNG. Every parameter group needs a nonzero gradient. Checkpoint after first step is loaded into fresh model/optimizer and cursor/weights/optimizer/RNG checked before later steps. Resident versus detached observations require bitwise equality; no post-outcome tolerance changes. Weak-reference lifetime probes retain one deliberate graph alias as positive control, then release it; maximum-batch overlap refusal and release-to-zero remain required. Tensor ownership is not proof of process RSS/allocator release.

Native/whole-capsule limits and failed/reserved/spent accounting are identical to the materialization charter. Any failed check or incomplete native/raw/terminal closure fails the single cell; all partial numerical observations remain retained and unavailable items explicit. No retry under either fixed identity or replacement family is allowed by this charter. Successful tiny comparison does not authorize a higher empirical cap, paper budget65, financial fits, full-size multi-distinct-graph capacity or actual archive transport. Complete raw preservation, native process/cgroup absence and independent recovery remain separate requirements.
