# Actual four-body source adoption

ACCEPTED_ACTUAL_SOURCE_ADOPTION_ONLY. Current source7b056a574e3e7b3c7ba209a39ee6a615e649d60c is the direct child of9dc5c79f738920b52947b4e63fed0397f1b5b207 in the same genuine root. Git reports exactly the three reviewed replacements and one new helper, with no other committed path change. All340 current tracked blobs were independently compared to actual working bytes and Git mode/OID. The195 implementation paths/150 package paths equal the accepted target map;191 old bodies remain identical. Every four-body size/hash/literal0664 mode matches the precise prior release and Root target copies.

The complete589-member nonGit tree matches Root AFTER589, with every original585 protected non-target member retaining its name/type/mode/hash. Original gate752c, all three FAILED claims and failed raw artifacts/checkpoints remain unchanged at their same absolute paths. All385 original reachable Git objects were re-read and matched against their pre-adoption type/extent/SHA256 pins. Historical0a2 remains an ancestor; no old provenance or checkpoint is relabeled.

The old gate remains incompatible with the changed hashes, and no new policy, registration, job, allowance or native release was adopted. The proposed future identity has no claim directory. Current matching native/Parent job search and old cgroup checks found none; this is a current sampled observation, not complete historical PID proof or future capacity. Original Parent actual_parent_exit remainsNULL. The known three spent FAILED claims/highest19 remain exact.

This review executed only metadata/opaque byte and local read-only Git checks. No admission, ResearchRun, numerical import, checkpoint deserialization, network, source edit or launch occurred. The initial read-only receipt filename guess is retained as a reviewer discovery error. Actual new-source policy/gate/accounting/caller/full preservation/recovery and final runtime release remain separate prerequisites. This closes only actual source adoption, not empirical eligibility.
