import ast,collections,datetime,hashlib,json,os,stat
from pathlib import Path
HERE=Path(__file__).resolve().parent;BASE=HERE.parent;CAP=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-recordfix-native-20261004-01/source');PREP=BASE/'financial-genuine-wrapper-recordfix-registration-preparation02-2026-10-04';OLD='financial-wrapper-classification-eager-interrupt1-20261003-01';SPENT='financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01';FRESH='financial-wrapper-classification-eager-interrupt1-claimedrun-20261004-01';checks=[]
def check(v,n):
 if not v:raise AssertionError(n)
 checks.append(n)
def sha(b):return hashlib.sha256(b).hexdigest()
def load(p):return json.loads(p.read_bytes())
gatepath=CAP/'fixture_inputs/financial_wrapper_recordfix01/gates.json';gate=load(gatepath);check(sha(gatepath.read_bytes())=='4474df26460aab41281bfdcc311129b613a90d76963e853858841200d9faa69a','actual gate4474')
phases=load(PREP/'ORIGINAL_PHASES.json')['slots'];order=load(PREP/'ORIGINAL_ORDER.json');draft=load(PREP/'generated01/OPERATIONAL_AMENDMENT_DRAFT.json');pm=load(PREP/'MANIFEST02.json') if (PREP/'MANIFEST02.json').is_file() else load(PREP/'MANIFEST01.json')
for name in ('ORIGINAL_PHASES.json','ORIGINAL_ORDER.json','generated01/OPERATIONAL_AMENDMENT_DRAFT.json'):
 row=next(r for r in pm['members'] if r['path']==name);check(sha((PREP/name).read_bytes())==row['sha256'],'authenticated historical18 '+name)
check(len(phases)==18 and len({r['proposed_plan']['experiment'] for r in phases})==18,'18 distinct phase contracts');check(len(gate['experiments'])==11,'11actual registered entries not19');check(len(order['initial10_order'])==10,'original10 initial registered');check(set(order['initial10_order'])|{SPENT}==set(gate['experiments']),'exact retained gate identities')
claims=[];snap=[]
for d in sorted((CAP/'research_runs').iterdir()):
 if (d/'claim.json').is_file():
  c=load(d/'claim.json');claims.append(c);t=load(d/'failed.json');check(t['status']=='failed' and t['claim_sha256']==sha((d/'claim.json').read_bytes()),'actual closed terminal join');snap.append({'experiment':d.name,'claim_sha256':sha((d/'claim.json').read_bytes()),'terminal_status':'failed','terminal_sha256':sha((d/'failed.json').read_bytes())})
check(len(claims)==1 and claims[0]['experiment_id']==SPENT,'actual exactly1spent');c=claims[0];family=gate['families'][c['experiment']['family']];check(c['family']==family and family['attempt_budget']==18 and family['prior_attempts']==0 and c['effective_attempt_budget']==18,'basefamily and current effective18 unchanged')
check(c['experiment']==gate['experiments'][SPENT],'spent definition exact genuine current gate');check(all('cumulative_budget_extension' not in e for e in gate['experiments'].values()),'no currently registered19extension')
check(not os.path.lexists(CAP/'research_runs'/OLD),'old predispatch has no fabricated numerical claim');check(FRESH not in gate['experiments'] and not os.path.lexists(CAP/'research_runs'/FRESH),'proposed fresh name is not current registered or claimed')
check(not os.path.lexists(CAP/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/FRESH) and not os.path.lexists(CAP/'research_artifacts/financial_wrapper_engineering'/FRESH),'proposed fresh namespace absent now')
counts=dict(collections.Counter(r['proposed_plan']['phase'] for r in phases));check(counts=={'interrupt1':4,'complete100':4,'continue100':4,'predict':4,'agreement':2},'all phase type denominators')
remaining=len(phases);used=family['prior_attempts']+len(claims);minimum=used+remaining
check(minimum==19 and 18-used==17 and remaining==18,'minimal19 preserves remaining18 afterspent1');check(minimum-1-used<remaining and minimum-used==remaining,'strict minimality18insufficient19exact')
check(sum(r['expected_disposition_if_contract_met']=='FAILED' for r in phases)==4 and sum(r['expected_disposition_if_contract_met']=='COMPLETE' for r in phases)==14,'conditional4FAILED14COMPLETE unchanged')
# Read and pin actual existing extension and admission source; no admission helper execution.
sourcefiles={}
for name in ('admission.py','budget_extensions.py','lifecycle.py','verify.py','onchain_replication/job.py'):
 p=CAP/'tradingagents/research'/name;b=p.read_bytes();check(sha(b)==c['experiment']['source_files']['tradingagents/research/'+name],'actual source pin '+name);sourcefiles[name]={'origin':str(p),'sha256':sha(b),'bytes':len(b)};(HERE/name.replace('/','__')).write_bytes(b)
ext=ast.parse((HERE/'budget_extensions.py').read_bytes());fn=next(n for n in ext.body if isinstance(n,ast.FunctionDef) and n.name=='effective_budget');fields=next(ast.literal_eval(n.value) for n in fn.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='fields' for t in n.targets))
check(fields=={'schema_version','program_id','base_family','cumulative_ceiling','consumed_before','initial_experiment','allocation','claims','reason'},'exact extension schema source derived')
# Evaluate only original arithmetic guard and current no-extension scalar route.
noext=next(n for n in fn.body if isinstance(n,ast.If) and ast.unparse(n.test)=='reference is None');check(eval(compile(ast.Expression(noext.test),'<actual no-extension predicate>','eval'),{'reference':None}) is True,'current no-extension branch selected');ret=next(n for n in noext.body if isinstance(n,ast.Return));check(ast.unparse(ret.value)=='base','actual current branch returns18')
usedguard=next(n for n in ast.walk(fn) if isinstance(n,ast.If) and 'used!=family' in ast.unparse(n.test).replace(' ',''));code=compile(ast.Expression(usedguard.test),'<actual extension consumed predicate>','eval')
for proposed,expect in [(1,False),(0,True),(2,True),(True,True),(-1,True)]:check(eval(code,{'used':proposed,'family':family,'seen':{SPENT},'ceiling':19}) is expect,'exact consumed snapshot predicate '+repr(proposed))
first=next(n for n in ast.walk(fn) if isinstance(n,ast.If) and ast.unparse(n.test)=='not adopters');inner=next(n for n in first.body if isinstance(n,ast.If));fc=compile(ast.Expression(inner.test),'<actual first adopter snapshot predicate>','eval')
for seen,experiment,expect in [({SPENT},FRESH,False),(set(),FRESH,True),({SPENT,OLD},FRESH,True),({SPENT},SPENT,True)]:check(eval(fc,{'experiment_id':experiment,'initial':FRESH,'seen':seen,'claims':{SPENT:c}}) is expect,'first adopter complete closed snapshot '+repr((seen,experiment)))
# Whole prospective DAG kept as proposal only; original historical slots remain untouched.
rows=[];mapped={r['proposed_plan']['experiment']:(FRESH if r['proposed_plan']['experiment']==OLD else r['proposed_plan']['experiment']) for r in phases}
for i,r in enumerate(phases):
 p=r['proposed_plan'];deps=[mapped[d] for d in r['dependencies']];rows.append({'ordinal':i+1,'original_phase_identity':p['experiment'],'proposed_execution_identity':mapped[p['experiment']],'phase':p['phase'],'task':p['task'],'execution':p['execution'],'cell_id':p['cell_id'],'conditional_expected_disposition':r['expected_disposition_if_contract_met'],'scientific_dependencies':deps,'registration_parent_for_fresh_first':SPENT if p['experiment']==OLD else None,'actual_phase_achieved':False,'future_definition_adopted':False})
seen=set()
for r in rows:check(set(r['scientific_dependencies'])<=seen,'topological phase '+str(r['ordinal']));seen.add(r['proposed_execution_identity'])
check(len(seen)==18 and SPENT not in seen and OLD not in seen,'18future phase executions exclude both failed IDs')
firstplan=dict(phases[0]['proposed_plan']);firstplan.update(experiment=FRESH,namespace=FRESH);check(firstplan['phase']=='interrupt1' and firstplan['prior_input'] is None and firstplan['reference_input'] is None,'fresh first phase does notreuse missing checkpoint')
requirements={'status':'PROSPECTIVE_REQUIREMENTS_NOT_EXTENSION_OR_ACCEPTED_REVIEW','program_id':gate['program_id'],'unchanged_base_family':family,'current_admitted_effective_ceiling':18,'current_consumed':1,'remaining_original_phase_contracts':18,'minimum_proposed_cumulative_ceiling':19,'prospective_complete_claim_total_if_no_other_unexpected_failure':19,'new_first_identity_proposal':FRESH,'new_first_identity_adopted':False,'new_first_registration_parent_proposal':SPENT,'new_first_plan_proposal':firstplan,'required_closed_claim_snapshot':snap,'old_predispatch_outer_preserved':OLD,'spent_unexpected_outer_preserved':SPENT,'operational_phase_and_reserved_identity_count_if_proposal_adopted':20,'current_actual_gate_entry_count':11,'new_initial_gate_entry_count_if_only_first_added':12,'deferred_dependent_phase_count':8,'extension_required_fields':sorted(fields),'extension_metadata_reference_requirements':{'extension':'exact source-pinned path and SHA256 at current and design commit','review':'actual independent accepted exact extension review; no fabricated reviewer or approval','allocation':'finite full18 DAG and retained spent/old identities, source-pinned; no self-referential future commit hash'},'actual_extension':None,'actual_extension_review':None,'actual_allocation':None,'actual_new_source':None,'actual_new_gate':None,'actual_new_caller':None,'full_failed_scope_recovery':None,'current_source_649_preserved':True,'source_route':'Same physical capsule after full failed-scope preservation/recovery, no active run; immutable649 retained; future current=design commit adds wrapperf4ea+closure/inputs/extension and new definition, retains old claimed definition and full claim/output/Git paths. No companion-relocation ancestry implied.','future_caller_changes_required':['exact new identity/source/current=design/gate/input/source closure pins','f4ea wrapper acceptance instead of old e2d pin','effective ceiling19 via genuine reviewed extension while basefamily18 unchanged; old Parent hardcoded18 cannot be reused','new released caller/request/verifier binding and full actual preservation/recovery/native observations'],'no_refund_or_transfer':True,'no_actual19_admission':True,'paper_fit_credit':0}
for name,v in [('REQUIREMENTS01.json',requirements),('PHASE_DAG01.json',{'status':'unadopted exact phase requirement mapping','rows':rows,'counts':counts,'conditional_dispositions':{'COMPLETE':14,'FAILED':4},'required_completed100epoch_fits':8,'required_fit_calls':12,'training_updates_across_interrupted_continued_reference':800,'agreement_updates':4,'replay_copies':16,'distinct_training_cells':10,'paper_fit_credit':0})]:
 with (HERE/name).open('x') as f:json.dump(v,f,sort_keys=True,indent=2);f.write('\n')
result={'decision':'MINIMUM_PROSPECTIVE_SAME_PROGRAM_CUMULATIVE19_REQUIRED_CURRENT18_ONLY','observed_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'checks':len(checks),'check_names':checks,'source_pointers':sourcefiles,'actual_gate_sha256':sha(gatepath.read_bytes()),'actual_claim_snapshot':snap,'authenticated_phase_source_manifest_sha256':sha((PREP/('MANIFEST02.json' if (PREP/'MANIFEST02.json').is_file() else 'MANIFEST01.json')).read_bytes()),'current_ceiling':18,'spent':1,'remaining_required_phases':18,'minimum_prospective_ceiling':19,'actual19_admitted':False,'admit_calls':0,'claim_or_registration_writes':0,'future_authority':None}
with (HERE/'READBACK01.json').open('x') as f:json.dump(result,f,sort_keys=True,indent=2);f.write('\n')
print(json.dumps({k:v for k,v in result.items() if k not in ('check_names','source_pointers')}))
