import ast,hashlib,importlib.metadata,importlib.util,json,os,platform,shutil,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();C=F/'financial-genuine-wrapper-root-parent-composition01-2026-10-04';PREP=F/'financial-genuine-wrapper-parent-preparation03-2026-10-04';REV=F/'financial-genuine-wrapper-parent-review03-2026-10-04';CAP=F/'financial-genuine-wrapper-root-preservation03-2026-10-04';P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-root-launch-20261004-01');S=P.parent/'genuine-financial-wrapper-native-20261003-01/source';H='d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
ck(sha((PREP/'recovery04.py').read_bytes())=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','acceptedrecoveryhash');sys.path.insert(0,str(PREP));sp=importlib.util.spec_from_file_location('composition_review_primitives',PREP/'recovery04.py');R=importlib.util.module_from_spec(sp);sp.loader.exec_module(R)
def read(p):return R.read(p.parent,p.name)
def doc(p,pin=None):
 b=read(p);ck(pin is None or sha(b)==pin,'pin '+p.name);return json.loads(b)
# Verify honest typed complete inventories before accepting copied helper origins.
for d,pin in [(PREP,'3c6c8ef58e93de1a314a105b77e0b452267494487c971c73f925f98615ad78de'),(REV,'c5c37ae65524e7033e1b5174d7391bdfd87704ee8576390c44c8236422c59af6')]:
 m=doc(d/'MANIFEST01.json',pin);rows=m['entries'];ck({str(p.relative_to(d)) for p in d.rglob('*')}=={r['path'] for r in rows}|{'MANIFEST01.json'},'complete accepted parent inventory')
 for r in rows:
  p=d/r['path'];s=p.lstat();ck(stat.S_IMODE(s.st_mode)==r['mode'],'parent originalmode')
  if r['type']=='file':b=read(p);ck(len(b)==r.get('bytes',r.get('size')) and sha(b)==r['sha256'],'parent source/review body')
  elif r['type']=='directory':ck(stat.S_ISDIR(s.st_mode),'honest directory')
  else:raise AssertionError('unexpected fixturetype')
composition=doc(C/'COMPOSITION01.json');sm=doc(C/'SOURCE_MANIFEST01.json',composition['source_manifest']['sha256']);pm=doc(C/'PARENT_MANIFEST01.json',composition['parent_manifest']['sha256']);ck(len(sm['members'])==878 and len(pm['members'])==15 and R.scan(S)==sm and R.scan(P)==pm,'fullcurrent878source15parenttyped/mode/body');ck(not S.is_relative_to(P) and not P.is_relative_to(S) and P.resolve()==P and S.resolve()==S and stat.S_IMODE(P.stat().st_mode)==0o700,'canonical disjointprivateparent');names=['parent01.py','supervisor01.py','descendants01.py','recovery04.py','owned_io.py','bounded_git01.py','PROTOCOL_PINS01.json']
for n in names:ck(read(P/n)==read(PREP/n) and stat.S_IMODE((P/n).stat().st_mode)==0o600,'exact7accepted helpercopy')
for n,ref in composition['proof_origins'].items():ck(read(P/'proofs'/n)==read(Path(ref['path'])) and sha(read(P/'proofs'/n))==ref['sha256'],'all5actualproof origins')
ck(len(composition['proof_origins'])==5 and len(composition['helper_hashes'])==6,'exactclosurecount');q=doc(P/'REQUEST_DRAFT01.json',composition['request']['sha256']);template=doc(PREP/'REQUEST_TEMPLATE01.json');changed={'parent_root','identity','source','design_source','registration','registration_sha256','source_files','input_hashes','runtime_mapping','caller_sha256','helper_hashes','expected_phase','proofs'};ck({k:v for k,v in q.items() if k not in changed}=={k:v for k,v in template.items() if k not in changed},'completeunchanged template remainder');ck(q['status']=='DRAFT_NOT_RELEASED' and q['final_review'] is None and q['proofs']['full_recovery'] is None and q['source']==q['design_source']==H and q['capsule_root']==str(S) and q['parent_root']==str(P),'actualnull releaseholds');gate=doc(S/q['registration'],q['registration_sha256']);e=gate['experiments'][q['identity']];ck(q['source_files']==e['source_files'] and len(q['source_files'])==289 and q['input_hashes']=={k:v['sha256'] for k,v in e['inputs'].items()} and len(e['inputs'])==8,'exactsource/inputrolemap');ck(q['caller_sha256']==sha(read(P/'parent01.py')) and q['helper_hashes']==composition['helper_hashes'],'actualcaller helperpins');order=doc(P/'CASE_ORDER01.json','341c045b452d9367c43a24916c80108f8a2a8cc9db669a02ada943c0f9e4108f');ck(read(P/'CASE_ORDER01.json')==read(F/'financial-genuine-wrapper-root-gate-adoption01-2026-10-04/FIXED_ORDER01.json') and q['identity']==order['first_initial']==order['initial10_order'][0]=='financial-wrapper-classification-eager-interrupt1-20261003-01' and q['expected_phase']=='interrupt1','exactcopied fixedorder firstcase');ck(len(order['complete18_topological_order'])==18 and len(order['initial10_order'])==len(gate['experiments'])==10,'18order10initial8withheld')
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never','-C',str(S),*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'boundedofflineGit');return r.stdout
installed=doc(F/'financial-genuine-wrapper-installed-gate-admission-review01-2026-10-04/READBACK01.json','db9d9e4f5957b64a8c29aed1514d99910917e51c7d0d1165f9215f5308351e29');rows={r['path']:r for r in installed['joined']};tree={}
for entry in git(['ls-tree','-r','-z',H]).split(b'\0'):
 if not entry:continue
 left,n=entry.split(b'\t');mode,typ,oid=left.decode().split();ck(typ=='blob','actualregularGit');tree[n.decode()]=(mode,oid)
ck(set(tree)==set(rows)==set(q['source_files'])|{q['registration']} and len(tree)==290 and sum(n.startswith('tradingagents/') for n in tree)==149,'complete290289149closure');reply=git(['cat-file','--batch'],(''.join(tree[n][1]+'\n' for n in sorted(tree))).encode());offset=0
for n in sorted(tree):
 end=reply.index(b'\n',offset);oid,typ,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2;r=rows[n];ck(typ=='blob' and oid==tree[n][1]==r['git_oid'] and tree[n][0]==r['git_mode'] and reply[offset-1:offset]==b'\n' and read(S/n)==b and sha(b)==r['sha256'] and stat.S_IMODE((S/n).stat().st_mode)==r['mode'] and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+b).hexdigest()==oid,'all290actualbody/Git/mode')
ck(offset==len(reply) and installed['implementation']==194,'completebatch194unchanged')
# Read metadata only. Readonly RECORD hardlinks are not owned output files.
def stream(p,limit):
 p=Path(p);s=p.lstat();ck(p.resolve()==p and stat.S_ISREG(s.st_mode) and s.st_size<=limit,'readonlyruntime extent/type');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW);h=hashlib.sha256();n=0
 try:
  ck(R.sig(s)==R.sig(os.fstat(fd)),'runtime actualopened')
  while True:
   b=os.read(fd,65536)
   if not b:break
   n+=len(b);ck(n<=limit,'bounded runtimebytes');h.update(b)
  ck(n==s.st_size and R.sig(s)==R.sig(os.fstat(fd))==R.sig(p.lstat()),'stable runtimebody');return h.hexdigest(),n,s.st_nlink
 finally:os.close(fd)
runtime=q['runtime_mapping'];ck(runtime==doc(S/e['inputs']['runtime_mapping']['path']) and len(runtime['distribution_records'])==251 and len({r['name'] for r in runtime['distribution_records']})==251,'actual251runtime mapped');records=[]
for row in runtime['distribution_records']:
 p=Path(row['record']);ck(p.is_relative_to(Path(sys.prefix)/'lib/python3.13/site-packages') and p.name=='RECORD' and p.parent.name.endswith('.dist-info') and importlib.metadata.version(row['name'])==row['version'],'actual metadata version/path');h,n,links=stream(p,R.FILE);ck(h==row['record_sha256'],'actual251RECORDhash');records.append(dict(row,bytes=n,nlink=links))
exe=Path(sys.executable).resolve();eh,en,el=stream(exe,64*1024**2);ck(runtime['executable']==sys.executable and runtime['resolved_executable']==str(exe) and runtime['prefix']==sys.prefix and runtime['python']==platform.python_version() and eh==runtime['executable_sha256'] and sha(read(S/'uv.lock'))==runtime['lock_sha256'],'actual interpreterbasic metadata');env=doc(S/e['inputs']['environment']['path']);ck(env['python']==platform.python_version() and env['cpu_count']==os.cpu_count() and env['lock_sha256']==runtime['lock_sha256'] and all(importlib.metadata.version(n)==v for n,v in env['packages'].items()),'basic historicalexpectation fields match noTorchAPI');refusal=doc(C/'DRAFT_REFUSAL01.json');ck(refusal['actual_exit']==1 and refusal['launch_requested'] is False and '--launch' not in refusal['actual_argv'] and 'ValueError: no draft release' in read(C/'DRAFT_REFUSAL01.err').decode() and read(C/'DRAFT_REFUSAL01.out')==b'' and not Path('/proc',str(refusal['actual_pid'])).exists(),'actualdraftrefusal closedPID');ck(all(not (S/n).exists() for n in ['research_runs','research_artifacts','fixture_outer']) and all(not (P/n).exists() for n in ['ATTEMPT01.json','attempt01.json']),'noactualclaims/attempt namespace')
source=read(CAP/'capture01.py');ct=ast.parse(source);main=next(n for n in ct.body if isinstance(n,ast.FunctionDef) and n.name=='main');text=ast.unparse(main);ck('R.same(SOURCE, source_manifest)' in text and 'R.same(PARENT, parent_manifest)' in text and text.index("R.read(REVIEW, 'MANIFEST01.json')")<text.index("R.put(HERE / 'REQUEST01.json'") and "a.review_manifest_sha256" in text,'exactreviewpin beforecapturewrites wholefixedmanifests');ck("os.path.lexists(HERE / 'INTENT01.json')" in text and 'R.pack(' in text and "'continuous_floor_watch_claim': False" in text and 'floor()' in text,'exclusiveoneuse/observedfloors');ck({p.name for p in CAP.iterdir()}=={'capture01.py'},'capture notyetexecuted');ck(not CAP.is_relative_to(S) and not CAP.is_relative_to(P),'captureoutputs outsidebothroots');ck(sum(r.get('bytes',0) for r in sm['members']+pm['members'])<=R.BASE and shutil.disk_usage(CAP).free>=R.FLOOR,'actualcombinedscope within128MiB floor');ck(R.scan(S)==sm and R.scan(P)==pm and git(['rev-parse','HEAD']).decode().strip()==H and git(['status','--porcelain','--untracked-files=all'])==b'','completefinalsourceparent unchanged');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numericalimports');out={'schema_version':1,'decision':'ACCEPTED_UNRELEASED_ACTUAL_COMPOSITION_AND_CAPTURE_SOURCE_ONLY','checks':len(checks),'source':H,'source_members':878,'parent_members':15,'tracked':290,'source_pins':289,'implementation':194,'package':149,'copied_helpers':7,'copied_proofs':5,'draft_request_sha256':sha(read(P/'REQUEST_DRAFT01.json')),'composition_sha256':sha(read(C/'COMPOSITION01.json')),'capture_source_sha256':sha(source),'source_manifest_sha256':sha(read(C/'SOURCE_MANIFEST01.json')),'parent_manifest_sha256':sha(read(C/'PARENT_MANIFEST01.json')),'runtime_records':records,'runtime_executable_bytes':en,'current_Torch_API_equality':None,'actualdraftrefused':True,'claims':0,'capture_or_recovery_executed':False,'final_review_full_recovery_null':True,'native_resource_capacity_release':False};(O/'READBACK01.json').write_bytes(R.encode(out));print(json.dumps({k:v for k,v in out.items() if k!='runtime_records'},indent=2))
