"""Independent source-only lineage interpretation; no source package imports."""
import ast,copy,hashlib,json,stat,sys
from pathlib import Path
D=Path(__file__).resolve().parent;I=D/'investigation';P=D.parent/'financial-genuine-wrapper-recordfix-dependent-source-investigation01-2026-10-04';CAP=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-recordfix-native-20261004-01/source');checks=[];sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
def ok(n,v):
 if not v:raise AssertionError(n)
 checks.append(n)
def put(n,v):(D/n).write_text(json.dumps(v,sort_keys=True,indent=2)+'\n')
ok('frozen investigation manifest',sha(P/'MANIFEST01.json')=='64ff8db301198076ca6b0ce20658f5fef1284da74a7bf56c78f10688f0445a1e');m=json.loads((P/'MANIFEST01.json').read_text());ok('complete investigation inventory',{p.relative_to(P).as_posix() for p in P.rglob('*') if p!=P/'MANIFEST01.json'}=={r['path'] for r in m['members']})
for r in m['members']:
 p=P/r['path'];q=I/r['path'];s=p.lstat();v=stat.S_IMODE(s.st_mode)==r['mode']==stat.S_IMODE(q.lstat().st_mode)
 if r['kind']=='file':v=v and stat.S_ISREG(s.st_mode) and s.st_size==r['bytes'] and sha(p)==sha(q)==r['sha256']
 else:v=v and p.is_dir() and q.is_dir()
 ok('manifest '+r['path'],v)
pins=json.loads((I/'SOURCE_PINS01.json').read_text());ad=json.loads((D.parent/'financial-genuine-wrapper-recordfix-outcome-verifier-preparation01-2026-10-04/SOURCE_ADOPTION01.json').read_text());ok('actual adoption metadata pin',sha(D.parent/'financial-genuine-wrapper-recordfix-outcome-verifier-preparation01-2026-10-04/SOURCE_ADOPTION01.json')==pins['adoption_sha256']);texts={};trees={}
for row in pins['actual_body_joins']:
 path=row['path'];actual=CAP/path;local=I/'source'/path;ok('source exact actual '+path,sha(actual)==sha(local)==row['sha256']==ad['source_files'][path] and actual.stat().st_size==row['bytes'] and stat.S_IMODE(actual.stat().st_mode)==row['mode']);texts[path]=local.read_text();trees[path]=ast.parse(texts[path])
ok('eight exact source bodies',len(texts)==8)
def fn(leaf,name):return next(n for path,t in trees.items() if path.endswith('/'+leaf) for n in t.body if isinstance(n,ast.FunctionDef) and n.name==name)
def text(leaf,name):
 path=next(k for k in texts if k.endswith('/'+leaf));return ast.get_source_segment(texts[path],fn(leaf,name))
comparisons=[('financial_wrapper_fixture.py','_parent','prior scientific provenance differs',False),('training.py','_reserve','continuation scientific provenance mismatch',True),('evaluation.py','recover_completed_model','recovery science differs',True),('financial_wrapper_fixture.py','_reference_state','reference scientific provenance differs',False)]
for leaf,name,msg,refusal in comparisons:
 function=fn(leaf,name)
 if refusal:expr=next(n.test for n in ast.walk(function) if isinstance(n,ast.If) and any(isinstance(z,ast.Constant) and z.value==msg for z in ast.walk(n)))
 else:expr=next(n.args[0] for n in ast.walk(function) if isinstance(n,ast.Call) and any(isinstance(z,ast.Constant) and z.value==msg for z in n.args))
 code=compile(ast.Expression(expr),'<actual '+name+' science predicate>','eval')
 # Deliberately incomplete scalar map, not a fabricated artifact provenance/claim.
 scalar={'source_commit':'old','cell_id':'same','source_hashes':['opaque-body-A'],'config_hash':'config','input_hash':'recipe','dictionary_hash':'dictionary','fold_id':'fold','model_execution':'backend'}
 for key,value in [('source_commit','new'),('cell_id','other'),('source_hashes',['opaque-body-B']),('config_hash','different'),('input_hash','different'),('dictionary_hash','different'),('fold_id','different'),('model_execution','other')]:
  changed=copy.deepcopy(scalar);changed[key]=value;ns={'value':{'provenance':scalar},'ref':{'provenance':scalar},'old':scalar,'prov':changed,'provenance':changed};answer=eval(code,ns);permitted=(not answer) if refusal else answer;expected=key=='source_commit' or name=='_reference_state' and key=='cell_id';ok('exact science comparison '+name+'/'+key,permitted==expected)
chain=fn('training.py','_reserve');expr=next(n.test for n in ast.walk(chain) if isinstance(n,ast.If) and any(isinstance(z,ast.Constant) and z.value=='unreviewed continuation chain' for z in ast.walk(n)));code=compile(ast.Expression(expr),'<exact chain predicate>','eval')
for previous,expected in [([],True),([Path('parent')],False),([Path('other')],True),([Path('parent'),Path('failed-child')],True)]:ok('one-prior-directory predicate '+repr(previous),eval(code,{'previous':previous,'parent':'parent'})==expected)
for name in ('_admitted','worker'):
 calls=[n for n in ast.walk(fn('job.py',name)) if isinstance(n,ast.Call) and ast.unparse(n.func) in ('admit','ResearchRun.start')];ok('genuine '+name+' no design/bindings forwarding',len(calls)==1 and {'source','root','registration','experiment'}<={k.arg for k in calls[0].keywords} and not {'design_source','bindings'}&{k.arg for k in calls[0].keywords})
cmd=text('job.py','_command');ok('CLI command single source','--source' in cmd and '--design-source' not in cmd and '--bindings' not in cmd)
jobtext=next(v for k,v in texts.items() if k.endswith('/job.py'));ok('CLI exposes no alternate design/bindings','--design-source' not in jobtext and '--bindings' not in jobtext)
admit=text('admission.py','admit');ok('genuine current HEAD required','source must equal the full current HEAD' in admit);ok('design original registration equal','design registration changed between freeze and execution' in admit);ok('parent exact recorded definition','parent_claim["experiment"] != experiments[exp["parent"]]' in admit);ok('terminal parent required','parent must have a terminal decision receipt before follow-up' in admit);ok('visible history and exact family','prior = claims(root)' in admit and 'claim["family"] != family' in admit and 'used >= ceiling' in admit)
verify=text('verify.py','verify_claim');ok('parent verification reads original committed registration','_blob(root, claim["source"], claim["registration"])' in verify and '_blob(root, claim["design_source"], claim["registration"])' in verify);ok('original source bodies verified from original revisions','_verify_sources(root, pinned, {claim["source"], claim["design_source"]})' in verify)
for leaf,name,needle in [('training.py','fit_cell',"load_checkpoint(continuation['checkpoint'],model,optimizer,rng,continuation['provenance'])"),('financial_wrapper_fixture.py','execute',"checkpoints.load_checkpoint(cp,probe,probe_optimizer,probe_rng,prior['provenance'])"),('financial_wrapper_fixture.py','_reference_state',"checkpoints.load_checkpoint(refcp,reference,op,rng,ref['provenance'])"),('evaluation.py','recover_completed_model','read_artifact(checkpoint,old)')]:ok('load exact original provenance '+name,needle in text(leaf,name))
parent=text('financial_wrapper_fixture.py','_parent');ok('prior FAILED versus COMPLETE exact lifecycle',"status='failed' if p['phase']=='continue100' else 'complete'" in parent and "terminal_raw==(directory/(status+'.json')).read_bytes()" in parent);ok('all checkpoint members registered','every checkpoint body must be a genuine registered input' in parent and "path.stat().st_size==item['size']<=FILE" in parent)
interrupt=text('financial_wrapper_fixture.py','_interrupt_parent');ok('original absolute failed/diagnostic paths binding',"'last_checkpoint':str(checkpoint)" in interrupt and "'checkpoint':str(checkpoint)" in interrupt);ok('original fit claim fresh parent',"'parent_checkpoint':None" in interrupt);ok('original planned failure strict',"'type':'PlannedInterruption'" in interrupt and 'prospective engineering failed-parent fixture after one real update; no fit completion' in interrupt)
reference=text('financial_wrapper_fixture.py','_reference_state');prediction=text('evaluation.py','recover_completed_model');ok('reference complete100 cursor',"complete['epochs']==100" in reference and "state['epoch']==100 and state['batch']==0" in reference);ok('reference physical path binding',"Path(complete['checkpoint']).resolve()==refcp.resolve()" in reference);ok('prediction physical path binding',"Path(completion['checkpoint']).resolve()!=checkpoint.resolve()" in prediction)
# Plain absolute-path projections prove root relocation changes literal joins; no receipt/read.
old=CAP/'research_artifacts/onchain_fit_cells/opaque/parent/checkpoints/opaque/manifest.json';new=Path('/home/malecada/master_thesis/opaque-relocated-companion/source')/old.relative_to(CAP);ok('different root changes absolute string',str(old)!=str(new));ok('different root changes resolved checkpoint',old.resolve()!=new.resolve());ok('same root retains original checkpoint',str(CAP/old.relative_to(CAP))==str(old))
execute=text('financial_wrapper_fixture.py','execute');ok('genuine cursor and reference validation before fit reservation',execute.index('_one_epoch_state(loaded)')<execute.index('_reference_state(run')<execute.index('training.fit_cell('));ok('prediction zero optimizer updates',"'optimizer_updates':0" in execute);ok('original100 completion retained',"len(fitted.logs)==100" in execute and "len(fitted.logs)" in execute)
provenance=text('financial_wrapper_fixture.py','provenance');ok('source commit separately recorded',"'source_commit':run.admission.source" in provenance);ok('implementation hash-set separate from gate metadata',"'source_hashes':sorted(set(sources.values()))" in provenance);ok('task part of config provenance',"'task':p['task']" in provenance)
ok('no numerical modules imported',not any(n in sys.modules for n in ('torch','numpy','scipy','pandas')))
put('CHECKS01.json',{'verdict':'ACCEPTED_CONDITIONAL_SOURCE_COMPATIBILITY','count':len(checks),'checks':checks,'actual_admission_calls':0,'actual_output_reads':0,'actual_claim_reads':0,'numerical_imports':0,'actual_topology_decision':None,'qualification':'AST/source and intentionally incomplete scalar/path projections only; no Run/Owner/artifact provenance or real/fake claim object.'});print(json.dumps({'count':len(checks),'verdict':'ACCEPTED_CONDITIONAL_SOURCE_COMPATIBILITY'}))
