from pathlib import Path
import json,os,hashlib,stat,subprocess,datetime,sys
H=Path(__file__).resolve().parent;C=H.parent/'heartbeat-root-checkpoint10-2026-10-04';CAP=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-root-launch-20261004-01');I='financial-wrapper-classification-eager-interrupt1-claimedrun-20261004-01';SOURCE='0a2e7639b42b9423b90743feadcda4078aa21816';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ok(v,n):assert v,n;checks.append(n)
def read(p):
 s=p.lstat();ok(stat.S_ISREG(s.st_mode) and not p.is_symlink() and s.st_size<=4*1024**2,'bounded regular '+p.name);b=p.read_bytes();ok((s.st_dev,s.st_ino,s.st_size,s.st_mtime_ns,s.st_ctime_ns)==(p.stat().st_dev,p.stat().st_ino,p.stat().st_size,p.stat().st_mtime_ns,p.stat().st_ctime_ns),'stable '+p.name);return b
def js(p):return json.loads(read(p))
run=CAP/'research_runs'/I;job=CAP/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/I;eng=CAP/'research_artifacts/financial_wrapper_engineering'/I;fit=next((CAP/'research_artifacts/onchain_fit_cells').glob('*/'+I));claim=js(run/'claim.json');failed=js(run/'failed.json');guard=js(job/'guard/final.json');parent=js(P/'attempt/parent-terminal.json');outer=js(C/'ROOT_NATIVE_LAUNCH01_EXIT.json')
ok(sha(read(C/'ROOT_NATIVE_LAUNCH01_EXIT.json'))=='1863906b1ac82e993b7111180a2bcc326bf945a1b8ec0b23b89a425e748508a4','actual outer receipt pin');ok(claim['source']==claim['design_source']==SOURCE and claim['effective_attempt_budget']==19,'actual admitted source/19');ok(failed['claim_sha256']==sha(read(run/'claim.json')) and failed['status']=='failed' and failed['output_sha256']=={},'failed claim join');ok(failed['reason'].startswith('PlannedInterruption:'),'planned failure reason');ok(claim['bindings'] is None and claim['bindings_sha256'] is None,'original synthetic bindings remain null')
gate=js(CAP/claim['registration']);ok(sha(read(CAP/claim['registration']))==claim['registration_sha256'],'gate pin');ok(len(claim['inputs'])==8 and len(claim['experiment']['source_files'])==338,'eight338')
for n,d in claim['inputs'].items():ok(sha(read(CAP/d['path']))==d['sha256'],'input '+n)
for n,pin in claim['experiment']['source_files'].items():ok(sha(read(CAP/n))==pin,'source '+n)
ok(subprocess.check_output(['git','-C',str(CAP),'rev-parse','HEAD'],text=True).strip()==SOURCE,'actual Git HEAD');tracked=subprocess.check_output(['git','-C',str(CAP),'ls-tree','-r','--name-only',SOURCE],text=True).splitlines();ok(len(tracked)==339,'actual339tracked')
runtime=js(CAP/claim['inputs']['runtime_mapping']['path']);ok(len(runtime['distribution_records'])==251,'251 RECORD');ok(sha(read(Path(runtime['resolved_executable'])))==runtime['executable_sha256'],'interpreter')
for d in runtime['distribution_records']:ok(sha(read(Path(d['record'])))==d['record_sha256'],'RECORD '+d['name'])
old=CAP/'research_runs/financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01';oldc=js(old/'claim.json');oldf=js(old/'failed.json');ok(oldc['effective_attempt_budget']==18 and oldf['claim_sha256']==sha(read(old/'claim.json')),'old spent history18');ok(len(list((CAP/'research_runs').glob('*/claim.json')))==2,'two genuine claims');ok(not list((CAP/'research_runs').glob('*/complete.json')),'zero complete claims')
for k in ('extension','review'):
 d=claim['experiment']['cumulative_budget_extension'][k];ok(sha(read(CAP/d['path']))==d['sha256'],'extension '+k)
ok(parent['actual_parent_exit'] is None and parent['actual_child_exit']==1 and parent['supervisor_result']['exit_code']==1,'original parent null/child1');ok(parent['cleanup']['cgroup_absent'] and parent['cleanup']['joined_unit_stopped'],'parent cleanup')
ok(guard['phase']=='failed' and guard['child_exit_code']==1 and guard['cleanup_verified'] and guard['retry'] is False,'native terminal');ok(guard['memory_high_bytes']==guard['memory_max_bytes']==3*1024**3 and guard['memory_swap_max_bytes']==0,'native memory controls');ok(guard['wall_seconds']==1800 and guard['reserve_bytes']==3*1024**3 and guard['start_reserve_bytes']==6*1024**3,'native time/reserve');ok(guard['native_unit_properties']=={'LimitFSIZE':'4194304','LimitFSIZESoft':'4194304','RuntimeMaxUSec':'30min'},'native unit file/time');ok(guard['disk_floor_bytes']==10*1024**3 and min(guard['disk_free_bytes'].values())>=10*1024**3,'diskfloor');ok(not guard['elapsed_time_kill'] and all(v==0 for v in guard['memory_events'].values()),'no observed memory/time kill');ok(len(guard['cpus'])==2 and all(mask and set(mask)<=set(guard['cpus']) for mask in guard['cpu_thread_readback'].values()),'CPU masks')
ready=js(job/'guard/cpu_ready.json');worker=js(job/'worker-file-limit.json');owner=js(job/'owner.json');ok(ready['cpus']==guard['cpus'] and ready['file_size_limit']==worker['file_size_limit']==[4194304,4194304] and worker['before_claim'],'early ready/file control');ok(guard['owner_identity']==owner,'genuine monitor Owner identity');obs=js(job/'observer.json')
for n,pin in obs['evidence_sha256'].items():ok(sha(read(job/n))==pin,'observer '+n)
ok(obs['financial_completion'] is False and obs['status']=='failed','observer failure');cell=js(job/'postmortem-cells.json');ok(len(cell)==1 and cell[0]['status']=='unavailable','unavailable cell')
diagnostic=js(eng/'interrupted-checkpoint.json');checkpoint=Path(diagnostic['checkpoint']);man=js(checkpoint);ok(sha(read(checkpoint))==diagnostic['sha256'] and diagnostic['epochs_completed']==1 and diagnostic['requires_genuine_failed_parent'] is True,'checkpoint diagnostic');ok(man['provenance']==diagnostic['provenance']==js(fit/'claim.json')['provenance'],'checkpoint provenance');ok(man['provenance']['source_commit']==SOURCE,'checkpoint source');ok(man['key']==checkpoint.parent.name and set(man['members'])=={'state.pt'},'checkpoint identity')
for n,d in man['members'].items():b=read(checkpoint.parent/n);ok(len(b)==d['size'] and sha(b)==d['sha256'],'opaque checkpoint hash')
f=js(fit/'failed.json');ok(f['last_checkpoint']==str(checkpoint) and f['type']=='PlannedInterruption','failed fit checkpoint');epoch=js(fit/'epoch-0000.json');ok(epoch['epoch']==0 and epoch['examples']==16 and epoch['seed']==11,'one epoch journal');ok(not (fit/'complete.json').exists() and not (run/'complete.json').exists(),'no fit or research completion');ok(not list((run/'outputs').iterdir()),'no research output publication')
cleanup=js(P/'attempt/owned-tree-cleanup.json');pids=set(guard['cpu_thread_readback'])|{str(ready['pid']),str(worker['pid']),str(owner['supervisor_pid']),str(owner['monitor_pid'])}|{str(r['pid']) for r in cleanup['owned_pid_start_records']};live={p:(Path('/proc')/p).exists() for p in sorted(pids)};ok(not any(live.values()),'all recorded PIDs absent now');ok(not Path(guard['cgroup']).exists(),'original cgroup absent now')
# Complete genuine outcome roots copied as opaque bytes; never decode checkpoint.
scopes={'parent-attempt':P/'attempt','research-runs':CAP/'research_runs','job':job,'wrapper':eng,'fit':fit};inventory=[];dest=H/'evidence';dest.mkdir()
for role,root in scopes.items():
 for p in [root]+sorted(root.rglob('*')):
  rel=p.relative_to(root);s=p.lstat();row={'role':role,'root':str(root),'path':str(rel),'mode':stat.S_IMODE(s.st_mode)};target=dest/role/rel
  if stat.S_ISDIR(s.st_mode):target.mkdir(parents=True,exist_ok=True);row['kind']='directory'
  else:b=read(p);target.parent.mkdir(parents=True,exist_ok=True);target.write_bytes(b);row.update(kind='file',bytes=len(b),sha256=sha(b))
  inventory.append(row)
for n in ['ROOT_NATIVE_LAUNCH01_INTENT.json','ROOT_NATIVE_LAUNCH01_EXIT.json','ROOT_NATIVE_LAUNCH01.stdout','ROOT_NATIVE_LAUNCH01.stderr']:(H/n).write_bytes(read(C/n))
(H/'ORIGINAL_OUTCOME_CENSUS01.json').write_text(json.dumps(inventory,indent=2)+'\n');out={'checks':len(checks),'check_names':checks,'claim_sha256':sha(read(run/'claim.json')),'failed_sha256':sha(read(run/'failed.json')),'checkpoint_manifest_sha256':sha(read(checkpoint)),'checkpoint_state_sha256':man['members']['state.pt']['sha256'],'recorded_pid_absence':live,'monitor_start_ticks':owner['monitor_start_ticks'],'recorded_start_ticks':cleanup['owned_pid_start_records'],'current_observed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'guard_elapsed_seconds':guard['elapsed_seconds'],'peak_sampled_memory_current_bytes':guard['peak_sampled_memory_current_bytes'],'spent_claims':2,'highest_actual_allowance':19,'complete_fits':0,'cell_dispositions':cell,'original_parent_exit':None,'Root_actual_exit_evidence':outer,'full_checkpoint_tensor_decoding':False};(H/'READBACK01.json').write_text(json.dumps(out,indent=2)+'\n');print(len(checks))
