import ast,difflib,gzip,hashlib,json,os,stat
from pathlib import Path
H=Path(__file__).resolve().parent;BASE=H.parent
sha=lambda b:hashlib.sha256(b).hexdigest()
def put(n,x):(H/n).write_text(json.dumps(x,indent=2,sort_keys=True)+'\n')
checks=[json.loads((H/f'CHECKS{i:02}.json').read_text()) for i in range(1,5)]
# The original offline sparse negative is immutable. Add a lossless alternative
# representation; it does not replace the raw body or imply actual recovery.
p=H/'opaque01/file-cap/producer/large';raw=p.read_bytes();compressed=gzip.compress(raw,mtime=0);(H/'OFFLINE_OVERSIZE_RAW01.gz').write_bytes(compressed)
assert gzip.decompress(compressed)==raw
put('OFFLINE_OVERSIZE01.json',{'path':str(p.relative_to(H)),'bytes':len(raw),'sha256':sha(raw),'allocated_bytes':p.stat().st_blocks*512,'purpose':'offline opaque negative per-file refusal; outside actual native 4MiB cap','original_preserved':True,'lossless_representation':'OFFLINE_OVERSIZE_RAW01.gz','gzip_bytes':len(compressed),'gzip_sha256':sha(compressed),'actual_remote_or_fresh_recovery':None})
refs={}
for directory,names in {
 'financial-batch-output-genuine-production-handoff-investigation01-2026-10-04':['MANIFEST01.json','HANDOFF01.json','REPORT01.md','SOURCE_BODIES01.json'],
 'financial-batch-output-genuine-byte-bridge-preparation01-2026-10-04':['MANIFEST01.json','byte_bridge01.py','owned_io.py'],
 'financial-batch-output-chunk-storage-preparation02-2026-10-04':['MANIFEST02.json','codec01.py','local_store01.py'],
}.items():
    for name in names:
        p=BASE/directory/name
        refs[str(p)]={'bytes':p.stat().st_size,'sha256':sha(p.read_bytes())}
put('PREDECESSOR_PINS01.json',refs)
protocol={'status':'DRAFT_SOURCE_ONLY_NOT_RELEASED','schema_version':1,'grant_role':'storage_lease','grant_template':{'schema_version':1,'kind':'two-imported-target-retained-lease-v1','execution_job_sha256':None,'roles':None,'targets':None,'max_logical_bytes':None,'max_allocated_bytes':None,'max_file_bytes':4194304,'free_floor_bytes':10737418240,'root_scope':'entire-admission-root','publication':False,'transport':False,'retirement':False},'actual_admitted_source':None,'actual_grant':None,'genuine_entrypoint_execution':None,'caller_native_release':None,'original_source339_explicitly_refused':'0a2e7639b42b9423b90743feadcda4078aa21816','new_source_requirements':{'helper':'storage_lease01.py','helper_sha256':sha((H/'storage_lease01.py').read_bytes()),'copied_owned_io_sha256':sha((H/'owned_io.py').read_bytes()),'loaded_reducer_origin':'original admitted held_score_consumer.PREFIX/owned_io.py','existing_source_policy':'must separately admit new source closure and exact source_files entries; original 202/151/207 versus194/149/338 contracts cannot be relabeled','self_hash_cycle':False},'operational_requirements':['One genuine active original resource-only Owner/Binding/Run and current Target/held token.','Entire admission root canonical, same device and UID; no secret, symlink, hardlink or special members; all preexisting bytes retained.','One fixed ledger namespace retained-lease-<actual workflow identity>; existing namespace always refuses.','Create shared lease before original writes; reserve all exact prospective directory/file paths before production. Existing immutable original raw bodies remain unchanged; append tickets freeze final extent.','Every producer, batch, output, codec, spool, recovered, journal, diagnostic and scratch writer must use the shared core, with callback checks and unchanged original native watches. Uninstrumented writers remain unsupported.','Only exact original two tiny imported targets of2/3 nodes with32motifs512samples. No financial population grant.','All external Parent/remote/recovery paths require their original independent native watch and a future separately reviewed aggregate design; this lease refuses claiming them inside its whole-root census.','Real source/runtime/input/grant registration, original ancestry checks, independent source review, external and fresh recovery precede live adoption.'], 'monotone_reservations':{'maximum_allowed_each':1073741824,'journal_slots':128,'journal_body_cap':65536,'journal_allocated_per_slot':131072,'ledger_directory_headroom':1048576,'baseline_scratch':4194304,'block_rounding':65536,'per_file_entry_headroom':65536,'per_new_directory_headroom':1048576,'new_copy_credit_or_refund':0},'claims_not_tested':['genuine scientific handles','numerical agreement/joint gradients','financial returns/cashflows/fees','full population or100epochs/1420fits','kernel quota/inter-sample hard bound','network/remote authority/recovery/retirement']}
put('PROTOCOL01.json',protocol)
summary={'status':'IMPLEMENTED_SOURCE_ONLY_AWAITING_DIFFERENT_AUTHOR_REVIEW','source_sha256':sha((H/'storage_lease01.py').read_bytes()),'owned_io_sha256':sha((H/'owned_io.py').read_bytes()),'control_runs':[{'run':i+1,'checks':c['checks'],'source_sha256':c['source_sha256']} for i,c in enumerate(checks)],'total_reported_control_assertions':sum(c['checks'] for c in checks),'interpretation':'CHECK01/02 repeat155 controls across original/refined utility; CHECK03 source/refinement controls; CHECK04 final one-predicate inverse/absence guard. Not independent scientific experiments.','original_source_changes':0,'new_helper_installed':False,'actual_current_source_supported':False,'original_file_negative_preserved':True,'hardlink_groups_preserved':True,'genuine_handles_constructed':False,'numeric_imports':False,'external_actions':False,'actual_capacity_or_production_permission':False,'raw_control_failures':'All four control processes exited0; intentional refusal outcomes retained in CHECKS and physical fixture trees. No failed traceback omitted.','harness_limits':['The unused initial callback_mutation setup in CHECK03 retained only its start record; its descriptors were relinquished by interpreter exit, not counted as explicit close assertions.','The initial check01 missing-directory control removes only a newly created empty opaque fixture directory, not original or live data.','An incidental empty /tmp/storage_patch_instruction_placeholder was created by an unused shell preamble; it carries no inputs or authority and is outside the evidence tree.']}
put('MACHINE01.json',summary)
report=f'''# Retained-workflow storage lease — source preparation only

A concrete uninstalled stdlib lease is implemented in `storage_lease01.py` ({summary['source_sha256']}). It measures every entry beneath one canonical retained root once, using parent descriptors, no-follow opens, stable before/after signatures, actual UID/device and a bounded census. Both file and directory logical sizes and allocated `st_blocks*512` are included. Scientific body bytes are not read or decoded. Link/special/hardlink/secret-path/namespace changes refuse. No scan exclusions or duplicated nested-root totals are used.

The complete role set is producer, batches, outputs, codec, spool, recovered, diagnostic, journal and scratch. `OwnedLease.reserve` records exact projected paths before writes, includes full copy sizes without prior-allocation credit, rounded blocks/entry/directory headroom,128 finite journal slots and retained scratch. Both cumulative counters only increase. Missing/unwritten tickets remain spent. Existing source and unreserved files are frozen by inode/mode/size/allocation/modification signatures; permitted append tickets freeze at declared final extent. Bytes disappearing, shrinking, moving or changing outside a ticket refuse. The original4MiB file ceiling, at most1GiB whole ceiling and10GiB free floor plus outstanding allocation commitment are not raised. Actual admitted lower limits must prevail.

`perform` executes a writer after reservation and outside the lease's own operation lock, permitting bounded periodic `check` callbacks. Recursive checks from the boundary itself refuse without waiting. Every failure poisons permanently, independently attempts a bounded failed journal record when possible, retains partial bytes/spend/errors, and closes both owned descriptors with the exact original first-fatal reducer. A failed diagnostic write does not fabricate a failed record. No resource descriptor is retried after uncertain close. Journal records are evidence of utility actions, not research claims or remote acknowledgments.

`GenuineLease` composes existing original Target, Owner, Binding, ResearchRun and `_HeldTransition` class identities from already loaded genuine modules. It invokes held.check, Binding.check, Target.check and compact_owner.verify_current without reacquiring Owner's held lock. Same-owner/Run rebinding accepts later genuine held transitions while retaining the original core and one-use workflow ledger. Original imported policy512/32, actual2/3-node two-target denominator, admitted source-origin/self hash, unchanged reducer alias, exact execution_job/grant bytes, original resource-only context and native storage maxima are required. Source339/0a2, financial_wrapper and missing grants explicitly refuse. No fake handles were constructed. These source joins have not been executed with genuine scientific handles.

The original producer role derives `research_artifacts/onchain_compact_mcm/<workflow>/<experiment>`; batches use the actual Owner root; output role derives `onchain_compact_outputs/<workflow>/<experiment>`. Codec/diagnostic paths use the actual Run directory, covering the existing byte bridge's per-role/per-graph subtrees. Spool/recovered/scratch are fixed prospective Run subtrees and journal uses the original Binding journal directory. The whole admission-root census also counts all original Git/source/baseline bytes. An actual path outside that root cannot receive a ticket. Root must separately authenticate any external Parent/native/remote roots and a complete future combined storage policy; this helper does not claim those paths were measured.

Control evidence comprises {summary['total_reported_control_assertions']} reported assertions across four runs, including two155-assertion runs on successive source drafts, independent direct `lstat` total reconstruction, all retained role bodies, actual hardlinks/lexical redirects, partial/callback/fatal/journal failures, real close attempts and source/inverse joins. CHECK01's sparse4MiB+1 offline negative remains unchanged (zero allocated blocks), with a separately verified lossless gzip representation. It is outside the native file cap and is never admitted capacity. Subsequent per-file tests used tiny scaled controls. All original fixture bytes, hardlink groups, drafts and raw stdout/stderr are retained. The unused CHECK03 setup and incidental empty preamble file are disclosed in MACHINE01, not counted as successful cleanup controls.

No baseline implementation, bridge, codec, spool, router, scientific conversion, registration, source capsule or live caller was changed. Exact original source hashes and AST definitions are in SOURCE_JOINS01; preparation references are in PREDECESSOR_PINS01. Two uninstalled internal drafts and literal patches preserve the implementation sequence. The final draft02→final change checks Target type before attribute access and has full byte/AST inverse.

Required next steps remain different-author review, exact final source/input/role/grant adoption, integration of every actual writer before its writes, measured original native whole watches and outer deadline, genuine numerical agreement/joint-gradient checks, whole-population/cumulative capacity and actual typed remote/fresh recovery. This is sampled metadata engineering, not a filesystem quota, atomic concurrent snapshot, deletion permission, disk saving, scientific representation-complete receipt, paper fit or financial return. No100-epoch/full1420-fit feasibility was tested. The conditional full population/tails exceed this bounded local policy; they stay unavailable rather than receiving a cap increase or subset substitution.
'''
(H/'REPORT01.md').write_text(report)
entries=[]
for p in sorted(H.rglob('*'),key=lambda p:p.relative_to(H).as_posix()):
    if p.name=='MANIFEST01.json' and p.parent==H:continue
    s=p.lstat();row={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
    if stat.S_ISLNK(s.st_mode):row.update(kind='symlink',target=os.readlink(p))
    elif stat.S_ISDIR(s.st_mode):row.update(kind='directory')
    elif stat.S_ISREG(s.st_mode):row.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()),nlink=s.st_nlink)
    else:raise RuntimeError('unaccounted type')
    entries.append(row)
put('MANIFEST01.json',{'schema_version':1,'status':'SOURCE_ONLY_UNINSTALLED_PREPARATION','root':str(H),'entries':entries,'members':len(entries),'regular_files':sum(r['kind']=='file' for r in entries),'literal_links':sum(r['kind']=='symlink' for r in entries),'file_bytes':sum(r.get('bytes',0) for r in entries),'excludes':['MANIFEST01.json']})
# No further writes after this point; full exact membership and all file/link pins.
m=json.loads((H/'MANIFEST01.json').read_text());actual={p.relative_to(H).as_posix() for p in H.rglob('*') if p!=H/'MANIFEST01.json'};assert actual=={r['path'] for r in entries}
for row in entries:
    p=H/row['path'];s=p.lstat();assert stat.S_IMODE(s.st_mode)==row['mode']
    if row['kind']=='file':assert s.st_size==row['bytes'] and s.st_nlink==row['nlink'] and sha(p.read_bytes())==row['sha256']
    if row['kind']=='symlink':assert os.readlink(p)==row['target']
print(json.dumps({'manifest_sha256':sha((H/'MANIFEST01.json').read_bytes()),'machine_sha256':sha((H/'MACHINE01.json').read_bytes()),'source_sha256':summary['source_sha256'],'report_sha256':sha((H/'REPORT01.md').read_bytes()),'members':len(entries),'files':m['regular_files'],'bytes':m['file_bytes'],'links':m['literal_links'],'control_assertions':summary['total_reported_control_assertions']}))
