import hashlib,importlib.util,json,os,shutil,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=F/'financial-genuine-wrapper-root-recordfix-final-flat01-2026-10-04';A=F/'financial-genuine-wrapper-recordfix-final-union-recovery-preparation01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
for n in ['restore_union01.py','recovery04.py','owned_io.py','bounded_git01.py']:ck((P/n).read_bytes()==(A/n).read_bytes(),'exact installed accepted helper '+n)
ck(sha((P/'restore_union01.py').read_bytes())=='2bda6b41ef21c1ed8e1e38a10d5cc3f982ae8d30beb5ae4425fe2b701ee3cc02','adapter exact pin')
sys.path.insert(0,str(P));sp=importlib.util.spec_from_file_location('installed_union_adapter',P/'restore_union01.py');M=importlib.util.module_from_spec(sp);sp.loader.exec_module(M)
raw=M.R.read(P,'REQUEST_PROPOSAL01.json');ck(sha(raw)=='aea68a9043843b2aff6aa71a00085cc3343ad3d505bca8f7a75cbe8f436844b9','exact actual proposal');q=json.loads(raw);ck(M.R.encode(q)==raw and q['release'] is None,'canonical unreleased proposal');ck(M.contract(q)=='6a18658b55c71cfd16e7fb76b2bff14a1c714f7f03b16c3f587c79b675080beb','exact release-excluded contract')
try:M.request(q)
except ValueError as e:ck(str(e)=='unreleased release','actual installed adapter rejects null release')
else:raise AssertionError('unreleased accepted')
review=M.reference(q['review']);ck(review==(F/'financial-genuine-wrapper-recordfix-final-union-recovery-review01-2026-10-04/READBACK01.json').read_bytes() and sha(review)=='e2b8f329aecfe41cf479ca74c39d09115ff369d7e49a2f17e1cf8d8cc1249d68','actual source review proof copy')
remote=Path(q['remote_root']);b=M.selected(remote,q);manifest=M.manifest_join(q,b['manifest']);ck(len(manifest['members'])==307 and q['expected_files']==276 and q['expected_logical_bytes']==3853463,'actual exact complete union denominator');ck(q['remote_receipt_sha256']=='c8a23f7b834a61e8da93dc1793ffcb6937559e558eee07f0c3a9cbad05893f51' and q['remote_commit']=='712fee46e11dece8138ab08778a1f9819a10cad3','actual independently accepted remote lineage')
ck(sha((O/'MANIFEST03.json').read_bytes())=='19c7b7d4bf6eccc1d5299c42f2c0fba7a58a023bab5fdd61346bb968a9a3ad4a','closed independent actual remote review')
out=Path(q['output_root']);ck(out==F/'financial-genuine-wrapper-recordfix-final-union-flat-20261004-01' and not os.path.lexists(out),'exact fresh one-use output');free=shutil.disk_usage(F).free;ck(free>=10*1024**3,'actual observed diskfloor')
release={'schema_version':1,'decision':'accepted-exact-one-use-final-union-flat','contract_sha256':M.contract(q),'helper_sha256':sha((P/'restore_union01.py').read_bytes()),'review_sha256':sha(review)};releasepath=O/'FLAT_RELEASE04.json';releasepath.write_bytes(M.R.encode(release));bound=dict(q,release={'path':str(releasepath),'sha256':sha(releasepath.read_bytes())});ck(M.request(bound)==(remote,out),'actual installed adapter validates exact genuine independent release without recovery');ck(not os.path.lexists(out),'no actual output created');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numerical imports')
x={'schema_version':1,'decision':'EXACT_FINAL_UNION_FLAT_REQUEST_RELEASED_PENDING_ROOT_EXECUTION','checks':len(checks),'proposal_sha256':sha(raw),'contract_sha256':M.contract(q),'release_sha256':sha(releasepath.read_bytes()),'source_review_sha256':sha(review),'actual_remote_review_sha256':sha((O/'REMOTE_READBACK03.json').read_bytes()),'observed_free_bytes':free,'actual_restore_performed':False,'numerical_authority':False};(O/'FLAT_RELEASE_READBACK04.json').write_bytes(M.R.encode(x));print(json.dumps(x,sort_keys=True))
