import datetime,hashlib,json,os,stat
from pathlib import Path
M=Path.cwd();B=M/'research/onchain-paper-replication-2026-09-24/full_sources'
D=B/'financial-genuine-wrapper-root-claimedrun-budget19-preparation01-2026-10-04';D.mkdir(mode=0o700)
I=B/'financial-genuine-wrapper-postclaim-budget-investigation01-2026-10-04'
req=json.loads((I/'REQUIREMENTS01.json').read_text());dag=json.loads((I/'PHASE_DAG01.json').read_text())
assert hashlib.sha256((I/'MANIFEST01.json').read_bytes()).hexdigest()=='fec09987af651f0482fcba8c2c6cfc8239a1bd5fcf38e0cacb12a5e9c3c8fad3'
CAP=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-recordfix-native-20261004-01/source')
gate_raw=(CAP/'fixture_inputs/financial_wrapper_recordfix01/gates.json').read_bytes();assert hashlib.sha256(gate_raw).hexdigest()=='4474df26460aab41281bfdcc311129b613a90d76963e853858841200d9faa69a'
gate=json.loads(gate_raw);family=gate['families']['synthetic-financial-wrapper'];assert family==req['unchanged_base_family']
assert len(dag['rows'])==18 and len({r['proposed_execution_identity'] for r in dag['rows']})==18
ID=req['new_first_identity_proposal'];OLD=req['spent_unexpected_outer_preserved'];claim=CAP/'research_runs'/OLD
for name,h in [('claim.json','4c543d71fad5255be61087eaa3619d9e88cbbdc12fa1398bd7fa7fe6fb75c128'),('failed.json','35158c0ecebfe4dc75203ba87d5372f2f85643c0b5f828a99e17aa28fe79c450')]:
 body=(claim/name).read_bytes();assert hashlib.sha256(body).hexdigest()==h;(D/('historical-'+name)).write_bytes(body)
def put(p,v):
 assert not p.exists();raw=(json.dumps(v,sort_keys=True,indent=2)+'\n').encode();p.write_bytes(raw);return hashlib.sha256(raw).hexdigest()
allocation={'schema_version':1,'program_id':gate['program_id'],'family':'synthetic-financial-wrapper','unchanged_base_family':family,'actual_spent_before':1,'actual_highest_adopted_before':18,'prospective_cumulative_ceiling':19,'minimum_required_ceiling_derivation':'1 genuine permanent unexpected FAILED claim + 18 original still-required phase contracts = 19; no failed claim is refunded, moved, or substituted for a planned checkpoint.','remaining_phase_contracts':dag['rows'],'original_phase_dag':dag,'retained_reserved_predispatch_identity':req['old_predispatch_outer_preserved'],'retained_spent_unexpected_identity':OLD,'retained_old_gate_entry_count':len(gate['experiments']),'new_first_identity':ID,'new_first_parent':OLD,'new_first_prior_input':None,'new_first_reference_input':None,'parent_role':'Closed lifecycle correction ancestry only; original failure has no checkpoint/reference fit and supplies no scientific continuation authority.','claim_snapshot':req['required_closed_claim_snapshot'],'allocation_policy':'This ceiling retains all eighteen original phases; all eight dependent definitions remain withheld until their genuine checkpoint/reference/results are accepted and recovered. No score-based tuning, capacity escalation, paper-budget transfer or per-failure automatic cap ladder. Any further unexpected consumption requires a separately justified, prospectively reviewed cumulative amendment.','numeric_scientific_change':False,'paper_fit_credit':0,'paper_budget_extension':None,'original_model_sha256':'20f451c08143dd81491b5c9fa0a90243ee6a9363df1fbbfcbd9c45b32f9b054d','original_training_sha256':'d5276b75491e130bd03d43de28120f72dd792e42af4446382a6c127d387b8ec0','approved_method_change':'Only accepted f4ea651b wrapper claimed-run authorization seam; original model/method/protocol/runtime metadata and all other193 implementation bodies unchanged.','future_source_route':'NEW genuine isolated capsule with original649 Git ancestry and byte-identical complete historical closed claim directory, explicit reviewed relocation metadata and fresh root job/caller; no old Owner/absolute runtime or checkpoint authority transfer. Original Source/Parent/raw stores remain unchanged.','execution_requirements':['Complete actual failed-scope external/fresh flat recovery and independent acceptance','Exact actual source/current=design closure, registration/charter/extension/allocation and genuine independent review committed','Original copied closed claim verified from authentic original Git/source/inputs; no synthetic claim or missing receipts','Fresh caller/binding/Owner/Run/native release, complete preservation and actual fresh recovery','Fresh eligible source/runtime/process/namespace/memory/disk/native controls before ONE fixed fresh initial case'],'actual_new_registration':None,'actual_new_source':None,'actual_new_caller':None,'actual_new_admission':None}
ah=put(D/'ALLOCATION19.PROPOSAL.json',allocation)
extension={'schema_version':1,'program_id':gate['program_id'],'base_family':family,'cumulative_ceiling':19,'consumed_before':1,'initial_experiment':ID,'allocation':{'path':'fixture_inputs/financial_wrapper_claimedrun01/allocation19.json','sha256':ah},'claims':req['required_closed_claim_snapshot'],'reason':'The original fresh guarded engineering attempt permanently consumed one claim before fitting when the wrapper attempted fresh admission after its genuine ResearchRun.start claim. The accepted source correction reuses existing genuine Run authorization without changing shared repeat protection, paper model, runtime scientific bodies, protocol, tolerances or test outcomes. All eighteen original lifecycle phase contracts remain pending; cumulative19 preserves the failed claim plus those eighteen, while unchanged base18/prior0, old identities and paper budgets remain immutable. This is a finite prospective engineering amendment, not a retry or automatic cap ladder.'}
eh=put(D/'EXTENSION19.PROPOSAL.json',extension)
put(D/'FIRST_PLAN.PROPOSAL.json',req['new_first_plan_proposal'])
put(D/'PROPOSAL_AUTHENTICATION01.json',{'scope':'Concrete finite cumulative engineering amendment19 for independent review, not an admitted gate/source/numerical release','time_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_gate_sha256':hashlib.sha256(gate_raw).hexdigest(),'original_source_commit':'649fb8a11089524aaef7843dffeeb90a3a55ca17','investigation_manifest_sha256':'fec09987af651f0482fcba8c2c6cfc8239a1bd5fcf38e0cacb12a5e9c3c8fad3','allocation_sha256':ah,'extension_sha256':eh,'future_allocation_path':extension['allocation']['path'],'future_extension_path':'fixture_inputs/financial_wrapper_claimedrun01/extension19.json','actual_independent_extension_review':None,'actual_gate_integration':None,'actual_effective19_admission':None,'actual_highest_effective_budget':18,'actual_spent':1,'planned_phases_achieved':0,'paper_fits_completed':0,'native_started':False})
(D/'PROPOSAL_BUILDER01.py').write_bytes(Path(__file__).read_bytes())
(D/'PROTOCOL01.md').write_text('The cumulative nineteen proposal preserves the actual failed claim and all eighteen original phase contracts. It neither modifies the original eighteen base family nor grants a paper-budget extension. The independent review must authenticate the complete old claim/terminal bytes, phase DAG, original model/training and narrow accepted source correction. A new isolated source and reviewed closed-history relocation are required; all old source, Parent, gate, Owner and absolute job paths remain historical. The first new registration parent records only correction ancestry and cannot supply a checkpoint. Actual gate/current-design source pins, genuine admission, final caller, failed-scope recovery and native eligibility remain separate requirements.\n')
rows=[]
for p in sorted(D.iterdir()):
 s=p.lstat();assert stat.S_ISREG(s.st_mode)and s.st_size<=4*1024**2;rows.append({'path':p.name,'bytes':s.st_size,'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'mode':stat.S_IMODE(s.st_mode)})
mh=put(D/'MANIFEST01.json',{'scope':'Frozen concrete prospective allocation/extension, no fabricated accepted reviewer or execution authority','rows':rows})
print(json.dumps({'allocation_sha256':ah,'extension_sha256':eh,'manifest_sha256':mh,'actual_admitted19':False,'actual_spent':1,'new_admission_or_numeric':False}))
