import ast,datetime,hashlib,importlib.util,json,os,stat,sys,time
from pathlib import Path
H=Path(__file__).resolve().parent;B=H.parent;N=B/'financial-genuine-wrapper-root-claimedrun-final-capture02-2026-10-04';O=B/'financial-genuine-wrapper-root-claimedrun-final-capture01-2026-10-04';A=B/'financial-genuine-wrapper-claimedrun-final-union-recovery-preparation02-2026-10-04';checks=[]
sys.path.insert(0,str(A));import recovery04 as R
sha=R.digest
def ck(v,n):
 if not v:raise AssertionError(n)
 checks.append(n)
def raw(p):return R.read(p.parent,p.name)
def obj(p):return json.loads(raw(p))
def inventory(root):
 rows=[]
 def visit(p,n):
  s=p.lstat();before=R.sig(s);r={'path':n,'mode':stat.S_IMODE(s.st_mode)}
  if stat.S_ISDIR(s.st_mode):
   r['kind']='directory';rows.append(r)
   for c in sorted(p.iterdir()):visit(c,c.name if n=='.' else n+'/'+c.name)
   ck(R.sig(p.lstat())==before,'stable directory '+str(p));return
  if stat.S_ISLNK(s.st_mode):r.update(kind='lexical-symlink',target=os.readlink(p))
  else:ck(stat.S_ISREG(s.st_mode) and s.st_size<=R.FILE,'bounded regular '+str(p));body=raw(p);r.update(kind='file',bytes=len(body),sha256=sha(body))
  ck(R.sig(p.lstat())==before,'stable original '+str(p));rows.append(r)
 visit(root,'.');return sorted(rows,key=lambda r:r['path'])
ck(sha(raw(N/'capture02.py'))=='31f8c7dfdc39fdbadd2149cd0c7d9d18e9d6b766841a7171629d6b5b01e47ab0','actual installed capture source');ck(sha(raw(N/'shards01.py'))=='9c38c0893790c22e3b0142a8ab175dceb9b14dd0aeeb80edc206e5329ffcbbba','actual installed planner');ck(raw(N/'capture02.py')==raw(B/'financial-genuine-wrapper-claimedrun-final-capture-preparation02-2026-10-04/capture02.py'),'actual source unchanged from author');ck(sha(raw(B/'financial-genuine-wrapper-claimedrun-final-capture-review02-2026-10-04/MANIFEST01.json'))=='e2c313a07bb3051cd95d08931a626301b84c87e004425a33f8ef64e3a1ff5bc9','different author source acceptance')
mraw=raw(N/'union-manifest.json');m=json.loads(mraw);R.validate(m);ck(R.encode(m)==mraw and sha(mraw)=='c72030b48f422bcfa52b1bbb2ca3202b9c8a8447387330f818edd20a58fb8b5d','actual canonical virtual manifest');ck(raw(O/'union-manifest.json')==mraw,'old failed manifest identical');ck(len(m['members'])==1476 and sum(r['kind']=='file' for r in m['members'])==1186,'1476/1186 full virtual denominator');R.same(N/'union-bytes01',m);ck(True,'new full physical virtual union');R.same(O/'union-bytes01',m);ck(True,'failed old full physical virtual union identical')
mapraw=raw(N/'union-bytes01/ORIGINAL_TREES01.json');ck(raw(O/'union-bytes01/ORIGINAL_TREES01.json')==mapraw,'original mapping byte-identical');mapping=json.loads(mapraw);ck(sha(mapraw)=='6f78f76b941551b9b6c4d6d12b02d59d8b19d4b6df7f9d5145991527cb8463ea','mapping exact hash');expected=obj(A/'EXPECTED_ORIGINALS01.json');ck(sha(raw(A/'EXPECTED_ORIGINALS01.json'))=='40b4002ee1b0edf1d2d4e4202cf3d5c98834eb9656b02558caedf40d7261dc30','fixed actual complete original census');ck(mapping['scope_trees']==expected['scope_trees'],'all20 exact source trees');virtual={r['path']:r for r in m['members']};files=links=typed=logical=0;names={'ORIGINAL_TREES01.json'}
for t in mapping['scope_trees']:
 observed=inventory(Path(t['original_root']));literal=[]
 for r in t['members']:
  rr=dict(r);rr.pop('union_path',None);literal.append(rr);typed+=1;n=r['path'];p=t['scope'] if n=='.' else t['scope']+'/'+n
  if r['kind']=='lexical-symlink':ck(p not in virtual,'literal link not materialized');links+=1;continue
  names.add(p);ck(virtual[p]['kind']==r['kind'],'virtual typed member')
  if r['kind']=='file':ck((virtual[p]['bytes'],virtual[p]['sha256'])==(r['bytes'],r['sha256']),'complete mapped body');files+=1;logical+=r['bytes']
 ck(observed==literal,'actual complete original tree '+t['scope'])
ck(names==set(virtual) and (typed,files,links,logical)==(1525,1185,50,18864635),'whole original/global virtual exactness')
indexraw=raw(N/'SHARD_INDEX01.json');idx=json.loads(indexraw);ck(sha(indexraw)=='da1aa342283473a8d47e0101f90bd0b25ed093c6f88f5abd183374326885f25a','actual index pin');ck(R.encode(idx)==indexraw,'canonical index');spec=importlib.util.spec_from_file_location('actual_planner_only',N/'shards01.py');plan=importlib.util.module_from_spec(spec);spec.loader.exec_module(plan);plans=plan.partition(m);ck(len(idx['shards'])==len(plans)==11,'11 deterministic shards');global_names=[];summaries=[]
for row,planned in zip(idx['shards'],plans):
 ck(row['regular_paths']==planned['regular_paths'],'deterministic ordered group');smraw=raw(N/row['manifest']['path']);sm=json.loads(smraw);R.validate(sm);ck(sm==planned['manifest'] and R.encode(sm)==smraw and len(smraw)==row['manifest']['bytes'] and sha(smraw)==row['manifest']['sha256'],'actual complete shard manifest');ck(row['members']==len(sm['members'])<=256 and row['logical_bytes']==sum(x.get('bytes',0) for x in sm['members'])<=2097152,'bounded typed/logical shard');R.same(N/'shard-trees'/row['id'],sm)
 ar=raw(N/row['archive']['path']);ck(len(ar)==row['archive']['bytes']<=4194304 and sha(ar)==row['archive']['sha256'] and row['archive']['manifest_sha256']==sha(smraw),'actual shard archive extent/hash');expected_shard={x['path']:x for x in sm['members']};seen=[]
 framed=R.framed_members(ar)
 try:
  for name,info,body in framed:
   ck(name in expected_shard and name not in seen,'actual framed membership');r=expected_shard[name];ck(info.mode==r['mode'],'actual archive mode')
   if r['kind']=='directory':ck(info.isdir() and info.size==0,'actual framed directory')
   else:
    ck(info.isfile() and len(body)==info.size==r['bytes'] and sha(body)==r['sha256'],'actual framed complete body');ck(body==R.read(N/'union-bytes01',name),'raw union/archive body identical');global_names.append(name)
   seen.append(name)
 finally:framed.close()
 ck(seen==[r['path'] for r in sm['members']],'complete ordered framed shard');sink=R.Sink();R.tar_stream(N/'shard-trees'/row['id'],sm,sink);ck(sink.count==len(ar) and sink.hash.hexdigest()==sha(ar),'full canonical recompression byte hash')
 summaries.append({'id':row['id'],'archive':row['archive'],'manifest':row['manifest'],'members':len(seen),'regular_bodies':len(row['regular_paths']),'canonical_recompression':True})
ck(global_names==sorted(r['path'] for r in m['members'] if r['kind']=='file') and len(set(global_names))==1186,'sorted disjoint complete11 archive body cover');ck(max(r['archive']['bytes'] for r in summaries)==577966,'maximum actual archive')
authraw=raw(N/'UNION_AUTHENTICATION01.json');auth=json.loads(authraw);ck(sha(authraw)=='77c739cd3b2f1afb229a671ae1d873a55f8a93c4deff4f77a22f0989242529e7','actual auth pin');ck(auth['index']=={'path':'SHARD_INDEX01.json','bytes':len(indexraw),'sha256':sha(indexraw),'virtual_manifest_sha256':sha(mraw)} and auth['union_mapping_sha256']==sha(mapraw),'actual auth all index/virtual/mapping joins');ck((auth['ordinary_members'],auth['original_trees'],auth['original_typed_members'],auth['original_regular_members'],auth['original_lexical_links'],auth['shard_count'])==(1476,20,1525,1185,50,11),'actual auth complete counts');ck(auth['source_capture_reused_unchanged'] is True and auth['genuine_native_or_numerical_started'] is False and auth['free_bytes']>=R.FLOOR and 0<auth['elapsed_seconds']<120,'actual scope/resource observations')
# Reuse accepted source-only semantic join as a supplemental check, no restore/run/request.
spec=importlib.util.spec_from_file_location('accepted_sharded_semantics_only',A/'restore_sharded01.py');S=importlib.util.module_from_spec(spec);spec.loader.exec_module(S);qr={'manifest':{'sha256':sha(mraw)},'shard_index':{'bytes':len(indexraw),'sha256':sha(indexraw)},'expected_shards':11};semantic=S.authenticate_union(qr,m,idx,authraw,mapraw);ck(semantic['original_regular_members']==1185,'accepted semantic footer agrees with independent reconstruction')
source=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');capture=B/'financial-genuine-wrapper-root-claimedrun-source339-capture01-2026-10-04';smanifest=obj(capture/'source-manifest.json');ck(sha(raw(capture/'source-manifest.json'))=='fdf77348b81a4d6df8b420b98530f5485900a0461636e1c201506106b036dfd8','original completeSource339 manifest');R.same(source,smanifest);ck(True,'actual Source1029/747 unchanged')
parent=Path(next(t['original_root'] for t in mapping['scope_trees'] if t['scope']=='actual-parent'));q=obj(parent/'REQUEST_FINAL03.json');gate=obj(source/q['registration']);e=gate['experiments'][q['identity']];ck(e['source_files']==q['source_files'] and len(e['source_files'])==338,'actual338 sourcepins');ck({k:v['sha256'] for k,v in e['inputs'].items()}==q['input_hashes'] and len(e['inputs'])==8,'actual8 inputpins');ck(len(q['runtime_mapping']['distribution_records'])==251 and obj(source/e['inputs']['runtime_mapping']['path'])==q['runtime_mapping'],'actual251 runtime metadata')
for n,pin in q['source_files'].items():ck(sha(raw(source/n))==pin,'current source '+n)
for name,ref in e['inputs'].items():ck(sha(raw(source/ref['path']))==ref['sha256'],'current input '+name)
head=raw(source/'.git/HEAD').decode().strip();head=raw(source/'.git'/head[5:]).decode().strip() if head.startswith('ref: ') else head;ck(head==q['source']==q['design_source']=='0a2e7639b42b9423b90743feadcda4078aa21816','actual current=design Source');ck(not os.path.lexists(source/'research_runs'/q['identity']) and not os.path.lexists(parent/'attempt'),'no new claim/attempt')
term=obj(N/'ACTUAL_TOOL_TERMINAL02.json');intent=obj(N/'INTENT01.json');ck(sha(raw(N/'ACTUAL_TOOL_TERMINAL02.json'))=='0424ab894f81c9e545be25133e8ae1fd14f0f7561897dc24edacffef3bc9c850','actual toolterminal pin');ck(term['actual_tool']=={'completion':'00f491','exit':0,'session':73084,'start':'ca4a83'} and term['actual_root_process']==intent,'actual tool/intent joins');ck(intent['actual_root_pid']==498623 and intent['actual_start_ticks']==16294313 and intent['actual_pgid']==intent['actual_sid']==498620,'original observed process pins');ck(raw(N/'ACTUAL_CAPTURE01.err')==b'' and sha(raw(N/'ACTUAL_CAPTURE01.out'))==term['out_sha256'],'raw actual stdout/stderr');ck(not os.path.exists('/proc/498623'),'originalPID currently absent');group=[];unreadable=[];pids=sorted(p for p in Path('/proc').iterdir() if p.name.isdigit());ck(len(pids)<32768,'finite process census')
for p in pids:
 try:
  fields=(p/'stat').read_text().rsplit(')',1)[1].split()
  if int(fields[2])==498620 or int(fields[3])==498620:group.append({'pid':int(p.name),'pgrp':int(fields[2]),'session':int(fields[3]),'ticks':int(fields[19])})
 except (OSError,ValueError,IndexError):unreadable.append(p.name)
ck(not group,'no observed current original group/session member')
# Failed predecessor retains its exact complete census and raw partial, never accepted gzip.
oldmanifestraw=raw(O/'FAILED_SCOPE_MANIFEST03.json');oldmanifest=json.loads(oldmanifestraw);ck(sha(oldmanifestraw)=='fdda7c05fa6b46d3054ffb56841ab816d00b51ff6aac93f40d9bae0092d45ceb','old frozen failure seal');oldactual=R.scan(O);ck(oldactual['root_mode']==oldmanifest['root_mode'] and [r for r in oldactual['members'] if r['path']!='FAILED_SCOPE_MANIFEST03.json']==oldmanifest['members'] and len(oldmanifest['members'])==1484 and len(oldactual['members'])==1485,'old1484seal/current1485 complete');failed=obj(O/'ACTUAL_TOOL_TERMINAL02.json');ck(sha(raw(O/'ACTUAL_TOOL_TERMINAL02.json'))=='ef8e9f17782b1b7a01a3852c069bb3c8d2b8bb51c29b1fa0a6e8a632a9d6465b' and failed['actual_tool_exit']==1 and failed['successful_union_authentication_absent'] is True,'old actual failure disposition');partial=raw(O/'union.tar.gz');ck(len(partial)==4190463 and sha(partial)=='fc7d4f78ae2db603aec2b84d14d9b98558ad9ea7d356df0983253eeab019972b','raw old partial exact');ck(not os.path.lexists(O/'UNION_AUTHENTICATION01.json'),'old successful auth absent');ck(all(failed[k] is None for k in ('actual_parent_pid','actual_start_ticks','original_process_group_history')),'old original OS history remains null');err=raw(O/'ACTUAL_CAPTURE01.err');ck(sha(err)==failed['raw_stderr_sha256'] and b'archive exceeds4MiB' in err and b'CleanupFailure' in err,'old raw cap plus cleanup failures preserved')
required=[r for r in oldactual['members'] if not (r['path']=='union-bytes01' or r['path'].startswith('union-bytes01/'))];ck(len(required)==8 and all(r['kind']=='file' for r in required),'eight exact old support/partial files');R.put(H/'FAILED_SCOPE_RECOVERY_REQUIREMENTS01.json',{'schema_version':1,'old_root':str(O),'old_root_mode':oldactual['root_mode'],'complete_failed_original_members':1485,'old_frozen_manifest_sha256':sha(oldmanifestraw),'must_select_exact_outside_union_files':required,'union_recovery_mapping':{'old_prefix':'union-bytes01','new_virtual_manifest_sha256':sha(mraw),'new_shard_index_sha256':sha(indexraw),'ordinary_members':1476,'regular_bodies':1186,'byte_and_mode_identical':True,'recoverable_via_new_complete_canonical_shards':True,'restored_already':False},'old_partial_archive_semantics':'opaque incomplete failed bytes only; not parsed/extracted or credited as successful archive','actual_external_recovery':None,'old_status':'PERMANENT_FAILED'})
R.put(H/'ACTUAL_ROOT_CENSUS01.json',{'root':str(N),'members':inventory(N)});R.put(H/'SHARDS_READBACK01.json',{'shards':summaries,'restored':False,'canonical_recompression_all':True});R.put(H/'PROCESS_READBACK01.json',{'observed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'original_pid':498623,'original_ticks':16294313,'original_group_session':498620,'pid_currently_absent':True,'observed_group_session_members':group,'unreadable_or_raced_proc_pids':unreadable,'qualification':'Current bounded stat census only; no historical descendant-completeness or native capacity claim'})
ck(not any(n in sys.modules for n in ('numpy','torch','scipy','pandas')),'no scientific imports');R.put(H/'READBACK01.json',{'decision':'ACCEPTED_COMPLETE_ACTUAL_SHARDED_BYTE_CAPTURE','checks':len(checks),'check_names':checks,'auth_sha256':sha(authraw),'index_sha256':sha(indexraw),'virtual_manifest_sha256':sha(mraw),'mapping_sha256':sha(mapraw),'source':head,'shards':11,'ordinary_members':1476,'regular_bodies':1186,'original_trees':20,'original_typed_members':1525,'original_regular_bodies':1185,'original_literal_links':50,'all_canonical_archives':True,'old_failed_scope_body_mode_identity':True,'old_failed_partial_success':False,'actual_flat_recovery':None,'actual_external_recovery':None,'numerical_authority':False});print('PASS',len(checks))
