"""Seal this independent review only. No actual scope mutation or recovery entry."""
from pathlib import Path
import json,hashlib,ast,sys
HERE=Path(__file__).resolve().parent;F=HERE.parent
sys.path.insert(0,str(F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05'));from verify_capture01 import R

def body(n):return R.read(HERE,n)
def emit(n,v):R.put(HERE/n,v)
def sha(n):return R.digest(body(n))
final=json.loads(body('FINAL_RECOVERY_READBACK01.json'));remote=json.loads(body('REMOTE_OUTCOME_AND_FLAT_CORE_READBACK01.json'));entry=json.loads(body('FLAT_ENTRY_READBACK01.json'))
assert final['decision']=='ACCEPTED_ACTUAL_COMPATIBILITY_COMPLETE100_BYTE_RECOVERY' and final['original_regular']==845 and final['inline_failed_regular']==110
report='''# Independent actual complete100 byte recovery review

Accepted the actual four canonical02 REMOTE outcomes, their exact dependent FLAT entries, and the complete returned byte population. All four flat children and separate actual Root tool calls exited 0, with empty cleanup failures. Original inner Parent exits remain null. The directly observed eight recorded flat PIDs and four owned groups were absent; the earlier receiver review observed its 264 recorded PIDs and 260 groups absent. These are bounded recorded-process observations, not complete historical PID inventories.

The independent read-only verifier joined all 26 actual remotely returned PAX archives to all 845 original opaque files (77,970,429 bytes), all 845 actual flat body files and their 26 mapping sidecars. All 1,074 original CAP/Parent typed members, modes, complete membership and current signatures joined. Archive framing, exact member/type/mode/body hashes, disjoint 7/7/6/6 piece coverage, and original source32d were checked. The separately accepted actual 407-object Git recovery basis02900ae1 is reused; it was not reconstructed again. No checkpoint was deserialized and no numerical experiment was rerun.

The actual returned composite55539547 was decoded and its complete failed-attempt PAX payload independently authenticated: 110 regular files and 119 typed entries, including the four original failed Root directories and separate actual Root logs. All 110 bodies equal their preserved originals. The embedded original capture-review body remains literal. Its historical external_recovery_accepted=false remains unchanged; this later review supplies the actual byte-recovery disposition. All four original failed metadata identities remain permanently failed and add no financial claim, refund or budget transfer.

The source04 implementations and immutable owned IO/Git/PAX/watch dependencies were reused under their previously accepted exact pins. This review did not independently re-review its author's watch implementation. Whole-root samples remain bounded by 64 MiB logical,96 MiB allocated,4 MiB per file,32,768 members and5 seconds; the shared768 MiB margin and10 GiB free-space floor are sampled checks, not physical reservation or quota.

One concrete binding defect was caught before any flat invocation: each unused FLAT_CONTRACT01 named REMOTE_RECEIPT01.json and REMOTE_ROOT_EXIT01.json, while caller01.evidence resolves those names under the original receiver. Those receiver paths did not exist. The original contracts remain preserved. Only the two references were corrected in FLAT_CONTRACT02 to genuine REMOTE_RECOVERY01.json and ACTUAL_ROOT_EXIT01.json. Actual extracted caller validators, complete generated caller/body equality, all13 helper pins, literal genuine inner releases and the full final requests passed before the four outer releases were issued. No contract01 entry ran. Exact findings and eight missing-path readbacks are retained in FLAT_ENTRY_READBACK01.json.

The final direct verifier read226,308,156 bytes and completed47,628 checks. It rejoined all owned iterator cleanup and final sampled signatures. Root join01 was not executed: this independent direct complete-population verification discharges the same required cross-lane byte check without another restoration or duplicate full scan. Original receiver and flat receipts are retained separately; no successful outcome was fabricated from a source-only label.

The final proof matches the ten-field complete100_outcome_recovery interface in accepted continuation preclaim079df4af. Its terminal hash is the genuine completion recordbd54cb00 from the accepted outcome machine, not the separate original Parent terminal or Root exit. The claimc6c1106d, checkpoint2b127b8c and outcome27e29cab remain unchanged. The proof refers to this review's machine without a circular machine/proof hash dependency.

Scope exclusions remain: no POSIX tree recreation, installed runtime-package body recovery, unrelated-store recovery, continuous writer exclusion, whole-capacity claim, scientific paper fit, runtime admission, new numerical claim or continuation launch. Currentness is sampled at the completed read boundaries. The successful100 outcome remains synthetic engineering; source adoption and any next actual admission remain Root obligations. Closed predecessor source/refutation/review bodies and all failed histories remain unchanged.
'''
with (HERE/'REPORT01.md').open('x') as f:f.write(report)
machine={'schema_version':1,'decision':final['decision'],'reviewer':'/root/storage_watch_review','source':final['source'],'identity':final['identity'],'outcome_review_sha256':final['outcome_review_sha256'],'claim_sha256':final['claim_sha256'],'terminal_sha256':final['terminal_sha256'],'checkpoint_sha256':final['checkpoint_sha256'],'capture_sha256':final['capture_sha256'],'original_regular':845,'original_typed':1074,'original_bytes':77970429,'pieces':26,'lanes':4,'inline_failed_regular':110,'inline_failed_typed':119,'composite_sha256':final['composite_sha256'],'Git407_basis':final['Git407_basis'],'actual_receipts':final['lanes'],'actual_remote_outcome_readback_sha256':sha('REMOTE_OUTCOME_AND_FLAT_CORE_READBACK01.json'),'actual_flat_entry_readback_sha256':sha('FLAT_ENTRY_READBACK01.json'),'actual_final_readback_sha256':sha('FINAL_RECOVERY_READBACK01.json'),'report_sha256':sha('REPORT01.md'),'original_root_join_executed':False,'direct_independent_complete_join':True,'original_parent_exit':None,'universal_process_history':None,'sampled_currentness_only':True,'POSIX_reconstruction':False,'installed_runtime_bodies_recovered':False,'whole_capacity':False,'numerical_authority':False,'claim_authority':False,'watch_self_review':False,'failed_metadata_financial_claims':0,'previous_failed_histories_preserved':True}
emit('MACHINE01.json',machine)
proof={'schema_version':1,'kind':'complete100_outcome_recovery','decision':'accepted-actual-complete100-byte-recovery','source':final['source'],'identity':final['identity'],'outcome_review_sha256':final['outcome_review_sha256'],'claim_sha256':final['claim_sha256'],'terminal_sha256':final['terminal_sha256'],'checkpoint_sha256':final['checkpoint_sha256'],'review':{'path':str(HERE/'MACHINE01.json'),'sha256':sha('MACHINE01.json')}}
p=F/'financial-wrapper-continuation-proof-reuse01-2026-10-05/preclaim_reuse01.py';source=R.read(p.parent,p.name);assert R.digest(source)=='079df4afd2ad9cc0c303c400df48aca05f22fceba66fe363f0d0147bfe94800c';fn=next(n for n in ast.parse(source).body if isinstance(n,ast.FunctionDef) and n.name=='_reuse_contract');required=next(n for n in fn.body if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='required' for t in n.targets));assert set(proof)==ast.literal_eval(required.value) and len(proof)==10
emit('COMPLETE100_OUTCOME_RECOVERY_PROOF01.json',proof)
emit('PROOF_INTERFACE_CHECK01.json',{'schema_version':1,'actual_consumer_source_sha256':R.digest(source),'exact_required_fields':sorted(proof),'proof_sha256':sha('COMPLETE100_OUTCOME_RECOVERY_PROOF01.json'),'review_machine_sha256':sha('MACHINE01.json'),'terminal_kind':'original genuine complete record from outcome MACHINE.actual_terminal_sha256','future_admission_run':False})
m=R.scan(HERE);emit('MANIFEST01.json',m)
print(json.dumps({'decision':machine['decision'],'machine_sha256':sha('MACHINE01.json'),'report_sha256':sha('REPORT01.md'),'proof_sha256':sha('COMPLETE100_OUTCOME_RECOVERY_PROOF01.json'),'manifest_sha256':sha('MANIFEST01.json'),'manifest_members':len(m['members'])}))
