from pathlib import Path
import json,hashlib,os,stat
D=Path(__file__).resolve().parent;A=D.parent/'financial-wrapper-compatibility-operational-delta-remote-successor02-2026-10-04';H=lambda b:hashlib.sha256(b).hexdigest()
def put(n,o):(D/n).write_text(json.dumps(o,sort_keys=True,indent=2)+'\n')
assert H((A/'recover01.py').read_bytes())=='ada3dafc7250452cb6db2eb33cdd5b5ecddb776511e247efcbc858dbb446aabf';assert (A/'recover01.py').read_bytes()==(D/'recover01.py').read_bytes();assert len(json.loads((D/'CHECKS01.json').read_bytes()))==428;assert (D/'CHECK01.stderr').read_bytes()==b'';assert (D/'AUTHOR_CHECK_FREEZE01.err').read_bytes()
report='''# Independent remote successor02 source review

Decision: ACCEPTED_SOURCE_ONLY_COMPLETE15_REMOTE_SUCCESSOR. Acceptance is limited to exact sourceada3dafc7250452cb6db2eb33cdd5b5ecddb776511e247efcbc858dbb446aabf, its four declared edits, concrete fifteen-body scope, unchanged process-control implementation and exact accepted dependency closure. This is not an installed entry release, actual external recovery, final selected commit, or numerical authority.

All428 independent checks passed. The author manifest e461c94e5e39880a809454a32fe76e50fc13941524407a536a1f7b62f8ddcbd3 authenticates20 declared members. The two explicitly excluded latest harness output files were also copied as current raw evidence; they are not falsely described as original manifest members. Original CHECK_FREEZE01.err and the initial wrong-POLICY-key harness remain retained.

The complete four-edit literal inverse yields b08f6c2667d28d5415449807fd91dcb8bd898b784f981e209cfc042cca6ed290 and matches the actual permanently failed Root02 source byte-for-byte. Independent AST comparison confirms only REQUIRED, validate_fixed_selection and two main literals change. Every other module node and function, including Git child setup/4MiB OS readback, pipe caps,60-second per-operation checks,600-second/1024-operation guard, observed exit versus actual reaped exit, group kill/reap/close cleanup, fatal priority, saved-byte readback and entry failure retention, is unchanged. No Git process was launched for this review.

Exactly15 original Main bodies match the hardcoded paths, lengths and SHA256s; total507946 bytes. The old ten are preserved exactly and the five additional records cover the complete closed failed forensic capture. Git blob OIDs were independently computed from literal bodies. All15 are distinct. Missing, duplicate, extra, foreign, altered hash, bool, float, negative and oversize selected records refuse in the actual pure selector. Exact original main guard expressions independently check lowercase40-hex commit format, sorted unique path ordering, required explicit receipt/selection/origin/HEAD/body/OID joins and the operation denominator. The zero commit used in source-format controls is explicitly synthetic and grants no selection or origin authority. The fresh namespace is exactly fresh-operational-source-policy02.git; the receipt status suffix01 remains a format label and does not reopen the spent Root02 identity.

The actual operational snapshot41 typed/33 bodies/943578 bytes and failed snapshot42 descendants/31 bodies/114237 bytes match every mode and body. Independently rebuilding canonical gzip/PAX from each actual snapshot reproduces the frozen archive bytes. The original43-member failed scope projects exactly to all42 descendants with the root kept separately. FAILED7491cc3 still records original init observed exit null and actual reaped exit0, while capture retains Root exit1 and historical changed path/field unknown. The actual snapshots remain local capture evidence, with external receipt fields null.

The watch04 sourcebdeaca is authenticated only as an exact dependency. Genuine different-author combined review MACHINEaed1248d003fbe19ccbd5f0f57b6801e6cf08713bb01d6d9fa56a145e172bb57 and MANIFEST7a94ef046588cb9a10a978d63865302e0b12a25e60db98190aea9927ecc59f47 are independently byte/type/mode authenticated across all70 declared review members. Its decision is ACCEPTED_NARROW_SOURCE_ONLY_FIXED_PUBLICATION_RETRY_SCHEDULE and its copied machine/report/manifest match originals. This reviewer authored the watcher and does not independently accept it here. Its peer acceptance covers the fixed two100ms delays inside the original three-attempt/five-second sampled policy; no cap increase or scientific-method change is inferred.

The unchanged write helper was exercised only on owned opaque local files. A successful saved-byte readback and all nine ValueError/MemoryError/SystemExit primary/real-close-secondary combinations preserve expected fatal priority, retain partial files and balance actual descriptors. These tests use the pinned accepted watcher as a dependency and do not constitute a second independent watcher review. No main/entry, network, subprocess/Git child, numerical library, checkpoint decoder, genuine Run/Owner, registration, gate or ledger action occurred.

## Documentation finding D1 — prospective operation arithmetic

Location: author REPORT01.md first paragraph, phrase "original53 plus". For ten distinct predecessor bodies, the unchanged formula10+unique+2*rows gives40; for the fifteen distinct selected bodies it gives55. The source formula is correct and this review independently verifies55 using actual body-derived Git OIDs. This is a prospective denominator, not an observed operation outcome. Preserve the frozen author report and append an explicit correction; do not edit historical receipts or claim an actual55-operation run. Root has specified that a separate erratum will correct the prose.

## Limits and pending authority

No substantive defect was found in the bounded four-edit successor scope. Source acceptance does not certify every inherited behavior under arbitrary mutation, hard real-time scheduling, a continuous aggregate quota, physical encrypted wire volume, or whole research capacity. The authenticated source fixes the15-body selection and preserves literal controls; a genuine fresh installed selection/Main commit, one-use caller/release, external execution outcome and independently verified final recovered bytes are still required. No current remote receipt or acceptance-shaped substitute was generated.

The previously withheld flat02 terminal-currentness finding remains outstanding for its separate flat03 correction/review; this remote-source acceptance cannot waive it. Likewise old385 Git, nine new opaque Git bodies, failed171 recovery, source-policy/recovery proof, final Parent/caller/gate supplement and actual runtime package recovery remain separate composition requirements. Original failed identities stay spent. Historical missing path/component and discarded earlier attempt errors remain unknown. Financial timing, returns/cashflow conventions, fee/funding treatment, exposure reuse and numerical/scientific outcomes were not tested. No additional reasoning effort is needed for this bounded source decision; actual external evidence is needed for any recovery claim.
'''
(D/'REPORT01.md').write_text(report)
put('REVIEW_ACCEPTANCE01.json',{'schema_version':1,'decision':'ACCEPTED_SOURCE_ONLY_COMPLETE15_REMOTE_SUCCESSOR','source_sha256':H((D/'recover01.py').read_bytes()),'author_manifest_sha256':H((D/'AUTHOR_MANIFEST01.json').read_bytes()),'watch_sha256':H((D/'watch01.py').read_bytes()),'different_author_watch_review_sha256':H((D/'WATCH_REVIEW_MACHINE01.json').read_bytes()),'different_author_watch_manifest_sha256':H((D/'WATCH_REVIEW_MANIFEST01.json').read_bytes()),'selected_readback_sha256':H((D/'SELECTED_READBACK01.json').read_bytes()),'report_sha256':H((D/'REPORT01.md').read_bytes()),'actual_root_selection':None,'actual_entry_release':None,'actual_external_recovery':None,'actual_observed_operations':None,'prospective_expected_operations':55,'scope':'Four exact edits and concrete complete15 body selection; unchanged source/process controls; accepted peer watcher dependency. No entry or numerical authority.'})
put('MACHINE01.json',{'schema_version':1,'decision':'ACCEPTED_SOURCE_ONLY_COMPLETE15_REMOTE_SUCCESSOR','source_sha256':H((D/'recover01.py').read_bytes()),'author_manifest_sha256':H((D/'AUTHOR_MANIFEST01.json').read_bytes()),'author_machine_sha256':H((D/'AUTHOR_MACHINE01.json').read_bytes()),'author_authenticated_members':20,'peer_watch_authenticated_members':70,'independent_checks':428,'exact_four_edit_literal_inverse':True,'all_other_ast_unchanged':True,'selected_count':15,'selected_bytes':507946,'unique_actual_body_derived_git_oids':15,'prospective_expected_operations':55,'actual_observed_operations':None,'scope_typed_members':[41,42],'scope_regular_bodies':[33,31],'failed_original_members_including_root':43,'different_author_watch_acceptance_sha256':H((D/'WATCH_REVIEW_MACHINE01.json').read_bytes()),'independent_watch_self_review':False,'watch_role':'Genuine different-author acceptance authenticated; exact pinned dependency only','documentation_finding':'D1 original53 prose incorrect; original10distinct implies40, new15distinct implies55; frozen report retained; no actual count claimed','actual_root_selection':None,'actual_entry_release':None,'actual_external_recovery':None,'actual_flat_recovery':None,'native':None,'claim':None,'report_sha256':H((D/'REPORT01.md').read_bytes()),'acceptance_sha256':H((D/'REVIEW_ACCEPTANCE01.json').read_bytes())})
rows=[]
for base,dirs,files in os.walk(D,followlinks=False):
 for n in sorted(dirs+files):
  p=Path(base)/n
  if p==D/'MANIFEST01.json':continue
  s=p.lstat();r={'path':str(p.relative_to(D)),'mode':stat.S_IMODE(s.st_mode)}
  if stat.S_ISREG(s.st_mode):r.update(kind='file',bytes=s.st_size,sha256=H(p.read_bytes()),nlink=s.st_nlink)
  elif stat.S_ISDIR(s.st_mode):r['kind']='directory'
  else:raise AssertionError(p)
  rows.append(r)
put('MANIFEST01.json',{'schema_version':1,'root_mode':stat.S_IMODE(D.stat().st_mode),'members':sorted(rows,key=lambda r:r['path'])})
print(json.dumps({n:H((D/n).read_bytes()) for n in ['MANIFEST01.json','MACHINE01.json','REPORT01.md','REVIEW_ACCEPTANCE01.json']}));print(json.dumps({'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'bytes':sum(r.get('bytes',0) for r in rows)}))
