import ast,copy,hashlib,json,stat
from pathlib import Path
H=Path(__file__).resolve().parent;sha=lambda b:hashlib.sha256(b).hexdigest()
def put(n,v):(H/n).write_text(json.dumps(v,indent=2,sort_keys=True,allow_nan=False)+'\n')
r=json.loads((H/'READBACK01.json').read_text());p=json.loads((H/'PARENT_INPUT_REQUIREMENTS01.json').read_text());q=json.loads((H/'NEXT_PHASE_REQUIREMENTS01.json').read_text());ph=json.loads((H/'PHASES18_CURRENT01.json').read_text());api=json.loads((H/'SOURCE_API_MAP01.json').read_text());rows=p['rows'];additional=[x for x in rows if x.get('alias_existing_role') is None];assert len(rows)==10 and len(additional)==9
q2=copy.deepcopy(q);q2['expected_input_count_rule']='8 base roles +2 descriptors +9 additional parent metadata/member roles (10 concrete paths less parent_job alias execution_job) +4 reference metadata roles +N reference checkpoint member roles =23+N. If actual reference manifest has exactly one member,24 roles. Root must compute actual count from full registered map and keep every original checkpoint member; no hardcoded8.';q2['supersedes_count_only']={'path':'NEXT_PHASE_REQUIREMENTS01.json','sha256':sha((H/'NEXT_PHASE_REQUIREMENTS01.json').read_bytes()),'correction':'Initial documentary count undercounted one parent role; actual enumerated10-row parent evidence map was correct.'};put('NEXT_PHASE_REQUIREMENTS02.json',q2)
independent=[x for x in ph if x['currently_registered'] and x['slot'] not in (1,2) and not x['original_dependencies']];assert len(independent)==8
put('INDEPENDENT_PREPARATION_OPTIONS01.json',{'scope':'metadata preparation only; does not reorder original phase execution or grant native parallelism','original_next_in_order':'financial-wrapper-classification-eager-continue100-20261003-01','then_original_predict':'financial-wrapper-classification-eager-predict-20261003-01','first_later_dependency_free_declared':'financial-wrapper-classification-selected-agreement-20261003-01','remaining_dependency_free_initial_entries':independent,'required_refresh_each':['exact actual current/source map instead of stale289 pins','current f4ea source closure instead of olde13 closure','actual same-root job disk/storage paths','carry exact adopted dfed/3268 extension19','new actual current=design commit and unchanged194 method/config/runtime proof','own new exact caller/recovery/release if later selected'],'ready_numerical_entries':[],'after_reference_accepted_recovered':'prepare new original continuation entry13 with complete real dependency hashes, descriptors and source/caller proofs; no API/method/cap amendment required on source evidence','reference_outcome_not_assumed':True})
put('MACHINE01.json',{'schema_version':1,'status':'BOUNDED_SOURCE_HISTORY_INVESTIGATION_NOT_ADMISSION','author':'combined_worker_review','observation':r['at_utc'],'current_source':r['source'],'gate_sha256':r['gate_sha256'],'registered_identities':12,'actual_spent':2,'highest_actual_allowance':19,'remaining':17,'base_attempt_budget':18,'prior_attempts':0,'original_total_phase_slots':18,'completed_reference_at_observation':False,'next_original_identity':q['original_continuation_plan']['experiment'],'next_original_identity_registered':False,'next_original_cell':q['original_continuation_plan']['cell_id'],'next_original_parent':q['continuation_parent'],'required_reference_identity':q['reference_identity'],'new_gate_entries_if_only_child_added':13,'parent_evidence_original_paths':10,'distinct_additional_parent_roles_if_job_alias_reused':9,'continuation_input_count':'23 plus actual reference checkpoint member count;24 only if one member','new_reference_or_continuation_claim':None,'future_source_design_gate_caller_recovery':None,'conditional_after_reference_claim_spent':3,'conditional_after_reference_claim_remaining':16,'conditional_scope':'budget arithmetic only, success must separately be authenticated; any unexpected failure halts dependent releases','new_budget_extension_needed_for_original_schedule':False,'admission_does_not_verify_every_input_body_preclaim':True,'ResearchRun_check_inputs_runs_after_exclusive_claim':True,'ready_launches':0,'source_checks':r['checks'],'no_numerical_checkpoint_decode_or_handle_construction':True,'paper_fit_credit':0,'paper_fits_pending':1420,'documentary_count_erratum_retained':'NEXT_PHASE_REQUIREMENTS02.json supersedes count sentence in01 only; raw10-row census unchanged'})
report='''# Following the complete100 reference: exact original next phase

At the timestamp in READBACK01, Source9dc5/gate752c has12 registered identities, both original FAILED claims only, spent2/highest19/17 remaining. The reference has no claim or terminal. No completed100 outcome is asserted. The original charter still requires18 phases:14COMPLETE+4plannedFAILED,8 complete100 fits,12 fit invocations,800training+4agreement updates,10cells and16replay copies. All1420 paper fits remain pending.

The next frozen phase is slot3, `financial-wrapper-classification-eager-continue100-20261003-01`, same original continued cell `financial-wrapper-classification-eager-continued-20261003-01`. It is currently unregistered. Its original plan is retained literally from generated03/PHASES01: continue100/classification/eager/prior_input=prior/reference_input=uninterrupted_reference. The experiment parent must be the actual plannedFAILED claimedrun identity d390/4b2, not the original reserved predispatch ID or unexpected recordfix failure. This is a new distinct claim; the failed identity stays permanently terminal and cannot be resumed, replayed or refunded.

Parent evidence is concrete: PARENT_INPUT_REQUIREMENTS01 lists ten exact original paths/hashes/sizes for claim, FAILED terminal, selected job/plan, fresh fit claim, failed-fit terminal, interrupted diagnostic, schedule, checkpoint manifest and opaque state.pt493424/223ced42. The manifestb2f7 and actual diagnostic retain historical source0a2 and absolute paths. The state bytes were only hashed, never decoded. There is exactly one prior failed fit directory under the continued cell; the original training engine refuses a second prior fit or unreviewed chain. The actual parent job matches the existing execution_job role exactly and can be referenced by that role without duplicating it. The required prior descriptor includes completion_input, but the continue100 branch does not read a completion: leave it explicitly null, never invent a COMPLETE body.

The independent reference is the exact original `financial-wrapper-classification-eager-complete100-20261003-01` on its different reference cell. Before the dependent registration is finalized, Root must have its actual COMPLETE claim/terminal, fit complete.json declaring100, actual checkpoint manifest/provenance and every member, plus complete external/fresh recovery and independent acceptance. Those values remain null here. The dependency descriptor has exactly checkpoint_input/provenance/completion_input/claim_input/terminal_input; all members must additionally be input roles. Expected role count is23 plus the number of actual reference checkpoint members, if the identical parent job reuses execution_job. It is24 only if the reference actually has one member. The first documentary count sentence incorrectly subtracted two rather than one parent role; it remains preserved in01 and is explicitly corrected by NEXT_PHASE_REQUIREMENTS02. The actual ten-path census was correct.

Root can prepare the metadata mechanically without changing the scientific implementation: retain all12 current entries exactly; add only original continuation as entry13 with genuine parent; create original child plan and the two precise dependency descriptors; bind every raw evidence input to its original local path/hash/dataset; reuse seven common source/input roles and original extensiondfed/review3268. Freeze a new current=design source and exact actual tracked source map, excluding only the gate. If only these three JSON bodies become new tracked sources, the tree would be342/pins341; this is conditional arithmetic, not a fixed future closure assertion. Raw outcome inputs do not have to be silently copied into scientific source: the generic API accepts explicit local input hash descriptors, while source_files authenticates the actual committed implementation/auxiliary map. Every input still needs actual preservation and hash/currentness checks. No new budget amendment or API relaxation is indicated for the remaining original phases.

A material pre-release boundary: admission.py validates input descriptor syntax and resolves hashes, but does not read every input body. ResearchRun.start writes its exclusive claim before _check_inputs; missing evidence can therefore spend a trial. Wrapper parent/reference semantic checks also occur inside execute after claim. ReadyTrue alone is insufficient: Root's independent pre-release source/metadata check must join every prerequisite body, exact parent registration, terminal, schedule/provenance and absolute origin before any new launch. The genuine guarded loader must still verify actual parent epoch1/batch0 and exact epoch0 log, actual reference100/0, then perform the original remaining99 updates and compare final model/Adam/RNG/logs exactly. This investigation cannot provide that tensor-level proof.

Source anchors and exact function/line/AST hashes are in SOURCE_API_MAP01. Relevant branches are wrapper _parent/_interrupt_parent/_reference_state/execute; training _reserve/fit_cell; admission.admit parent equality/repeat/saturation/input rules; lifecycle.start/_check_inputs; and job._admitted/_command. Parent equality requires the old parent's entire experiment definition remain unchanged in the new gate. The CLI supplies no design-source or bindings option; wrapper authorize requires current=design and no bindings. A new source commit at the same physical root can retain the old source_commit in parent provenance because scientific comparison excludes that field only. A relocated root would invalidate existing absolute diagnostic/failed-fit paths unless separately reviewed; it cannot be silently substituted.

After a reference claim, arithmetic becomes spent3/remaining16 whether it succeeds or fails. Continuation eligibility additionally requires its accepted COMPLETE result; an unexpected failure stops releases. After actual continued COMPLETE and its full recovery, original slot4 `financial-wrapper-classification-eager-predict-20261003-01` uses that completed parent, zero updates and saved-model replay. It is also currently unregistered. Prediction cannot substitute for the99-update continuation or full100 completion.

Eight later dependency-free initial entries can be prepared as metadata independently; the first in the frozen order is classification-selected-agreement. Their current entries still have289source pins/no extension and old job/closure roles, so none is a ready launch. INDEPENDENT_PREPARATION_OPTIONS01 names all eight and their exact refresh requirements. This does not select a reordered experiment or authorize parallel native work. The original eight dependent registrations remain withheld until actual prerequisite results exist.

Every eventual phase needs a new identity-specific external Parent/request matching its actual source, expanded input cardinality, original protocol and strict whole-root watches; existing complete100 Parent7f28 is fixed to another identity/eight roles and cannot be reused. Preserve/recover the new source, entire caller/review scope and all actual dependency outcomes, then obtain exact release and fresh native measurements. Keep modelCONFIG20f451/trainingd527, seed11/full16batch/28lookback/448distinct synthetic graphs/all trainable gradients, original100epoch schedule and exact/F32 tolerances unchanged. No array, label, numerical package, genuine handle, admission, claim, network or live file mutation was used; no financial performance or whole100/full-population capacity claim follows.
'''
(H/'REPORT01.md').write_text(report)
rows=[]
for f in sorted(H.rglob('*')):
 s=f.lstat();row={'path':str(f.relative_to(H)),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):row['kind']='directory'
 elif stat.S_ISREG(s.st_mode):b=f.read_bytes();assert len(b)<=4194304;row.update(kind='file',bytes=len(b),sha256=sha(b))
 else:raise AssertionError('unexpected type')
 rows.append(row)
put('MANIFEST01.json',{'schema_version':1,'self_excluded':'MANIFEST01.json','scope':'complete focused next-phase source/history investigation and retained documentary count erratum','members':rows,'counts':{'members':len(rows),'files':sum(x['kind']=='file' for x in rows),'logical_bytes':sum(x.get('bytes',0) for x in rows)}})
for row in rows:
 f=H/row['path'];assert stat.S_IMODE(f.stat().st_mode)==row['mode']
 if row['kind']=='file':assert sha(f.read_bytes())==row['sha256']
print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'report':sha((H/'REPORT01.md').read_bytes()),'members':len(rows),'files':sum(x['kind']=='file' for x in rows),'bytes':sum(x.get('bytes',0) for x in rows)}))
