"""Bounded source/history/opaque byte census. No project imports or admission."""
import ast,copy,hashlib,json,os,stat,subprocess,datetime
from pathlib import Path
H=Path(__file__).resolve().parent;B=H.parent;C=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,n):assert v,n;checks.append(n)
def read(p):
 s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_size<=4194304 and p.resolve()==p,'bounded canonical '+str(p));b=p.read_bytes();t=p.lstat();ck((s.st_dev,s.st_ino,s.st_mode,s.st_size,s.st_mtime_ns,s.st_ctime_ns)==(t.st_dev,t.st_ino,t.st_mode,t.st_size,t.st_mtime_ns,t.st_ctime_ns),'stable '+str(p));return b
def put(n,v):(H/n).write_text(json.dumps(v,indent=2,sort_keys=True,allow_nan=False)+'\n')
graw=read(C/'fixture_inputs/financial_wrapper_claimedrun01/gates.json');ck(sha(graw)=='752c34dfad4df2ca36b5dc4dcb999846f8de01bd1a61c5356092c4e55fbd678c','current actual gate');g=json.loads(graw);source=subprocess.run(['git','-C',str(C),'rev-parse','HEAD'],capture_output=True,text=True,check=True,timeout=10).stdout.strip();ck(source=='9dc5c79f738920b52947b4e63fed0397f1b5b207','current actual source');(H/'CURRENT_GATE01.json').write_bytes(graw)
REF='financial-wrapper-classification-eager-complete100-20261003-01';PARENT='financial-wrapper-classification-eager-interrupt1-claimedrun-20261004-01';CHILD='financial-wrapper-classification-eager-continue100-20261003-01';PREDICT='financial-wrapper-classification-eager-predict-20261003-01';ex=g['experiments'][REF];ck(len(g['experiments'])==12 and CHILD not in g['experiments'] and PREDICT not in g['experiments'],'current12 excludes original next dependents')
charterraw=read(C/ex['charter']['path']);ck(sha(charterraw)==ex['charter']['sha256']=='041ab6260eeb81805202ba31c4ba1710b3109bbd0b24131e83a5c4f05984cbb1','original18 charter');charter=json.loads(charterraw);(H/'ORIGINAL_CHARTER02.json').write_bytes(charterraw)
orig=B/'financial-genuine-wrapper-registration-preparation01-2026-10-04/generated03/PHASES01.json';pr=read(orig);(H/'ORIGINAL_PHASE_TEMPLATES01.json').write_bytes(pr);ph=json.loads(pr);plans={r['proposed_plan']['experiment']:r['proposed_plan'] for r in ph['slots']};plan=plans[CHILD];ck(len(ph['slots'])==18 and len(ph['withheld_dependent_registrations'])==8,'all18 original slots/eight deferred dependents');ck(plan['phase']=='continue100' and plan['cell_id']=='financial-wrapper-classification-eager-continued-20261003-01' and plan['prior_input']=='prior' and plan['reference_input']=='uninterrupted_reference','exact frozen continuation plan')
(H/'source').mkdir();apis=[]
for name in ['tradingagents/research/onchain_replication/'+s for s in ('financial_wrapper_fixture.py','training.py','job.py','checkpoints.py','financial_execution.py')]+['tradingagents/research/'+s for s in ('admission.py','lifecycle.py','verify.py','budget_extensions.py')]:
 b=read(C/name);ck(sha(b)==ex['source_files'][name],'actual source pin '+name);(H/'source'/name.replace('/','__')).write_bytes(b);tree=ast.parse(b);apis.append({'path':name,'sha256':sha(b),'definitions':[{'name':n.name,'line':n.lineno,'ast_sha256':sha(ast.dump(n,include_attributes=False).encode())} for n in tree.body if isinstance(n,(ast.ClassDef,ast.FunctionDef))]})
# Exact actual failed parent metadata, preserving original root locations; no state decoding.
claimraw=read(C/'research_runs'/PARENT/'claim.json');parentclaim=json.loads(claimraw);failraw=read(C/'research_runs'/PARENT/'failed.json');ck(sha(claimraw)=='d390980c956aab64d5521698cbb6123ccf01ece94a95277b97755f019adf692b' and sha(failraw)=='4b2d7b0d162e80fe2074997baed35f2d6e6c86e5f660872fc2b8e97bb9622558','actual planned failed parent');ck(parentclaim['experiment']==g['experiments'][PARENT],'parent experiment must remain exact in future gate')
jobref=parentclaim['inputs']['execution_job'];parentjob=json.loads(read(C/jobref['path']));parentplanref=parentclaim['inputs'][parentjob['payload']['plan_input']];parentplanraw=read(C/parentplanref['path']);parentplan=json.loads(parentplanraw);ck(sha(parentplanraw)==parentplanref['sha256'],'actual claim-selected interrupt plan');ck(jobref==ex['inputs']['execution_job'],'parent job role can reuse current execution_job input exactly')
diagpath=C/'research_artifacts/financial_wrapper_engineering'/PARENT/'interrupted-checkpoint.json';diagraw=read(diagpath);diag=json.loads(diagraw);cp=Path(diag['checkpoint']);cpraw=read(cp);cpmeta=json.loads(cpraw);ck(sha(cpraw)==diag['sha256']=='b2f7d33b2f2280f5d9b0a9731ea320c64d18768bda772926421ddb0af2e12c70','actual checkpoint manifest');fit=cp.parents[2];ck(fit.name==PARENT and cpmeta['provenance']==diag['provenance'] and cpmeta['provenance']['source_commit']=='0a2e7639b42b9423b90743feadcda4078aa21816','historical checkpoint provenance unchanged');ck([p.name for p in fit.parent.iterdir()]==[PARENT] and not (fit/'complete.json').exists(),'exact one prior failed fit; no chain')
parent_paths={'claim_input':C/'research_runs'/PARENT/'claim.json','terminal_input':C/'research_runs'/PARENT/'failed.json','parent_job_input':C/jobref['path'],'parent_plan_input':C/parentplanref['path'],'fit_claim_input':fit/'claim.json','failed_fit_input':fit/'failed.json','diagnostic_input':diagpath,'schedule_input':fit/'schedule.json','checkpoint_input':cp};parentrows=[]
for role,p in parent_paths.items():
 b=read(p);parentrows.append({'descriptor_field':role,'path':str(p.relative_to(C)),'bytes':len(b),'sha256':sha(b),'kind':'original metadata JSON','alias_existing_role':'execution_job' if role=='parent_job_input' else None})
for name,ref in cpmeta['members'].items():
 ck(Path(name).name==name,'checkpoint member lexical');p=cp.parent/name;b=read(p);ck(len(b)==ref['size'] and sha(b)==ref['sha256'],'opaque checkpoint body pin only');parentrows.append({'descriptor_field':'checkpoint_member:'+name,'path':str(p.relative_to(C)),'bytes':len(b),'sha256':sha(b),'kind':'opaque checkpoint binary NOT decoded'})
for name,b in [('PARENT_CLAIM01.json',claimraw),('PARENT_FAILED01.json',failraw),('PARENT_PLAN01.json',parentplanraw),('PARENT_CHECKPOINT_MANIFEST01.json',cpraw),('PARENT_DIAGNOSTIC01.json',diagraw)]: (H/name).write_bytes(b)
# Only actual pure metadata plan/task/cell validator isolated from genuine source.
fw=ast.parse(read(C/'tradingagents/research/onchain_replication/financial_wrapper_fixture.py'));ns={'PHASES':('agreement','interrupt1','complete100','continue100','predict')};names={'Unavailable','require','validate_plan','_interrupt_case'};exec(compile(ast.Module(body=[n for n in fw.body if isinstance(n,(ast.ClassDef,ast.FunctionDef)) and n.name in names],type_ignores=[]),'actual_metadata_case','exec'),ns);ns['validate_plan'](plan);ns['_interrupt_case'](plan,parentplan,PARENT);checks.append('actual frozen continuation/actual parent phase-cell match')
for field,value in [('cell_id','different-cell'),('task','regression'),('execution','selected')]:
 v=copy.deepcopy(plan);v[field]=value
 try:ns['_interrupt_case'](v,parentplan,PARENT)
 except ValueError:checks.append('wrong continuation '+field+' refused')
 else:raise AssertionError('case accepted')
claims=[]
for p in sorted((C/'research_runs').glob('*/claim.json')):
 b=read(p);v=json.loads(b);t=read(p.parent/'failed.json');claims.append({'identity':p.parent.name,'claim_sha256':sha(b),'failed_sha256':sha(t),'allowance':v['effective_attempt_budget']});ck(not (p.parent/'complete.json').exists(),'actual claims both failed')
ck(len(claims)==2 and max(v['allowance'] for v in claims)==19 and g['families'][ex['family']]['attempt_budget']==18 and g['families'][ex['family']]['prior_attempts']==0,'actual occupancy2 highest19 base18prior0')
for who in (REF,CHILD,PREDICT):ck(not os.path.lexists(C/'research_runs'/who),'actual unclaimed '+who)
phases=[]
for row in charter['phases']:
 ident=row['proposed_identity'];e=g['experiments'].get(ident);p=plans[ident];entry={'slot':row['slot_index'],'identity':ident,'logical_key':row['logical_key_not_identity'],'cell':row['proposed_cell'],'phase':p['phase'],'original_dependencies':row['proposed_dependencies'],'currently_registered':e is not None,'current_source_pin_count':None if e is None else len(e['source_files']),'current_extension19':False if e is None else e.get('cumulative_budget_extension')==ex['cumulative_budget_extension'],'actual_status':None,'ready_to_launch':False}
 if row['slot_index']==1:entry.update(actual_fulfillment=PARENT,actual_status='plannedFAILED_checkpoint_opaque_accepted',original_identity='permanently reserved predispatch failure, no claim')
 if ident==CHILD:entry['required_actual_dependencies']=[PARENT,REF]
 phases.append(entry)
put('SOURCE_API_MAP01.json',apis);put('PHASES18_CURRENT01.json',phases);put('PARENT_INPUT_REQUIREMENTS01.json',{'actual_root':str(C),'actual_parent':PARENT,'rows':parentrows,'prior_descriptor_not_created':True,'parent_provenance':cpmeta['provenance'],'completion_input_for_failed_parent':'field is required in prior descriptor but not read in continue100 route; use explicit null, never fabricate a completion','checkpoint_members':len(cpmeta['members']),'body_currentness':'opaque hashes only; real loader cursor/log/model/optimizer/RNG validation still pending'})
put('NEXT_PHASE_REQUIREMENTS01.json',{'status':'PROSPECTIVE_NOT_REGISTERED_NOT_RELEASED','original_continuation_plan':plan,'original_prediction_plan':plans[PREDICT],'continuation_parent':PARENT,'reference_identity':REF,'reference_claim':None,'reference_COMPLETE_terminal':None,'reference_fit_complete100':None,'reference_checkpoint_manifest':None,'reference_checkpoint_members':None,'reference_provenance':None,'new_gate_entry':None,'new_source':None,'new_design_source':None,'new_Parent_request':None,'new_recovery_release':None,'prospective_gate_entry_count_if_only_child_added':13,'minimum_new_fixed_JSON_roles':['wrapper_plan','prior','uninterrupted_reference'],'existing_common_roles_reused':['environment','execution_job','model','runtime_mapping','source_closure','synthetic_recipe','training'],'raw_outcome_inputs':'existing exact local parent/reference paths may remain untracked inputs: generic admission resolves explicit SHA descriptors; do not silently commit/rewrite artifacts or require a different-source API','source_map_rule':'include every actually adopted tracked implementation/auxiliary JSON excluding self gate; actual resulting count must be recomputed. Three new tracked JSONs alone would mean342 tree/341 pins, conditional not a promised final count. Original194 implementation closure stays exact.','expected_input_count_rule':'8 base roles+2 descriptors+8 unique additional parent role/body paths if execution_job is reused+4 reference metadata paths+every reference checkpoint member. With one reference member this is23; count must be computed from exact final role map, not hardcoded8.','readiness':'complete100 accepted and fully externally/fresh recovered before child launch; no outcome assumed','conditional_occupancy_after_reference_claim':'3 spent/highest19/16 remaining regardless success; child availability additionally requires COMPLETE100, unexpected failure stops releases','prediction_after_continuation':'new original predict ID requires genuine continued COMPLETE,fit100,replay/checkpoint+members and its full recovery; zero updates'})
put('READBACK01.json',{'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source':source,'gate_sha256':sha(graw),'current_registered_identities':list(g['experiments']),'actual_claims':claims,'actual_spent':2,'highest_actual_allowance':19,'remaining':17,'reference_unclaimed_at_observation':True,'checks':len(checks),'check_names':checks,'no_numerical_import_admission_run_or_owner':True,'checkpoint_decoded':False,'original_phase_metadata_sha256':sha(pr),'future_outcome_null':True})
print(json.dumps({'checks':len(checks),'phase':CHILD,'registered':False,'spent':2,'remaining':17,'parent_roles_and_members':len(parentrows)}))
