from pathlib import Path
import hashlib,json,os,stat,shutil
P=Path(__file__).absolute().parent;A=P.parent/'financial-wrapper-compatibility-preclaim-source01-2026-10-04'
def sha(b):return hashlib.sha256(b).hexdigest()
def put(n,v):(P/n).write_text(json.dumps(v,sort_keys=True,indent=2)+'\n')
for n in ['FREEZE01.out','FREEZE01.err']:shutil.copyfile(A/n,P/('AUTHOR_'+n))
source=sha((P/'CANDIDATE_preclaim01.py').read_bytes());w=sha((P/'WITNESS01.json').read_bytes());readback=json.loads((P/'READBACK01.json').read_bytes());history=json.loads((P/'HISTORICAL_READBACK01.json').read_bytes())
negative=P/'owned01/over-cap-negative'
put('MACHINE01.json',{'schema_version':1,'decision':'WITHHELD_PRECLAIM_CURRENTNESS_PC1','candidate_sha256':source,'author_manifest_sha256':sha((A/'MANIFEST01.json').read_bytes()),'author_sealed_typed_members':40,'author_additional_declared_freeze_logs':2,'independent_passing_checks':readback['checks']+history['count'],'actual_genuine_historical_verify_claim':True,'public_Admission_Run_Owner_constructed':False,'public_preclaim_success_tested':False,'future_recovery_COMPLETE_fabricated':False,'finding':{'id':'PC1','function':'Reader.finish / Reader._physical cleanup','lines':[106,115],'witness_sha256':w,'witness_returned_success_after_current_bytes_changed':True,'impact':'Earlier registered/policy/source bytes can become stale inside later owned cleanup before preclaim return. Downstream post-start checks may then fail after a claim is spent. No invalid scientific outcome was executed.'},'scoped_passes':['actual195 source pins/191 unchanged historical bodies grounded in fixed policy','exact real review proof/machine/report/manifest joins','actual historical FAILED claim/fit/schedule/checkpoint opaque state joins','all tested descriptor cleanup first-fatal/secondary retention','missing/future COMPLETE and recovery refusals','source-only bounds and genuine class guard'], 'limits':{'source195_bytes':2062446,'source195_double_read_bytes':4124892,'own_reader_total':8388608,'own_file':4194304,'sampled_deadline_seconds':120,'original_verify_claim_outside_counter':True,'whole_parent_capacity_unproved':True},'negative_control':{'path':'owned01/over-cap-negative','bytes':negative.stat().st_size,'allocated_bytes':negative.stat().st_blocks*512,'sha256':sha(negative.read_bytes()),'deliberately_nonadmitted':True,'retain_original_sparse_file':True},'prior_failures_retained':['INSPECTION_FAILURE01.json','CHECK01.err (review harness initially omitted author declared FREEZE log exclusions)'],'no_source_or_gate_edits':True,'no_numerical_or_native_execution':True,'no_release':True})
(P/'REPORT01.md').write_text('''# Independent preclaim source review

WITHHELD_PC1 against exact source24b6c2a51759bf992fb0da479f46ba6d582b0e24f1c5c40c5055a34f859de71e. No live source, registration, claim or Parent was changed.

**PC1 — Reader.finish(), lines112–115; _physical cleanup106–111.** The final loop rehashes each cached path in order. Later owned descriptor cleanup can change an earlier path after its last byte comparison. The independent real-FD witness closes the later file descriptor, rewrites the earlier file from `original` to `changed!`, explicitly advances its mtime, then returns normally. Reader.finish succeeds while its earlier cached bytes differ from current bytes. This occurred inside owned cleanup before return; it is not a claim about arbitrary post-return races, continuous immutability or metadata ABA. No fake Admission/Run, future outcome or recovery authority was constructed. The later numerical worker still checks input hashes, but it can do so after Run.start has spent the claim: avoiding that missing/stale prerequisite failure is this helper's purpose.

Required correction: add a finite final whole-reader path/type/inode/mode/signature rejoin after every measurement descriptor cleanup, tied to each verified byte sample. It must reject this explicit later-close mutation, preserve all prior first-fatal/secondary evidence and caps, and describe only sampled currentness. An identical unbounded rescan loop or a claim of continuous exclusion would not resolve the stated contract. Preserve source01 and the exact witness; review a separately named successor.

350 independent passing source/metadata/refusal checks accompany the finding. Complete author40-member sealed scope authenticated; its two explicitly excluded freeze logs were separately hashed/copied. Every current195 implementation body was rehashed. The actual fixed independent policy proof/machine/report/manifest joins passed through the candidate reader. Actual original FAILED history passed through genuine read-only verify_claim and the candidate _historical validator; original d390/4b2/b2f7/223ced42 hashes remain unchanged and checkpoint bytes were never decoded. Wrong parent/plan/provenance, fabricated completion aliases, absent genuine COMPLETE dependencies, bad hashes and missing recovery refused. Six independent real two-descriptor primary/secondary matrices retained all exception objects and closed all descriptors, supplementing rather than recounting the author's24 cases. Source AST retains exact genuine Admission guard, no public construction or start, no numerical load and strict fixed phase/policy/provenance relationships.

Root-authenticated external references and genuine independent authorship remain essential: the helper's recovery machine/typed-manifest/body joins authenticate supplied evidence, not authorship or a remote event by themselves. Actual final Parent/recovery references remain NULL here. No full public preclaim success, COMPLETE100 reference, COMPLETE continuation or prediction was manufactured or tested. Original verify_claim's own Git/source transport is outside this helper's8MiB reader counter and sampled120-second checks. The current195 body reads alone require2,062,446 bytes, or4,124,892 including final rehash. Actual final caller/registration/proof/recovery and checkpoint bundles must be measured against remaining reader capacity; no whole-caller resource or numerical capacity is established.

The initial independent harness failed because it did not apply the author's declared FREEZE log exclusions; CHECK01.err and progress are retained, corrected CHECK02 passed. The exact sparse4MiB+1 file owned01/over-cap-negative is a deliberately refused, nonadmitted negative control with zero allocated data blocks. It remains a real original file and must not be omitted from future complete preservation or relabeled as within the4MiB admitted file limit. No original evidence was deleted or rewritten. Final source acceptance, caller integration, actual recovery, cumulative budget and numerical release remain withheld/separate.
''')
rows=[]
def walk(p,rel=''):
 for q in sorted(p.iterdir(),key=lambda q:q.name):
  n=q.name if not rel else rel+'/'+q.name
  if n=='MANIFEST01.json':continue
  s=q.lstat();r={'path':n,'mode':stat.S_IMODE(s.st_mode)}
  if stat.S_ISLNK(s.st_mode):r.update(kind='symlink',target=os.readlink(q));rows.append(r)
  elif stat.S_ISDIR(s.st_mode):r.update(kind='directory');rows.append(r);walk(q,n)
  else:r.update(kind='file',bytes=s.st_size,sha256=sha(q.read_bytes()));rows.append(r)
walk(P);rows.sort(key=lambda r:r['path']);put('MANIFEST01.json',{'schema_version':1,'scope':'complete independent review and every raw failure/control; excludes only this self seal','members':rows,'typed_members':len(rows),'regular_files':sum(r['kind']=='file' for r in rows),'regular_bytes':sum(r.get('bytes',0) for r in rows),'nonadmitted_over_file_cap':['owned01/over-cap-negative']})
print(json.dumps({n:sha((P/n).read_bytes()) for n in ['MANIFEST01.json','MACHINE01.json','REPORT01.md','WITNESS01.json']}));print('members',len(rows))
