from pathlib import Path
import json,hashlib,ast
R=Path('/home/malecada/master_thesis/TradingAgents-audit-fixes');F=R/'research/onchain-paper-replication-2026-09-24/full_sources';D=F/'financial-wrapper-compatibility-operational-delta-tooling01-2026-10-04';D.mkdir(mode=0o700);OLD=F/'financial-wrapper-complete100-failed-root-remote03-2026-10-04';CAP=F/'financial-wrapper-compatibility-operational-delta-capture02-2026-10-04';V=F/'financial-wrapper-compatibility-concrete-policy-review01-2026-10-04'
def h(b):return hashlib.sha256(b).hexdigest()
names=[CAP/n for n in ['CAPTURE01.json','PAYLOAD_MANIFEST01.json','operational-delta01.tar.gz','ORIGIN_MAP01.json','root_delta_capture05.py']]+[V/n for n in ['MANIFEST01.json','MACHINE01.json','REPORT01.md','REVIEW_PROOF01.json','READBACK01.json']]
assert all(p.is_file() for p in names)
required={p.relative_to(R).as_posix():{'bytes':p.stat().st_size,'sha256':h(p.read_bytes())} for p in sorted(names)}
raw=(OLD/'recover01.py').read_text();tree=ast.parse(raw);node=next(x for x in tree.body if isinstance(x,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='REQUIRED' for t in x.targets));lines=raw.splitlines(True);lines[node.lineno-1:node.end_lineno]=['REQUIRED = '+repr(required)+'\n'];new=''.join(lines);new=new.replace('fresh-complete100-failed-outcome02-02.git','fresh-operational-source-policy01.git').replace('fresh-actual-remote-complete100-failed-outcome02-supervised-recovered','fresh-actual-remote-operational-source-policy01-supervised-recovered').replace('Exact corrected failed-outcome02 and retained withheld-capture01 bytes recovered. Historical native attempt remains FAILED/spent; remote retrieval starts no claim. Baseline385 Git remains separate.','Exact frozen operational source/policy delta and genuine independent policy review bytes recovered. Original failed histories remain spent; no claim is started. Old385 actual recovered Git plus nine new bodies form an explicitly checked394-object source basis; final registration/caller/runtime-body recovery remain separate.')
(D/'recover01.py').write_text(new);(D/'watch01.py').write_bytes((OLD/'watch01.py').read_bytes());U=D/'utilities';U.mkdir(mode=0o700)
for n in ['recovery_pax01.py','owned_io.py','bounded_git01.py']:(U/n).write_bytes((OLD/'utilities'/n).read_bytes())
(D/'REQUIRED_BODIES01.json').write_text(json.dumps(required,sort_keys=True,indent=2)+'\n')
# Scope-only edits. Preserve every original function except the changed receipt-context literals in main.
a=ast.parse(raw);b=ast.parse(new);equal=[x.name for x in a.body if isinstance(x,ast.FunctionDef) and x.name!='main' and ast.dump(x,include_attributes=False)==ast.dump(next(y for y in b.body if isinstance(y,ast.FunctionDef) and y.name==x.name),include_attributes=False)];assert len(equal)==len([x for x in a.body if isinstance(x,ast.FunctionDef)])-1
(D/'SOURCE_SCOPE_INVERSE01.json').write_text(json.dumps({'schema_version':1,'original_source_sha256':h(raw.encode()),'new_source_sha256':h(new.encode()),'changes':['fixed REQUIRED literal10bodies','new fresh Git namespace','new actual receipt status','honest operational scope qualification'],'all_other_functions_unchanged':equal,'all_resource_and_cleanup_controls_unchanged':True,'native_or_NUM_authority':None},indent=2)+'\n')
print(len(required),sum(x['bytes'] for x in required.values()))
