from pathlib import Path
import hashlib,json,resource,os,signal
resource.setrlimit(resource.RLIMIT_AS,(256*1024**2,)*2);resource.setrlimit(resource.RLIMIT_FSIZE,(4*1024**2,)*2);os.sched_setaffinity(0,{3,4});os.nice(10);signal.alarm(30)
H=Path(__file__).resolve().parent;F=H.parent;P=F/'mcm-batched-driver03-2026-10-09';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();cells=[60105600,72495392,65558720,60001376,50606112,50616352,56584576];batches=[(n+4095)//4096 for n in cells];body=lambda v:(json.dumps(v,sort_keys=True,separators=(',',':'),allow_nan=False)+'\n').encode();logical=0
for n in cells:
 for start in range(0,n,4096):
  stop=min(start+4096,n);size=92+53*(stop-start);pending=body({'schema':3,'kind':'engineering_pending','start':start,'stop':stop,'workload_sha256':'0'*64,'disposition':'attempted_unknown_without_complete'});meta=body({'schema':3,'kind':'engineering_complete','pending_sha256':'0'*64,'payload_sha256':'0'*64,'payload_bytes':size,'record_bytes':53,'purposes_sha256':'0'*64});logical+=size+len(pending)+len(meta)
lines=(P/'driver.py').read_text().splitlines(True);out=[];pos=0
for part in (P/'inverse.patch').read_text().split('@@ ')[1:]:
 if not part.startswith('-'):continue
 hdr,tail=part.split(' @@',1);start=int(hdr.split()[0][1:].split(',')[0])-1;out+=lines[pos:start];pos=start
 for line in tail.splitlines(True)[1:]:
  if line.startswith(' '):assert lines[pos]==line[1:];out.append(line[1:]);pos+=1
  elif line.startswith('-'):assert lines[pos]==line[1:];pos+=1
  elif line.startswith('+'):out.append(line[1:])
out+=lines[pos:];assert ''.join(out)==(F/'mcm-batched-driver02-2026-10-09/driver.py').read_text()
x={'decision':'accepted-source-only-with-ledger-correction','driver_sha256':sha(P/'driver.py'),'journal_sha256':sha(F/'mcm-batched-execution03-2026-10-09/batch_journal.py'),'executor_sha256':sha(F/'mcm-batched-execution03-2026-10-09/pair_executor.py'),'evidence':{n:sha(H/n) for n in ['RESULT01.json','STREAM02.json','driver01.py','stream02.py']},'checks':['exact_driver_inverse','unchanged_tasks_batch_AST','unchanged8accepted02_IO_primitives','latest_payload_root_and_earlier_batch_corruption_refused','actual64node_motif_tasks_across48batch','single_local_lifetime_exact_bounded_f32','sink_primary_generator_index_journal_cleanup','token_cap_before_work','10stream_cases_short_extra_misorder_priorpurpose_workload_closemutation_pending_root_header'],'arithmetic':{'batch_cells':4096,'per_graph_batches':batches,'batch_count':sum(batches),'retained_files':3*sum(batches),'record_bytes':53,'header_bytes':92,'conditional_logical_journal_bytes':logical,'fixed_token_payload_bytes':sum(batches)*168,'max_token_cap':64*1024**2,'additional_logical_sweeps':6,'additional_logical_read_bytes':logical*6},'correction':'Author101555batch/304665file ledger rounded total across graph boundaries. Actual driver resets each graph:101559batches/304677files. Original failed101555 assertion preserved. Source correctness accepted; original ledger quantity not accepted.','qualification':'Reuses accepted02 numeric12advance5checkpoint evidence; routing deterministic callbacks are not numerical equality.168B/batch fixed token payload excludes Python headers,bounded reader/parsed records/runtime. Historical confirmed_post_sink counters do not certify currentness after later mutation; final rejoin refuses success, sink effects cannot roll back. All files must remain local through final join:offload/retirement blocker. Exact conditional ledger excludesfilesystem/outputs/checkpoints/scratch/physicalIO; six additional logical sweeps are costs, no speedup. Exclusive ownership/frozen numeric runtime assumptions; no hostile concurrency proof. Source-only, not genuine authority, installation, capacity, benchmark, empirical permission or launch. Prior withholdings unchanged.'}
(H/'SOURCE_REVIEW01.json').write_text(json.dumps(x,indent=2)+'\n');print(json.dumps({'sha256':sha(H/'SOURCE_REVIEW01.json'),'arithmetic':x['arithmetic']}))
