import gzip,hashlib,io,json,os,stat,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;D=F/'financial-genuine-wrapper-root-claimedrun-final-capture01-2026-10-04';V=F/'financial-genuine-wrapper-claimedrun-final-capture-review01-2026-10-04';sys.path.insert(0,str(F/'held-consumer-final-recovery-preparation04-2026-10-03'));import recovery04 as R
sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):assert v,m;checks.append(m)
def read(p):return R.read(p.parent,p.name)
ck(sha(read(D/'capture01.py'))=='1c74338bb78018c8816933c23b850090ef29ebce503ef7420d716e1f2a374749','actual accepted original failedhelper');ck(sha(read(V/'MANIFEST01.json'))=='b5a6b4cb3576b469ae1c9614d47865c255c5604390f0c2c9922726feab046bbc','prior source-only review immutable');m=json.loads(read(D/'union-manifest.json'));mapping=json.loads(read(D/'union-bytes01/ORIGINAL_TREES01.json'));ck(R.scan(D/'union-bytes01')==m,'complete actual copied prepackunion');ck(len(m['members'])==1476 and sum(r['kind']=='file' for r in m['members'])==1186,'full1476typed1186regular');wanted={'ORIGINAL_TREES01.json'};totals={'files':0,'links':0,'bytes':0,'members':0};prior=json.loads(read(V/'ACTUAL_ORIGINAL_SCOPES01.json'));priorby={t['scope']:t for t in prior};ck(len(mapping['scope_trees'])==len(prior)==20,'exact20 originalroots')
for tr in mapping['scope_trees']:
 root=Path(tr['original_root']);ck(root.resolve()==root and root==Path(priorby[tr['scope']]['original_root']),'exactoriginalroot');seen={'.'}|{p.relative_to(root).as_posix() for p in root.rglob('*')};ck(seen=={r['path'] for r in tr['members']},'entireactual currentoriginal membership');normalized=[]
 for r in tr['members']:
  p=root/r['path'];s=p.lstat();ck(stat.S_IMODE(s.st_mode)==r['mode'],'every original literal mode');norm={k:v for k,v in r.items() if k!='union_path'};normalized.append(norm);totals['members']+=1
  if r['kind']=='file':
   b=read(p);ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and len(b)==r['bytes'] and sha(b)==r['sha256'],'every original currentopaque body');ck(read(D/'union-bytes01'/r['union_path'])==b,'every actualcopied opaque body');wanted.add(r['union_path']);totals['files']+=1;totals['bytes']+=len(b)
  elif r['kind']=='lexical-symlink':ck(stat.S_ISLNK(s.st_mode) and os.readlink(p)==r['target'],'every literal originaltarget');ck(not os.path.lexists(D/'union-bytes01'/tr['scope']/r['path']),'no literal linkinstantiation');totals['links']+=1
  else:ck(stat.S_ISDIR(s.st_mode),'original directorytype')
 ck(normalized==priorby[tr['scope']]['members'],'entire originalscope unchanged since sourcereview')
ck(totals['files']==1185 and totals['links']==50 and totals['bytes']==18864635,'whole20scope actualdenominators');ck({r['path'] for r in m['members'] if r['kind']=='file'}==wanted,'no missing/extra copied body');ck(max(r.get('bytes',0) for r in m['members'])==575475,'no individualbody capoverflow')
partial=read(D/'union.tar.gz');ck(len(partial)==4190463 and len(partial)<R.FILE,'exact retainedpartialextent withinunchangedcap');inflated=0;failure=None
try:
 with gzip.GzipFile(fileobj=io.BytesIO(partial),mode='rb') as z:
  while True:
   chunk=z.read(65536)
   if not chunk:break
   inflated+=len(chunk);ck(inflated<=192*1024**2,'bounded incompletegzip diagnostic')
except (EOFError,OSError) as e:failure={'type':type(e).__name__,'message':str(e),'inflated_prefix_bytes_observed':inflated}
ck(failure is not None,'actualpartial gzip has no validcompletedfooter');ck(not os.path.lexists(D/'UNION_AUTHENTICATION01.json'),'actual authentication neverwritten');err=read(D/'ACTUAL_CAPTURE01.err');out=read(D/'ACTUAL_CAPTURE01.out');ck(out==b'','original emptyout');text=err.decode();ck(text.count('ValueError: archive exceeds4MiB; retain failed attempt')==2 and 'ExceptionGroup: body/cleanup failures (2 sub-exceptions)' in text and text.rstrip().endswith('owned_io.CleanupFailure: score storage cleanup unresolved; worker must stop'),'original body+gzipcloseValueErrors+CleanupFailure retained');(O/'ORIGINAL_ACTUAL_CAPTURE01.err').write_bytes(err);(O/'ORIGINAL_ACTUAL_CAPTURE01.out').write_bytes(out)
S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');sm=json.loads(read(F/'financial-genuine-wrapper-root-claimedrun-source339-capture01-2026-10-04/source-manifest.json'));R.same(S,sm);P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-root-launch-20261004-01');ck(sha(read(P/'REQUEST_FINAL03.json'))=='529c9bf3c587e6160a217e8eb339882e59433b6fc0f759d0009d261f872b2bd8' and not os.path.lexists(P/'attempt'),'originalParent unchanged/nonativeattempt');ck({p.name for p in (S/'research_runs').iterdir()}=={'financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01','.lock'},'no freshclaim');ck(R.scan(D/'union-bytes01')==m,'whole retainedcopy stableatend');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','tradingagents'} for n in sys.modules),'no research/numerical import')
x={'schema_version':1,'decision':'VERIFIED_ORIGINAL_FINAL_CAPTURE_FAILED_INCOMPLETE_ARCHIVE_NO_UNION_ACCEPTANCE','helper_sha256':sha(read(D/'capture01.py')),'original_source_review_manifest_sha256':'b5a6b4cb3576b469ae1c9614d47865c255c5604390f0c2c9922726feab046bbc','checks':len(checks),'prepack_manifest_sha256':sha(read(D/'union-manifest.json')),'copied_typed_members':1476,'copied_regular_members':1186,'original20scope':totals,'partial_archive_sha256':sha(partial),'partial_archive_bytes':len(partial),'incomplete_gzip_diagnostic':failure,'original_stderr_sha256':sha(err),'original_stdout_sha256':sha(out),'original_body_error':'ValueError: archive exceeds4MiB; retain failed attempt','original_cleanup_error':'ValueError: archive exceeds4MiB; retain failed attempt','original_surface_error':'owned_io.CleanupFailure','authentication_absent':True,'reported_actual_tool':{'session':62650,'start':'dcf485','completion':'133355','exit':1,'provenance':'Root report; separate persisted terminal pending'},'original_pid':None,'original_start_ticks':None,'original_process_group':None,'original_process_history_unavailable':True,'Source339_unchanged':True,'Parent_unchanged_no_attempt':True,'new_claims':0,'partial_archive_complete_or_recoverable_final_union':False,'numerical_or_capacity_authority':False,'disposition':'Permanently preserve closed original failed namespace; no rerun. A separately reviewed successor must retain unchanged body/archive caps and all original failures.'};(O/'READBACK01.json').write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');print(json.dumps({'checks':len(checks),'partial':sha(partial),'failure':failure}))
