"""Genuine exact single metadata receiver release after dependency closure."""
from pathlib import Path
import importlib.util,json,os,sys
H=Path(__file__).resolve().parent;F=H.parent;MAIN=F.parents[2]
spec=importlib.util.spec_from_file_location('accepted_bounded_reader',F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05/verify_capture01.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);Reader,R=m.Reader,m.R
rd=Reader();sr=rd.read(H/'REMOTE_SOURCE_READBACK01.json');source=json.loads(sr);D=Path(source['root'])
for n,h in [('recover01.py',source['receiver_sha256']),('watch01.py',source['watch_sha256']),('SELECTED_BODIES01.json',source['selection_sha256']),('SOURCE_BINDING01.json',source['source_binding_sha256']),('utilities/owned_io.py','09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb')]:rd.read(D/n,h)
confirm=F/'heartbeat-root-checkpoint10-2026-10-04/REMOTE_CONFIRMATION63.json';confraw=rd.read(confirm,'9cca77c571a4c476820d15d9b07e7fa96f8622f3fd377f3f2876b32e7209befa');conf=json.loads(confraw);rd.need(conf['actual_main_commit']==conf['actual_remote_head']==source['commit'] and conf['push']['exit_code']==conf['actual_readback']['exit_code']==0,'actual genuine pushed/readback commit')
for row in json.loads(rd.read(D/'SELECTED_BODIES01.json'))['rows']:rd.read(MAIN/row['path'],row['sha256'])
for n in ('fresh-refused-continuation-outcome01.git','selected','REMOTE_RECOVERY01.json','FAILED01.json'):rd.need(not os.path.lexists(D/n),'fresh exact output '+n)
wspec=importlib.util.spec_from_file_location('fixed_accepted_watch',D/'watch01.py');W=importlib.util.module_from_spec(wspec);wspec.loader.exec_module(W);sample=W.census(D)
rd.need(W.POLICY=={'logical':67108864,'allocated':100663296,'members':32768,'depth':32,'file':4194304,'sample_seconds':5,'floor':10737418240,'samples':8192},'unchanged exact accepted whole-tree limits');rd.finish()
release={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_REFUSAL_OUTCOME_REMOTE','owned_root':str(D),'cwd':str(MAIN),'commit':source['commit'],'receiver_sha256':source['receiver_sha256'],'watch_sha256':source['watch_sha256'],'owned_io_sha256':'09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb','selection_sha256':source['selection_sha256'],'source_binding_sha256':source['source_binding_sha256'],'argv':[str(MAIN/'.venv/bin/python'),'-B',str(D/'recover01.py'),'--selection-sha256',source['selection_sha256']],'expected_operations':34,'selected_count':8,'selected_bytes':267420,'receiver_seconds':600,'Git_operation_seconds':60,'per_child_FSIZE_bytes':4194304,'whole_tree_policy':W.POLICY,'numerical_authority':False,'restore_entry_released':False,'relaunch_consumed_financial_identity':False,'actual_remote_confirmation':{'path':str(confirm),'sha256':R.digest(confraw)},'source_review':{'path':str(H/'REMOTE_SOURCE_READBACK01.json'),'sha256':R.digest(sr)}}
R.put(H/'REMOTE_ENTRY_RELEASE01.json',release);readback={'schema_version':1,'decision':release['decision'],'release_sha256':R.digest(R.encode(release)),'source_review':release['source_review'],'exact_dependency_gap_resolved':True,'prior_gap_retained':'REMOTE_ENTRY_GAP01.json','five_original_and_dependency_bodies_authenticated':True,'fresh_output_namespaces':True,'actual_receiver_baseline':sample,'actual_entry_executed_by_reviewer':False,'checks':rd.checks,'read_bytes':rd.total};R.put(H/'REMOTE_ENTRY_READBACK01.json',readback);print(json.dumps({'release_sha256':readback['release_sha256'],'readback_sha256':R.digest(R.encode(readback)),'checks':rd.checks}))
