"""Exact fixed once-only flat entry; no restore invocation by reviewer."""
from pathlib import Path
import ast,importlib.util,json,os,shutil
H=Path(__file__).resolve().parent;F=H.parent;MAIN=F.parents[2];C=F/'heartbeat-root-checkpoint10-2026-10-04';D=F/'financial-wrapper-continuation-refused-outcome-remote01-2026-10-05';OUT=F/'financial-wrapper-continuation-refused-outcome-flat01-2026-10-05';P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-continue100-canonical-plan-root-launch-20261005-01')
spec=importlib.util.spec_from_file_location('accepted_bounded_reader',F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05/verify_capture01.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);Reader,R=m.Reader,m.R
rd=Reader();old=rd.read(C/'CANONICAL_CONTINUATION_REFUSAL_FLAT01.py','67e28bb5c8ab3ad6b9324f0fe095f12ae1309dfc730ba3a827f971df5bd9beaa');new=rd.read(C/'CANONICAL_CONTINUATION_REFUSAL_FLAT02.py','b1a64ac74a44e195cef215ffacd929c5d399c6d53215d4e429319ae57af25c37');extra="(OUT/'flat').mkdir(mode=0o700)\n";rd.need(new.decode().count(extra)==1 and new.decode().replace(extra,'',1).encode()==old,'complete exact single mkdir inverse');rd.need(ast.dump(ast.parse(new.decode().replace(extra,'',1)),include_attributes=False)==ast.dump(ast.parse(old),include_attributes=False),'allotherAST unchanged')
readback=json.loads(rd.read(H/'REMOTE_OUTCOME_READBACK01.json'));rr=rd.read(D/'REMOTE_RECOVERY01.json',readback['remote_receipt_sha256']);receipt=json.loads(rr);rd.read(D/'ACTUAL_ROOT_EXIT01.json',readback['actual_Root_exit_sha256']);rd.tree(D/'selected',readback['selected_mode_manifest'])
q=json.loads(rd.read(P/'REQUEST_FINAL01.json','a9a04d60abced0ae01f192a7fc3897bf3972891d374a98f33f15522b8dc20e18'))
helperpins={n:q['helper_hashes'][n] for n in ('recovery04.py','owned_io.py','bounded_git01.py')}
for n,h in helperpins.items():rd.read(P/n,h)
pre='research/onchain-paper-replication-2026-09-24/full_sources/financial-wrapper-continuation-refused-outcome-capture01-2026-10-05/'
rows={r['path']:r for r in receipt['selected_blobs']};inputs={}
for n in ('increment.tar.gz','archive-manifest.json','CAPTURE01.json'):
 p=D/'selected'/(pre+n);raw=rd.read(p,rows[pre+n]['sha256']);rd.need(len(raw)==rows[pre+n]['bytes'],'actual restoreinput bound');inputs[n]={'path':str(p),'sha256':R.digest(raw)}
cap=json.loads(rd.read(Path(inputs['CAPTURE01.json']['path'])));man=json.loads(rd.read(Path(inputs['archive-manifest.json']['path'])));R.validate(man);rd.need(cap['archive']['sha256']==inputs['increment.tar.gz']['sha256'] and cap['archive']['manifest_sha256']==inputs['archive-manifest.json']['sha256'] and len(man['members'])==cap['regular']==55 and cap['new_original_bodies']==54 and cap['complete_current_CAP_regular']==832 and cap['complete_current_CAP_typed']==1060,'complete actual fixed restorepopulation')
rd.need(not os.path.lexists(OUT) and shutil.disk_usage(F).free>=10737418240,'fresh exact flatnamespace and10GiB floor');rd.finish()
finding={'schema_version':1,'status':'ORIGINAL_UNEXECUTED_FLAT_SOURCE_WITHHELD_CORRECTED','original_sha256':R.digest(old),'original_location':'CANONICAL_CONTINUATION_REFUSAL_FLAT01.py:28','primitive_location':'recovery04.py:143','cause':'FlatOutput.begin requires existing private output; original creates OUT but not OUT/flat','impact':'FileNotFoundError after reserving OUT; no actual invocation occurred','correction':'exact one-line explicit private0700 flat-directory creation; all other source/AST unchanged','corrected_sha256':R.digest(new)};R.put(H/'FLAT_SOURCE_FINDING01.json',finding)
release={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_REFUSAL_OUTCOME_FLAT','source_path':str(C/'CANONICAL_CONTINUATION_REFUSAL_FLAT02.py'),'source_sha256':R.digest(new),'cwd':str(MAIN),'argv':[str(MAIN/'.venv/bin/python'),'-B',str(C/'CANONICAL_CONTINUATION_REFUSAL_FLAT02.py')],'owned_output_root':str(OUT),'helper_root':str(P),'helper_pins':helperpins,'receiver_receipt_sha256':R.digest(rr),'actual_receiver_Root_exit_sha256':readback['actual_Root_exit_sha256'],'inputs':inputs,'archive_bodies':55,'original_bodies':54,'disk_floor_bytes':10737418240,'per_file_bytes':4194304,'POSIX_reconstruction':False,'runtime_body_recovery':False,'numerical_authority':False,'namespace_reuse_authority':False,'future_final_outcome_review_required':True};R.put(H/'FLAT_ENTRY_RELEASE01.json',release);result={'schema_version':1,'decision':release['decision'],'release_sha256':R.digest(R.encode(release)),'source_sha256':R.digest(new),'full_single_line_literal_AST_inverse':True,'actual_remote_readback_sha256':R.digest(rd.read(H/'REMOTE_OUTCOME_READBACK01.json')),'original_finding':'FLAT_SOURCE_FINDING01.json','actual_restore_executed_by_reviewer':False,'checks':rd.checks,'read_bytes':rd.total};rd.finish();R.put(H/'FLAT_ENTRY_READBACK01.json',result);print(json.dumps({'release_sha256':result['release_sha256'],'readback_sha256':R.digest(R.encode(result)),'checks':rd.checks}))
