"""Final consolidated actual refusal disposition and external BYTE recovery seal."""
from pathlib import Path
import importlib.util,json
H=Path(__file__).resolve().parent;F=H.parent
spec=importlib.util.spec_from_file_location('accepted_bounded_reader',F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05/verify_capture01.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);R=m.R
r=json.loads(R.read(H,'FINAL_RECOVERY_READBACK01.json'))
def ref(n):return {'path':str(H/n),'sha256':R.digest(R.read(H,n))}
report='''# Consolidated continuation refusal and recovery review

The actual launch is accepted as terminal not_admitted, followed by complete fresh byte recovery of its changed evidence. It is not a completed continuation. resources.py:523–529 refused before publishing the workload release because available memory6,437,638,144 bytes fell4,812,800 bytes below the fixed6,442,450,944-byte startup requirement. Actual Root and supervisor exit1, native launcher125/signal-before-release and workload_pid null are preserved. Original Parent and guard child-exit nulls remain unknown. The lifecycle claim, fit, wrapper and guard release namespaces are absent. No99 resumed updates, comparison, final checkpoint, new financial claim or paper-fit credit occurred. The prior one COMPLETE/three FAILED/four spent/highest20 accounting is reused unchanged; this consumed launch namespace cannot be reopened or relaunched by this review.

Recorded cleanup authenticates all seven recorded PIDs, four groups and absent stopped cgroup. Native process history remains explicitly incomplete. Registered3GiB memory high=max/swap0,4MiB files,two-CPU affinity,10GiB disk floor and sampled resource controls were retained. The user-space CPU quota controller remains unavailable; observed affinity is the supported control. No memory threshold, scope or budget was relaxed.

Actual local capture and fresh remote/flat recovery independently cover54 original bodies750,566 bytes: Parent28 regular/32 typed entries, native job9 regular/10 typed, immutable outcome phase14 files and3 actual Root evidence files. The55-entry archive includes COMPOSITION; all236,548 compressed bytes, frames, canonical PAX encoding, modes, original mappings and hashes match. Parent30 in an initial Root message was a prose error; original manifests always recorded28. The actual receiver returned all eight selected bodies267,420 bytes from committed bd3ca812746142c1998e4494335bd11cba975b91 in34 successful reaped Git operations. Its distinct Root exit is zero; recorded Git PIDs/groups are absent. Physical encrypted wire bytes and universal process history remain unknown.

Two concrete entry issues were caught before invocation. Installed watch01.py:5–8 initially lacked its required utilities/owned_io.py; Root installed the unchanged pinned dependency while preserving the four original bodies. Original unexecuted CANONICAL_CONTINUATION_REFUSAL_FLAT01.py:28 passed a missing OUT/flat to the accepted FlatOutput.begin, which requires an existing private directory. The separately preserved02 adds exactly one private0700 mkdir; full literal/AST inverse and actual inputs were verified. No buggy original entry ran. Actual released02 completed once with Root0; all55 restored opaque bodies plus metadata match all54 original files and the composition. The initial reviewer Root-receipt key error and its correction remain retained as a harness error.

The complete current CAP is832 regular/1060 typed entries, formed from accepted823/1049 plus exact9/11 additions. Current source d4c81c0961342bfe4c5771aabbef1d46a14cffb8 and422 logical Git objects remain unchanged. Prior823 byte hashes and251 runtime evidence were reused explicitly, without rescans. Genuine accepted prior current recovery4bb778 anchors the composition. Later review/recovery authority is additive outside the immutable outcome phase; no recursive self-archive is claimed.

Acceptance is BYTE preservation with sampled currentness. It excludes POSIX reconstruction, installed runtime package body recovery, continuous writer exclusion, whole capacity, and external recovery of later receiver/flat utility implementations that were only locally bound. No numerical retry, namespace reuse, Owner/Run creation, policy amendment or additional claim is authorized. This reviewer ran no numerical imports/checkpoint decode, public launcher, network operation or restoration. Economic returns, timing leakage, exposure reuse, fees/funding and scientific numerical agreement were not tested because no workload was admitted.
'''
with (H/'REPORT01.md').open('x') as f:f.write(report)
machine={'schema_version':1,'decision':'ACCEPTED_TERMINAL_NOT_ADMITTED_AND_COMPLETE_CHANGED_BYTE_RECOVERY','reviewer':'/root/storage_watch_review','source':r['source'],'identity':r['identity'],'outcome_phase':ref('OUTCOME_PHASE_MANIFEST01.json'),'outcome_proof':ref('OUTCOME_PHASE_PROOF01.json'),'capture_readback':ref('CAPTURE_READBACK01.json'),'remote_entry':ref('REMOTE_ENTRY_RELEASE01.json'),'remote_outcome':ref('REMOTE_OUTCOME_READBACK01.json'),'flat_entry':ref('FLAT_ENTRY_RELEASE01.json'),'final_recovery':ref('FINAL_RECOVERY_READBACK01.json'),'report':ref('REPORT01.md'),'prior_current_recovery':r['prior_current_recovery'],'current_CAP_regular':832,'current_CAP_typed':1060,'Git_logical_objects':422,'old823_body_hashes_reused_not_reread':True,'runtime251_evidence_reused':True,'original_bodies_recovered':54,'archive_bodies':55,'remote_selected_bodies':8,'remote_successful_reaped_Git_operations':34,'new_lifecycle_claims':0,'resumed_updates':0,'paper_fit_credit':0,'namespace_reserved':True,'relaunch_authorized':False,'original_financial_Parent_exit':None,'universal_native_process_history':None,'POSIX_reconstruction':False,'installed_runtime_body_recovery':False,'whole_capacity':False,'continuous_writer_exclusion':False,'numerical_authority':False}
R.put(H/'MACHINE01.json',machine)
proof={'schema_version':1,'kind':'complete_continuation_refusal_byte_recovery','decision':'accepted-actual-terminal-not-admitted-evidence-byte-recovery','source':r['source'],'identity':r['identity'],'review':ref('MACHINE01.json'),'prior_current_recovery':r['prior_current_recovery'],'actual_remote_receipt_sha256':r['actual_remote_receipt_sha256'],'actual_flat_receipt_sha256':r['actual_flat_receipt_sha256'],'actual_flat_Root_exit':r['actual_flat_Root_exit'],'scope':{'original_new_bodies':54,'archive_bodies':55,'current_CAP_regular':832,'current_CAP_typed':1060,'Git_logical_objects':422,'Parent_regular':28,'job_regular':9,'outcome_phase_regular':14,'Root_evidence_regular':3},'lifecycle_claim_created':False,'numerical_updates':0,'namespace_reserved':True,'namespace_reuse_authorized':False,'numerical_authority':False,'excludes':['POSIX-reconstruction','installed-runtime-bodies','whole-capacity','continuous-writer-exclusion','universal-process-history','later-bound-transport-utility-external-recovery']};R.put(H/'FULL_REFUSAL_RECOVERY_PROOF01.json',proof)
manifest=R.scan(H);manifest['self_excluded']='MANIFEST01.json';manifest['scope']='Complete consolidated actual continuation refusal, recorded cleanup, local capture, exact metadata entries and actual remote/flat byte recovery; immutable outcome phase remains unchanged.';R.put(H/'MANIFEST01.json',manifest)
print(json.dumps({n:ref(n) for n in ('MACHINE01.json','REPORT01.md','FULL_REFUSAL_RECOVERY_PROOF01.json','MANIFEST01.json')}))
