"""Actual new refusal flat bytes plus explicitly reused accepted current basis."""
from pathlib import Path
import importlib.util,json,os,shutil,subprocess
H=Path(__file__).resolve().parent;F=H.parent;D=F/'financial-wrapper-continuation-refused-outcome-flat01-2026-10-05';REMOTE=F/'financial-wrapper-continuation-refused-outcome-remote01-2026-10-05'
spec=importlib.util.spec_from_file_location('accepted_bounded_reader',F/'financial-wrapper-compatibility-complete100-recovery-review01-2026-10-05/verify_capture01.py');m=importlib.util.module_from_spec(spec);spec.loader.exec_module(m);Reader,R=m.Reader,m.R
rd=Reader();entry=json.loads(rd.read(H/'FLAT_ENTRY_RELEASE01.json','7c93b8555a18a94516a3b95976b97152361b42b9bf289b599a54c4981f24e219'));rd.read(Path(entry['source_path']),entry['source_sha256']);inputs={n:rd.read(Path(v['path']),v['sha256']) for n,v in entry['inputs'].items()};capture=json.loads(inputs['CAPTURE01.json']);manifest=json.loads(inputs['archive-manifest.json']);rr=rd.read(D/'RECOVERY01.json','b66a28dfc8a6fe0bb372920a379c1ded7ebea6174a7487cc4e2a9c0791734a8f');receipt=json.loads(rr)
rd.need(receipt['receiver_receipt_sha256']==entry['receiver_receipt_sha256'] and receipt['capture_sha256']==R.digest(inputs['CAPTURE01.json']) and receipt['archive_sha256']==R.digest(inputs['increment.tar.gz']) and receipt['manifest_sha256']==R.digest(inputs['archive-manifest.json']) and receipt['new_original_bodies']==54 and receipt['accepted_old_basis_reused'] and not receipt['POSIX_reconstruction'] and not receipt['runtime_bodies_recovered'] and not receipt['paper_fit_or_namespace_reuse_authority'],'actual exact receiver/capture/flat receipt joins')
primitive=receipt['primitive'];flat=D/'flat';meta_raw=rd.read(flat/primitive['metadata_file'],primitive['metadata_sha256']);meta=json.loads(meta_raw);mapping=meta['flat_members'];expected={r['path']:r for r in manifest['members']};rd.need(meta['manifest']==manifest and meta['archive']==capture['archive'] and len(mapping)==primitive['regular_bodies']==primitive['members']==55 and set(mapping)==set(expected) and len(set(mapping.values()))==55,'actual entire55body typed archive metadata')
fm={'schema_version':1,'root_mode':448,'members':sorted([{'path':mapping[n],'kind':'file','mode':384,'bytes':row['bytes'],'sha256':row['sha256']} for n,row in expected.items()]+[{'path':primitive['metadata_file'],'kind':'file','mode':384,'bytes':len(meta_raw),'sha256':R.digest(meta_raw)}],key=lambda r:r['path'])};rd.tree(flat,fm);bodies={n:rd.read(flat/mapping[n],row['sha256']) for n,row in expected.items()}
it=R.framed_members(inputs['increment.tar.gz']);seen=set();primary=None
try:
 for n,t,b in it:
  rd.need(n in expected and n not in seen and t.isfile() and t.mode==expected[n]['mode']==384 and t.size==len(b)==expected[n]['bytes'] and b==bodies[n],'every external PAX/restored byte');seen.add(n)
except BaseException as e:primary=e
R._cleanup((it.close,),primary=primary)
if primary is not None:raise primary
rd.need(seen==set(expected),'complete55restored denominator');comp=json.loads(bodies['COMPOSITION01.json']);prior_capture=json.loads(rd.read(H/'CAPTURE_READBACK01.json','b3600dbacba6a5fc1cfb26d7ce743644e53f6a8d0edcbdd0dbfd1b0ac2d5f746'));rd.need(R.digest(bodies['COMPOSITION01.json'])==prior_capture['composition_sha256'],'actual original composition externally recovered')
origins={};material=comp['materialized']
for label,scope in comp['scopes'].items():
 root=Path(scope['root']);sm=scope['manifest']
 if label!='outcome-phase':rd.tree(root,sm)
 else:
  phase=json.loads(rd.read(root/'OUTCOME_PHASE_MANIFEST01.json','ff83b37edd3dc9c0253209210559b9d51022a88065b1119bdab50f3cad05b510'));rd.need([r for r in sm['members'] if r['path']!='OUTCOME_PHASE_MANIFEST01.json']==phase['members'],'immutable recovered phase, later review files excluded')
 for row in sm['members']:
  if row['kind']=='file':origins[label+'/'+row['path']]=root/row['path']
for n in material:
 if n.startswith('Root/'):origins[n]=F/'heartbeat-root-checkpoint10-2026-10-04'/n[5:]
rd.need(set(origins)==set(material) and len(material)==54,'complete original54scope')
for n,p in origins.items():
 row=material[n];b=bodies[row['flat']];rd.need(len(b)==row['bytes'] and R.digest(b)==row['sha256'] and rd.read(p,row['sha256'])==b,'all54external original joins')
basis=json.loads(rd.read(Path(comp['basis']['path']),comp['basis']['sha256']));rd.read(Path(basis['review']['path']),basis['review']['sha256']);rd.need(comp['basis']['sha256']=='4bb7781345617bf5529e63b0c2d0a630aad726df87c3dc895ab4e02ca323aa79' and comp['Git_logical_objects']==422 and comp['old823_capsule_bodies_not_reread'] and comp['old_runtime251_not_reread'],'exact accepted old-byte/runtime evidence reuse')
CAP=Path(basis['capsule_root']);rd.tree(CAP,comp['capsule'],('.git',));head=rd.read(CAP/'.git/HEAD').decode().strip();source=rd.read(CAP/'.git'/head[5:]).decode().strip() if head.startswith('ref: ') else head;rd.need(source==comp['source']==basis['source'],'unchanged currentsource')
outcome=json.loads(rd.read(H/'OUTCOME_READBACK01.json'));rd.need(all(not os.path.lexists(p) for p in outcome['absent_namespaces']),'no claim/fit/workload release since refusal')
rootref=json.loads(rd.read(H/'ACTUAL_FLAT_ROOT_EXIT_REF01.json'));actual_raw=rd.read(Path(rootref['path']),rootref['sha256']);actual=json.loads(actual_raw)
# Exact actual Root receipt schema is supplied after the one real restoration.
rd.need(actual['actual_root_exit_code']==0 and actual['actual_root_session'] is None and actual['actual_root_tool_chunk']=='0eb97a' and actual['actual_recovery_receipt_sha256']==R.digest(rr) and actual['source02_sha256']==entry['source_sha256'],'genuine separate flat Root exit0/source/receipt; no invented session')
out=rd.read(Path(actual['stdout']['path']),actual['stdout']['sha256']);err=rd.read(Path(actual['stderr']['path']));v=json.loads(out);rd.need(err==b'' and v['recovery_sha256']==R.digest(rr) and v['regular_bodies']==55 and v['new_original_bodies']==54,'actual final Root streams')
rd.need({p.name for p in D.iterdir()}=={'flat','RECOVERY01.json','ACTUAL_ROOT_EXIT01.json'},'whole actual flat root membership')
paths=[D,flat]+list(flat.iterdir())+[D/'RECOVERY01.json',D/'ACTUAL_ROOT_EXIT01.json'];logical=sum(p.lstat().st_size for p in paths if p.is_file());allocated=sum(p.lstat().st_blocks*512 for p in paths);rd.need(logical<=67108864 and allocated<=100663296 and len(paths)<=32768 and shutil.disk_usage(D).free>=10737418240,'actual final whole output bounds/floor')
previous=json.loads(rd.read(F/'financial-wrapper-continuation-current-preservation-preparation01-2026-10-05/CURRENT_COMPOSITION02.json','65ee768ba3a6569b125920bbc61f01d64487a90a5ced608df31b505cd008f370'));delta=json.loads(rd.read(F/'financial-wrapper-continuation-canonical-delta-root01-2026-10-05/snapshot/COMPOSITION01.json'));expectedgit=set(previous['git']['current416'])|{v['oid'] for v in delta['Git']['new_objects']};proc=subprocess.run(['git','--no-optional-locks','-C',str(CAP),'rev-list','--objects',source],capture_output=True,check=True,timeout=10);rd.need(not proc.stderr and len(proc.stdout)<1048576 and {x.split()[0] for x in proc.stdout.decode().splitlines()}==expectedgit and len(expectedgit)==422,'actual unchanged422 Git closure metadata')
rd.finish();result={'schema_version':1,'decision':'ACCEPTED_ACTUAL_COMPLETE_REFUSAL_BYTE_RECOVERY','source':source,'identity':comp['identity'],'actual_flat_receipt_sha256':R.digest(rr),'actual_flat_Root_exit':rootref,'actual_remote_receipt_sha256':entry['receiver_receipt_sha256'],'actual_remote_Root_exit_sha256':entry['actual_receiver_Root_exit_sha256'],'archive_sha256':R.digest(inputs['increment.tar.gz']),'archive_manifest_sha256':R.digest(inputs['archive-manifest.json']),'capture_sha256':R.digest(inputs['CAPTURE01.json']),'composition_sha256':R.digest(bodies['COMPOSITION01.json']),'original_bodies':54,'archive_bodies':55,'physical_flat_bodies_including_metadata':56,'original_Parent_regular':28,'original_job_regular':9,'original_outcome_phase_regular':14,'original_Root_evidence_regular':3,'current_CAP_regular':832,'current_CAP_typed':1060,'Git_basis_unchanged':422,'prior_current_recovery':comp['basis'],'old823_body_hashes_reused_not_reread':True,'runtime251_evidence_reused':True,'terminal_disposition':'not_admitted; reserved namespace; no relaunch','new_lifecycle_claims':0,'resumed_updates':0,'paper_fit_credit':0,'original_financial_Parent_exit':None,'native_history_complete':False,'POSIX_reconstruction':False,'runtime_bodies_recovered':False,'whole_capacity':False,'continuous_writer_exclusion':False,'bound_transport_utilities_externally_recovered':False,'numerical_or_relaunch_authority':False,'checks':rd.checks,'read_bytes':rd.total};R.put(H/'FINAL_RECOVERY_READBACK01.json',result);print(json.dumps({'decision':result['decision'],'readback_sha256':R.digest(R.encode(result)),'checks':rd.checks}))
