from pathlib import Path
import difflib,json,hashlib
H=Path(__file__).resolve().parent;S=Path('tradingagents/research/onchain_replication')
changes={}
def patch(name,edits):
 a=(S/name).read_text();b=a
 for old,new in edits:
  assert old in b,(name,old);b=b.replace(old,new,1)
 (H/name).write_text(b);(H/(name+'.patch')).write_text(''.join(difflib.unified_diff(a.splitlines(True),b.splitlines(True),fromfile=str(S/name),tofile=str(S/name))))
 changes[name]={'baseline_sha256':hashlib.sha256(a.encode()).hexdigest(),'candidate_sha256':hashlib.sha256(b.encode()).hexdigest()}
patch('compact_mcm.py',[("    durability_selected = type(policy.get('schema_version')) is int and policy['schema_version']==2", "    from . import compact_mcm_batched\n    batched_selected = compact_mcm_batched.selected(policy)\n    if batched_selected:compact_mcm_batched.validate(policy,pairs)\n    durability_selected = type(policy.get('schema_version')) is int and policy['schema_version']==2"), ("if durability_selected else {'schema_version','max_entries','max_workflow_metadata_bytes','numeric'})", "if durability_selected else ({'schema_version','max_entries','max_workflow_metadata_bytes','numeric','batched'} if batched_selected else {'schema_version','max_entries','max_workflow_metadata_bytes','numeric'}))"), ("policy['schema_version'] in (1,2)","policy['schema_version'] in (1,2,3)"), ("    with compact_owner._held(target.owner) as held:\n        return _produce_locked", "    with compact_owner._held(target.owner) as held:\n        from . import compact_mcm_batched\n        selected_policy=json.loads(target.owner.bound._run.read_input(input_name))\n        if compact_mcm_batched.selected(selected_policy):\n            require(progress is None and diagnostic is None,'batched scoring diagnostic/partial-stop route not implemented')\n            return compact_mcm_batched.produce(target,graph_hash=graph_hash,input_name=input_name,output_input=output_input,held=held)\n        return _produce_locked")])
patch('compact_owner.py',[("    contract = thaw(stage.contract)\n    if 'archive' not in contract:","    contract = thaw(stage.contract)\n    if 'batched' in contract:\n        from .compact_mcm_batched import stage_content\n        return stage_content(stage)\n    if 'archive' not in contract:"),("    def _stage_bindings(self, stage):\n", "    def _stage_bindings(self, stage):\n        if stage.contract is not None and 'batched' in stage.contract:\n            _stage_content(stage);return\n")])
patch('compact_mcm_output.py',[("def _source(args):\n    root", "def _source(args):\n    if 'batched' in args['contract']:\n        from .compact_mcm_batched import output_source\n        return output_source(args)\n    root"),("def _chunks(args, start):\n    root", "def _chunks(args, start):\n    if 'batched' in args['contract']:\n        from .compact_mcm_batched import output_chunks\n        yield from output_chunks(args,start)\n        return\n    root")])
(H/'SOURCE_PINS01.json').write_text(json.dumps(changes,indent=2)+'\n')
