from pathlib import Path
import json,hashlib,stat,tarfile
M=Path.cwd();F=M/'research/onchain-paper-replication-2026-09-24/full_sources';D=Path(__file__).parent;T=F/'financial-wrapper-continuation-successor-terminal-flat01-2026-10-05';R=F/'financial-wrapper-continuation-successor-terminal-remote01-2026-10-05';C=F/'heartbeat-root-checkpoint10-2026-10-04';CAP=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');PREFIX='research/onchain-paper-replication-2026-09-24/full_sources/financial-wrapper-continuation-successor-terminal-capture01-2026-10-05';H=lambda b:hashlib.sha256(b).hexdigest()
def read(p):return json.loads(p.read_bytes())
def ref(p):b=p.read_bytes();return {'path':str(p),'bytes':len(b),'sha256':H(b)}
def put(n,x):p=D/n;assert not p.exists();p.write_text(json.dumps(x,sort_keys=True,indent=2)+'\n');p.chmod(0o444);return ref(p)
r=read(T/'RECOVERY01.json');root=read(T/'ACTUAL_ROOT_EXIT01.json');meta=read(T/'flat/body-metadata.json');manifest=read(R/'selected'/PREFIX/'archive-manifest.json');capture=read(R/'selected'/PREFIX/'CAPTURE01.json');check=read(D/'TERMINAL_CAPTURE_CHECK01.json');raw27=read(D/'RAW_EVIDENCE01.json')
assert ref(T/'RECOVERY01.json')['sha256']=='169b8bdacf67bb375f9dcef44fdff02f9a3649710f05215eb6798ab1dd510a63' and ref(T/'ACTUAL_ROOT_EXIT01.json')['sha256']=='1043bf6f66132d088818849479bad90e850d6e69cfa675bb66e8c8914779837d'
assert root['actual_root_exit']==0 and root['session_id'] is None and root['tool_chunk_id']=='c981ef'
for n in ['entry','recovery_receipt','stdout','stderr']:assert ref(Path(root[n]['path']))==root[n]
assert r['receiver_receipt_sha256']==ref(R/'REMOTE_RECOVERY01.json')['sha256']=='cf8f9f9fc97a59cb41d830798d78cf1c16589ee29e1bed68374527bdc22ccffb'
assert ref(T/'flat/body-metadata.json')['sha256']==r['primitive']['metadata_sha256']=='1f9661119ba5fca936c4c4b20d79869f8cc818495028dfbb39347850d3615706'
assert meta['manifest']==manifest and meta['archive']==capture['archive'] and r['primitive']['regular_bodies']==r['primitive']['members']==88
assert set(meta)=={'schema_version','archive','flat_members','manifest'} and len(meta['flat_members'])==88
assert set(p.name for p in (T/'flat').iterdir())==set(meta['flat_members'].values())|{'body-metadata.json'} and len(set(meta['flat_members'].values()))==88
assert stat.S_IMODE((T/'flat').stat().st_mode)==stat.S_IMODE(T.stat().st_mode)==0o700
expected={v['path']:v for v in manifest['members']};payload={}
for name,leaf in meta['flat_members'].items():
 p=T/'flat'/leaf;assert p.is_file() and not p.is_symlink() and p.stat().st_nlink==1 and stat.S_IMODE(p.stat().st_mode)==0o600
 b=p.read_bytes();assert len(b)==expected[name]['bytes'] and H(b)==expected[name]['sha256'];payload[name]=b
assert set(payload)==set(expected)
archive=R/'selected'/PREFIX/'increment.tar.gz';assert ref(archive)['sha256']==r['archive_sha256']==capture['archive']['sha256']=='d26c3af64a99e21162df9effacd9249f749555da059cc19a4e882125810cde17'
with tarfile.open(archive,'r:gz') as tar:
 members=tar.getmembers();assert len(members)==88 and {m.name for m in members}==set(payload)
 for member in members:assert member.isfile() and tar.extractfile(member).read()==payload[member.name] and member.mode==expected[member.name]['mode']
x=json.loads(payload['COMPOSITION01.json']);assert H(payload['COMPOSITION01.json'])==check['composition']['sha256'];assert len(x['materialized'])==87
originmap={}
for name,row in x['materialized'].items():
 b=payload[row['flat']];assert len(b)==row['bytes'] and H(b)==row['sha256'];label,rel=name.split('/',1);base=CAP if label=='CAP' else C if label=='Root' else Path(x['scopes'][label]['root']);p=base/rel;assert p.read_bytes()==b;originmap[str(p)]=(name,b)
for row in raw27['files']:
 n,b=originmap[row['path']];assert H(b)==row['sha256'] and len(b)==row['bytes']
parentterm=json.loads(payload[x['materialized']['Parent/attempt/parent-terminal.json']['flat']]);guardname='CAP/research_artifacts/onchain-paper-replication-2026-09-24/runs/'+x['identity']+'/guard/final.json';guard=json.loads(payload[x['materialized'][guardname]['flat']]);actualroot=json.loads(payload[x['materialized']['Root/SUCCESSOR_NUMERICAL_ROOT_EXIT01.json']['flat']]);assert parentterm['actual_parent_exit'] is None and guard['child_exit_code'] is None and actualroot['actual_root_exit']==1
assert not (CAP/'research_runs'/x['identity']).exists() and not (CAP/'research_artifacts/financial_wrapper_engineering'/x['identity']).exists()
checkflat={'schema_version':1,'decision':'accepted-actual-terminal-flat-byte-recovery','flat_receipt':ref(T/'RECOVERY01.json'),'actual_flat_root_exit':ref(T/'ACTUAL_ROOT_EXIT01.json'),'flat_metadata':ref(T/'flat/body-metadata.json'),'actual_receiver':ref(R/'REMOTE_RECOVERY01.json'),'actual_archive':ref(archive),'actual_manifest':ref(R/'selected'/PREFIX/'archive-manifest.json'),'composition_sha256':H(payload['COMPOSITION01.json']),'flat_bodies_independently_read_once':88,'original_bodies_current_origin_joined':87,'raw_terminal_bodies_joined':27,'flat_file_mode':0o600,'flat_root_mode':0o700,'unknown_original_exits_preserved':True,'original_839_CAP_or_Git_bodies_reread':False,'POSIX_reconstruction':False,'numerical_authority':False};print(put('TERMINAL_FLAT_CHECK01.json',checkflat))
outcome=read(D/'OUTCOME_CHECK01.json')
proof={'schema_version':1,'decision':'accepted-actual-complete-terminal-refusal-byte-recovery','identity':x['identity'],'source':x['source'],'outcome':'terminal-operational-preclaim-storage-refusal','actual_external_commit':'34e8da6656fc0cf7ac28cfe511ec99451f09cadc','actual_receiver':ref(R/'REMOTE_RECOVERY01.json'),'actual_receiver_root_exit':ref(R/'ACTUAL_ROOT_EXIT01.json'),'actual_flat_recovery':ref(T/'RECOVERY01.json'),'actual_flat_root_exit':ref(T/'ACTUAL_ROOT_EXIT01.json'),'actual_capture':check['capture'],'actual_archive_sha256':r['archive_sha256'],'actual_manifest_sha256':r['manifest_sha256'],'independent_outcome':ref(D/'OUTCOME_CHECK01.json'),'independent_capture':ref(D/'TERMINAL_CAPTURE_CHECK01.json'),'independent_remote':ref(D/'TERMINAL_REMOTE_CHECK01.json'),'independent_flat':ref(D/'TERMINAL_FLAT_CHECK01.json'),'accepted_unchanged_byte_basis':x['basis'],'composition_sha256':H(payload['COMPOSITION01.json']),'scope':{'CAP_regular':848,'CAP_typed':1079,'CAP_new_regular':9,'CAP_unchanged_regular_reused':839,'physical_Git':'accepted complete original physical Git bytes and metadata basis retained,438 logical objects','Parent_regular':29,'closed_preparation_review_regular':36,'outcome_phase_regular':5,'Root_regular':8,'increment_original_bodies':87,'increment_archive_bodies':88,'raw_outcome_bodies':27,'increment_original_bytes':932041},'actual_root_exit':1,'original_parent_exit':None,'job_supervisor_exit':1,'original_guard_child_exit':None,'separate_native_launcher_exit':125,'workload_pid':None,'genuine_claim_present':False,'numerical_updates':0,'new_checkpoint_present':False,'continuation_agreement_tested':False,'namespace_reserved':True,'namespace_reuse_authorized':False,'lifecycle_accounting':outcome['lifecycle_accounting'],'cleanup':outcome['cleanup'],'external_byte_recovery':True,'runtime_package_bodies_recovered':False,'POSIX_reconstruction':False,'immutable_writer_exclusion':False,'new_launch_authority':False,'historical_unknowns_rewritten':False,'remaining_local_tail':'This independent recovery proof, later review closure and post-recovery receiver/flat receipts require the next ordinary external backup; no recursive self-preservation claim.','qualification':'Complete captured terminal byte evidence established by accepted unchanged CAP/Git basis plus actual new increment external fetch and fresh flat recovery. Refusal identity remains reserved; no numerical completion, performance, capacity, economics or paper-fit claim. No old839 CAP/Git/507-body rescan.'};print(put('FULL_TERMINAL_RECOVERY_PROOF01.json',proof))
