import ast,hashlib,importlib.util,json,os,stat,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-root-launch-20261004-01');S=P.parent/'genuine-financial-wrapper-native-20261003-01/source';C=F/'financial-genuine-wrapper-root-preservation04-2026-10-04';B=F/'financial-genuine-wrapper-root-final-binding02-2026-10-04';V=F/'financial-genuine-wrapper-final-release-review01-2026-10-04';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
ck(sha((U/'recovery04.py').read_bytes())=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','R4 exact');sys.path.insert(0,str(U));sp=importlib.util.spec_from_file_location('union_review_R',U/'recovery04.py');R=importlib.util.module_from_spec(sp);sp.loader.exec_module(R)
def read(p):return R.read(p.parent,p.name)
def doc(p):return json.loads(read(p))
sm=doc(C/'SOURCE_MANIFEST01.json');pm=doc(C/'PARENT_MANIFEST01.json');vm=doc(C/'REVIEW_MANIFEST01.json');ck(R.scan(S)==sm and R.scan(P)==pm and R.scan(V)==vm,'complete stable three actual scopes');ck((len(sm['members']),len(pm['members']),len(vm['members']))==(878,23,10),'actual 878/23/10');old=doc(F/'financial-genuine-wrapper-root-release-binding01-2026-10-04/PARENT_MANIFEST02.json');rows={r['path']:r for r in pm['members']};ck(all(rows[r['path']]==r for r in old['members']),'all original19 unchanged');ck(set(rows)-{r['path'] for r in old['members']}=={'REQUEST_FINAL03.json','proofs/FINAL_RELEASE_REVIEW01.json','proofs/FINAL_RELEASE_REPORT01.md','proofs/FINAL_RELEASE_MANIFEST01.json'},'only four finalappendages')
q=doc(P/'REQUEST_FINAL03.json');ck(sha(read(P/'REQUEST_FINAL03.json'))=='dc80a4dff93fbf3261bdf151076c1420630ed38926ab7094d60eb1902bde25bc' and read(P/'REQUEST_FINAL03.json')==read(B/'REQUEST_FINAL03.json'),'actual final request');before=doc(P/'REQUEST_CANDIDATE02.json');ck({k for k in q if q[k]!=before[k]}=={'final_review'},'only actual final review reference changes');ck(sha(R.encode({k:v for k,v in q.items() if k!='final_review'}))=='6884fa8027cf49b519f5c635828244d4685ce0f989691593e816792e2586704a','contract unchanged')
for n,orig in [('FINAL_RELEASE_REVIEW01.json','RELEASE_REVIEW01.json'),('FINAL_RELEASE_REPORT01.md','REVIEW01.md'),('FINAL_RELEASE_MANIFEST01.json','MANIFEST01.json')]:ck(read(P/'proofs'/n)==read(V/orig),'actual final proof copy '+n)
ck(q['final_review']=={'path':str(P/'proofs/FINAL_RELEASE_REVIEW01.json'),'sha256':sha(read(V/'RELEASE_REVIEW01.json'))},'exact genuine review reference');m=doc(V/'MANIFEST01.json');ck(len(m['entries'])==9 and {p.name for p in V.iterdir()}=={r['path'] for r in m['entries']}|{'MANIFEST01.json'},'manifest self-exclusion explains10')
for r in m['entries']:
 p=V/r['path'];ck(stat.S_IMODE(p.lstat().st_mode)==r['mode'] and len(read(p))==r['bytes'] and sha(read(p))==r['sha256'],'all9original reviewed bodies unchanged')
validation=doc(B/'VALIDATION01.json');ck(validation['actual_exit']==0 and validation['launch_requested'] is False and validation['native_preflight_performed'] is False and '--launch' not in validation['actual_argv'] and not Path('/proc',str(validation['actual_pid'])).exists(),'Root original defaultvalidation record closed');ck(read(B/'VALIDATE01.out')==read(B/'VALIDATE01.err')==b'','actual empty validation streams');ck(not (P/'attempt').exists() and all(not (S/n).exists() for n in ['research_runs','research_artifacts','fixture_outer']),'no launch reservation outputs')
source=read(C/'capture04.py');tree=ast.parse(source);main=next(n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='main');condition=next(n for n in ast.walk(main) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and n.func.attr=='require' and len(n.args)==2 and isinstance(n.args[1],ast.Constant) and n.args[1].value=='exact final23/9 scope');namespace={'R':R,'parent_manifest':pm,'review_manifest':vm};witness=None
try:exec(compile(ast.Module(body=[ast.Expr(value=condition)],type_ignores=[]),str(C/'capture04.py'),'exec'),namespace)
except ValueError as e:witness={'exception':type(e).__name__,'message':str(e),'line':condition.lineno,'actual_review_members':len(vm['members']),'declared_expected_review_members':9,'source_sha256':sha(source)}
ck(witness is not None,'exact source refusal reproduced without capture writes');text=source.decode();ck(text.index("R.put(HERE/'REQUEST01.json'")<text.index("'exact final23/9 scope'")<text.index("R.put(HERE/'INTENT01.json'"),'failure follows request before intent');ck(not any((C/n).exists() for n in ['REQUEST01.json','INTENT01.json','CAPTURE01.json','complete-source01.tar.gz']),'actual capture remains unexecuted');ck(R.scan(S)==sm and R.scan(P)==pm and R.scan(V)==vm,'three scopes unchanged after review');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas','tradingagents'} for n in sys.modules),'no numerical lifecycle imports')
out={'schema_version':1,'decision':'WITHHELD_CAPTURE_SOURCE','finding':'FC1: actual final review scope has ten members including its manifest, source requires nine','checks':len(checks),'source_sha256':sha(source),'actual_composition_accepted':True,'source_members':878,'parent_members':23,'review_members':10,'contract_sha256':'6884fa8027cf49b519f5c635828244d4685ce0f989691593e816792e2586704a','witness':witness,'actual_capture_executed':False,'native_authority':False,'source_request_write_before_refusal':True,'required_remedy':'Preserve source04; a separately reviewed successor must use complete ten-member review scope without dropping MANIFEST01.json.'};(O/'READBACK01.json').write_bytes(R.encode(out));(O/'WITNESS01.json').write_bytes(R.encode(witness));print(json.dumps(out,indent=2))
