import ast,hashlib,importlib.metadata,importlib.util,json,os,platform,shutil,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();C=F/'financial-genuine-wrapper-root-parent-composition01-2026-10-04';PREP=F/'financial-genuine-wrapper-parent-preparation03-2026-10-04';REV=F/'financial-genuine-wrapper-parent-review03-2026-10-04';CAP=F/'financial-genuine-wrapper-root-preservation03-2026-10-04';P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-root-launch-20261004-01');S=P.parent/'genuine-financial-wrapper-native-20261003-01/source';H='d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
ck(sha((PREP/'recovery04.py').read_bytes())=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','acceptedrecoveryhash');sys.path.insert(0,str(PREP));sp=importlib.util.spec_from_file_location('composition_review_primitives',PREP/'recovery04.py');R=importlib.util.module_from_spec(sp);sp.loader.exec_module(R)
def read(p):return R.read(p.parent,p.name)
def doc(p,pin=None):
 b=read(p);ck(pin is None or sha(b)==pin,'pin '+p.name);return json.loads(b)
# Verify honest typed complete inventories before accepting copied helper origins.
for d,pin in [(PREP,'3c6c8ef58e93de1a314a105b77e0b452267494487c971c73f925f98615ad78de'),(REV,'c5c37ae65524e7033e1b5174d7391bdfd87704ee8576390c44c8236422c59af6')]:
 m=doc(d/'MANIFEST01.json',pin);rows=m['entries'];ck({str(p.relative_to(d)) for p in d.rglob('*')}=={r['path'] for r in rows}|{'MANIFEST01.json'},'complete accepted parent inventory')
 for r in rows:
  p=d/r['path'];s=p.lstat();ck(stat.S_IMODE(s.st_mode)==r['mode'],'parent originalmode')
  if r['type']=='file':b=read(p);ck(len(b)==r.get('bytes',r.get('size')) and sha(b)==r['sha256'],'parent source/review body')
  elif r['type']=='directory':ck(stat.S_ISDIR(s.st_mode),'honest directory')
  else:raise AssertionError('unexpected fixturetype')
B=F/'financial-genuine-wrapper-root-release-binding01-2026-10-04';binding=doc(B/'BINDING01.json');q=doc(P/'REQUEST_CANDIDATE02.json',binding['candidate_sha256']);old=doc(P/'REQUEST_DRAFT01.json',binding['original_draft_sha256']);ck(read(P/'REQUEST_CANDIDATE02.json')==read(B/'REQUEST_CANDIDATE02.json'),'actual candidate copy');ck({k for k in q if q[k]!=old[k]}=={'status','proofs'} and q['final_review'] is None,'only status/full recovery bound, final review remains absent');ck({k:v for k,v in q['proofs'].items() if k!='full_recovery'}=={k:v for k,v in old['proofs'].items() if k!='full_recovery'},'old proof roles unchanged');ck(sha(R.encode({k:v for k,v in q.items() if k!='final_review'}))==binding['contract_sha256']=='6884fa8027cf49b519f5c635828244d4685ce0f989691593e816792e2586704a','exact contract');sm=doc(CAP/'SOURCE_MANIFEST01.json');pm=doc(B/'PARENT_MANIFEST02.json');ck(R.scan(S)==sm and R.scan(P)==pm and len(pm['members'])==19,'complete actual source878 parent19');original=doc(C/'PARENT_MANIFEST01.json');current={r['path']:r for r in pm['members']};ck(all(current[r['path']]==r for r in original['members']),'all15 original typed modes bodies unchanged');ck(set(current)-{r['path'] for r in original['members']}==set(binding['new_parent_appendages']),'exact4 appendages');proofpins={}
for role,ref in q['proofs'].items():
 raw=read(Path(ref['path']));ck(sha(raw)==ref['sha256'],'actual proof '+role);proofpins[role]=sha(raw)
FR=F/'financial-genuine-wrapper-actual-recovery-review02-2026-10-04'
for n,origin in [('FULL_RECOVERY_READBACK02.json','FLAT_READBACK02.json'),('FULL_RECOVERY_REVIEW02.md','FLAT_REVIEW02.md'),('FULL_RECOVERY_MANIFEST02.json','MANIFEST02.json')]:ck(read(P/'proofs'/n)==read(FR/origin),'genuine full recovery origin '+n)
for n,pin in dict(q['helper_hashes'],**{'parent01.py':q['caller_sha256']}).items():ck(sha(read(P/n))==pin and read(P/n)==read(PREP/n),'actual7 accepted helper bytes')
gate=doc(S/q['registration'],q['registration_sha256']);e=gate['experiments'][q['identity']];ck(q['source_files']==e['source_files'] and len(q['source_files'])==289,'exact registered289source');ck(q['source']==q['design_source']==H and q['input_hashes']=={k:v['sha256'] for k,v in e['inputs'].items()} and len(e['inputs'])==8,'exact source design8inputs')
for role,ref in e['inputs'].items():ck(sha(read(S/ref['path']))==ref['sha256'],'actual input '+role)
order=doc(P/'CASE_ORDER01.json',binding['case_order_sha256']);ck(order['first_initial']==order['initial10_order'][0]==q['identity']=='financial-wrapper-classification-eager-interrupt1-20261003-01' and q['expected_phase']=='interrupt1','exact firstcase');ck(len(order['complete18_topological_order'])==18 and len(order['initial10_order'])==len(gate['experiments'])==10,'18fixed10initial8withheld')
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never','-C',str(S),*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'boundedofflineGit');return r.stdout
installed=doc(F/'financial-genuine-wrapper-installed-gate-admission-review01-2026-10-04/READBACK01.json','db9d9e4f5957b64a8c29aed1514d99910917e51c7d0d1165f9215f5308351e29');rows={r['path']:r for r in installed['joined']};tree={}
for entry in git(['ls-tree','-r','-z',H]).split(b'\0'):
 if not entry:continue
 left,n=entry.split(b'\t');mode,typ,oid=left.decode().split();ck(typ=='blob','actualregularGit');tree[n.decode()]=(mode,oid)
ck(set(tree)==set(rows)==set(q['source_files'])|{q['registration']} and len(tree)==290 and sum(n.startswith('tradingagents/') for n in tree)==149,'complete290289149closure');reply=git(['cat-file','--batch'],(''.join(tree[n][1]+'\n' for n in sorted(tree))).encode());offset=0
for n in sorted(tree):
 end=reply.index(b'\n',offset);oid,typ,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2;r=rows[n];ck(typ=='blob' and oid==tree[n][1]==r['git_oid'] and tree[n][0]==r['git_mode'] and reply[offset-1:offset]==b'\n' and read(S/n)==b and sha(b)==r['sha256'] and stat.S_IMODE((S/n).stat().st_mode)==r['mode'] and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+b).hexdigest()==oid,'all290actualbody/Git/mode')
ck(offset==len(reply) and installed['implementation']==194,'completebatch194unchanged')
# Read metadata only. Readonly RECORD hardlinks are not owned output files.
def stream(p,limit):
 p=Path(p);s=p.lstat();ck(p.resolve()==p and stat.S_ISREG(s.st_mode) and s.st_size<=limit,'readonlyruntime extent/type');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW);h=hashlib.sha256();n=0
 try:
  ck(R.sig(s)==R.sig(os.fstat(fd)),'runtime actualopened')
  while True:
   b=os.read(fd,65536)
   if not b:break
   n+=len(b);ck(n<=limit,'bounded runtimebytes');h.update(b)
  ck(n==s.st_size and R.sig(s)==R.sig(os.fstat(fd))==R.sig(p.lstat()),'stable runtimebody');return h.hexdigest(),n,s.st_nlink
 finally:os.close(fd)
runtime=q['runtime_mapping'];ck(runtime==doc(S/e['inputs']['runtime_mapping']['path']) and len(runtime['distribution_records'])==251 and len({r['name'] for r in runtime['distribution_records']})==251,'actual251runtime mapped');records=[]
for row in runtime['distribution_records']:
 p=Path(row['record']);ck(p.is_relative_to(Path(sys.prefix)/'lib/python3.13/site-packages') and p.name=='RECORD' and p.parent.name.endswith('.dist-info') and importlib.metadata.version(row['name'])==row['version'],'actual metadata version/path');h,n,links=stream(p,R.FILE);ck(h==row['record_sha256'],'actual251RECORDhash');records.append(dict(row,bytes=n,nlink=links))
exe=Path(sys.executable).resolve();eh,en,el=stream(exe,64*1024**2);ck(runtime['executable']==sys.executable and runtime['resolved_executable']==str(exe) and runtime['prefix']==sys.prefix and runtime['python']==platform.python_version() and eh==runtime['executable_sha256'] and sha(read(S/'uv.lock'))==runtime['lock_sha256'],'actual interpreterbasic metadata');env=doc(S/e['inputs']['environment']['path']);ck(env['python']==platform.python_version() and env['cpu_count']==os.cpu_count() and env['lock_sha256']==runtime['lock_sha256'] and all(importlib.metadata.version(n)==v for n,v in env['packages'].items()),'basic historicalexpectation fields match noTorchAPI');
# Only exact stdlib validator functions are evaluated. No preflight, launch,
# job module, ResearchRun, Owner, Binding or numerical package is imported.
parent_ast=ast.parse(read(P/'parent01.py'));chosen=[n for n in parent_ast.body if isinstance(n,ast.FunctionDef) and n.name in {'reference','contract','validate_release'}]
ns={'R':R,'Path':Path,'sha':sha,'require':R.require,'json':json,'re':__import__('re'),'CAP':S,'PROOFS':{'cumulative','full_recovery','independent_source_input_runtime'}};exec(compile(ast.Module(body=chosen,type_ignores=[]),str(P/'parent01.py'),'exec'),ns)
try:ns['validate_release'](q)
except ValueError as error:ck(str(error)=='unresolved release field final_review','actual candidate honestly refuses absent review');refusal=str(error)
else:raise AssertionError('candidate falsely released')
jobpath=S/'tradingagents/research/onchain_replication/job.py';jobtext=read(jobpath).decode();jobast=ast.parse(jobtext);worker=next(n for n in jobast.body if isinstance(n,ast.FunctionDef) and n.name=='_worker');wt=ast.unparse(worker);ck(wt.index('with ResearchRun.start(')<wt.index('inventory(root, include_torch='),'genuine claim before actual Torch inventory');ck("raise ValueError('registered execution environment differs')" in wt and "financial_wrapper_fixture.execute(run, args" in wt,'mismatch raises actual failed lifecycle, genuine execute');resourcepath=S/'tradingagents/research/onchain_replication/resources.py';rt=read(resourcepath).decode();fwtext=read(S/'tradingagents/research/onchain_replication/financial_wrapper_fixture.py').decode();ck('memory_swap_max_bytes=0' in jobtext and "_command(args, 'worker')" in jobtext,'native zero swap genuine worker');ck("raise PlannedInterruption('prospective engineering failed-parent fixture after one real update; no fit completion')" in fwtext and "deadline=time.monotonic()+1700" in fwtext and 'torch.set_num_threads(2)' in fwtext and "require(not torch.cuda.is_available()" in fwtext,'fixed plannedFAILED/1700/CPU policy');ck('ResearchRun.start' not in read(P/'parent01.py').decode(),'outer caller cannot manufacture lifecycle claim')
j=doc(S/e['inputs']['execution_job']['path']);policy=j['resources'];ck(policy['memory_max_bytes']==policy['memory_high_bytes']==3*1024**3 and policy['wall_seconds']==1800 and policy['disk_free_floor_bytes']==10*1024**3 and policy['disk_paths']==[str(S)] and policy['storage_budget']['root']==str(S) and policy['native_unit_limits']['file_size_bytes']==4*1024**2,'actual native resource frozen policy')
pt=read(P/'parent01.py').decode();st=read(P/'supervisor01.py').decode();ck('supervise(command,CAP,env,directory,1840,checked,spawned)' in pt and 'child_cleanup(q,args,child[\'process\'],directory)' in pt and "'actual_parent_exit':None" in pt and "'outcome_semantics_accepted':False" in pt,'outer bound cleanup originaloutcome uncertainty');ck(st.index('on_spawn(process)')<st.index('tree.scan()'),'accepted PF2 spawn handle before fallible census');ck('finally:R._cleanup((lambda:os.close(fd),))' in pt and 'R._cleanup((retain_cleanup,retain_terminal,checked)' in pt,'accepted PF1 and complete cleanup reducer')
ck(all(not (S/n).exists() for n in ['research_runs','research_artifacts','fixture_outer']) and not (P/'attempt').exists(),'actual no claims outputs attempt');ck(R.scan(S)==sm and R.scan(P)==pm and git(['rev-parse','HEAD']).decode().strip()==H and git(['status','--porcelain','--untracked-files=all'])==b'','final stable complete source parent unchanged');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas','tradingagents'} for n in sys.modules),'no numerical or lifecycle imports')
# This is the real independent source-contract verdict, not an OS outcome.
machine={'schema_version':1,'decision':'accepted-exact-one-use-financial-parent','contract_sha256':ns['contract'](q),'proof_sha256':proofpins,'identity':q['identity'],'source':q['source'],'caller_sha256':q['caller_sha256']}
expected=next(n for n in ast.walk(chosen[-1]) if isinstance(n,ast.Compare) and isinstance(n.left,ast.Name) and n.left.id=='review').comparators[0]
ck({k.value for k in expected.keys}==set(machine),'exact actual seven-field review schema')
result={'schema_version':1,'decision':'ACCEPTED_EXACT_SOURCE_CONTRACT_ONLY_FINAL_UNION_AND_FRESH_PREFLIGHT_REQUIRED','checks':len(checks),'candidate_sha256':sha(read(P/'REQUEST_CANDIDATE02.json')),'contract_sha256':machine['contract_sha256'],'source':H,'tracked':290,'source_pins':289,'implementation':194,'package':149,'parent_members':19,'original_parent_members_recovered':15,'new_appendages_recovered':False,'current_runtime_records':records,'runtime_executable_bytes':en,'current_Torch_API_equality':None,'candidate_refusal':refusal,'proof_sha256':proofpins,'claim_count':0,'native_executed':False,'final_union_recovery_verified':False,'fresh_preflight_verified':False,'native_cleanup_verified':False,'whole_fit_capacity_verified':False,'scientific_authority':False,'requirements':['Recover complete final union including new actual review and request before launch','Independent actual final union acceptance','Fresh exact unused namespace, processes and resources preflight','At most one exact first identity; preserve genuine FAILED interruption and all outputs','Unexpected failure stops subsequent numerical release; no retry or budget transfer']}
(O/'READBACK01.json').write_bytes(R.encode(result));(O/'RELEASE_REVIEW01.json').write_bytes(R.encode(machine));print(json.dumps({'checks':len(checks),'machine_sha256':sha(R.encode(machine)),'readback_sha256':sha(R.encode(result)),'decision':result['decision']},indent=2))
