"""Actual recovered bytes only; offline Git reads with lazy fetch disabled."""
from pathlib import Path
import hashlib,json,os,stat,subprocess,time
HERE=Path(__file__).resolve().parent;MAIN=HERE.parents[3];OUT=HERE.parent/'neural-cold-feature-handoff-comparison-outcome01-2026-10-03';REC=OUT/'outcome-recovery02';COMMIT='a72e126f324b3dbfab1a8860af8c9e4158b6392d';started=time.monotonic()
def need(ok,why):
 if not ok:raise ValueError(why)
def raw(p,limit=4194304):
 s=p.lstat();need(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=limit,'bounded regular '+str(p));b=p.read_bytes();t=p.lstat();need((s.st_dev,s.st_ino,s.st_mode,s.st_size,s.st_mtime_ns,s.st_ctime_ns)==(t.st_dev,t.st_ino,t.st_mode,t.st_size,t.st_mtime_ns,t.st_ctime_ns),'file changed');return b
def digest(b):return hashlib.sha256(b).hexdigest()
def doc(p):return json.loads(raw(p))
def git(repo,args,limit=4194304):
 r=subprocess.run(['git','-c','remote.origin.promisor=false','-c','protocol.allow=never','-C',str(repo),*args],env={**os.environ,'GIT_NO_LAZY_FETCH':'1','GIT_OPTIONAL_LOCKS':'0','GIT_TERMINAL_PROMPT':'0'},capture_output=True,timeout=20);need(r.returncode==0 and len(r.stdout)<=limit and len(r.stderr)<=65536,'offline Git failed/bound');return r.stdout
receipt=doc(OUT/'REMOTE_OUTCOME_RECOVERY02.json');need(receipt['remote_commit']==COMMIT and receipt['status']=='fresh-actual-remote-complete-failed-comparison-outcome-recovered','actual receipt status/commit');need(receipt['actual_numerical_jobs_replayed']==0,'no replay');repo=REC/'repository.git';need(git(repo,['rev-parse','FETCH_HEAD']).decode().strip()==COMMIT,'fresh fetched commit');need(not (repo/'objects/info/alternates').exists(),'no alternates')
selected=receipt['selected_blobs'];need(len(selected)==101 and len({x['path'] for x in selected})==len(selected),'selected denominator');total=0
for row in selected:
 name=row['path'];p=Path(name);need(not p.is_absolute() and '..' not in p.parts and str(p)==name,'selected safe path');copy=raw(REC/'selected'/p);need(len(copy)==row['bytes'] and digest(copy)==row['sha256'],'selected localhash');need(copy==raw(MAIN/p),'selected original equality');total+=len(copy);need(total<=64*1024**2,'selected total');need(git(repo,['show',COMMIT+':'+name])==copy,'actual offline remote blob')
retained=doc(OUT/'OUTCOME_RETENTION01.json');binding=doc(OUT/'COLLECTION_ROOT_MODE_BINDING01.json');archive=raw(REC/'selected'/OUT.relative_to(MAIN)/'comparison-outcome01.tar.gz');need(digest(archive)==retained['archive_sha256']==receipt['archive_sha256']=='0df30abe430dced727edec3687a49bad739e743d62290b7972e76a8ee5d8774d','same independently canonical verified archive');need(archive==raw(OUT/'comparison-outcome01.tar.gz'),'original archive bytes')
root=REC/'collection';need(stat.S_IMODE(root.lstat().st_mode)==binding['mode']==509 and stat.S_ISDIR(root.lstat().st_mode),'actual restored root mode');rows=retained['members'];expected={x['path']:x for x in rows};need(len(rows)==len(expected)==2313 and '.' not in expected,'nonroot scope');seen=set();files=dirs=size=0;todo=[root]
while todo:
 parent=todo.pop()
 with os.scandir(parent) as it:children=list(it)
 for entry in children:
  need(time.monotonic()-started<180,'sampled review duration');p=Path(entry.path);name=p.relative_to(root).as_posix();need(name in expected and name not in seen,'extra/duplicate');s=p.lstat();row=expected[name];need(stat.S_IMODE(s.st_mode)==row['mode'],'member mode');seen.add(name)
  if row['kind']=='directory':need(stat.S_ISDIR(s.st_mode),'directory kind');dirs+=1;todo.append(p)
  else:
   need(stat.S_ISREG(s.st_mode) and s.st_nlink==1,'regular singlelink');b=raw(p);need(len(b)==row['bytes'] and digest(b)==row['sha256'],'member extent/hash');files+=1;size+=len(b)
need(seen==set(expected) and (files,dirs,size)==(1764,549,9963221),'full restored member equality');need(receipt['whole_tree_members_including_root']==2314,'inclusive denominator')
cap=root/'data/capsule';B='361339125a3f1cd57e7ba8611f5a994ae649fa0b';A='9742c6ec817dd0917f9f35a52e4b83965ca1cd29';need(git(cap,['rev-parse','HEAD']).decode().strip()==B,'restored B');need(git(cap,['rev-list','--parents','-n','1',B]).decode().strip()==B+' '+A,'restored sole parent');need(not (cap/'.git/objects/info/alternates').exists(),'restored no alternates')
report=doc(root/'collection.json');need(digest(raw(root/'collection.json'))==retained['collection_sha256']==receipt['collection_sha256'],'collection');expected_dispositions={'compare':'FAILED_AUTHENTICATED_TERMINAL','materialize':'MATERIALIZATION_COMPLETE_SCIENCE_PENDING'};need({k:v['strict_scientific_disposition'] for k,v in report['outcomes'].items()}==expected_dispositions==receipt['verification']['scientific_dispositions'],'original phase dispositions');need(receipt['verification']['status']=='complete-actual-recovered-byte-equality','actual collector readonly verification');need(not raw(REC/'verify-recovery.stderr'),'readonly verify stderr')
query=doc(root/'request.json');external=doc(root/'data/external-evidence/reference-index.json')['references'];inventory_ref=query['inventory'];entry=next(x for x in external if x['original']==inventory_ref);inventory=doc(root/'data/external-evidence'/entry['retained']);need(inventory['source_count']==195 and inventory['package_count']==147,'source195/package147');
for row in inventory['source_inventory']:need(digest(raw(cap/row['target']))==row['sha256'],'source body identity')
runtime=doc(cap/'cold_prep/runtime.json');need(len(runtime['distribution_records'])==251,'251 runtime RECORD metadata only')
reg=doc(cap/'cold-comparison-registration02.json');exp=reg['experiments']['compact-cold-comparison-20261003-01'];need(len(exp['inputs'])==44 and len(exp['cells'])==1,'fixed compare denominator');family=reg['families']['compact-cold-genuine-authority'];need(family['attempt_budget']==2 and family['prior_attempts']==0,'exhausted finite family')
for value in exp['inputs'].values():need(digest(raw(cap/value['path']))==value['sha256'],'all44 recovered original inputs')
for identity,terminal,status in [('compact-cold-inputs-20261003-01','complete.json','complete'),('compact-cold-comparison-20261003-01','failed.json','failed')]:
 run=cap/'research_runs'/identity;claim=raw(run/'claim.json');t=doc(run/terminal);need(t['status']==status and t['claim_sha256']==digest(claim),'original terminal join')
need(not (cap/'research_runs/compact-cold-comparison-20261003-01/complete.json').exists(),'no scientific completion');need(not any((cap/'research_runs/compact-cold-comparison-20261003-01/outputs'/n).exists() for n in exp['outputs']),'four outputs missing')
parent=doc(root/'data/parent-compare/intent.json');guard=doc(cap/'research_artifacts/onchain-paper-replication-2026-09-24/runs/compact-cold-comparison-20261003-01/guard/final.json');pids={parent['parent_pid']}|set(report['outcomes']['compare']['cleanup']['recorded_pids'])|{int(x) for x in guard['cpu_thread_readback']};need(len(pids)==12 and all(not Path('/proc',str(pid)).exists() for pid in pids) and not Path(guard['cgroup']).exists(),'original12PIDcgroupabsence');need(guard['child_exit_code'] is None and guard['cleanup_verified'] is True and guard['cleanup_unit_properties']['ExecMainStatus']=='125','failed native distinct');need(doc(root/'data/parent-compare/wait.json')['wrapper_exit_code']==1 and (root/'data/parent-compare/failure.json').is_file(),'original parent failure')
result={'schema_version':1,'status':'ACTUAL_REMOTE_RECOVERY_ACCEPTED_CORE_SCOPE','remote_commit':COMMIT,'selected_blobs':len(selected),'selected_bytes':total,'nonroot_members':len(rows),'root_inclusive_members':2314,'files':files,'nonroot_directories':dirs,'root_inclusive_directories':550,'logical_bytes':size,'root_mode':509,'archive_sha256':retained['archive_sha256'],'source':B,'phase_dispositions':expected_dispositions,'fresh_current_original_process_absence':sorted(pids),'family_attempts_spent':2,'family_attempt_budget':2,'source_review02_and03':'included in actual101 selected closure','selected_source_count':195,'package_count':147,'registered_compare_inputs':44,'runtime_RECORD_metadata_count':251,'installed_runtime_or_financial_store_recovery':False,'scientific_completion':False,'reviewer_network_or_replay':False,'elapsed_seconds':time.monotonic()-started}
(HERE/'READBACK02.json').write_text(json.dumps(result,indent=2,sort_keys=True)+'\n');print(json.dumps(result,sort_keys=True))
