import ast,hashlib,json,os,shutil,stat,subprocess,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();P=F/'financial-genuine-wrapper-root-remote-recovery03-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
def sig(s):return (s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns)
def read(p):
 s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4*1024**2 and p.resolve()==p,'regular canonical bounded input');fd=os.open(p,os.O_RDONLY|os.O_NOFOLLOW)
 try:
  ck(sig(os.fstat(fd))==sig(s),'actual opened identity');out=[];total=0
  while True:
   b=os.read(fd,65536)
   if not b:break
   total+=len(b);ck(total<=s.st_size,'bounded extent');out.append(b)
  ck(sig(os.fstat(fd))==sig(s)==sig(p.lstat()) and total==s.st_size,'stable body identity');return b''.join(out)
 finally:os.close(fd)
def git(args,data=None):
 r=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never',*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1','GIT_TERMINAL_PROMPT':'0'});ck(r.returncode==0 and len(r.stdout)<=8*1024**2 and len(r.stderr)<=65536,'bounded local Git only');return r.stdout
raw=read(P/'SELECTED_BODIES01.json');ck(sha(raw)=='932033a5e2ebd0e09b3cfd72b10cc12643b8f8366f18d12bba07736253876e4d','exact selection pin');v=json.loads(raw);ck((json.dumps(v,sort_keys=True,indent=2)+'\n').encode()==raw,'canonical selection');H='81022cc2f30c4aa2bf58a076eb6cff8d03c30b69';ck(v['remote_commit']==H,'explicit committed selection');rows=v['rows'];names=[r['path'] for r in rows];ck(names==sorted(set(names)) and len(rows)==248 and sum(r['bytes'] for r in rows)==7767259,'exact unique248 extent7767259');ck(11+2*len(rows)==507 and len(rows)<=506 and 507<=1024 and sum(r['bytes'] for r in rows)<=64*1024**2,'effective row and operation budgets');ck(git(['rev-parse','HEAD']).decode().strip()==H,'actual MainHEAD selectedcommit')
committed={}
for ent in git(['ls-tree','-r','-z',H,'--',*names]).split(b'\0'):
 if not ent:continue
 meta,path=ent.split(b'\t');mode,typ,oid=meta.decode().split();committed[path.decode()]={'git_mode':mode,'kind':typ,'git_object':oid}
ck(set(committed)==set(names),'exact committed selected tree');reply=git(['cat-file','--batch'],(''.join(committed[n]['git_object']+'\n' for n in names)).encode());offset=0;joined=[]
for row in rows:
 n=row['path'];p=ROOT/n;meta=committed[n];ck(n.startswith('research/') and Path(n).as_posix()==n and '..' not in Path(n).parts and not any(x in ('.env','keys','apis') for x in Path(n).parts),'safe exact path');ck(type(row['bytes']) is int and 0<=row['bytes']<=4*1024**2 and meta['kind']=='blob' and meta['git_mode'] in ('100644','100755'),'regular selected mode extent');end=reply.index(b'\n',offset);oid,typ,size=reply[offset:end].decode().split();size=int(size);b=reply[end+1:end+1+size];offset=end+size+2
 ck(oid==meta['git_object'] and typ=='blob' and reply[offset-1:offset]==b'\n' and hashlib.sha1(b'blob '+str(size).encode()+b'\0'+b).hexdigest()==oid,'actual Git blob body OID');ck(read(p)==b and sha(b)==row['sha256'] and len(b)==row['bytes'],'complete selected byte joins');mode=stat.S_IMODE(p.lstat().st_mode);ck(meta['git_mode']==('100755' if mode&0o111 else '100644'),'actual executable-mode Git join');joined.append(dict(row,git_mode=meta['git_mode'],git_object=oid,original_filesystem_mode=mode))
ck(offset==len(reply),'complete no trailingGitframe');selected=set(names);review_closures=[]
for row in rows:
 if Path(row['path']).name not in ('MANIFEST01.json','MANIFEST02.json'):continue
 p=ROOT/row['path'];m=json.loads(read(p));members=m.get('members',m.get('entries'));regular={str((p.parent/r['path']).relative_to(ROOT)) for r in members if r.get('kind',r.get('type'))=='file'};ck(regular<=selected,'all selected review manifest regular bodies included')
 for r in members:
  q=p.parent/r['path'];s=q.lstat();ck(stat.S_IMODE(s.st_mode)==r['mode'],'review metadata original mode')
  if r.get('kind',r.get('type'))=='file':ck(stat.S_ISREG(s.st_mode) and s.st_size==r.get('bytes',r.get('size')) and sha(read(q))==r['sha256'],'review actual full regular body')
  elif r.get('kind',r.get('type'))=='directory':ck(stat.S_ISDIR(s.st_mode),'review declared directory retained as metadata')
  else:raise AssertionError('unexpected review member kind')
 review_closures.append({'manifest':row['path'],'regular_members':len(regular),'typed_members':len(members)})

C=F/'financial-genuine-wrapper-root-preservation05-2026-10-04';cap=json.loads(read(C/'CAPTURE01.json'));request=json.loads(read(C/'REQUEST01.json'));ck(sha(read(C/'CAPTURE01.json'))=='8ac4415b12753cf985688359efe7210122321ce21130c4bc472df65f04da4823' and sha(read(C/'REQUEST01.json'))=='ada07624b7954c85ed5f158785343496a4af9c5b7ee96372a6403146d88fceaf','exact finalcapture chain');ck(cap['source']==request['source']=='d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0' and request['tracked']==290 and request['source_pins']==289 and request['implementation']==194 and request['package']==149,'exactsource290/289194149')
for role,count in [('source',878),('parent',23),('review',10)]:
 mraw=read(C/(role.upper()+'_MANIFEST01.json'));m=json.loads(mraw);archive=read(C/('complete-'+role+'01.tar.gz'));ck(sha(mraw)==cap['archives'][role]['manifest_sha256']==request[role+'_manifest_sha256'] and len(m['members'])==cap[role+'_members']==count,'allthree actual manifest lineage');ck(sha(archive)==cap['archives'][role]['sha256'] and len(archive)==cap['archives'][role]['bytes'],'complete selected archive body')
prior116=json.loads(read(F/'financial-genuine-wrapper-root-remote-recovery02-2026-10-04/SELECTED_BODIES01.json'))['rows'];lookup={r['path']:r for r in rows};ck(len(prior116)==116 and all(lookup[r['path']]==r for r in prior116),'all116 prior support exact rows unchanged')
required_dirs=['financial-genuine-wrapper-root-preservation04-2026-10-04','financial-genuine-wrapper-root-preservation05-2026-10-04','financial-genuine-wrapper-root-release-binding01-2026-10-04','financial-genuine-wrapper-root-final-binding02-2026-10-04','financial-genuine-wrapper-final-release-review01-2026-10-04','financial-genuine-wrapper-final-union-capture-review01-2026-10-04','financial-genuine-wrapper-final-union-capture-review02-2026-10-04','financial-genuine-wrapper-final-union-preservation-review01-2026-10-04','financial-genuine-wrapper-final-flat-source-review01-2026-10-04','financial-genuine-wrapper-root-flat-recovery03-2026-10-04']
for name in required_dirs:
 d=F/name;regular={p.relative_to(ROOT).as_posix() for p in d.rglob('*') if p.is_file()};ck(regular<=selected,'complete required support '+name)
I=F/'financial-genuine-wrapper-final-union-preservation-review01-2026-10-04';ck(sha(read(I/'MANIFEST01.json'))=='96d318852ae8c2bab34a132aefae29300bd501b6b5d355fc5a225dbdfc70e1c2','actual fullcapture reviewpin');prior=json.loads(read(I/'READBACK01.json'));ck(prior['capture_sha256']==sha(read(C/'CAPTURE01.json')) and all(prior['archives'][role]['archive']==cap['archives'][role] for role in ['source','parent','review']),'whole canonical capture acceptance exactjoins');flat=F/'financial-genuine-wrapper-root-flat-recovery03-2026-10-04';FR=F/'financial-genuine-wrapper-final-flat-source-review01-2026-10-04';ck(sha(read(FR/'MANIFEST01.json'))=='4ff87e8b7569b7d4ae97e2f36fb34fd0bd06852bf8472d66752f882b373c3189' and sha(read(flat/'restore01.py'))=='ca8bd0042db431e6c4d48ffbf7b55814ca4e68b4ec1d37a2f8f21c442813cfd6' and sha(read(P/'recover_financial03.py'))=='8531e7bfeac0ae71091d6d2cb6feb5dde5c891e4a86faca626a5757cf7fe8bd2','exact reviewedflat transportsource');sourceverdict=json.loads(read(FR/'READBACK01.json'));ck(sourceverdict['flat_source_sha256']==sha(read(flat/'restore01.py')) and sourceverdict['transport_source_sha256']==sha(read(P/'recover_financial03.py')),'independent source verdictjoins')
for n in ['recover_financial03.py','PREPARATION01.json','PROTOCOL01.md']:ck((P/n).relative_to(ROOT).as_posix() in selected,'required transportsource support')
ck((P/'SELECTED_BODIES01.json').relative_to(ROOT).as_posix() not in selected,'selection is local postcommit notselfselected');ck(len({r['git_object'] for r in joined})==163,'163 unique actual blobs')
B=F/'financial-genuine-wrapper-root-final-binding02-2026-10-04';final=json.loads(read(B/'REQUEST_FINAL03.json'));ck(sha(read(B/'REQUEST_FINAL03.json'))=='dc80a4dff93fbf3261bdf151076c1420630ed38926ab7094d60eb1902bde25bc' and sha((json.dumps({k:v for k,v in final.items() if k!='final_review'},sort_keys=True,indent=2)+'\n').encode())=='6884fa8027cf49b519f5c635828244d4685ce0f989691593e816792e2586704a','actual selected finalrequest/contract');ck(sha(read(F/'financial-genuine-wrapper-final-release-review01-2026-10-04/RELEASE_REVIEW01.json'))=='7d18390bc44df519fcf43e88c1fb20e016994378fbc34b7d96d6e73690f8cd60','selected actual genuine review machine')
for n,pin in {'recovery04.py':'b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','owned_io.py':'09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb','bounded_git01.py':'db4a65a450bf9930abac04ab794539ebd952b07826d7314b4aea4e989dd9240f'}.items():
 p=F/'held-consumer-final-recovery-preparation04-2026-10-03'/n;ck(p.relative_to(ROOT).as_posix() in selected and sha(read(p))==pin,'all3actual primitive scope')
ck(all(not os.path.lexists(P/n) for n in ['fresh-financial03.git','selected','REMOTE_RECOVERY01.json','FAILED01.json']),'freshremote absent');ck(all(not os.path.lexists(flat/n) for n in ['flat-source01','flat-parent01','flat-review01','INTENT01.json','RECOVERY01.json']),'allactualflat absent');free=shutil.disk_usage(P).free;ck(free>=10*1024**3,'actualobserved10GiB floor');ck(git(['rev-parse','HEAD']).decode().strip()==H,'final Main unchanged');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numericalimports');out={'schema_version':1,'decision':'ACCEPTED_EXACT_FINAL_LOCAL_SELECTED_UNION_PENDING_ACTUAL_REMOTE','checks':len(checks),'selection_sha256':sha(raw),'selected_commit':H,'selected_count':248,'selected_logical_bytes':7767259,'expected_git_operations':507,'unique_git_objects':163,'effective_maximum_rows':506,'source':'d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0','capture_sha256':sha(read(C/'CAPTURE01.json')),'archives':cap['archives'],'complete_review_regular_closures':review_closures,'disk_free_bytes':free,'fresh_namespaces_absent':True,'actual_remote_or_flat_recovery':False,'final_union_acceptance':False,'runtime_native_authority':False,'joined':joined};(O/'READBACK01.json').write_text(json.dumps(out,sort_keys=True,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k not in ['joined','complete_review_regular_closures']},indent=2))
