from pathlib import Path
import json,hashlib,stat
H=Path(__file__).resolve().parent;B=H.parent;A=B/'financial-wrapper-compatibility-composed-recovery-preparation01-2026-10-04';D=B/'financial-wrapper-compatibility-composed-recovery-root01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();r=json.loads((H/'RECONSTRUCTION03.json').read_bytes())
for root,n,prefix in [(A,n,'author') for n in ['verify01.py','INPUTS01.json','MANIFEST01.json','MACHINE01.json','REPORT01.md','CONTROLS01.json','PROOF_INTERFACE01.json']]+[(D,n,'actual') for n in ['ROOT_MEASUREMENT01.json','MEASURED01.stdout','MEASURED01.stderr']]:
 p=H/'evidence'/prefix/n;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes((root/n).read_bytes())
report='''# Composed BYTE recovery checker01 review

**WITHHELD_CR1_CR2_CR3. No accepted recovery proof is authored.** Actual Root measurement9e449c82/stdout180b3768/exit0 is genuine observed metadata, not an accepted proof. Exact checker14145d47, inputsf992329f and author manifest53707774 remain unchanged.

CR1 — `verify01.py:45–49`, Reader.read cleanup: an earlier ordinary ValueError during real descriptor read is re-raised even when the actual descriptor close subsequently raises MemoryError or SystemExit. The later first fatal is only attached as `secondary_close_failure` and suppressed as the propagated exception. Both real close callbacks close the actual descriptor before raising; no descriptor leak is asserted. Correct cleanup must choose the earliest genuine fatal across primary and all cleanup objects, otherwise preserve ordinary precedence, and retain secondary objects without unsafe diagnostics.

CR2 — `verify01.py:57–61`, Reader.tree plain scandir context: with a genuine opened iterator, original KeyboardInterrupt plus later close SystemExit escapes SystemExit; original MemoryError plus close ValueError escapes ValueError. Iterator is actually closed. A plain context-manager exit replaces the earlier fatal. Explicitly attempt iterator cleanup once under the same primary/fatal precedence policy and retain all objects. Root/new source bodies must remain unchanged until separate reviewed successor adoption.

CR3 — `verify01.py:280–281`, public exception diagnostic: the exact extracted exception handler calls str(error), JSON formatting and print before bare raise without protection. Hostile KeyboardInterrupt.__str__ raising SystemExit replaces the original; original MemoryError with a printing OSError also escapes the latter. These are source-handler controls, not an executed public checker or fabricated outcome. Guard all diagnostic work so it cannot replace the selected original fatal; secondary diagnostic failures must remain inspectable. Do not add string/repr/add_note hooks to solve retention.

Independent positive reconstruction:16,989 assertions across1,671 distinct regular paths/83,823,385B authenticate all ten old failed flat scopes, all three original Git-object flat scopes and both new flat scopes with complete canonical compressed reconstruction. The whole original capsule588typed/475bodies, current589typed,585 protected original metadata entries and four exact new source bodies join. Exact194 historical/195 target path maps preserve191 unchanged paths. All385 original plus9 new logical objects have type/extent/SHA256/GitOID checks, complete typed parent/tree/blob reachability, canonical slash-aware tree ordering and all340 current tracked body/executable-mode joins. Three FAILED claims/highest19 remain. All actual declared recovery-receipt refs, selected external blobs and installed closure metadata are additionally authenticated.

This independent read scope is explicitly different from Root's1,727 distinct files/84,824,406B: it reconstructs the complete substantive body/Git composition and selected ancillary receipts through separate code, and does not claim an identical invocation/read-cache population or perform every author assertion. The35 receipt subset alone is not used as a substitute for the83.82MB body reconstruction. Full semantic admission/proof release remains withheld despite these successful byte joins.

Original Root measurement source/inputs/stdout/empty stderr/observed exit0 and current child absence authenticate. No current actual state/checkpoint tensor is deserialized; opaque bodies are only hashed and reconstructed. No numerical imports, network, Git process/mutation, restore operation, research claim or current-source edit was used. The independent reconstruction does not rerun the author run/main.

Author negative controls remain intact. FIFO and symlink are only typed/literal metadata checked; hardlinked regular fixtures and the4MiB+1 extent-negative body are not opened by the bounded positive reader. Their modes/extent/nlink/inode metadata and author declared seals are retained, without falsely claiming independently hashed negative contents. RECONSTRUCT01 first refused the over-cap negative fixture; the script/traceback remain. RECONSTRUCT02 separates those nonadmitted fixtures and passes; RECONSTRUCT03 adds ancillary receipt joins. Its old machine status suffix mentions CR1_CR2 because it predates the separate CR3 witness; this final review includes all three.

Necessary successor scope is narrow: shared explicit first-fatal-safe descriptor/iterator cleanup plus primary-safe public diagnostic publication, retaining all genuine source/maps, finite read caps, byte/hash/tree checks, original source/claim provenance and exclusion flags. Require exact literal/AST inverse outside those declared seams; replay real CR1/CR2/CR3 RED→GREEN, cleanup-object retention and finite controls. The unchanged scientific method/model/training/runtime/claims are not migration targets. Any later accepted proof must be genuinely authored after the corrected source and complete actual composition review, with literal receipt copies under its sealed descendant directory. No proof file or placeholder accepted authority is created here.

Exclusions remain BYTE plus original-mode metadata only: no POSIX/runtime-package/unrelated-store recovery, continuous writer exclusion, complete numerical capacity, new gate/admission/native grant, or paper credit.
'''
(H/'REPORT01.md').write_text(report)
m={'schema_version':1,'decision':'WITHHELD_CR1_CR2_CR3_COMPOSED_PROOF','source_sha256':sha((A/'verify01.py').read_bytes()),'author_manifest_sha256':sha((A/'MANIFEST01.json').read_bytes()),'inputs_sha256':sha((A/'INPUTS01.json').read_bytes()),'actual_measurement_sha256':sha((D/'ROOT_MEASUREMENT01.json').read_bytes()),'actual_stdout_sha256':sha((D/'MEASURED01.stdout').read_bytes()),'actual_observed_exit':0,'source_commit':'7b056a574e3e7b3c7ba209a39ee6a615e649d60c','policy_sha256':'ae8fbdc9d13e75fc453b70b5ee633c89fb4577e9b68a35b4147cf1bbd58c6887','checker_sha256':'d0d770b45def89e8e00e81fa1bbb35416034eaace5ecab0f15193fd43b7a32d8','historical_map_sha256':'ebb1727ccb55678aead9f0d5b5ee43ec81a46019c7fbb13c4b4f76144507bbca','target_map_sha256':'2e281f7ca64a12be316424d8e93b0eab28ba0d121214e79ada7249c96930b040','assertions':r['assertions'],'independent_files':r['distinct_regular_files_read'],'independent_bytes':r['bytes_read'],'actual_root_files':1727,'actual_root_bytes':84824406,'independent_read_scope_identical_to_author':False,'complete_substantive_body_git_composition_reconstructed':True,'recovery_proof_sha256':None,'recovery_proof':None,'numerical_authority':False,'findings':['CR1 later first fatal suppressed by ordinary Reader.read primary','CR2 iterator close replaces earlier fatal','CR3 public exception diagnostics replace original fatal'],'witness01_sha256':sha((H/'WITNESS01.json').read_bytes()),'witness02_sha256':sha((H/'WITNESS02.json').read_bytes()),'reconstruction_sha256':sha((H/'RECONSTRUCTION03.json').read_bytes()),'report_sha256':sha((H/'REPORT01.md').read_bytes())}
(H/'MACHINE01.json').write_text(json.dumps(m,indent=2,sort_keys=True)+'\n');rows=[]
for p in sorted(H.rglob('*')):
 if p==H/'MANIFEST01.json':continue
 s=p.lstat();z={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):z['kind']='directory'
 elif stat.S_ISREG(s.st_mode):z.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()))
 else:raise AssertionError(p)
 rows.append(z)
(H/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'members':rows,'exclusion':'self only; all positive reconstruction code/raw failures and fatal witnesses retained'},indent=2,sort_keys=True)+'\n');print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'witness01':m['witness01_sha256'],'witness02':m['witness02_sha256'],'report':m['report_sha256'],'members':len(rows)}))
