import ast,copy,hashlib,json,stat
from pathlib import Path
H=Path(__file__).resolve().parent;B=H.parent;N=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');O=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-recordfix-native-20261004-01/source');OLDID='financial-wrapper-classification-eager-interrupt1-recordfix-20261004-01';NEWID='financial-wrapper-classification-eager-interrupt1-claimedrun-20261004-01';checks=[]
def sha(b):return hashlib.sha256(b).hexdigest()
def check(v,n):
 if not v:raise AssertionError(n)
 checks.append(n)
def read(p):
 s=p.lstat();check(stat.S_ISREG(s.st_mode) and p.resolve()==p and s.st_size<=4194304,'exact canonical bounded '+p.name);b=p.read_bytes();t=p.lstat();check((s.st_dev,s.st_ino,s.st_mode,s.st_size,s.st_mtime_ns,s.st_ctime_ns)==(t.st_dev,t.st_ino,t.st_mode,t.st_size,t.st_mtime_ns,t.st_ctime_ns),'stable '+p.name);return b
origins={'actual-old-claim.json':O/'research_runs'/OLDID/'claim.json','actual-old-gate.json':O/'fixture_inputs/financial_wrapper_recordfix01/gates.json','actual-new-gate.json':N/'fixture_inputs/financial_wrapper_claimedrun01/gates.json','actual-admission.py':N/'tradingagents/research/admission.py','actual-lifecycle.py':N/'tradingagents/research/lifecycle.py','actual-verify.py':N/'tradingagents/research/verify.py','frozen-verifier03.py':B/'financial-genuine-wrapper-first-outcome-verifier-preparation03-2026-10-04/verifier01.py'};pins={}
for name,p in origins.items():raw=read(p);(H/name).write_bytes(raw);pins[name]={'origin':str(p),'sha256':sha(raw),'bytes':len(raw)}
check(pins['actual-old-claim.json']['sha256']=='4c543d71fad5255be61087eaa3619d9e88cbbdc12fa1398bd7fa7fe6fb75c128','genuine oldclaim exact');check(pins['actual-old-gate.json']['sha256']=='4474df26460aab41281bfdcc311129b613a90d76963e853858841200d9faa69a','actual originalgate exact');check(pins['actual-new-gate.json']['sha256']=='3a20293832fa7ecc5e2821fb27dc940d1a997ab7f2ad373bc28f73e893e8781a','actual newgate exact');check(pins['frozen-verifier03.py']['sha256']=='f6626d0a66dba46e6b4a314c4806a0452844fda886375f5e99e99186b2ceaa56','exact frozenverifier03')
claim=json.loads((H/'actual-old-claim.json').read_bytes());old=json.loads((H/'actual-old-gate.json').read_bytes());new=json.loads((H/'actual-new-gate.json').read_bytes());exp=old['experiments'][OLDID];newexp=new['experiments'][NEWID]
check(claim['experiment']==exp,'actual claim contract exact');check(claim['windows']!=exp['windows'],'actual RED direct windows equality refuses genuine claim');check(claim['windows'][0]['availability']==exp['windows'][0]['availability']=='existing','availability is preserved, not replaced')
# Exact code assignments from genuine verifier, no verify_claim/admit/Run call.
fn=next(n for n in ast.parse((H/'actual-verify.py').read_bytes()).body if isinstance(n,ast.FunctionDef) and n.name=='verify_claim');assignments=[n for n in fn.body if isinstance(n,ast.Assign) and isinstance(n.targets[0],ast.Name) and n.targets[0].id in ('windows','exposures')];check(len(assignments)==2,'two genuine verifier expansion assignments')
ns={'registered':old,'exp':exp};exec(compile(ast.Module(body=assignments,type_ignores=[]),'<actual verifier pure window expansion>','exec'),ns);check(claim['windows']==ns['windows'] and claim['prior_exposures']==ns['exposures'],'actual GREEN genuine verify expansion matches')
# Independent pure expected function: original gate only, no future receipt.
def expected_claim_window_fields(registered,experiment):
 return {'windows':[{**w,'identity':registered['datasets'][w['dataset']]['identity'],'state':'spent' if experiment['stage']=='confirmation' else 'exposed'} for w in experiment['windows']], 'prior_exposures':[{**item,'identity':info['identity']} for info in registered['datasets'].values() for item in info['exposures']]}
expected=expected_claim_window_fields(old,exp);future=expected_claim_window_fields(new,newexp);check(expected=={'windows':ns['windows'],'prior_exposures':ns['exposures']},'independent matches literal actual function');check(future==expected,'next registered expansion same exposed synthetic administrative windows');check(not (N/'research_runs'/NEWID).exists(),'no actual next claim exists')
# Actual inherited verifier guard, evaluated only with existing genuine metadata.
vast=ast.parse((H/'frozen-verifier03.py').read_bytes());guard=next(n for n in ast.walk(vast) if isinstance(n,ast.Call) and isinstance(n.func,ast.Name) and n.func.id=='require' and len(n.args)>1 and isinstance(n.args[1],ast.Constant) and n.args[1].value=='claim unbound initial windows');check(eval(compile(ast.Expression(guard.args[0]),'<actual inherited window guard>','eval'),{'claim':claim,'e':exp}) is False,'whole original guard false on actual old claim')
check(claim['schema_version']==1 and claim['bindings'] is None and claim['bindings_sha256'] is None,'schema/unbound siblings pass; windows is exact failure')
# Original admission append's exact expansion matches reconstructed verifier.
atree=ast.parse((H/'actual-admission.py').read_bytes());append=next(n for n in ast.walk(atree) if isinstance(n,ast.Call) and isinstance(n.func,ast.Attribute) and isinstance(n.func.value,ast.Name) and n.func.value.id=='windows' and n.func.attr=='append');assembled=[eval(compile(ast.Expression(append.args[0]),'<actual admission window value>','eval'),{'window':w,'info':old['datasets'][w['dataset']],'exp':exp}) for w in exp['windows']];check(assembled==claim['windows'],'exact admission append matches actual old windows')
ltree=ast.parse((H/'actual-lifecycle.py').read_bytes());claimexpr=next(n.value for n in ast.walk(ltree) if isinstance(n,ast.Assign) and any(isinstance(t,ast.Name) and t.id=='claim' for t in n.targets) and isinstance(n.value,ast.Dict));fields={k.value:ast.unparse(v) for k,v in zip(claimexpr.keys,claimexpr.values) if isinstance(k,ast.Constant)};check(fields['windows']=='admitted.windows' and fields['prior_exposures']=='exposures','actual lifecycle preserves admitted windows')
mutations=[]
for field in ('identity','state','availability','dataset','start','end'):
 c=copy.deepcopy(claim['windows']);c[0][field]='wrong';check(c!=expected['windows'],'changed '+field+' refuses');mutations.append(field)
for field in claim['windows'][0]:
 c=copy.deepcopy(claim['windows']);del c[0][field];check(c!=expected['windows'],'missing '+field+' refuses')
check(claim['windows']+claim['windows']!=expected['windows'],'duplicate window refuses');check([]!=expected['windows'],'missing whole window refuses');c=copy.deepcopy(claim['windows']);c[0]['extra']='field';check(c!=expected['windows'],'unexpected added claim field refuses')
for stage,state in [('development','exposed'),('discovery','exposed'),('confirmation','spent')]:
 e=copy.deepcopy(exp);e['stage']=stage;check(expected_claim_window_fields(old,e)['windows'][0]['state']==state,'genuine stage-derived state '+stage)
check(claim['prior_exposures']==expected['prior_exposures'],'prior exposures exact');extra=copy.deepcopy(claim['prior_exposures']);extra[0]['identity']='wrong';check(extra!=expected['prior_exposures'],'wrong historical exposure identity refuses')
source=ast.get_source_segment(Path(__file__).read_text(),next(n for n in ast.parse(Path(__file__).read_text()).body if isinstance(n,ast.FunctionDef) and n.name=='expected_claim_window_fields'))+'\n';(H/'expected_window_fields01.py').write_text(source)
out={'decision':'CONFIRMED_WINDOW_COMPARISON_DEFECT','checks':len(checks),'check_names':checks,'verifier_sha256':pins['frozen-verifier03.py']['sha256'],'verifier_guard_line':guard.lineno,'actual_old_claim_windows':claim['windows'],'actual_old_experiment_windows':exp['windows'],'actual_old_prior_exposures':claim['prior_exposures'],'expected_next_registered_window_fields':future,'actual_next_claim':None,'fake_claim_created':False,'admission_or_run_called':False,'corrective_requirement':'Compare actual claim windows to complete ordered gate-derived expansion preserving every original field and adding dataset identity and stage-derived state. Also retain exact prior_exposures comparison consistent with genuine verify_claim; preserve schema/bindings/source/registration/cumulative/cleanup checks. No lifecycle/admission mutation or stripping identity/state/availability.','evidence_origins':pins};(H/'READBACK01.json').write_text(json.dumps(out,sort_keys=True,indent=2)+'\n');print(json.dumps({k:v for k,v in out.items() if k not in ('check_names','evidence_origins')}))
