import hashlib,json,stat,datetime
from pathlib import Path
H=Path(__file__).resolve().parent;sha=lambda b:hashlib.sha256(b).hexdigest()
def put(n,v):(H/n).write_text(json.dumps(v,sort_keys=True,indent=2,allow_nan=False)+'\n')
x=json.loads((H/'controls02/READBACK01.json').read_text());y=json.loads((H/'SUCCESSOR_CONTROLS01.json').read_text());f=json.loads((H/'FRAMING04.json').read_text())
put('MACHINE01.json',{'schema_version':1,'decision':'accepted-source-only-fixed17-remote-and-restore02','reviewer':'combined_worker_review independent of Root source author','timestamp_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'remote_sha256':'b03a2c296d122f95f395c02fa1821df25d246d3d21ce93a28560a953f2335879','original_restore_sha256':'6af39be9f02e21e14b8409b312165ecb3e8e622f2243b42dfc2553b9781c6695','original_restore_disposition':'WITHHELD_BR1_DESTINATION_ABSENT','successor_restore_sha256':'8b010b28e37978c6ea24eb0e4aaad68d715f4031a102d7396f4627fd501d06e1','successor_inverse_sha256':'176b20e48f7c955438a0f6da1c99fe23f27420eb54055c97b944a56b8a4c49f5','full_literal_AST_inverses':True,'unchanged_primitives':3,'fixed_selected_bodies':17,'fixed_selected_bytes':5320678,'remote_operations':45,'scopes':6,'combined_flat_logical_bytes':19101427,'original_git_objects':385,'original_git_object_bytes':7807097,'offline_git_operations_if_complete':392,'git_operations_cap':400,'deadline_qualification':'180s checked between outer operations; genuine boundedGit has10s per child and actual R4 finite parsing; not an independently preemptive whole-process clock','current_source':'9dc5c79f738920b52947b4e63fed0397f1b5b207','capture_sha256':'7d65c2bac832832df5d62d49a41b31b7d54b33b52a448d048cd94b9541f8a176','checks':{'corrected_metadata_original_controls':x['checks'],'successor_tiny_controls':y['checks'],'actual_fixed_framing_members':sum(v['members'] for v in f['scopes']),'actual_fixed_framing_regular':sum(v['opaque_regular'] for v in f['scopes']),'actual_root_receipt_mode_rows':7},'actual_tiny_Git_objects':3,'actual_tiny_Git_successful_ops':10,'malformed_actual_Git_refusal':True,'real_current385_reconstruction_performed':False,'current_remote_receipt':None,'current_external_commit_selection':None,'actual_Root_restore':None,'final_request_release':None,'source_Main_CAP_Parent_registry_mutation':False,'network_or_numerical_import':False,'genuine_handle_or_claim':False,'installed_runtime_or_POSIX_tree_or_capacity_authority':False,'raw_failure_retained':{'script':'check01.py','stderr':'CHECK01.err','cause':'reviewer expected later ordinary error rather than genuine CleanupFailure carrying both ordinary exceptions; separate controls02/check02 corrects this expectation; original BR1 real failure remains source defect'},'scope_qualification':'source approval applies only fixed17 exact selected scope and exact captured six manifests; generic supplemental selection support not granted'})
report='''# Complete100 baseline recovery source review

**Accepted source-only:** fixed17 remote b03a2c29 and corrected flat caller restore02/8b010b28. **Original restore01/6af39be9 remains WITHHELD_BR1**. No actual recovery entrypoint, remote action, original Git reconstruction, native work or admission was invoked.

BR1: original restore01.py line76 passes an absent destination to R.restore. Its own fresh check requires those directories absent, while unchanged recovery04.FlatOutput.begin requires an already-existing private0700 directory. Actual tiny opaque R.pack→R.restore reproduces FileNotFoundError with destination still absent. The caller would stop after FLAT_INTENT and before first-scope restoration. Root's separately preserved restore02 adds exactly destination assignment/mkdir0700 and passes that directory to the unchanged restorer. Complete byte and AST inverse restores6af. Executing those exact corrected statements against a tiny canonical archive succeeds; repeating them refuses FileExistsError. The original predecessor and first earlier API/fatal errata drafts remain in evidence.

Remote b03a has a complete four-edit byte/AST inverse to accepted original b1b661. Child management, deadlines, first-fatal selection, all cleanup attempts, exclusive writes/readback and actual remote HEAD/OID/size/hash joins are unchanged. The fixed17 bodies total5,320,678 bytes and imply45 Git operations (11+2N), within506paths/64MiB logical/4MiB per body/1024calls/10GiB floor. Five malformed/missing/duplicate/path/hash controls refuse. Acceptance is limited to the exact17-body release; the inherited generic validator can support supplemental rows, which this review does not grant. The actual committed remote selection and receipt remain unavailable.

The six exact manifests bind19,101,427 logical bytes. All six actual archives were parsed read-only through the original framed parser, comparing every member's order/type/mode/length/hash with the exact manifest; no current Source body was restored or interpreted. This tests fixed archive compatibility, not a general cure for historical PAX corner cases. Seven original Root receipts are0664 and their captured private bodies0600. Sidecar17b9baf9 and all seven current original hashes/modes explicitly preserve that mapping; no literal POSIX-mode equality is claimed.

The Git index is fixed to385 unique original reachable objects/7,807,097 raw bytes and Source9dc5. The caller authenticates restored type/size/SHA256 and original Git SHA1 framing, writes each through genuine bounded offline Git, then joins HEAD, fsck, current339 names and complete reachable object census. Exact success denominator is392 operations (init+385writes+update-ref+symbolic-ref+rev-parse+fsck+ls-tree+rev-list), below400. Original helper per-child timeout10s, outer180s boundary checks, per-body4MiB and10GiB floor are unchanged; the outer deadline is checked between operations, not claimed to be an independent preemptive timer. Actual19.1MiB fixed flat logical scope is below64MiB; no universal allocated-storage or future whole-fit capacity follows.

A separate tiny ordinary Git fixture used the same genuine helper to reconstruct three objects, verify exact blob/tree/commit OIDs, fsck, current tree and complete reachable census. Ten commands succeeded; genuine Git refused a malformed tree. This is an offline source-API control only; the385 original objects have not been freshly reconstructed by this reviewer.

Nine actual extracted entry cleanup pairs verify original first fatal preservation, later fatal selection over ordinary failure and ordinary CleanupFailure retaining both causes; all journal attempts occur. The first reviewer harness incorrectly expected the later ordinary exception directly, rather than the genuine uncertainty wrapper. Its full traceback/partial fixtures are retained. Separate corrected controls pass; no source fix or suppression was attributed to that harness error. Original-R4 cleanup and all three pinned primitive bodies remain unchanged.

The remote and flat entrypoints still require a genuine actual selected-remote receipt and pins. No fake receipt, Owner, Admission or scientific claim was created. The local baseline is explicitly prelaunch: the final request/release are not captured and require a separate recovered supplement and independent exact release. Root alone owns actual remote/flat work and its independent outcome review. Actual runtime packages, POSIX instantiation, continuous race immunity, empirical performance, financial accounting, scientific tensor/cursor checks and100-epoch resource feasibility were not tested. All original FAILED claims and1420 pending paper fits remain unchanged.
'''
(H/'REPORT01.md').write_text(report)
rows=[]
for p in sorted(H.rglob('*')):
 s=p.lstat();r={'path':str(p.relative_to(H)),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):r['kind']='directory'
 elif stat.S_ISREG(s.st_mode):b=p.read_bytes();assert len(b)<=4194304;r.update(kind='file',bytes=len(b),sha256=sha(b))
 else:raise AssertionError('unexpected owned evidence type')
 rows.append(r)
put('MANIFEST01.json',{'schema_version':1,'self_excluded':'MANIFEST01.json','scope':'complete independent original-withheld and corrected-successor source review including all tiny Git/failed harness evidence','members':rows,'counts':{'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'logical_bytes':sum(r.get('bytes',0) for r in rows)}})
for r in rows:
 p=H/r['path'];assert stat.S_IMODE(p.lstat().st_mode)==r['mode']
 if r['kind']=='file':assert sha(p.read_bytes())==r['sha256'] and p.stat().st_size==r['bytes']
print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'report':sha((H/'REPORT01.md').read_bytes()),'members':len(rows),'files':sum(r['kind']=='file' for r in rows),'bytes':sum(r.get('bytes',0) for r in rows)}))
