import ast,hashlib,importlib.util,json,os,shutil,stat,sys
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;C=F/'financial-genuine-wrapper-root-preservation06-2026-10-04';V=F/'financial-genuine-wrapper-first-attempt-closure-review01-2026-10-04';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-root-launch-20261004-01');S=P.parent/'genuine-financial-wrapper-native-20261003-01/source';outer=F/'financial-genuine-wrapper-root-first-launch01-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
b=(C/'capture06.py').read_bytes();ck(sha(b)=='4f849700c45c5d4b35009988d91e0aeaed72084c2fce39ab3404aeabd8069a06','exact source06');tree=ast.parse(b);pins=next(ast.literal_eval(n.value) for n in tree.body if isinstance(n,ast.Assign) and any(isinstance(x,ast.Name) and x.id=='PINS' for x in n.targets))
for n,h in pins.items():ck(sha((U/n).read_bytes())==h,'exact acceptedprimitive')
sys.path.insert(0,str(U));sp=importlib.util.spec_from_file_location('failedcapture_review',U/'recovery04.py');R=importlib.util.module_from_spec(sp);sp.loader.exec_module(R)
def read(p):return R.read(p.parent,p.name)
def doc(p):return json.loads(read(p))
ck(sha(read(V/'MANIFEST01.json'))=='192a6a838e5561b77e3192c33b5fa00260d33ffd260b27c7046c7c63eef190bc','genuine independentclosure manifest');m=doc(V/'MANIFEST01.json');ck({p.name for p in V.iterdir()}=={r['path'] for r in m['entries']}|{'MANIFEST01.json'},'complete frozen closure evidence')
for r in m['entries']:ck(sha(read(V/r['path']))==r['sha256'] and len(read(V/r['path']))==r['bytes'] and stat.S_IMODE((V/r['path']).stat().st_mode)==r['mode'],'all actual closure proofbodymode')
closure=doc(V/'READBACK01.json');ck(closure['decision']=='ACCEPTED_FAILED_OUTER_ATTEMPT_CLOSED_NO_NUMERICAL_CLAIM' and closure['claim_count']==0 and closure['outer_attempt_permanently_reserved'] is True,'closed reserved no numericalclaim');targets=[('source',S,878,'SOURCE'),('parent',P,30,'PARENT'),('outer',outer,8,'ROOT_CALLER')];manifests={}
for label,root,count,priorlabel in targets:
 m=doc(C/(label.upper()+'_MANIFEST01.json'));ck(m==R.scan(root)==doc(V/(priorlabel+'_MANIFEST01.json')) and len(m['members'])==count,'exact full actual '+label);R.validate(m);manifests[label]=m
ck(sum(r.get('bytes',0) for m in manifests.values() for r in m['members'])<=R.BASE and shutil.disk_usage(C).free>=R.FLOOR,'actual fullthree combinedbounds/observedfloor');ck(all(not C.is_relative_to(root) and not root.is_relative_to(C) for _,root,_,_ in targets),'allarchives outside originalscopes');terminal=doc(P/'attempt/parent-terminal.json');actual=doc(outer/'ACTUAL_TERMINAL01.json');ck(sha(read(P/'attempt/parent-terminal.json'))==closure['parent_terminal_sha256'] and sha(read(outer/'ACTUAL_TERMINAL01.json'))==closure['root_terminal_sha256'],'exactclosed actual original exit joins')
main=next(n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name=='main');text=ast.unparse(main)
def predicate(message):return next(n for n in ast.walk(main) if isinstance(n,ast.Call) and ast.unparse(n.func)=='R.require' and len(n.args)>1 and isinstance(n.args[1],ast.Constant) and n.args[1].value==message)
code=compile(ast.Expression(predicate('original pre-dispatch failed exit semantics')),'exact failedexitpredicate','eval');eval(code,{'R':R,'terminal':terminal,'actual':actual});ck(True,'exactactual NULL/1/sourcebound semantics accepted');refusals=[]
for name,t,a in [('coerced_original_exit',dict(terminal,actual_parent_exit=1),actual),('invented_success',terminal,dict(actual,actual_parent_exit=0)),('unknown_nodispatch',dict(terminal,cleanup=dict(terminal['cleanup'],source_bound_no_dispatch=False)),actual)]:
 try:eval(code,{'R':R,'terminal':t,'actual':a})
 except ValueError as e:refusals.append({'case':name,'error':str(e)})
 else:raise AssertionError('invalid exitsemantics accepted')
ck(len(refusals)==3,'three exact closuresemantic refusals');ck(text.index("'exact independent failed scope and capture-source review'")<text.index("'original pre-dispatch failed exit semantics'")<text.index("R.put(HERE / 'REQUEST01.json'")<text.index('R.pack(')<text.index("R.put(HERE / 'CAPTURE01.json'"),'review and authenticfailedscope before any write');ck("('source', SOURCE, 878), ('parent', PARENT, 30), ('outer', OUTER, 8)" in text and 'R.same(root, manifests[label])' in text and "not os.path.lexists(SOURCE / 'research_runs' / IDENTITY)" in text,'exact allthree targets/no actualclaim');ck("('INTENT01.json', 'CAPTURE01.json', 'REQUEST01.json')" in text and 'R.pack(root, manifests[label]' in text,'oneuse and unchanged exclusive writer');ck("'continuous_floor_watch_claim': False" in text and "'failed_identity_permanently_reserved': True" in text and "'original_parent_terminal_exit': None" in text,'truthful originalNULL/reserved/floor qualifications');ck(R.FILE==4*1024**2 and R.BASE==128*1024**2 and R.FLOOR==10*1024**3,'unchanged boundedprimitives')
ck(all(not (C/n).exists() for n in ['REQUEST01.json','INTENT01.json','CAPTURE01.json','complete-source01.tar.gz','complete-parent01.tar.gz','complete-outer01.tar.gz']),'actualsource06 neverexecuted');ck(all(R.scan(root)==manifests[label] for label,root,_,_ in targets),'allthree finalstable');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas','tradingagents'} for n in sys.modules),'no numerical/lifecycle import');out={'schema_version':1,'decision':'ACCEPTED_EXACT_FAILED_SCOPE_CAPTURE_SOURCE_ONLY','checks':len(checks),'source_sha256':sha(b),'closed_review_manifest_sha256':sha(read(V/'MANIFEST01.json')),'source':'d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0','identity':closure['identity'],'target_members':{k:len(v['members']) for k,v in manifests.items()},'target_manifest_sha256':{k:sha(R.encode(v)) for k,v in manifests.items()},'refusals':refusals,'actual_capture_executed':False,'numerical_claims':0,'native_noncreation_qualification':'source-order inference; no actual native property readback','failed_identity_permanently_reserved':True,'further_numerical_release_halted':True,'external_failedscope_recovery':False,'native_authority':False};(O/'READBACK01.json').write_bytes(R.encode(out));print(json.dumps(out,indent=2))
