from pathlib import Path
import hashlib,json,stat,os,datetime
H=Path(__file__).resolve().parent;B=H.parent;C=B/'heartbeat-root-checkpoint10-2026-10-04';D=B/'financial-wrapper-compatibility-operational-delta-root-remote03-2026-10-04';sha=lambda b:hashlib.sha256(b).hexdigest();draft=json.loads((D/'ROOT_FLAT04_INSTALLATION_DRAFT01.json').read_bytes());r=json.loads((H/'READBACK01.json').read_bytes());q=json.loads((H/'READBACK02.json').read_bytes())
copies=[(C,n,'caller/'+n) for n in ['root_operational_flat04.py','root_operational_flat05.py','ROOT_FLAT_CALLER05_LITERAL_EDITS01.json','ROOT_FLAT_CALLER05_SOURCE_INVERSE01.json','ROOT_FLAT_CALLER05_SOURCE_DIFF01.patch']]+[(D,n,'installed/'+n) for n in list(draft['helpers_and_metadata'])+['ROOT_FLAT04_INSTALLATION_DRAFT01.json','REMOTE_RECOVERY01.json','SELECTED_BODIES01.json','ROOT_REMOTE03_EXIT01.json']]
for dirname in ['financial-wrapper-compatibility-operational-delta-flat-entry-review04-2026-10-04','financial-wrapper-compatibility-operational-delta-flat-source-mode-review04-2026-10-04']:
 for n in ['MACHINE01.json','MANIFEST01.json','REPORT01.md']:copies.append((B/dirname,n,dirname+'/'+n))
for root,n,dest in copies:
 p=H/'evidence'/dest;p.parent.mkdir(parents=True,exist_ok=True);p.write_bytes((root/n).read_bytes())
report='''# Exact one-use operational flat entry05

**Accepted exactly one fresh flat-only invocation of caller05 on the completed remote03 receiver.** This is an entry release, not an actual restoration result. Original remote03 remains completed; remote replay and all numerical/research authority remain excluded.

Exact caller025a28c6 binds unchanged installed draft770f509c before parsing and binds installed helper17f4, all eight declared helper/metadata byte/mode pins, actual remote64c74556, selectiond2f64 and Rootexit0f0eba1a. The genuine source04 acceptancec1f124/c1ed84 and exact completed-input profiled238 remain intact. The full66-segment literal inverse reconstructs original withheld caller04 exactly, including AST equality after reversal. Original caller04, its genuine withheld review and actual descriptor/fatal witnesses remain immutable.

EF1 is corrected: exact old put under a real fdopen MemoryError leaks its descriptor; new put using pinned IO._opened closes that same owned descriptor and propagates the original fatal. Reviewer closes only the old control descriptor after inode verification. Both partial files are retained. Exact two-stdio context controls fail the second real fdopen and confirm both descriptors close while the primary KeyboardInterrupt survives.

EF2 is corrected:25 primary/secondary pairs exercise the actual finalbody and subsequent original primary propagation. KeyboardInterrupt/SystemExit/MemoryError primary precedence survives later final-publication failures; when no earlier fatal exists, the later fatal wins; ordinary cleanup uncertainty refuses via CleanupFailure. All actual secondary objects are retained in FAILURE_OBJECTS and terminal descriptors close. A real tiny isolated ordinary child is killed by the exact final cleanup code, reaped with SIGKILL and absent afterward while the original KeyboardInterrupt survives. This tiny control never invokes a Root helper or scientific process.

The current installed helper's pure component authenticates all15 selected records under the fixed observed seven-directory mode profile, and its terminal cohort rejoins. Receiver remains private0700; original selected0775/0700 input modes remain unchanged. Current whole-owned baseline:119members,4,004,543 logical/4,313,088 allocated bytes, disk free16,498,925,568B. No exact selected recover/restore executable appears in the contemporaneous process census. Both withheld04 and fresh05 outer names and all fixed flat result/intent/failure/output namespaces are absent. These are timestamped sampled observations; caller rechecks them immediately before entry.

Independent controls:165 assertions/28 case records, plus16 actual existing-name refusal cases and one wrong-body-pin refusal, and exact draft-before-parse AST check. CHECK02 stdout says16 for the combined count; that retained human-readable count is a reviewer typo. READBACK02 correctly contains17 refusal rows and this report/machine preserve the denominator. No failed control is hidden.

Scope: exactly the immutable two archives yielding33+31 opaque bodies and their two flat metadata files, using the accepted unchanged R4/owned IO/bounded Git/watch dependencies. Inner180-second/64-boundary limits and outer210-second/128-observation guard remain; per-file4MiB, whole64MiB logical/96MiB allocated and10GiB floor remain. The outer parent now records actual getrlimit(FSIZE); child inheritance is expressly a default-inheritance statement, not separate child readback. The count guard can stop earlier than the time ceiling; neither is a minimum execution entitlement.

Root alone may invoke caller05 once with this genuine MACHINE hash after fresh eligibility checks. Preserve every partial or failed namespace and actual Root/child exit independently. Final auxiliary sidecar is outside the helper's byte cohort and requires separate actual outcome authentication. No current actual flat receipt, composed recovery proof, POSIX/runtime reconstruction, continuous writer exclusion, whole capacity, economic/financial or numerical permission is asserted. Publication failure can leave partial terminal bytes; actual tool termination and retained exception evidence remain necessary to classify the outcome.
'''
(H/'REPORT01.md').write_text(report)
m={'schema_version':1,'decision':'ACCEPTED_EXACT_ONE_USE_OPERATIONAL_FLAT_ENTRY_ONLY','owned_root':str(D),'root_outer_caller_sha256':sha((C/'root_operational_flat05.py').read_bytes()),'installation_draft_sha256':sha((D/'ROOT_FLAT04_INSTALLATION_DRAFT01.json').read_bytes()),'flat_helper_sha256':draft['source_sha256'],'remote_receipt_sha256':draft['remote_receipt_sha256'],'selection_sha256':draft['selection_sha256'],'flat_execution_released':True,'remote_execution_released':False,'numerical_authority':False,'permitted_invocations':1,'actual_entry_started':False,'actual_flat_receipt':None,'source_review_machine_sha256':draft['source_review_machine_sha256'],'source_review_manifest_sha256':draft['source_review_manifest_sha256'],'fixed_outputs':['flat-operational-delta01','flat-failed-remote02-01'],'caller_path':str(C/'root_operational_flat05.py'),'checks':r['assertions'],'cases':len(r['cases']),'additional_refusal_rows':len(q['refusals']),'readback_sha256':sha((H/'READBACK01.json').read_bytes()),'predicate_readback_sha256':sha((H/'READBACK02.json').read_bytes()),'report_sha256':sha((H/'REPORT01.md').read_bytes()),'time':datetime.datetime.now(datetime.timezone.utc).isoformat(),'conditions':['Fresh exact caller predicates and resource/process/namespace recheck immediately before Root entry','No replay of remote03 or any existing namespace','Preserve all partial/failure evidence','Separate actual two-scope result/sidecar/Root terminal independent review required'],'limits':{'file_bytes':4194304,'logical_bytes':67108864,'allocated_bytes':100663296,'disk_floor_bytes':10737418240,'inner_seconds':180,'inner_boundaries':64,'outer_seconds':210,'outer_observations_guard':128},'qualification':'One ordinary BYTE flat entry only; finite sampled currentness, no continuous writer exclusion, POSIX/runtime/wholecapacity/scientific authority. Parent FSIZE readback distinct from unobserved child readback.'}
(H/'MACHINE01.json').write_text(json.dumps(m,indent=2,sort_keys=True)+'\n');rows=[]
for p in sorted(H.rglob('*')):
 if p==H/'MANIFEST01.json':continue
 s=p.lstat();z={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISDIR(s.st_mode):z['kind']='directory'
 elif stat.S_ISREG(s.st_mode):z.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()))
 else:raise AssertionError(p)
 rows.append(z)
(H/'MANIFEST01.json').write_text(json.dumps({'schema_version':1,'members':rows,'exclusion':'self only; every tiny partial diagnostic and all controls retained'},indent=2,sort_keys=True)+'\n');print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'machine':sha((H/'MACHINE01.json').read_bytes()),'report':m['report_sha256'],'members':len(rows)}))
