import ast,hashlib,importlib.util,json,os,shutil,stat,subprocess,sys,time
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;P=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-root-launch-20261004-01');S=P.parent/'genuine-financial-wrapper-native-20261003-01/source';C=F/'financial-genuine-wrapper-root-first-launch01-2026-10-04';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
ck(sha((U/'recovery04.py').read_bytes())=='b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','exact bounded metadata primitive');sys.path.insert(0,str(U));sp=importlib.util.spec_from_file_location('closed_review_R',U/'recovery04.py');R=importlib.util.module_from_spec(sp);sp.loader.exec_module(R)
def read(p):return R.read(p.parent,p.name)
def doc(p):return json.loads(read(p))
sm=R.scan(S);pm=R.scan(P);cm=R.scan(C);oldbase=F/'financial-genuine-wrapper-root-preservation05-2026-10-04';ck(sm==doc(oldbase/'SOURCE_MANIFEST01.json') and len(sm['members'])==878,'full originalsource878 unchanged');oldparent=doc(oldbase/'PARENT_MANIFEST01.json');oldrows={r['path']:r for r in oldparent['members']};rows={r['path']:r for r in pm['members']};ck(all(rows[n]==r for n,r in oldrows.items()),'originalfinal Parent23 unchanged');ck(set(rows)-set(oldrows)=={'attempt','attempt/intent.json','attempt/owned-tree-cleanup.json','attempt/parent-terminal.json','attempt/spawn.json','attempt/stderr','attempt/stdout'} and len(pm['members'])==30,'actual Parent30 sixfiles plusattemptdir');q=doc(P/'REQUEST_FINAL03.json');identity=q['identity'];H=q['source'];ck(sha(read(P/'REQUEST_FINAL03.json'))=='dc80a4dff93fbf3261bdf151076c1420630ed38926ab7094d60eb1902bde25bc' and H=='d4e56ba9ed968e9c24b2813656c2ca65a3dbd7a0' and identity=='financial-wrapper-classification-eager-interrupt1-20261003-01','exact original identity/source/request');parent=doc(P/'attempt/parent-terminal.json');cleanup=doc(P/'attempt/owned-tree-cleanup.json');spawn=doc(P/'attempt/spawn.json');intent=doc(C/'ROOT_INTENT01.json');terminal=doc(C/'ACTUAL_TERMINAL01.json');qual=doc(C/'INTENT_QUALIFICATION01.json');preflight=doc(C/'PREFLIGHT01.json');ck(terminal['actual_parent_exit']==1 and terminal['original_parent_terminal_actual_parent_exit'] is None and parent['actual_parent_exit'] is None and parent['actual_child_exit']==1 and terminal['original_parent_terminal_sha256']==sha(read(P/'attempt/parent-terminal.json')),'original parentNULL and separate actualexit1');ck(terminal['actual_exec_session']==67281 and terminal['actual_start_tool']=='22bda2' and terminal['actual_completion_tool']=='319ae9','actual original toolchain');ck(terminal['actual_stdout_sha256']==sha(read(C/'ACTUAL_LAUNCH01.out')) and terminal['actual_stderr_sha256']==sha(read(C/'ACTUAL_LAUNCH01.err')) and read(C/'ACTUAL_LAUNCH01.out')==read(C/'ACTUAL_LAUNCH01.err')==b'','actual outerstreams empty');error=read(P/'attempt/stderr');ck(len(error)==parent['supervisor_result']['stderr_bytes']==2049 and len(read(P/'attempt/stdout'))==parent['supervisor_result']['stdout_bytes']==0 and b'Unavailable: runtime installed RECORD unavailable' in error and b'_,job=_admitted(args)' in error,'original supervised traceback actualfailure');ck(parent['identity']==spawn['identity']==intent['identity']==identity and parent['source']==spawn['source']==intent['source']==H and spawn['argv']==preflight['actual_command'] and parent['supervisor_result']['exit_code']==1 and parent['supervisor_result']['pid']==spawn['pid']==163035,'genuine actual command owner joins');ck(parent['cleanup']['owned_tree_cleanup_sha256']==sha(read(P/'attempt/owned-tree-cleanup.json')) and cleanup['subreaper_used'] is True and cleanup['remaining_original_identities']==[] and cleanup['dedicated_no_preexisting_children'] is True,'actual original cleanupchain')
observed_pids=[]
for row in cleanup['owned_pid_start_records']:
 ck(row['pid']==163035 and row['ticks']=='13604837','exactoriginal process identity');ck(not Path('/proc',str(row['pid'])).exists(),'actualoriginal PID absent')
 for pid in [row['pid'],row['ppid']]:
  if pid not in observed_pids:ck(not Path('/proc',str(pid)).exists(),'actual originalchild/outer PID absent');observed_pids.append(pid)
 try:os.killpg(row['pgrp'],0)
 except ProcessLookupError:ck(True,'actualoriginal processgroup absent')
 else:raise AssertionError('original processgroup persists')
base=S/'research_artifacts/onchain-paper-replication-2026-09-24/runs'/identity;run=S/'research_runs'/identity;ck(not os.path.lexists(base) and not os.path.lexists(run) and all(not os.path.lexists(S/n) for n in ['research_runs','research_artifacts','fixture_outer']),'zero actual programclaims and no casebase');native_names=['live.json','final.json','cpu_ready.json','release.json','child.log'];ck(parent['cleanup']['stable_absent_native_records']==native_names and all(not os.path.lexists(base/'guard'/n) for n in native_names),'all five original nativepaths absent');ck(parent['cleanup']['source_bound_no_dispatch'] is True and parent['cleanup']['requires_independent_outcome_review'] is True and parent['outcome_semantics_accepted'] is False,'original conditional no-dispatch semantics preserved')
job=read(S/'tradingagents/research/onchain_replication/job.py');fw=read(S/'tradingagents/research/onchain_replication/financial_wrapper_fixture.py');resources=read(S/'tradingagents/research/onchain_replication/resources.py');jt=ast.parse(job);launch=next(n for n in jt.body if isinstance(n,ast.FunctionDef) and n.name=='launch');at=ast.unparse(launch);ck(at.index('_admitted(args)')<at.index('_base(args)')<at.index('subprocess.Popen('),'genuine sourceadmission precedes all casebase/native dispatch');worker=next(n for n in jt.body if isinstance(n,ast.FunctionDef) and n.name=='worker');ck('with ResearchRun.start(' in ast.unparse(worker),'claim only in later genuineworker');ck("distribution.files or ()" in fw.decode() and "str(f).endswith('.dist-info/RECORD')" in fw.decode() and "require(len(matches)==1,'runtime installed RECORD unavailable')" in fw.decode(),'exact observed failing predicate');ck(parent['cleanup']['existing_pre_dispatch_protocol_sha256']==doc(P/'PROTOCOL_PINS01.json'),'original sourceprotocol complete map')
for n,h in parent['cleanup']['existing_pre_dispatch_protocol_sha256'].items():ck(sha(read(S/n))==h==q['source_files'][n],'actual originalprotocol source unchanged')
ck(sha(read(C/'PREFLIGHT01.json'))==intent['actual_readonly_preflight_sha256'] and preflight['native_properties_before_release_observed'] is False and preflight['whole_fit_capacity'] is False,'genuine readonlypreflight qualified');ck(intent['native_properties_verified_by_original_guard_before_worker_release'] is True and qual['original_intent_preserved'] is True and 'not an observational proof' in qual['original_intent_native_properties_verified_field'],'original misleading TRUE explicitly disqualified');union=F/'financial-genuine-wrapper-final-actual-recovery-review01-2026-10-04';ck(sha(read(union/'MANIFEST02.json'))==intent['actual_union_manifest_sha256']=='2f22b5496a551524f94a19f4ca180351f3be929046ee3a7a31a63491a6b49e4d' and sha(read(union/'FLAT_READBACK02.json'))==intent['actual_union_readback_sha256']=='de4b59c019ba95128e6725fd9f08efeacc8f86ab1384c2d6f0a6046051c97515','original complete byteunion chain')
metadata=doc(O/'runtime_metadata03.out');ck(metadata['cwd']==str(S) and metadata['first_observed_failure']['name']=='setuptools' and metadata['first_observed_failure']['match_count']==17 and metadata['first_observed_failure']['direct_pinned_RECORD_hash_matches'] is True,'real matchedlaunchcwd metadata firstfailure')
# Bounded current cgroup directory names only; no native controls, no unit invented.
start=time.monotonic();stack=[Path('/sys/fs/cgroup')];visited=0;native_groups=[]
while stack:
 ck(time.monotonic()-start<10 and visited<32768,'bounded cgroup name census');d=stack.pop();visited+=1
 with os.scandir(d) as it:
  for entry in it:
   if entry.is_dir(follow_symlinks=False):
    p=d/entry.name
    if entry.name.startswith('onchain-replication-') and entry.name.endswith('.service'):native_groups.append(str(p))
    stack.append(p)
ck(not native_groups,'no current onchain native service cgroups observed')
# Exact active-job argv filter, no arbitrary command-string match; retain no unrelated arguments.
active=[];start=time.monotonic();seen=0
with os.scandir('/proc') as it:
 for entry in it:
  if not entry.name.isdigit():continue
  seen+=1;ck(seen<=32768 and time.monotonic()-start<10,'bounded current process census')
  try:
   with open(Path(entry.path)/'cmdline','rb') as f:argv=f.read(65537).split(b'\0')
  except (FileNotFoundError,ProcessLookupError,PermissionError):continue
  if b'tradingagents.research.onchain_replication.job' in argv and str(S).encode() in argv:active.append(int(entry.name))
  if str(P/'parent01.py').encode() in argv:active.append(int(entry.name))
ck(not active,'no actualselected job orparent process');free=shutil.disk_usage(S).free;ck(free>=R.FLOOR and sum(r.get('bytes',0) for m in [sm,pm,cm] for r in m['members'])<=R.BASE,'closed combined capture scope fits observed floor and128MiB');ck(R.scan(S)==sm and R.scan(P)==pm and R.scan(C)==cm,'allthree closed scopes stable afterinspection');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas','tradingagents'} for n in sys.modules),'no numerical lifecycle import');
for label,m in [('SOURCE',sm),('PARENT',pm),('ROOT_CALLER',cm)]: (O/(label+'_MANIFEST01.json')).write_bytes(R.encode(m))
out={'schema_version':1,'decision':'ACCEPTED_FAILED_OUTER_ATTEMPT_CLOSED_NO_NUMERICAL_CLAIM','checks':len(checks),'identity':identity,'source':H,'original_request_sha256':sha(read(P/'REQUEST_FINAL03.json')),'actual_parent_exit':terminal['actual_parent_exit'],'original_parent_terminal_actual_parent_exit':parent['actual_parent_exit'],'actual_supervised_child_exit':parent['actual_child_exit'],'root_terminal_sha256':sha(read(C/'ACTUAL_TERMINAL01.json')),'parent_terminal_sha256':sha(read(P/'attempt/parent-terminal.json')),'original_traceback_sha256':sha(error),'source_members':len(sm['members']),'parent_members':len(pm['members']),'root_caller_members':len(cm['members']),'attempt_regular_files':6,'observed_absent_original_pids':observed_pids,'current_selected_active_pids':active,'current_native_cgroup_matches':native_groups,'cgroup_directories_observed':visited,'native_noncreation':'source-order inference with absent original paths and process drainage; no actual native property readback exists','claim_count':0,'numerical_claim_spent':False,'outer_attempt_permanently_reserved':True,'planned_interrupt_reached':False,'checkpoint_available':False,'numerical_components_completed':0,'paper_fit_credit':0,'further_numerical_release_halted':True,'retry_refund_transfer_authorized':False,'metadata_diagnosis':metadata,'native_properties_observed':False,'actual_current_closed_capture_executed':False,'new_failed_scope_external_recovery':False,'disk_free_bytes':free};(O/'READBACK01.json').write_bytes(R.encode(out));print(json.dumps({k:v for k,v in out.items() if k!='metadata_diagnosis'},indent=2))
