# Actual baseline byte recovery accepted

The once-only fresh FLAT2 completed under the independently accepted caller04/USTAR successor. Actual Root session87078/start270020/completion1affab exited0; child1172174/startticks21840304 exited0 with no cleanup failures. Original actual_parent_exit remains null; the separate Root tool receipt supplies actual0. The parent and child are currently absent, as is the known child process group. No historical parent group or native cgroup path was invented.

One substantive reconstruction verified all323 restored bodies and374 typed archive members across the three scopes (262/303,14/16,47/55 files/members). Each private flat leaf, complete mapping, original mode metadata, ordered TAR header, body hash and full canonical USTAR/gzip re-encoding matches the actual selected archive. All44 externally recovered selected blobs/6,089,473 bytes/34 unique objects/132 Git operations remain authenticated. The complete eight original closed trees and260 body origins, including failed capture03 mode history and installed coalesced evidence, agree with their recovered bytes and original mode metadata. Empty original directories remain explicitly represented in metadata; no POSIX tree restoration is claimed.

The current Source32d57eac5ea14435cd9d4aeb3e3b04d98bf16c41 joins all605 typed members/491 regular bodies and original modes. All355 current committed blobs,354 registered pins and11 roles match; the gate is the sole excluded self-pin. The complete407-object byte composition reuses the exact accepted old589-member/394-object external recovery basis and authenticates all13 additional recovered object bodies/framing/index pins. The already independently reconstructed commit/tree ancestry is reused; no broad old Git reconstruction or scientific import was repeated. All ten Parent draft files match current originals, including caller424f13b6/requeste7579251 and seven helpers. Genuine source/input/runtime proofac1 and old recovery proofc5 remain literal. Runtime251RECORD evidence is metadata only. All three genuine FAILED claims/terminal hashes remain unchanged, highest actual claim budget19; the unused compatible reference has no claim.

The first flat attempt stays permanently FAILED with its original Root1/child-9/null field, exact169 retained prefix bodies and absent completion metadata. Those169 bodies were freshly hashed; original receiver membership and selected-mode history remain unchanged. Its census/publication and USTAR/PAX findings are retained in review01. This successful FLAT2 uses a distinct root and output names; it does not reclassify or overwrite the earlier attempt.

The composition pass completed16,494 checks over1,361 distinct files/61,383,747 bytes under the unchanged64MiB audit reader bound. A small terminal supplement joins actual startticks,10 outer and14 inner complete samples, current process absence and a fresh whole-root/floor observation. Original caller elapsed2.087486773 seconds is distinct from tool timing. Sampling and the owned-child pause do not prove general writer exclusion, atomic immutability or kernel quota. There were no new failing harnesses in this review; unexecuted or failed predecessor harnesses remain sealed in review01.

BASELINE_FULL_RECOVERY_PROOF01 is a genuine compact proof for this completed baseline BYTE and original-mode-metadata composition. Its review reference points to MACHINE01 without a hash cycle; the final manifest seals both. It excludes the genuinely later final Parent request/release/three-proof binding and final caller supplement, installed runtime package bodies, unrelated stores, POSIX reconstruction, whole-fit capacity and all numerical authority. Full final preclaim8MiB and final caller recovery must still be measured/authenticated after actual binding. No numerical experiment, claim, admission, restoration or network operation was executed by this reviewer.
