# Continuation launch outcome phase

The actual continuation launch terminated before research admission. The native guard recorded6,437,638,144 available bytes against the unchanged6,442,450,944-byte startup requirement: a4,812,800-byte shortfall. Actual pinned resources.py:523–529 checks this threshold before publishing release.json. The native launcher reports125, signal before release, workload_pid null; release.json and the research claim/fit/wrapper namespaces are absent. job.py:354 creates ResearchRun only behind the guarded worker, while job.py:468–472 records not_admitted when no claim exists. The genuine observer is not_admitted and its literal owner/evidence hashes join the original files.

No99 resumed optimizer updates, final checkpoint, exact reference comparison or continuation completion occurred. The original complete100 reference remains an accepted prior result, not this outcome. Financial accounting adds zero claims: the accepted one COMPLETE/three FAILED/four spent/highest20 basis is unchanged. The consumed Parent and native launch namespaces are nevertheless terminal preserved evidence, with no relaunch or reuse granted. No scientific paper fit or economic result is credited.

Actual Root session25715 terminated with exit1 (initial0f0a35/final584196); Parent supervisor child exit1 is independently recorded. Original actual_parent_exit and guard child_exit_code remain null. These nulls are not overwritten by the separate Root receipt or launcher125. Cleanup authenticates the actual before/stop/after control receipts, stopped unit and absent cgroup. All seven recorded PIDs and four recorded process groups are absent at readback. Native PID history is explicitly incomplete; no universal process-history proof is claimed. Actual3GiB memory high=max/swap0,4MiB file bound,two-CPU affinity,10GiB disk floor and sampled storage/time limits join the original registered controls. No cap or policy changed.

The complete changed Parent attempt15 files/18 typed entries and native run9 files/10 typed entries are pinned in OUTCOME_READBACK01. Source/runtime/public-preflight/current-recovery bases are reused within their accepted scope; no old payload, runtime matrix, numerical experiment or checkpoint deserialization was repeated. A reviewer harness first used the wrong Root receipt key; its original script/traceback and exact schema correction remain retained. This is a harness error, not a source or outcome defect.

This phase accepts the precise retained resource refusal and recorded cleanup. Fresh external byte recovery of the new evidence remains pending, in this same review. The phase seal is immutable; later capture/recovery files remain outside it. Not tested: numerical agreement, economic returns, timing leakage, fees/funding, exposure reuse, capacity, installed runtime body recovery, POSIX reconstruction or continuous writer exclusion.
