import ast,gzip,hashlib,importlib.util,io,json,os,shutil,stat,subprocess,sys,tarfile
from pathlib import Path
O=Path(__file__).resolve().parent;F=O.parent;ROOT=Path.cwd();P=F/'financial-genuine-wrapper-root-flat-recovery01-2026-10-04';D=P/'flat01';U=F/'held-consumer-final-recovery-preparation04-2026-10-03';REMOTE=F/'financial-genuine-wrapper-root-remote-recovery01-2026-10-03';S=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-native-20261003-01/source');H='868bfa6404a2c34d6e5b6e0932a2baf4b38eb370';sha=lambda b:hashlib.sha256(b).hexdigest();checks=[]
def ck(v,m):
 assert v,m
 checks.append(m)
for n,pin in {'recovery04.py':'b40e5f06a0fd57b689e44ae82afd73ca8fe6721c43400beefe992ec12b17c18a','owned_io.py':'09d1fbcc03f2c9303db95f34ca6c07ddb47bfdb49b35452f4cb6829a5d667aeb','bounded_git01.py':'db4a65a450bf9930abac04ab794539ebd952b07826d7314b4aea4e989dd9240f'}.items():ck(sha((U/n).read_bytes())==pin,'actual unchanged primitive '+n)
sys.path.insert(0,str(U));spec=importlib.util.spec_from_file_location('flat_review_primitives',U/'recovery04.py');a=importlib.util.module_from_spec(spec);spec.loader.exec_module(a)
def read(p):return a.read(p.parent,p.name)
def doc(p,pin=None):
 b=read(p);ck(pin is None or sha(b)==pin,'pin '+p.name);v=json.loads(b);ck(a.encode(v)==b,'canonical '+p.name);return v
old=doc(O/'MANIFEST01.json','53392323532cab1b158f8d0bd132752c6d02a21cfc89e273ce9d3b3478dcc204')
for row in old['members']:
 p=O/row['path'];ck(sha(read(p))==row['sha256'] and p.stat().st_size==row['bytes'] and stat.S_IMODE(p.stat().st_mode)==row['mode'],'prior immutable remote review retained')
r=doc(P/'RECOVERY01.json','cb1467a17c43890878174126dbd9640aced6ee17103e403a1395d5acd1733b68');ck(r['source']==H and r['remote_receipt_sha256']=='22d937c697bb23485e9f20ee6af3faa7caf2c80d4f2ef8aac1b91bd7551afba8' and r['independent_source_review_manifest_sha256']=='0b7b5f2788b90e7ab77ae674dce1410236b11474a271da1907d6fa3bcbb159cf','actual exact source receipt review pins');rr=doc(REMOTE/'REMOTE_RECOVERY01.json',r['remote_receipt_sha256']);prior=doc(O/'REMOTE_READBACK01.json');ck(rr['remote_commit']==prior['recovered_commit']=='cd54c7b8fad26b91d06917621c4862e77b73b2c8','separate actual external origin chain');ck(len(rr['selected_blobs'])==102 and len({x['path'] for x in rr['selected_blobs']})==102,'no duplicate remote rows')
for row in rr['selected_blobs']:
 b=read(REMOTE/'selected'/row['path']);ck(len(b)==row['bytes'] and sha(b)==row['sha256'] and hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest()==row['git_object'],'all102 actual remote originalpins retained')
B=REMOTE/'selected/research/onchain-paper-replication-2026-09-24/full_sources/financial-genuine-wrapper-root-preservation02-2026-10-04';cap=doc(B/'CAPTURE01.json',r['capture_sha256']);m=doc(B/'complete-manifest01.json',r['actual']['manifest_sha256']);q=doc(B/'REQUEST01.json',cap['request_sha256']);archive=read(B/'complete-source01.tar.gz');ck(sha(archive)==cap['archive']['sha256']==r['actual']['archive_sha256']=='497a0ae3c0aba9b5f8bb41e933bed878ba49adf759a880d8a338637d732d1af4' and len(archive)==cap['archive']['bytes'],'exact fetched archive');meta=doc(D/r['actual']['metadata_file'],r['actual']['metadata_sha256']);ck(meta['manifest']==m and meta['archive']==cap['archive'],'full actual flat metadata chain');mapping=meta['flat_members'];files={x['path']:x for x in m['members'] if x['kind']=='file'};ck(set(mapping)==set(files) and len(mapping)==len(set(mapping.values()))==533 and len(m['members'])==755,'complete533 body755members no missing duplicate');ck(set(mapping.values())=={f'body-{i:05d}.body' for i in range(533)},'exact flat ordinalbody names');ck({p.name for p in D.iterdir()}==set(mapping.values())|{'body-metadata.json'},'actual534files no extras');ck(D.resolve()==D and stat.S_IMODE(D.lstat().st_mode)==0o700 and D.lstat().st_uid==os.geteuid(),'actual private acquired root');flatbodies={};flatrows=[]
for n,leaf in mapping.items():
 p=D/leaf;s=p.lstat();ck(stat.S_ISREG(s.st_mode) and s.st_nlink==1 and stat.S_IMODE(s.st_mode)==0o600,'actual singlelink0600flat inode');b=read(p);row=files[n];ck(len(b)==row['bytes'] and sha(b)==row['sha256'] and read(S/n)==b,'flat original fullopaque body');flatbodies[n]=b;flatrows.append({'semantic_path':n,'flat_file':leaf,'bytes':len(b),'sha256':sha(b),'original_mode':row['mode'],'actual_mode':0o600,'observed_device':s.st_dev,'observed_inode':s.st_ino})
ck(stat.S_IMODE((D/'body-metadata.json').stat().st_mode)==0o600,'metadata0600');ck(a.scan(S)==m,'complete actualSourceGit metadata/body stablebefore')
# Independent bounded raw512/PAX decoder and exact full reconstruction from actual flat files.
p=F/'held-consumer-final-released-scope-capture-review01-2026-10-03/check01.py';tree=ast.parse(read(p));defs=[n for n in tree.body if isinstance(n,ast.FunctionDef) and n.name in ('decode','recode')];ck(len(defs)==2,'pure independentdecoder/recode');exec(compile(ast.Module(body=defs,type_ignores=[]),str(p),'exec'));decoded,framing=decode(archive,m);ck(all(decoded[n]==b for n,b in flatbodies.items()),'all decoded actualflat bodies');ck(recode(m,flatbodies)==archive,'fullcanonicalgzipTAR reconstructed from recoveredflat');ck(r['actual']['root_mode']==m['root_mode']==stat.S_IMODE(S.stat().st_mode),'rootmode semantic metadata original')
def git(args,data=None):
 x=subprocess.run(['git','--no-replace-objects','-c','protocol.allow=never','-C',str(S),*args],input=data,stdout=subprocess.PIPE,stderr=subprocess.PIPE,timeout=10,env={'PATH':'/usr/bin:/bin','GIT_CONFIG_GLOBAL':'/dev/null','GIT_CONFIG_NOSYSTEM':'1','GIT_OPTIONAL_LOCKS':'0','GIT_NO_LAZY_FETCH':'1','GIT_NO_REPLACE_OBJECTS':'1'});ck(x.returncode==0 and len(x.stdout)<=8*1024**2 and len(x.stderr)<=65536,'bounded originalsource literalGit');return x.stdout
ck(git(['rev-parse','HEAD']).decode().strip()==H,'actual unchanged current868');I=F/'financial-genuine-wrapper-installed-expectation-review01-2026-10-04';installed=doc(I/'READBACK01.json','654c84e1c98110d54bf4b5c91ec1ed2bb2f594b0bb800bdca3e8fe18148b92a6');rows={x['path']:x for x in installed['joined']};tree={}
for ent in git(['ls-tree','-r','-z',H]).split(b'\0'):
 if not ent:continue
 left,n=ent.split(b'\t');mode,typ,oid=left.decode().split();ck(typ=='blob','actual tracked regularGit');tree[n.decode()]={'git_mode':mode,'git_object':oid}
ck(set(rows)==set(tree)=={n for n in files if not n.startswith('.git/')} and len(rows)==243,'complete current243 recovered scope');codecount=0
for n,row in rows.items():
 b=flatbodies[n];ck(tree[n]['git_object']==row['git_object']==hashlib.sha1(b'blob '+str(len(b)).encode()+b'\0'+b).hexdigest() and tree[n]['git_mode']==row['git_mode'] and sha(b)==row['sha256'] and len(b)==row['bytes'] and files[n]['mode']==row['mode'],'recovered243 actualsourceOID/mode/body mapjoin')
ck(installed['implementation']==194 and installed['package']==149 and installed['auxiliary']==49 and sum(n.startswith('tradingagents/') for n in rows)==149,'actual19414949scope');ck(sha(flatbodies['fixture_inputs/financial_wrapper_expectation01/environment.json'])=='1ff7418a2b7c77300aea731cea5bba78277d323241ac0ec59f41f43207c66d87','exact historical expectation body');env=json.loads(flatbodies['fixture_inputs/financial_wrapper_draft01/environment.DRAFT.json']);ck(all(env[k] is None for k in ['torch_version','cuda_build','cuda_available']),'historicalNULL drafts unchanged');draft=json.loads(flatbodies['fixture_inputs/financial_wrapper_draft01/DRAFT01.json']);ck(len(draft['slots'])==18 and all(not x['admitted'] and x['actual_outcome'] is None for x in draft['slots']),'18unreserved actualdrafts')
t=doc(P/'ACTUAL_FLAT_TERMINAL01.json');intent=doc(P/'INTENT01.json');stdout=read(P/'FLAT01.stdout');stderr=read(P/'FLAT01.stderr');ck(t['exit']==0 and t['receipt_sha256']==sha(read(P/'RECOVERY01.json')) and t['stdout_sha256']==sha(stdout) and t['stderr_sha256']==sha(stderr) and not stderr and t['native_or_claim'] is False,'actual parent terminal stream joins');summary=json.loads(stdout);ck(summary['status']==r['status'] and summary['members']==755 and summary['regular_bodies']==533,'actualstdout membership');ck(intent['source']==H and intent['remote_receipt_sha256']==r['remote_receipt_sha256'] and intent['capture_sha256']==r['capture_sha256'] and not Path('/proc',str(intent['pid'])).exists(),'actual intent and completedPID absence');ck(sha(read(P/'restore_financial01.py'))=='24da8af5f01e902e83f01a840d31f7fb24671e818c95dd17f331fbac44bdeac3','actualunchanged caller');ck(a.scan(S)==m and git(['status','--porcelain','--untracked-files=all'])==b'' and git(['rev-parse','HEAD']).decode().strip()==H,'complete final source unchanged');ck(all(r['actual'][k] is False for k in ['instantiated_posix_tree','recovered_tree_git_join','runtime_package_bodies_recovered','outside_stores_recovered','research_authority']) and r['native_or_claim_started'] is False,'narrow nonauthority flags');free=shutil.disk_usage(P).free;ck(free>=a.FLOOR and r['free_bytes']>=a.FLOOR,'actual observed10GiBfloor');ck(not any(n.split('.')[0] in {'numpy','torch','scipy','pandas'} for n in sys.modules),'no numerical imports');out={'schema_version':1,'decision':'ACCEPTED_ACTUAL_CURRENT_FINANCIAL_SOURCE_ARCHIVAL_SCOPE_CLOSURE_ONLY','checks':len(checks),'source':H,'flat_receipt_sha256':sha(read(P/'RECOVERY01.json')),'remote_receipt_sha256':r['remote_receipt_sha256'],'actual_terminal_sha256':sha(read(P/'ACTUAL_FLAT_TERMINAL01.json')),'metadata_sha256':r['actual']['metadata_sha256'],'archive_sha256':sha(archive),'members':755,'regular_bodies':533,'actual_flat_files':534,'tracked_files':243,'implementation':194,'package':149,'auxiliary':49,'logical_bytes':sum(x['bytes'] for x in files.values()),'canonical_reconstruction_from_actualflat':True,'framing':framing,'disk_free_bytes':free,'actual_recorded_elapsed_seconds':r['elapsed_seconds'],'original_posix_tree_or_git_database_instantiated':False,'runtime_store_registration_native_authority':False,'flat_bodies':flatrows};(O/'FLAT_READBACK02.json').write_bytes(a.encode(out));print(json.dumps({k:v for k,v in out.items() if k!='flat_bodies'},indent=2))
