from pathlib import Path
import ast,hashlib,json,os,stat
H=Path(__file__).resolve().parent;B=H.parent
sha=lambda b:hashlib.sha256(b).hexdigest()
def put(n,v):(H/n).write_text(json.dumps(v,indent=2,sort_keys=True)+'\n')
a=json.loads((H/'AUTHENTICATION01.json').read_text());c=json.loads((H/'CHECKS01.json').read_text());r=json.loads((H/'REPLAY02.json').read_text());f=json.loads((H/'FINAL_SOURCE_CHECK02.json').read_text());source=(H/'storage_lease01.py').read_bytes()
put('MACHINE01.json',{'status':'IMPLEMENTED_SL1_SL2_SOURCE_CORRECTION_AWAITING_INDEPENDENT_REVIEW','source_sha256':sha(source),'original_source_sha256':sha((H/'storage_lease01.original.py').read_bytes()),'original_preparation_manifest':'4666b0d4745709a43326b8b2298be5cb8a8754800aceb9343b552a260ef8b250','original_withheld_review_manifest':'050bb158a3c6d1c3e38976afe3e115609237f6a1ac1007967c619e571ea3cae8','authentication_checks':a['checks'],'correction_checks':c['checks'],'adapted_deterministic_replay_assertions':r['checks'],'final_comment_inverse_checks':f['checks'],'executable_control_assertions_total':c['checks']+r['checks']+f['checks'],'failed_harness':'FINAL_INVERSE_FAILURE01.json/.err and final_inverse_failure01.py retained','prior_failed_rapid_rewrite_replay':'Preserved in original050bb complete tree; literal stderr copy retained here. Not a155-pass run.','new_source_changes':['new final descriptor-free metadata rejoin','census rejoin after all measured descendant descriptor/iterator cleanup','sample rejoin after floor/resource query','one final census after trailing boundary callback','check/reserve return final sample','future helper origin02 only','comment explicitly says stat fingerprint, not byte immutability'],'genuine_class_AST_unchanged':True,'original_source_or_five_utilities_modified':False,'numeric_imports_or_genuine_handles_executed':False,'actual_native_or_capacity_credit':False,'actual_remote_or_recovery':None})
prior=json.loads((B/'financial-batch-output-genuine-storage-lease-preparation01-2026-10-04/PROTOCOL01.json').read_text());prior['status']='CORRECTED_DRAFT_SOURCE_ONLY_NOT_RELEASED';prior['new_source_requirements']['helper_sha256']=sha(source);prior['new_source_requirements']['origin']='financial-batch-output-genuine-storage-lease-preparation02-2026-10-04/storage_lease01.py';prior['sample_semantics']={'byte_hashes':False,'atomic_snapshot':False,'kernel_quota':False,'continuous_inter_sample_protection':False,'finite_final_census_after_trailing_callback':True,'descriptor_free_metadata_rejoin_after_measurement_cleanup_and_resource_query':True,'returned_measurement':'final actual sampled totals','coincident_stat_fingerprints':'cannot detect same-size byte changes if all observed stat fields coincide; original source/target/content validators retain their own body checks','terminal_close':'closes lifetime lease descriptors; not a new archival proof of every future filesystem state'};put('PROTOCOL02.json',prior)
report=f'''# Storage lease successor02 — source preparation only

Exact original source92e5 and preparation4666 remain immutable WITHHELD_SL1_SL2 under independent review050bb/MACHINE24e45. The successor helper is `{sha(source)}`. No original utility, capsule, registration, Owner, Run, ledger or source body was changed.

SL1 is corrected by exactly one final `_sample` after the actual trailing boundary callback. `check` and `reserve` return that final sample, so a permitted reserved-file write by the trailing callback is included in returned logical/allocated totals. An unreserved write by the same callback refuses during that first operation. No user callback follows the final sample.

SL2 is corrected by `_rejoin`, a bounded metadata fingerprint sweep after census child/iterator cleanup. Every recorded directory and file is checked against its full sampled signature, including directory membership fingerprints, identity, mode, link count, extent, allocated blocks and modification/change clocks. A further sweep follows the sample's resource query. The sweep creates no descriptor or iterator and schedules no callback or cleanup. A later real child close that changes an earlier file's mtime now refuses in the first operation. There is no recursive scan-until-stable or infinite retry.

These are stat-fingerprint checks, not byte immutability. The original independent rapid same-size rewrite replay failed; its exact original complete tree, script and stderr are authenticated and preserved. The successor does not relabel it as155 passed. The adapted155-assertion replay explicitly changes mtime for a deterministic metadata-mutation control; the literal change is declared in REPLAY_ADAPTATION01. Same-size changed bytes with coincident observed fingerprints can still pass this utility. Original Target/Owner/source validators retain their separate content/ancestry checks. Concurrent changes after the final sampled stat, OS/filesystem quota behavior and continuous immunity remain unproved.

Exact oldRED/newGREEN SL1 and SL2 controls use newly owned opaque trees and actual file descriptors. Other controls cover truthful final counters, resource-query mutation, sampled allocated overrun/floor, first fatal and all actual lease descriptor closes, terminal refusal, retained partial bytes, role/grant predicates and no refund/reset. The final file differs from tested executable code by one comment only, verified AST-identical. There are {c['checks']} correction assertions,155 adapted replay assertions and5 final inverse/comment assertions; {a['checks']} authentication assertions verify complete original and review trees separately. They are utility/source checks, not financial experiments or full-capacity measurements. One reverse-order literal-inverse harness assertion failed after the comment edit; exact stderr/body/context are retained, then the corrected narrow-before-broad inverse passed. Full final literal and AST inverse are in INVERSE_FINAL02, with all genuine class code unchanged.

The original sparse4MiB+1 negative and lossless gzip remain in preparation01 unchanged and authenticated. It is nonadmitted offline evidence, not a production file/capacity claim. New controls use tiny scaled allocation/per-file predicates. Original hardlink and lexical-link groups are preserved; no original deletion or cleanup occurred.

The same entire-admission-root simultaneous producer/batch/output/codec/spool/recovered/diagnostic/journal/directory/scratch accounting, finite monotone exact-path reservations,10GiB floor,4MiB file ceiling, existing lower whole caps, first-fatal reducer, one-use namespace and held-transition ownership remain. GenuineLease class AST is unchanged; the new source-origin string is separately declared for future admission. Source339, financial grants and missing real grants still refuse. Outside-root Parent/transport/recovery paths receive no accounting credit. No genuine Owner/Run/Target, numerical arrays, claim, native job, network, upload, retirement or deletion authority was executed.

Different-author successor review and complete future source/grant/caller adoption, full writer instrumentation, original native whole watches, actual preservation/fresh recovery and measured full-population capacity remain required. No100-epoch or1,420-fit feasibility, scientific conversion agreement, financial returns, representation completion or disk freeing is established.
''';(H/'REPORT01.md').write_text(report)
entries=[]
for p in sorted(H.rglob('*'),key=lambda x:x.relative_to(H).as_posix()):
 if p==H/'MANIFEST01.json':continue
 s=p.lstat();row={'path':p.relative_to(H).as_posix(),'mode':stat.S_IMODE(s.st_mode)}
 if stat.S_ISLNK(s.st_mode):row.update(kind='symlink',target=os.readlink(p))
 elif stat.S_ISDIR(s.st_mode):row.update(kind='directory')
 elif stat.S_ISREG(s.st_mode):row.update(kind='file',bytes=s.st_size,sha256=sha(p.read_bytes()),nlink=s.st_nlink)
 else:raise AssertionError('unknown type')
 entries.append(row)
put('MANIFEST01.json',{'schema_version':1,'members':entries,'scope':'complete source-only successor02; excludes this manifest only'})
assert {p.relative_to(H).as_posix() for p in H.rglob('*') if p!=H/'MANIFEST01.json'}=={x['path'] for x in entries}
for row in entries:
 p=H/row['path'];s=p.lstat();assert stat.S_IMODE(s.st_mode)==row['mode']
 if row['kind']=='file':assert s.st_size==row['bytes'] and sha(p.read_bytes())==row['sha256'] and s.st_nlink==row['nlink']
 if row['kind']=='symlink':assert os.readlink(p)==row['target']
print(json.dumps({'manifest':sha((H/'MANIFEST01.json').read_bytes()),'source':sha(source),'machine':sha((H/'MACHINE01.json').read_bytes()),'report':sha((H/'REPORT01.md').read_bytes()),'members':len(entries),'files':sum(x['kind']=='file' for x in entries),'bytes':sum(x.get('bytes',0) for x in entries),'authentication_checks':a['checks'],'correction_checks':c['checks'],'replay_checks':r['checks'],'final_inverse_checks':f['checks']}))
