from pathlib import Path
import os,stat,json,hashlib,types,time
D=Path(__file__).resolve().parent;F=D.parent;O=F/'financial-wrapper-compatibility-coalesced-evidence-root03-2026-10-04';A=F/'financial-wrapper-compatibility-coalesced-evidence-outcome-review04-2026-10-04';C=F/'heartbeat-root-checkpoint10-2026-10-04';P=F/'financial-wrapper-compatibility-coalesced-evidence-correction04-2026-10-04';CAP=Path('/home/malecada/master_thesis/onchain-financial-isolation/genuine-financial-wrapper-claimedrun-native-20261004-02/source');checks=[];reads={};started=time.monotonic()
def h(b):return hashlib.sha256(b).hexdigest()
def sig(s):return [s.st_dev,s.st_ino,s.st_mode,s.st_nlink,s.st_size,s.st_mtime_ns,s.st_ctime_ns]
def ok(v,n):assert v,n;checks.append(n)
def read(p,pin=None):
 s=p.lstat();ok(p.resolve()==p and stat.S_ISREG(s.st_mode) and s.st_nlink==1 and s.st_size<=4194304,'canonical regular bound');b=p.read_bytes();ok(sig(p.lstat())==sig(s) and len(b)==s.st_size,'body current');ok(pin is None or h(b)==pin,'actual pin');reads[str(p)]={'sha256':h(b),'bytes':len(b),'mode':stat.S_IMODE(s.st_mode),'signature':sig(s)};ok(time.monotonic()-started<60,'bounded review');return b
def J(p,pin=None):return json.loads(read(p,pin))
prior=J(A/'MACHINE01.json','e267987ec088fcde40936aad9275967131521aa94b7db19fc3237409e629b6a6');seal=J(A/'MANIFEST01.json','2eb451cc119963749bc6ac3a2edaf089590b900de810625a888216bfe3f14b95');before=J(A/'READBACK01.json',prior['readback_sha256']);plan=J(A/'INSTALL_CANDIDATES01.json',prior['install_plan_sha256']);read(A/'REPORT01.md',prior['report_sha256'])
for n,x in plan['candidate_files'].items():ok(read(O/n,x['sha256'])==read(Path(x['source']),x['sha256']) and (O/n).stat().st_size==x['bytes'] and stat.S_IMODE((O/n).stat().st_mode)==0o600,'exact installed candidate body/mode')
observed=J(C/'COALESCED_CANDIDATES_INSTALL04_OBSERVED01.json','ef49531c539c1845b864ddadf16e97d7bd65bb449f7ed582d3e7e6be0c1be295');exit=J(C/'COALESCED_CANDIDATES_INSTALL04_ACTUAL_TOOL_EXIT01.json');intent=J(C/'COALESCED_CANDIDATES_INSTALL04_INTENT01.json');ok(h(read(C/'COALESCED_CANDIDATES_INSTALL04_ACTUAL_TOOL_EXIT01.json')).startswith('f4a073f0'),'supplied actual exit prefix');ok(exit['actual_tool_exit']==0 and exit['actual_tool_chunk']=='59fe54' and exit['observed_receipt']['sha256']==h(read(C/'COALESCED_CANDIDATES_INSTALL04_OBSERVED01.json')),'actual Root tool exit receipt');ok(intent['actual_review_sha256']==h(read(A/'MACHINE01.json')) and intent['install_protocol_sha256']==h(read(A/'INSTALL_CANDIDATES01.json')) and intent['actual_root_pid']==observed['actual_root_pid']==1110756,'actual installation intent/observed join');ok(observed['actual_tool_exit'] is None and observed['numerical_or_claim_started'] is False and not Path('/proc/1110756').exists(),'original unknown/tool separate and actual installerPID absent')
manifest=J(O/'MANIFEST01.json','f6326fbf10f76c378f4070d7be91c2c4013d58dc2a0c64ca7e0da11cade56d6d');rows={x['path']:x for x in manifest['members']};ok(len(rows)==len(manifest['members'])==66,'exact66 unique sealrows');namespace={};logical=0;allocated=O.lstat().st_blocks*512
for root,ds,fs in os.walk(O,followlinks=False):
 for n in ds+fs:
  p=Path(root)/n;rel=p.relative_to(O).as_posix();s=p.lstat();ok(s.st_uid==os.getuid() and (stat.S_ISDIR(s.st_mode) or stat.S_ISREG(s.st_mode)),'actual owner/ordinary type');namespace[rel]=sig(s);allocated+=s.st_blocks*512
  if stat.S_ISREG(s.st_mode):logical+=s.st_size
ok(set(namespace)==set(rows)-{'.'}|{'MANIFEST01.json'} and len(namespace)==66,'exactactual66children no omitted/extras');ok(namespace==observed['actual_final_namespace']['members'],'actual postinstall retained fingerprints');ok(sig(O.lstat())==observed['actual_final_namespace']['root_signature'],'actual postinstall root signature')
for n,x in rows.items():
 p=O/n;s=p.lstat();ok(stat.S_IMODE(s.st_mode)==x['mode'],'exact manifested mode')
 if x['kind']=='file':ok(len(read(p,x['sha256']))==x['bytes'],'all actual outerseal bytes')
 else:ok(stat.S_ISDIR(s.st_mode),'actual seal directory')
for n,s in before['whole_signatures'].items():ok(namespace[n]==s,'all63 original signatures preserved')
ok(sum(x['kind']=='file' for x in rows.values())==61 and logical==1469655 and allocated==1622016,'actual62files logical/allocated');space=os.statvfs(O);ok(space.f_bavail*space.f_frsize>=10737418240,'actual10GiB floor');machine=J(O/'MACHINE01.json');ok(machine['source_commit']=='7b056a574e3e7b3c7ba209a39ee6a615e649d60c' and machine['new_source32d_recovery'] is False and machine['final_parent_recovery'] is False,'honest original7b scope');ok(J(O/'DRAFT_LAYOUT01.json')['actual_root_exit'] is None,'draftoriginal NULL retained')
source=read(P/'copy_layout01.py','fcadbfcde1bf9d9d61887af27de2dff610b5d7cce188a4cb77da1c99d6989fda');M=types.ModuleType('actual_pinned_components');M.__file__=str(P/'copy_layout01.py');exec(compile(source,M.__file__,'exec'),M.__dict__);PC=M.PC;ok(h(M.PRECLAIM_BYTES)=='557b7bcb38b48e3bf1e9e5b5b1eae25ab4908b8567820e17700dc08774b48d16','unchanged actual preclaim557');gate=J(CAP/'fixture_inputs/financial_wrapper_compatibility01/gates.json','e1846c9fbd5d1964c867c9c7027e3e9a6009520c07841ed720c035374dbeb806');registered=gate['experiments']['financial-wrapper-classification-eager-complete100-compatibility-20261004-01']['inputs'];r=PC.Reader();inputs=PC.Inputs(CAP,registered,r);policy=inputs.json('operational_source_compatibility');draft=J(O/'DRAFT_LAYOUT01.json');refs={'review_'+k:v for k,v in draft['review_reference_candidates'].items()}
for key,n in [('proof','ORIGINAL_RECOVERY_PROOF01.json'),('machine','MACHINE01.json'),('report','REPORT01.md'),('manifest','MANIFEST01.json')]:refs['recovery_'+key]={'path':str(O/n),'sha256':h(read(O/n))}
review=PC._proof_bundle('review',refs,inputs,policy,r);recovery=PC._proof_bundle('recovery',refs,inputs,policy,r);ok(review['decision']=='ACCEPTED_EXACT_CONCRETE_POLICY_ONLY' and recovery['decision']=='ACCEPTED_ACTUAL_OPERATIONAL_SOURCE_POLICY_BYTE_RECOVERY','genuine both actual proofbundle components');r.finish();ok(r.total<=8388608,'bounded actual componentReader total');ok(len(recovery['recovery_receipts'])==38 and all(Path(x['path']).is_relative_to(O) for x in recovery['recovery_receipts']),'all38 real outerroot receipt joins');ok(not (CAP/'research_runs/financial-wrapper-classification-eager-complete100-compatibility-20261004-01').exists(),'fresh claim remains absent')
for p,x in list(reads.items()):ok(h(read(Path(p)))==x['sha256'],'final readbackbody join')
for n,s in namespace.items():ok(sig((O/n).lstat())==s,'finalwhole currentness')
result={'checks':len(checks),'actual_root':str(O),'installed_pins':{n:plan['candidate_files'][n]['sha256'] for n in plan['candidate_files']},'actual_intent':intent,'actual_observed_sha256':h(read(C/'COALESCED_CANDIDATES_INSTALL04_OBSERVED01.json')),'actual_exit':exit,'actual_exit_sha256':h(read(C/'COALESCED_CANDIDATES_INSTALL04_ACTUAL_TOOL_EXIT01.json')),'full_typed_rows':66,'actual_regular_files':62,'old63_signatures_preserved':True,'review_bundle_passed':True,'recovery_bundle_passed':True,'actual_component_reader_bytes_including_finish':r.total,'actual_external_refs':refs,'registered_inputs':11,'actual_recovery_receipts':38,'logical_bytes':logical,'allocated_bytes':allocated,'current_signatures':namespace,'read_bodies':reads,'Admission_created':False,'Run_created':False,'full_preclaim_executed':False,'final8MiB_fit':None,'numerical_authority':False};(D/'READBACK01.json').write_text(json.dumps(result,indent=2)+'\n');print(len(checks),r.total)
