The actual committed source and genuine read-only admission are accepted within this review scope. Current and design source32d57eac5ea14435cd9d4aeb3e3b04d98bf16c41 is a single-parent direct descendant of7b056a574e3e7b3c7ba209a39ee6a615e649d60c. Its diff adds exactly the fifteen previously released input/gate paths, with no modification or deletion. All355 tracked bodies match the committed tree, the index and tracked worktree are clean, and all354 declared source pins match both disk and Git. The eleven roles, original twelve gate definitions and exact new reference identity/parent-null topology remain intact.

All605 non-Git members have exactly the durable signatures captured by the immediately preceding outcome review, including owner/mode/inode/size/mtime/ctime, and every prior body hash was rechecked. All394 original logical Git objects remain reachable and identical. The resulting reachable closure has407 objects, comprising13 additional logical objects; fifteen added files do not imply fifteen distinct new blobs because content can reuse an existing object. All407 object IDs were reconstructed from their genuine type, length and bytes. There is no claim of remote recovery of this new source commit.

The original three failed identities, claims and failure hashes remain unchanged; no complete marker or fresh compatibility claim exists. Highest claimed cumulative allowance remains19 and spent attempts remain3. The newly committed20 amendment remains prospective. The original checkpoint bodies were hashed opaquely and preserved through the prior605 comparison, with no checkpoint decode or empirical evaluation.

Root's actual read-only CLI receipt dcbef49b is joined to its raw stdout8982989e and empty stderr, actual child exit0, exact source/registration/experiment command and current capsule. Its output reports metadata_admitted, ready true, empirical_inputs_opened false and run_started false. Parent file-size limits are explicitly inheritance evidence rather than a separate child-limit readback. This review does not invent that missing child readback.

An independent genuine job._admitted call also succeeded under the pinned interpreter, with actual Admission type, ready true and the exact committed source. A Python import finder rejected numerical-library imports; an audit hook rejected filesystem writes/mutations while permitting already-open real pipe descriptors used for finite Git input. No Run or Owner was created or started. Every loaded tradingagents module originated from the capsule and its body was rehashed. The source closure contains195 installed source bodies; job.required_sources contains150 package bodies, of which142 are directly in onchain_replication. The runtime checks authenticated Python3.13.13, the interpreter/lock mapping and251 installed distribution RECORD and METADATA origins. RECORD validation does not rehash all installed dependency bodies or establish their external recovery.

The original integration harness incorrectly rejected the writable end of an existing subprocess pipe; its raw traceback and empty output remain. The successor allows only an already-open descriptor whose actual fstat type is FIFO, while ordinary filesystem write attempts remain denied. A second review-harness assertion confused the142-file subpackage,150-file required package and195-file installed closure; the source and traceback remain, with corrected independent cardinalities in the final check. No product source, old artifact or registration changed for either correction.

The final postcommit readback passed9816 assertions and retained exact paths, signatures and all407 logical object hashes. These are sampled read-only observations, not atomic exclusion of concurrent writers, full-capacity proof or a numerical result. The source-only compatibility policy and recovery proofs are retained, but job._admitted does not replace the separate complete final metadata preclaim checker. Final8MiB evidence budget, unresolved final references, caller/Parent recovery and native eligibility remain outstanding. No numerical, claim or further live mutation authority is granted. Timing leakage, return/cashflow/exposure, fees/funding and predictive performance were not tested because this task concerns source/runtime/admission metadata only.
