# Final source/runtime bridge — pending actual installed evidence

The actual current source/design32d57eac, all354 source pins/355 tracked names,11 registered inputs,195 implementation paths, Parent424f/e757 and seven helpers match. The audit authenticated actual interpreter/lock and251 RECORD bodies with their direct installed METADATA names/versions. Package bodies were not fully rehashed; no scientific package was imported and no Admission was constructed. Actual original read-only admission dcbef49 and independent review62b5/da5, Parent source reviewfaaa/dc438 and local capture435b/4a21 are literal evidence.

The metadata proof required by Parent is an object containing compatibility_preclaim_external_refs, an exact eight-key mapping: review_proof/review_machine/review_manifest/review_report and recovery_proof/recovery_machine/recovery_manifest/recovery_report. Each value is the exact canonical path and lowercase SHA256 pair. The four review refs name Root's actual nested concrete-policy original files, with original proof/MACHINE/REPORT/MANIFEST bytes and modes. The recovery proof remains actual ORIGINAL_RECOVERY_PROOF01 c5cf. The final three refs must name Root's installed independent candidate39a9/e6f6/f632 bodies, not merely files in the reviewer's candidate directory. Those destinations were absent during the draft measurement, so no accepted source proof was emitted.

The genuine source helper's Inputs/Reader/_proof_bundle/_sealed components were exercised on current literal metadata without a fake Admission. The exact policy bundle passed, and missing/null/hash-mutated references refused. Distinct paths containing identical c5 bytes remain separately charged; only actual shared canonical paths coalesce. The original Reader's physical first pass plus finish reread measured7,959,734 bytes across256 known unique paths. Including the current117,551-byte draft twice projects8,194,836 bytes. The frozen candidate trio adds56,094 charged bytes:8,250,930 before source metadata proof, actual full-recovery proof, final release and final-request size growth. Remaining137,678 charged bytes is a finite allowance for those unknown body sizes, not a preclaim success.

The bridge independently verifies full installed typed membership and exact different-author candidate seal before creating a compact source metadata proof. It cannot install Root evidence, alter a gate, create a claim or launch. The final actual-request inventory tool refuses the genuinely missing REQUEST_FINAL01 today. When actual final bodies exist, it can read all exact unique paths through the unchanged8MiB Reader including finish, with original final release hashes and both proof bundles. This remains a byte-read inventory, not the public genuine Admission/preclaim or native eligibility call.

Source proof references do not include their own hash or the final request hash. The final request references the source proof and all three Parent proofs; the final release hashes the request excluding final_review. Actual REQUEST_FINAL01's hash is separately supplied to Parent. This resolves the reference cycle without dropping fields or body evidence. Root's original outer source/Git/runtime/native checks are additional work outside the preclaim8MiB counter; they are not hidden inside this measurement.

The original bridge01 harness used unprefixed layout review keys and failed before inventory/proof output. Source, stderr and correction are preserved. The final-request missing-file refusal is expected and retained separately. No capture, restore, external transfer, numerical execution, Owner/Run/Binding or actual public preflight occurred. Old three FAILED identities/highest19, new prospective20 and all scientific method/tolerance bodies remain unchanged.
